### ISSUE TITLE
Result of select depends on order of arguments

### ISSUE THREAD

**Issue by maximyurchuk** [bazelbuild/bazel#10042]
### Description of the problem / feature request:
Result of `select` invocation depends on order of arguments (in some cases). 

### Feature requests: what underlying problem are you trying to solve with this feature?
Trying to use selects. Actually problem appeared while trying to use bazel_skylib. Example below is minimal example without bazel_skylib.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Consider following code:
```
package(default_visibility = ["//visibility:public"])
load(":rule.bzl", "my_rule")
 
 
config_setting(
    name = "foo",
    define_values = {
        "foo": "1"
    }
)

config_setting(
    name = "bar",
    define_values = {
        "bar": "1"
    }
)


alias(
    name = "foo_bar",
    actual = select({
        ":bar": ":foo",
        "//conditions:default": ":bar",
    }),
)


my_rule(
    name = "check1",
    input = select({
       ":foo": "1111",
       ":foo_bar": "2222",
    })
)

my_rule(
    name = "check2",
    input = select({
       ":foo_bar": "2222",
       ":foo": "1111",
    })
) 
```

And bazel invocation:
```
c:\git\bazel-issues\select_order>c:\bazel\bazel-1.0.0-windows-x86_64.exe build  --define foo=1 --define bar=1 //:all
INFO: Writing tracer profile to 'C:/users/yurchuk/_bazel_yurchuk/vpuf7p3a/command.profile.gz'
DEBUG: C:/git/bazel-issues/select_order/rule.bzl:3:5: input = 2222
DEBUG: C:/git/bazel-issues/select_order/rule.bzl:3:5: input = 1111
INFO: Analyzed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 3 targets...
INFO: Elapsed time: 0.347s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

Rule `check1` got different `input` attribute than `check2` (`1111` and `2222`). 

[Here](https://github.com/maximyurchuk/bazel-issues/tree/master/select_order) you could find full example. 

### What operating system are you running Bazel on?
Windows 10, x64, 1903

### What's the output of `bazel info release`?
```
c:\git\bazel-issues\select_order>c:\bazel\bazel-1.0.0-windows-x86_64.exe info release
INFO: Writing tracer profile to 'C:/users/yurchuk/_bazel_yurchuk/vpuf7p3a/command.profile.gz'
release 1.0.0
```

Also issue reproduces on master branch (c731933e93c19b5e70275e4f4ae2e7da90fa3a32, Fri Oct 11 15:45:20 2019 -0700)

**Comment by gregestren** [comment]
This is very surprising. `select` should fail outright if more than a single condition matches: https://docs.bazel.build/versions/master/be/functions.html#select. I'll go dig in...

**Comment by maximyurchuk** [comment]
@gregestren please take a notice: 
```
If multiple conditions match and one is a specialization of the others, the specialization takes precedence.
```
-- maybe this rule take place here. Because foo_bar is "True" if and only if foo=1 and bar=1.

**Comment by gregestren** [comment]
This is a gap in the logic between `select` and `alias`:

```python
my_rule(
    name = "check1",
    input = select({
       ":foo": "1111",
       ":foo_bar": "2222",
    })
)
```
short-circuits `select`s normal logic of checking that multiple conditions can't match because it resolves the alias to `foo`, which produces 

```python
my_rule(
    name = "check1",
    input = select({
       ":foo": "1111",
       ":foo": "2222",
    })
)
```

which `select` sees as the same condition matching twice (in which case it arbitrarily chooses one instance, which also isn't good).

The specific faulty logic is at https://github.com/bazelbuild/bazel/blob/706d75b172dba318a9fecc106fa15b6d01eb21c1/src/main/java/com/google/devtools/build/lib/packages/ConfiguredAttributeMapper.java#L166-L167 and https://github.com/bazelbuild/bazel/blob/706d75b172dba318a9fecc106fa15b6d01eb21c1/src/main/java/com/google/devtools/build/lib/packages/ConfiguredAttributeMapper.java#L172 
`matchingConditions` is a hash table that treats both `config_setting` `foo` and `alias` `foo__bar` as the same key.

We can fix this (and properly consider the above an error) by distinguishing them. I have an upcoming PR that does that.
