### ISSUE TITLE
Support run under label with `bazel run`.

### ISSUE THREAD

**Issue by drew-gross** [bazelbuild/bazel#10060]
### Description of the problem / feature request:

It says in the [docs](https://docs.bazel.build/versions/0.26.0/user-manual.html#flag--run_under_run) that `bazel run` with `--run_under` does not support labels, while `bazel test` does. E.g. `bazel test --run_under=//tools:my_inspector //some:test` is expected to work while `bazel run --run_under=//tools:my_inspector //some:binary` is not. This is a feature request to add support to labels when using `bazel run --run_under`. (we have noticed that doing it today does work sporadically - it seems that doing `bazel run //tools:my_inspector` first causes the `--run_under` invocations to succeed)

### Feature requests: what underlying problem are you trying to solve with this feature?

We have a number of tools that launch another process with a wrapper. For example, we have `//tools:flamegraph` which, which used with `bazel test --run_under="//tools:flamegraph" //some:test` will produce a flamegraph of the target. It would be convenient if this also worked for `bazel run`, so that a single command can build the flamegraph tool, build the binary being inspected, and then run them.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

N/A

### What operating system are you running Bazel on?

Linux (Ubuntu 4.15)

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.26.1-cruise-118fa1a
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

The docs linked above

### Any other information, logs, or outputs that you want to share?

N/A

**Comment by lberki** [comment]
I'm having trouble reproducing this. The code says that this should work:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommand.java#L233

And testing this by:

```
touch WORKSPACE
cat > BUILD <<EOF
sh_test(
    name = "t",
    srcs = ["test.sh"],
)

sh_binary(
    name = "b",
    srcs = ["b.sh"],
)
EOF

cat > test.sh <<EOF
#!/bin/bash

echo I am Test
EOF

cat > b.sh <<EOF
#!/bin/bash

echo I am Binary "$*"
exec "$*"
EOF

chmod +x {test,b}.sh
bazel run --run_under=//:b :t --test_output=streamed
```

yields the expected lines from `:b` and `:t`. 

One possible caveat is that you must supply an absolute label to `--run_under` (i.e. one starting with `//` or `@`). This is because that flag (somewhat stupidly in retrospect) can take both paths to pre-existing binaries and labels, and thus it must decide which one it is. For example, `foo` can be both a relative label and a path. In most of the ambiguous cases, the decision will be that it's a path (and if it is, the designated target will not get built):

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/config/RunUnderConverter.java#L47

Maybe that's what trips you up?

**Comment by drew-gross** [comment]
I'm not familiar with all the functions being called [here](https://github.com/bazelbuild/bazel/blob/bd0a40254697ec7e0cd9a522cf5ba282ea76389c/src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommand.java#L242-L243) but it doesn't seem to be building the `--run_under` target, which would match the behaviour I've seen where the `--run_under` works if you have already built the target you are running under.

Maybe I'm wrong though, and the docs just need an update to reflect the fact that is now expected to work. FWIW in our case the actual target we are running is also a binary and not a test (otherwise I would probably just use `bazel test`), which is different from your example, though I wasn't able to repro my original issue just by changing `sh_test` to `sh_binary`.

I definitely am using `//` when I attempt to `--run_under`, so using non-absolute labels isn't the problem.

**Comment by lberki** [comment]
You mean it's *not* (and not "now") expected to work?

Building the `--run_under` target is requested here:

https://github.com/bazelbuild/bazel/blob/bd0a40254697ec7e0cd9a522cf5ba282ea76389c/src/main/java/com/google/devtools/build/lib/runtime/commands/RunCommand.java#L289

If you can come up with a reproducible instance where the `--run_under=` target starts with `//` or `@` and it doesn't get built, I'd be very interested because both by code reading and my experiments show that that should not be possible. The "works when I build the target before" phenomenon is a strong hint that that's happening, but I can't figure out why or reproduce it :(

**Comment by drew-gross** [comment]
No I mean "now", the [docs](https://docs.bazel.build/versions/master/user-manual.html#flag--run_under_run) currently say "This has the same effect as the --run_under option for bazel test (see above), except that it applies to the command being run by bazel run rather than to the tests being run by bazel test and **cannot run under label**." If it can now run under label, probably that **cannot run under label** line can just be removed.

The issue repros only sporadically in our large repo, I haven't been able to make a reduced test case yet.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
