### ISSUE TITLE
toolchain '@local_config_cc//:cc-compiler-x64_windows' is not found

### ISSUE THREAD

**Issue by hevrard** [bazelbuild/bazel#10086]
### Description of the problem / feature request:

When compiling gapid (http://gapid.dev), updating from bazel 0.26.0 to any version between 0.27.0 and 1.0.0 leads to the following error:

```
ERROR: C:/users/builder/_bazel_kbuilder/fsjplg7y/external/bazel_tools/tools/cpp/BUILD:58:1:
Target '@bazel_tools//tools/cpp:malloc' depends on toolchain
'@local_config_cc//:cc-compiler-x64_windows', which cannot be found: no such target
'@local_config_cc//:cc-compiler-x64_windows': target 'cc-compiler-x64_windows' not declared
in package '' defined by C:/users/builder/_bazel_kbuilder/fsjplg7y/external/local_config_cc/BUILD.bazel'
```

The project can currently compile with bazel 0.26.0, but any version from 0.27.0 to 1.0.0 leads to this error. In 0.27.0 release notes, I noticed the following:

> Repository containing autoconfigured C++ toolchain @local_config_cc has been
> split in 2 - see local_config_cc_toolchains

But I cannot manage to find any documentation on local_config_cc_toolchains?

GAPID uses a mingw toolchain for c++ on Windows, see details here:
https://github.com/google/gapid/blob/master/tools/build/cc_toolchain.bzl
Could this be perturbating Bazel?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to compile this PR with Bazel 1.0.0 on Windows: https://github.com/google/gapid/pull/3243

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

bazel 1.0.0

###  Have you found anything relevant by searching the web?

There is basic documentation on c++ toolchain setup, but I can't find a way to fix the above error.

**Comment by hlopko** [comment]
Hi @hevrard,

Yup I see where the problem is. It is indeed in your use of `local_config_cc`. The commit you correctly identified split the `local_config_cc` repository and added `local_config_cc_toolchains`. That toolchains repo is a preparation for https://github.com/bazelbuild/bazel/issues/7260. The problem is that since ~ 0.24, we select a C++ toolchain using `cc_toolchain_suite`, but also using toolchain resolution. By default we pick the former, but #7260 makes Bazel pick the latter.

Now since you override `local_config_cc`, but you don't override the toolchains repo, targets in the toolchains repo point to targets in `local_config_cc` that don't exist. There are 2 possible fixes:

1. Also override `local_config_cc_toolchains`, produce empty BUILD file there (or produce a valid toolchain target for your msys toolchain).
2. Add the missing target, use alias and point it to your msys toolchain. This way your toolchain will work with both `cc_toolchain_suite` and toolchain resolution. This is the place where we generate the toolchain target:
https://source.bazel.build/bazel/+/351302a2b7c03d135347c08defa2266a12bfd67c:tools/cpp/BUILD.toolchains.tpl;l=3

To acknowledge, my change was a breaking change that I got away with (it's too late now to introduce an incompatible flag for it now).

Let me know if this explanation doesn't make sense.
