### ISSUE TITLE
Dart rules

### ISSUE THREAD

**Issue by jjangga0214** [bazelbuild/bazel#10207]
Though this repo might not be responsible for rules request, I'd like to suggest official Dart support. 
Google invented Dart, and it's been heavily investing in Flutter, which makes enough sense to make official Dart rules.

**Comment by laurentlb** [comment]
Related discussions:
- https://groups.google.com/d/msg/bazel-discuss/SnXvMgAUGzI/WAN7R0S2BwAJ
- https://github.com/flutter/flutter/issues/19680
- https://github.com/flutter/flutter/issues/14125

Dart rules should be developed in a separate repository, like other rules. While I'd love to see Dart rules, I can't guarantee that someone will volunteer to write them.

I'll close this bug because it's not actionable for the Bazel team. If someone wants to start working on this, I'd like to hear about it. I can help advertize it.

**Comment by cbracken** [comment]
Copying my note from https://github.com/flutter/flutter/issues/14125:

If someone were interested in writing and maintaining a set of Bazel rules for Dart, it's probably not a too a massive undertaking if you were to build on top of https://github.com/cbracken/rules_dart. 

FWIW those rules formed the initial base for a rewrite of Dart support internally when Skylark/Starlark came along and I started extracting the original hardcoded Dart & Dart proto support out of Blaze and into something more portable. The internal rules are now far more complex and cover a bunch of scenarios that don't matter outside our internal codebase, but these are still a pretty functional starting point. There's a branch with proto support which I haven't updated in years -- at the time I wrote it, our internal baseline (non Dart) proto support hadn't yet landed in Bazel, so that branch probably needs a ton of updating but it's also probably a reasonable base if you need proto support.

I can't promise to support those rules more than on an ad-hoc basis which is why I haven't done the work to upstream them to a Bazel reposity myself, but if someone does have the time to do it, feel free to use those as a starting point. I'm pretty fluent with Bazel and happy to comment/review, even if I can't promise quick turnaround. It's certainly within my sphere of interest :)
