### ISSUE TITLE
Bazel CI: Flip --incompatible_remap_main_repo broke many projects in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#10246]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1281

Culprit finder points to 81b57d605de823f8e6f846a06d8e50d9a00041e3
https://buildkite.com/bazel/culprit-finder/builds/236
https://buildkite.com/bazel/culprit-finder/builds/235

**Comment by meteorcloudy** [comment]
Ping @aehlig , Should we revert the flip or disable all broken downstream projects?
/cc @dslomov

**Comment by aehlig** [comment]
> Ping @aehlig , Should we revert the flip or disable all broken downstream projects?

For `rules_go` I'm pretty sure the breakage is due to the implicit assumption in that repository that every artifact path generated by bazel starts with `external/`. So there, it is the downstream project at fault.

For `rules_rust` I still haven't managed to find out what the root cause of this breakage is. So I still cannot tell, if flag flip uncovered a bug in `rules_rust` or in `bazel` (but, on the other hand, #3115 and #7180 are bugs in bazel as well).

**Comment by laurentlb** [comment]
If project maintainers should fix the code or take a look at the issue, please file bugs.

**Comment by aehlig** [comment]
Filed issue for `rules_go`. Again, for `rules_rust` it is not clear in which code (`bazel` or `rules_rust`) the underlying issue is.

**Comment by aehlig** [comment]
Corresponding issues and/or pull requests have been filed.
