### ISSUE TITLE
Query @sub//... of local_repository fails because of including @sub//bazel-subdir/

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#10255]
### Description of the problem / feature request:

Consider two repositories, `toprepo` which uses `subrepo`. `subrepo` is buildable of its own, which means that `subrepo-checkout-dir/bazel-subrepo-checkout-dir` will exist. When working in `toprepo`, `bazel query @subrepo//...` will fail when traversing `@subrepo//bazel-subrepo-checkout-dir`.

### Feature requests: what underlying problem are you trying to solve with this feature?

By solving #7093 and #9080, it would be possible to add `bazel-*` to `subrepo/.bazelignore` and therefore avoid the problem. I will ignore `bazel-*` in all my future repositories, so consider adding `bazel-*` as a default built-in ignore.

Alternatively, teach `local_repository` to suppress `bazel-*` folders or limit the suppression to `bazel-{bin,out,testlogs}` and `bazel-<dirname>`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
mkdir subdir
touch subdir/WORKSPACE
cat > WORKSPACE <<EOF
local_repository(
    name = "subrepo",
    path = "subdir",
)
EOF

(cd subdir && bazel build @bazel_tools//tools/build_defs/hash:sha256)
bazel build @subrepo//...
```
results in
```
ERROR: error loading package '@subrepo//bazel-subdir/external/bazel_tools/tools/python/runfiles': Every .bzl file must have a corresponding package, but '@subrepo//tools/python:private/defs.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
INFO: Elapsed time: 0.712s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (9 packages loaded)
    currently loading: @subrepo//bazel-subdir/external/bazel_tools/tools/python
```

### What operating system are you running Bazel on?

Linux (Ubuntu)

### What's the output of `bazel info release`?

`release 1.1.0`

**Comment by SilverTux** [comment]
Hi,

We have faced an issues similar to this and we figured it out that the problem is the `bazel build ...:all` command. What `...` will do is recursively find bazel stuff in the current and child directories. Your first command `bazel build @bazel_tools//tools/build_defs/hash:sha256` will create symlinks inside the subdir which will point to /home/user/.cache/... dir. I don't remember where but I've read somewhere that you shouldn't run bazel command inside that directory.
The solution is to use absolut references insted `...`.

Best regards,
SilverTux
