### ISSUE TITLE
depset hashability requirement is a breaking change

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#10289]
bbde22993476d5265baadba022be35852c5101d7 made the `depset` constructor reject non-hashable element types. However, users may be currently relying on being able to put immutable but not hashable elements in depsets. The one I ran into is `TransitiveInfoCollection` (aka Starlark's `Target`).

**Comment by laurentlb** [comment]
Thanks.

This has been reverted with https://github.com/bazelbuild/bazel/commit/dafd2345e0220e26ab85fe1bd0a104ee6b257ded.

**Comment by alandonovan** [comment]
To clarity, my original change had two effects, one significant, one not:
First, it changed the element validity check from "is immutable" to "is hashable". This change does affect change the error message, but is otherwise relatively minor.
Second, it copied the element validity check current applied to the `depset([x])` constructor to the `depset(direct=[x])` constructor as well. This fixed a bug that existing programs currently exploit, and is thus a breaking change.

**Comment by laurentlb** [comment]
The `direct` argument is deprecated and will be removed. See `--incompatible_disable_depset_items` (https://github.com/bazelbuild/bazel/issues/9017).

**Comment by benjaminp** [comment]
Isn't it `items` that will be removed not `direct`? (Presumably I wouldn't have come to rely on this behavior if I hadn't already done the #9017 migration.)

**Comment by laurentlb** [comment]
Oops, sorry, you're right.

**Comment by alandonovan** [comment]
Google issue number: b/144992997

**Comment by laurentlb** [comment]
This is fixed, as far as I know.
