### ISSUE TITLE
nullable final field refinement

### ISSUE THREAD

**Issue by cushon** [bazelbuild/bazel#10326]
Would it be safe to refine the type of the field to non-null in the lambda (similar to #266), given that it is `final`?

```java
import org.checkerframework.checker.nullness.qual.Nullable;

public class T {
  private final @Nullable String f;

  T(@Nullable String f) {
    this.f = f;
  }

  void test() {
    if (f == null) {
      return;
    }

    Runnable r =
        () -> {
          System.err.println(f.toString());
        };
  }
}
```

```
./checker-framework-3.0.0/checker/bin/javac -processor Nullness T.java
T.java:17: error: [dereference.of.nullable] dereference of possibly-null reference f
          System.err.println(f.toString());
                             ^
1 error
```

**Comment by wmdietlGC** [comment]
@cushon Did you mean to file this with typetools/checker-framework?

https://github.com/typetools/checker-framework/issues/266 and
https://github.com/typetools/checker-framework/issues/1248 are marked fixed and I would have expected your example to work.

When using an anonymous class for `r` the checker is happy. It also works when instead of a final field one uses a parameter.
I'll look into why this doesn't work for lambdas & final fields.

**Comment by comius** [comment]
@cushon Can this be closed?
