### ISSUE TITLE
Bazel crashes on Windows 10 while evaluating node `REPOSITORY_DIRECTORY:@local_config_cc` [duplicate of #10096]

### ISSUE THREAD

**Issue by LakatosI** [bazelbuild/bazel#10331]
### Description of the problem / feature request:

Bazel 1.2.1 crashes in Windows 10 while evaluating node `REPOSITORY_DIRECTORY:@local_config_cc`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Bazel 1.2.1 accessible from PATH.
> mkdir test
> cd test
> touch WORKSPACE
> bazel sync

### What operating system are you running Bazel on?

> Windows 10 Pro 1909

### What's the output of `bazel info release`?

> release 1.2.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Not a git repository

###  Have you found anything relevant by searching the web?

> No

### Any other information, logs, or outputs that you want to share?

> Visual Studio 2017 Version 15.9.16 installed.
> Stack trace is attached to issue. 
[stacktrace.txt](https://github.com/bazelbuild/bazel/files/3902194/stacktrace.txt)

**Comment by laszlocsomor** [comment]
Which shell do you run Bazel from?

Does it help if you set `BAZEL_VC`? (https://docs.bazel.build/versions/1.2.0/windows.html#build-c-with-msvc)

**Comment by laszlocsomor** [comment]
Also, please set `CC_CONFIGURE_DEBUG=1` and paste the output here. That'll print extra debug info, that hopefully reveals why you get a bad path.

**Comment by laszlocsomor** [comment]
Looks the same as https://github.com/bazelbuild/bazel/issues/10096

**Comment by laszlocsomor** [comment]
This might have been fixed by https://github.com/bazelbuild/bazel/commit/56568045c27285d54b52106486134efed31834bd

Could you please try something?
1. Download the latest nightly build of Bazel:
https://buildkite.com/organizations/bazel/pipelines/bazel-at-head-plus-downstream/builds/1296/jobs/21114830-c84d-4b57-a12f-b9d6ee1c4537/artifacts/397a5762-5537-466a-b1f9-893c8ce73d1d
2. Rename the downloaded file "bazel-dev.exe"
3. Run any build with that "bazel-dev.exe" -- does this fix the issue?

**Comment by LakatosI** [comment]
I apologize for the late reply. The issue is indeed fixed in the nightly build of Bazel. My projects successfully build.
