### ISSUE TITLE
Allow querying for "all targets in all repositories"

### ISSUE THREAD

**Issue by brian-peloton** [bazelbuild/bazel#1034]
The wildcard `//...` gets all of the rules in the main repository, but it doesn't get ones in other repositories. It would be useful to easily run all tests, including those in other repositories and be able to run queries over everything.

**Comment by nathantchan** [comment]
What's the status of this? Was it added to 0.7?

**Comment by schroederc** [comment]
Any update on this?

**Comment by leosh64** [comment]
Is there any progress on this issue?

**Comment by janakdr** [comment]
I don't think "all repositories" is well defined, is it? Is your issue that `bazel query //...` doesn't return rules from other repositories that it depends on? `bazel query 'deps(//...)'` will return all rules from all repositories that the main repository depends on. What do you want beyond that?

**Comment by bsilver8192** [comment]
I think "all targets in all repositories in `deps(//...)`" is well-defined, which is what I'm looking for (I opened this issue, with an account created for a previous employer). One solution would be a query operator similar to `siblings`, but for the same _repository_, not just the package.

**Comment by janakdr** [comment]
Ah, I understand now that you want targets coming from repositories that are needed by the main repository but not necessarily needed themselves. Yes, that isn't supported. But is there a reason you'd want it? Do you care if someone else's external repository has a broken target? I guess maybe it's actually under your control, just split off?

**Comment by bsilver8192** [comment]
That's one case. I have several libraries which aren't "mine", but they are checked into my source tree (generally with git-subtree, to keep track). They are set up as external repositories for bazel via local_repository with a relative path. These libraries often have local modifications which are in the process of being sent upstream and/or backports of upstream changes on top of the last release I imported. It would be nice to run the tests for all of those, without having to maintain an explicit list of target patterns for CI with all of them, and remembering to update that list.

The other case is just wanting to run tests of external code I didn't modify, with my toolchains and target systems. I've found bugs in external libraries and compilers that way.

**Comment by aiuto** [comment]
If you are using your own WORKSPACE file instead of the one that the other repo uses _as its developement WORKSPACE_ then the test results are not meaningful. Some repos use a large WORKSPACE for development but ship the tarball with a smaller workspace and no dependencies. One might do this so they can depend on stardoc for creating their documentation, but don't want to make their users also depend on stardoc.

The only tests faithful to the repo you have vendored in like this is to move under that workspace and run the test from there, so it picks up the correct repository setup.

**Comment by bsilver8192** [comment]
@aiuto I disagree actually. I know my WORKSPACE may be different, but I want to run the tests with the versions of transitive dependencies I'm using, to test the library as I'm using it. I agree they may not have the same meaning as the library author intended, but if that is the case, I would really like to know because it could mean the library as I'm using it is broken. I understand I may need to add WORKSPACE entries just to run tests, or possibly exclude targets from certain external repositories if they have dependencies which aren't worth dealing with.

I'm aware that doing this means interacting with libraries in a way their authors don't intend users to do. However, I think one of the big strengths of vendoring dependencies is how a natural the transition from "user" to "contributor" is.

I would like something in the query language to at least let me look at what all the tests I could choose to run are.

**Comment by bsilver8192** [comment]
I just found https://docs.bazel.build/versions/master/query.html#external-repos, which gets close.

**Comment by konste** [comment]
Another example when querying across workspaces is needed: we have primary workspace which pulls in hundreds of external workspaces (external Git repos). I have to maintain a large set of custom Bazel rules used across those workspaces. When I need to do some work, like refactoring,  on specific Bazel rule I first need to see 1. If the rule is actually used anywhere and 2. If it is then how exactly it is used, so I need to look at all the places the rule is instantiated, even if it is outside of dependencies of the primary workspace. So I literally need the list of all rules from all workspaces. I know how to get all workspaces: //external:* now I need to be able to query their combined scope.

**Comment by jin** [comment]
As a current workaround, whenever I need to do something across external workspaces, I'll first do a query on `//external:all` to get the name, and then munge it into more bazel commands after. 

e.g. this snippet is from https://github.com/bazelbuild/rules_jvm_external/pull/411, where I'm running a script in each external repository, filtering by the repository name pattern:

```bash
#!/usr/bin/env bash
set -euo pipefail

(
    cd $BUILD_WORKING_DIRECTORY
    # TODO: use --ui_event_filters to filter DEBUG lines away when it's in a Bazel release.
    for R in $(bazel query --noshow_progress --noshow_loading_progress //external:all | grep unpinned);
    do
        name=$(echo $R | cut -d':' -f2)
        bazel run @$name//:pin
    done
)
```

I expect that you'll be able to replace `bazel run` with `bazel query`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
