### ISSUE TITLE
Cache management facilities

### ISSUE THREAD

**Issue by cgils** [bazelbuild/bazel#1035]
Please consider adding some way of setting a maximum cache size. At the moment our project's build caches grow unbounded leading to us discarding them periodically.

A facility with which to display cache information would be nice as well. Something like the output of `ccache -s`, for example:

```
  cache directory                     /home/user/.ccache
  cache hit (direct)                 34993
  cache hit (preprocessed)             153
  cache miss                         23479
  compile failed                         3
  ccache internal error                  1
  preprocessor error                     1
  cache file missing                     1
  unsupported source language          382
  no input file                       7322
  files in cache                     70445
  cache size                          16.4 Gbytes
  max cache size                      90.0 Gbytes
```

**Comment by dslomov** [comment]
@cgils, are you talking about project "cache" (it is not really a cache, it is just your output directory) or stuff that gets into ~/.cache/bazel?

**Comment by cgils** [comment]
Stuff that gets put into ```~/.cache/bazel```.

**Comment by glinscott** [comment]
I vote for this to be higher priority :).  Bazel is commonly filling up hard drives on our project from the `~/.cache/bazel` directory growing unbounded.

**Comment by kavehv** [comment]
+1

**Comment by jianga** [comment]
+1

**Comment by jiayiliu** [comment]
+1, esp. if the home dir is on NFS.

**Comment by lefromage** [comment]
+1

**Comment by burnzzz** [comment]
+1

**Comment by softprops** [comment]
+1

**Comment by dahlstrom-g** [comment]
+1

**Comment by mhlopko** [comment]
@buchgr

**Comment by buchgr** [comment]
@jin do you have an idea to which component to assign this issue?

**Comment by jin** [comment]
@buchgr team-Local-Exec sounds like a good fit.

**Comment by edrumwri** [comment]
+1

**Comment by jmmv** [comment]
Per #2765, one more thing to consider if implementing a smarter clean command is `bazel clean //target`. Noting here because this would possibly conflict with the `bazel clean some-id` proposal above.

**Comment by ozio85** [comment]
+1

**Comment by jonatanj** [comment]
+1

**Comment by dchichkov** [comment]
It had been some time since 2016, it'd be great for this to get higher priority.  

To give some context, I'm on 2TB drive and have to keep fighting with Bazel for living space.  My ~/.cache/bazel is consistently eating up to 0.7TB of free space (in 2-3 weeks). I have to purge it then.  And that results in multi-GB downloads (CUDA, etc). 

It'd be great to add a limit and an LRU-type of behavior to the cache.  Alternative - remove "{Fast, Correct} - Choose two"  advertisement from the web page.  Eating all the space on the disk is not correct.  Making a user to purge cache completely is not fast.

**Comment by MilesCranmer** [comment]
This issue should really be P1, not P2. It is extremely bad that on my system there have been nearly a million files generated in the `~/.cache` that aren't automatically cleared.

On many personal computers, people might just not realize this is happening, and have their entire filesystem slowed down due to the additional effort needed by their system to index everything.

Then, on some shared computers where there are hard file limit constraints, bazel is effectively unusable because it generates so many files. (This is the only reason I noticed this in the first place – otherwise I would have just had a slower filesystem without knowing why)

**Comment by Ryang20718** [comment]
+1

**Comment by gosha-frost** [comment]
+1

**Comment by StilesCrisis** [comment]
+1

**Comment by tjgq** [comment]
We acknowledge the problem discussed here; however, for the sake of clarity, I'm going to close this issue in favor of the following narrower-scoped ones:

https://github.com/bazelbuild/bazel/issues/2109
https://github.com/bazelbuild/bazel/issues/5139
https://github.com/bazelbuild/bazel/issues/22515
https://github.com/bazelbuild/bazel/issues/22516

**Comment by dechapon25** [comment]
Dechapon25
