### ISSUE TITLE
@platforms setup flake

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#10397]
### Description of the problem / feature request:

We're occasionally seeing this flake on local and CI builds:

```
ERROR: /private/var/tmp/_bazel_iosci/f749baf807251022363d6bcea6ad530d/external/local_config_platform/BUILD.bazel:4:1: error loading package '@platforms//os': /private/var/tmp/_bazel_iosci/f749baf807251022363d6bcea6ad530d/external/platforms/os/BUILD (No such file or directory) and referenced by '@local_config_platform//:host'
ERROR: While resolving toolchains for target @com_github_bazelbuild_buildtools//buildozer:buildozer: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@platforms//os': /private/var/tmp/_bazel_iosci/f749baf807251022363d6bcea6ad530d/external/platforms/os/BUILD (No such file or directory)
ERROR: Analysis of target '@com_github_bazelbuild_buildtools//buildozer:buildozer' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@platforms//os': /private/var/tmp/_bazel_iosci/f749baf807251022363d6bcea6ad530d/external/platforms/os/BUILD (No such file or directory)
```

Some notes:

- This can happen after running any command, not just at server start
- It isn't always the `os` target that fails, sometimes we see the `cpu` target fail as well.
- It can happen with any target even though this example is buildifier

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

We can't reproduce consistently but it seems to happen with multiple different bazel subcommands

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 1.2.0

**Comment by katre** [comment]
I can't reproduce this, even trying to build 1000 times, on either Linux or Mac.

Command:
```
for i in `seq 1000`; do bazel clean --expunge && bazel build @local_config_platform//:host || break; done
```

(On Mac, I did have a number of problems initially that ended up being caused by my firewall. This was different than your report, however, because it happened every time, not intermittently.)

I suspect your problem is an intermittent networking issue that causes the repository to not be downloaded properly. You may need to add additional system-level network tracing to help you diagnose this, but without more details I don't think there's anything the Bazel team can do to help you.

I'm re-assigning this to you and noting that it needs more information. If you can find out more details I'll be happy to take a further look, but for now I'm not sure there's anything we can do to help you.

**Comment by ob** [comment]
We've seen some of those on partial downloads. Fixed by not depending on external sources :-)

**Comment by keith** [comment]
@katre do you have any idea if this could be masking a download failure as @ob mentioned?

**Comment by katre** [comment]
It's possible but I don't know how to check further. I'm going to re-assign the team and see if this can be better tracked.

**Comment by katre** [comment]
(Also, sorry for the delay on handling this due to the holidays!)

**Comment by laurentlb** [comment]
If someone finds a way to reproduce the issues, that would be useful.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
