### ISSUE TITLE
JavaInfo.transitive_runtime_jars.owner shows proto_library not java_lite_proto_library

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel#10423]
# Description of the problem / feature request:

Following #10422, I'm trying this piece of code to get the transitive export jars
```python
def _get_transitive_exports(library):
    ret = []
    exports = {}
    runtime_jars = library[JavaInfo].transitive_runtime_jars.to_list()
    transitive_exports = library[JavaInfo].transitive_exports.to_list()
    for te in transitive_exports:
        exports[te] = True
    for rj in runtime_jars:
        if exports.get(rj.owner, False) == True:
            ret.append(rj)
    return ret
```

However, this doesn't work because `rj.owner` is always the `proto_library`, and not the `java_lite_proto_library`. So I'm stuck.

For instance:
```
<generated file libmytarget_proto-lite.jar> <> //:mytarget_proto (!= //:mytarget_javalite_proto)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Get the transitive export jars.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

`release 1.2.1`

**Comment by lberki** [comment]
This is WAI. This is because the `owner` of a file is the label of the rule or aspect that generated it. In this case, `java_proto_library()` propagates an aspect over the `proto_library` rules in its transitive closure and the `.jar` file gets generated when the aspect reaches the respective `proto_library` rule. Consider the case when a `.jar` file is generated for two `java_proto_library` rules:

```
proto_library(name="base")
proto_library(name="left", deps=[":base"])
proto_library(name="right", deps=[":base"])
java_proto_library(name="left_java", deps=[":left"])
java_proot_library(name="right_java", deps=[":right"])
```

Then if you want the `owner` to be the label of the `java_proto_library` rule, you couldn't decide whether the owner of `base.jar` should be `:left` or `:right`.

**Comment by steeve** [comment]
Thank you. Is there another way to get the transitive export jars ?

**Comment by lberki** [comment]
Good question! I don't think so :( I think the best would be to add a method that contains the jar files so that you don't have to guess, but we don't have that at the moment. 

What do you need this for? I'm surprised that you need this since you should in principle treat jars from direct dependencies and from transitive exports in the same way.
