### ISSUE TITLE
Bazel 2.0 with breaking changes was released earlier than the promised three-month stability window

### ISSUE THREAD

**Issue by vam-google** [bazelbuild/bazel#10465]
https://blog.bazel.build/2019/06/06/Bazel-Semantic-Versioning.html promises three-month stability window between major version releases.

Bazel 1.0.0 was released on Oct 10, Bazel 2.0 was released on Dec 19, which is 2 month 9 days after. 

For users, who installed bazel as a linux package, it was updated auotmatically right after the release, starting breaking them immediately (in a very frustrating way, since they did not change anything in their projects).

**Comment by jin** [comment]
@dslomov @aehlig

**Comment by philwo** [comment]
Bazel does time-based, monthly releases. Bazel 1.0rc1 was cut in September, Bazel 1.1rc1 was cut in October, Bazel 1.2rc1 was cut in November and Bazel 2.0rc1 was cut in December. We don't count days between releases and artificially hold back a release to fulfil the three month window.

The fact that Bazel 1.0 was released later than expected due to bugs and some polish we wanted to do for this version does not "stop the train" for the following releases, which were cut and released on their expected and planned schedule.

Regarding automatic updates: There are various ways to solve this. I would recommend to use `.bazelversion` files if you require a fixed Bazel version for a specific project. Bazel 2.0 actually has much improved support for this: You can install individual Bazel versions side-by-side with the latest one via `apt-get install bazel-1.2.1`, which install that version as /usr/bin/bazel-1.2.1.

If you then add a `.bazelversion` file to your project: `echo 1.2.1 > .bazelversion`, Bazel's wrapper script that is installed by default as `/usr/bin/bazel` when you `apt-get install bazel` is smart enough to parse this and instead of using the latest, possibly incompatible version of Bazel, uses the /usr/bin/bazel-1.2.1 binary. If that doesn't exist, it prints a helpful message how to install it, tailored to your system.

Hope this helps. As you're a Googler, you might also be interested in checking out b/133690867, where this exact problem was discussed and a solution has been provided.

**Comment by steeve** [comment]
As a regular user, bazelisk is definitely the way to go. Pinning the version of your build tool is a very convenient thing that allows you to set your update schedule as you like.

**Comment by laurentlb** [comment]
Is there any action item here, or shall we close the issue?

**Comment by vam-google** [comment]
@laurentlb Please close it
