### ISSUE TITLE
`singlejar` should preserve Java 9+ features

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#10507]
### Description of the problem / feature request:

In Java 9, there are two important tags added to the jar manifest that change how the module path (not the classpath) is handled. These are `Automatic-Module-Name` (to allow regular jars to define a module name without needing an associated `module-info`) and `Multi-Release` (to indicate that this is a Multi-Release jar) 

At present `singlejar` doesn't copy either of these from the existing manifest. The omission of `Automatic-Module-Name` makes sense to a degree, but precludes `singlejar` from being used to merge `java_library` targets into a single java module without specifying extra options. The lack of `Multi-Release` is more serious, and harder to work around as it may not be obvious to someone adding a jar to the classpath that they are working with a multi-release jar.

**Comment by philwo** [comment]
FYI @cushon, @iirina

**Comment by cushon** [comment]
singlejar supports adding custom entries to the output manifest [1] (that's how [`java_binary.deploy_manifest_lines`](https://docs.bazel.build/versions/master/be/java.html#java_binary.deploy_manifest_lines) works, it just doesn't automatically preserve those entries from the inputs.

What semantics would you want if there are multiple inputs, which wouldn't necessarily all have the same manifests?

It might be better for a rule for creating modular jars to require the module name to be set as an attribute, instead of trying to infer it from the inputs.

[1] https://github.com/bazelbuild/bazel/blob/c1705729ead09f28b8c718e9019fd8dbd74962be/src/tools/singlejar/options.cc#L39

**Comment by shs96c** [comment]
The semantics should be something like:

 * If any included jar sets `Multi-Release`, then the combined jar must have that set too (allowing the multi-release jar to continue to function as expected)
* If any jar contains an `Automatic-Module-Name`, this should be dropped, but a warning should be printed to the console (which can be suppressed)

The first of those is far more important than the second :)

**Comment by raiderx** [comment]
I faced with an issue: I'm importing JAR [ngdbc.jar](https://mvnrepository.com/artifact/com.sap.cloud.db.jdbc/ngdbc/2.3.58). `ngdbc.jar` is a Multi-Release JAR which has 2 versions of JDBC driver:
- for Java 8 and below by default (does not work in Java 9 and above),
- for Java 9 and above (does not work in Java 8 and below).
So I can't run my jar in Java 11 because Bazel's `singlejar` builds my jar with default classes for Java 8 and below from `ngdbc.jar`.

**Comment by cushon** [comment]
> If any included jar sets Multi-Release, then the combined jar must have that set too (allowing the multi-release jar to continue to function as expected)

As of https://github.com/bazelbuild/bazel/commit/f33ce3d8192953e425f613024ec04541ceb80f1b, singlejar has a `--multi_release` jar that causes `Multi-Release: true` to be set in the output. (It was possible earlier by using `--deploy_manifest_lines 'Multi-Release: false'`.)

The tentative plan to add `--incompatible_multi_release_deploy_jars` to Bazel that causes all `_deploy.jar`s to be multi-release.

We considered having singlejar consider whether any input jar was multi-release first, but ran into a couple of issues:

Singlejar writes the `META-INF/MANIFEST.MF` file first, before the inputs are processed, and it processes all of the inputs in a single pass for performance reasons. So it would be a regression to process the inputs twice to check for any multie-release jars, and it would add complexity to try to  write the manifest first and then patch it up later.

I looked at just writing the manifest file at the end, but some of the many zip implementations that process manifests are optimized to assume the manifest is at the beginning, so it would have been an invasive change.

I think unconditionally making deploy jars multi-release is defensible because the feature needs to be enabled if any transitive dep uses it anyways, so over time as soon as any low-level library in a repro uses it it's going to need to be enabled ~everywhere. There doesn't seem to be that much benefit to selectively enabling it.

**Comment by davido** [comment]
@bazelbuild/triage not stale

**Comment by davido** [comment]
@cushon What is the current status of this FR?

As pointed out by @shs96c, merging two JARs, where one JAR is MR-JAR is currently broken, because `Multi-Release` is lost.

As a workaround, MR-JAR flag could be added manually:

```python 
# Merge jars so
# META-INF/services/org.apache.lucene.codecs.Codec
# contains the union of both Codec collections.
java_binary(
    name = "lucene-core-and-backward-codecs-merged",
    data = ["//lib:LICENSE-Apache2.0"],
    deploy_manifest_lines = [
        "Multi-Release: true",
    ],
    main_class = "NotImportant",
    runtime_deps = [
        # in case of conflict, we want the implementation of backwards-codecs
        # first.
        "@backward-codecs//jar",
        "@lucene-core//jar",
    ],
)
```

The problem with this approach is, that for example for Lucene project, 
only only in very recent release 9.8.0 MR-JAR started to be used, so that simply upgrading Gerrit with recent Lucene version broke the build and the final artifact.

If this FR is implemented, I would just expect that merging JARs would preserved the MR-JAR bit

See this related discussion: [1].

[1] https://github.com/apache/lucene/issues/12307#issuecomment-1807097946

**Comment by cushon** [comment]
The plan from https://github.com/bazelbuild/bazel/issues/10507#issuecomment-1080825793 to "add `--incompatible_multi_release_deploy_jars` to Bazel that causes all `_deploy.jar`s to be multi-release" happened in https://github.com/bazelbuild/bazel/commit/7f75df2d299e383f58e7a0f82fd0822c88776b5e.

If you pass `--incompatible_multi_release_deploy_jars` to Bazel, `_deploy.jar` outputs for `java_binary` will always set the Multi-Release bit in the manifest, so if the jar merges in any multi-release dependencies (e.g. from `java_import`s, or custom rules that produce Multi-Release output) the bit should be preserved.

**Comment by davido** [comment]
> If you pass --incompatible_multi_release_deploy_jars to Bazel, _deploy.jar outputs for java_binary will always set the Multi-Release bit in the manifest, so if the jar merges in any multi-release dependencies (e.g. from java_imports, or custom rules that produce Multi-Release output) the bit should be preserved.

Thank you, I can confirm, that passing `--incompatible_multi_release_deploy_jars` to Bazel 7.0.0rc3:

```diff
diff --git a/.bazelrc b/.bazelrc
index 25a112d6e9..2703664276 100644
--- a/.bazelrc
+++ b/.bazelrc
@@ -64,6 +64,8 @@ build:remote21 --config=remote_shared
 # this flag here once flipped in Bazel again.
 build --incompatible_strict_action_env
 
+build --incompatible_multi_release_deploy_jars
+
 build --announce_rc
```

preserved the multi-release bit from the lucene-core.jar:

````bash
$ bazeldev build //lib/lucene:lucene-core-and-backward-codecs-merged_deploy.jar
[...]
```

META-INF/MANIFEST.MF 
```
Manifest-Version: 1.0
Created-By: singlejar
Main-Class: NotImportant
Multi-Release: true
```

^^^Now the bit is preserved, and the test is passing.
