### ISSUE TITLE
Implement the toolchain transition

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#10523]
Tracking issue for the implementation of [toolchain transitions](https://github.com/bazelbuild/proposals/blob/master/designs/2019-02-12-toolchain-transitions.md).

**Comment by eagleonhill** [comment]
What's the target release for toolchain transition and `exec` transition?

While I agree it's better to use `exec` transition than `host`, the fact that currently entire toolchain has applied `host` transition makes it impossible to include runtime libraries today. If `exec` transition would take more effort, would it be possible to decouple them, so there's some proper way to link runtime?

Just a little more background: https://docs.bazel.build/versions/master/skylark/lib/CcToolchainInfo.html#dynamic_runtime_lib is currently broken because the symlink is located at `bazel-out/host`.

**Comment by katre** [comment]
Are you using the `--incompatible_enable_cc_toolchain_resolution` flag? We haven't flipped that behavior and this is part of the reason it's not the default yet. I'd recommend flipping that back and continuing to use the legacy `cc_toolchain`suite` approach if this is causing you problems.

I am working on a migration plan for the toolchain transition and hope to send it around shortly. Once that's been agreed on I'll begin implementation and start working with rule owners to migrate, since doing this as a single world-breaking migration isn't feasible. Because CC rules don't use toolchain resolution by default, getting that working may be far down the list.

**Comment by timblakely** [comment]
Just ran into what I thought was #6889. Glad to see I wasn't going crazy when querying `ctx.target_platform_has_constraint` and not seeing the right constraints.

My use case is that I need to configure `feature`s and `flag_sets` that are passed to the `cc_common.create_cc_toolchain_config_info` based on the target cpu. My workaround is to have a separate cc_toolchain for each target, but that's not scalable in the long run.

Once toolchain transitions are in, would this use case be supported?

**Comment by katre** [comment]
That is internal to the `cc_toolchain` machinery, and so it's part of toolchain resolution (toolchain resolution will select a single `cc_toolchain` instance for a target, and then that toolchain's dependencies are up to the rule implementation).

You'll need to follow up with the CC rule maintainers to find out if that's a use case they want to support. if so, I can work with them on ways to implement it in their toolchain implementation.

**Comment by hlopko** [comment]
Wohooo \o/ Congrats! :)

**Comment by katre** [comment]
Re-opening, we also need to support aspects that use toolchains.

**Comment by katre** [comment]
Now I can close again.
