### ISSUE TITLE
Bazel runs tests in a sandbox even with "local = 1"

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#1052]
In our documentation, we say that when you set the "local = 1" attribute on a test, the test will run without sandboxing. This is supposed to be equivalent to setting the "tags = ['local']" attribute on a test: http://bazel.io/docs/be/common-definitions.html#test.local

However, when I run this test, it actually executes in a sandbox, as seen in "ps axuf":
```
sh_test(
    name = "example_test",
    srcs = ["example_test.sh"],
    local = 1,
)
```

This test however runs without a sandbox:
```
sh_test(
    name = "example_test",
    srcs = ["example_test.sh"],
    tags = ["local"],
)
```

So, it looks like the "local = 1" logic is somehow broken. We should write a test for this behavior and then fix the bug.

**Comment by edwardmjm** [comment]
I hit this issue as well, what's the conclusion?
I'd like to run a test in my source tree, but can't find a way to address it.
Both `local = 1` and `tags = ["local"]` put my tests into a sandbox.
My bazel version is 0.10.0

**Comment by edwardmjm** [comment]
Sorry, I misunderstand the `sandbox` here.
I think it means `read-only` environment here.
What I want is to have a fully mirror of my codebase in the test running environment.

**Comment by jin** [comment]
As long as the sources are declared as inputs to your test, Bazel will make them available at test runtime. 

Do you have a use case where this is not sufficient?

**Comment by edwardmjm** [comment]
It is sufficient, but it needs huge amount of unnecessary work.
I am migrating from cmake to bazel. In a folder, basically it is some python and some genrules.
We had a test script run all the python tests in this folder recursively.
So basically I need all py files under this folder as `data` for the test script.
But given there are some `genrule` I need to run, there are some BUILD files, so that glob(["**/*.py"]) can't get through.

For example, we have a folder `python` contains following files.
`python/BUILD`
`python/test_a.py`
`python/folder_a/BUILD` this one has genrule in it.
`python/folder_a/folder_b/BUILD` this one has genrule as well.
`python/folder_a/folder_b/folder_c/test_b.py`

We run the test script under `python`, it will run all the test_*.py recursively. Now we want to wrap it as a `sh_test` in bazel. So we need to specify all the `test_*.py` in the `data` field. But there is no easy way to do that since `glob()` can't get through `python/folder_a/BUILD` and `python/folder_a/folder_b/BUILD`

I know it is a good way to use bazel, but it is too much work for migrating everything at the same time.

**Comment by jin** [comment]
Thanks for the comprehensive explanation on your use case! It does seem tedious to perform this particular migration. Do you mind creating a question with what you've posted so far on [StackOverflow](https://stackoverflow.com/questions/tagged/bazel), tagged with `bazel`? This issue is closed and will not get as many eyeballs as StackOverflow.

**Comment by edwardmjm** [comment]
OK, here it is.
https://stackoverflow.com/questions/49415876/how-to-run-test-on-the-source-tree-in-bazel

**Comment by jin** [comment]
I just thought of a method and answered in the post. Hope that works for
you.
