### ISSUE TITLE
Starlark semantics change does not invalidate external repositories

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#10538]
In order to finally lay `--incompatible_do_not_split_linking_cmdline` to rest, we need to make some changes to `unix_cc_configure.bzl` which are not backward compatible. Therefore, we need to hide that behind a flag somehow.

One approach to do so is to expose Starlark incompatible flags to repository functions. However, when such a flag is changed, Starlark repositories are not invalidated and not rebuilt. (note that incorrectness of this pattern already exists at HEAD, because Starlark repository functions, well, depend on Starlark semantics)

This blocks at least:

https://github.com/bazelbuild/bazel/issues/10327
https://github.com/bazelbuild/bazel/issues/9254

**Comment by laurentlb** [comment]
> we need to make some changes to `unix_cc_configure.bzl` which are not backward compatible. Therefore, we need to hide that behind a flag somehow.

Is there any plan to move this file out of `@bazel_tools`? bzl files not shipped with Bazel don't need incompatible flags.

**Comment by oquenchil** [comment]
Not any time soon.

**Comment by oquenchil** [comment]
Laurent this brings up a very good question though. When unix_cc_configure.bzl is in rules_cc which is a workspace rule, how do we introduce incompatible changes if we cannot create Starlark semantic flags from outside? Even if rules_cc is outside of Bazel I expect that due to its importance we will still be asked to follow the same policy, but how would we do this?

1) unix_cc_configure.bzl is in Bazel for now. 
2) But even when it's in rules_cc, we will have to add incompatible flags through Bazel until a mechanism for incompatible changes in external repositories is available. 

So this incorrectness bug due to workspaces not being refetched should be prioritized anyway starting with 1)

**Comment by laurentlb** [comment]
Users will deal with incompatibilities when they want to update their dependency on rules_cc. In other words, updating Bazel will not break them; they can update their dependency independently. You shouldn't need a flag for this (just like we don't use flags in Skylib).

**Comment by oquenchil** [comment]
Alright, that makes sense, thank you. Can this still be fixed since right now unix_cc_configure.bzl is in Bazel?

I expect that we will always have internal workspace rules one way or another, not just those from external repos.

**Comment by lberki** [comment]
This is not unique to `unix_cc_configure.bzl`: AFAIU all Starlark repositories, well, execute Starlark code and as such, are vulnerable to incorrect caching on changes to Starlark semantics flags.

**Comment by laurentlb** [comment]
Yes, indeed. Flags that affect Starlark semantics may also affect the repository functions. So we have a correctness issue here.

@aehlig will take a look.
