### ISSUE TITLE
Access workspace status in a Starlark action

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#1054]
https://groups.google.com/forum/#!topic/bazel-discuss/hqyMFjEpJgM

There's apparently no way to access volatile-status.txt in a Skylark action.

**Comment by dslomov** [comment]
@damienmg ptal

**Comment by damienmg** [comment]
Yes there is no nice way to do it, except use a stamped genrule that expose that file to the skylark rule.

**Comment by schroederc** [comment]
It's possible to add a dependency to the `ctx.version_file` artifact and read it (as well as `ctx.info_file`).  However, it would be useful to allow Skylark rules access to value of the `--stamp` setting so that they can *conditionally* rely on that file when stamping is requested.

This issue also relates tangentially to #849.

**Comment by mgyucht** [comment]
+1! I would love to be able to do this as well.

**Comment by mikedanese** [comment]
Is this even possible with workspace status modeled as an action? What would a solution look like?

**Comment by AustinSchuh** [comment]
Building off what @schroederc wrote, I'd really love to only stamp when --stamp=true is specified.  Which means that I need access to the --stamp flag in skylark.

**Comment by jaksky** [comment]
Is it possible to access such info(workspace status) from macro?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
