### ISSUE TITLE
Preserve unexpected generated files

### ISSUE THREAD

**Issue by jpan127** [bazelbuild/bazel#10601]
### Description of the problem / feature request:

I'm guessing this is a feature request: I would like a way to specify side effects from a rule `cc_library` for example.  If I run the compile command with specific options, additional files may be generated and bazel wipes these.

### Feature requests: what underlying problem are you trying to solve with this feature?

Preserve unexpected generated files.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

No bug.

### What operating system are you running Bazel on?

Ubuntu 16.04

### What's the output of `bazel info release`?

release 2.0.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

No.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

No need.

###  Have you found anything relevant by searching the web?

Yep.

### Any other information, logs, or outputs that you want to share?

Use case: https://github.com/bazelbuild/bazel/issues/9047

**Comment by ArekSredzki** [comment]
This would be very useful!

**Comment by janakdr** [comment]
Sounds like this is specific to sandboxing?

**Comment by susinmotion** [comment]
@jmmv is this something you're familiar with?

**Comment by jmmv** [comment]
Yes, I'm assuming this is specific to sandboxing. The sandbox won't propagate unknown outputs into the output tree, and that's very much by design.

What's the use case here? If you are passing extra options to generate new files, then the rules should know about them. They could use a tree artifact to capture those unknown outputs though.

**Comment by ArekSredzki** [comment]
@jmmv One such use case is described in #9047. Put otherwise, we'd like `cc_library` to configurably support additional output artifacts. If you use `-ftime-trace` with Clang, it will produce a `.json` alongside the other artifacts for each build unit. It's desirable to be able to retain those artifacts while retaining sandboxing. What's the easiest way to do this?

**Comment by ArekSredzki** [comment]
Someone at our company was able to add support for this using an aspect. I've asked them to chime in here if they have time.
