### ISSUE TITLE
sha256 of http_archive is not checked

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#10630]
### Description of the problem / feature request:

The `sha256` of `http_archive` is not checked on macOS sometimes

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Checkout https://github.com/bazelbuild/bazel-gazelle/commit/92bc7b03d768a3581bd9bdd30d5e3635bbf854da
2. Run `bazel build //:gazelle`, verify it succeeds
3. Apply the following patch, which changed the rules_go version without changing its sha:
```diff
diff --git a/WORKSPACE b/WORKSPACE
index 867d957..e95f7c3 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -6,8 +6,8 @@ http_archive(
     name = "io_bazel_rules_go",
     sha256 = "b27e55d2dcc9e6020e17614ae6e0374818a3e3ce6f2024036e688ada24110444",
     urls = [
-        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.21.0/rules_go-v0.21.0.tar.gz",
-        "https://github.com/bazelbuild/rules_go/releases/download/v0.21.0/rules_go-v0.21.0.tar.gz",
+        "https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.20.4/rules_go-v0.20.4.tar.gz",
+        "https://github.com/bazelbuild/rules_go/releases/download/v0.20.4/rules_go-v0.20.4.tar.gz",
     ],
 )
```
4. Run `bazel build //:gazelle` again. It still succeeds

### What operating system are you running Bazel on?

macOS 10.15.2

### What's the output of `bazel info release`?

release 2.0.0

### Any other information, logs, or outputs that you want to share?

The same issue can be reproduced since at least Bazel 1.1

**Comment by davido** [comment]
//CC @aehlig 

This is a duplicate of: https://github.com/bazelbuild/bazel/issues/5144.

The repository cache is activated per default in recent Bazel version. If you do partially update: only URL was mutated but sha256 wasn't adapted, the artifact for the old sha256 is retrieved from the repository cache and delivered. The URL is ignored in this case.

The fix is to add canonical_id to the rule. I did something similar in gerrit for `http_file()` rule recently see: [2], [3].

[2] https://github.com/bazelbuild/bazel/issues/10612
[3] https://bazel-review.googlesource.com/c/bazel/+/127210

**Comment by linzhp** [comment]
Thanks for explaining
