### ISSUE TITLE
Source forest creation failed

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1064]
Bazel intermittently produces this error message:

```
ERROR: Source forest creation failed: /usr/local/google/home/lberki/.cache/bazel/_bazel_lberki/737f930c0b15836858bd51aa38e729ca/github/.#WORKSPACE (File exists).
```

**Comment by damienmg** [comment]
when doing what? (repro?)

**Comment by lberki** [comment]
The command that failed like this last time was `bazel build //src/test/shell/bazel/...` . I don't think it's specific to the command, though.

**Comment by damienmg** [comment]
`.#WORKSPACE` looks very suspicious, assigning to @kchodorow for investigation.

**Comment by kchodorow** [comment]
That's generally what emacs names autosave files.  I'll look into it, but saving or removing the file should be a workaround.

**Comment by lberki** [comment]
Yep, that's an emacs autosave file. I didn't change the WORKSPACE file, this was a stale autosave. My best guess is a glitch in the source forest creation code.

**Comment by damienmg** [comment]
No repro. Sounds like a stale emacs autosave file. Closing

**Comment by erickj** [comment]
I received this same error (with an emacs autosave file) however it was an innocuous notes document rather than the WORKSPACE file that is causing issues:

ERROR: Source forest creation failed: /home/erick/.cache/bazel/_bazel_erick/4fbe1c2851c54abfd26b77789ffadbff/execroot/io_vos/.#NOTES.md (File exists)

Only after manually removing the autosave file and doing a `$ bazel clean --expunge` would the build proceed. `$ bazel clean` (w/o --expunge) did not solve the issue
