### ISSUE TITLE
maven_jar has undocumented name restrictions.

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#1066]
apparently, you can't use dashes and/or dots in maven_jar names. This is not documented.

Can this be documented or fixed?

hanwen@nienhuys:~/vc/gitiles$ bazel build gitiles-servlet/...
ERROR: /home/hanwen/vc/gitiles/WORKSPACE:20:1: maven_jar rule //external:joda-time's name field must be a legal workspace name.
ERROR: /home/hanwen/vc/gitiles/WORKSPACE:62:1: maven_jar rule //external:servlet-api_3_0's name field must be a legal workspace name.

**Comment by smparkes** [comment]
This was mentioned in the release notes for 0.1.5: https://github.com/bazelbuild/bazel/releases/tag/0.1.5

> Repository rules must use names that are valid workspace names.

I saw it in the release notes since it was a breaking change.

Not sure if the requirement ever got added anywhere. Moreover, things like http://bazel.io/docs/be/workspace.html#be-menu still use examples (@my-ssl) that are no longer valid.
