### ISSUE TITLE
incompatible_applicable_licenses: Add global attribute "applicable_licenses"

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/bazel#10687]
This flag enables a new attribute `applicable_licenses` to be globally available on any rule. It also enables a `package()`  level attribute `default_applicable_licenses`.

**Flag:** --incompatible_applicable_licenses

**Motivation**:  #7444 - we are pulling the existing `licenses` rule out of Bazel and creating a Starlark based rule set that adds more flexibility. Also see: 
[License Checking in Bazel](https://docs.google.com/document/d/1uwBuhAoBNrw8tmFs-NxlssI6VRolidGYdYqagLqHWt8/edit#
)

**Migration**
If your rules define an attribute `applicable_licenses`, you must rename that.
We expect to flip this flag in Bazel 4.x

**Comment by keith** [comment]
Is this actively being worked on?

**Comment by aiuto** [comment]
Yes.  I'm trying to prove out working code at Google before releasing
things that are I flux. That said, when I am back in the office later this
week I can do the paperwork to create the rules-repo repository to hold the
macros to.make use of it. The core Bazel changes should be all done, if you
want to try with the flag flipped.

**Comment by keith** [comment]
Great thanks for the update!

**Comment by keith** [comment]
@aiuto any updated estimate on when the macros repo will be open sourced?

**Comment by aiuto** [comment]
It is on my plate for April. The Covid response has caused some slowdowns
and reprioritization in the last few weeks, so it is hard for me to
promise, but that is still my target.

**Comment by ulfjack** [comment]
We needed to handle licenses in preparation for our first public release, and since this wasn't ready, I had to design my own license handling infrastructure. These are our requirements so far:

- Generate a list of projects and license URLs.
- Generate a directory or zip of all applicable licenses.
- Also handle notice files from downstream projects.
- Handle compile-time dependencies (both host and target configuration).

The documentation currently primarily documents what your proposed rules look like, but I'm more interested in what the intended interface between Bazel and the licensing rules looks like. From what I've seen so far, I'm not sure the Google rules will work for us, and I expect to continue to use our own.

**Comment by aiuto** [comment]
Hi Ulf:  FYI, I am days away from releasing the work so far to bazelbuild/rules_license.  Just waiting for the last launch bit to flip.  Once that happens, I can more quickly iterate on the examples there and canonical license kinds.

**Comment by aiuto** [comment]
It's longish to explain that interface here. I hope the examples in the
public repo explain it. But roughly.

Someone publishing software can specify it is available under license
- with a specific text of their license
- and that it is of a well known kind, like GPL2. The well known kinds are
based on SPDX identifiers.

Every organization that cares about this will mirror in the list of well
known identifiers, but they
are expected to set their own license *conditions* for what that license
identifier implies.

We provide canonical tools that
- gather transitive license declarations for a top level target
- provide the package names, license texts, conditions, copyright notices,
... as a big JSON blob for you to process into things like Android resource
files or an audit report
- check that the conditions used matches the set of conditions allowed by a
license_policy.

Each organization will write their own license_policy rules.  In the
typical case there is at least a policy each for things like mobile_app,
internal_server, server_to_delivered_in_binary, private_test_app.

So. The rules provide a framework, but each organization must write their
own policy.

**Comment by keith** [comment]
After just a brief look I don't completely understand how the pieces fit together, but I'm happy to look at some changes to try and get a better sense

**Comment by aiuto** [comment]
Have you read the design doc?  That gives a lot of background.

**Comment by jheaff1** [comment]
Any update on this?

**Comment by adam-azarchs** [comment]
It isn't clear from this issue, the design doc, or the rules_license repository what the current status is.  I _think_ it might be safe to start building stuff around the rules (e.g. our own list of `license_kind`s) but I'd rather not put a lot of effort into this if the public rules are way out of sync with the internal version so I'd have to overhaul everything for some future update.

Another thing that is unclear from the design document is whether this is ever expected to handle non-vendored third-party dependencies.  In particular, what is going to be badly needed to make this useful for people who don't just vendor everything into their monorepo are updates to various repository fetching rules.  `npm_install` would be a particularly important and complex example use case.  If there is ever going to be built-in support from the official `rules_nodejs` for this, I would want to make sure that whatever I build for us internally stays at least mostly compatible with it.  Other examples would include e.g. `go_respository`, `pip_install`, `maven_install`, and so on.  Obviously _can_ be done (with varying degrees of ease of use and reliability) but not clear whether there's plans to actually do it.

**Comment by fmeum** [comment]
@aiuto I tried to adopt `rules_license` in a ruleset, but encountered two blockers that I listed in https://github.com/bazelbuild/rules_license/issues/9 that are fixed by https://github.com/bazelbuild/rules_license/pull/7 and https://github.com/bazelbuild/rules_license/pull/8. If these were fixed, rulesets could start to use `rules_license` to add license annotations.

**Comment by adam-azarchs** [comment]
According to the design doc, it's expected that every organization will fork `rules_license`.  However, generally-applicable changes like the above would be nice to get into the "official" version to keep things from diverging too far.  Certainly the  private visibility for the SPDX license set makes them useless (since there's nothing else in that package).  For `license` rules in I think the vast majority of cases you'd want the rule to be visible to at least sub-packages - there's a decent argument to be made for the macro to set the visibility to `:__subpackages__` by default.

Related to that, as I've been rolling these rules out I've found it would be convenient if `default_applicable_licenses` were available on `workspace` as well as `package`, since in a majority of cases (outside of Google, anyway), a bazel workspace corresponds to a git repository, which usually has a single license file in the root which applies to everything in the repo (possibly with a few exceptions here and there).  I do however recognize that that might be tricky to get working because as far as I can tell the content of `WORKSPACE` files is more or less ignored for external repositories (though maybe `bzlmod` will be changing the situation there?  It would be nice if `bzlmod` had some affordances for doing that, though last I heard that wasn't part of the plan).

**Comment by fmeum** [comment]
> According to the design doc, it's expected that every organization will fork `rules_license`.  

This point in the doc might warrant further clarification. As I understand it, many *organizations* will fork or vendor rules_license. However, rulesets and other open-source dependencies would have to be able to refer to a common set of license_kind definitions.

>  I do however recognize that that might be tricky to get working because as far as I can tell the content of `WORKSPACE` files is more or less ignored for external repositories (though maybe `bzlmod` will be changing the situation there?  It would be nice if `bzlmod` had some affordances for doing that, though last I heard that wasn't part of the plan).

I think that bzlmod is flexible enough to support this use case as is: If rules_license defines appropriate module extensions, modules could use those to declare their default licenses and rules_license would be able to associate them with the modules as it will have visibility into the entire module dependency graph.

**Comment by aiuto** [comment]
I had forgotten this issue, since it was about the flag to add the feature. The feature was added and the flag removed long ago, so I am going to close this issue.   Let's discuss more of what rules_license does in that repository rather than this thread.

To answer some of the points from above.
- many of the issues/PR mentioned are now done
- I am working on a unified mechanism to splice license and package information from upstream repos like Maven into the BUILD graph.  I have a working prototype, but bzlmod breaks it, so more engineering is needed.
- SBOM work is changing the whole face.
