### ISSUE TITLE
singlejar unexpectedly normalizes timestamps for non .class file entries

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#10789]
Gerrit Code Review project provides dozen of plugins to extend its core functionality. The plugin artifact is a JAR file that contains also web assets like JavaScript and HTML files. The timestamp of these assets is accessible from HTTP request in gerrit server and should not be normalized.

Even though there is this documentation section in the `singlejar`'s source code (https://github.com/bazelbuild/bazel/blob/master/src/tools/singlejar/output_jar.cc#L503-L505):

```
   // When normalize_timestamps is set, entry's timestamp is to be set to
   // 01/01/2010 00:00:00 (or to 01/01/2010 00:00:02, if an entry is a .class
   // file).
```

It seems that nevertheless the timestamp of non .class files is normalized. To reproduce, have a rule that produces non .class file entries in jar, and run singlejar to create an output artifact:

```
  $ unzip -l ~/in.jar
  Archive:  /home/davido/in.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
  1952076  2020-02-14 19:19   static/codemirror-element-shadydom.html
      329  2020-02-14 19:19   static/codemirror_editor.html
  1952220  2020-02-14 19:19   static/codemirror-element-shadowdom.html
     1802  2020-02-14 19:20   static/codemirror_editor.js
---------                     -------
  3906427                     4 files
```

Create the out.jar using `singlejar_local` with `--normalize` option from bazel installation:

```
  $ external/remote_java_tools_linux/java_tools/src/tools/singlejar/singlejar_local --normalize --output ~/out.jar --sources ~/in.jar
```

Verify that the out.jar is now broken:

```
  $ unzip -l ~/out.jar
  Archive:  /home/davido/out.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2010-01-01 00:00   META-INF/
       48  2010-01-01 00:00   META-INF/MANIFEST.MF
       44  2010-01-01 00:00   build-data.properties
  1952076  2010-01-01 00:00   static/codemirror-element-shadydom.html
      329  2010-01-01 00:00   static/codemirror_editor.html
  1952220  2010-01-01 00:00   static/codemirror-element-shadowdom.html
     1802  2010-01-01 00:00   static/codemirror_editor.js
---------                     -------
  3906519                     7 files
```

This diff fixed the problem: [1], though, the proper fix would be appreciated. The corresponding Gerrit issue is here: [2]. Temporary workaround in Gerrit: [3]. I used Bazel@HEAD (5370e40ea51e29f9f2dc5628932ac926e811b65d).

[1] https://bazel-review.googlesource.com/c/bazel/+/129350
[2] https://bugs.chromium.org/p/gerrit/issues/detail?id=12349
[3] https://gerrit-review.googlesource.com/c/gerrit/+/255292

**Comment by aiuto** [comment]
I'm assigning this to Rules-Server, but it really belongs nowhere, or in a few places.

What we have is two competing needs. 
1. We want to insulate the build tree from the mod time of files, so that Bazel can minimally rebuild only when the content changes.
2. You need some packaging rules that absolutely take mod time and build time into account.

I think the way we would have to solve this is have a capability to track build time of files and plumb this through to packaging rules. That is a non-trivial project.

Another approach is to change the packaging rules so that they all have the option to stamp with the build time of the package. Instead of 2020-01-01 you'll get today's date/time. If we go that route, we should do similar behavior for all the packaging rules in @rules_pkg. We might consider moving singlejar out of the bazel sources and into rules_pkg also.

**Comment by davido** [comment]
Bazel is optimizing the output artifact for reproducible builds.
