### ISSUE TITLE
Centralize style definitions across Bazel doc properties

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#10793]
docs.bazel.build, blog.bazel.build, and bazel.build/contributing.html all serve their own style definitions.

If can serve this from a centralized place, all style updates will propagate site-wide for free.

Outcome is faster iteration and guaranteed consistency.

**Comment by jin** [comment]
The plan is to serve CSS styles from a centralized repo (or one of the repos, preferably bazelbuild/bazel-website), and have the other repos pull the CSS styles from the centralized repo.

**Comment by laurentlb** [comment]
Related: the footer of https://www.bazel.build/, https://blog.bazel.build/ and https://docs.bazel.build/ are different. They don't include the same links.

**Comment by jin** [comment]
Since docs.bazel.build (https://github.com/bazelbuild/bazel/commit/762c27d2cdc8d66cc4f91a141ec667150e8a5f39) and blog.bazel.build (https://github.com/bazelbuild/bazel-blog/pull/225) are now pulling the base stylesheet from www.bazel.build, we can close this now, and mark Docs milestone 1 as complete.
