### ISSUE TITLE
How is Bazel beneficial for nodejs or typescript monorepo?

### ISSUE THREAD

**Issue by jjangga0214** [bazelbuild/bazel#10801]
I'd like to ask if Bazel is beneficial for nodejs and typescript projects.

There're already lerna, or nrwl/nx.

Pure nodejs project generally does not need "build" process.

Frontend apps would use webpack or rollup.(What is the advantage of Bazel's rollup_bundle in node rule, by the way?)

Typescript allows [incremental build(--incremental)](https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options) with [project references](https://www.typescriptlang.org/docs/handbook/project-references.html) feature.

Thus, why would Bazel needed or how would it provide profit, to node based monorepo?

Maybe, remote build and cache?

Any idea or experience?

Thanks!

**Comment by sudoforge** [comment]
I am by no means an expert on current javascript monorepos, and everyone will have their own opinions on this, but at a high level, using Bazel brings a few benefits:

- You can "build" your javascript services with the same tool and in the same way as the rest of your codebase
- Bazel supports remote execution and remote caching, which can greatly improve the development experience by avoiding discrepancy between development environments (e.g. one user on OSX, another on Linux, a third on Windows)
- One of the main benefits of Bazel, as I see it: Bazel can reduce or remove "it works on my machine" builds by ensuring the same version of webpack, rollup, nodejs, etc is used for all application code, and preferring hermeticity throughout your builds and tests (you can, of course, introduce non-hermetic behavior, but that is anti-pattern)
- Another main benefit of Bazel is the dependency graph. It is infinitely valuable to be able to run a simple query and determine every dependency a particular target has.

As to  your other question,

> What is the advantage of Bazel's `rollup_bundle` in `rules_nodejs`, by the way?

As per [the documentation](https://bazelbuild.github.io/rules_nodejs/Rollup.html), the `rollup_bundle` rule is a wrapper around the `rollup` command line application. The _purpose_ of doing this is so that it can be executed via Bazel, and benefit from the same points I've noted above.

**Comment by thesayyn** [comment]
The most important one is that bazel is multi language which lets you build complex multi language applications easily. 
Only thing you have to do is add the appropriate rules into your workspace.

To give a real life example, we have this huge project which we has nodejs server and clients in different languages(swift, dotnet, java). With this setup we have the ability to rerun only the affected tests if something changes in the server code. 

Hint: also bazel forces you to write more modular code which is a good thing if you have juniors in your team. (I love this feature the most)

**Comment by jin** [comment]
@jjangga0214 hopefully the answers above clarify things for you! Closing as there's nothing actionable here.
