### ISSUE TITLE
Document best practices for Skylark remote repositories

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1081]
From code review (by @kchodorow):
Optional: have a section on best practices.  You mention that these rules are non-hermetic, but it might be good to go over:

1. They should require & verify checksums whenever possible.
2. What they cache/when the cache is invalidated/what the criteria is for them being re-run.
3. Anything else people should know?

**Comment by davidzchen** [comment]
What about naming for workspace rules?

As mentioned in my comment in #699, should we discourage naming workspace rules `*_library` and `*_binary` to avoid confusion since those rules would have names similar to regular build rules?

For workspace rules that pull packages from various package managers (e.g. NPM, Bower, PyPI, Crates.io, DUB, etc.), I think it would be better to name those rules `*_package` (though for Rust, I'm planning to call it `cargo_crate` since the Rust community refers to them as crates).

We will also want to have rules for finding libraries on the local system to cover the uses cases people use Autoconf for, though I am less sure about how we should name such rules.

WDYT?

**Comment by damienmg** [comment]
I think what you said make sense, sgtm

**Comment by shahms** [comment]
I've written some rules for finding system libraries with pkg-config for Kythe.  At the moment, the tentative name is `pkg_config_module` but I'm not wedded to that.  `pkg_config_package` seemed a bit redundant, but reasonable.  I've also got some rules for mapping a local library using an environment variable, but have struggled to come up with a better name than `local_cc_library` .

**Comment by damienmg** [comment]
I think `*_package` for packaging rule and `*_config{ure}` for configuration rule is correct.

**Comment by damienmg** [comment]
The blog post is the official documentation for now.
