### ISSUE TITLE
Document the `environment_group` pseudo-rule and `environment` rule

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#10849]
There is no documentation for either the `environment_group` pseudo-rule or the `environment` rule. `environment` appears to have one piece of documentation (for the [`fullfills` attribute](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/constraints/EnvironmentRule.java;l=46;drc=c5fcc86d1fb02ee20ad1ce6fadb2a73f54a691e1)), but that can't be found because the overall rule isn't documented. `environment_rule` is implemented by a Starlark function and is [explicitly called out as undocumented](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/packages/StarlarkLibrary.java;l=138;drc=d8ee69ab679594cb47fa8c5fa24b309a2a23b54c).

**Comment by katre** [comment]
Tagging @gregestren for context and history.

**Comment by gregestren** [comment]
This is fair. We've kept it undocumented because platforms should (I think) supplant most practical uses of this and we don't want too forked an API as we can help it. 

But the cat's out of the bag already and we can clarify these relationships and best practices in the docs.

**Comment by shahms** [comment]
One thing that isn't covered by platforms but can be done with constraints (although awkwardly) is preventing a target from transitively depending on targets which are mutually exclusive (regardless of platform), e.g.

```
environment(name = "a-env")

environment(name = "b-env")

environment_group(
    name = "a_xor_b",
    defaults = [
        ":a-env",
        ":b-env",
    ],
    environments = [
        ":a-env",
        ":b-env",
    ],
)
cc_library(
    name = "a_lib",
    srcs = ["a.cc"],
    restricted_to = [":a-env"],
)

cc_library(
    name = "b_lib",
    srcs = ["b.cc"],
    restricted_to = [":b-env"],
)

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = select({
        ":env-a": [":a_lib"], # Succeeds.
        ":env-b": [":b_lib"], # Succeeds.
        "//conditions:default": [ # Fails.
            ":a_lib",
            ":b_lib",
        ],
    }),
)
```

There shouldn't be any need to define and use a new platform to express and enforce this kind of constraing.

**Comment by gregestren** [comment]
I acknowledge platforms don't solve all use cases naturally. Product features (like "free" vs. "premium") are a prominent counterexample.

In your above example, would `a-env` and `b-env` refer to anything in particular? What's the non-platform mutual exclusivity you're thinking?

**Comment by shahms** [comment]
This case came up internally specifically around avoiding known ODR violations at build time by declaring two libraries explicitly incompatible. A fairly niche case, to be sure, but considering the hard-to-debug breakages such issues can cause seemed potentially valuable to support.

**Comment by shahms** [comment]
Still not documented and still has a few uses which aren't covered by platforms, such as one of the primary use cases called out in the comment on the `compatible_with` attribute:
> For example, externally deployable binaries shouldn't depend on libraries with company-secret code.

This constraint is not easily achievable with platforms and the behavior of violations is worse as violations will be silently allowed until a target in violation is explicitly built.  Additionally, using platforms for this kind of enforcement is quite disruptive as you potentially need to "fork" every platform for every such constraint rather than allowing the constraint to live in a standalone environment group.

**Comment by gregestren** [comment]
How about handling https://github.com/bazelbuild/bazel/issues/10849#issuecomment-1077917292 and https://github.com/bazelbuild/bazel/issues/10849#issuecomment-2477028331 with aspects? Or `bazel cquery`? I realize these are also awkward - they're not as simple as slapping a tag on a dep and building like normal. But the problem is there's still no awkwardness-free API for expressing arbitrary dep constraint relationships. `environment_group`, etc. is no exception.  

> externally deployable binaries shouldn't depend on libraries with company-secret code

For this, I think https://github.com/bazelbuild/rules_license is the current vision. It's a fancy use of aspects to reliably enforce license constraints. It shouldn't be too hard to map "company-secret' to a license model. 

Arguments against documenting `environment_group`:

1. Bazel has an over-complex API. The community fairly complains there are too many sub-APIs with overlapping features and it's hard to reason through them.
1. `environment_group` breaks down for multi-team / multi-org projects. Binary owner `//foo` wants to set a new `compatible_with`. That requires tagging `//foo`'s transitive deps. It's not only a potentially large change, but it crosses team, org, and release boundaries. Library maintainers may get PRs to support environments they don't actually know or care about.  This is a huge reason we've since explored other paradigms.
2. `environment_group` doesn't soundly work with `select()`.  https://github.com/bazelbuild/bazel/issues/10849#issuecomment-1077917292 is a clean example but at some point the semantics are fundamentally ambiguous because `compatible_with` has to resolve constraints before `select()` itself resolves. So it has to make assumptions which some users may want while others want the opposite. [Details](https://github.com/bazelbuild/bazel/blob/08beb210eddd35b703857e005d99c60b963e8e10/src/main/java/com/google/devtools/build/lib/analysis/constraints/ConstraintSemantics.java#L83-L119).

You're clearly able to use this, which is great. But how much community demand is there for sanctioning this in official documentation when it produces a more complex public API? Yet another concept for users to learn about and figure out how to fit with all the other possibilities.
