### ISSUE TITLE
Bazel CI: rules_haskell is broken with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#10953]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1421#0d30573e-d485-477b-8c25-9fc9d8a0f663
```
/tmp/tmpixj2i9vn/bazel --nomaster_bazelrc --bazelrc=/dev/null info
ERROR: <builtin>: Rule class sh_posix_toolchain declared too many attributes (180 > 150)
ERROR: error loading package '': in /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/554c449d1d415008aa2ab797cbd0edbd/external/rules_haskell/haskell/ghc_bindist.bzl: Extension file 'sh/posix.bzl' has errors
```
Culprit: https://github.com/bazelbuild/bazel/commit/b839a51d346b61815fd48de2396250c80d1713f0
Bazel Auto Sheriff: https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/86

/cc @michajlo

**Comment by meteorcloudy** [comment]
@michajlo Can you help fixing this today? Otherwise, I'll have to rollback the culprit.

**Comment by michajlo** [comment]
Does that rule _really_ need 180 attributes? We can raise the limit, but it can't go any higher than 254 due to https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/packages/AttributeContainer.java#L48. The current default was chosen to give a good amount of warning before getting close to that hard limit in order to give users time to fix things.

**Comment by meteorcloudy** [comment]
> Does that rule really need 180 attributes?
/cc @aherrmann @mboes Can you help answering this question?

**Comment by michajlo** [comment]
Filed https://github.com/tweag/rules_sh/issues/13 for follow-up.
