### ISSUE TITLE
Warning: Rule '<every remote repository rule>' indicated that a canonical reproducible form can be obtained by dropping arguments ["generator_name", "generator_function"]

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#11040]
I'm seeing these warnings for every remote repository rule on Bazel@HEAD (5c1c0d1ed8643c90fba239d1bc642e4ebd044c2c).

Here are the warnings for [gitiles](https://gerrit.googlesource.com/gitiles) repository:

```
  $ bazel build :gitiles
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 0e7d47af-ed3f-4882-8129-8ead508a664b
DEBUG: Rule 'com_googlesource_gerrit_bazlets' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1581093008 -0500" and dropping ["generator_name", "generator_function"]
DEBUG: Repository com_googlesource_gerrit_bazlets instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule git_repository defined at:
  /home/davido/.cache/bazel/_bazel_davido/9fdffb7f2a398de2e1a63eaee2ea7c50/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18: in <toplevel>
DEBUG: Rule 'rules_java' indicated that a canonical reproducible form can be obtained by dropping arguments ["generator_name", "generator_function"]
DEBUG: Repository rules_java instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/davido/.cache/bazel/_bazel_davido/9fdffb7f2a398de2e1a63eaee2ea7c50/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by dropping arguments ["generator_name", "generator_function"]
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/davido/.cache/bazel/_bazel_davido/9fdffb7f2a398de2e1a63eaee2ea7c50/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
DEBUG: Rule 'remote_java_tools_linux' indicated that a canonical reproducible form can be obtained by dropping arguments ["generator_name", "generator_function"]
DEBUG: Repository remote_java_tools_linux instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/davido/.cache/bazel/_bazel_davido/9fdffb7f2a398de2e1a63eaee2ea7c50/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
DEBUG: Rule 'rules_proto' indicated that a canonical reproducible form can be obtained by dropping arguments ["generator_name", "generator_function"]
DEBUG: Repository rules_proto instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/davido/.cache/bazel/_bazel_davido/9fdffb7f2a398de2e1a63eaee2ea7c50/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
DEBUG: Rule 'remotejdk11_linux' indicated that a canonical reproducible form can be obtained by dropping arguments ["generator_name", "generator_function"]
DEBUG: Repository remotejdk11_linux instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/davido/.cache/bazel/_bazel_davido/9fdffb7f2a398de2e1a63eaee2ea7c50/external/bazel_tools/tools/build_defs/repo/http.bzl:336:16: in <toplevel>
```

**Comment by davido** [comment]
Bisecting the problem:

git bisect good 2feb36fc51
ebb86fcdc202c440a362a54f6b0de8a049dfa84b is the first bad commit
"bazel packages: record Starlark stack in RuleClass at creation"

//CC @alandonovan

**Comment by jin** [comment]
cc @laurentlb This is a UI regression.

**Comment by aiuto** [comment]
cc/ +Alan Donovan <adonovan@google.com>

**Comment by alandonovan** [comment]
Sorry for the regression. My change (ebb86fc) had the necessary effect of plumbing the callstack from Starlark all the way to repository_rule instantiation, which means that repository_rules now have generator_* attributes, just like ordinary package rules. Though I forgot to mention it in the change description, this was an intentional behavior change that seemed like a good thing.

Is it a good thing?  If so, then the RepositoryResolvedEvent machinery (which I don't understand at all) will need to change in some way to accommodate it. If not, then I will need to suppress the creation of generator_* attributes for repository rules.

The first of these approaches seems simpler (though not easier) to me.

@laurentl @susinmotion

**Comment by alandonovan** [comment]
@brandjon  Who owns the WORKSPACE.resolved hack^Wmachinery?

**Comment by laurentlb** [comment]
I'm afraid no one owns (or is familiar) with this machinery anymore.
Both approaches seem reasonable to me.

**Comment by brandjon** [comment]
According to repository rule [docs](https://docs.bazel.build/versions/3.0.0/skylark/repository_rules.html#implementation-function), repo rule functions may return a dict indicating what params would need to be passed in order to make the call to the repo rule reproducible in the future. Since repo rules now have new implicit attributes, this logic will identify their absence in any returned dict as indicating a problem.

I'll go ahead and make the repo rule machinery explicitly ignore those particular builtin attributes by hardcoding their names. I'm unaware of any more general mechanism we have for identifying implicit attributes (aside from special character names like `$`, which I don't think applies here).

**Comment by alandonovan** [comment]
Got it; your solution sounds reasonable. Thanks for investigating.

**Comment by brandjon** [comment]
FTR, I was going to give the same treatment to the `name` attribute as well, since it too is implicitly available on every repository rule. But on further reflection, that seems like a bad idea since the returned dictionary feeds into the resolved file machinery (we presumably wouldn't want to encourage users to omit a critical field there).
