### ISSUE TITLE
Cquery is completely broken for test_suite rule

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11042]
### Description of the problem / feature request:

Any **cquery** for any **test_suite** target always returns `Empty query results` while plain **query** works as expected.

### Bugs: what's the simplest, easiest way to reproduce this bug? 

Trivial repro: https://github.com/konste/bazel_test_suite_cquery
`bazel query hello-world-test-suite` returns `//:hello-world-test-suite`
`bazel cquery hello-world-test-suite` returns `Empty query results`

### What operating system are you running Bazel on?

Reproduces on Linux and Windows.

### What's the output of `bazel info release`?

2.2.0

**Comment by gregestren** [comment]
Reproduced. Digging in....

**Comment by gregestren** [comment]
@konste this is due to the Bazel flag [`--expand_test_suites`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--expand_test_suites):

> Expand test_suite targets into their constituent tests before analysis. When this flag is turned on (the default), negative target patterns will apply to the tests belonging to the test suite, otherwise they will not. Turning off this flag is useful when top-level aspects are applied at command line: then they can analyze test_suite targets.

This is basically saying that you can write:

    $ bazel build -- //:my_test_suite -//:test_i_dont_want_to_run

and Bazel omits `//:test_i_dont_want_to_run` from the set in `//:my_test_suite`.

But this only works with `--expand_test_suites`, which itself works by first replacing `//:my_test_suite` with the set of tests it contains, then filtering out what you don't want. The consequence being `//:my_test_suite` no longer exists.

This affects `cquery` and not `query` because `cquery` operates over the analysis phase (when that replacement happened) while `query` operates over the loading phase (before the replacement).

The easiest fix would be:

    $ bazel cquery //:hello-world-test-suite --noexpand_test_suites

That comes at the cost of not being able to exclude tests as above.

**Comment by konste** [comment]
Thank you, @gregestren, that explanation makes sense to me! But you must forgive me for the false alarm as the effect of this flag on cquery was not obvious even for yourself.

**Comment by konste** [comment]
Actually as cquery does not try to run any tests and negative (exclusion) pattern does not make sense for it, so I feel like it would be logical for cquery to imply `--noexpand_test_suites`.

**Comment by gregestren** [comment]
That sounds fair to me. I'll try to flip that.
