### ISSUE TITLE
Bazel CI: rules_kotlin is broken with Bazel@HEAD

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#11125]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1459#6212bf67-fdc1-4140-88e9-6cc21508d846
`//src/test/kotlin/io/bazel/kotlin/builder/utils:SourceJarCreatorTest` is broken with the following error message:
```
BazelTestRunner exiting with a return value of 0
JVM shutdown hooks (if any) will run now.
The JVM will exit once they complete.
 
-- JVM shutdown starting at 2020-04-14 04:02:44 --
 
================================================================================
ERROR: bazel crash in async thread:
java.lang.IllegalArgumentException: Byte string is not UTF-8.
```
Culprit: https://github.com/bazelbuild/bazel/commit/886d7d590fae2f860788a4c8ccb4624e59fc212d
Bazel Auto Sheriff: https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/119

/cc @michajlo Can you take a look to see if we should rollback the change or send a fix to rules_kotlin?

**Comment by michajlo** [comment]
IIUC the breakage was due to setStdoutBytes checking for valid utf8 and the new ByteString chunking style in 886d7d5 potentially splitting up the data in a way that produced invalid utf8. This actually uncovered a bug in the Progress api - stdout/err can be binary data, but the api uses strings, which can result in invalid data.
