### ISSUE TITLE
RESOURCE_EXHAUSTED errors should be retried indefinitely

### ISSUE THREAD

**Issue by yinfu** [bazelbuild/bazel#11145]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
RESOURCE_EXHAUSTED errors should be retried indefinitely. This specific request is to track using Bazel with Remote Build Execution but applies in general.

### Feature requests: what underlying problem are you trying to solve with this feature?

Reduce the number of failures due to RESOURCE_EXHAUSTED errors, which should go away with time.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

For RBE, can set an arbitrarily low custom override for a quota and then call it via Bazel.

### What operating system are you running Bazel on?

n/a

### What's the output of `bazel info release`?

n/a

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

**Comment by ulfjack** [comment]
Trying indefinitely is almost certainly not acceptable behavior - if the remote execution system is *already* overloaded, then retrying generally makes it *worse* and the only viable behavior is to exit the build with an error. When I say *worse*, I mean it will increase the time to recovery and can make it impossible for you to recover at all without finding and terminating a majority of running Bazel instances. I.e., you may have to shut down an even larger part of your infrastructure in order to get back into a working state.

Further reading: *Site Reliability Engineering*; Edited by Betsy Beyer, Chris Jones, Jennifer Petoff and Niall Richard Murphy

Available for free here:
https://landing.google.com/sre/sre-book/toc/index.html

I'm not against having a command-line flag or similar to control the retry behavior (if there isn't already). If you want to use that to shoot yourself massively in the foot, I won't stop you, but I don't believe that this is acceptable default behavior.
