### ISSUE TITLE
Error message for failed action includes wrong file

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#11151]
### Description of the problem / feature request:

When an action fails the error message should include a requested output file in the error message not the first one int the action. This is confusing if that output file isn't even being requested to be built. This can happen if the rule implementation combines the steps to produce different output files into a single action.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://gist.github.com/endobson/09cae63977d518748fd0ac908c3f61af

```
% bazel build //:foo2
INFO: Invocation ID: 52d440fd-5a96-4278-bf4b-e7f1d60bb62b
INFO: Analyzed target //:foo2 (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users/endobson/tmp/action-error/BUILD:4:1: Couldn't build file foo.a: error executing shell command: '/bin/bash -c false rule1' failed (Exit 1) bash failed: error executing command /bin/bash -c 'false rule1'

Use --sandbox_debug to see verbose messages from the sandbox
Target //:foo2 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.109s, Critical Path: 0.02s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

`foo.a` is completely not needed by this build, only `foo.b` is. Thus this error message should say `Couldn't build file foo.b`, or at least something that is independent of the file name if there are multiple outputs.

### What operating system are you running Bazel on?

mac os

### What's the output of `bazel info release`?

release 3.0.0

**Comment by janakdr** [comment]
Unfortunately this would be a bit tricky to fix in general. At the time an action fails, we may not know which outputs are needed (we know at least one is needed). In the case that A produces two outputs, A_important and A_unimportant, if B and C both depend on A, B runs first, and requests A_unimportant, while C would request A_important but hasn't yet executed in the build (because of scheduling) we'd still probably want to show the failure message with A_important.

Besides that issue, technically this would be somewhat tricky to implement. The message comes from [SkfyrameActionExecutor](https://github.com/bazelbuild/bazel/blob/cfe91cef9f2473836d2f8a64cdbeda84ec9ed442/src/main/java/com/google/devtools/build/lib/skyframe/SkyframeActionExecutor.java#L1598), I think. The knowledge of what other actions depend on this action, and in particular which artifact is needed, is not available there. We could potentially do some kind of retrieval of the other actions, check their inputs, and use the first output that was in those inputs, but it would be pretty complex.

The overall idea here is to tell the user what action failed to execute. I think we could add the action description (like, "Compiling foo.cc") to the error message. Would that be helpful?

**Comment by endobson** [comment]
If the idea is to tell the user which action failed then tell them that, not which output failed to build. I think it is much preferable to give the user less precise information if it is irrelevant. Thus adding information to error message without taking out the wrong file name isn't really fixing the issue.

**Comment by janakdr** [comment]
I don't think it's technically the wrong file name: the action was supposed to produce that file, and it failed to do so. But I take your point. It looks like this error message has been present internally for over 13 years, so there may be quite a blast radius if we change it. I'll take a look.
