### ISSUE TITLE
rdeps ranks do not represent number of hops

### ISSUE THREAD

**Issue by stephenchu** [bazelbuild/bazel#1115]
This may or may not be a bug, perhaps just missing proper documentation, but here is a simple observation where I think the issue lies.

Having a simple package structure of:
```
.
├── 1
│   ├── BUILD
│   └── file.txt
├── 2
│   ├── BUILD
│   └── file.txt
├── 3
│   ├── BUILD
│   └── file.txt
└── WORKSPACE
```

and having a DAG of "3 depends on 2 depends on 1":

```
$ cat 1/BUILD
package(default_visibility=["//visibility:public"])

filegroup(
  name = "file",
  srcs = ["file.txt"],
)
```
```
$ cat 2/BUILD
package(default_visibility=["//visibility:public"])

filegroup(
  name = "file",
  srcs = ["file.txt", "//1:file"],
)
```
```
$ cat 3/BUILD
package(default_visibility=["//visibility:public"])

filegroup(
  name = "file",
  srcs = ["file.txt", "//2:file"],
)
```

When I run `bagel query rdeps(//..., //1:file) --output=maxrank` to find out what depends on 1 and show corresponding number of hops to get there, I get:

```
$ bazel query 'rdeps(//..., //1:file)' --output=maxrank
0 //3:file
1 //2:file
2 //1:file
```

It's somewhat unexpected to me because `//3:file` is the farthest from `//1:file`, yet the rank is 0.

This is my Bazel version:
```
ip-10-254-0-159:~/toy/question% bazel version
Build label: head (@829d118)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main_deploy.jar
Build time: Fri Apr 1 18:04:16 2016 (1459533856)
Build timestamp: 1459533856
Build timestamp as int: 1459533856
```

**Comment by kchodorow** [comment]
I think this is WAI.  See http://bazel.io/docs/query.html#output-ranked, in particular: '"Root" nodes (those which have no incoming edges) are of rank 0, their successors are of rank 1, etc.'  //3:file is a root node, since no one depends on it.  0, 1, and 2 are indicating hops from the root node, not from your query node.  

`--output=maxrank` picks the longest possible path through the tree.  There's only one path above, but if you added a dependency on //1:file from //3:file (i.e., change `srcs` to `["file.txt", "//2:file", "1:file"]`), you'd get the same output.  If you used `--output=minrank`, you'd get:

```
0 //3:file
1 //2:file
1 //1:file
```

Does that make sense?

**Comment by stephenchu** [comment]
Yea. It makes sense now. Given the same graph, the rank numbers don't change regardless of whether the graph comes from `deps(...)` or `rdeps(//..., ...)`, according to your definition of root nodes. Thank you for your explanation.

**Comment by kchodorow** [comment]
You're welcome!
