### ISSUE TITLE
config_setting() doesn't fail when referencing non-existing rules

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#11231]
So I had a typo in this rule:

```python
  config_setting(
    name = "java11",
    values = {
        "java_toolchain": "//tools/error_prone_warnings_toolchain_java11",
    },
)
```

And was wondering, why or why configuration `java11` wasn't active.

Looking deeper revealed that I misspelled the value:

Wrong: `"//tools/error_prone_warnings_toolchain_java11"`
Right: `"//tools:error_prone_warnings_toolchain_java11"`

As the `BUILD` in `tools` package contained the referenced rule:

```python
default_java_toolchain(
    name = "error_prone_warnings_toolchain_java11",
    bootclasspath = ["@bazel_tools//tools/jdk:platformclasspath.jar"],
    jvm_opts = JDK9_JVM_OPTS,
    package_configuration = [
        ":error_prone",
    ],
    source_version = "11",
    target_version = "11",
    visibility = ["//visibility:public"],
)
```

I am wondering if error handling could be improved in this area? And the problem could have been reported, as Bazel could realize that I'm referencing a non-existing rule in `config_setting()`.

**Comment by gregestren** [comment]
This is an interesting idea. Conceptually I agree. 

The technical challenge is `config_setting` implements `values` as a `string -> string` map: (https://github.com/bazelbuild/bazel/blob/02ce2a6a9700fd09fc6a7c944d7ef79abf9dbf4e/src/main/java/com/google/devtools/build/lib/rules/config/ConfigRuleClasses.java#L188

which means Bazel treats the value as a raw string, not a label that needs to be resolved against another target.

One solution would be to use a `string -> label` map and consider `//tools/error_prone_warnings_toolchain_java11` a proper target dependency of `:java11`. That'll be hard since not everything in `values` is a label.

Another is to find where `config_setting` compares expected values against actual values and do "target exists" checking there: https://github.com/bazelbuild/bazel/blob/ec614868e65675a1d77233200298c8ce107ce228/src/main/java/com/google/devtools/build/lib/rules/config/ConfigSetting.java#L266

This might be hard since it might require Skyframe evaluation in a part of the code base that's not well-suited for it.

The final option I can think of is to have some pre-processor that looks through `values`, finds settings corresponding to label-typed flags, and adds the labels as secret dependencies to the `config_setting` (like in a `:secret-label-dependencies` attribute). That would *just work* if there was a suitable place to inject the pre-processor.
