### ISSUE TITLE
bazelisk's last_green version is 404'ing, breaking CI pipelines

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#11242]
```
$ export USE_BAZEL_VERSION=last_green
$ bazel build //src:bazel
2020/04/29 00:39:35 Using unreleased version at commit 18e8981fab5e2beaf7643df4948f0f5027341764
2020/04/29 00:39:35 Downloading https://storage.googleapis.com/bazel-builds/artifacts/ubuntu1404/18e8981fab5e2beaf7643df4948f0f5027341764/bazel...
2020/04/29 00:39:35 could not download Bazel: HTTP GET https://storage.googleapis.com/bazel-builds/artifacts/ubuntu1404/18e8981fab5e2beaf7643df4948f0f5027341764/bazel failed with error 404
```
Also reported on [Slack](https://bazelbuild.slack.com/archives/CA31HN1T3/p1588117662060300)

https://buildkite.com/bazel/rules-swift-swift/builds/1525#7104bb04-3438-465b-8198-262e44f86b8c

**Comment by jin** [comment]
The latest commit with binaries on GCS: dbc7fb2de0aaa7ae38c2866d2a84fb3bad223cf9 (https://storage.googleapis.com/bazel-builds/artifacts/macos/dbc7fb2de0aaa7ae38c2866d2a84fb3bad223cf9/bazel)

Commits on and after 18e8981fab5e2beaf7643df4948f0f5027341764 (3 hours ago) do not have binaries uploaded.

**Comment by jin** [comment]
Looks like CI caught up.

**Comment by keith** [comment]
Thanks!

**Comment by fweikert** [comment]
Root cause: The pipeline that builds and publishes Bazel binaries failed for https://github.com/bazelbuild/bazel/commit/18e8981fab5e2beaf7643df4948f0f5027341764 since GitHub returned a 500 error when trying to fetch the CI script. 

This was a transient failure, and builds at subsequent commits succeeded.

Related: https://github.com/bazelbuild/bazelisk/issues/69

I can’t find the exact comment, but some time ago I proposed to fix bazelisk by returning the last green version that actually has a binary.
