### ISSUE TITLE
HTTP(S) Proxy Support for Remote Cache Downloads

### ISSUE THREAD

**Issue by michaeleisel** [bazelbuild/bazel#11374]
### Description of the problem / feature request:
I want to use a proxy to route HTTP remote cache download requests through a packet sniffer (Charles). I've tried:
- Setting the `HTTP_PROXY` and `HTTPS_PROXY` environment variables
- Setting `-Dhttps.proxyHost=localhost` and `-Dhttps.proxyPort=8888` for `startup --host_jvm_args`
- Setting the above JVM flags for `build --jvmopt`

Unfortunately, I still don't see requests for anything besides the oauth token coming through the packet sniffer. I know there's also `build --remote_cache_proxy`, but it doesn't seem oriented towards this use case and I was having trouble getting it to transparently pass through requests with `socat`.

### Feature requests: what underlying problem are you trying to solve with this feature?

Observing the performance of Bazel remote cache calls, and identifying where the bottlenecks are. I see that the time it takes to do a build with a hot remote cache is much longer than the time it would take to download all the artifacts in a single zip, so I want to see if that's simply due to latency or what.

### What operating system are you running Bazel on?

MacOS Catalina

### What's the output of `bazel info release`?

`release 3.1.0`

**Comment by aiuto** [comment]
I'm not an expert in our network stack, but a few thoughts.

My hunch is that repository downloads use Java http fetch, and HTTPS_PROXY is supported there, while remote execution uses gRPC and thus a different proxy setup.

https://github.com/grpc/grpc/issues/9561  hints that you should try the lower case environment variable 'https_proxy', rather than the capitalized one. The code hints that too.
third_party/grpc/src/core/ext/filters/client_channel/http_proxy.cc:  char* uri_str = gpr_getenv("https_proxy");

You also might try  `-Dgrpc.enable_http_proxy=1` in host_jvm_args

**Comment by michaeleisel** [comment]
These are HTTP requests, not gRPC

**Comment by aiuto** [comment]
You do say remote execution. Did you not mean that?

**Comment by michaeleisel** [comment]
Ah I do in one place say that. But no, I mean remote caching

**Comment by omarzl** [comment]
@michaeleisel did you find a way to debug the remote cache calls? I am just stuck in the same point as you were, I tried with the env vars, the jvm args and also I modified Bazel java code (HttpCacheClient.java) but I can't make it work, I am using latest bazel version: 3.7.1

**Comment by LiushuiXiaoxia** [comment]
Does anyone solve it?

**Comment by pamgluss-slack** [comment]
My team is also experiencing this issue, trying to find a viable workaround still
