### ISSUE TITLE
Installing bazel-X.Y.Z via apt does not install bash completion script

### ISSUE THREAD

**Issue by thompsonja** [bazelbuild/bazel#11410]
It should install the script based on the documentation: https://docs.bazel.build/versions/master/completion.html#bash

Tested with a blank ubuntu:20.04 docker image, following the apt install instructions. If I do `apt install bazel-3.1.0`, the script does not appear, but following it with a `apt install bazel` does cause the completion script to appear.

**Comment by aiuto** [comment]
cc/ @meteorcloudy  (since you are working with the .deb building right now)

**Comment by meteorcloudy** [comment]
@thompsonja This is working as intended.
Because of two reasons:
1. If we include the bash completion script in bazel-3.1.0, it will be conflict with bazel package.
2. The bash completion script won't work for a binary called "bazel-3.1.0".

If you want to use a specific version of Bazel with bash completion. You can install Bazel via
eg. `apt-get install bazel=3.1.0`
