### ISSUE TITLE
Symlink action documentation is badly misleading

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11423]
### Description of the problem / feature request:

[Symlink action documentation](https://docs.bazel.build/versions/master/skylark/lib/actions.html#symlink) is probably outdated and misleading. It calls for `target_file` and `target_path` parameters neither of which exists in reality. Instead there seems to be a single parameter `target`, but it is not clear which of the two missing parameters behavior (if any) it has.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here is the [repro](https://github.com/Bazel-snippets/symlinks_repro)
It shows two documented uses of symlink action which don't work and one undocumented which seems to work.

### What operating system are you running Bazel on?

Linux/Mac/Windows

### What's the output of `bazel info release`?

3.1.0

**Comment by Yannic** [comment]
`ctx.actions.symlink` was recently extended to support `Artifact -> Artifact` symlinks (it only supported unresolved/dangling symlinks and required `--experimental_allow_unresolved_symlinks`). We did break the API of `ctx.actions.symlink`, but that's OK because the previous API was [experimental](https://docs.bazel.build/versions/master/backward-compatibility.html#what-is-stable-functionality). The new symlink functionality will be in Bazel 3.2.

See [ctx.actions.symlink in 3.1](https://docs.bazel.build/versions/3.1.0/skylark/lib/actions.html#symlink), which documents the behaviour you're seeing.

**Comment by konste** [comment]
Is there a tracking issue for that change to get more info? Specifically I wonder if the output parameter for symlink action supposed to be created by declare_file or declare_symlink? 

Also what exactly is new about Artifact -> Artifact symlinks?
Do we still need --experimental-allow-dangling-symlinks to enable it?
And finally why new symlink functionality comes in 3.2, but we already see the break in 3.1?

**Comment by Yannic** [comment]
There is https://github.com/bazelbuild/bazel/issues/7514, but it's not very useful to understand the API :/. For the new API, the documentation should explain how to use it.

For the old `ctx.actions.symlink`, you always need to declare the output file with `ctx.actions.declare_symlink()`.

For the new `ctx.actions.symlink`, it depends:
  - If you want `Artifact -> Artifact` symlinks (i.e. a symlink to `target_file`), you need to use `ctx.actions.declare_file()`.
  - For unresolved symlinks (i.e. a symlink to `target_path`), you still use `ctx.actions.declare_symlink()`.

The difference between `Artifact -> Artifact` symlinks and unresolved symlinks is that, in the `Artifact -> Artifact` case, Bazel will verify that the target exists (i.e. is a source file or declared by `ctx.actions.declare_file()`), while unresolved symlinks are basically opaque strings to Bazel and may reference files that don't even exist (which can be useful, e.g., to reference system-libraries or tools like system-installed `gcc`).

`ctx.actions.symlink` for unresolved experimental symlinks actually exists since Bazel 1.0, and continues to be experimental under the new API (i.e. you need `--experimental-allow-dangling-symlinks` if you want to use `target_path`). Making this non-experimental is tracked in https://github.com/bazelbuild/bazel/issues/10298

**Comment by konste** [comment]
@Yannic Thanks a lot for your response! It actually starts to make sense for me now. So the documentation with `target_file` and `target_path` attributes does not match the actual code not because it is obsolete, but rather because it is a little too early and reflects the state of the code which comes in 3.2.0, right?
One thing I noticed is that on Windows symlink action copies the file rather than creating symlink. Why is that difference from Linux/Mac?

**Comment by laurentlb** [comment]
cc @meteorcloudy for the Windows question

**Comment by konste** [comment]
[Here](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/windows/WindowsFileSystem.java;l=96;drc=e86a93b9fba865c3374a5a7ccdabc9863035ef78) I can see that depending on `createSymbolicLinks` property creation of symlink maybe substituted with the copy operation. I could not track where or why it maybe set to False though.

**Comment by Yannic** [comment]
> @Yannic Thanks a lot for your response! It actually starts to make sense for me now. So the documentation with `target_file` and `target_path` attributes does not match the actual code not because it is obsolete, but rather because it is a little too early and reflects the state of the code which comes in 3.2.0, right?

Exactly.

> One thing I noticed is that on Windows symlink action copies the file rather than creating symlink. Why is that difference from Linux/Mac?

I see you already found the implementation of `WindowsFileSystem`. `createSymbolicLinks` seems to be controlled by [--windows_enable_symlinks](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/runtime/BlazeServerStartupOptions.java;l=474;drc=9a6997d595fbf3447e911346034edfbde7d8b57e)(?), but I'll defer to @meteorcloudy for more detailed info (I was similarly surprised by the fact that files are copied on Windows when implementing `ctx.actions.symlink`).

**Comment by meteorcloudy** [comment]
> One thing I noticed is that on Windows symlink action copies the file rather than creating symlink. Why is that difference from Linux/Mac?

Yes, because on Windows you don't have the permission to create file symlink by default (We use Junction for creating directory symlink). To enable that, you'll need to turn on Windows Developer Mode and pass `--windows_enable_symlink` as a startup flag for Bazel. `--windows_enable_symlink` will soon be available in Bazel 3.2.0

More details at https://docs.bazel.build/versions/master/windows.html#enable-symlink-support

**Comment by tjgq** [comment]
The original issue was due to an API change, and the documentation has since been improved (in particular, to explain the difference in behavior between `target_path` and `target_file`). I don't think there's anything actionable here, but feel free to reopen otherwise.
