### ISSUE TITLE
no such package '@remotejdk_linux//'

### ISSUE THREAD

**Issue by starbrights** [bazelbuild/bazel#11439]
### Description of the problem / feature request:

While compiling bazel-native I get an error as below:

`| ERROR: /home/user/y/yocto30/sp/bazel/bazel_78IhpVnz/out/external/bazel_tools/tools/jdk/BUILD:305:1: no such package '@remotejdk_linux//': java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu-9.0.7.1-jdk9.0.7/zulu9.0.7.1-jdk9.0.7-linux_x64-allmodules.tar.gz] to /home/user/y/yocto30/sp/bazel/bazel_78IhpVnz/out/external/remotejdk_linux/zulu9.0.7.1-jdk9.0.7-linux_x64-allmodules.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '@bazel_tools//tools/jdk:remote_jdk'
| Analyzing: target //src:bazel_nojdk (237 packages loaded, 10085 targets config\
| ured)
|     Fetching @remotejdk_linux; fetching 14s
| ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis failed
`
I have no clue what is the "real" problem. The file is accessable by web-browser and curl. So I guess it is not a proxy issue (although I am behind one).
I have no clue at all what it is about the java issue. A "bitbake openjdk-8-native" has be succesfull. 
No idea what this means "no such package '@remotejdk_linux//' and who is complaining?
Or is the certification path a problem? Which certificate and where to put it in?

### Feature requests: what underlying problem are you trying to solve with this feature?

I am using the meta-tensorflow layer in Yocto. I have to cross compile it for an Cortex A9.

### What operating system are you running Bazel on?

I am using Ubuntu 18.04 as a host machine and have to cross compile it for Cortex A9, the toolchain and all the stuff is already created by Yocto - so I justed added this.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?
git://git.yoctoproject.org/meta-tensorflow
99a3d8319db51d92b9b3671816f3e023c764264f
99a3d8319db51d92b9b3671816f3e023c764264f

###  Have you found anything relevant by searching the web?

Have found some possible hints here (below), but I am not able to use this information. 

https://github.com/bazelbuild/bazel/issues/6656
https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

If answer is in here then I need a little help to understand it. Thank you.

**Comment by philwo** [comment]
The JDK that Bazel runs with is not able to download the URL https://mirror.bazel.build/openjdk/azul-zulu-9.0.7.1-jdk9.0.7/zulu9.0.7.1-jdk9.0.7-linux_x64-allmodules.tar.gz, because of this error: `PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and referenced by '@bazel_tools//tools/jdk:remote_jdk'`.

I thus assume that whatever JDK you're using to run Bazel does not have the required SSL root certificates to validate the certificate of https://mirror.bazel.build.

I'll close this, as I don't think it's a Bazel bug - but if you still need help here, please comment with the output of `bazel info` and `bazel version` and I'm happy to have a look!
