### ISSUE TITLE
git_repository doesn't pull down submodules

### ISSUE THREAD

**Issue by fzakaria** [bazelbuild/bazel#1145]
I added GRPC to my `WORKSPACE`
```
git_repository(
    name = "grpc",
    remote = "https://github.com/grpc/grpc.git",
    tag = "release-0_13_1",
)
```

However its failing to build it properly since it doesn't pull down the `third-party` submodules.

```
ERROR: /Users/fzakaria/Development/GRPC/EchoServerModel/BUILD:5:1: //EchoServerModel:proto_echo: missing input file '@grpc//:third_party/nanopb/pb_common.h'.
```

**Comment by fzakaria** [comment]
Looks like the offending line is here: https://github.com/bazelbuild/bazel/blob/0773430188885e075121ebf720c82bb05a39db21/src/main/java/com/google/devtools/build/lib/bazel/repository/GitCloner.java#L143

I'm actually a bit confused by the need to use submodules.
I guess it would re-introduce the diamond dependency problem ?
Do bazel repos just have to write themselves to be 'exportable' with `git_repository` ?
(I guess referring to //external for all third_party libraries)

**Comment by davidzchen** [comment]
Does adding `init_submodules = 1` work for you? http://bazel.io/docs/be/workspace.html#git_repository.init_submodules

The reason why we set `.setCloneSubmodules(false)` on that line is because setting it to true will actually recursively clone all submodules, which is undesirable for certain repositories, such as github.com/rust-lang/rust-installer, which recursively includes itself as a submodule and would result in an infinite loop. Setting `init_submodules = 1` will clone the first-level submodules only.

As for grpc's use of submodules, ideally, it would be better to use workspace dependencies, though I am wondering whether they are using submodules to be compatible with other build systems they are using, such as their Makefile.

@kchodorow - any thoughts on this?

**Comment by fzakaria** [comment]
I see. I'll give that a shot. 
I'm still trying to grasp external workspaces. 
On one note I love that it makes it easier for myself to onboard onto the platform and/or vend BUILD files but I'm still struggling on how to do it without re-introducing diamond dependencies (unless I'm not thinking it through)

I could pull in another workspace that builds for instance with a specific version of guava in its own third-party folder while I pull in another and now suddenly were back at gradle ;)

**Comment by davidzchen** [comment]
@jart and @hhclam have been having some discussion about ways to mitigate the diamond dependency problem in #1065 and #1071. I don't think we have a resolution yet about how to recursively include dependencies of external repositories added in their WORKSPACE files though.

+ @damienmg, @lberki

**Comment by lberki** [comment]
@fzakaria : the original idea was that for the time being, people would declare what kind of external dependencies they need in the //external package in a human-readable format, and then top-level projects would craft their WORKSPACE files in such a way that all such dependencies are satisfied.

This is essentially manual dependency resolution, but until we come up with something principled, I thought this was workable. Alas, that's not the case because people started implementing their own little ways to pull in dependencies because when these projects started, WORKSPACE files weren't smart enough :(

**Comment by fzakaria** [comment]
Okay cool. Thanks for the links, informative reads + proposals. 
Due to the current speed of development of Bazel and scope many of the existing OSS examples give a varying degree of examples to learn from which added to the confusion. 

I'll go ahead and close this.
