### ISSUE TITLE
Add new option --treat_no_test_targets_found_as_success_return_code

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#11465]
Right now the code unconditionally returns exit code 4 in this situation, see:  https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/commands/TestCommand.java#L165-L187

The problem is, that this requires some boilerplate on the CI code to differentiate between 0, 1 and 4. Gerrit Code Review has 100+ plugins, and we don't have plugin specific CI configuration, so that we would like to run generic command:

```
  $ bazelisk test plugins/{name}/...
```

The problem is to handle `NO_TEST_TARGETS` outcome on the CI side:

```bash
echo 'Running tests...'
set +e
bazelisk test plugins/{name}/...
TEST_RES=$?
set -e
if [ $TEST_RES -eq 4 ]
then
    echo 'No tests found for this plugin (tell this to the plugin maintainers?).'
elif [ ! $TEST_RES -eq 0 ]
then
    echo 'Tests failed'
    exit 1
fi
```

Instead, we would like to be able to just say this:

```
  $ bazelisk test --treat_no_test_targets_found_as_success_return_code \
     plugins/{name}/...
```

See this CL for more details: [1].

[1] https://gerrit-review.googlesource.com/c/gerrit-ci-scripts/+/268512

**Comment by ulfjack** [comment]
Some people unconditionally add an always-passing test to their command line as a workaround.

**Comment by davido** [comment]
> Some people unconditionally add an always-passing test to their command line as a workaround.

Should the CI manipulate BUILD files for SUT to achieve that workaround or what exactly do you mean by: "to their command line"? Do you have code pointer for me?

**Comment by aiuto** [comment]
I believe @ulfjack\'s suggestion was to do 
```
bazelisk test //:always_true_test //plugins/{name}/...
```
@davido  It seems to me from your script that you are making use of the 4 result
```
echo 'No tests found for this plugin (tell this to the plugin maintainers?).'
```

I am not keen on a separate flag for changing the result. Instead I would like to see "no tests found" integrated with the work for skipping non-applicable test targets. So you would ask for a structured result file saying how many tests were  found, skipped, passed, failed. Maybe even we break down skipped into skipped because of configuration non-applicability or skipped because of filtering.

**Comment by davido** [comment]
Thanks for this suggestion.
