### ISSUE TITLE
Attribute 'size' for test rules should be configurable.

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#11472]
### Description of the problem / feature request:

Test rules such as cc_test have attribute `size` which may take predefined set of string values, such as `small`, `medium`, etc. This attribute is not currently configurable, but it should be. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Justification for making this attribute configurable: We have tests which are as quick as 20 sec when compiled in `opt` mode and as slow as 120 sec in `dbg` mode. As the result we can set the test size to `small` and get a Bazel warning that it is too slow in `dbg` or we can set it to `medium` and get a Bazel warning that it is too fast in `opt`. Either way we get a Warning, so without making `size` parameter configurable there is no way to set it right.

### What's the output of `bazel info release`?

3.1.0

**Comment by jiridanek** [comment]
You can currently configure what `small`, etc. means, regarding default timeout. I set this up once so that a slow CI machine had the limits three times bigger than my workstation. Then the tests stopped timing out.

https://docs.bazel.build/versions/master/command-line-reference.html#flag--test_timeout

I personally quite dislike the warning you mention. It nudges me into finetuning something that does not seem all that important, really, compared to the time that can be sunk into getting it just right, and maintaining it that way.

The test "size" is, given what I've read so far, meant to be used as a replacement of "unit"/"integration"/"system"/"e2e" terminology used by testers, which can be approached without the biases of previous professional experience. It is not meant to be just a way to slap a default timeout on a test. (I was using it as a way to slap timeouts on tests in the CI example I mentioned in the beginning.)

**Comment by konste** [comment]
@jiridanek thank you for the information! I did not know test size timeouts are configurable. Still my issue stays as I really need to change the timeout as the function of dbg/opt configuration. And I also think that simple `timeout` parameter measured in seconds would be more flexible and easier to use than predefined buckets.

**Comment by ulfjack** [comment]
You can adjust the test timeouts when you're running debug builds without adjusting the test sizes. Docs:
https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-tests

Quote:
> The test timeout can be overridden with the --test_timeout flag, e.g. for running under certain conditions which are known to be slow.

Running tests in debug mode seems to fall exactly into this category.

**Comment by konste** [comment]
Thank you, @ulfjack! Yes I noticed `timeout` attribute for the test rules, but although it is formally different thing than the `size` attribute, practically they feel the same. And it is also not configurable unfortunately. I wonder why. I understand that timeout can be globally controlled by `--test_timeout` flag, but there is no way to set it in `.bazelrc` differently for `dbg` and `opt`, is there?

**Comment by ulfjack** [comment]
When we introduced configurable attributes, we had to exclude attributes that were accessed in a context where no configuration is available. In the case of test size and timeout, those are accessed during test filtering, which happens even before (normal) loading+analysis. Also see #11455.

Fixing this would require delaying test suite expansion / test filtering to after analysis (maybe partially delaying it based on whether the attributes use select or not). I don't see how to do that without either adding a lot of complexity or performing a lot of (potentially) unnecessary package loading.

As for `test_timeout` - the standard mechanism to set flags based on other flags is `--config`. This allows you to define sets of flags that are set together. In this case, you could create an `opt` config, and then set `--config=opt`, which would enable `--compilation_mode=opt` and set `--test_timeout` (and maybe other flags, like `--copts=-Dextra_special_opt=1`). Yes, that would require retraining yourself to use `--config=opt` or `--config=debug` instead of `-c opt` or `-c dbg`, but it might be a good idea anyway.

**Comment by konste** [comment]
Understood about `--config=opt`. Will try to introduce it to the team and change the habit of using `-c opt` directly.

`test_suite` causes us grief and confusion by itself (which may warrant separate issue). Consider this simple structure:
```
filegroup(
    name = "bin",
    srcs = [<all binary targets>],
)

filegroup(
    name = "tests",
    srcs = [<all test targets>],
    testonly = True,
)

filegroup(
    name = "everything",
    srcs = ["bin", "tests"],
    testonly = True,
)
```
People naturally expect to be able to run `bazel test everything`, but the outcome is not what they expecting - everything is build, but not tested! To test `tests` it must be `test_suite`, not filegroup. Ok, we can make it `test_suite`, but `test_suite` cannot be a source for `filegroup` `everything`.  So now we need two rules for <all test targets> collection - one `test_suite` and one `filegroup`. And still people have to remember that to build everything they can do `bazel build everything`, but to build and test everything they need to do `bazel test bin tests`. Doable but confusing and hard to explain and remember.

**Comment by jiridanek** [comment]
@konste That's more of a StackOverflow question, honestly. But that's just because I have a pretty good idea what the answer is supposed to be, and I am pretty sure that any discussion there will not result in Bazel enhancements. https://github.com/bazelbuild/bazel/issues/4257 There is a discussion somewhere whether "test everything" should imply "build everything", or whether only tests and their dependencies should be built. Can't find that now.

**Comment by konste** [comment]
@jiridanek I think I remember the discussion you are referring to. Don't want to spend time looking for it now. But the outcome of that discussion was quite positive: `bazel test ...` does the right thing - builds everything buildable and tests everything testable. Great! That discussion got closed on that positive note. But `...` does not sit well with the multi-platform builds, at least until skipping of platform incompatible targets is implemented, so instead of `...` we want to use explicit manually created target `everything` and BOOM - what works for `...` does not work for explicit target. :-(

**Comment by ulfjack** [comment]
You should be able to do something like this:
```
filegroup(
    name = "bin",
    srcs = [<all binary targets>],
)

sh_test(
    name = "bin-build-test",
    srcs = ["do_nothing_and_exit_0.sh"],
    data = [":bin"],
)

test_suite(
    name = "tests",
    tests = [<all test targets>],
    testonly = True,
)

test_suite(
    name = "everything",
    tests = ["bin-build-test", "tests"],
    testonly = True,
)
```

For multi-platform builds, skipping is the way forward.

**Comment by konste** [comment]
Clever trick!

**Comment by aiuto** [comment]
For the reasons @ulfjack mentioned, this is not an request. We'll keep it in the backlog for now, but we won't be devoting any time to try to build it.
