### ISSUE TITLE
java_common.merge does not merge jdeps

### ISSUE THREAD

**Issue by dmitrig01** [bazelbuild/bazel#11486]
### Description of the problem / feature request:

java_common.merge does not merge jdeps

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
a = JavaInfo(output_jar = ..., compile_jar = ..., jdeps = ...)
b = JavaInfo(output_jar = ..., compile_jar = ...)
print(a.outputs.jdeps) # ->  prints the jdeps file
print(java_common.merge([a, b]).outputs.jdeps) # -> None
```

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

```release 2.2.0```

**Comment by lberki** [comment]
This is WAI; the `.jdeps` file contains about a single compiler invocation.  the result of `java_common.merge()` is not the result of a Java compilation, so its jdeps file will be empty.

**Comment by jongerrish** [comment]
@lberki - What do you suggest for rules that produce more than one compiler invocation?

Specifically, I'm working on improving jdeps support in [@rules_kotlin](https://github.com/bazelbuild/rules_kotlin).

Here we use `java_common.compile()` to compile Java source which returns a `JavaInfo` and build Kotlin source ourselves producing ABI and runtime jars as well as jdeps.

Since I understand a rule can not return multiple providers of the same type, it appears that we need to merge `JavaInfo` providers from both the Java and Kotlin compiler invocations to produce a unified `JavaInfo` provider with merged ijar, class_jar + jdeps

Does this sound a reasonable approach so far? If so, how do you suggest we merge jdeps? Does anything exist to do that? We can write a tool ourselves to do this or course or is it something you would consider adding to the Java Skylark APIs, e.g: `FileApi java_common.merge_jdeps(Sequence<FileApi> mergees), seems useful to support JVM rules that support mixed source types like Kotlin does.
