### ISSUE TITLE
Default C++ toolchains feature for setting Werror

### ISSUE THREAD

**Issue by wesleyw72** [bazelbuild/bazel#11550]
### Description of the problem / feature request:

It's quite commonly desirable to be able to set `Werror` for treating warnings as errors. Currently one way of doing is by passing this in `copts`. However, it would be nicer if it was part of the default toolchain and therefore could be enabled with an `error` feature. This would also allow easy disabling it for certain targets, an  example being external libraries which don't build with `Werror`.

### Feature requests: what underlying problem are you trying to solve with this feature?

An easier way of configuring treating warning as errors.

**Comment by aiuto** [comment]
You can create your own toolchain that does that.

**Comment by wesleyw72** [comment]
@aiuto I am aware of that. The comment was to say it would be a useful thing to be provided as part of the default toolchain.

**Comment by aiuto** [comment]
We are not about to flip the default, because so many things would start breaking.  So then we have a feature to make this easier to default. Tthat reduces to another attribute on cc_* rules. It could be something like "warnings_are_errors = 'true/false/toolchain_default'.
Is that what you had in mind? 

Then the next design point is if something like that should be an attribute or simply one of a set of copts that are specially interpreted.  C++ toolchains encountering those would translate them into their equivalent.  We do that to map clang flags to msvc flags all the time (e.g  -Dfoo=bar => /D:foo=bar)
Besides warnings_are_errrors there could be similar for optimization styles/levels and probably other sets of flags.

**Comment by wesleyw72** [comment]
@aiuto I completely agree that making it a default is not a good idea. I was wondering if it could be a [feature ](https://docs.bazel.build/versions/master/cc-toolchain-config-reference.html#features) like debug/opt? That way we could enable the feature as a whole for a project, and use the 'feature = ["-warning_are_errors"]' for libraries that can't be built with it?

**Comment by aiuto** [comment]
Those are fine questions.  You just upped the game by saying `feature`. That cross-cuts across all languages. That might be an even more interesting behavior than just a C toolchain feature.

**Comment by wesleyw72** [comment]
@aiuto Yeah, that’s a good point and what I had in mind. A well defined feature name that can be used to enable warnings as errors across languages/toolchains that support it would be nice.

**Comment by wesleyw72** [comment]
@aiuto do you think this might be a good first issue for the community? As far as I can tell for C++ it would just involve adding to the existing default toolchain with a well known feature name. However, I am probably missing a lot of context.

**Comment by jheaff1** [comment]
Any update on this? I develop projects that must build on Linux (gcc) and Windows (MSVC) and this cc toolchain `feature` would be very useful indeed

**Comment by aiuto** [comment]
Maybe the place to ask about this is in
https://github.com/bazelbuild/rules_cc
