### ISSUE TITLE
error loading package 'bazel-rdx-code/external/bazel_tools/tools/android'

### ISSUE THREAD

**Issue by crorvick** [bazelbuild/bazel#11606]
### Description of the problem:

We recently upgraded from Bazel 0.23 to 3.2 and now occasionally run into the following error:
```
ERROR: error loading package 'bazel-rdx-code/external/bazel_tools/tools/android': Label '//tools/python:private/defs.bzl' is invalid because 'tools/python' is not a package; perhaps you meant to put the colon here: '//:tools/python/private/defs.bzl'?
```
We are using Bazel to build and test a C++ codebase along with supporting Python scripts.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

It is not 100% reproducible for us and I have no idea how to isolate the problem.

### What operating system are you running Bazel on?

CentOS 7.5

### What's the output of `bazel info release`?

```
release 3.2.0
```

###  Have you found anything relevant by searching the web?

Not really.

**Comment by crorvick** [comment]
Also, reportedly restarting the build without cleaning the cache or other intervention does succeed.

**Comment by razeh** [comment]
One other note: our ~/.cache directory is setup as a symbolic link to local storage.

**Comment by razeh** [comment]
We are also seeing spurious errors on directory permissions for our toolset.
We use devtoolset8 to build, and we are occasionally seeing:
      ERROR: /home/blah/bazel-code/external/devtoolset8/var/lib/stap-server (Permission denied)

Which is correct, because under external/devtoolset8:
      var -> /opt/rh/devtoolset-8/root/var

And indeed, ordinary users do not have permission to write into step-server:

drwxr-x--- 3 stap-server stap-server 4096 Nov  8  2018 bazel-code/external/devtoolset8/var/lib/stap-server//

**Comment by crorvick** [comment]
Also worth noting: we are using `--incompatible_merge_genfiles_directory=false` because we have a dependency on the `bazel-genfiles/` link that is not trivial to resolve.

**Comment by crorvick** [comment]
Another transient error.  This one looks particularly odd.
```
ERROR: <workspace path>/bazel-asdf/external/bazel_tools/tools/python/python_version.bzl:60:13: Traceback (most recent call last):
        File "<workspace path>/bazel-asdf/external/bazel_tools/tools/python/BUILD", line 102
                define_python_version_flag(<1 more arguments>)
        File "<workspace path>/bazel-asdf/external/bazel_tools/tools/python/python_version.bzl", line 60, in define_python_version_flag
                fail(<1 more arguments>)
define_python_version_flag() is private to @bazel_tools//tools/python
Loading: 254 packages loaded
```

**Comment by omathias** [comment]
I am getting similar error when I am build a java project using bazel 3.2. I have updated the $TEST_TMPDIR env variable that changes the output root. Please advice

**Comment by limdor** [comment]
I have a similar issue with a quite simple example: https://github.com/limdor/bazel-examples/tree/dd9fb62aef08ff7db5757c6a6c9fbbc2b493f2a5/third_party_dependencies
In my case using bazel 3.4.1. Cleaning the cache made it worked. Because bazel version is not pinged, could be that the cache was build with a previous bazel version, I kept a copy of the old cache in case someone wants to investigate.
The part that I am a bit concern is that in my example there is not python at all, only c++. However I use http_archive and rules_cc, not sure if internally they use some python.

**Comment by crorvick** [comment]
bump
