### ISSUE TITLE
Missing javadoc output from ConstraintSemantics and EnvironmentRule

### ISSUE THREAD

**Issue by trainman419** [bazelbuild/bazel#1161]
There are javadocs in [ConstraintSemantics.java](https://github.com/bazelbuild/bazel/blob/812227f8733a2b6679cd9b06cea26fe238afb8dd/src/main/java/com/google/devtools/build/lib/analysis/constraints/ConstraintSemantics.java#L46), but to the best of my knowledge those javadocs are not hosted anywhere.

Instead, the documentation for [compatible_with](http://bazel.io/docs/be/common-definitions.html#common.compatible_with) links directly to the source code.

The documentation for compatible_with makes it look useful for an application that I have in mind (building firmware within a larger repository), but without good documentation about ConstraintSemantics or the EnvironmentRule that it depends on, I can't properly evaluate it.

This makes it incredibly difficult to use bazel.

**Comment by trainman419** [comment]
I've been slowly piecing together how to use the environment semantics based on the docs in src/main/java/com/google/devtools/build/lib/packages/EnvironmentGroup.java and the test cases in src/test/java/com/google/devtools/build/lib/packages/PackageFactoryTest.java , but it's slow going.

**Comment by davidstanke** [comment]
Assigning to @gregestren for review

**Comment by gregestren** [comment]
We could produce a lighter weight constraints HOWTO doc, absolutely. We intentionally haven't publicized this feature *too* much because there's a very real chance that platform/toolchain work will eclipse most constraint uses.

Since this issue is old, if anyone would still like such a doc for current work they're trying to do with constraints, let me know and I can whip something together.

**Comment by RNabel** [comment]
@gregestren I just stumbled across this issue when trying to set up a way to filter targets based on the platform they are built for. 

In the process of writing our own `CROSSTOOL`s for 5 different platforms my team came across the platform / toolchain work you mention, but I have not found much documentation which clearly explains the differences in the selection mechanisms used with platforms (selected using `--platform` on the command line) and CROSSTOOLS (using `--cpu`, `--compiler`, `--glibc`), and now a third concept with the environment variables (how would does bazel decide whether you're building for `x86`? Does it only look at the host cpu? Is there a way to define custom cpu types in a `CROSSTOOL` or `platform` definition?). 

I'd really appreciate some pointers or explanations :)

**Comment by gregestren** [comment]
Hi Robin,

I apologize for my delay in responding. This thread got lost in the flood. I'm trying to do better at reducing how often that happens. If delays like this are disruptive to you please let me know and we can clarify communication channels.

It's fair to be confused about the relationship between platforms, CROSSTOOL, and environments because this is a constantly changing situation. The executive summary is:

1. [Platforms](https://docs.bazel.build/versions/master/platforms.html) & [toolchains](https://docs.bazel.build/versions/master/toolchains.html) *will* be the source of truth for CPU, compiler, etc. They will deprecate flags like `--cpu` and most of the environments this issue was created for. I believe they'll also deprecate CROSSTOOL (which is essentially a legacy-style toolchain), but I'm unsure of the exact roadmap (@mhlopko?).
2. This is an ongoing project. So now we're in an intermediate state as we steadily push more responsibility away from `--cpu`, CROSTOOL, etc. and toward platforms and toolchains. 
3. Today, `--cpu` is the source of truth for the target CPU and `--host_cpu` is the source of truth for the host CPU. This is what CROSSTOOL resolves with. It also [implicitly sets](https://docs.bazel.build/versions/master/platforms.html#built-in-constraints-and-platforms) the *target* and *host* platforms, respectively, which support rules that are set up for platform-style resolution.
4. Going forward, that process will reverse: [`--platforms`](https://docs.bazel.build/versions/master/platforms.html#specifying-a-platform-for-a-build) will be the source of truth and that will implicitly set `--cpu`. When feasible, `--cpu`, `--host_cpu`, etc. will be removed outright.
5. Environments / constraints, as described in this issue, will continue to live on somehow. Most of them will be absorbed into platforms. But environments can also imply non-platformy things (like software version, secret vs. public, and so on). So I think they'll continue to play a role for that purpose.
6. The best place to track progress is on Bazel's [configurability roadmap](https://www.bazel.build/roadmaps/configuration.html). This is a project commitment to "configuration-related" initiatives over the year, which includes all the above. It's refreshed monthly and includes links to relevant issues. It also links a [platforms roadmap](https://www.bazel.build/roadmaps/platforms.html) for a deeper dive into that.

As for custom CPU types, I believe platforms support it but `--cpu`- doesn't. @katre can confirm and, being the main driver of platforms in general, can comment more broadly.

If you want to link into platforms/toolchains, you'd need to write your Skylark rules to support them. The [toolchains doc](https://docs.bazel.build/versions/master/toolchains.html#defining-a-toolchain) has guidance, and there's an example with the [rust rules](https://github.com/katre/rules_rust) (not sure if that's the best current example to link to?).

**Comment by katre** [comment]
@RNabel Right now, unfortunately, the work to get the C++ rules working with platforms/toolchains is not entirely done. Unfortunately, the rules are very complex, and there's a lot of hidden state we discover as we work. The good news is that we do eventually want to transition away from --cpu/--compiler for C++ rules, and to --platforms. The bad news is it's going to take a while, and it's not really in a good state for people to try and use without a lot of deep diving into the code to understand how C++ toolchains work.

**Comment by mhlopko** [comment]
Small clafification, CROSSTOOL in general will not be deprecated, although [we will use Skylark](https://docs.google.com/document/d/1Nqf16jqDGWSrPp4VuRxh0iNnVBoAXsO0meDH69J9xoc/edit#heading=h.r30au8wdo4dh) to define the info that is currently defined in the CROSSTOOL file. What will change (and is changing already) is how the toolchain is selected from the crosstool.

And re env variables, I believe you are talking about CC and friends, which control  how the autoconfigured bazel C++ toolchain is generated. The main entry point is [cc_configure](https://source.bazel.build/bazel/+/0b6e04ba582087609821d12ccc53c3aa978db5c7:tools/cpp/cc_configure.bzl), and you can think of it as a process that generates CROSSTOOL and BUILD files for the toolchain. How Bazel then selects a toolchain from these files is completely standard, using `--cpu` and `--compiler`, and completely independent from environment variables.

**Comment by gregestren** [comment]
Going forward we want to discourage, not encourage this API. This all needs to get subsumed into the platform / toolchain API, which *is* documented and is continuing to take over most cases for constraints.
