### ISSUE TITLE
CPU#determineCurrentCpu() determine that the machine is 32 bits if the JRE is 32 bits

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1165]
Discovered in #1122

Assigning to Philip so he can figure out a proper fix when he's back

**Comment by damienmg** [comment]
The line of code https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/util/CPU.java


We have to tell whether this is a correct behavior or not.

**Comment by philwo** [comment]
IMHO this is the correct behavior, unless proven otherwise ;) We have enough work to do.

Of course we can also change the behavior, but is there any reason to do so? It would involve writing JNI code for multiple platforms to figure out the CPU architecture of the running OS (not only 32-bit vs. 64-bit, but also ARM and PPC), testing it, ...

**Comment by damienmg** [comment]
SGTM, maybe we should document that behavior somewhere (in the detection code maybe?)

**Comment by meisterT** [comment]
I don't think it's worth fixing or documenting.
