### ISSUE TITLE
Documentation is not specific about where select() cannot be used

### ISSUE THREAD

**Issue by trainman419** [bazelbuild/bazel#1167]
The [documentation for `select()`](http://bazel.io/docs/be/functions.html#select) says:

> It can replace the right-hand side of almost any attribute assignment so that the attribute's value depends on the Bazel flags passed in at the command line.

So I've premised the last day or so of my build-system work on being able to use `select()` within an `environment_group()`, only to find that select isn't supported in that context.

Please explicitly document the places where `select()` can or cannot be used, so that users are not surprised like this in the future.

**Comment by gregestren** [comment]
I'm doing some work that's going to expose this. As a first step each attribute's individual documentation will be marked "nonconfigurable" if it doesn't work with select. As an eventual followup I'll produce a single-page list of incompatible attributes

Of course, environment_group isn't going to appear in the former since it's undocumented. :) It's also, to be honest, "different", since it's a [function](http://www.bazel.io/docs/be/functions.html#functions), not a normal Bazel rule. Functions don't work with select because they get evaluated before we know which select path to follow.

Also note the current "read the source" way to find incompatible attributes: https://github.com/bazelbuild/bazel/blob/0773430188885e075121ebf720c82bb05a39db21/src/main/java/com/google/devtools/build/lib/rules/apple/XcodeConfigRule.java#L51

**Comment by gregestren** [comment]
Update: nonconfigurable attributes have been marked as such in the documentation for some time:  https://bazel.build/search.html?cx=012346921571893344015%3Axv_nfgpzbu4&cof=FORID%3A10&ie=UTF-8&q=%22nonconfigurable%22

It's currently not a priority to produce an aggregated, single-page list. Please reopen this if anyone needs this. We're also unlikely to document this for rules that are themselves undocumented (like environment_group).
