### ISSUE TITLE
Native providers are not hashable in Starlark

### ISSUE THREAD

**Issue by restingbull** [bazelbuild/bazel#11795]
### Description of the problem / feature request:

JavaInfo cannot be used as a key in a dict

This is fine:
```
some = provider()
duck_target = { some: "value"}
```
This is not:
```
some = JavaInfo
duck_target = { some: "value"}
unhashable type: 'Provider'
```
Nor is:
As is this:
```
some = DefaultInfo
duck_target = { some: "value"}
```

### What operating system are you running Bazel on?

macOS Catalina, 10.15.5

### What's the output of `bazel info release`?

release 3.4.1

###  Have you found anything relevant by searching the web?

https://bazelbuild.slack.com/archives/CDCEKVCHY/p1594853194023500

**Comment by restingbull** [comment]
It would very handy to be able to create provider key'd dictionaries for developing reusable toolchains.

**Comment by brandjon** [comment]
Yes, that does seem unfortunate. Internally, targets are thought of as collections of provider instances, keyed on the provider type. So it could make sense in Starlark to construct a dict from an arbitrary provider type to its value.

(On the other hand, we discourage programmatic enumeration of all providers returned by a target, in order to avoid brittle rule behavior that's overly sensitive to providers it doesn't directly work with. So perhaps that argues against constructing such dictionaries in Starlark?)

**Comment by brandjon** [comment]
Can you elaborate on how this affects toolchains?

**Comment by restingbull** [comment]
A command pattern is to pass an `attr` into a function and pull specific providers from it -- by allowing `Provider` as a hash key, a rule developer can duplicate that effect without needing to create an attribute.
