### ISSUE TITLE
Java header compilation fails to find inner class base type

### ISSUE THREAD

**Issue by jfancher** [bazelbuild/bazel#11845]
### Description of the problem / feature request:

We ran into an issue when we upgraded Guava, which moved a base type of one of its classes into another library. This new library was added as a transitive dep, but it still triggered a failure when building a header jar for one of our libraries.

We have something like this:

```java
package lib;

import com.google.common.util.concurrent.AbstractFuture;

public class Outer {
    public class Inner extends AbstractFuture<Void> {
        public Inner i() { return this; }
    }
}
```

With this `BUILD` file:
```starlark
java_library(
    name = "lib",
    srcs = ["Outer.java"],
    deps = ["@maven//:com_google_guava_guava"],
)
```

Note that `AbstractFuture` extends `InternalFutureFailureAccess` -- the latter is defined in `@maven//:com_google_guava_failureaccess`, which is a dep of `@maven//:com_google_guava_guava`.

We can build `:lib` just fine. But when we build another library that depends on `:lib`, we get:
```
Compiling Java headers liblib-hjar.jar (1 source file) failed (Exit 1)
Outer.java:7: error: could not locate class file for 
  com.google.common.util.concurrent.internal.InternalFutureFailureAccess
        public Inner i() { return this; }
```

Either of the following are workarounds:
- Add `@maven//:com_google_guava_failureaccess` as a direct dependency of `:lib`
- Build with `--java_header_compilation=false`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Full reproducer here:
https://github.com/jfancher/bazel-issues/tree/java_header_failure

I'm unsure of the full list of conditions needed for the failure, but this was as much as I was able to strip it down.

### What operating system are you running Bazel on?

Linux (WSL)

### What's the output of `bazel info release`?

`release 3.4.1`

###  Have you found anything relevant by searching the web?

No. I recall reading that there's a reduced classpath heuristic which can fail in some cases, but I can't find anything that looks like this exact problem.

**Comment by lberki** [comment]
@cushon , WDYT? This doesn't look like a bug in Bazel itself but in header compilation.

**Comment by cushon** [comment]
`com.google.common.util.concurrent.internal.InternalFutureFailureAccess` is defined in a separate jar (`external/maven/v1/https/jcenter.bintray.com/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar`) which isn't on the classpath for the turbine action.

turbine uses direct classpaths, and relies on Strict Java Deps enforcement and 'repackaging' transitively symbols that may be transitively referenced from a compilation to ensure the symbols it needs are available. The repackaging isn't happening here for the prebuilt `.jar` files, so it can't see `InternalFutureFailureAccess`.

```
$ bazel aquery 'mnemonic(Turbine, :lib)'
...
    --classpath \
    external/maven/v1/https/jcenter.bintray.com/com/google/guava/guava/29.0-jre/guava-29.0-jre.jar \
```

```
$ bazel aquery 'mnemonic(Javac, :lib)'
...
    --direct_dependencies \
    external/maven/v1/https/jcenter.bintray.com/com/google/guava/guava/29.0-jre/guava-29.0-jre.jar \
...
    --classpath \
    external/maven/v1/https/jcenter.bintray.com/com/google/guava/guava/29.0-jre/guava-29.0-jre.jar \
...
    external/maven/v1/https/jcenter.bintray.com/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar \
```

There isn't currently a way to disable that optimization (https://github.com/bazelbuild/bazel/commit/0aa176ab31c637e1f9e9b6016c8dde4e53bba66a#diff-dfb9c85604d6c64b67139342a26d2a48L420).

One option might be to have `@maven//:com_google_guava_guava` export `failureaccess-1.0.1.jar` instead of declaring it as a dep, so it gets included on the transitive classpath.
