### ISSUE TITLE
Git cloning fails: add retry option?

### ISSUE THREAD

**Issue by nitnelave** [bazelbuild/bazel#1194]
Hello,

When trying to build TensorFlow (on DockerHub), I ran into problems when cloning the dependency repositories: https://hub.docker.com/r/nitnelave/tensorflow/builds/bbhn9ycakwkbmzyqupkzjbh/

Maybe a way to get around this problem (since it happens randomly), apart from finding the root cause, would be to offer a retry option for the cloning?

It's really annoying since it ruins half of my automated builds.

Thanks!

**Comment by kchodorow** [comment]
Sorry about the lack of followup!  I get a 404 for the link.  Rerunning Bazel should be about the same penalty as automatically retrying, though.

**Comment by nitnelave** [comment]
Damn, I don't have the log anymore, I cleaned up my repository and deleted that one, sorry :/ Let's try it with this log: https://hub.docker.com/r/nitnelave/tensorflow-dependencies/builds/bq7h8kq7a7udamnsrtsyks8/

The problem with retrying is that I don't know (automatically) if Bazel failed because of that or if something didn't compile. I can't have a look and retry, because I use it in a docker building script. Plus, it should be possible for Bazel to take advantage of everything it has already downloaded for the repo to avoid downloading everything all over again.

I should be able to run bazel and have it complete properly without human intervention.

**Comment by kchodorow** [comment]
Hmm, I see what you mean, but this is a little weird.  I'm hesitant to "just retry [some number of times]," since there's no way for Bazel to know how many times to retry or if something is a retriable failure.  Perhaps Bazel should give a different exit code for download errors.  

Also, for Git in particular, unfortunately we can't do much about picking up where we left off on downloads as we're using jGit, so we're limited by its capabilities.

**Comment by nitnelave** [comment]
I don't know what's the state of the repository after failing to clone, but perhaps going into the directory and running `git pull` might fix the issue. I think Bazel cleans up after failing to clone, so it would have to be before that step.

Maybe add a `retry-on-git-fail` option, with a number, or something like that? To at least give the possibility of retrying.

**Comment by kchodorow** [comment]
Nope: http://stackoverflow.com/questions/14738219/how-to-resume-a-git-pull-clone-after-a-hung-up-unexpectedly.  Also, as mentioned, we don't use git, we use jgit (but same problem).

**Comment by nitnelave** [comment]
So what's your take on the `retry-on-git-fail` option?

**Comment by jart** [comment]
We recommend using `{new_,}http_archive` instead. For example, with GitHub, you can download anything you want like this:

- `https://github.com/bazelbuild/bazel/archive/0.4.0.tar.gz`
- `https://github.com/bazelbuild/bazel/archive/a1699bd77f1770670eac191d701757b98556b1c5.tar.gz`

Every git hosting service supports this. For this reason, `git_repository` will probably be deprecated soon.

A new commit is going to be pushed soon adding a massive amount of reliability to http_archive and friends. It will do retries. It will allow you to specify multiple mirrors. It's going to be amazing. If you migrate to http_archive and mirror files, your builds will never break again due to downloads. You're going to be so happy.

When that commit gets pushed, this issue will be closed. If you don't deem this solution adequate, let us know and we'll re-open the issue.

**Comment by pcj** [comment]
From my perspective, I find it a little unsatisfactory that the end-user should have to do the cognitive translation from `git_repository` to `http_archive`.  I just want to be able to say `go get foo/bar a169`, without having to know that `github.com/foo/bar/archive/a169.tar.gz` is the best way to get that.  

Said another way, I think completely dropping `git_repository` is a step in the wrong direction, because it says what it does.  If the implementation needs to change, fine with that.

Am I just stuck in my ways (already?)

**Comment by jart** [comment]
The reason why we recommend against it is because we want the user to have a good experience. Telling Bazel "here is a git repository" is deceptively simple and doesn't reveal the long term cost. Cloning git repositories takes a lot of bandwidth, cpu, and wall time that is unnecessary. jgit is buggy. It's not mirrored so it's less reliable and can't failover when github is down. And take into consideration last time I checked github's uptime was 98%. So then you've got Travis and Jenkins breaking left and right and people are unhappy.

That said, `git_repository` is not going to be removed. The worst we're probably going to do is stick a deprecation warning on it. 

Alternatively, we could have it translate GitHub URLs into tarballs automatically so `git_repository` can always go fast without any action necessary on the part of the user.

**Comment by jart** [comment]
By the way, when you see the commit that's about to go live, you are just not going to believe how reliable we've made http_archive, http_file, etc. I don't think it would be a stretch to say that Bazel is going to have the most reliable way of downloading files ever invented in the history of the Internet. It's incredible. You're going to be so impressed by the progress that you won't be able to contain your excitement about the prospect of using this new feature.
