### ISSUE TITLE
Uncaught dependency cycle when a config transition always creates new configurations

### ISSUE THREAD

**Issue by segiddins** [bazelbuild/bazel#11951]
### Description of the problem / feature request:

Hit an `Internal error thrown during build. Printing stack trace: com.google.devtools.build.lib.collect.nestedset.NestedSet$NestedSetDepthException` doing the following.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```starlark
# stuff.bzl
Prov = provider()

def _tr_impl(settings, attr):
    return {
        "//command_line_option:cpu": settings["//command_line_option:cpu"] + ",default",
    }

tr = transition(
    implementation = _tr_impl,
    inputs = ["//command_line_option:cpu"],
    outputs = ["//command_line_option:cpu"],
)

def _r_impl(ctx):
    return [Prov()]

def _a_impl(ctx, target):
    return []

a = aspect(
    implementation = _a_impl,
    attr_aspects = ["deps"],
)

r = rule(
    cfg = tr,
    implementation = _r_impl,
    attrs = {
        "deps": attr.label_list(
        ),
        "str": attr.string(),
        "int": attr.int(mandatory=True),
        # "_allowlist_function_transition": attr.label(
        #     default = "@bazel_tools//tools/allowlists/function_transition_allowlist",
        # ),
        "_whitelist_function_transition": attr.label(
            default = "@bazel_tools//tools/whitelists/function_transition_whitelist",
        ),
    },
)

r_2 = rule(
    implementation = _r_impl,
    attrs = {
        "deps": attr.label_list(
            aspects = [a],
        ),
    }
)
```

```starlark
# BUILD.bazel
load(":stuff.bzl", "r", "r_2")

r(
    name = "a",
    # deps = ["//package:f"]
    int = select({
        "//:b": None,
    })
)

r(
    name = "b",
    deps = [":a"],
    int = 1
)

r_2(
    name = "c",
    deps = [":b"]
)
```

Run `bazel build a` (it also fails building `b` and `c`).

I'd expect, instead, to get a dependency cycle error message (like a do if I change the select to refer to `:a`).

### What operating system are you running Bazel on?

macOS 10.15

### What's the output of `bazel info release`?

`release 3.4.1`

###  Have you found anything relevant by searching the web?

No

**Comment by gregestren** [comment]
Interesting. When I ran this I didn't get a `NestedSetDepthException` but a straight-up OOM:

```
Internal error thrown during build. Printing stack trace: java.lang.OutOfMemoryError: Java heap space

ERROR: bazel crash in async thread:
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.time.Duration.create(Unknown Source)
	at java.base/java.time.Duration.ofNanos(Unknown Source)
	at com.google.common.base.Stopwatch.elapsed(Stopwatch.java:213)
	at com.google.devtools.build.lib.profiler.CollectLocalCpuUsage.run(CollectLocalCpuUsage.java:51)
```

But I agree something is seriously off here. This looks like a straightforward dependency cycle, which should be caught by Bazel's standard cycle-checking logic.

**Comment by segiddins** [comment]
If I had to guess, the label being referenced inside the `select` (perhaps combined with it not being a real build setting target) is somehow deferring the cycle detection. It might also have to do with the transition guaranteeing that the cycle will explode out the configured target graph?

**Comment by gregestren** [comment]
I'm fairly certain I know what's going on. Yes, it's the transition.  Here's an even more minimal repro:

```py
# stuff.bzl
def _tr_impl(settings, attr):
    return {
        "//command_line_option:cpu": settings["//command_line_option:cpu"] + ",default",
    }

tr = transition(
    implementation = _tr_impl,
    inputs = ["//command_line_option:cpu"],
    outputs = ["//command_line_option:cpu"],
)

def _r_impl(ctx):
    return []

r = rule(
    cfg = tr,
    implementation = _r_impl,
    attrs = {
	"deps": attr.label_list(),
	"_allowlist_function_transition": attr.label(
            default = "@bazel_tools//tools/allowlists/function_transition_allowlist",
	),
    },
)
```

```py
# BUILD.bazel
load(":stuff.bzl", "r")

r(
    name = "a",
    deps = [":a"],
)
```

    $ bazel build //:a

The problem is because `a` self-configures itself with a new configuration, each time Bazel evaluates `a` it's technically getting a new configured target. The target is of course the same, but the configuration is new. So it's technically a new graph node and not a duplicate.

This isn't even a bug, really. Other build structures rely on this pattern, based on the assumption that different variations of the configured target ultimately reduce to an ending base case. For example:

```py
r(
    name = "a",
    deps = select){
       ":orig_configuration": [":a"],
       ":modified_configuration": []
   }))
```

This resolves perfectly well so long as the second instance of `:a` transitions away from `:orig_configuration`.

You've modeled a scenario that *doesn't* self-resolve.

Ultimately Bazel shouldn't crash. So this is a good report. But I'm not sure what the answer is. It's hard to programmatically know if a dependency structure will self-resolve (sounds suspiciously like the [halting problem](https://en.wikipedia.org/wiki/Halting_problem)!) but mass-blocking all such dependencies reduces functionality. Bazel could impose some evaluation depth limit, but even that ultimately becomes arbitrary.

Given that you have to make this happen by defining a transition that allows it, my hunch is this is best solved by documenting best practices to help transition designers avoid this risk, or maybe even have some "transition linting" tool that can warn about this.

Is this actually blocking something you need to do?

**Comment by segiddins** [comment]
No, not blocking anything. Came across it while trying to repro another bug, and saw bazel build take a minute to error out so thought I'd report it.
