### ISSUE TITLE
native.existing_rule fails to parse rule names beginning with `:`

### ISSUE THREAD

**Issue by trainman419** [bazelbuild/bazel#1195]
I'm building a macro which can take many types of things as arguments; both existing rules and raw source files.

By convention, as described in the [Labels](http://bazel.io/docs/build-ref.html#labels) section of the manual, rules should be passed with the leading colon, so when calling my macro and passing a filegroup, I pass `srcs = ":my_srcgroup"`.

When I try to determine if this is an existing rule or a file in my macro, I do:

```
for src in srcs:
  if native.existing_rule(src)
    # some things for filegroups
  else:
    # other things for file names
```

Unfortunately, native.existing_rule does not understand the leading-colon syntax for rules, and therefore always returns false for any rule name starting with a `:`

I have a workaround but it's ugly:

```
for src in srcs:
  rule_name = src
  if rule_name.startswith(':'):
    rule_name = rule_name[1:]
  rule = native.existing_rule(rule_name)
  print(src, rule)
  if rule:
    # some things for filegroups
  else:
    # other things for file names
```

**Comment by brandjon** [comment]
I imagine you could also pass the argument to the `Label` constructor, and then take the `name` field.

It seems undesirable to allow `existing_rule` to accept an optional leading colon, because that would still require preprocessing if, say, the label was specified in absolute form, or belonged to another package.

In general, we discourage using `existing_rule` (or `existing_rules`) because it leads to brittle macros.

I'll leave this issue open because we should ideally provide some uniform recommendations (or possibly API) for processing macro arguments. In particular, it's common to get tripped up by `select()`s, which are opaque to macros but not rules.

**Comment by brandjon** [comment]
Closing this issue because I think this change to the `existing_rules` API wouldn't make it simpler, and the workaround seems straightforward. We can track the general macro usability issue separately.
