### ISSUE TITLE
filegroup rule will change the order of the file list(srcs)

### ISSUE THREAD

**Issue by yicm** [bazelbuild/bazel#12047]
### Description of the problem / feature request:

`filegroup` rule will change the order of the file list(`srcs`), causing the link order in `cc_library` to change, and finally a `undefined reference to` error will appear.

### Feature requests: what underlying problem are you trying to solve with this feature?

`filegroup` rule Keep the original file list order.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

**1)** a static library git repository:

```
- include
    - a.h
    - b.h
- libs
    - liba.a
    - libb.a
```

liba depends on libb.

**2)** import the static library repositry by `new_git_repository` in WORKSPACE

```python
new_git_repository(                                                             
    name = "external_static_libs",                                                                                                                     
    remote = "xxx.git",  
    commit = "a7ee1605",                                                        
    build_file = "//bazels:external_static_libs.BUILD",                                    
)  
```

`bazels/external_static_libs.BUILD`:

```python
filegroup(
    name = "includes",
    srcs = glob(["include/*.h"])
)

filegroup(                                                                      
    name = "libs",                                                              
    srcs = glob([                                                               
        “libs/liba.a”,
        "libs/libb.a",
    ]),                                                                         
)                                                                               
   
cc_library(                                                                     
    name = "external_static_libs",                                                         
    hdrs = [":includes"],                                                       
    srcs = [                                                                    
        “:libs”,                 
    ],                                                                   
    includes = [                                                                
        "include/*.h",                               
    ],                                                                          
    linkstatic = True,                                                          
    visibility = ["//visibility:public"],                                       
)     
```

**3) build hello target**

BUILD:

```
cc_binary(                                                                      
    name = "hello",                                                             
    srcs = ["hello.cpp"],                                                                                                                   
    visibility = ["//visibility:public"],                                                                                            
    includes = [                                                                
        "external/external_static_libs/include"                               
    ],                                                                          
    deps = ["@external_static_libs"]                                                       
)       
```

### What operating system are you running Bazel on?

```
$ echo $MACHTYPE
x86_64-pc-linux-gnu
```

### What's the output of `bazel info release`?

```
$ bazel info release
release 3.3.1
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

null

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

not a git repository.

###  Have you found anything relevant by searching the web?

null

### Any other information, logs, or outputs that you want to share?

```
$ cat bazel-out/k8-fastbuild/bin/hello-2.params 
-o
bazel-out/k8-fastbuild/bin/hello
-Wl,-S
-fuse-ld=gold
-Wl,-no-as-needed
-Wl,-z,relro,-z,now
-B/usr/bin
-pass-exit-codes
-lstdc++
-lm
bazel-out/k8-fastbuild/bin/_objs/hello/hello.pic.o
external/external_static_libs/libs/libb.a
external/external_static_libs/libs/liba.a
```

**Comment by yicm** [comment]
@aiuto What other data do you need?

**Comment by ulfjack** [comment]
I think that this behavior is intentional. Does it help if you swap the order of `liba.a` and `libb.a` in the filegroup rule? Is the repro somewhere where we can access it (e.g., on GitHub)?

**Comment by aiuto** [comment]
@yicm Sorry about that. I added the label, but forgot to click the [comment] button.

I was wondering what you expected the behavior to be.
- Is this just glob in a filegroup, or glob anywhere, or filegroup alone without a glob?
- Do you expect that the globs would be in sorted order? In order of the elements of the list?

Like, @ulfjack, I think this is intentional behavior. Or at least reasonable unspecified behavior.
That is, I don't think glob should make any promises about the order of files.
If you require linking libb after liba, then you should set up an explicit dependency from liba to libb.

Back to why glob should not promise anything.
Conceptually, glob walks the file tree on disk, matches file names against the patterns, includes in output.
So, the order of files would naturally be the order they get scanned in the file system
To try to preserve an ordering where the the glob patterns were used would be extra overhead, and requires an explicit rule about what happens if two or more glob patterns match a file.
 
We could potentially order the result of a glob by name, which is of limited value.
I can also see that as a can of worms w.r.t. portability of Unicode names on different OSes.

If we are talking about filegroup alone, reordering things, I think that is also reasonable
behavior. The style for most rule attributes that are lists of files is to order them alphabetically,
Tools like buildifier do that for you. It would seem odd to have filegroup `srcs` be different than
the rest.

**Comment by yicm** [comment]
@aiuto Thank you, I understand it. This design is reasonable.

**Comment by mwette** [comment]
So filegroup documentation says `The list of targets that are members of the file group. `   But here a list is not a sequence I guess.   That very annoying, as the originator's problem shows.   Is there something that will give me an ordered list of files?

EDIT: submitted issue 27472
