### ISSUE TITLE
CLI output ignores the comment lines when referencing the issue/error.

### ISSUE THREAD

**Issue by dzintars** [bazelbuild/bazel#12057]
### Description of the problem / feature request:

CLI ignores the comment lines in BUILD files when referencing the issue/error line.
![image](https://user-images.githubusercontent.com/547420/92335095-52075c80-f09c-11ea-9b21-701ba9e1fa33.png)
Actual dependency error in particular case is on line 17

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add few comment lines `# my comment ....` in any section of BUILD file before build rule dependencies.
Add non-fetchable dependency of build rule after comment lines in BUILD file.
Build

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

`release 3.4.1`

###  Have you found anything relevant by searching the web?

- GitHub issues: https://github.com/bazelbuild/bazel/issues

Did not found relevant issues.

**Comment by brandjon** [comment]
The reported line number is the line at which the call to the build rule is made, i.e., the line where "cc_binary(" (or whatever the rule is) appears. This is because targets remember where they're instantiated but not the details of how they're constructed. This is similar to how, when you call a function that does validation on one of its parameters, the stack trace will show where you called the function but not necessarily the line of code on which you passed the offending argument.

I just verified that I get the correct line number (for the first line of the target declaration) when the target is preceded by a comment.
