### ISSUE TITLE
Bazel incompatible flags pipeline broken

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#12058]
See https://github.com/bazelbuild/bazel/issues/11885#issuecomment-687106046

> `Bazelisk + Incompatible flags` on Buildkite is broken with Bazel 3.5.0: [https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/615#1f97d2d1-4d06-454b-af61-deff7963d347/95-10](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/615#1f97d2d1-4d06-454b-af61-deff7963d347/95-104)

**Comment by meisterT** [comment]
cc @laurentlb since this might affect the 3.6 release

**Comment by philwo** [comment]
There's no `migration-3.5` tag - maybe we just forgot to do the tag stuff in the playbook: https://github.com/bazelbuild/continuous-integration/blob/master/docs/release-playbook.md#update-the-status-of-github-issues-for-incompatible-changes?

**Comment by aiuto** [comment]
I did the obvious first step and created the label.  I'll see if that works when it runs tonight.

**Comment by laurentlb** [comment]
The second step is to update the issues to use the label (https://github.com/bazelbuild/continuous-integration/blob/master/docs/release-playbook.md#start-new-migration-windows).

**Comment by aiuto** [comment]
Just adding a migration-3.5 label does not resolve the problem.
There also needs to be at least one issue with
- a migration tag for the current Bazel version
- a title that begins with   'incompatible_change'

See `fetch_incompatible_flags`
https://github.com/bazelbuild/continuous-integration/blob/b2b6568edf43303870efb36cbe9c2c04206a3f5d/buildkite/bazelci.py#L2651

But I am trying to understand what is going on. Because it is not working as I expected.
- I know we are going through that routine, because I can put in a wonky URL, and then I see the error message about 'not recognized as in incompatible flag'.
- but after I fix the title, it still fails out at line 2733

One thing that makes this flaky is testing on flag title. As written, it is not possible to include starlark defined flags in this scheme. We should probably test on an additional label. Or simply having 'incompatible_', rather than using starts_with().

**Comment by aiuto** [comment]
Next step is to investigate where the FATAL error comes from. That is not in the ci source code, nor bazel.

**Comment by meisterT** [comment]
Tony, did you prolong ongoing migration windows?

**Comment by aiuto** [comment]
No. AFAICT, that won't matter. I added at least one thing in the 3.5 window and it still fails.
But I can try that.

**Comment by meisterT** [comment]
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/624 looks like you got something working, but prolonging the migration windows still matters for the meaningfulness of the pipeline :-)

**Comment by aiuto** [comment]
It looks like having migration-3.5 on an issue is not enough. The issues must also be labeled incompatible-change. When I did that to  https://github.com/bazelbuild/bazel/issues/12061 I could get the build to start.
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/624

I missed rolling forward the migration-3.4 labels to migration-3.5
It is a little error prone that the absence of any migration changes fails only after the release is made
rather than during the release candidate phase.

I'll roll them to 3.5.

**Comment by aiuto** [comment]
The pipeline is running again with the migration-3.5 labels.
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/624

**Comment by philwo** [comment]
For future reference and release managers - the [release manager playbook](https://github.com/bazelbuild/continuous-integration/blob/master/docs/release-playbook.md) should be treated like an IKEA manual. That means: Do not try to be smart, optimize / skip / reorder steps. Just follow it and the end result will be.. well, a usable piece of furniture, or a Bazel release (depending on the manual).

Like aviation and workplace safety regulations, the playbook is written in the tears and blood of broken Bazelisks, pipelines, releases and Git branches. Assume that every step is exactly there for a reason, even if it might not be obvious. If you follow them to the letter, they are not error prone. Errors have only happened in the past, when a new release manager thought it's ok to follow them by spirit instead. ;)

**Comment by meisterT** [comment]
Let me suggest to add this statement to the top of the playbook.

**Comment by aiuto** [comment]
Not prolonging the incompatible issue labels was not intentional. I just didn't see it.  I think I looked at the first 2 steps of the "update the status ..." section, saw they were no-ops, and missed the third.

What is surprising is that the problem does not show up until after the release is pushed. That indicates that the step could really float until much later in the process.

**Comment by philwo** [comment]
@aiuto That is a good point. It might be possible to add a Bazelisk pipeline for release candidates, too.
