### ISSUE TITLE
Documentation issue: Bazel Container

### ISSUE THREAD

**Issue by jsharpe** [bazelbuild/bazel#12060]
Documentation URL: https://docs.bazel.build/versions/2.0.0/bazel-container.html

Docker run command points to 0.17 rather than the correct version for the version of the docs.

**Comment by aiuto** [comment]
Note: This is only a problem for older versions of the docxs. The versioned docs point to `latest`: https://docs.bazel.build/versions/master/bazel-container.html
This, OTOH, might still be wrong, in the sense that when the 3.5 docs are "old", they will point to `latest` rather than 3.5.  The question is what is the intent of this page.  To help you get started in general, or to get started with a particular version. The answer to this might determine if this page should be versioned or not.  The current text is essentially unversioned.

cc: @floriographygoth
