### ISSUE TITLE
TEST_UNUSED_RUNFILES_LOG_FILE should be honored like other actions

### ISSUE THREAD

**Issue by allada** [bazelbuild/bazel#12062]
### Description of the problem / feature request:
Currently it appears that `unused_inputs_list` works for `ctx.action.run` rules, however tests do not appear to go down the same code path (based on me looking through bazel source code). We would like to use `TEST_UNUSED_RUNFILES_LOG_FILE` in our remote infrastructure test harness, since we can already see when files are being accessed and auto-populate this file with the files that where never opened. However, it appears bazel does not honor this file when deciding if a test is cached or not.

We have terrible cache hit rates on a lot of our expensive (cost wise) tests because these tests are often our e2e tests. Someone might end up modifying a python file that "might" be touched by the test and we have to run the test because of how the current cache system works.

Is there currently any plan to use the `TEST_UNUSED_RUNFILES_LOG_FILE` output for better cache hits?

**Comment by tomdegoede** [comment]
We are experiencing similar issues with our e2e setup. I had this sort of working locally but seem to have lost my changes. I'll see if I can reconstruct the POC.

Two issues that I encountered:
* Currently the test action receives a Middleman Artifact as input. I had to replace this with `runfilesSupport.getRunfiles().getAllArtifacts()` because otherwise the set of inputs cannot be filtered using the actual files.
* In our specific case we receive multiple TreeArtifacts as runfile inputs. These should be expanded in the action inputs in order to filter individual files. it looks like this is done in some places in the code base already but I'm uncertain how to re-use that here.

I'm also wondering if there are any design decisions reasoning about why this was not fully implemented.

**Comment by tomdegoede** [comment]
I have re-produced my changes https://github.com/tomdegoede/bazel/commit/cc81ce9469881f790004166903619c05e83341cb for what it's worth :)

**Comment by lberki** [comment]
This is not surprising. `TEST_UNUSED_RUNFILES_LOG_PATH` is vestigial in Bazel and is used in our internal version for reporting tests that have way more inputs than they need but not for test caching.

I think it would be a nice feature but its implementation would be a little more complicated than that of `unused_inputs_list` because the inputs of tests are all runfiles.
