### ISSUE TITLE
Errors during resolving `//...` target patterns get swallowed in `--keep_going` mode

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#12148]
if `ProcessPackageDirectory` encounters an error, instead of re-throwing the exception as it should, it swallows it and only calls `reportErrorAndReturn()`, which, although it does report an error on the UI, does not raise an error to Skyframe.

This results in Bazel erroneously returning the exit code 0 even when there are errors.

Reproduction:
```
touch WORKSPACE
mkdir -p d/e/f
echo 'filegroup(name="f")' > d/BUILD
touch d/e/f/BUILD
chmod 000 d/e
bazel build -k //...; echo $?
```

This yields the exit code 0 and the message:
`ERROR: Failed to load package, for d/e, skipping: no such package 'd/e': Unable to determine the local repository for directory .../d/e` (home directory redacted)

The error message is also somewhat mysterious, but at the very least, if an error was found, Bazel should have a nonzero exit code.

**Comment by haxorz** [comment]
I think this is WAI from ProcessPackageDirectory's perspective. Assigning to @anakanemison to confirm.

**Comment by lberki** [comment]
It's definitely not a WAI from the user's perspective, is it, though?

**Comment by haxorz** [comment]
Yes, I agree. I wanted Mark's thoughts on ProcessPackageDirectory first though.

**Comment by anakanemison** [comment]
I agree with both statements, "this is not WAI from the user's perspective" and "this is WAI from ProcessPackageDirectory's perspective".

The behavior in ProcessPackageDirectory descends from this change made to the implementation of RecursivePkgFunction:

https://cs.opensource.google/bazel/bazel/+/f7ff616b36a980e344d240066c909b8995a1ea37

The problem which that change was meant to address was that a Skyframe error in the deps of an RPF node would result in a Skyframe error value for the RPF node. That error value, propagating through its parents, would prevent its ancestors from retaining any information about their other subdirectories which weren't in error. This was bad for --keep_going evaluations because the user would expect those subdirectories not in error to be acted on (e.g. built, queried, whatever).

The change in f7ff616 was to make RecursivePkgFunction handle errors in its deps by emitting an error message and returning a zero-like value. In a --nokeep_going build, the non-error zero-like value would get ignored by skyframe, and the child's error would bubble up. In a --keep_going build, the zero-like value allowed the ancestor nodes to collect and return information about their subdirectories not in error.

The emitted error event was (and is) sufficient for the query command to return a non-zero numerical exit code, on account of the error-event-detection-based mechanism query uses to determine whether a command failed. That error-event-detection behavior is unique to query. Your build command example suffers because its strategy for determining whether the command should fail works differently.

I happen to be working in this area now for FailureDetails, so I may be a good person to work on this problem.

I am not fond of query's error event sensitivity so I would not propose extending it to other commands. (I don't like it because it couples important behavior to side effects of functions instead of the values they compute.) I'm eager to hear others' ideas, but I can think of some myself.

One thing that I think wouldn't work well would be to embed non-error subdirectory information in an exception thrown by RecursivePkgFunction. Skyframe wants Skyfunction implementations to prioritize enriching errors from their deps given what information they have over signalling that they depend on unavailable information (via returning null). That would conflict with how we would want RecursivePkgFunction to evaluate in --keep_going mode: we'd want the exception it throws to be enriched with all information about non-error subdirectories, and to get that, it might need to return null. Maybe there wouldn't be any negative consequences to that deviation from Skyframe's mandate, but it's bad form.

I'd guess, having two kinds of zero-like values that ProcessPackageDirectory can return, one in the case of no errors, and one in the case of some error, would be a good place to start. The difficulty there would be propagating that "something went wrong" value through all the things that consume ProcessPackageDirectoryResults, up to the place where e.g. the 'build" command determines whether to return a zero numerical exit code. It might touch a lot of things.

**Comment by lberki** [comment]
Cheh, I gave a talk about Skyframe to the Nooglers in Munich yesterday, and I said that error handling in Skyframe was complicated, but we eventually nailed it down. Apparently, that was wishful thinking 👍 

I like the idea of the in-error return value of SkyFunctions with useful data. It appears that a SkyFunction can return the following things:

1. A "was I successful" bit (for Skyframe to act upon based on the value of `--keep_going`). This is actually a trit, because there is "all OK", there is "error" and there is "catastrophe, stop even `--keep_going`.
2. A value for SkyFunctions that depend on it.
3. A single error to report when something goes wrong and to enrich for dependent SkyFunctions.
4. Events to report to the user

Currently, we can only have one of (2) and (3), but I could imagine a world where we can have both. Then SkyFunctions would handle the propagation of (2) upwards and Skyframe would handle the propagation of (3), thereby having the best of both worlds: non-hackish partial result reporting and error handling whose correctness does not depend on the implementation of every SkyFunction.
