### ISSUE TITLE
Bazel downgrade to 3.4.1 keeps reverting to 3.5.0

### ISSUE THREAD

**Issue by nickgeorge** [bazelbuild/bazel#12185]
### Description of the problem / feature request:
Bazel 3.5.0 is unusable to me due to https://github.com/bazelbuild/bazel/issues/12069#issuecomment-698640174

So I manually install 3.4.1 using
```
$ sudo apt-get install -y --no-install-recommends    bash-completion    g++    zlib1g-dev  && curl -LO "https://github.com/bazelbuild/bazel/releases/download/3.4.1/bazel_3.4.1-linux-x86_64.deb"  && sudo dpkg -i bazel_*.deb
```

This yields `bazel --version 3.4.1`
Consistently, a  hour or so later I find `bazel --version 3.5.0`, which is again broken

### Feature requests: what underlying problem are you trying to solve with this feature?

please don't silently upgrade me to a broken version!  or any version!

### What operating system are you running Bazel on?

glinux

**Comment by meisterT** [comment]
Cc @philwo

**Comment by philwo** [comment]
Hi Nick,

your system seems to be auto-upgrading all installed Debian packages on a regular schedule. There's nothing Bazel can do about that, as we only provide the packages - only your system administrator can help you configure your computer so that this package isn't auto-upgraded.

That said, if your project needs to use Bazel 3.4.1, I would recommend to add a `.bazelversion` file to its top-level directory (next to the `WORKSPACE` file) with just the contents `3.4.1`. Then you can install Bazel 3.4.1 in addition to the latest version via `apt install bazel-3.4.1`. If you run `bazel build ...` in your project, it should then automatically use the correct version! 👍 

Hope this helps!

**Comment by philwo** [comment]
Forgot to say, please feel free to ping me on our internal chat (username philwo@) if you need help, happy to help you out. :)
