### ISSUE TITLE
https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz

### ISSUE THREAD

**Issue by alejandrolozano2** [bazelbuild/bazel#12193]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Replace this line with your answer.

### Feature requests: what underlying problem are you trying to solve with this feature?

> 
Hi!
https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz is no longer available. 
https://github.com/unicode-org/icu/archive/release-62-1.tar.gz has a different sha256.  This breaks the meta-tensorflow compilation.  Will the mirror.bazel.build be available?

Thanks!
Alejandro

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by oquenchil** [comment]
Is that tar in Bazel's workspace file or Tensorflow's? If it's Tensorflow's, please file a bug against them.

**Comment by philwo** [comment]
Hi Alejandro,

If the file is not on mirror.bazel.build, then it was never uploaded there (but people probably didn't notice until now, because Bazel automatically used the file from GitHub). Probably, because TensorFlow linked it from their WORKSPACE file, but then they didn't upload it.

I would love to help out, but unfortunately, if the sha256 on GitHub has already changed, we have no way of sourcing the original file with the old sha256 hash, so we cannot upload it. Unless someone happens to have it and can provide it to me. As @oquenchil said, please report this to TensorFlow, they will have to figure out how to fix this.
