### ISSUE TITLE
java_* rules should use srcjar as compiler inputs, instead of raw sources

### ISSUE THREAD

**Issue by asuffield** [bazelbuild/bazel#12276]
The java_* rules currently produce an action which runs all sources through singlejar to produce a .srcjar, and an action which compiles all sources to the output .jar.

In the case where some of the sources are shipped in as jars produced by the jdk jar tool, they are likely to contain timestamps which perturb the cache key. This behaviour would be substantially improved if the java_* rules were changed to compile the output of singlejar, instead of the original sources. It would also be a more precise output: the compiled jar comes from this exact srcjar, instead of coming from some other input that you can't access via JavaInfo.

**Comment by comius** [comment]
I assume java_* rules compile from sources instead of srcjar to reduce critical path.
@cushon Can you confirm?

**Comment by cushon** [comment]
The `java_` rules support compiling sources in jars, but only if that jar exists statically, e.g. the following works:

```
java_library(
    ...
    srcs = ["foo.srcjar"],
)
```

As the bug notes, the rules also support a `.srcjar` output that packages up the sources, but it doesn't use that generated `.srcjar` as the input to compilation.

> In the case where some of the sources are shipped in as jars produced by the jdk jar tool, they are likely to contain timestamps which perturb the cache key.

I'm not sure I follow this. The `.srcjar` Bazel creates has normalized timestamps. Bazel itself doesn't use `jar`, in part because the output contains timestamps, which would make outputs non-deterministic.

Is the idea that a build might create a non-deterministic `.srcjar` (e.g. in a `genrule` using `jar`) and pass that into a `java_` rule, and if the rule created an action that normalized the input `.srcjar` with singlejar it would improve caching? The preferred solution to that problem would be to change the `genrule` to produce deterministic output, instead of trying to work around it downstream.

**Comment by asuffield** [comment]
Yes - making it so that creating .jar files using the jar tool would just work. Bazel creates exactly the right .srcjar file for this, but doesn't use it.

Exposing singlejar for people to use is a more complex solution, but would also work. Currently the only readily available tool is jar; to create deterministic genrules today we would have to write custom code.

**Comment by comius** [comment]
There is a `java_common.pack_sources` function that is already exposed and should do the trick.

**Comment by cushon** [comment]
Is there a difference here between the `java_` rules compared to other rules that consume jar or zip archives? Any rule that consumes archives could set up a separate action to extract and re-create the archive with normalized timestamps to try to mitigating getting non-deterministic input, but that adds actions to the build, and is just working around the problem that another action produced the non-deterministic outputs.

Maybe the distinction is that the `java_` rules already support packaging their sources into an archive? They only do that for builds that request it. Doing that for every build, and doing that work on the critical path, would still cost something.

It would be convenient to have jar support creating archives with fixed timestamps, but there are other good ways to do that, such as singlejar, or `java_common.pack_sources`, or this example from Bazel using `java.util.jar`: https://github.com/bazelbuild/bazel/blob/817e220a47a9a8832e782417ed94cb1ee48a4a2d/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/jarhelper/JarHelper.java#L58).
