### ISSUE TITLE
Subdirectories with a WORKSPACE file can be used in the parent workspace

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#12298]
### Description of the problem / feature request:

Despite what the [documentation](https://docs.bazel.build/versions/master/build-ref.html#workspace) says, the presence of a WORKSPACE file in a subdirectory does not prevent that subdirectory from being visible to Bazel.

EDIT: However, if the subdirectory with a WORKSPACE file is referred to as a local_repository in the main WORKSPACE, Bazel will then not traverse into it.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ touch WORKSPACE
$ mkdir nested
$ touch nested/WORKSPACE
$ echo 'filegroup(name="hello")' > nested/BUILD
$ bazel build //nested:hello
# succeeds

# EDIT
$ echo 'local_repository(name="nested",path="nested")' > WORKSPACE
$ bazel build //nested:hello
# fails
```

### What operating system are you running Bazel on?

Debian testing (gLinux), repros on latest macOS

### What's the output of `bazel info release`?

release 3.6.0

**Comment by Wyverald** [comment]
cc @lberki @meteorcloudy @katre 

It's arguable whether this is a bug since some actually rely on this behavior (@meteorcloudy can give more info). But the situation where it doesn't match the docs is definitely not perfect; and we likely need to fix this for the new external deps design to work well (in particular, vendoring mode).

**Comment by lberki** [comment]
Even if people rely on this bug, it's still a bug. I was about to say that IIRC TensorFlow depends on on it, but i guess that's what @meteorcloudy said, too?

Depending on how difficult it is to fix, in the interest of not making two complex project depend on each other, you might be able to use something based on the `.bazelignore` code path to ignore just the download directory but nothing else. Not that it would be nice because you'd then special-case a directory for no apparent reason, but it's still an option, if an ugly one.

**Comment by Wyverald** [comment]
@laszlocsomor pointed out that, if the subdirectory with a WORKSPACE file is referred to as a local_repository in the main WORKSPACE, Bazel will then _not_ traverse into it:

```
# continuing on from the example in OP
$ echo 'local_repository(name="nested",path="nested")' > WORKSPACE
$ bazel build //nested:hello
# fails
```

**Comment by laszlocsomor** [comment]
> Even if people rely on this bug, it's still a bug.

Agreed. It's also inconsistent with how BUILD files are treated.

**Comment by lberki** [comment]
Woah, are you sure? A quick look at the code doesn't reveal how this could be implemented and in any case, recursive globs may also be a problem.

**Comment by Wyverald** [comment]
I am, unfortunately, sure :P The error message might give a clue as to where it's implemented:

```
$ bazel build //nested:hello
ERROR: Skipping '//nested:hello': no such package 'nested': Invalid package reference nested crosses into repository @nested: did you mean to use @nested// instead?
WARNING: Target pattern parsing failed.
ERROR: no such package 'nested': Invalid package reference nested crosses into repository @nested: did you mean to use @nested// instead?
INFO: Elapsed time: 0.212s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by lberki** [comment]
Indeed! And it's also easy to figure out what's happening after seeing the error message :)

**Comment by meteorcloudy** [comment]
> I was about to say that IIRC TensorFlow depends on on it, but i guess that's what @meteorcloudy said, too?

TensorFlow probably doesn't rely on this behaviour, but I did use this to glob all Bazel's source.
See https://github.com/bazelbuild/bazel/tree/master/tools/distributions/debian/protobuf
and https://github.com/bazelbuild/bazel/blob/f6a1805407cf286768796b7e031ca22ec83a7166/tools/distributions/debian/BUILD#L4

**Comment by katre** [comment]
Okay, now I recall. I added this check as part of #3553, and specifically only made it happen when the WORKSPACE file is referred to as a local_repository, in order to not break users who had un-used WORKSPACE files in their projects.

So this was intended when we added the check, but could be changed and reported as a slightly different error now, if we decided.
