### ISSUE TITLE
IgnoredPackagePrefixesFunction loses errors

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#12303]
Here's a short reproduction:
```
$ mkdir repo
$ touch repo/WORKSPACE
$ echo 'toolchain_type(name = "toolchain_type")' > repo/BUILD.bazel
$ mkdir main
$ echo 'local_repository(name = "repo", path = "../repo")' >> main/WORKSPACE
$ touch main/BUILD.bazel
$ cd main/
$ bazel cquery --output=starlark --starlark:expr 'target' @repo//:toolchain_type
...
FAILED: Build did NOT complete successfully
Internal error thrown during build. Printing stack trace: java.lang.NullPointerException
	at com.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment.getIgnoredPackagePrefixesPathFragments(PostAnalysisQueryEnvironment.java:235)
	at com.google.devtools.build.lib.query2.cquery.ConfiguredTargetQueryEnvironment.getTargetsMatchingPattern(ConfiguredTargetQueryEnvironment.java:293)
	at com.google.devtools.build.lib.query2.engine.TargetLiteral.eval(TargetLiteral.java:73)
	at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.eval(AbstractQueryEnvironment.java:129)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.evalTopLevelInternal(AbstractBlazeQueryEnvironment.java:113)
	at com.google.devtools.build.lib.query2.common.AbstractBlazeQueryEnvironment.evaluateQuery(AbstractBlazeQueryEnvironment.java:154)
...
```

Looks like [`PostAnalysisQueryEnvironment.getIgnoredPackagePrefixesPathFragments`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/query2/PostAnalysisQueryEnvironment.java;bpv=1;bpt=1;l=231?ss=bazel&q=PostAnalysisQueryEnvironment&gsn=getIgnoredPackagePrefixesPathFragments&gs=kythe%3A%2F%2Fgithub.com%2Fbazelbuild%2Fbazel%3Flang%3Djava%3Fpath%3Dcom.google.devtools.build.lib.query2.PostAnalysisQueryEnvironment%23441f41b4417f9463ad8c64de3ddf7a89a6eaa3bf5486293fae3b8a7ffdab3553) can't handle a null return value. It's unclear to me if this is an expected return from [`IgnoredPackagePrefixesFunction`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/IgnoredPackagePrefixesFunction.java;bpv=1;bpt=1;l=41?ss=bazel&q=IgnoredPackagePrefixesFunction&gsn=IgnoredPackagePrefixesFunction&gs=kythe%3A%2F%2Fgithub.com%2Fbazelbuild%2Fbazel%3Flang%3Djava%3Fpath%3Dcom.google.devtools.build.lib.skyframe.IgnoredPackagePrefixesFunction%2311cc35cc99cd4e8434ecf34a5c8ebb4b6f5c56b57e433e110088106378faa069) or not.

**Comment by katre** [comment]
Cc @aiuto and @c-parsons (also @juliexxia for general cqueryness): I have no idea who knows what IgnoredPackagePrefixesFunction is doing.

**Comment by c-parsons** [comment]
FWIW this looks unrelated to `--output=starlark` (using other output formats also result in the same failure)

**Comment by katre** [comment]
Oh, whoops, I should have checked that.

**Comment by juliexxia** [comment]
Looks like PostAnalysisQueryEnvironment.getIgnoredPackagePrefixesPathFragments was written by @joeleba 

Joe would you mind taking a look?

**Comment by katre** [comment]
I've tracked this further, it's not a problem with cquery at all, it's that IgnoredPackagePrefixesFunction has poor error handling. More details to come.

**Comment by katre** [comment]
In addition to the previous repro, I've managed to trigger this issue with IgnoredPackagePrefixesFunction by having an invalid repository rule: this raises an exception in RepositoryDelegatorFunction, but IgnoredPackagePrefixesFunction does not check for errors, and so the error information is lost and callers receive a null value.

**Comment by lberki** [comment]
(It appears that I'm late to the party?) `IgnoredPackagePrefixesFunction` itself is the implementation of the `.bazelignore` file, i.e. parts of the source tree that globs and `...` should not traverse into.

It looks like what happens is that:

1. `PostAnalysisQueryEnvironment` always depends on `IgnoredPackagePrefixesValue`
2. `IgnoredPackagePrefixesValue` is only requested when a label in the main repository is loaded: https://github.com/bazelbuild/bazel/blob/450c7ad65bfcffebf753159ee2b617e557ffb4fd/src/main/java/com/google/devtools/build/lib/skyframe/PackageLookupFunction.java#L105 (and when a Starlark repository is fetched, but that's not relevant here)
3. `PostAnalysisQueryEnvironment` doesn't want to mutate Skyframe, it only reads it (understandable) and relies on the analysis phase to prime it with every value it needs

I can see two band-aids:

1. Always request `IgnoredPackagePrefixesValue` in `PackageLookupFunction` (adds an extra Skyframe edge to each package not in the main repository; this is probably OK, but it's weird and unnecessary) 
2. Only request `IgnoredPackagePrefixesValue` in `PostAnalysisQueryEnvironment` when it's needed. It looks like this would also work, but the way target pattern lookup is implemented in `ConfiguredTargetQueryEnvironment.getTargetsMatchingPattern()` is quite convoluted, so I can't tell.

**Comment by katre** [comment]
The actual problem is both simpler and harder:
1.  Nowhere in Bazel's code do any callers of IgnoredPackagePrefixesValue check for errors.
2.  IgnoredPackagePrefixesValue can (after #12315 and #12317) throw InconsistentFilesystemException, RepositoryFunctionException, or IOException.

I noticed this by writing a buggy `repository_rule` (it failed in some cases to actually write any files, which leads to an IOException). While this originally caused a crash, after the first fix it **only** caused builds to fail with no useful error reporting (because callers of IgnoredPackagePrefixesFunction are ignoring the errors).

I spent a little bit of time trying to add the correct error handling, but it's complex and required too many changes. I plan to figure out who added IgnoredPackagePrefixesFunction and assign this issue to them.

**Comment by lberki** [comment]
That would be @irengrig (not anymore on the team)

**Comment by lberki** [comment]
@katre , does this mean that at least one of my above three assumptions is wrong?

**Comment by katre** [comment]
No, your assumptions aren't wrong, they're simply too focused. I originally noticed the issue with a query, but it's also present in builds. IgnoredPackagePrefixesFunction is already a dependency of PackageLookupFunction (see [here](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/PackageLookupFunction.java;drc=a5a4f47295ccb6cd81cf8732772c849b1a8b9d58;l=106) and [here](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/PackageLookupFunction.java;drc=a5a4f47295ccb6cd81cf8732772c849b1a8b9d58;l=352)).

The problem is that any error during repository loading (say, someone makes a syntax or logic error in their custom repository rule) will cause IgnoredPackagePrefixesFunction to throw an exception, but it's not being checked for (`env.getValues` vs `env.getValuesOrThrow`). That exception causes skyframe to stop execution, but no error is ever actually reported.

**Comment by katre** [comment]
The root-root cause is "no one should ever be able to call a skyfunction and ignore the error values", but that's a much bigger architectural hurdle than "add error handling to existing IgnoredPackagePrefixFunction calls".

**Comment by lberki** [comment]
Then are there two issues? `IgnoredPackagePrefixesValue` is not always a depedency of `PackageLookupFunction` because packages not in the main repository return from the function [here](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/PackageLookupFunction.java;l=95;drc=a5a4f47295ccb6cd81cf8732772c849b1a8b9d58).

that of course doesn't exclude the possibility that that value ends up being in Skyframe somehow by some other route. I haven't checked that.

I don't think people who depend on `IgnoredPackagePrefixesValue` need to do error checking. If a `SkyFunction` throws an exception, Skyframe stops the evaluation of values that depend on it unless they explicitly signal (by calling `getValuesOrThrow()`) that they want to handle errors.

**Comment by katre** [comment]
Yes, skyframe stops execution, but it never reports the actual error message, which is not helpful for users.

**Comment by lberki** [comment]
That, of course, but it's not an explanation for the crash.

**Comment by katre** [comment]
Okay, here's a reproduction of the problem: https://github.com/katre/error_demo

Take a look at the readme, but here's the TL;DR:

```
$ bazel build //:sample --extra_toolchains=@broken//...
WARNING: errors encountered while analyzing target '//:sample': it will not be built
INFO: Analyzed target //:sample (0 packages loaded, 6 targets configured).
INFO: Found 0 targets...
ERROR: command succeeded, but not all targets were analyzed
INFO: Elapsed time: 0.130s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully
```

This should report that:
1.  The repository `broken` is invalid, due to an error
2.  There are no registered toolchains of the type `//:toolchain_type`

Instead, it gives a completely useless message and the user has no idea what to do, unless they know how to attach a debugger to a Bazel process and step through toolchain resolution skyfunctions.

**Comment by lberki** [comment]
Oh, the useless message is certainly a problem! I thought it has a different root cause than the crash.

**Comment by katre** [comment]
My understanding is that the crash is because the error from IgnoredPackagePrefixesFunction is unhandled, so that when cquery starts running it gets back a null value. If the error were handled the build would have finished before then (with the error reported).

**Comment by lberki** [comment]
Errors don't cause `env.getValue()` to return null, do they?

**Comment by katre** [comment]
That's what I observed while debugging.

1.  control reaches [RegisteredToolchainsFunction](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/RegisteredToolchainsFunction.java)
   1.  this calls into [TargetPatternUtil.expandTargetPatterns](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/TargetPatternUtil.java;l=54;drc=a5a4f47295ccb6cd81cf8732772c849b1a8b9d58;bpv=1;bpt=1)
   2. This calls into `TargetPatternFunction`, which returns null, since the value isn't in skyframe
   3. Skyframe restart
2. Control reaches [`TargetPatternFunction`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/TargetPatternFunction.java)
   1.  This calls into IgnoredPackagePrefixesFunction for the repository from the pattern, which returns null, since the value isn't in skyframe
   2. Skyframe restart
3. Control reaches [`IgnoredPackagePrefixesFunction`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/IgnoredPackagePrefixesFunction.java)
   1. This calls into RepositoryDelegatorFunction for the repository, which returns null, since the value isn't in skyframe
   2.  Skyframe restart
4. Control reaches RepositoryDelegatorFunction, which processes and throws an IOException
5. IgnoredPackagePrefixesFunction restarts, gets the exception from RepositoryDelegatorFunction, and re-throws it
6. TargetPatternFunction restarts, tries to get the value for IgnoredPackagPrefixesFunction
   1.  This returns null, because the call is to `env.getValues`, not `env.getValuesOrThrow`
   2. TargetPatternFunction assumes that this means the value hasn't been calculated, and returns null to signal a skyframe restart
   3.  Skyframe notes that TargetPatternFunction returned null but requested no new nodes, and marks the value as being in error
7. RegisteredToolchainsFunction restarts, gets null for TargetPatternFunction, and then the same process as above.
8. Eventually, it works back up to the top-level Skyframe call, which notes that there was an error and prints the generic message above.

At no point can any of these skyfunctions distinguish between "the node I depend on hasn't been evaluated" and "the node I depend on has an error that isn't being reported".

**Comment by lberki** [comment]
Aand, you were indeed right. It's even there in the documentation!

https://github.com/bazelbuild/bazel/blob/b20f5122b9523381d70b52ebbb41a9a22e96b87b/src/main/java/com/google/devtools/build/skyframe/SkyFunction.java#L122

**Comment by lberki** [comment]
/cc @janakdr 

...and now with a bit fresher mind, I'm kind of curious about step 9/ii: if a dependency is in error and thus `#getValues()` returns null, what is the caller of `#getValues()` supposed to do?

It doesn't know the error so it can't do anything useful so it seems there isn't a lot of point in restarting the caller instead of bailing out, but it's documented in the above line so I suppose this is by design?

**Comment by joeleba** [comment]
>  if a dependency is in error and thus #getValues() returns null, what is the caller of #getValues() supposed to do?
AFAIK: nothing.

**Comment by lberki** [comment]
Yeah, hence my confusion: `TargetPatternFunction` does exactly nothing after it receives the null from the evaluation of `IgnoredPackagePrefixesValue`, but then how come Bazel crashes?

**Comment by katre** [comment]
@joeleba: Sure, but that error message is never surfaced to the user, which is IMO a problem.
@lberki: The crash is an interaction between the build failing (so several keys have no associated nodes), and cquery (which assumes that if the build completed all nodes are available).

**Comment by lberki** [comment]
Argh, nevermind. That makes a lot of sense and I have no idea how I didn't realize that. Thanks for your patience :)

**Comment by gregestren** [comment]
@joeleba - for next steps can you categorize / prioritize this issue?

**Comment by joeleba** [comment]
*Problem:* error message is swallowed with `--keep_going` in katre@'s example.

There are 2 ways for an error message to be printed:
1. From the SkyFunction itself. [Example](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/ConfiguredTargetFunction.java;l=417;drc=859c9acc895d7e1add7e52b9b2a4c43718b4c352)
2. Via [BuildTool](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/buildtool/BuildTool.java;l=372;drc=4009b176cb480eb2f16b86f8d05a2e2beb62f61d).

### Approach 1: Printing err message from SkyFunction.

![image](https://user-images.githubusercontent.com/10117525/97188247-99a88b80-17a3-11eb-9370-374fa8847d5c.png)

The above table is the path that Skyframe takes to reach RepositoryDelegatorFunction, where the exception originates. Along the way, we can see which underlying exceptions are wrapped in `SkyFunctionException`s, and whether they're propagated (either as-is or wrapped) until the level where the error is currently printed (`ConfiguredTargetFunction`).

We have 2 options here:
1. Propagate the IOException till it reaches a SkyFunction that can print error. The IOException should be wrapped in e.g. a new `IgnoredPackagePrefixesException` since it's bad practice to just propagate a low level exception like IOException without additional context . This approach either:
- requires substantial code change: we need to repeat this for all the exceptions along the path. It's also possible to use an existing exception class along the path to wrap this new exception, but I couldn't find an inheritance that makes sense; or
- somewhat breaks the abstraction between SkyFunctions (e.g. teaching ConfiguredTargetFunction about an exception that it didn't expect from its direct dependencies, but rather from grandchildren).
2. Print the err message in `IgnoredPackagePrefixesException`. Could result in repeated error messages in `--nokeep_going`:
![Screenshot 2020-10-26 at 16 56 30](https://user-images.githubusercontent.com/10117525/97196034-4850ca00-17ac-11eb-858a-bc4614156cca.png)

### Approach 2: Printing err message via BuildTool.

With `--nokeeping_going`, there's no problem as Skyframe bubbles the error up and eventually [prints out the error](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/buildtool/BuildTool.java;l=372;drc=4009b176cb480eb2f16b86f8d05a2e2beb62f61d).

However, with `--keep_going`, the warning message [doesn't include](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/SkyframeBuildView.java;l=744;drc=859c9acc895d7e1add7e52b9b2a4c43718b4c352) any specific error. We can simply adjust this to actually print out the error messages. *Is there a reason why we don't already do it?*

Result would look something like:
![Screenshot 2020-10-26 at 17 01 50](https://user-images.githubusercontent.com/10117525/97196653-01170900-17ad-11eb-90a9-6dc791a5eec0.png)

**Comment by katre** [comment]
Thanks for looking into this. I agree that fixing BuildTool is probably the best approach.

**Comment by joeleba** [comment]
> Would printing the error in BuildTool actually fix the crash here?

I don't think so. Haven't looked into the crash yet. This is just about the missing error message.

>  The principle is that the user should be able to tell how their code depends on the error that's being emitted.

I'm not 100% sure what you mean. Do you mean: by printing them in the SkyFunctions, we could include additional context to the printed error message so that its origin can be narrowed down?

What's your view on printing the error in `IgnoredPackagePrefixesException`?

**Comment by janakdr** [comment]
> I'm not 100% sure what you mean. Do you mean: by printing them in the SkyFunctions, we could include additional context to the printed error message so that its origin can be narrowed down?

yes, that's what I mean: you can say which target failed to analyze as a result of this failure.

If the error can be appropriately described inside IgnoredPackagePrefixesFunction (that is, it wouldn't be a mystery to the user why they should care about a random external repository throwing an error), then it makes sense to emit the error there.
