### ISSUE TITLE
Support compile_only_deps for cc_*

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#12350]
There is the closed PR https://github.com/bazelbuild/bazel/pull/8482 which wasn't merged due to a lack of a design doc. A design doc would be required due to the big semantic change that it would be to introduce such a change. Most of the friction comes from the fact that the compile_only_deps might not be needed if we had include scanning in Bazel.

A design doc should come first and should explore all the questions that come up with this topic including:
- Why don't we have include scanning in Bazel?
- Does having both features make sense?
- Is it such a disruptive change?

**Comment by bjacklyn** [comment]
We need a solution for this because unlike what the documentation implies -- that headers in `srcs` are private -- that is not actually true for remote cache hits. Private headers are part of the remote cache key; this means changes to private headers invalidate consumers who don't read them! Dotd dependency pruning helps for local builds because you usually build multiple times, but that still means the first build is always cache misses.

Has Google open sourced the include scanning anywhere? I'm imagining that if it was added to bazel as a _pruning_ operation to minimize the inputs for remote cache hits & files sent over the network for remote execution then it is more palatable. We already have dotd pruning which runs post-compilation (and I think we have lto index pruning which runs pre-lto_linking?), this would just be another in the same category except it runs pre-compilation.

Is the main concern that this makes it harder to move the cc_rules to starlark in the future? Because when that happens dotd will have to be solved in the same way, so I don't think that should prevent include scanning from being shared with the community. It would be great to hear what the concerns are with having include scanning in bazel.

Also @oquenchil in the linked PR you mentioned:
> I have never liked include scanning. Specifically, how deep ingrained include scanning is into the core of Bazel and how hard it is to pull the logic out to the leaves (the C++ rules implementation).

Could you elaborate on what you dislike about include scanning? My ideal implementation would be for the starlark language to be extended to support lazily evaluated actions so that action outputs (i.e. the include scanner action outputs) can be inspected mid-build and used in starlark to decide what the subsequent inputs should be for the corresponding compilation action. Although maybe that is too pie-in-the-sky of an idea to be implemented since it means bazel doesn't get to know everything upfront (although I don't think it introduces any problem with reproducibility) but I guess it would break the *query operations.
