### ISSUE TITLE
site: docker README.md link is turned into busted README.html

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel#1236]
If you search for "Docker rules", on [http://bazel.io/faq.html](http://bazel.io/faq.html), you'll notice that the link it points to is broken. It points to [https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/docker/README.html](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/docker/README.html) when, from looking at the original faq.md, it should be pointed to [https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/docker/README.md](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/docker/README.md). 

The easiest fix is to just point the link to [https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/docker/#readme](https://github.com/bazelbuild/bazel/tree/master/tools/build_defs/docker#readme), but it seems like there is also a bug in the document generator.

**Comment by jmhodges** [comment]
Linked PR, #1237, is a quick fix to the faq.md, but doesn't fix the underlying doc generator problem. It seems worth submitting if the fix to the generator isn't obvious, or would take a while to finish.

**Comment by davidzchen** [comment]
Thanks for catching this. One behavior of the documentation pipeline is that it converts all links to pages with the `.md` file extension to `.html` (since all the pages on the site have `.html` file extensions but the internal versions are served as `.md`).

Since the Docker rules have not been moved to their own repositories yet, the [Docker Rules page](http://bazel.io/docs/be/docker.html) on the bazel.io site is still there, and we can link to that page for now.

**Comment by davidzchen** [comment]
This was fixed by 7453175.
