### ISSUE TITLE
objc_library rules fail to link (empty *.objlist) when position-independent code is enabled

### ISSUE THREAD

**Issue by erikmchut** [bazelbuild/bazel#12439]
# Description of the problem / feature request:

objc_library rules fail when the position-independent code feature is enabled.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Build an objc_library rule with `--force_pic` or `-c dbg --features=supports_pic`

### What operating system are you running Bazel on?

Mac OSX with a custom apple crosstool

### What's the output of `bazel info release`?

release 1.2.1

###  Have you found anything relevant by searching the web?

I've looked into the bazel codebase. It appears that there is a hardcoded line in the call to `registerObjFilelistAction` to includes only object files build without pic in the intermediate objlist file. As a result, the `*.objlist` file that is generated is empty if pic is enabled.

https://github.com/bazelbuild/bazel/blob/1.1.0/src/main/java/com/google/devtools/build/lib/rules/objc/CompilationSupport.java#L1097

### Any other information, logs, or outputs that you want to share?

The error is the following
`fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file list file: bazel-out/apl-darwin_x86_64-opt/bin/c8/gui/imgui-app-archive.objlist is empty
`
This error stems from the fact that `imgui-app-archive.objlist` is indeed empty. I believe that it is empty because the object files generated in the compile step are all .pic.o, but the hardcoded line (linked above) is only looking for non-pic object files to include. It perhaps should be updated to use the value of the current bazel pic setting.

**Comment by susinmotion** [comment]
@googlewalt is this in your wheelhouse?

**Comment by googlewalt** [comment]
Sure.  I can take this.

**Comment by epertoso** [comment]
@googlewalt any update on this one? On the surface, it seems it's a matter of adding the pic object files to the action that emits the `.objlist` file, but maybe is there some other reason why this isn't the case?

As a side note, al the default macOS `apple_cc_toolchain`s don't have the `supports_pic` feature at all (it's declared [here](https://github.com/bazelbuild/bazel/blob/a04cb1bfad4734f801c48bae3070a799067bda4e/tools/osx/crosstool/cc_toolchain_config.bzl#L3516) but is not used by any toolchain except `armeabi-v7a`, which IIUC is relevant for Android, therefore never being selected for Objective-C-related actions), maybe that's why this bug isn't so noticeable.

I could try sending out a PR if there isn't any other reason to avoid this change.

**Comment by googlewalt** [comment]
Sorry for the delay.  For Apple, clang implicitly builds with `-fPIC`, so there should be no need to specify `-fPIC` yourself (in fact for most Apple CPUs, it's not even possible to turn that off.)

It's intentional that the Apple toolchain does not support the `supports_pic` feature.  That feature doesn't just set `-fPIC`, it triggers other functionality that is not useful or supported for Apple.  There is some pic-related code in the toolchain that should probably be deleted.

**Comment by jwnimmer-tri** [comment]
FYI In case it helps anyone else, I hit this problem because I accidentally had a stray `build --force_pic` in my `.bazelrc` file.  Removing that option solved my problem.
