### ISSUE TITLE
Expose bzl_library for @bazel_tools//tools/build_defs/repo

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#12444]
I reference `@bazel_tools//tools/build_defs/repo:http.bzl` in a Starlark file.

However, I am unable to create a bzl_library (and thus Stardocs) for it.

* Attempt `@bazel_tools//tools/build_defs/repo:lib`: Target/package doesn't exist.
* Attempt `@bazel_tools//tools/build_defs/repo:http.bzl`: Not public

**Comment by philwo** [comment]
@pauldraper Is the suggested fix to make http.bzl public?

**Comment by pauldraper** [comment]
@philwo either make the file public, or make it part of a public bzl_library. (IDK if Bazel has bzl_libraries....I'm guessing not.)

**Comment by philwo** [comment]
I don't understand why `http.bzl` is not publicly visible. In `BUILD.repo` it is exported via this line:

https://github.com/bazelbuild/bazel/blob/35c27f3eb9a040d8f68280f34dd977d7fe894099/tools/build_defs/repo/BUILD.repo#L1

And the documentation says: "By default, file targets are visible only from the same package. To make a file accessible from another package, use exports_files. If the call to exports_files specifies the visibility attribute, that visibility applies. Otherwise, the file is public (the default_visibility is ignored)." (https://docs.bazel.build/versions/master/visibility.html#visibility-of-a-file-target)

So it should work, right? 🤔

**Comment by pauldraper** [comment]
Yeah, I would think so...IDK how the .repo mechanism works.

**WORKSPACE.bazel**

```py
bind(
    name = "test",
    actual = "@bazel_tools//tools/build_defs/repo:http.bzl"
)
```

```
$ bazel version
Build label: 3.7.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Nov 24 17:38:30 2020 (1606239510)
Build timestamp: 1606239510
Build timestamp as int: 1606239510
```

```
$ bazel build //external:test
ERROR: /home/paul/rivet/foo/WORKSPACE.bazel:1:5: in bind rule //external:test: target '@bazel_tools//tools/build_defs/repo:http.bzl' is not visible from target '//external:test'. Check the visibility declaration of the former target if you think the dependency is legitimate. To set the visibility of that source file target, use the exports_files() function
ERROR: Analysis of target '//external:test' failed; build aborted: Analysis of target '//external:test' failed
INFO: Elapsed time: 5.027s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 6 targets configured)
```

**Comment by brandjon** [comment]
The `export_files` decl was [added](https://github.com/bazelbuild/bazel/blame/35c27f3eb9a040d8f68280f34dd977d7fe894099/tools/build_defs/repo/BUILD.repo#L1) on 2020-11-02, so it likely isn't in the bazel version you're using. This issue should be fixed at head.
