### ISSUE TITLE
git_repository should provide shallow fetch option

### ISSUE THREAD

**Issue by robinp** [bazelbuild/bazel#1246]
It doesn't seem to be useful to pull all the history - why not specify --depth=1 ? But maybe I'm missing some usecase.

**Comment by davidzchen** [comment]
+cc @kchodorow

Unfortunately, [jgit does not support shallow clones](http://stackoverflow.com/questions/11475263/shallow-clone-with-jgit). The only way to support shallow clone would be either to 1) add support for shallow cloning to jgit or 2) rewrite the `git_*` rules in Skylark and use the Git binaries directly.

To me, (2) would be more preferable since it is much simpler to do than (1). I'll go ahead and put together a proof of concept.

**Comment by kchodorow** [comment]
I think (2) is a good idea, since it's been tough getting jgit to behave the same way git would with auth, proxies, etc.

**Comment by johnynek** [comment]
2) has been done:

https://github.com/nelhage/bazel_git_repositories

**Comment by davidzchen** [comment]
Awesome! Since there are lots of issues opened for various features or bugs that would be covered by using bazel_git_repositories rather than the native rules, let's de-dup them against #1408.
