### ISSUE TITLE
Starlark: object validity checks are performed inconsistently in public API

### ISSUE THREAD

**Issue by stepancheg** [bazelbuild/bazel#12481]
* `StarlarkList.copyOf` and `Dict.copyOf` perform validity check
* `StarlarkList.addElement` does not perform validity check
* `Dict.putEntry` does not perform validity check
* `Tuple.copyOf` does not perform validity check

So, in some cases, users are protected from feeding invalid values into Starlark, while in others they aren't. Feeding an invalid object into a Starlark interpreter accidentally is really easy.

In addition to that, certain safe functions like `Dict.values0` perform validating invocation `StarlarkList.copyOf` wasting CPU on operations which cannot fail.

This is inconsistent and suboptimal.

I see several options how to handle this.

## Remove the validity checks

Starlark public API does not have too many users, we put warnings in javadocs, attribute that to Java language limitations, and that's it.

Additionally, we can have a global JVM property `-Dstarlark.strictApiChecks=true` (off by default) to enable these checks at runtime to help debugging tests or Bazel itself.

And additionally, we improve diagnostics on failures. For example, when object does not match native function parameter in `BuiltinFunction.checkParamValue`, before failing with `parameter '%s' got value of type '%s', want '%s'`, we perform an additional check that the argument is actually a valid Starlark object.

That would be my preferred option.

## Remove special handling of `String` and `Boolean`

Make them `StarlarkValue`, so we could put `StarlarkValue` in parameter types and make javac perform these validations at compile time.

The downside here is more memory consumed by `StarlarkString` objects, like 20 bytes per object, and it's hard to estimate how bad it would be in practice. This might be dangerous, so I'm hesitant to use this option, but the code will look nice and clean.

## Create safe (default)/unsafe (fast) function pairs

Explicitly name non-validating functions `xxxUnsafe` or `xxxUnchecked`, use unsafe functions privately, and let users decide what's more important for them, performance or safety.

The downside is a lot of boilerplate code in the Starlark implementation.

## Validate inputs unconditionally

Insert validation checks in all public APIs, even in APIs used internally. That would hurt performance, I don't consider this option.

There are certain optimisations of Starlark I plan to implement, this inconsistency gets in the way. Let's decide what to do about it, and I can send a PR implementing the decision?

CC @alandonovan @laurentlb

**Comment by alandonovan** [comment]
I'm sure we all agree that the ideal outcome is that checks are thorough and unconditional yet have negligible dynamic cost.  In recent commits, increased the checks' coverage of the public API (though more is still needed), and attempted to measure the CPU cost, of which I am always conscious, and was unable to detect any regression---even each check would appear to cost one last-level cache miss in general.  So, before we consider complicating the API (by adding conditional checks or safe/unsafe pairs of functions) I would like to see evidence that the dynamic cost is actually a problem. Don't dismiss this option until then.

Introducing a common supertype for all Starlark values would solve a great many design problems, but I don't believe it is feasible. Defining StarlarkBool would be easy, much like StarlarkInt was, because few functions accept them as parameters, it's easy to handle "return bool" and "return int", and the type is rarely used as a type parameter (e.g. list of int). But this would not be the case for StarlarkString: even if we made it "unsafely" share its representation with j.l.String, there are a vast number of Bazel built-in functions that interoperate with List<String> and Map<String, ?>, and all such code would need to do expensive reboxing operations.
