### ISSUE TITLE
aquery ActionKey interprets --action_env inconsistently

### ISSUE THREAD

**Issue by wchargin** [bazelbuild/bazel#12561]
### Description of the problem / feature request:

The `ActionKey` output of `bazel aquery` incorporates `--action_env`
values that are given in explicit `KEY=VALUE` form, but not just as
`KEY`. This is inconsistent with the actual RBE cache.

Underlying problem: setting up a remote cache that’s populated on one
machine and read from another, and trying to align the cache keys. The
natural approach is to use `bazel aquery`, but `bazel aquery` says that
the cache keys are the same even though they’re cache-missing.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ >WORKSPACE
$ >BUILD printf '%s\n' 'genrule(name="gen", outs=["f"], cmd=">$@")'
$ PATH=/tmp/one ~/bin/bazel aquery --action_env=PATH //:gen 2>/dev/null | grep ActionKey
  ActionKey: 1894a571299ce63b69d3954e14ba6b7e310bdfc092309f86820f61ab1baf6e2c
$ PATH=/tmp/two ~/bin/bazel aquery --action_env=PATH //:gen 2>/dev/null | grep ActionKey
  ActionKey: 1894a571299ce63b69d3954e14ba6b7e310bdfc092309f86820f61ab1baf6e2c
$ ~/bin/bazel aquery --action_env=PATH=/tmp/one //:gen 2>/dev/null | grep ActionKey
  ActionKey: dc034c7ecfd6be13b385d7ab68e8b9e2cd067139577447ec90b2f666ef2cfec2
$ ~/bin/bazel aquery --action_env=PATH=/tmp/two //:gen 2>/dev/null | grep ActionKey
  ActionKey: 1957e4f434180a5119fb1998c1817d5d6b28c72b11c0dc63f50d23dd1959d253
```

…and if you have a remote cache set up, then changing `PATH` and setting
`--action_env=PATH` does cause a cache miss, even though Bazel reports
the action key as not having changed.

### What operating system are you running Bazel on?

gLinux (like Debian); also straight Debian 10 on GCE

### What's the output of `bazel info release`?

release 3.7.0

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

I read [the `aquery` FAQ entry][faq], “The ActionKey remains the same
even though the content of an input file changed.” It’s not clear to
me that this is the same issue, since that FAQ entry says that “Changes
to the […] environment […] should affect the key”.

What I really want to know is: “what exactly is determining whether this
will be a remote cache hit, and what do I have to change to get these
two systems to align their keys?” If `aquery` is not the right tool for
that, please suggest a better workflow.

[faq]: https://docs.bazel.build/versions/master/aquery.html#action-key

### Any other information, logs, or outputs that you want to share?

Nay.

**Comment by aiuto** [comment]
I'm not sure if this is a bug or how-to request.

cc: @joeleba  It looks like you wrote that text, maybe you can clarify.

**Comment by wchargin** [comment]
From my perspective, it looks like at the very least a documentation
bug, since the documentation implies that `--action_env=PATH=$PATH`
means the same thing as `--action_env=PATH`, but those behave
differently under `aquery`.

It’s also a how-to request for the potential XY problem of “I want to
align these two systems to hit the same cache”. If there is a nice way
to do that, I think that it would be a great addition to the docs. But
I understand that general how-to requests are better suited for other
fora, so feel free to exclude that from the scope of this issue. Just
wanted to mention to provide the broader context.

**Comment by joeleba** [comment]
> I read the aquery FAQ entry, “The ActionKey remains the same
even though the content of an input file changed.” It’s not clear to
me that this is the same issue, since that FAQ entry says that “Changes
to the […] environment […] should affect the key”.

This part of the aquery documentation was extracted from [ActionAnalysisMetadata](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/actions/ActionAnalysisMetadata.java;l=61-88;drc=8b856f5484f0117b2aebc302f849c2a15f273310), as aquery just displays this metadata after the analysis phase without modification. Perhaps @janakdr (the author of the doc in ActionAnalysisMetadata) has some ideas on why the action keys stay the same if we have `--action_env=PATH` and modify the `PATH` env values, and whether that's expected?

The FAQ also mentioned that this is not to be confused with [RemoteCacheClient#ActionKey](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/common/RemoteCacheClient.java;l=38;drc=21577f202eb90ce94a337ebd2ede824d609537b6). I'm not familiar with how these values can be aligned. Maybe the remote execution team is more familiar.

**Comment by janakdr** [comment]
The lossiness happens in [ActionEnvironment#addTo](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/actions/ActionEnvironment.java;l=235;drc=a9b118bbe1d7c6c4be4524547dddc1fc21ba60ad). We just add the names of the "inherited" environment variables, not the values.

This is handled specially in [ActionCacheChecker](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/actions/ActionCacheChecker.java;l=347;drc=3ad1580c8162a63b34541f6a721e9ed18b969acb).

It looks like aquery needs to do something more like what the ActionCacheChecker does: compute the used environment and append it as a digest. We don't want to stick this computation into the action key itself because that is expected to be unchanged across builds: we cache the computation.
