### ISSUE TITLE
--experimental_windows_watchfs makes folders with subfolders undeletable

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#12573]
### Description of the problem / feature request:

The flag `--experimental_windows_watchfs` on Windows blocks deletion of any workspace folder with subfolders and files in the subfolders.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. On Windows make sure Bazel server is not running. Shutdown it if necessary.
2. At the root of the workspace create folder `Foo`, inside it create folder `Bar` and inside `Bar` create a file `Baz`. The content of the file does not matter. 
3. Start Bazel server, for instance run `bazel info`.
4. Try to delete the folder `Foo` with Explorer or anything. The folder cannot be deleted. This is the problem.
5. The file `Baz` and the folder `Bar` can be deleted and after that the folder `Foo` can be deleted too. Or shutdown Bazel server and then the folder `Foo` can be deleted directly.

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

3.7.0

### Any other information, logs, or outputs that you want to share?

This issue is a follow up for #11619 
Attn: @tomdegoede

**Comment by tomdegoede** [comment]
This is due to windows internals for watching the file system which locks parent directories of folders it's watching. I have very rarely encountered the issue (probably because deleting folders is not so common). It also seems to only occur in certain places. For example in the explorer I can delete the folder but from powershell I cant. I'm not planning to look into this further since we are not running into it and it would require a bigger overhaul either changing to junctions to symlinks or having a background process constantly process changes using a recursive watcher.

**Comment by konste** [comment]
Understood. Let's keep the issue opened though to help other people who may try to use `--experimental_windows_watchfs` and encounter a similar problem.
