### ISSUE TITLE
FR: `http_archive` should support retrying `IOException` for the same URL

### ISSUE THREAD

**Issue by suzaku** [bazelbuild/bazel#12599]
### Description of the problem / feature request:

The problem I have is similar to #8974 but different.

In my case, I don't have fallback URLs, so I want to retry the same URL after a short period of time. Currently, I can list the same URL multiple times in `urls` to implement retry, but there's no way I can configure `bazel` to wait for several seconds before retrying.

### Feature requests: what underlying problem are you trying to solve with this feature?

Add support for `http_archive` to retry a single URL directly and insert waiting before retries.

**Comment by ywmei-brt1** [comment]
Can you please give me some instructions or hints for how to work around with this if we don't have `retry`?

The problem is our codebase is depending on llvm, and we use http_archive to import it in workspace file. But often, this import will fail on pre-submit for 

```
RROR: //:include_scanner :: Error loading option //:include_scanner: no such package '@llvm//utils/bazel': java.io.IOException: Error downloading [https://github.com/llvm/llvm-project/archive/c4c5e79dd4b4c78eee7cffd9b0d7394b5bedcf12.zip] to /Volumes/BuildData/tmpfs/tmp/build_output/ff05699b48cc86b57d1674e64bd311b3/external/llvm/temp17610850666583603663/c4c5e79dd4b4c78eee7cffd9b0d7394b5bedcf12.zip: java.net.SocketTimeoutException: Read timed out
```

All we have to do it to manually retry the presubmit.

Thank you very much.
