### ISSUE TITLE
Support --test_lang_filters for non-official _test rules

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#12618]
For example, with a `go_test` target using rules_go, I'd hope to `--test_lang_filters=go` but get `WARNING: Unknown language 'go' in --test_lang_filters option` as documented

https://docs.bazel.build/versions/master/user-manual.html#flag--test_lang_filters
> list of test languages for languages with an official *_test rule

Of course as Bazel makes progress on moving rules to starlark I'd expect these "official" test rules to go away, so I hope there is a plan for having starlark rules contribute their "lang" in some way to keep this feature working.

**Comment by katre** [comment]
No one has worked on `--test_lang_filters` in quite some time. I'm going to assign this to the rules team so that @lberki can decide if this is functionality to keep or to deprecate.

In the meantime, you can work around this with `bazel query`:
```
$ bazel query 'kind(go_test, //...)' | xargs bazel test
```

Definitely clunkier, but it will get the job done, and you can add additional filtering to the query.

**Comment by alexeagle** [comment]
At some point this started working and I have documented it on rules like rules_js.
