### ISSUE TITLE
Make the execution root structure match that of the runfiles tree

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1262]
Followup to #848.  Now we have execroot paths like:

```
output_base/execroot/local_repo/external/another_repo/foo/bar
```

but we want the execution root paths to look like:

```
output_base/execroot/another_repo/foo/bar
```

(Not exactly a bug, but we don't have an "improvement" category.)

**Comment by kchodorow** [comment]
One complication with this is what to do with outputs.  For the main repository, you get the output of //foo:bar in:

```
bazel-out/local-fastbuild/bin/foo/bar
```

Bazel uses `bazel-out/local-fastbuild/bin + execPath` for these files, which doesn't work great when the execPath is ../another_repo/foo/bar.  Once alternative is `bazel-out/local-fastbuild/bin/external/another_repo/foo/bar`, I'm going to talk to @gregestren about his plans for changing output dirs for configurations and see if this could piggypack on any of that.

**Comment by kchodorow** [comment]
Rolling back due to #1422.

**Comment by kchodorow** [comment]
Some breakages:

* Android integration test: http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/71/console
* Go unhappy w/ buildifier: http://ci.bazel.io/job/buildifier/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/9/console
* Windows: http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.7,PLATFORM_NAME=windows-x86_64/609/console
* http://ci.bazel.io/job/TensorFlow_Serving/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/158/console
* http://ci.bazel.io/job/TensorFlow/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/273/console
* .gitignore causing problems: http://ci.bazel.io/job/skydoc/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/112/console

**Comment by damienmg** [comment]
Rollback so reopening :)

**Comment by kchodorow** [comment]
Change was rolled back, this shouldn't have been closed.

**Comment by johnynek** [comment]
You mention `execroot`, but will this also change the path in `bazel-bin` or is that one and the same?

For instance, in 0.4.4, external repos are still in `external/some_repo_foo/` and the current repo is at the root of `bazel-bin`.

This actually creates a pain for thrift support across repos because thrift imports are (somewhat terribly) based on file paths. So, we need to know the relative path to the other thrift. This means if repo A has thrift that depends on repo B, and repo C then includes repo A to use that thrift, it will fail because the path to B from A's view (in A's repo) has B as external, but from C's repo both A and B are external which changes their relative paths.

This creates a situation where we can have 1 level of nesting in external repos, but not more, which makes us sad 🐼.

**Comment by kchodorow** [comment]
In the brave new world, everything will be a siblings.  So you'll have:

```
<output_base>/
  execroot/
    some_repo_foo/
    A/
    B/
    C/
```

Does that work for your use case?

**Comment by johnynek** [comment]
Thanks for your reply @kchodorow. I'm not sure I totally follow the plan.

Right now, for instance, `bazel-bin` links into `execroot/some_repo_foo/local-fastbuild/bin`. In there, I can see `external/....`

After this change, will paths in external be gone, so we would see:
```
execroot/
  A/local-fastbuild/bin
  B/local-fastbuild/bin
  C/local-fastbuild/bin
```
?

I'm not sure if that would actually matter for my question. I think as long as the path that objects think they are on is not `external/A/foo` but just `foo`, things will work as we want.

To be honest, it is not always clear to track what things do and don't care about path sub-strings.

**Comment by kchodorow** [comment]
Exactly, there will be a separate `repo/local-fastbuild/{bin,genfiles,testlogs,etc.}` output directory for each repository.  No external/ anywhere!

> To be honest, it is not always clear to track what things do and don't care about path sub-strings.

I'm not sure what you mean, can you clarify?

**Comment by johnynek** [comment]
a skylark rule that uses `.path` on a file I think gets the full path from the local-fastbuild? I'm not really sure what path is actually gets. But those paths matter to some rules (like the thrift rules we have since thrift does import by relative path, not by module/package name).

So, this is how we get into this boat now. The `.path` is different when you run as an external repo, and so this is where the problem comes.

I guess ideally, we want anything you can learn from skylark to be the same in local or remote cases, since otherwise we could potentially break in a remote case but not local, or vice-versa.

By the way: one hygiene issue with remove repos is here: #1673, so the prelude of a remote repo is ignored. It seems to me it should be applied inside that repo otherwise things are very brittle.

**Comment by kchodorow** [comment]
> I guess ideally, we want anything you can learn from skylark to be the same in local or remote cases, since otherwise we could potentially break in a remote case but not local, or vice-versa.

That's what this bug is trying to fix: make local & remote paths "look the same."

> a skylark rule that uses .path on a file I think gets the full path from the local-fastbuild?

Technically, `.path` is the path to the file under the execution root, so it'll include the local-fastbuild segments for output files (but not source files).  So `File('//my:generated_file').path` should be bazel-out/local-fastbuild/genfiles/my/generated_file, whereas `File('//my:src_file').path` would just be my/src_file.

.short_path is what you end up with in the runfiles tree, which doesn't have local-fastbuild subdirectories, so everything ends up as though it were a source file (my/generated_file & my/src_file).

**Comment by johnynek** [comment]
Thanks for the clarification. I think solving this bug will be what we want for our use case then.

**Comment by mhlopko** [comment]
Hello Kristina, is this still expected to be fixed in 0.5?

**Comment by kchodorow** [comment]
No.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
