### ISSUE TITLE
bazel  third-party CPP library relative path

### ISSUE THREAD

**Issue by hillguo** [bazelbuild/bazel#12660]
Depending on the third-party CPP library, some directory header files contain the relative path of.. /. / how to introduce bazel

**Comment by hillguo** [comment]
![image](https://user-images.githubusercontent.com/29300108/101491801-251a5c80-399f-11eb-83cf-b9d884f8e422.png)

**Comment by oquenchil** [comment]
Please see the [attributes of cc_library](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library_args) to work with include paths.

**Comment by cso-mark** [comment]
I'm hitting this issue too. @oquenchil is there a specific pointer you can give? I'm trying to include an external library into my project. The external project uses cmake which does not have any issues with the relative `#include ../somefile.h` idiom. The [bazel documentation](https://docs.bazel.build/versions/main/bazel-and-cpp.html) says "Avoid using UNIX directory shortcuts, such as . (current directory) or .. (parent directory)." But since this is a huge external library which I'm just copying and pasting into my project, I don't really want to rewrite all the include paths.

**Comment by Knowledge91** [comment]
I am having the same issue with importing the glm:
WORKSPACE
```
new_git_repository(
    name = "glm",
    build_file = "//third_party:glm.BUILD",
    commit = "658d8960d081e0c9c312d49758c7ef919371b428",
    remote = "https://github.com/g-truc/glm.git",
)
```
//third_party/glm.BUILD
cc_library(
    name = "glm",
    hdrs = glob([
        "glm/*.hpp",
        "glm/**/*.hpp",
    ]),
    includes = ["."],
    textual_hdrs = glob(["glm/**/*.inl"]),
    visibility = ["//visibility:public"],
)
```

Error message:
```
In file included from gl_main.cc:10:
In file included from external/glm/glm/gtc/matrix_transform.hpp:24:
In file included from external/glm/glm/gtc/../mat4x4.hpp:5:
In file included from external/glm/glm/gtc/.././ext/matrix_double4x4.hpp:5:
In file included from external/glm/glm/gtc/.././ext/../detail/type_mat4x4.hpp:6:
In file included from external/glm/glm/gtc/.././ext/../detail/type_vec4.hpp:6:
In file included from external/glm/glm/gtc/.././ext/../detail/qualifier.hpp:3:
external/glm/glm/gtc/.././ext/../detail/setup.hpp:33:10: fatal error: '../simd/platform.h' file not found
#include "../simd/platform.h"
         ^~~~~~~~~~~~~~~~~~~~
```
