### ISSUE TITLE
Bazel should allow for redirecting all external repos to a certain directory/url

### ISSUE THREAD

**Issue by fenrus75** [bazelbuild/bazel#1266]
For both cases where network access is limited, or building bazel based software for inclusion into a Linux distribution, it would be nice if a directory could be provided on the command line where bazel would look for files it would otherwise download, prior to actually downloading those files if they are not in this external cache.

**Comment by kchodorow** [comment]
There are two issues here:

* Better configurability: make the tooling better at finding local copies of, say, the go tool (instead of downloading it). We've recently done some work here for C++, but the other tools could do it, too, and we could provide a more fully-featured API for finding things locally.
* Better reuse of local downloads: right now every workspace downloads its own copies of external repositories, in some cases these could be shared between all bazel instances. There has been some interest in this on the mailing list as well: https://groups.google.com/d/msg/bazel-discuss/ouCC9p-BUto/m0j4PHvRAQAJ.

**Comment by fenrus75** [comment]
it's more than about "reuse"; it's about predictability.

for a fully reproducable build (from a Linux distro integration
perspective) the desire is very strong to not let a build of a component
download "stuff from the internet", but instead, put everything needed in
place from a known good archived copy.  (this is not just "reproducable",
it's usually also needed for legal compliance for GPL and other similar
licenses, you need to KNOW you have everything used)

having a "try to grab all downloads from <THIS> directory please" feature
would solve this very nicely.

**Comment by ahumesky** [comment]
Some things you may find useful:
- all the workspace rules that download files (http_archive, http_file, http_jar, new_http_archive, maven_jar) have a sha256 (or sha1 for maven_jar) attribute to verify that the download is correct
- local_repository and new_local_repository can pull in local directories that are external to the workspace
- bazel works well with checking every dependency into source control

**Comment by kchodorow** [comment]
Updated the title to better reflect the feature request.  I think this would be pretty useful to have for testing, too.

**Comment by damienmg** [comment]
This is planned for our CI support (where we want to replace non deterministic workspace operation by well-known vendored repositories).
