### ISSUE TITLE
repr of OutputGroupInfo is confusing

### ISSUE THREAD

**Issue by alandonovan** [bazelbuild/bazel#12682]
Re-reporting on behalf of @sfreilich (see https://github.com/bazelbuild/starlark/issues/149)
The repr of target[OutputGroupInfo] is:
```
struct(_hidden_top_level_INTERNAL_ = depset([]))
```
That probably should have a repr that mentions OutputGroupInfo and hides the field for OutputGroupInfo.HIDDEN_TOP_LEVEL.

**Comment by sfreilich** [comment]
Sorry for misfiling, thanks for directing this to the right place.

**Comment by janakdr** [comment]
I don't have any familarity with where this comes from. It looks like a "core Starlark" bug, not a "core" bug.

**Comment by alandonovan** [comment]
Janak, see the first line of the bug report: I recategorized it from "core Starlark" to "Bazel's Build Language" because lib.analysis.OutputGroupInfo and lib.packages.Struct are both Bazelisms. The fix, if one is necessary, is to provide an overridden implementation of OutputGroupInfo.repr. It's technically a breaking change but likely a benign one.

**Comment by janakdr** [comment]
Perhaps we're missing a category in this tracker, but "team-Core" in our Github issue tracker is for issues related to the Google-internal "*-core" team. "Bazel's Build Language" is decidedly not in scope for us. I've recategorized it as "team-Starlark" within the Bazel issue tracker, which seems right to me, since who else would own "Bazel's Build Language"? If that's wrong, then probably @aiuto needs to create another category with a different owner.

**Comment by aiuto** [comment]
This seems to be one of the many issues that hits code that is not "unowned", but rather "unwatched". It's old, stable stuff that does not get a lot of active development, so no one seems to be the immediate owner. I'll take it in configurability for now.

**Comment by aiuto** [comment]
This is not a configurability problem. I'm taking it as a meta-request to figure out what team should own this kind of thing.
