### ISSUE TITLE
Make target_compatible_with available also for cc_import

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazel#12745]
### Description of the problem / feature request:

target_compatible_with is not available for cc_import

### Feature requests: what underlying problem are you trying to solve with this feature?

The same logic that one would like to apply to a cc_library applies to a cc_import

### What's the output of `bazel info release`?

Build label: 4.0.0rc7

**Comment by gregestren** [comment]
@philsc what do you think?

**Comment by gregestren** [comment]
FYI this is because `cc_import` is a `BaseRule` instead of a `RuleBase`:

- https://github.com/bazelbuild/bazel/blob/8346ea4cfdd9fbd170d51a528fee26f912dad2d5/src/main/java/com/google/devtools/build/lib/rules/cpp/CcImportRule.java#L110
- https://github.com/bazelbuild/bazel/blob/eb5cdcb972326321a649d9b4df495ae22aea3f12/src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java#L386
- https://github.com/bazelbuild/bazel/blob/eb5cdcb972326321a649d9b4df495ae22aea3f12/src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java#L438

@philsc  do you remember if this was an intentional distinction when placing `target_compatible_with`?

TODO: rename `BaseRule` and `RuleBase` to be less confusing.

**Comment by gregestren** [comment]
FYI I'm giving a go at that TODO: https://bazel-review.googlesource.com/c/bazel/+/151410

**Comment by philsc** [comment]
The original patch (22b4dbcaf05756d506de346728db3846da56b775) added the attribute to pretty much any rule. This included repository rules. That broke a few projects including [bazelbuild/bazel-toolchains](https://github.com/bazelbuild/bazel-toolchains/blob/b9bc541aae7bd8e09c6954e2e9da3f7ffe4f77f0/WORKSPACE#L384).

@katre saved the day with 775a979bde21a71ddf04f67b865e8c43a29f702a that shifted the attribute from `commonCoreAndStarlarkAttributes` to `RuleBase`.

Sounds like this caused `target_compatible_with` not to work with `cc_import`.

I think making `target_compatible_with` work with `cc_import` makes sense and should be done. I can play around with that. I also noticed that `filegroup` doesn't support `target_compatible_with` even though that sometimes has very similar use cases. I.e. making pre-compiled binaries available.

@katre , do you have any additional thoughts? I'm happy to explore expanding the kinds of rules that `target_compatible_with` is available for.

**Comment by katre** [comment]
It's unfortunate that we don't have an easy way to specify "all non-repository rules". I definitely think that we should support `target_compatible_with` on `filegroup` and `cc_import`. Sorry that my fix missed these cases.

**Comment by gregestren** [comment]
@katre  I think we can distinguish between build vs. repository rules, unless my understanding of what a "workspace" rule is off.  See:

https://bazel-review.googlesource.com/c/bazel/+/151410/2/src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java#367
https://bazel-review.googlesource.com/c/bazel/+/151410/2/src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java#384

Do the distinctions I added in those comments sound right?

Re: `cc_toolchain`, point taken. Maybe it'd be easiest just to throw the attribute onto there too, even if it's not useful on that rule. i.e. having some innocuous over-inclusion might be better than noticeable under-inclusion.

Worst case we could always ad-hoc add it to a specific rule. But it'd be lovely to avoid that.

**Comment by katre** [comment]
@gregestren: Those renames and comments are good: very helpful. I'm less certain that we're consistently distinguishing between "build" and "non-build" rules, but I'm also less worried about that: if someone puts `target_compatible_with` on a `cc_toolchain`, I'm not 100% sure what should happen but I also think the user may have a reason, and don't see a reason to prohibit it out of hand.

Instead of build/non-build, I think I mentally bucket rules into "generates actions"/"doesn't generate actions" (with tests being a subset of the former). I'm not sure that this is more useful, and it definitely isn't reflected in the code anywhere.

**Comment by gregestren** [comment]
That's a good point. I like that phrasing - I'll try to integrate it.

@philsc I suggest holding until I've gotten https://bazel-review.googlesource.com/c/bazel/+/151410 in then just opening access to all non-WORKSPACE rules.

**Comment by philsc** [comment]
Okay, that sounds good to me. Thanks!

**Comment by gregestren** [comment]
Apologies, I forgot to link the final commit here. It was https://github.com/bazelbuild/bazel/commit/9868455f017ddf00eaef02cb52551b45212d4136.
