### ISSUE TITLE
Technical Debt: Cyclic dependencies between EvalUtils, Dict and Starlark

### ISSUE THREAD

**Issue by jbpextra** [bazelbuild/bazel#12774]
### Description of the problem:

 

There exists a cyclic dependency between classes EvalUtils, Dict and Starlark that routinely wastes 2% of overall development time.

 

We at Skuld Technologies have developed a tool that automatically finds cycles that have a negative impact on the development process. These cyclic dependencies have the potential to create exponential ripple effects during development that, when removed, can make contributors significantly more productive. We will proceed create the pull request and hope to get feedback from someone within the core team. Thanks in advance!

![Bazel-pre](https://user-images.githubusercontent.com/20543411/103648589-69c4f380-4f5d-11eb-89e4-386bc63852a8.png)

 

 

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

 

> cfebb18ad206162c1309962e8d396a5fd0ef234e

**Comment by alandonovan** [comment]
> There exists a cyclic dependency between classes EvalUtils, Dict and Starlark

Yes, that's part of the design. All classes in this directory are part of the same Java package, and thus may freely refer to each other. This is not a problem, so please do not attempt to "solve" it.


>  that routinely wastes 2% of overall development time.

Please explain what this number means and how you obtained it. This comment leaves me very skeptical that what you are measuring corresponds to anything in reality.

**Comment by jbpextra** [comment]
Hi @alandonovan, thanks for your quick reply.

First of all, apologies for not having elaborated further on the initial submission.

In a task to validate the tool we developed, we ran an analysis over multiple open-source projects and for this one we saw great potential in limiting the extra work from arising from cycles.

Specifically, we found an unusually high frequency of extra changes between EvalUtils and Starlark. We define as "extra changes" the work that has to be done because of the existence of technical debt, in this case being the cyclic dependency. A look in the git history, shows that the indexing/slicing functions have been moving around classes, which indicates that they should have their own class.

The rule of disallowing cyclic dependencies between packages is certainly a good rule of thumb for avoiding high negative impact cases but doesn't mean cyclic dependencies between intra-package classes can't potentially be problematic. The class Starlark both uses the Dict class as a dictionary and holds functions that the dictionary implementation make use of. Even if there doesn't appear to be a problem right now, it is a risk that software evolves in a way were changes in Starlark or Dict creates ripple effects across the codebase. Therefore, we propose the introduction of an interface to enforce the separation between definition and implementation to preemptively diminish the risk of that happening.

Regarding the 2% figure, it is based on the relative weight of the work tagged as not-needed-if-it-weren't-for-the-cycle in respective to whole set of changes in the analyzed time frame.

Hope you found this explanation satisfactory.

**Comment by alandonovan** [comment]
> Specifically, we found an unusually high frequency of extra changes between EvalUtils and Starlark. We define as "extra changes" the work that has to be done because of the existence of technical debt, in this case being the cyclic dependency. A look in the git history, shows that the indexing/slicing functions have been moving around classes, which indicates that they should have their own class.

The real problem here is that there is a design, but your analysis, like all automated tools, cannot know it. The design principle is that EvalUtils defines operations on Starlark data structures, and is a private class. Starlark is a public facade for the package as a whole. For public operations, Starlark is the correct place. Alternatively, they might be defined in a method EvalUtils, to which a public Starlark method might delegate; that's fine too. I see no benefit here to additional classes.

In fact, I have spend the last 18 months cleaning up this package to disentangle it from Bazel proper, and much of that work has been in deleting classes that don't carry their weight. If you are trying to understand what makes for better code in Bazel, you may find it valuable to study my last 450 or so changes to get a sense of the things that really matter.


> that doesn't mean cyclic dependencies between intra-package classes can't potentially be problematic.
> The class Starlark both uses the Dict class as a dictionary and holds functions that the dictionary implementation make use of. Even if there doesn't appear to be a problem right now, it is a risk that software evolves in a way where changes in Starlark or Dict creates ripple effects across the codebase. Therefore, we propose the introduction of an interface to enforce the separation between definition and implementation to preemptively diminish the risk of that happening.

Both classes necessarily depend on Dict because Dict is a core part of the language: for example, it's part of the function calling convention. Also Starlark.UNIVERSE holds all the built-in functions of the core language, which means it necessarily depends on everything, and they in turn depend on it. This is not a problem (though, as in any Java project, there have been occasions on which the JVM's completely dynamic order of initialization has created problems---but adding more classes would make that worse, not better). Adding more classes does not improve the code. Adding interfaces does, I argue, actual harm to the code, by making it more complex than necessary, both the reader and to the class interpreter.


> Regarding the 2% figure, it is based on the relative weight of the work tagged as not-needed-if-it-weren't-for-the-cycle in respective to whole set of changes in the analyzed time frame.

It sounds like you used number of lines of code or diff hunks as a proxy for effort. The two are very poorly correlated. It's easy to add hundreds of lines of code. It is easy to move code within a package. It is easy to change the implementation of a function with a good interface. It is very hard to break a dependency on a public symbol.

Having done essentially all of the cleanup work on this package in the last two years, I can tell you that the effort was 90% thinking and 10% typing. One you have figured out exactly change is needed, the keyboard effort required to implement it is usually trivial by comparison.

There is an enormous amount of technical debt in Bazel, but this is not it.

**Comment by brandjon** [comment]
It's conceivable that a tool for identifying dep cycles may be useful for targeting tech debt reduction efforts. But it does not follow that any dep cycle between classes within the same package should be eliminated, or is even cause for concern.

Ironically, this particular area of code has recently benefited from more human-direct refactoring than any other part of Bazel, and is least in need of automated suggestions.
