### ISSUE TITLE
"bazel clean" failure when Starlark options present in "build" lines in .bazelrc

### ISSUE THREAD

**Issue by stefanbucur** [bazelbuild/bazel#12808]
### Description of the problem / feature request:

When I use a label-typed Bazel option on a `build` line in a `.bazelrc` file, Bazel fails with an error:

```
# .bazelrc file
build --//fuzzing:cc_engine=//fuzzing/engines:libfuzzer
```

```sh
$ bazel clean
ERROR: Unrecognized arguments: --//fuzzing:cc_engine=//fuzzing/engines:libfuzzer
```

This is quite problematic for us, because we offer this option in a library, and developers are expected to be able to override the option in their own workspaces.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```sh
$ git clone git@github.com:bazelbuild/rules_fuzzing.git
$ cd rules_fuzzing
$ [edit the .bazelrc file and add the "build --//fuzzing:cc_engine=//fuzzing/engines:libfuzzer" snippet]
$ bazel clean
```

### What operating system are you running Bazel on?

Debian

### What's the output of `bazel info release`?

`release 3.7.2`

**Comment by aiuto** [comment]
Only sending to configurability because of command line parsing, but I think any team could do this.

**Comment by Yannic** [comment]
Looks like this was previously fixed in https://github.com/bazelbuild/bazel/issues/11506 (and I *think* I remember it working correctly).

/cc @juliexxia @katre

**Comment by stefanbucur** [comment]
I've just checked, and Bazel does indeed display a warning when using `--//fuzzing:cc_engine_sanitizer`, which is a string-typed flag. However, it triggers an error for `--//fuzzing:cc_engine`, which is a *label-typed* flag. So maybe this case was not handled in #11506?

**Comment by juliexxia** [comment]
(Context: I'm moving on from Bazel on friday and spending some time triaging all bugs assigned to me before unassigning myself)

Just tried the repro with release bazel and got the described error, but tried with bazel built at head and got the expected warning. I haven't tried to figure out what change resulted in that but I'd request trying this again when the new release comes out and see if it's still an issue.

**Comment by gregestren** [comment]
Status: let's wait until the next Bazel release to verify the issue, as @juliexxia suggested. 

After that point if anyone still sees the problem please ping this thread.

**Comment by gregestren** [comment]
This fails for me with bazel 4.1.0. I'll look further.

**Comment by gregestren** [comment]
Dug in and I'm confused. :(

This works for me with bazel@head. But not bazel 4.1.0.

- [Bazel 4.1's release bug](https://github.com/bazelbuild/bazel/issues/13099) is baselined to 4.0.0 ( https://github.com/bazelbuild/bazel/commit/6b33bdb1e22514304c0e35ce8e067f2175685245), which itself is baselined to https://github.com/bazelbuild/bazel/commit/37a429ad12b4c9e6a62dbae4881a1ff03b81ab40, which was committed Nov 18, 2020
- The first fix for `clean`, https://github.com/bazelbuild/bazel/commit/32e1313f90abcaa99c1b79750fcc4a8bdf7314c6, was committed May 27, 2020
- The fix for `clean`, https://github.com/bazelbuild/bazel/commit/69d4acef9c4f6546955e549a7ffaab8dbcfbc9d2, was commited May 29, 2020

What would be different between 4.1.0 and head, then?

Something is not adding up here.

**Comment by gregestren** [comment]
`CleanCommand` at the `4.1..0` tag: https://github.com/bazelbuild/bazel/blob/4.1.0/src/main/java/com/google/devtools/build/lib/runtime/commands/CleanCommand.java. I see the relevant code:

https://github.com/bazelbuild/bazel/blob/c4975efdd7ede7b46637bf353209d9ac371181a5/src/main/java/com/google/devtools/build/lib/runtime/commands/CleanCommand.java#L133-L135

And I don't see any interesting changes to the file since: https://github.com/bazelbuild/bazel/commits/master/src/main/java/com/google/devtools/build/lib/runtime/commands/CleanCommand.java

**Comment by gregestren** [comment]
`git bisect` led me to https://github.com/bazelbuild/bazel/commit/64157a59d187f32201faa8503194b1cfa23b6f16 from Dec 22, 2020. We can request this as a cherrypick for 4.2.0.

**Comment by gregestren** [comment]
Closing this bug, now that it's been cherrypick-requested for 4.2.0.

**Comment by CareF** [comment]
Still get a warning message of this for bazel 5.1.0
