### ISSUE TITLE
Add the ability to run the same test program with different arguments during "bazel test //..."

### ISSUE THREAD

**Issue by Bu11etmagnet** [bazelbuild/bazel#12866]
### Description of the problem / feature request:

As a developer, I would like to run the same test binary with different arguments during `bazel test //...`, e.g. I want the following commands to be run

```
test1 --fast
test1 --slow
test2 --high
test2 --low
```

This is currently not possible, because a `cc_test` allows only one set of `args` , and `--test-arg` applies to all tests. The only solution is to run `bazel test` once for each invocation

```
bazel test test1 --test_arg --fast
bazel test test1 --test_arg --slow
bazel test test2 --test_arg --high
bazel test test2 --test_arg --low
(and so on for every single test binary)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Running the same test binary with different arguments

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

(Not applicable to a feature request)

### What operating system are you running Bazel on?

Linux (RHEL 7)

### What's the output of `bazel info release`?

3.6.0-2020-10-15 (@24ceee8)

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

###  Have you found anything relevant by searching the web?

https://stackoverflow.com/a/50890446

However, `--test-arg` applies to all test programs, and doesn't help for `bazel test //...`

### Any other information, logs, or outputs that you want to share?

The running of tests should be separated from the building of the tests. Currently, `cc_test` tries to do both at the same time, with `srcs` and `deps` for building and `args` for running. Perhaps a `cc_runtest` with `args` and a reference to a `cc_test`.

**Comment by gregestren** [comment]
@sdtwigg has some input. Assigning accordingly for triage.

**Comment by sdtwigg** [comment]
Unfortunately, this feature request is not especially feasible under our current architecture. As I discovered in one of my plans to fix-up `--trim_test_configuration`, test action creation and discovery is a bit too intricate. (My original plan was to create the TestAction, which is the main use of TestConfiguration including test_args outside of the build graph. However, this required refactoring a bunch of systems at the top-level that expected such an integration. For the same reasons, even if that refactoring had been done most of those systems would need adjustment.) Since test_arg is still part of the configuration, this  feature request would necessitate using a split transition at the top-level (and still have corresponding issues adjusting all the top-level systems to handle this.)

Alternatively, I suggest just incorporating the varying args into the test itself. One action can build the binary and then an sh_test (which is very, very close to the *_runtest you asked for) can call this binary for each of the varying args (or create an sh_test for each arg). If just need this as a one-off, can `blaze build` the test, see the reported location of the test binary, and then run that in some shell script.

PS: An actual runtest test that doesn't produce a test binary would be tricky as many parts of Bazel infrastructure assume every test target is a binary target that builds its own new binary. Note that a runtest implementation that just copied the old binary (or wrapped it in a new script maybe with baked in args) would work fine.

**Comment by Bu11etmagnet** [comment]
`sh_test` looks like a suitable alternative, thank.

**Comment by aiuto** [comment]
Backlog cleanup.
- As @sdtwigg mentioned, this is hard to change
- and there are alternatives
- and we have other priorities for 2023
- and there is another FR for parameterized tests, which is essentially the same problem (i.e. this is a dup).
