### ISSUE TITLE
No way to report progress from a Skylark remote repository

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1289]
If we do a slow operation in a skylark remote repository there is no way to report it to the user and we should provide facilities for it.

To be designed.

/cc @aehlig fyi

**Comment by davidzchen** [comment]
This will also be good to have for #1408, especially for getting the `git_repository` integration tests to work.

**Comment by benley** [comment]
This would be very nice to have in the docker_pull repository rule I just put together too.  Bazel curently gives users the misleading impression that the daemon is just hung while it waits for `docker pull` and `docker save` to run.

**Comment by damienmg** [comment]
@benley: hehe that's exactly the same problem that we had that made me fill that bug, see https://github.com/bazelbuild/continuous-integration/blob/master/base/docker_pull.bzl

**Comment by benley** [comment]
I don't know how feasible any of these would be to implement, but I would totally settle for any of:

* A way to print warnings or info logs to the console _before_ the `repository_ctx.execute()` actions finish rather than after, so you could at least have a "this may take a while" message
* A flag to display repository rule subcommands as they execute, like `--subcommands` (I was somewhat surprised that `--subcommands` doesn't already accomplish this!)
* A flag to stream stdout/stderr from repo subcommands to the console as they execute

**Comment by htuch** [comment]
+1, we build our entire set of external dependencies under a `repository_rule` (see https://github.com/lyft/envoy/pull/716). Today it just hangs and does nothing for a while before moving on with the rest of the build. I know that with `quiet = False` on `repository_ctxt.execute` we can see progress, but that is sadly only available in newer Bazel than 0.4.5 which most of us are on, plus it's not the most elegant way of reporting progress.

**Comment by Globegitter** [comment]
I was also surprised that `--subcommands` was not showing output from repository rules. But maybe it's worth having a separate flag for that, like `--repository_subcommands`, I could imagine that at times one just wants to see the ones or the others. Also it would be nice if the `quiet=False` that can be passed into the `repository_context.execute` could be controlled ad-hoc via a flag, something like `repository_subcommand_quiet=True/False`. Sometimes when there is an issue with the underlying command in can be really helpful to see the full command. 

Also when introducing people to Bazel for some it seems a bit 'magic' at first not being able to see what bazel is doing, especially when one has a lot of docker or pip or npm dependencies to download and at first just has to wait potentially a couple of minute not being able to see anything.

**Comment by Globegitter** [comment]
For reference, there is now a `--experimental_workspace_rules_logging=yes` flag, which logs the internal proto message of each rule - the logging is very verbose, as it pretty prints the object and also prints all available environment variables, but it is a first step :)

**Comment by ittaiz** [comment]
@Globegitter Thanks! Used it now and it helped me :)
Do you know if anyone is planning on working on global `quiet=False` from outside?

**Comment by ittaiz** [comment]
@helenalt @aehlig this is another issue in the "bad onboarding experience" of developers. Mainly FYI since the current flag allows me to give it to people to use on first clone (it's probably two orders of magnitude too much logging but it's already there).

**Comment by ittaiz** [comment]
I actually see that on [master](https://github.com/bazelbuild/bazel/blob/1950bf94ab7bd760e37f3f45b9878a7a6bf5e56f/src/main/java/com/google/devtools/build/lib/bazel/debug/DebuggingOptions.java) this flag has changed to `experimental_workspace_rules_log_file` and now accepts a file and writes to it.
I think it doesn't solve the use-case I'm referring to.
@aehlig wdyt?

**Comment by agoulti** [comment]
I'm working on the experimental_workspace_rules_log_file flag, and you're right, I don't think it fits your use case. The motivation for the flag is to allow deep inspection of certain potentially non-hermetic behaviors during build. It will necessarily be verbose, but also being real-time was never a requirement for us.

Sounds like what you want is some special print function in Skylark that would bypass the normal mechanisms (e.g., don't cache, do repeat on re-execution). I'm not familiar enough with design constraints for Skylark to comment on how difficult it would be.

**Comment by ittaiz** [comment]
Thanks. It sounds like your work is not really related to this issue since AFAIU the people commenting here are discussing pretty much the same use case of the developer staring at the screen.
It sounds like adding a command line flag to globally toggle quiet=false will greatly advance the status and doesn’t require a big skylark design. @laurentlb wdyt?

**Comment by laurentlb** [comment]
This is really for @aehlig or @dkelmer

**Comment by ittaiz** [comment]
@aehlig and I discussed offline and he suggested that a first step, which could be relatively easier, is to have Bazel report which repository rules are currently working (even if they don't emit their logs yet).
I think this can be a great step forward as it will give the users some visibility.
Once we have this we can consider if emitting the repository rules logs while they run is worth the cost of sometimes replaying the logs when a repository rule is restarted.

**Comment by Globegitter** [comment]
@aehlig what is the reason that the api change would make this slow to be accepted? Could it not just be behind some experimental flag or something?

**Comment by guibou** [comment]
I'd like the output of `repository_ctx.execute` to be pipeable to the `repository_ctx.report_progress` in a streamed way.

This way, we'll be able to see progress in a controlled way in the command line.

I recently switched the `quiet` flag from `False` to `True` in rules_nixpkgs (https://github.com/tweag/rules_nixpkgs/pull/77) because it was generating too much unpredictable noise. However users are in the black when a nix process can run for a (very long time) and I did not found any way to set `quiet` to `False` from the command line.
