### ISSUE TITLE
'bazel [build/test] //...' follows the bazel convenience symlinks and causes geometric growth in 'bazel test' execution times.

### ISSUE THREAD

**Issue by rpoyner-tri** [bazelbuild/bazel#1293]
See attached example project.

Using an ill-advised glob pattern to select data files (maybe any kind of files?) leads to some cumulative server or cache problem. The project continues to build, but execution times of 'bazel test //...' grow geometrically.

I'm not looking for a fix to permit the bad glob pattern, necessarily. What I would like is for ill-advised cases like this to fail fast with a comprehensible error message. 

[bazelweird.zip](https://github.com/bazelbuild/bazel/files/273095/bazelweird.zip)

**Comment by rpoyner-tri** [comment]
Right, here's a way to reproduce the problem, with (maybe redundant) timing measurements:
`seq 100 | xargs -i time bazel test //...`

If you get beyond 12 or so iterations, you must have a very nice computer :) .

**Comment by kchodorow** [comment]
Wow, that's interesting!  Thanks for the simple repro, looking into it.

**Comment by kchodorow** [comment]
Looked into this a bit.  Not sure why yet, but here's what seems to be happening: output is supposed to go in $(bazel info execution_root)/bazelweird/bazel-out.  Because this has runfiles, they should go in $(bazel info execution_root)/bazelweird/bazel-out/local-fastbuild/bin/weird_test.runfiles/__main__/path/to/files.  However, for every build it's creating a new level of bazel-out symlink at a deeper level, e.g., after several builds it looks like:

```
ls /path/to/execroot/bazelweird/bazel-out/local-fastbuild/bin/weird_test.runfiles/__main__/bazel-out/local-fastbuild/bin/weird_test.runfiles/__main__/bazel-out//local-fastbuild/bin/weird_test.runfiles/__main__/bazel-out/local-fastbuild/bin/weird_test.runfiles/__main__/bazel-out/local-fastbuild/bin/weird_test.runfiles/__main__/bazel-out/local-fastbuild/bin/weird_test.runfiles/__main__/bazel-out/local-fastbuild/bin/weird_test.runfiles/__main__/bazel-out/local-fastbuild/bin/weird_test.runfiles/__main__/weird/test/data/x
```

**Comment by damienmg** [comment]
Because the glob is matching the convenience link?

**Comment by rpoyner-tri** [comment]
Thanks for looking, devs!

**Comment by philwo** [comment]
Sounds like a pretty bad bug to me, if globs match the convenience symlinks in the workspace! However, it might be difficult to detect reliably, because the name of the convenience symlinks can be configured using a flag and you can even have multiple Bazel servers running in the same workspace, each with their own output_base and symlinks.

@damienmg @kchodorow Any suggestions on how to fix this? Assigning it to Kristina for now, because I don't know a better owner, please feel free to reassign.

**Comment by damienmg** [comment]
We should special case the output_base: if glob match file in the output_base, ignore them.

Adding @haxorz @janakdr for some people with more idea on glob / performance.

**Comment by mhlopko** [comment]
Friendly ping, is this still expected to be fixed in 0.5? It's still at least 2 weeks away, but we're getting there :)

**Comment by kchodorow** [comment]
No.

**Comment by haxorz** [comment]
i don't think @janakdr or i ever noticed the mention, sorry. in the future, feel free to ping me if i have not responded to a github mention!

iiuc, the problem is with a recursive target patterns like //..., not with the build language 'glob' function, right?

i addressed the more general form of this issue in https://github.com/bazelbuild/bazel/commit/1e66ccd2f18b03733f22b93ad8051ff2cf37d3dd, in response to a google-internal concern with directory symlinks. see the note about 'DONT_FOLLOW_SYMLINKS_WHEN_TRAVERSING_THIS_DIRECTORY_VIA_A_RECURSIVE_TARGET_PATTERN
' in https://bazel.build/versions/master/docs/command-line-reference.html#target-pattern-syntax for the documentation on this feature.

the implementation is now in https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skyframe/ProcessPackageDirectory.java#L239-L251 at head.

-----------

solutions to this github issue that come to mind:
(1) have @rpoyner-tri add a DONT_FOLLOW_SYMLINKS_WHEN_TRAVERSING_THIS_DIRECTORY_VIA_A_RECURSIVE_TARGET_PATTERN sentinel file in the top-level directory of their bazel workspace or have the bazel installer someone due this automatically (idk if this even makes sense - sorry i don't know the process by which bazel users make new workspaces).
(2) special-case the top-level directory
(3) special-case the bazel convenience symlinks
(4) make the existing feature a bit more fancy, e.g. have DONT_FOLLOW_SYMLINKS_WHEN_TRAVERSING_THIS_DIRECTORY_VIA_A_RECURSIVE_TARGET_PATTERN be a line-separated list of  symlink dirents to not follow.

--------

(1) feels lame. (2) feels bad because it interacts poorly with symlink dirents in the top-level directory that the user actually wants bazel to care about. (3) was already mentioned by @philwo and he already explained it was messy. (4) would be fine with me.

**Comment by damienmg** [comment]
What I believe we should do is ignore all symlink pointing in the Bazel output user root, of course this won't cover the case where people set the output user root but that should cover 99% of the cases.

WDYT?

**Comment by meisterT** [comment]
Damien's solution sounds simple, doesn't require user action and since it was not reported more often is probably sufficient.

**Comment by graywolf-at-work** [comment]
> it was not reported more often

Just wanted to report that I've just hit this today. Not sure if "+1" is wanted here or not.

**Comment by bsilver8192** [comment]
The solution of ignoring symlinks pointing into the output base has been implemented since discussion died out in 2017. If you're seeing this on a modern bazel release, you're probably using multiple output bases and ended up with stale convenience symlinks when switching. If they point into a different output base, then `//...` recurses into them.

**Comment by graywolf-at-work** [comment]
Assuming 3.7.2 is modern enough, will try to put together minimal reproduction.

**Comment by graywolf-at-work** [comment]
So, given bazel project as in the attachement and bazel version

```
+   $ bazel --version
bazel 3.7.2
```

, every second invocation of `bazel test //...` fails.

```
+$ ls -al
total 12
drwxr-xr-x  2 wolf wolf  100 Jan 20 22:15 .
drwxrwxrwt 25 root root 1000 Jan 20 22:16 ..
-rw-r--r--  1 wolf wolf   92 Jan 20 22:13 BUILD
-rwxr-xr-x  1 wolf wolf   24 Jan 20 22:14 tree.sh
-rw-r--r--  1 wolf wolf   26 Jan 20 22:10 WORKSPACE
+$ bazel test //...
Starting local Bazel server and connecting to it...
INFO: Analyzed target //:foo (21 packages loaded, 229 targets configured).
INFO: Found 1 test target...
Target //:foo up-to-date:
  bazel-bin/foo
INFO: Elapsed time: 7.729s, Critical Path: 0.31s
INFO: 5 processes: 3 internal, 2 linux-sandbox.
INFO: Build completed successfully, 5 total actions
//:foo                                                                   PASSED in 0.1s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings commaINFO: Build completed successfully, 5 total actions
+$ bazel test //...
INFO: Analyzed target //:foo (1 packages loaded, 20 targets configured).
INFO: Found 1 test target...
ERROR: /tmp/repro/BUILD:1:8: //:foo: missing input file '//:bazel-bin/foo.runfiles/MANIFEST'
Target //:foo failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /tmp/repro/BUILD:1:8 4 input file(s) do not exist
INFO: Elapsed time: 0.368s, Critical Path: 0.02s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
//:foo                                                          FAILED TO BUILD

FAILED: Build did NOT complete successfully
+$ bazel test //...
INFO: Analyzed target //:foo (1 packages loaded, 18 targets configured).
INFO: Found 1 test target...
Target //:foo up-to-date:
  bazel-bin/foo
INFO: Elapsed time: 0.414s, Critical Path: 0.24s
INFO: 4 processes: 2 internal, 2 linux-sandbox.
INFO: Build completed successfully, 4 total actions
//:foo                                                                   PASSED in 0.1s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings commaINFO: Build completed successfully, 4 total actions
+$ bazel test //...
INFO: Analyzed target //:foo (1 packages loaded, 20 targets configured).
INFO: Found 1 test target...
ERROR: /tmp/repro/BUILD:1:8: //:foo: missing input file '//:bazel-out/_tmp/actions/stderr-4-0'
Target //:foo failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /tmp/repro/BUILD:1:8 2 input file(s) do not exist
INFO: Elapsed time: 0.209s, Critical Path: 0.01s
INFO: 3 processes: 3 internal.
FAILED: Build did NOT complete successfully
//:foo                                                          FAILED TO BUILD

FAILED: Build did NOT complete successfully
```

Bazed on error message

```
missing input file '//:bazel-out/_tmp/actions/stderr-4-0'
```

it definitelly looks like bazel is trying to traves the symlinks.
[repro.tar.gz](https://github.com/bazelbuild/bazel/files/5845334/repro.tar.gz)

**Comment by kshyanashree** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
