### ISSUE TITLE
Pkg_tar's contents are always timestamped Dec 31, 1969

### ISSUE THREAD

**Issue by imcginnis** [bazelbuild/bazel#1299]
This issue was originally brought up by Jeremy Lewi in this discussion on the bazel forums:  [https://groups.google.com/forum/#!topic/bazel-discuss/cprd0UhRMAs](https://groups.google.com/forum/#!topic/bazel-discuss/cprd0UhRMAs) 

Having the old timestamp creates issues with tools like python's distutils. E.g. - doing `python setup.py install` on the contents of a tarball made by Bazel will fail with zip complaining that it doesn't support timestamps before 1980.

Would it be possible to have a way to change the timestamp from the pkg_tar rule? Something like Kamal Marhubi's suggestion from the discussion would be great.

**Comment by kchodorow** [comment]
This would be a good attribute to add.

**Comment by AustinSchuh** [comment]
I keep thinking about good ways to automatically set the timestamps to something saner when deploying.  Maybe drive the timestamp off the timestamp in the last git commit of the repo if stamping is enabled, or 0 otherwise?  Or drive it off the time from stamping only when stamping is enabled?

**Comment by kchodorow** [comment]
Using the build timestamp if stamp=1 seems reasonable to me.

**Comment by objmagic** [comment]
Is there any follow-up on this issue? For https://github.com/twitter/heron/issues/101, we currently suppress warnings emitted by `tar`. It would be good if we can change the timestamp.

**Comment by kchodorow** [comment]
No, it shouldn't be too hard if someone wanted to add it, but it hasn't been a priority.  Interest noted, though.

**Comment by objmagic** [comment]
so @steren from Google's Bazel team was communicating with us (Twitter [Heron](https://github.com/twitter/heron) team) because he'd like to gather feedback from us and want to showcase our project on main page (if I got the information correctly). We would love to help Bazel team on this. Meanwhile, can we prioritize this issue and have it fixed as an exchange? @damienmg @kchodorow

**Comment by steren** [comment]
@ssuchter did you work on any patch to address the problem? We would be glad to review it.

**Comment by ssuchter** [comment]
I got busy on other projects and didn’t have time to finish it.

The existing patch that I submitted for review does address the timestamps,
but there was a good suggestion to add more unit tests, and that’s when I
ran out of time.

Sean

On June 9, 2017 at 6:38:39 AM, Steren (notifications@github.com) wrote:

@ssuchter <https://github.com/ssuchter> did you work on any patch to
address the problem? We would be glad to review it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bazelbuild/bazel/issues/1299#issuecomment-307391006>,
or mute the thread

**Comment by wking** [comment]
It seems like @ssuchter's old patch is [here][1], in case someone has time to pick it up again.

[1]: https://groups.google.com/forum/#!msg/bazel-dev/iwOPKRhf_wE/ZM23x1UpAwAJ

**Comment by beasleyr-vmw** [comment]
The missing timestamp field appears to break Maven's maven-antrun-plugin when extracting a gzipped tarball. (This is done in two steps: gunzip, then untar. What I observe is that the .tar.gz is never gunzipped. I'm *guessing* it's from the plugin's builtin up-to-date check which would compare the .gz's mtime to that of the target .tar. This is a problem for large orgs who're incrementally adopting Bazel and need Bazel-produced bits to still work with legacy Maven/Ant/etc. builds.)

So it looks like there are two related distinct issues to consider:

1. A deterministic mtime of 0 causes undefined behavior in downstream software. Maybe Bazel can use a different value for the epoch? (946684800 --- 2000-01-01 --- would sidestep the Python problem described in the original report.)
2. As discussed elsewhere in this issue, let folks store timestamps when building w/ stamp=1 (@ssuchter's patch). (Should this be forked to a separate issue?)

**Comment by aiuto** [comment]
The current solution is not really sufficient. It impacts anyone using TarFileWriter, for example rules_docker.

I propose instead that TarFileWriter keeps using mtime=0, but pkg_rpm alone sets to the 2000-01-01 build date. I have a change which does this in progress, but I want to clean it  up a bit.

**Comment by aiuto** [comment]
> I propose instead that TarFileWriter keeps using mtime=0, but pkg_rpm alone sets to the 2000-01-01 build date. I have a change which does this in progress, but I want to clean it up a bit.

Implemented in #7482
