### ISSUE TITLE
Add a private_deps field to cc_library 

### ISSUE THREAD

**Issue by jlaxson** [bazelbuild/bazel#13000]
### Description of the problem / feature request:

cc_library treats all dependencies and transitive dependencies as public to its consumers.  This results in include directories, headers, and maybe compile flags exploding in volume when you have a complex dependency tree.  CMake supports a rather granular public/private definition for libraries to control what gets inherited by a consuming library, and what is only used for directly compiling the specific library.

As a basic start, cc_library could support a `private_deps` field.  Any targets here would be considered the same as `deps` for compilation purposes, however when computing the final CcInfo provider, hdrs, textual_hdrs, and includes would not be included (obviously the linking context would still be included to properly pick up transitive .a/.so/etc).  This would make it easy to control dependency explosion and better hide unfortunately-named files in dependencies.

### Feature requests: what underlying problem are you trying to solve with this feature?

As an example I see in many public projects:

* libpng depends on liblzma from xz, even though no public libpng header depends on lzma.
* any first-party cc_library that has libpng in its deps gets all of the lzma headers
* lzma rather unfortunately exports a "Common/Common.h" header (this is made more complex by macos' case-insensitive filesystem)
* This interacts in build-breaking ways with any other code that might deign to define a Common.h header (how often does that happen?)
* In addition, this causes an explosion of files that must be added to the sandbox for downstream compilation.
* The remote cache hit rate is stunted, because an upstream change (say to a header that is hidden/privately included by an intermediary library) still propagates to every compile action downstream, even though the output is not going to change.

### Any other information, logs, or outputs that you want to share?

I will write it with a bit of guidance and knowing in principle that it is mergeable.  Starting code is here: https://github.com/jlaxson/bazel/tree/compile_only_deps

cc @oquenchil since you seem to be active on all my rules_cc work.

**Comment by bjacklyn** [comment]
Yes, a solution for this is needed and would be hugely helpful for my org. I'd say the most important bullet point missing from your list is how it would improve remote cache hits. For example, a change to a header in liblzma not only invalidates all compilation actions for libpng (which is expected), but invalidates every compilation action in every downstream library/binary _even if none of them read any header from liblzma_. In this trivial example of 2 libraries it doesn't sound like a big deal, but when you have hundreds of libraries and binaries being invalidated because a hdr changed that nobody reads besides libpng it is a big deal.

There is a PR which I think implements something like this which wasn't accepted because internally Google uses hdr include scanning (and thus doesn't have this problem even though everyone else using bazel does): https://github.com/bazelbuild/bazel/pull/8482 

As a side note I would also be happy if hdr including scanning was made available as the solution for this problem. That would give a perfect dep list of hdrs which would invalidate compilation actions even less -- for example even with private deps a changed hdr in liblzma that is not read by libpng would still invalidate libpng -- but private deps still solves 99% of this problem. Arguably the user experience of not having to maintain public vs. private deps lists would be better, but private deps is probably the more "bazel" way to do it.

**Comment by jlaxson** [comment]
Thanks, I discovered that PR later after writing this, and I'll add cache hit efficacy to my list of rationale.   A bit of an unfortunate outcome to get left by the wayside.  I took that as inspiration to bring something like that up to current master, and it's here: https://github.com/jlaxson/bazel/tree/compile_only_deps.

The include scanning would be superb for incremental builds (most Makefile toolchains have had that for decades with `-MD` :p), but it seems to me there's an easy answer to why include scanning is not sufficient on its own and a syntax addition is necessary regardless: visibility.  There are perfectly reasonable sets of third party libraries with overlapping header files that can't be composed inside bazel.  And if bazel plus the compiler can't differentiate the correct header currently, I'm not sure that scanning will be able to correctly resolve it either.

Also, with speed as a top level project goal, having a way to break the transitive dependency chain could drastically cut down on the effort spent symlinking/sandboxing downstream dependencies.  I lose a core or two during build to fseventsd trying to keep up with all the filesystem activity, when most of our actual libraries only have tens or a few hundred direct dependency files.

**Comment by jlaxson** [comment]
Never mind, I was thinking too narrowly on include scanning.  If the scanned includes were used so that the downstream compilation context was filtered by the dependencies of public `hdrs`, it would help.  There is still value in explicitly specifying what you expect to be public/private though - one can imagine trying to fix an issue several libraries downstream because something is leaking you don't expect.  Also, seems like the core CcRules implementation would look similar?  Still need separate CcCompilationContext for actual compiling and the public interface.

**Comment by oquenchil** [comment]
This is available as implementation_deps.

**Comment by dflems** [comment]
@oquenchil are there plans to add `implementation_deps` support to `objc_library`?

**Comment by oquenchil** [comment]
@googlewalt might know.

**Comment by googlewalt** [comment]
As a matter of principle we'd like `objc_library` to behave as much like `cc_library` as possible, so yes eventually we'd want to support it.  The work has not been scheduled, however.

**Comment by xiemotongye** [comment]
> @oquenchil are there plans to add `implementation_deps` support to `objc_library`?

I have the same requirement. We use bazel to organize & build our iOS project. This project have a complex dependency tree. When a header file of the downstream module changes, it break the cache of upstream modules. `swift_library` has `private_deps`, `cc_library` has `implementation_deps`. Only `objc_library` doesn't have one. If `implementation_deps` is supported to objc_library, we can cut down lots of time for compilation.

**Comment by oquenchil** [comment]
Can you file a feature request with the label team-rules-Objc?

**Comment by xiemotongye** [comment]
Yep, I have filed a feature request. But I can't add labels to it.
