### ISSUE TITLE
Bazel Not Reporting Segmentation Faults

### ISSUE THREAD

**Issue by mileseldon-verb** [bazelbuild/bazel#1304]
When running a program that seg faults, Bazel exits cleanly. Running the same program via the binary in bazel-bin results in a segmentation fault. It appears to be something in the way that Bazel reports the result of the child process that is the command you are running.

**Comment by hermione521** [comment]
@damienmg Can you look at this?

**Comment by hermione521** [comment]
I took a look at the code and I guess the problem is that we print everything (excluding the segmentation fault) and exit but do nothing about this [numericExitCode](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java#L481).
Not sure how to fix it, but will do it in the future.

**Comment by ccdavid** [comment]
Any updates to this one? It's a huge waste of time to catch problems when there is no indication of a SegFault.

**Comment by AdamDorwart** [comment]
Any update here? Going to either use `--script_path` or `--run_under` unless there's a better way.

**Comment by popozy** [comment]
Any updates?

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
