### ISSUE TITLE
Breakages on Windows and Android tests

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#1316]
commit:
https://github.com/bazelbuild/bazel/commit/bd69849378112c3b05bc218e57cdafca82860710

breakages:
http://ci.bazel.io/job/bazel-tests/22/
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/567/

**Comment by menny** [comment]
This is also broken on Mac OSX

**Comment by damienmg** [comment]
@dslomov is fixing the windows breakage, coming from a known issue with runfiles tree on Windows. Reinstalling the slave will get pass it. So android is the remaining issue.

**Comment by dslomov** [comment]
Windows is fixed. @kchodorow. do you know what's up with android tests? (Tutorial is also broken)

**Comment by kchodorow** [comment]
I think Android is hardcoding a runfiles path as x.runfiles/wsname/external/androidsdk, which bd69849 turned off (it's now x.runfiles/androidsdk).  Looking...

**Comment by damienmg** [comment]
Note that the location replacement does not work correctly either

**Comment by kchodorow** [comment]
What do you mean?

**Comment by damienmg** [comment]
See
http://ci.bazel.io/job/bazel-docker-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=docker/4/console

**Comment by kchodorow** [comment]
It actually does, but the tests are assuming that runfiles tree path == exec root path, which is no longer true.  You can't use $location to get the runfiles tree path.

**Comment by damienmg** [comment]
Which means that pattern is no longer valid:
https://github.com/bazelbuild/bazel/blob/master/tools/cpp/test/BUILD#L74 Which should be, shouldn't it?

Other skylark rules are failing because the path they are getting is an execroot dependent path.
How far are we from getting the deep_execroot turn on by default? Maybe we should stay in the intermediary state until we can get the deep execroot turned on (or maybe we can turn on now in Bazel but not internally).

**Comment by kchodorow** [comment]
> Which means that pattern is no longer valid:
> https://github.com/bazelbuild/bazel/blob/master/tools/cpp/test/BUILD#L74 Which should be, shouldn't it?

No, it shouldn't.  (Or at least I don't think it should be.)

> How far are we from getting the deep_execroot turn on by default? 

deep execroot is on by default (and has been for several weeks), but that doesn't mean the exec root paths have been rearranged yet (that's the hard part).  That change will hopefully go out for code review this week.

**Comment by damienmg** [comment]
On Tue, May 31, 2016 at 5:09 PM Kristina <notifications@github.com> wrote:

> Which means that pattern is no longer valid:
> https://github.com/bazelbuild/bazel/blob/master/tools/cpp/test/BUILD#L74
> Which should be, shouldn't it?
>
> No, it shouldn't. (Or at least I don't think it should be.)
>
Then what should be used in that example? We can certainly hard code the
path to it but is that correct?

> How far are we from getting the deep_execroot turn on by default?
>
> deep execroot is on by default (and has been for several weeks), but that
> doesn't mean the exec root paths have been rearranged yet (that's the hard
> part). That change will hopefully go out for code review this week.
>

Oh nice :) then the $(location ) pattern will be correct for both runfiles
tree and execroot :)

Anyway, the problem arise in skylark rules (this is why there is so many
test failures there). We need to have an intermediary solution (especially
since it seems like this change will be in 0.3)

**Comment by kchodorow** [comment]
> Then what should be used in that example? We can certainly hard code the
> path to it but is that correct?

Based on the last doc on Windows runfiles I saw, I think that runfiles should probably eventually be referred to via some API, but in the meantime hardcoding it seems reasonable.  

> Anyway, the problem arise in skylark rules (this is why there is so many
> test failures there). We need to have an intermediary solution (especially
> since it seems like this change will be in 0.3)

People can run with --legacy_external_runfiles if they need that path while rules are updated (which is in the release notes).
