### ISSUE TITLE
Invalid null return can be conflated with uninitialized variable

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/bazel#13299]
### Description of the problem / feature request:

In https://github.com/bazelbuild/rules_rust/issues/635 , we hit a confusing error with the `cc_toolchain`. It was producing an error that made it look like a variable wasn't in lexical scope when it was. Maybe its assignment triggered something like an exception or an undefined value, but it was assigned in a lexical sense.

I assigned this variable to 0, and got an error I would expect for an incorrect type. Whatever find_cpp_toolchain is/was doing seems to result in a lexical error that is difficult to interpret.

This was all happening in Bazel 4.0. cc @katre

**Comment by brandjon** [comment]
It sounds like the issue was triggered by `ctx.toolchains[...]` returning `null`, which is not a valid Starlark value. This would cause the variable it gets assigned to to be interpreted as still being uninitialized, which explains that error message.

The immediate fix (if it hasn't already been implemented) is to not return `null` as a Starlark value.

We could also add more validation to the point in the interpreter where null was being passed through. Extra validation would require a little benchmarking to ensure it isn't a significant performance regression.
