### ISSUE TITLE
Richer generic type annotations in `@ParamType`

### ISSUE THREAD

**Issue by tetromino** [bazelbuild/bazel#13365]
Currently, in src/main/java/net/starlark/java/annot/ParamType.java, we require `generic1` to be a scalar type value:

```java
  // TODO(adonovan): make this an array---a non-breaking change for most clients---
  // ideally of the same length as the number of type parameters of type().
  Class<?> generic1() default Object.class;
```

Quoting @alandonovan from https://github.com/bazelbuild/bazel/pull/12637#discussion_r537059010:

> A change I would like to make is to replace generic1 with an array of Class types for the list of parameters. The assumption that there is one parameter makes no sense for Dicts, for example.
> 
> However, it is a surprisingly involved change, especially in its interactions with Copybara (the other application that uses java.starlark.net).

An additional use case is to declare a container which can hold multiple types. For example, several functions in `actions` module (e.g. `actions.run_shell()`) take parameters which can may be a sequence of strings or actions.args() objects intermixed arbitrarily.

Similarly, we might imagine a dict whose keys may be either strings or integers, and whose values might also be of multiple types.

Thus, a plain array of types is probably insufficient in the long term (although it might cover 90% of our use case, and thus be good enough for now).

For prior art of how generic types ought be represented, we should take a look at [`typing` in Python 3](https://docs.python.org/3/library/typing.html).

**Comment by brandjon** [comment]
(Moving to team-Starlark-Interpreter because the annotation system lives inside the net.java.starlark namespace.)

> An additional use case is to declare a container which can hold multiple types.

Emphasis on that being a separate use case. The one Alan was referring to is how `Sequence<V>` has one type variable `V` while `Dict<K, V>` has two vars `K` and `V`.

The problem with richer types is that it's a rabbit hole, and a lot of extra complexity for relatively small benefit. For instance, look at the old `SkylarkType.java` / `StarlarkType.java` file that used to exist a couple years ago. That class purported to establish a type lattice. There were a lot of edge cases it didn't cover, and that wasn't a problem because the use cases weren't really there anyway. But what was a problem was maintaining the extra bloat as we refactored the interpreter.

We also don't need to do everything in the annotation system because we have helpers like `Sequence.cast` and can add more as needed. Or we can just continue to use bespoke code for complicated cases (like allowed-providers, which can be a list of providers/strings or a list of such lists). Let's only add machinery/helpers if there are at least several callers.

> For prior art of how generic types ought be represented, we should take a look at `typing` in Python 3.

Personally I dislike how complicated/inconsistent Python typing is. But even if we use a relatively simple type language, my above concern still applies.
