### ISSUE TITLE
Bazel query cannot resolve paths that are not in the root workspace

### ISSUE THREAD

**Issue by luna-duclos** [bazelbuild/bazel#13398]
### Description of the problem / feature request:

Given the following repo layout:

```
WORKSPACE
foo/bar/WORKSPACE
foo/bar/file.txt
```

When doing a bazel query from the root workspace into the sub-workspace like so: `bazel query foo/bar/file.txt`, the query cant actually solve the file, despite this working fine in the root workspace
Instead, one has to word the query like so: `bazel query @bar//:file.txt`, which then works fine for all queries

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to be able to feed a list of modified files from git directly into bazel query without having to do a bunch of preprocessing first, can we make the direct way work ? Right now I had to build a Go tool that resolves the workspace, package and label of each file before passing them to bazel query, which is absurd

### What operating system are you running Bazel on?

Linux, MacOS and Windows

### What's the output of `bazel info release`?

```
release 4.0.0
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Private repo, so not applicable

###  Have you found anything relevant by searching the web?

I have not

### Any other information, logs, or outputs that you want to share?

No

**Comment by janakdr** [comment]
The logic to interpret a path as a target is here: https://github.com/bazelbuild/bazel/blob/863383aa4f67948b2024ba583b196defabb9e21d/src/main/java/com/google/devtools/build/lib/cmdline/TargetPattern.java#L340. We only ever try the main repository. This is not actually query-specific, it's about interpretation of any target pattern. Passing back to team-XProduct, since team-Core is pretty ignorant of how sub-workspaces work and how to resolve them. Happy to consult on the solution. My guess is that you'll need to augment TargetPatternResolver to answer if a path prefix corresponds to a sub-workspace, then use that repository instead of the main one?
