### ISSUE TITLE
win10 Extracting Bazel installation...

### ISSUE THREAD

**Issue by rainmakerMa** [bazelbuild/bazel#13401]
I have installed the bazel 3.1.0 version

but when i try to use bazel to build, whatever i type bazel ...

it just show Extracting Bazel installation...  and quit , why is is ? 

i want to use bazel to compile tensorflow, sos!!!

**Comment by philwo** [comment]
Hi @rainmakerMa,

I'm sorry that Bazel is not working for you!

Could you post your question on our mailing list https://groups.google.com/g/bazel-discuss maybe? More people who might have had the same problem can see it there and try to help you! I'm happy to also respond there with some ideas.

If we find out that it's caused by a Bazel bug, we can continue here to track the debugging and fix.

Thanks,
Philipp
