### ISSUE TITLE
Typical formatting of rule docstring is unusable for Markdown output

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#13402]
Commonly a rule with multi-line documentation can have a second paragraph, which developers commonly indent to be readable within the dictionary where it's declared:

```
example_rule = rule(
    implementation = _rule_impl,
    doc = """Small example of rule using a markdown template.

    This paragraph should not have extra intent, as that would make it a code block.
    """,
    attrs = {
        "first": attr.string(doc = "This is the first attribute"),
        "second": attr.string(default = "2"),
    },
)
```

However when producing Markdown-format output, the extra indent on the lines following the first causes that text to be a code block.

> Small example of rule using a markdown template.
> ```
>     This paragraph should not have extra intent, as that would make it a code block.
> ```

Bazel has [code to account for this](https://github.com/bazelbuild/bazel/blob/4.0.0/src/tools/starlark/java/com/google/devtools/starlark/common/DocstringUtils.java#L202) by inferring the baseline indentation, however this logic doesn't apply to the rule documentation string.

As a real-world example, see the codeblock that appears here:
https://bazelbuild.github.io/rules_kotlin/kotlin#kt_jvm_binary
and the (ugly) fix required currently:
https://github.com/bazelbuild/rules_kotlin/pull/533/files#diff-4494836edf6b3f0b67056cb72ef24752d21a8c08eb8f2ca4790780179dd76d81R315

**Comment by alexeagle** [comment]
The same problem can be observed on docstrings for rule attributes. I can file a separate issue for that if the fixes go in separate PRs.

**Comment by brandjon** [comment]
@tetromino and I agree that this is useful for markdown and seems at least non-harmful for other output formats.

If we already have indentation logic, we should probably share it for any built-in dedent feature. But we could consider making a (backwards incompatible) change if that logic is surprising/deficient.

Design questions:

* What strategy should dedent logic use? Python has [`textwrap.dedent`](https://docs.python.org/3/library/textwrap.html#textwrap.dedent), but that doesn't account for the first line, which is often unindented non-whitespace content. It also doesn't strip leading and trailing whitespace/newlines, which arguably you might want in order to treat

```
    def f():
        """
        abc
        xyz
        """
```

as identical to

```
    def f():
        """abc
        xyz"""
```

* What should be considered whitespace? `textwrap.dedent` handles both spaces and tabs but considers them non-equal for the purpose of determining common leading whitespace. Should we do the same? But Starlark (at least the Java implementation) doesn't allow tabs for indentation of code, so allowing it for documentation seems inconsistent.

* Where in the pipeline should indentation processing be applied?

    * Immediately upon evaluation of the docstring (e.g. `StarlarkFunction#getDocumentation`)? This would mean indentation is already processed (and not recoverable) at the time of a hypothetical `bazel query` command that dumped out doc content.

    * Before generating the doc content protos (`stardoc_output.proto`)? But note that when we rewrite stardoc doc extraction, this choice kind of merges with the above.

    * Internally to whatever rendering template applies to the extracted doc content?

**Comment by tetromino** [comment]
https://github.com/bazelbuild/stardoc/pull/170 will complete the fix by updating Stardoc's extractor
