### ISSUE TITLE
Warning about mismatched remote / local Xcode versions when not running remotely

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#13413]
If you have some Xcode config like:

```bzl
available_xcodes(
    name = "local",
    default = ":version12_4_0_12D4e",
    versions = [
        ":version12_4_0_12D4e",
        ":version12_5_0_12E262",
    ],
)

available_xcodes(
    name = "remote",
    default = ":version12_4_0_12D4e",
    versions = [
        ":version12_4_0_12D4e",
    ],
)
```

Where 12.5 is only available locally, but you only pass `--strategy=local`, you still see this warning:

```
WARNING: /.../bazel/third_party/BUILD:47:13: in xcode_config rule //bazel/third_party:xcode_config: --xcode_version=12E262 specified, but it is not available remotely. Actions requiring Xcode will be run locally, which could make your build slower. Consider using one of [12.4.0.12D4e].
```

I would only expect to see this if I was actually executing actions remotely.

**Comment by susinmotion** [comment]
Xcode selection happens in the analysis phase, where the strategy hasn't come into play yet. 

The way we work with this internally is by passing an `--xcode_config` that only contains local versions (eg `@local_config_xcode//:host_xcodes`) if we're not using remote execution.

In order to get rid of the warning if `--strategy=local`, we'd need to reevaluate the Xcode config when the strategy changed, which I'm hesitant to do, though I could be convinced.
