### ISSUE TITLE
Support API Level 30 with NDK r21 (in ndkcrosstools)

### ISSUE THREAD

**Issue by EwoutH** [bazelbuild/bazel#13421]
### Problem

Currently the latest LTS build of the Android NDK (r21e) doesn't seem to support the latest stable Android API Level (30).

Over at [google/lyra](https://github.com/google/lyra) we got the [following error](https://github.com/google/lyra/runs/2388488717#step:3:33) when trying to upgrade to the API Level 30:
```
WARNING: API level 30 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 29
```
Targeting the API level 30 is [mandatory](https://support.google.com/googleplay/android-developer/answer/9859152#zippy=%2Ctarget-api-level-requirements-for-the-play-console) for the Google Play store starting from August 2, 2021 for new apps and  from November 1, 2021 for app updates.

### Bazel version

4.0.0 (the latest stable release)

### Environment

* NDK Version: r21e, the current LTS release (`21.4.7075529`)
* Host OS: Ubuntu 20.04.2 LTS (GitHub [virtual environment](https://github.com/actions/virtual-environments/blob/ubuntu20/20210425.1/images/linux/Ubuntu2004-README.md))
* ABI: arm64-v8a
* NDK API level: 30
* Device API level: 30

### Build log

This [GitHub Actions build](https://github.com/google/lyra/runs/2388488717#step:3:33) contains the error.

### Possible solution

The problem is probably in [ApiLevelR19.java#L57](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/android/ndkcrosstools/r19/ApiLevelR19.java#L57), where API Level 30 isn't supported.

Also see: [NDK 21 support](https://github.com/bazelbuild/bazel/commit/7c00472efb05164cae8f415c548812a1877e6e9a), where NDK 21 support was added, but only with API Level 29 and not Level 30.

**Comment by EwoutH** [comment]
Additionally, the Android Gradle plugin [version 4.2.0](https://developer.android.com/studio/releases/gradle-plugin#4-2-0) also ships with SDK Build Tools 30 and NDK 21.4.

**Comment by ahumesky** [comment]
It looked like this was as simple as adding 30 to this map:
https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/bazel/rules/android/ndkcrosstools/r19/ApiLevelR19.java#L25

However, I think there's a small bug in how the API level checks are implemented. The r19 crosstool generator code is shared between 19, 20, and 21;
https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/bazel/rules/android/ndkcrosstools/AndroidNdkCrosstools.java#L54-L56

and have the same API level data:
https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/bazel/rules/android/ndkcrosstools/r19/NdkMajorRevisionR19.java#L40

but NDK r19 only supports up to API level 28, r20 supports up to api 29, and r21 supports up to api 30.

The means that if `android_ndk_repository` points to ndk version r19 or r30, its `api_level` attribute could have 30 in it, and later actions will fail with errors like "file not found" (because there's no `android-30` directory in the ndk's platform directory). If there is no `api_level` specified, then it should still correctly pick the latest version in the ndk though.

Hopefully this will just require refactoring a few things. Bazel was able to compile a simple app with native code with ndk r21 and api level 30.
