### ISSUE TITLE
native.glob does not work with @//

### ISSUE THREAD

**Issue by abergmeier** [bazelbuild/bazel#1346]
When globbing the following leads to an error message about empty segments:

```
native.glob( ["@//common/*"] )
```

Problems seems to be that it splits by `/` and then checks the result that no empty segment is present.

**Comment by meteorcloudy** [comment]
Sorry, we don't support this. The argument of glob is not a list of label, it has to be a list of path.

**Comment by abergmeier** [comment]
Fair enough. Should I write a patch that then errors when you try to call glob with a string starting with `@` or `//`?

**Comment by meteorcloudy** [comment]
That would be nice~ :)

**Comment by laurentlb** [comment]
A file can contain `@` and you might want to match it. The only thing we can do is detect `//`, but apparently it's already done?

**Comment by nickgeorge** [comment]
Hmm I'd like to follow up on this - I'm trying to refer to files on an external archive, so I have an http_archive with 
`exports_files(glob(["package/**"]))`
as the build rule - seems like that should make 
`glob(["@my_archive//*.json"])`
work.  Is there a workaround for this?  One option would be to define all the subsets as filegroups in the http_archive build rule, but that would be pretty ugly - seems better to let the user of the archive specify which files they want

**Comment by Devatoria** [comment]
Any news about that? It seems a legit use case to be able to glob on files exported by another module through `exports_files`, no?

**Comment by meteorcloudy** [comment]
@lberki Any idea on this? I guess we don't support this for a reason?

**Comment by gonzojive** [comment]
Is there a commonly used library for creating a distinct target that selects a file or set of files from within a filegroup?

**Comment by lberki** [comment]
@gonzojive I don't know of any (that doesn't mean that ti doesn't exist, though!)

@meteorcloudy the reason why we don't support globbing like this is that if you allowed one to glob e.g. the contents of package from package B, what package B is would depend on the contents of package A and Bazel would like to keep these independent for two reasons:
1. To be able to reason about caching packages (both for humans and for machines)
2. So that people cannot reach into internals of other packages (if Bazel allowed to do this, adding a source file to a package would be a breaking change)
