### ISSUE TITLE
--explain explain should tell what files changed

### ISSUE THREAD

**Issue by metti** [bazelbuild/bazel#13566]
### Description of the problem / feature request:

Running `bazel --explain explain.log` will create `explain.log` with an explanation why a target was rebuilt. Unfortunately it lacks detailed information about which files changed. Instead a typical diagnostic is:

```
Build options: --announce_rc --explain explain.log
Executing action 'BazelWorkspaceStatusAction stable-status.txt': unconditional execution is requested.
Executing action 'Building something //some:target': One of the files has changed.
```

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to specify `--explain explain.log` for my builds unconditionally to adhoc debug "huh-why-did-this-now-build?"-situations.

Ninja's explain log `-d explain` helped me in the past numerous times to track down dependency issues.

### What's the output of `bazel info release`?

`development version`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Recent Bazel used for Android

**Comment by lberki** [comment]
The reason why Bazel doesn't have this admittedly basic piece of functionality is that it's, surprisingly, not doable with the data Bazel keeps about an action.

Since some action have a lot of inputs, Bazel doesn't store the checksums of each input or even the set of inputs for each cached action (except for C++). Instead, what it does it stores just the xor of all the checksums of all `<input path, checksum of input file>` pairs (see `MetadataDigestUtils.fromMetadata()`

So when one of these files changes, it's detected, but Bazel cannot tell which one changed (hell, I don't even know how we detect when the set of inputs files changed...)

In order to fix this, we could do two things:
1. Peek into Skyframe invalidation (that wouldn't work on Bazel server restarts, but it would work most of the time and it would be complicated)
2. Replace the action cache (it's looking increasingly like a tempting target for multiple reasons, but it's not a small amount of work and it has to fulfill some pretty strict CPU and RAM constraints)

**Comment by lberki** [comment]
(/cc @janakdr since we discussed this yesterday)
