### ISSUE TITLE
`aar_import` does not except `JavaInfo` providers in `exports` attribute

### ISSUE THREAD

**Issue by menny** [bazelbuild/bazel#13567]
### Description of the problem / feature request:

Allow any `JavaInfo` to be referenced in `aar_import#exports`

Looking at the [source code](https://github.com/bazelbuild/bazel/blob/ec7affdfa40072bb1dc3ba7ba430aebb6adf69e9/src/main/java/com/google/devtools/build/lib/rules/android/AarImportBaseRule.java#L55) `exports` is locking the references to `aar_import` or `java_import`.

Note that `deps` do allow `jvm_import`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I tried to add a [`jvm_import`](https://github.com/bazelbuild/rules_jvm_external/blob/aa530f0c37d86d18040df82ca7e5de7a4732f861/private/rules/jvm_import.bzl) target to the list of `aar_import#exports`.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

not really

### Any other information, logs, or outputs that you want to share?

none

**Comment by jin** [comment]
Yeah, I think aar_import should be able to export JavaInfo in jvm_import since it already exports java_import. I think this is an issue for changing the native aar_import rule to not use rule classes as a filter for the exports attribute, and nothing much rules_jvm_external can do here. Alternatively, we can also require usage of the Starlark aar_import which @ahumesky added (IIRC) and modify that instead.

**Comment by menny** [comment]
Are you referring to https://github.com/bazelbuild/rules_android/tree/pre-alpha? Is that usable?
