### ISSUE TITLE
--cache_test_results for test invalidate build analysis cache

### ISSUE THREAD

**Issue by guibou** [bazelbuild/bazel#13648]
### Description of the problem / feature request:

I do have `test --cache_test_results` in my `.bazelrc` and whenever I'm running `bazel test` or `bazel run`, I'm receiving the following message and a new analysis phase is run:

```
INFO: Build option --cache_test_results has changed, discarding analysis cache.
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ bazel test --cache_test_results //...
$ bazel build //...
$ bazel test --cache_test_results //...
$ bazel build //...
```

See the `INFO` message and the slowdown because analysis is redone.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

`release 4.0.0- (@non-git)`

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

from nixpkgs.

**Comment by brentleyjones** [comment]
Btw, If you set `build --cache_test_results` in your `.bazelrc` (instead of `test --cache_test_results`), it will prevent the analysis cache thrashing.

**Comment by meisterT** [comment]
@sdtwigg will this go away after your work is done?

**Comment by guibou** [comment]
I do have a similar problem with `--run_under` which also trash the analysis cache. In summary, there is too much options trashing the analysis cache even if they have no impact on the analysis phase.

**Comment by sdtwigg** [comment]
For Bazel, `--trim_test_configuration` should already be enabled by default (in the latest versions) and stopping a full throwaway of analysis (test targets will still be re-analyzed) when `--cache_test_results` is changed.

`--run_under` is unfortunately a different issue (as it does technically impact the analysis phase more than one might expect to ensure runfiles of underlying binaries are properly changed). It still might be possible to do something here, but the fix is not as obvious.
