### ISSUE TITLE
Consider using PID namespaces for the sandbox

### ISSUE THREAD

**Issue by hermione521** [bazelbuild/bazel#1368]
Mentioned by Lukács:

It seems that they would make the cleanup much simpler and more complete, because if you kill -9 the internal init from the outside, all processes in the namespace are automatically killed. It also becomes the parent of orphaned processes within the sandbox, which is also useful:

http://man7.org/linux/man-pages/man7/pid_namespaces.7.html
https://lwn.net/Articles/532748/

**Comment by philwo** [comment]
This is work-in-progress and I should have a CL that implements it ready tomorrow.

**Comment by damienmg** [comment]
It is implemented.

**Comment by abergmeier-dsfishlabs** [comment]
And how do I disable that for testing?

**Comment by philwo** [comment]
@abergmeier-dsfishlabs You can't disable the PID namespacing support in the sandbox, because we now rely on it to clean-up child processes. In comparison, the process-wrapper that is used when you completely disable sandboxing tries to clean-up children on SIGTERM by putting them in the same process group, then forwarding the SIGTERM to that group. However that's not nearly as reliable.

Is there a reason why you'd like to disable PID namespacing for testing?

**Comment by abergmeier-dsfishlabs** [comment]
@philwo I had a Python native module, which was misbehaving (multithread deadlock) in tests. GDB complains about not working properly with PID namespacing. I wonder how you guys then debug broken C++ tests.

**Comment by abergmeier-dsfishlabs** [comment]
BTW: Using `--spawn_strategy=standalone` seems to have changed the PID namespace handling to a certain degree!?

**Comment by philwo** [comment]
@abergmeier-dsfishlabs Yes, PID namespacing is a feature provided by the sandbox strategy (more specifically, by linux-sandbox.cc - it only works on Linux, macOS doesn't seem to have something similar).

The way to disable PID namespacing is to disable sandboxing, which you did with --spawn_strategy=standalone. :) For debugging this seems like a good way.
