### ISSUE TITLE
Build event upload hangs indefinitely when onError is called during completion

### ISSUE THREAD

**Issue by oehme** [bazelbuild/bazel#13689]
I was testing a build event service and noticed that Bazel hangs indefinitely if that service fails during `onCompleted` handling. Here's a service implementation that you can reproduce this with: 

``` 
@Override
public StreamObserver<PublishBuildToolEventStreamRequest> publishBuildToolEventStream(StreamObserver<PublishBuildToolEventStreamResponse> responseObserver) {

    return new StreamObserver<>() {
        @Override
        public void onNext(PublishBuildToolEventStreamRequest value) {
            responseObserver.onNext(PublishBuildToolEventStreamResponse.newBuilder()
                    .setStreamId(value.getOrderedBuildEventOrBuilder().getStreamId())
                    .setSequenceNumber(value.getOrderedBuildEvent().getSequenceNumber())
                    .build());
        }

        @Override
        public void onError(Throwable t) {
        }

        @Override
        public void onCompleted() {
            responseObserver.onError(new RuntimeException("Boom"));
        }
    };
}
``` 

The build waits indefinitely on `Waiting for build events upload: Build Event Service`. This does not happen if `onError` is called in `onNext` handling. In that case Bazel notices the error, retries a couple times and eventually gives up.

**Comment by meisterT** [comment]
Cc @michaeledgar

**Comment by michaeledgar** [comment]
By using your example `StreamObserver` in `BazelBuildEventServiceModuleTest`, I've confirmed the hang happens when you run bazel with the default flags: `--bes_upload_mode=WAIT_FOR_UPLOAD_COMPLETE --bes_timeout=0s`. As a workaround, you can set either --bes_timeout to a positive value, and/or change `--bes_upload_mode` to either `NOWAIT_FOR_UPLOAD_COMPLETE` or `FULLY_ASYNC`. Both of these modes allow BES uploading to continue after a command has run, which may or may not be suitable for your use-case.

I'm looking into the suitable fix for the `--bes_upload_mode=WAIT_FOR_UPLOAD_COMPLETE --bes_timeout=0s` case now.
