### ISSUE TITLE
package(default_visibility=X) differs from visibility=X

### ISSUE THREAD

**Issue by dmivankov** [bazelbuild/bazel#13681]
### Description of the problem / feature request:

`package(default_visibility = X)` works differently from explicitly setting `visibility = X`
Namely `visibility=` can refer to other `@repository//some:__pkg__`, but `default_visibility` ignores such entries.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

A/WORKSPACE
```py
workspace(name = "A")

new_local_repository(
  name = "B",
  path = "../B",
  build_file_content = """
package(default_visibility = ["@A//:__pkg__"]) # line 1
genrule(
  name = "b.gen",
  outs = ["b"],
  cmd = "echo >$@",
#  visibility = ["@A//:__pkg__"], # line 2
)
  """
)
```
A/BUILD
```py
alias(
  name = "a",
  actual = "@B//:b",
)

genrule( # to also test non-trivial targets
  cmd = "echo >$@",
  name = "aa",
  outs = ["aaa"],
  srcs = ["@B//:b"],
)
```
B - empty directory
```sh
$ cd A
$ bazel build @B//:b
# ok

$ bazel build @A//:a
A/BUILD:1:6: in alias rule //:a: target '@B//:b' is not visible from target '//:a'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//:a' failed; build aborted: Analysis of target '//:a' failed

$ bazel build @A//:aaa
A/BUILD:6:8: in genrule rule //:aa: target '@B//:b' is not visible from target '//:aa'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//:aaa' failed; build aborted: Analysis of target '//:aa' failed
```
but if line 1 is commented out in A/WORKSPACE and line 2 uncommented all 3 build commands suddenly start to work
```sh

```
### What operating system are you running Bazel on?

NixOS

### What's the output of `bazel info release`?

release 4.1.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

via NixPkgs

**Comment by brandjon** [comment]
`default_visibility` is [parsed](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/packages/DefaultPackageArguments.java#L53) using [`PackageUtils.getVisibility`](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/packages/PackageUtils.java#L26), which dispatches to `PackageGroupsRuleVisibility`, which tries to [process](https://github.com/bazelbuild/bazel/blob/9302ebd906a2f5e9678f994efb2fbc8abab544c0/src/main/java/com/google/devtools/build/lib/packages/PackageGroupsRuleVisibility.java#L37-L42) the arg as a `package_group` package path string, and failing that considers the arg to be a label of a `package_group` target.

So the problem is that `default_visibility` does not recognize the same cases that `visibility` does. It's instead a bizarre mix of `package_group` and `visibility` syntax, that allows `//pkg/...` and `//visibility:public`, but not `//pkg:__subpackages__`.
