### ISSUE TITLE
[4.2.0rc1] RBE failures

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#13712]
Many downstream tests for the 4.2.0rc1 release (#13558) that use RBE are failing with the same error:

```
(14:37:15) ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/5b34f2c948c819bb75d6ced27ba4bd5d/external/rbe_ubuntu1604_java8/java/BUILD", line 19, column 60, in <toplevel>
		load("@bazel_tools//tools/jdk:local_java_repository.bzl", "local_java_runtime")
Error: file '@bazel_tools//tools/jdk:local_java_repository.bzl' does not contain symbol 'local_java_runtime'
(14:37:15) ERROR: Analysis of target '//src:bazel' failed; build aborted: error loading package '@rbe_ubuntu1604_java8//java': Package 'java' contains errors
(14:37:15) INFO: Elapsed time: 24.554s
(14:37:15) INFO: 0 processes.
(14:37:15) FAILED: Build did NOT complete successfully (16 packages loaded, 19 targets configured)
```

**Comment by katre** [comment]
Example: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2105#8c39fda3-2658-4c6f-98b1-75bc366798a9

**Comment by katre** [comment]
Possibly related, but not RBE: rulles_appengine is failing with:
```
(14:40:01) ERROR: Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/3852df67dc47caa68319f9a882de2fb0/external/rules_appengine_toolchain/BUILD.bazel", line 5, column 6, in <toplevel>
		"JVM8_TOOLCHAIN_CONFIGURATION",
Error: file '@bazel_tools//tools/jdk:default_java_toolchain.bzl' does not contain symbol 'JVM8_TOOLCHAIN_CONFIGURATION'
(14:40:01) ERROR: /var/lib/buildkite-agent/builds/bk-docker-mtbz/bazel-downstream-projects/rules_appengine/appengine/BUILD:15:6: no such target '@rules_appengine_toolchain//:jdk8': target 'jdk8' not declared in package '' defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/3852df67dc47caa68319f9a882de2fb0/external/rules_appengine_toolchain/BUILD.bazel and referenced by '//appengine:jdk8'
```

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2105#d80cadd7-1846-4878-a93b-efbae0f5bbba

**Comment by katre** [comment]
Looks like `local_java_runtime` was added in ba8d404978056ff2b56f4a3056d661f432fb2e58, and `JVM8_TOOLCHAIN_CONFIGURATION` in 6202271b9b1bdf1b73b1e2ad55f30cf467899005.

Assigning to @comius to figure out if there's a cherrypick that will fix this, or if we need to do something more drastic.

**Comment by katre** [comment]
Repro instructions:

Check out [rules_go](https://github.com/bazelbuild/rules_go).

Build bazel from the [release branch](https://github.com/bazelbuild/bazel/tree/release-4.2.0rc1).

Run:
```
bazel-dev build --nobuild --nokeep_going --config=remote_shared --incompatible_strict_action_env --host_javabase=@buildkite_config//java:jdk --javabase=@buildkite_config//java:jdk --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --crosstool_top=@buildkite_config//cc:toolchain --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 --extra_toolchains=@buildkite_config//config:cc-toolchain --extra_execution_platforms=@buildkite_config//config:platform --host_platform=@buildkite_config//config:platform --platforms=@buildkite_config//config:platform -- //...
```

**Comment by comius** [comment]
This is again problem with condition in old bazel-toolchains https://github.com/bazelbuild/bazel-toolchains/commit/19884d30a8fd3a1a6aef46ccb7e7f36e41ca572b

@philwo knows how to best handle it.

**Comment by katre** [comment]
@philwo Please let me know if you have a chance to investigate this, it is blocking the 4.2.0 release.

**Comment by philwo** [comment]
Oh, I think these failures are OK - it's just that the version check in bazel-toolchains does not correctly work for Bazel release candidate versions. The breakages will automatically go away once the actual final release is out.

...

Wait a sec, I think I'm having a déjà vu. 😀 

So, I checked rules_go, rules_appengine and Bazel at the above failed commit f7267329c9623dc3065b7d51c9346cb22183931d. They all have the fixed bazel-toolchains version 4.1.0 in their WORKSPACE file, so it should be fine.

Could it be that the version check *actually* does not work for release candidates, because the downstream pipeline does not correctly embed the version number? See the `bazel info` part of the above linked Buildkite job:

```
/tmp/tmp89plcxnw/bazel --nomaster_bazelrc --bazelrc=/dev/null version
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Build target: bazel-out/k8-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0
```

No version number, thus the check "fails open" and runs into the Bazel >= 5.0.0 code path, which does not work with our 4.2.0rc1 of course. 🤔

**Comment by philwo** [comment]
@meteorcloudy Could we improve the downstream pipeline so that when it's running for a branch called `release-4.2.0rc1` it automatically embeds the correct version number (possibly we should just embed `4.2.0` and omit the rc1 part, because some of the version checks assume that the components only contain integers..) in the build steps?

**Comment by katre** [comment]
Is this an issue with the pipeline or with the way I created to he release?

I'd really like to get this right and verify it before the release finishes.

There's already going to be an RC2 next week if we need to test or tweak.

**Comment by philwo** [comment]
I think it's the pipeline. As we can see here:

![image](https://user-images.githubusercontent.com/504652/126840398-bf93f04b-c34a-48b5-ad40-649c517b52ea.png)

In the failing step it downloaded the Bazel binary that was built in this previous step:

![image](https://user-images.githubusercontent.com/504652/126840474-2c5a94c7-3b51-46e2-b65f-3062d89ac684.png)

There is no `--embed_label` or anything in the build command line, thus the resulting binary does not have a version.

We should probably add the required flags for embedding the version information when `save_but` is True in `execute_commands`: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/bazelci.py#L981

**Comment by meteorcloudy** [comment]
OK, I'll look into how to make this work today!

**Comment by meteorcloudy** [comment]
I embedded the version into the rc binary, now projects are failing because the version is too high....

During RBE toolchain configuration:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2115#9338eccf-cfa0-49d4-adf2-d4ffa5ba823f
```
2021/07/26 09:44:27 could not download Bazel: HTTP GET https://releases.bazel.build/4.2.0/release/bazel-4.2.0-linux-x86_64 failed with error 404
```

During version check:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2115#ff1acde8-325f-41b3-b38a-3669bfcc7442
```
Error in fail: Your bazel is too new. Maximum supported version 4.1.0 of bazel, found 4.2.0
```

**Comment by coeuvre** [comment]
Maybe it's a good chance to cherrypick https://github.com/bazelbuild/bazel/pull/13633 to replace `rbe_autoconfig` with `rbe_configs_gen`?

**Comment by meteorcloudy** [comment]
> Maybe it's a good chance to cherrypick #13633 to replace rbe_autoconfig with rbe_configs_gen?

We'll have to cherry-pick this for all downstream projects that enables RBE, right? I think that's a bit too much work?

I looked into the source of rbe_configure, it seems that if I include the the rc name in the version lable, it might work. Let me try that first.

**Comment by coeuvre** [comment]
> We'll have to cherry-pick this for all downstream projects that enables RBE, right? I think that's a bit too much work?

Yes. We probably need to find an easier way for downstream projects to use the configurations generated by `rbe_configs_gen`.

**Comment by meteorcloudy** [comment]
The downstream is now greener when we have version "4.2.0rc1" embedded:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2116#_

**Comment by meteorcloudy** [comment]
- Android Studio Plugin failed expected with "soft fail", so can be ignored.
- Bazel examples failed on version check because it requires the bazel version to be digit, it passed in the build without version embedded.
- rules_gwt failed because it doesn't work on ubuntu 18.04 after [dropping 16.04](https://github.com/bazelbuild/rules_gwt/commit/28d48b0277d047cc4be3346507cff12ad50db5c9).
- rules_nodejs failed on rbe is also an known failure.

**Comment by katre** [comment]
Thanks @meteorcloudy! Are there any changes I need to cherrypick into release-4.2.0-patches for these, or was this all pipeline fixes?

**Comment by meteorcloudy** [comment]
@katre Nope, there are only fixes from the CI scripts.

**Comment by katre** [comment]
Thanks. Closing this for now.
