### ISSUE TITLE
String representation of Label type drops reference to the main repository

### ISSUE THREAD

**Issue by mmcloughlin** [bazelbuild/bazel#13731]
### Description of the problem:

The string representation of `Label` type drops reference to the main repository.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The full problem is described in google/llvm-bazel#236. The underlying cause is that `str(Label("@//path/to/label")) = "//path/to/label"`. Please let me know if there is a better way to solve this problem.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
release 4.1.0
```

###  Have you found anything relevant by searching the web?

Looking at the source code, it appears to me that the functionality required is already in the `Label.getUnambiguousCanonicalForm()` method, whereas string conversion uses `Label.getCanonicalForm()`.

https://github.com/bazelbuild/bazel/blob/227da61a0a522e5c3e3cd3f05e2e2d3a0a0c1b00/src/main/java/com/google/devtools/build/lib/cmdline/Label.java#L438-L444

It may be possible to fix this by changing string representation to use `getUnambiguousCanonicalForm`, or exposing `getUnambiguousCanonicalForm` through another method on the starlark type.

**Comment by brandjon** [comment]
In general it is not safe to convert a Label to a string and back again to a Label. The loss of info (main repo `@//pkg...` to default repo `//pkg...`) is one example, but you also have the same problem anytime there is repository remapping going on, such that `@repo//...` has a different meaning in the place where the str is converted back to a Label.

I think the real question is why building LLVM requires converting a Label through a string and back.

**Comment by GMNGeoffrey** [comment]
I don't believe we were converting a label to a string and then back to a label, at least not explicitly. We're trying to allow a user to pass in a label that indicates where a dependency should find some target. This is the implementation: https://github.com/llvm/llvm-project/blob/main/utils/bazel/zlib.bzl In particular, the issue was with `llvm_zlib_external`. I'm happy to know of other ways to achieve the result accomplished by these repository rules that doesn't have this fragility.

One thing I'd note in general when building these rules, is that figuring out what Bazel is going to resolve some label or path relative too is *super* confusing and you end up having to jump through all sorts of hoops to pass these around. See, for instance, our previous [implementation](https://github.com/google/llvm-bazel/blob/5ead6e3e642acdd5c85966d6371fb4c90fa322e3/llvm-bazel/overlay_directories.bzl#L70-L84) of a general rule to overlay one directory tree on top of another which required passing in some label referencing a workspace file in order to figure out what a path would be relative to. Thankfully as that rule became very specialized and with the move the LLVM monorepo, chsigg was able to simplify this quite a bit (https://reviews.llvm.org/D108274). Or as another example, this [rule for setting up submodules](https://github.com/google/iree/blob/fd8a769f8ca88eaf358d472e6d65f0616c22a52f/build_tools/bazel/workspace.bzl#L11) which I spent quite a while trying to make not require both a path *and* a label specifying the same thing, but was foiled.

**Comment by fmeum** [comment]
As of Bazel 6, this is fixed and `Label(str(l)) == l` is guaranteed for any label `l`.
