### ISSUE TITLE
Bazel in Windows Server 2016 Docker container failing when interacting with mounted workspace path

### ISSUE THREAD

**Issue by perezd** [bazelbuild/bazel#13797]
Error I'm seeing:
```
[FATAL 22:08:41.754 src/main/cpp/blaze.cc:1300] blaze_util::MakeCanonical('c:\workspace') failed: (error: 2): The system cannot find the file specified.
```

Here's a gist of the Dockerfile setup:
https://gist.github.com/perezd/1e812472666df2c9d42dd6eb5fa693d8

I'm running it like so:
```
docker run -v C:\my_local_workspace:C:\workspace <image_name> version
```

The dockerfile forwards args to Bazel, so in that above command I'm simply attempting to print version strings. If I remove the volume mount, version info prints just fine.

Something is going wrong here:
https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze.cc#L1300

I should also note, that in the `entrypoint.ps1` script, I can list the C:\workspace directory just fine and the contents are there.

Any suggestions? Workarounds?

**Comment by philwo** [comment]
It would be interesting to see where exactly Bazel fails in https://github.com/bazelbuild/bazel/blob/70073fd3ea1424e87e7ba16e29cd87aac7cb17e7/src/main/cpp/util/file_windows.cc#L474.

**Comment by philwo** [comment]
I wonder how Docker volumes are actually implemented on Windows.

@perezd out of curiosity, could you try not using the root directory of the volume as your workspace, but a subdirectory, e.g. `-WorkingDirectory "C:\workspace\ws"` in your entrypoint.ps1? Maybe this helps Bazel skip over the problematic behavior of the root of the volume.

**Comment by perezd** [comment]
Gave that a shot, getting the same error, just deeper: 

```
[FATAL 19:13:08.453 src/main/cpp/blaze.cc:1300] blaze_util::MakeCanonical('c:\workspace\ws') failed: (error: 2): The system cannot find the file specified.
ied.
```

**Comment by meteorcloudy** [comment]
Related issue https://github.com/bazelbuild/bazel/issues/11237, Bazel cannot resolve certain type of directory symlink and probably should not try to resolve them.

**Comment by meteorcloudy** [comment]
For this specific issue, https://cs.opensource.google/bazel/bazel/+/master:src/main/cpp/util/file_windows.cc;l=425 is the place the error was thrown, Bazel failed to open the symlink directory inside the docker.

**Comment by meteorcloudy** [comment]
I debugged this a bit, it turned out the [GetFinalPathNameByHandleW](https://cs.opensource.google/bazel/bazel/+/master:src/main/cpp/util/file_windows.cc;l=444?q=RealPath&ss=bazel%2Fbazel) doesn't work if the path is under a symlink to the host system.

We are hitting exactly the issue described here: https://blog.sixeyed.com/docker-volumes-on-windows-the-case-of-the-g-drive/

There is no simply fix for this issue, @perezd can you try the suggested workaround in that article?

**Comment by meteorcloudy** [comment]
Oh, the article also mentioned it's no longer an issue in Windows server 2019, can you probably upgrade the version of your docker image?

**Comment by perezd** [comment]
OK so I tried the G:\ drive hack, and I can determine that the drive mapping is working (ls works) but Bazel fails in the identical way. Does this still appear as a symlink to Bazel even as a mapped drive?

**Comment by perezd** [comment]
I can confirm this error is only windows server 2016, the docker image works as expected w/ 2019.

**Comment by meteorcloudy** [comment]
> Does this still appear as a symlink to Bazel even as a mapped drive?

It failed in `GetFinalPathNameByHandleW` in the equivalent implementation of [realpath](https://cs.opensource.google/bazel/bazel/+/master:src/main/cpp/util/file_windows.cc;l=421?q=RealPath&ss=bazel%2Fbazel) for Windows, so don't even check if it's a symlink.

I think our best chance is to use Windows server 2019, because even if we find a workaround for Bazel, you could still encounter the same issue with other tools.

**Comment by perezd** [comment]
Cool, lets close this as wontfix then, I have it working just fine in 2019 now.
