### ISSUE TITLE
Bazel cquery fails if paths are incompatible for platform

### ISSUE THREAD

**Issue by kwc** [bazelbuild/bazel#13861]
### Description of the problem / feature request:

Bazel `cquery` is a useful command for finding build dependencies you wish to avoid/remove in a specific configuration.

If you use Bazel `cquery` to find `somepath` or `allpaths` to a incompatible target, it will error with:

```
bazel --nohome_rc cquery  'allpaths(//foo:bar, //foo:baz)'
```
```
ERROR: Target //foo:baz is incompatible and cannot be built, but was explicitly requested.
```

As this is failing in a `bazel build` step, it actually does produce a relevant result, but accidentally, and if there are no query results, it simply returns an error instead of 0 results.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Using the following trivial `BUILD.bazel`, with one incompatible target:
```
sh_test(
    name = "foo",
    srcs = ["BUILD.bazel"],
)

sh_test(
    name = "bar",
    srcs = ["BUILD.bazel"],
)

sh_test(
    name = "baz",
    srcs = ["BUILD.bazel"],
    target_compatible_with = ["@platforms//:incompatible"],
)
```

A `cquery` between the targets shows how `cquery` will `ERROR` if the target is an incompatible target.
```
$ bazel cquery 'somepath(:foo, :bar)'
INFO: Analyzed 2 targets (1 packages loaded, 430 targets configured).
INFO: Found 2 targets...
INFO: Empty query results
INFO: Elapsed time: 0.770s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
$ bazel cquery 'somepath(:foo, :baz)'
ERROR: Target //:baz is incompatible and cannot be built, but was explicitly requested.
Dependency chain:
    //:baz   <-- target platform didn't satisfy constraint @platforms//:incompatible
INFO: Elapsed time: 0.243s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 3 targets configured)
```

Repeating the same command with `bazel query`:
```
$ bazel query 'somepath(:foo, :baz)'
INFO: Empty results
$ bazel query 'somepath(:foo, :bar)'
INFO: Empty results
Loading: 0 packages loaded
```

### What operating system are you running Bazel on?

Ubuntu 18.04

### What's the output of `bazel info release`?

`release 4.1.0`

###  Have you found anything relevant by searching the web?

No

The closest issue I can find is #13019, which is a separate query/genquery issue.

**Comment by kwc** [comment]
In an ideal world, I was hoping that `bazel cquery` works regardless of whether or not the code is actually build-able, since my main reasons for using the command are fixing or avoiding build issues. I need `cquery` instead of `query` as `select()` statements usually divert the incompatible dependencies. This is a corner case that interrupts normal bazel graph debugging workflows.

I found this because:

 1. Build error in our build due to dependency on incompatible target
 2. Try to use `bazel cquery` to find places where this incompatible target is leaking in
 3. Realize that `bazel cquery` isn't actually working, but able to keep debugging with just `bazel build` commands

The error output gives me similar information; however, it provides that information as error output, it only mimics `somepath`-like queries, and it always has an error result, which makes it difficult to use the command in automated tooling. 

I filed this bug after discussing this with @philsc in the hopes that there is some way of addressing this behavior longer term. That said, this is not super critical.

**Comment by gregestren** [comment]
This is fair. Conceptually cquery doesn't need to do *complete* analysis like in a real build. i.e. it doesn't actually need to create actions.

@katre and I have tossed around the idea of having `cquery` do more limited processing that avoids that. That would relieve this problem and reduce cases where `cquery`  doesn't work as a debugging tool because it fails just like the real build. We've noticed that annoyance too.

Less ambitiously, we could try having `cquery` make all targets "implicit". Incompatible target skipping, by its very name, is capable of skipping targets instead of failing, so long as you're building `:all`. I'm not sure what the code that flips that bit would look like.

I'm also curious what happens if you add [`--keep_going`](https://docs.bazel.build/versions/main/user-manual.html#flag--keep_going) to your query. I really have no idea if that helps, but it's an interesting interaction.

**Comment by philsc** [comment]
I think it makes sense for `cquery` to run these kinds of queries. The error that's currently being printed is really only meaningful when the user tries to build the target (since it's impossible to build an incompatible target).

**Comment by konste** [comment]
At this time with Bazel 4.2.1 I observe that `cquery` returns incompatible targets as well as compatible and this actually creates a problem for us, because we feed `cquery` output to the following `build` and it fails with `Target ... is incompatible and cannot be built, but was explicitly requested.`

**Comment by gregestren** [comment]
Happy you got a resolution, @konste . :)

Following up on my last comment, for the original bug, can anyone verify if adding `--keep_going` to the `cquery` gets around this? I'm specifically interested because of 

https://github.com/bazelbuild/bazel/blob/33f7648fbaa875f73416be47f0b3c10ed93f30d6/src/main/java/com/google/devtools/build/lib/analysis/constraints/TopLevelConstraintSemantics.java#L146-L164

which implies `--keep_going` demotes the error to a warning.

**Comment by gregestren** [comment]
All - I put up https://github.com/bazelbuild/bazel/pull/14311 to try to address this issue.

I'm very interested in your feedback. It's a bit of a paradigm shift for cquery and could introduce its own confusion (i.e. what @konste reported two comments above). But I'm cautiously optimistic this paradigm would be more sustainable.
