### ISSUE TITLE
Add default environment rules for Android

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#1386]
Probably using some form of `compatible_with` / `restricted_to`.

**Comment by ahumesky** [comment]
In particular since bazel defaults to java 8 now, you get this rather cryptic error if an android_binary depends on a java_library:

PARSE ERROR:
unsupported class file version 52.0

and you have to know to set `--javacopt="-target 7 -source 7"` or add `javacopts = ["-target 7 -source 7"]` to the library rule. This will be mitigated by java 8 -> java 7 desugaring, but doesn't help with things like API usage.

**Comment by ahumesky** [comment]
See https://github.com/bazelbuild/bazel/issues/2222 for java 8 desugaring

**Comment by aj-michael** [comment]
Even with java8 desugaring, I think we should still have some form on the constraints system to deal with this, because the desugarer does not handle all of java8.

**Comment by ahumesky** [comment]
We can add some default environments to `@bazel_tools` and see if we can default the android rules to use something like `@bazel_tools//build_environments:android`, e.g.

```
package(default_visibility = ["//visibility:public"])

environment(name = "android")

environment(name = "default")

environment_group(
  name = "execution_environment",
  defaults = [":default"],
  environments = [
    ":default",
    ":android",
  ]
)
```

**Comment by jin** [comment]
Closing in favor of toolchains/platforms.
