### ISSUE TITLE
Simple test runner for ios_test

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1387]
The existing test runner used in google3 for ios_test is very heavyweight and not (yet) open sourced. We would like to have a lightweight and simple test runner which we can open source. This bug tracks that effort.

Requirements:
- match existing test runner API so we can use the same rule with both test runners (we may be able to use a different execution template which means the API are the script template substitutions performed by bazel).
- output XML logs
- Actually run tests (support at least xctests)

Internal issue: b/24099852

**Comment by dmishe** [comment]
There has been a few talks about fixing the open source test runner, and this issue seems related.

In short, since the current OSS runner is not functioning, it would be nice to have it fixed. Current issues are:

- The paths to xctest and the app bundles seem to mixed.
- It uses iossim, a really old util for managing simulators, it should be replaced with xcodebuild runs.

Even better, restrict it to Xcode 8 because that will make the actual test runner code very simple. Literally a single xcodebuild invocation.

If that's ok, should we proceed here, or create a new issue?

**Comment by ulfjack** [comment]
Whatever it takes to get it working. If it only works with Xcode 8, then at least it works some of the time rather than none of the time.

**Comment by Andyccs** [comment]
Any update on this?

**Comment by ulfjack** [comment]
No, sorry. We're having trouble finding the time to work on this at all. All of our iOS experts are tied up in other work.

**Comment by steren** [comment]
Update: An `ios_test` skylark rule is planned for this quarter. @sergiocampama is working on it

**Comment by steren** [comment]
Update on my update: `ios_test` is just the skylark rule, not the test runner.

**Comment by steren** [comment]
An update: A new team member will be owning this work as a top priority. 
We'll keep you posted when we have an estimate date.

**Comment by c-parsons** [comment]
We have ios_ui_test and ios_unit_test (written in skylark) available for use.

https://github.com/bazelbuild/rules_apple

There's still more work we want to do on this test runner, but this should resolve this Feature Request as stated.
