### ISSUE TITLE
Document how repository_ctx is invalidated.

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1390]
This might be working as intended, but it's a bit weird.  Repository rules can access the environment, but are not invalidated by changes in the environment.  For example, I created a repository rule that printed out the contents of the environment variable ABC:

```
~/test$ ABC=456 ~/gitroot/bazel/bazel-bin/src/bazel build @b//:all
WARNING: /Users/kchodorow/test/tester.bzl:2:3: 456.
INFO: Found 0 targets...
INFO: Elapsed time: 3.962s, Critical Path: 0.01s
~/test$ ABC=123 ~/gitroot/bazel/bazel-bin/src/bazel build @b//:all
WARNING: /Users/kchodorow/test/tester.bzl:2:3: 456.
INFO: Found 0 targets...
INFO: Elapsed time: 0.282s, Critical Path: 0.00s
```

tester.bzl:

```
def _impl(repository_ctx):
  print(repository_ctx.os.environ['ABC'])
  repository_ctx.file('BUILD')

a = repository_rule(implementation = _impl, local = True)
```

WORKSPACE:

```
load('//:tester.bzl', 'a')
a(name = 'b')
```

(empty BUILD file).

**Comment by damienmg** [comment]
This is working as intended. Recategorizing as documentation.

FWIW, here the reason:

We could put a dependency to the environment but that would trigger rebuild on each environment change this is incorrect. We could add environment dependency on only the requested environment but that would skip the case where the requested environment variable name is contructed depending on the environment.

All those rules are fundementally non-hermetic. This is the reason for #974

**Comment by kchodorow** [comment]
Could repository rules have a field for environment settings they consume?  E.g.,

```
x = repository_rule(
    implementation = _impl,
    environ = ['ABC']
)
```

Then:

```
def _impl(repository_ctx):
  print(repository_ctx.os.environ['ABC'])  # works
  print(repository_ctx.os.environ['DEF'])  # error?
```

**Comment by shahms** [comment]
FWIW, I would really like this.  I suspect it would reduce the number of times I have to run `bazel shutdown` and/or `bazel expunge`.

**Comment by damienmg** [comment]
@shahms: yes that's incorrect to have to expunge right now. We are invalidating incorrectly on some case and we are not supporting manual invalidation which is the topic of #974. The idea is to be able to say "I want to reconfigure repository `@foo`"

@kchodorow: this is not really feasible: what about environment key that are computed by the workspace, how do you express them? Also the environment is something really volatile and it might change just because you relogged and forget to reset correctly env 'ABC', triggering a rebuild and failing the build, invaliding the whole cache (the main reason for C++ autoconf are users running on cluster, where the environment do change all the time due to the way they set-up the tooling). We had this discussion around the sandbox also.

**Comment by damienmg** [comment]
https://bazel-review.googlesource.com/c/6697/ the design doc that will serve as basis for this documentation, it explains the current behavior and the next one.
