### ISSUE TITLE
Finish BEP support for query/cquery/aquery

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#14208]
### Description of the problem / feature request:

When running `bazel query --output=streamed_proto`, Bazel converts the binary output stream to UTF-8 before upload / output, breaking it in the process.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here's an example query I ran:

`bazel query --output=streamed_proto //cpp:all --build_event_json_file=foo.json > foo.dat`

The binary output starts like this:
```
00000000  e3 0c 08 01 12 de 0c 0a  09 2f 2f 63 70 70 3a 63  |.........//cpp:c|
00000010  70 70 12 09 63 63 5f 62  69 6e 61 72 79 1a 35 2f  |pp..cc_binary.5/|
```

The JSON output starts like this:
```
{"id":{"progress":{"opaqueCount":6}},"progress":{"stdout":"�\f\b\u0001\u0012�\f\n\t//cpp:cpp\u0012\tcc_binary\u001a5
```

The first character of stdout looks like a question mark and is called `REPLACEMENT CHARACTER` (https://en.wikipedia.org/wiki/Specials_(Unicode_block)).

### What operating system are you running Bazel on?

Doesn't really matter.

### What's the output of `bazel info release`?

I ran this example with 4.2.1, but Bazel HEAD seems susceptible to the same problem.

###  Have you found anything relevant by searching the web?

I'm surprised this wasn't filed earlier. I'm pretty sure some people at Google are aware of this.

**Comment by ulfjack** [comment]
The problem that makes it hard to properly fix this is that the underlying proto files are declared as `string`, which means Utf-8 string:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto#L261

My best idea for a possible solution is to change Bazel to treat the binary input as ISO-8859-1 and convert them to UTF-8 for transmission. That allows the original binary data to be recovered by converting back to ISO-8859-1. It's unlikely that this will break anyone who isn't broken already and it provides a workaround for users that need the binary data from `bazel query`.

**Comment by ulfjack** [comment]
Alternatively, one could add a `bytes` field to the proto and either send both binary and (broken) utf-8 or have a flag that indicates which it is.

**Comment by benjaminp** [comment]
Perhaps for the particular usecase described in the OP, the `query` command should be able to upload its result to a CAS like normal local files referenced in BEP. A series of console "progress" events is a clunky way to store a (possibly) massive binary proto.

**Comment by meisterT** [comment]
cc @michaeledgar

**Comment by michaeledgar** [comment]
We don't want the Progress field in BEP to be used for transferring structured data. As @benjaminp suggested, we should instead upload the output file and report the URI.

There is presently a mechanism for this that is only implemented inside Google, but should be easily wired up to use the remote cache feature. A [BlazeModule may implement `#getQueryRuntimeHelperFactory()`](https://github.com/bazelbuild/bazel/blob/7c015cdaec2172231f0f765b3b13706a23a8a60f/src/main/java/com/google/devtools/build/lib/runtime/BlazeModule.java#L373-L381) to return a [`QueryRuntimeHelper.Factory`](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/runtime/QueryRuntimeHelper.java#L49-L51). We can extend `RemoteModule` to implement this method and return a new RemoteCacheQueryRuntimeHelperFactory which checks if a new flag, `--upload_query_results`, is set. If it is, a `RemoteCacheQueryRuntimeHelper` is returned - otherwise, a default [`StdoutQueryRuntimeHelper`](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/runtime/QueryRuntimeHelper.java#L53-L94) is returned.

I'll tag this as a remote execution feature.

**Comment by michaeledgar** [comment]
Present-day support for reporting query results via BEP is spotty and does not adequately support the full range of features offered by the query commands. Some known issues with the current support follow.

## Known Issues

### Large Streams

Today, query results are reported in BEP via `Progress` events, because query results are always written to standard output and **all** standard output is reported in `Progress` events. For queries with large result sets, this can produce very large BEP streams, putting strain on BEP consumers (such as BES implementations).

### Binary Output

As noted in issue #14208, reporting BEP via `Progress` limits the output formats available. `Progress` events expect UTF8 output, but queries with `--output=streamed_proto` will write arbitrary bytes to standard output.

### No Named File Output

BEP already has mechanisms for directing users to a file with arbitrary content produced on behalf of the build tool. Unfortunately, query results are always written to standard output. Users could redirect this output to a file, but this redirection is not reported in BEP and the query results will still appear in the `Progress` events.

## Approaches

There is presently a mechanism for this that is only implemented inside Google, but should be easily wired up to use the remote cache feature. A [BlazeModule may implement `#getQueryRuntimeHelperFactory()`](https://github.com/bazelbuild/bazel/blob/7c015cdaec2172231f0f765b3b13706a23a8a60f/src/main/java/com/google/devtools/build/lib/runtime/BlazeModule.java#L373-L381) to return a [`QueryRuntimeHelper.Factory`](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/runtime/QueryRuntimeHelper.java#L49-L51). We can extend `RemoteModule` to implement this method and return a new RemoteCacheQueryRuntimeHelperFactory which checks if a new flag, `--upload_query_results`, is set. If it is, a `RemoteCacheQueryRuntimeHelper` is returned - otherwise, a default [`StdoutQueryRuntimeHelper`](https://github.com/bazelbuild/bazel/blob/09c621e4cf5b968f4c6cdf905ab142d5961f9ddc/src/main/java/com/google/devtools/build/lib/runtime/QueryRuntimeHelper.java#L53-L94) is returned.

Note that writing the results to CAS will require some care - some users want to process query results as they are produced in a streaming fashion. Writing to CAS means the URI is only available after writing the file is complete. One simple approach is to write multiple files to the CAS based on size and timing.
