### ISSUE TITLE
about gradle to bazel 

### ISSUE THREAD

**Issue by tmxdyf** [bazelbuild/bazel#14305]
Do you know why I haven't used bazel for so long? Because our existing Android project is built by gradle, if it supports fast gradle to bazel, then I will consider using bazel. I hope bazel is easy to use.

**Comment by meisterT** [comment]
I am not sure what you are asking, can you clarify? If you are asking about automated migration from Gradle to Bazel, then you may want send an email to the bazel-discuss mailing list to learn what other people did.

This talk might also be interesting: https://www.youtube.com/watch?v=b8uR7_vReQ0 (but it is 2 years old)

**Comment by gregestren** [comment]
Feedback appreciated. I'm going to close this as a bug since it's a broad-reaching request. I agree that continuing a discussion at [bazel-discuss](https://groups.google.com/g/bazel-discuss) or [Slack](https://bazelbuild.slack.com/join/shared_invite/zt-dzm4qj0h-maSR3EcEr8SWE1f7dA55zw#/shared-invite/email) would be the right way forward.
