### ISSUE TITLE
Please enable `--experimental_enable_aspect_hints` by default

### ISSUE THREAD

**Issue by thii** [bazelbuild/bazel#14327]
### Description of the problem / feature request:

Please enable `--experimental_enable_aspect_hints` by default.

rules_swift started depending on the `aspect_hints` attribute since https://github.com/bazelbuild/rules_swift/commit/c42a37a025b51d48ee9efff0ec5f06ad29003b92, many changes have stacked up since then, which makes it difficult to not depend on it now. If this flag is disabled by default, all rules_swift users would have to explicitly enable it.

May I request to revert this change https://github.com/bazelbuild/bazel/commit/60ebb105dbf34f0b267ea7573157246b4c9bfcaf to enable it back? (I submitted a PR here https://github.com/bazelbuild/bazel/pull/14326).

If it has to be disabled for internal Blaze users, is there a way to configure the sync process to exclude this flag?

More context: https://github.com/bazelbuild/rules_swift/pull/691.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 5.0.0rc2

**Comment by thii** [comment]
cc @scentini

**Comment by scentini** [comment]
cc @comius 

We hid this feature behind an experimental flag because there were concerns around the effect that the `aspect_hints` attribute has on targets it is specified in:
```
cc_library(
    name = "lib",
    ...
    aspect_hints = [":my_hint"],
)

my_hint(
    name = "my_hint",
    deps = ["//foo/bar:some_large_dependency"],
)
```

Whenever `//foo/bar:some_large_dependency` (or some transitive dependency) changes, `lib` will need to be reanalyzed, although `cc_ilbrary` doesn't need to know nor care about `:my_hint`.

Due to this, the feature might need go through some changes and a decision was made to not provide it as a stable feature in Bazel 5.0. We're in a process of discussing potential changes, and I'll talk to the relevant Bazel folks to see if we can reach an agreement soon.

**Comment by brentleyjones** [comment]
Hi @scentini (and @comius). Was there any traction on the discussion about potential changes? rules_swift would still like to use this feature, and a resolution in time for 5.1 would be nice.

**Comment by keith** [comment]
@scentini any idea who we can poke around getting this moving forward?

**Comment by scentini** [comment]
I believe this is @comius's domain; One of sventiffe@ or lberki@ is probably the right person for escalation.

**Comment by keith** [comment]
@comius @sventiffe @lberki any update on this decision at google? We're considering forcing users to flip this experimental flag since the upstream version of rules_swift has diverged so significantly from the public version because of the requirement to use this new flag.

**Comment by comius** [comment]
The flag is experimental - meaning the contract is, that it may be removed at anytime.

The `aspect_hints` feature was put behind a flag, because we know there are issues with its design and we would like to keep our options open. Potentially this feature is going to be designed differently.

Keeping the flag to `false`, will help containing it.

Main issue with the design of `aspect_hints` is, that computation of reverse deps becomes a non-local property on aspects. 

Second problem is, that while the feature is useful in a mono-repo, it poorly supports Bazel with repositories (use case is when one repo needs to annotate another one).

Possible solution is to supply the hinting information next to an aspect. That info would have a form of a map from target to hint.

**Comment by keith** [comment]
Thanks for the context, is there any active work going towards improving those?

**Comment by keith** [comment]
@comius any movement on how production ready this is?

**Comment by Wyverald** [comment]
@comius gentle ping :)

**Comment by lberki** [comment]
We discussed in person with @comius and given that this is already turned on by default at Google and if it caused any problems, they would already have manifested there, I think it's fine to flip this flag.

For the record, I am a little worried because with the addition of `aspect_hints=`, there are going to be two attributes whose meaning is somewhat hazy (this and `data=`) and I have already seen instances of people abusing `data=`: it is supposed to mean "files needed when code described by this rule is being executed" but people routinely used it as "data attached to the rule that its definition does not have a place for". (but `aspect_hints=` is specifically designed to cover that second use case!)

For the record, the objections against `aspect_hints=` were:
* It's possible for a rule to pull in a large dependency graph through this attribute even though it's meant to attach small pieces of structured information to a rule that is then used by aspects (sort of like `tags=` but rich) and it's not clear how Bazel should enforce that this does not happen
* It's possible for intra-language dependencies to crop up (e.g. C++ rules acquiring a dependency on Swift), which means that suddenly your pure C++ project depends on `@rules_swift` and changes to `@rules_swift` surprisingly invalidate C++ code (but this is a problem at very large scales only, and this fear did not materialize at Google)
* There is the possibility of namespace collisions (not for hints that are dependencies on a singular tag, e.g. `:no_modules`, but for cases where the rich data is in a rule generated by a macro in the same package as the rule being annotated).
