### ISSUE TITLE
Use SIGKILL when timing out a test, if SIGTERM fails to terminate the test.

### ISSUE THREAD

**Issue by gunan** [bazelbuild/bazel#1437]
We have a test, where it looks like one of the libraries we are including captures the SIGTERM signal, and prevents the test from exiting.
The test is small sized, but it never exits when we run it with "bazel test"

It would be nice if bazel can try SIGTERM, wait 10(or 2sec, I dont know) seconds, and if the process have not exited send SIGKILL.

Would this be an easy feature to add?

**Comment by philwo** [comment]
This is definitely a useful feature and I wonder why we don't already do this (or maybe we try, but this is currently broken). I'll have a look next week!

**Comment by gunan** [comment]
Ping!
Any updates here?
I mistyped the signals above, bazel seems to send SIGINT, and some tests seem to ignore that.
I see a lot of SIGINT ignoring in python tests that swig a lot of c++ code.

**Comment by philwo** [comment]
Hi @gunan,

this should already work - the TestStandaloneStrategy sets a timeout, which is then passed to process-wrapper in StandaloneSpawnStrategy, or to linux-sandbox in LinuxSandboxRunner (depending on your system and flags, one of these will be used to actually run the test process).

The process-wrapper is called in a way that it kills the test with SIGTERM after the timeout, waits 5 seconds and then kills it with SIGKILL. The linux-sandbox is currently called in a way that it sends SIGTERM immediately followed by SIGKILL when the timeout expires.

Could you share a minimal example of a test that doesn't exit for you and your bazel command-line + output of when you test it?

That would help me a lot! Also, the new Linux sandbox (currently in code review) might fix this for you as well, because it uses PID namespaces to more reliably kill processes.

Philipp

**Comment by gunan** [comment]
We usually see this problem in our jenkins instance for tensorflow.
I will work to see if I can reproduce the problem locally and let you know.

**Comment by gunan** [comment]
We seem to just run into this again with bazel 0.3.1
http://ci.tensorflow.org/job/tensorflow-cl-cpu-python3/6116/consoleFull

//tensorflow/core:framework_rendezvous_test                             TIMEOUT in 3605.0s
//tensorflow/contrib/layers:optimizers_test                              FAILED in 5.0s

Is it possible the issue shows up when running bazel inside a docker container?

**Comment by philwo** [comment]
> //tensorflow/core:framework_rendezvous_test TIMEOUT in 3605.0s

I don't know what happened here. From just looking at this line, it seems like this worked as intended: The test had a timeout of 1 hour (= 3600 seconds), process-wrapper send it a SIGTERM signal at 3600s, the test didn't care, then it got terminated with a SIGKILL exactly 5 seconds later and Bazel logged it as a timeout. Except that the test has "size = small" in its BUILD file and none of the usual TestTimeouts map to 3600 seconds anyway.

I'll investigate.

**Comment by gunan** [comment]
Well, this is embarrassing, but it looks like we were using a different bazelrc file, which sets the timeout to 3600:
test --verbose_failures --test_timeout=3600 --test_output=errors --test_verbose_timeout_warnings

I think this is causing our problems.
I am really sorry for taking your time. Closing the issue, since I now know that it is on our end.
