### ISSUE TITLE
Combine "maven_jar" and "java_import". Allow maven to work outside of WORKSPACE.

### ISSUE THREAD

**Issue by michaelsafyan** [bazelbuild/bazel#1439]
Right now, one can import maven artifacts via `maven_jar`. However, it only works within the `WORKSPACE` file. This is problematic for organization, especially if many such jars are listed. For example, if I want these artifacts to be organized in a third-party directory structure, like:

```
   third_party/google/guava
   third_party/google/dagger2
   third_party/google/gae
   third_party/apache/log4j
   ...
```

... the restriction on listing these all in `WORKSPACE` becomes problematic. On top of that, it seems that `maven_jar` seems to serve much the same purpose as `java_import`, except that `java_import` looks for the JAR file locally. Consider merging these into a single rule (where one can specify either "jars" for local jar files or "maven_artifact" for downloading from maven).

**Comment by davidzchen** [comment]
FWIW, `java_import` looks for a JAR file that is within the workspace. A hypothetical `local_jar` rule that searches for JARs outside the workspace would still be a repository rule since it is non-hermetic and would, under the current convention, be restricted to the WORKSPACE file.

In order to combine `maven_jar` with `java_import`, we would need to decide whether we should allow non-hermetic repository rules to be intermixed with conventional build rules in BUILD files.

**Comment by michaelsafyan** [comment]
At the very least, allow non-hermetic rules under "third_party" (or some
whitelist of directories specified on the command line), please. Without
that, WORKSPACE files can become unacceptably large and disorganized.

**Comment by kchodorow** [comment]
You can use `load()` statements from WORKSPACE files, to keep them shorter and more readable.

**Comment by zhexuany** [comment]
@kchodorow Any updates about this particular issue?

**Comment by kchodorow** [comment]
What in particular are you looking for? You can currently use load statements and we are working on allowing recursive workspaces (#1943).
