### ISSUE TITLE
Name 'struct' is not defined

### ISSUE THREAD

**Issue by k6project** [bazelbuild/bazel#1450]
I have a custom rule that takes a single string parameter (a JSON string).
The rule is defined as follows:

my_rule = rule (
...
attrs = { "json_string": attr.string() }
...
)

In the BUILD file  I try to invoke:

my_rule( name="...", json_string = struct(...<struct definition here>...).to_json )

When I run bazel build, i get the following:

name 'struct' is not defined

Can this be a bug, or am i doing something wrong?

**Comment by davidzchen** [comment]
AFAIU, Skylark functions, such as `struct()`, are only available in .bzl files and not BUILD files (@laurentlb, correct me if I'm wrong). What kind of JSON string are you trying to pass to your rule? Would it be sufficient to use the `string_dict` type for this attribute? If not, what is the motivation for passing the JSON string from inside the BUILD file rather than keeping the JSON in a file and passing it to the rule via a `label` attribute, such as `data`?

**Comment by k6project** [comment]
Well, some of our initial requirements included passing a certain small set of JSON data to build rule as a string, but i guess we can accomplish that in some other way. Anyways, thanks for the clarification.
