### ISSUE TITLE
error: Argument list too long

### ISSUE THREAD

**Issue by michaelreneer** [bazelbuild/bazel#14530]
### Description of the problem / feature request:

I am getting an error when trying to build https://github.com/tensorflow/federated on MacOS while depending on TensorFlow Bazel targets.

```
ERROR: /Volumes/BuildData/tmpfs/tmp/bazel/external/org_tensorflow/tensorflow/python/BUILD:3216:24: Linking external/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so failed: (Aborted): cc_wrapper.sh failed: error executing command 
  (cd /Volumes/BuildData/tmpfs/tmp/bazel/execroot/org_tensorflow_federated && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    PATH='/Volumes/BuildData/tmpfs/src/github/federated/venv/bin:/Users/kbuilder/.rvm/gems/ruby-2.6.3/bin:/Users/kbuilder/.rvm/gems/ruby-2.6.3@global/bin:/Users/kbuilder/.rvm/rubies/ruby-2.6.3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/CMake.app/Contents/bin:/Applications/Unity/Unity.app/MacOS:/Users/kbuilder/Library/Android/sdk/platform-tools:/Users/kbuilder/Library/Android/sdk/tools/bin:/Users/kbuilder/.rvm/bin' \
    XCODE_VERSION_OVERRIDE=11.3.0.11C29 \
  external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt-exec-50AE0418/bin/external/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so-2.params)
Execution platform: @local_execution_config_platform//:platform
clang: error: unable to execute command: posix_spawn failed: Argument list too long
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

There is not really an easy way to reproduce this issue. Sync my CL and then on a MacOS machine using remote caching.

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

I have version 4.2.2

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA

###  Have you found anything relevant by searching the web?

It might be caused by https://cs.opensource.google/bazel/bazel/+/master:tools/osx/crosstool/wrapped_clang.cc;bpv=0 which looks like how we run clang from Bazel

**Comment by michaelreneer** [comment]
@meteorcloudy

**Comment by michaelreneer** [comment]
@keith

**Comment by cramertj** [comment]
cc @jkr26

**Comment by meteorcloudy** [comment]
Also /cc our C++ rules team: @c-mita @oquenchil

**Comment by keith** [comment]
What version of macOS are you using? ARGMAX in macOS big sur was doubled from previous versions (IIRC), and this issue popped up before that. Also there were potentially some fixes between bazel 4.x and 5.x (I've lost track), can you test the 5.0.0rc3 (I'm not sure if TF is compatible with it or not).

Can you expand the response file mentioned there `bazel-out/darwin-opt-exec-50AE0418/bin/external/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so-2.params` and see why there are so many arguments? I'm unable to get anywhere building this on my M1 machine so I cannot test to repro on the newer macOS version

**Comment by cramertj** [comment]
(I work with @michaelreneer) We're currently testing on mojave, but can update. Here's a gist with the details of that file: https://gist.github.com/cramertj/fa7b411e2f7f2a03147c49529a325972

**Comment by keith** [comment]
Yea so the underlying issue is that ld64 didn't support full response files without crashing until very recently, so clang executes it with a `-filelist` argument with all the files, but it has to directly pass all the `-force_load` flags, which it looks like you have ~2k of with very long paths. Any solution I can come up with would require _some_ tool version bump. As of Xcode 13.x (IIRC) ld64 supports response files correctly, so I updated clang to reflect that, but that would likely require a very recent clang. Alternatively you could use lld for macOS which is still early but we believe is stable, that has accepted response files forever, so if you have a recent enough llvm version that it works (which I assume you can because you're using the bazel integration), using it should resolve this as well.

Let me know what you can do here, but I don't think we have a fix for this in bazel unfortunately.

**Comment by michaelreneer** [comment]
@keith Thanks for getting back! However, I am confused as to how TF is building without using Big Sur? I'll update this thread with the status of my investigation.

Some information about our current environment:

```
+ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G3020
+ xcodebuild -version
Xcode 11.3
Build version 11C29
```

I've been trying to build on Big Sur as you suggested, here is some information about the environment I am testing on.

```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
$ xcodebuild -version
Xcode 12.5.1
Build version 12E507
```

Is this version of Xcode new enough or will I need Xcode 13?

Thanks

**Comment by keith** [comment]
> I am confused as to how TF is building without using Big Sur

I'm mot sure what TF's supported OS versions are.

> ProductVersion:	10.14.6

Yep I think this would do it.

> Is this version of Xcode new enough or will I need Xcode 13?

I think this should be enough because the ARGMAX bump is a system wide change, not related to specific tools versions.

But best to try it and see if it works now!

**Comment by timsutton** [comment]
Going from 10.15 (Catalina) to 11 (Big Sur), ARGMAX quadrupled from 262,144 to 1,048,576.

**Comment by michaelreneer** [comment]
I've tested this build on Big Sur and I am no longer seeing the issue, thanks.

**Comment by llv22** [comment]
@timsutton I forked https://github.com/llv22/bazel-macOS-10.13.6/releases/tag/5.2.1 and create incremental link for legacy macOS 10.13.6. Basically it merges object files, .o, .a, .lo to intermediate object files, so that the ultimate output file will only rely on the reduced object files to avoid arguments overflow, esp. for tensorflow building system.  core code in https://github.com/llv22/bazel-macOS-10.13.6/blob/baad0cae14ec6679ee6c77bb4c06d8b8f709c8f6/src/main/java/com/google/devtools/build/lib/rules/cpp/CppLinkAction.java and test code in https://github.com/llv22/bazel-macOS-10.13.6/blob/baad0cae14ec6679ee6c77bb4c06d8b8f709c8f6/src/test/java/com/google/devtools/build/lib/rules/cpp/CppLinkActionTest.java. The built bazel is uploaded here https://github.com/llv22/bazel-macOS-10.13.6/releases/tag/5.2.1. I used the cracked bazel to link _pywrap_tensorflow_internal.so. By the way, I also disabled param files on xcode 10.1, as such feature doesn't support by libtool.
