### ISSUE TITLE
Aliases of macros do not show up in call stack

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#14628]
### Description of the problem / feature request:

When a macro is aliased in a bzl file, the bzl file does not show in the call stack when running `bazel query`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create a Bazel workspace with this file:

```python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "2b1641428dff9018f9e85c0384f03ec6c10660d935b750e3fa1492a281a53b0f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.29.0/rules_go-v0.29.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.29.0/rules_go-v0.29.0.zip",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.17.1")
```

2. Run `bazel query --output=build //external:platforms`. It will print out something like:

```
# /private/tmp/bazel_alias/WORKSPACE:14:22
http_archive(
  name = "platforms",
  generator_name = "platforms",
  generator_function = "go_rules_dependencies",
  urls = ["https://mirror.bazel.build/github.com/bazelbuild/platforms/releases/download/0.0.4/platforms-0.0.4.tar.gz", "https://github.com/bazelbuild/platforms/releases/download/0.0.4/platforms-0.0.4.tar.gz"],
  sha256 = "079945598e4b6cc075846f7fd6a9d0857c33a7afc0de868c2ccb96405225135d",
  strip_prefix = "",
)
# Rule platforms instantiated at (most recent call last):
#   /private/tmp/bazel_alias/WORKSPACE:14:22                                                                                     in <toplevel>
#   /private/var/tmp/_bazel_zplin/a89e6e7d339371fe17f2f57e732bf186/external/io_bazel_rules_go/go/private/repositories.bzl:45:11  in go_rules_dependencies
#   /private/var/tmp/_bazel_zplin/a89e6e7d339371fe17f2f57e732bf186/external/io_bazel_rules_go/go/private/repositories.bzl:296:18 in _maybe
# Rule http_archive defined at (most recent call last):
#   /private/var/tmp/_bazel_zplin/a89e6e7d339371fe17f2f57e732bf186/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31 in <toplevel>
```

Although `@io_bazel_rules_go//go:deps.bzl` is the one `WORKSPACE` calls to load `//external:platforms`, `deps.bzl` does not show up in the call stack.

### What operating system are you running Bazel on?

macOS Monterey

### What's the output of `bazel info release`?

release 5.0.0-homebrew

**Comment by brandjon** [comment]
This is working as intended. I didn't follow the specific stack trace in your example, but just in terms of how aliases and functions work:

When you declare a function with `def foo(): ...`, the name of the resulting function object bound to variable `foo` is "foo". When you then write `bar = foo` to create an alias, you have bound another variable `bar` to the same function named "foo". You have not mutated the function in any way.

There is also no "export" mechanism (hack) for functions the way there is for providers, rules, and aspects. Bazel does not introspect the name of a variable to decide how to name the function object; that comes from the interpreter itself by virtue of evaluating the `def` statement.

With that in mind, it isn't really feasible to include aliases in stack traces of any kind. Short of doing something hacky like annotating the call frame based on the syntax of the call rather than just the nature of the function object being called.
