### ISSUE TITLE
It should be possible to use the same extension as both a production and dev dependency

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#14635]
### Description of the problem / feature request:

It's often useful to use the same extension as both a production and development time dependency. eg.

```starlark
# In MODULE.bazel
http = use_extension(":extensions.bzl", "http")
dev_http = use_extension(":extensions.bzl", "http", dev_dependency = True)

http.archive(
   name = "prod_dep"
   sha256 = "..."
   urls = [ ... ],
)

dev_http.archive(
  name = "dev_dep",
   sha256 = "..."
   urls = [ ... ],
)
```

When one tries this, the following error is shown:

```shell
ERROR: Traceback (most recent call last):
	File "<root>/MODULE.bazel", line 19, column 26, in <toplevel>
Error in use_extension: this extension is already being used at <root>/MODULE.bazel:10:22
```

As an aside, this message not include the name of the extension which makes debugging harder.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See above

### What's the output of `bazel info release`?

release 5.0.0

**Comment by shs96c** [comment]
I would hope that if a dev and production rule tried to create the same named workspace an error would be thrown. I think that's probably inevitable given my mental model of how this works, but best to check

**Comment by Wyverald** [comment]
Current thinking is to make the `dev_http = use_extension(...)` line legal, with the semantics that all `dev_http.X` tags will only take effect if the current module is the root module. This should be fairly easy to do.

My original thinking was that we could introduce some sort of scoping construct within MODULE.bazel files, to make several statements "dev" (read: effective only in the root module), instead of having `dev_dependency=True` on each individual statement. "Statement" here would include everything -- `bazel_dep`, overrides, tags, etc. The tricky part is that there's no easy Starlark syntax for this. So in lieu, the idea above would serve as a rough equivalent of grouping several tags as "dev", which suffices for our use cases for now.
