### ISSUE TITLE
`implementation_deps` are not linked by `cc_shared_library` or `cc_binary` with `dynamic_deps`

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#14731]
### Description of the problem:

Both `cc_shared_library` and `cc_binary` with `dynamic_deps` do not link in transitive dependencies that they are only connected to through `implementation_deps`.

The root cause is that both the Starlark and the Java version of the graph aspect only consider attributes named `deps`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See the integration test in #14730.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

development version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

From 5c4422e9efc4616d35526f1500864c879f6b506e via `bazel build //src:bazel-dev`.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel
5c4422e9efc4616d35526f1500864c879f6b506e
5c4422e9efc4616d35526f1500864c879f6b506e

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

I have prepared a fix at https://github.com/bazelbuild/bazel/pull/14730.

**Comment by fmeum** [comment]
Closing as `implementation_deps` are no more. I will check whether `interface_deps` suffer from the same problem.

**Comment by oquenchil** [comment]
Hold on Fabian. I got feedback a few months ago that interface_deps is an incompatible change across repos which is uncalled for given the little benefit it provides (it was about consistency with the exports attribute in other rules). I thought I could solve this via WORKSPACE magic and I tried last week but I can't. Taking that into account I will probably rollback the change that converted implementation_deps to interface_deps.

Also I suspect that the same problem applies to interface_deps since it's probably related to the aspect not being propagated to those attributes. The fix shouldn't be too complicated but I will do it once I have reverted the previous change.
