### ISSUE TITLE
error adding Bazel distribution URI as a package source

### ISSUE THREAD

**Issue by yolanda93** [bazelbuild/bazel#1484]
curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
gpg: no valid OpenPGP data found.

**Comment by aehlig** [comment]
As the error message "curl: (77) error setting certificate [...]" indicates, the problem is in your set up of curl. Please check your curl configuration, in particular the part specifying the trusted CAs. Also note, that you do not have to use curl; you can use any browser you trust to download the public key from the mentioned URL.
