### ISSUE TITLE
Allow for using custom providers in the BUILD files

### ISSUE THREAD

**Issue by konste** [bazelbuild/bazel#14920]
### Description of the problem / feature request:

Example: assume we have rule1 which among other things returns custom provider `targets_list` which carries the list of targets rule1 calculates. Imagine rule2 which depend on rule1 and supposed to act on the targets list supplied by rule1. 
Here is what we want:
```
rule2(
    name = "rule2",
    deps = ["rule1[targets_list]"],
)
```

### Feature requests: what underlying problem are you trying to solve with this feature?

Custom providers created with provider() function are used to convey different subsets of the data between the rules. Receiving rule can query for the providers it knows about, and fetch the data from those. But in some cases we need to extract the provider before rule implementation function has a chance to run. For example in rule definition we have:
```
"deps": attr.label_list(aspects = [custom_aspect])
```
When the list of deps is supplied in the BUILD file `custom_aspect` gets applied to them.
But when the list of targets is supplied through the custom provider there is no way to tell aspect to run on those.
And there is no way to pass targets (as opposite to files) between the rules other than with the custom provider.

### What operating system are you running Bazel on?

Linux, MacOS, Windows

### What's the output of `bazel info release`?

5.0.0

**Comment by brandjon** [comment]
If I understand, the request here is to allow a target to specify its own dependencies based on the targets/labels returned by a provider of another target.

This is generally impossible in Bazel because of the distinction between the Loading and Analysis phases. By the end of the loading phase we've already determined the labels that a target depends on. But providers are not evaluated and returned until the analysis phase. (Technically, Loading and Analysis are interleaved across the build, but the kind of backflow of information this FR requires would be a dangerous precedent and probably lead to cycles in some cases.)

That said, there are some ways to delay the determination of dependencies into the Analysis phase. But I don't think any of them provide the expressive power you're looking for.

* `select()` requires you to enumerate a superset of the possible dependencies, so it can't create arbitrary dep edges based on what happens at analysis.
* toolchain resolution can allow a target to depend on an arbitrary toolchain, but it's determined by platform/toolchain constraint information supplied in BUILD files.
* Starlark-defined flags (`build_setting`) can express labels via `label_flag` / `label_setting`, but it looks like those aren't extensible at analysis time and can only be influenced by Starlark-defined transitions, not rule implementations.

Perhaps you can shoehorn your use case into one of these more restricted forms.

**Comment by brandjon** [comment]
Closing since the request as stated is infeasible. Feel free to reopen if I misunderstood.

**Comment by konste** [comment]
Let me ask related question: is it feasible to implement the capability for the rule to apply aspect not directly to some attribute of type "label_list", but to the list of targets coming from a provider of one of the dependencies?
