### ISSUE TITLE
New Bazel Docs: Broken Link to "Building with Platforms"

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/bazel#14979]
Hey, wonderful Bazel folks,

I was browsing the platform docs, and noticed that the link to the new docs was broken for https://docs.bazel.build/versions/main/platforms-intro.html. 

The broken link is https://bazel.build/concepts/platform-intro

Filed a quick PR (#14978) for the other small issue I saw on that page; but figured I should give a friendly heads on this one because I don't know exactly how the new docs system works.

Thanks so much for all you do!
Chris
(ex-Googler)

**Comment by gregestren** [comment]
Oh that's funny. I independently discovered that while triaging https://github.com/bazelbuild/bazel/issues/14982 and now come to this bug.

The problem is it should be plural platform**s**-intro: https://bazel.build/concepts/platforms-intro. I haven't been able to figure out where that link gets set but @fweikert will know.

**Comment by fweikert** [comment]
Hey Chris,

Thank you for the report! I just fixed it.

**Comment by cpsauer** [comment]
You're very welcome. Thank you!
