### ISSUE TITLE
Invoking bazel for the same tests twice with the same Invocation Id causes an error return code

### ISSUE THREAD

**Issue by Gormo** [bazelbuild/bazel#15036]
### Description of the problem / feature request:

Invoking bazel for the same tests twice with the same Invocation Id causes tests
to be marked as skipped with NO_STATUS instead of passed and gives an error return-code.

We are aware that this is quite an odd use-case but we have a case where we first execute tests
and after that invoke the tests again but with --show-result to extract the build output files.

### Feature requests: what underlying problem are you trying to solve with this feature?

N/A

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
echo "Run with setting different invocation Ids:"
$BAZEL_BIN test //:all --invocation_id="$(/usr/bin/uuidgen)"
$BAZEL_BIN test //:all --invocation_id="$(/usr/bin/uuidgen)"
echo "Return code: $?"

echo "Run using the same invocation Id"
invocation_id=$(/usr/bin/uuidgen)
$BAZEL_BIN test //:all --invocation_id="${invocation_id}"
$BAZEL_BIN test //:all --invocation_id="${invocation_id}"
echo "Return code: $?"
```

### What operating system are you running Bazel on?

Linux - Ubuntu 18.04

### What's the output of `bazel info release`?

release 5.0.0

Bug also verified on latest 6.0.0 pre-release

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Example Output:

> Run with setting different invocation Ids:
> INFO: Analyzed target //:test (0 packages loaded, 0 targets configured).
> INFO: Found 1 test target...
> Target //:test up-to-date:
>   bazel-bin/test
> INFO: Elapsed time: 0.223s, Critical Path: 0.00s
> INFO: 1 process: 1 internal.
> INFO: Build completed successfully, 1 total action
> //:test                                                         (cached) PASSED in 0.1s
> 
> Executed 0 out of 1 test: 1 test passes.
> INFO: Build completed successfully, 1 total action
> INFO: Analyzed target //:test (0 packages loaded, 0 targets configured).
> INFO: Found 1 test target...
> Target //:test up-to-date:
>   bazel-bin/test
> INFO: Elapsed time: 0.189s, Critical Path: 0.00s
> INFO: 1 process: 1 internal.
> INFO: Build completed successfully, 1 total action
> //:test                                                         **(cached) PASSED in 0.1s**
> 
> Executed 0 out of 1 test: 1 test passes.
> INFO: Build completed successfully, 1 total action
> **Return code: 0**
> Run using the same invocation Id
> INFO: Analyzed target //:test (0 packages loaded, 0 targets configured).
> INFO: Found 1 test target...
> Target //:test up-to-date:
>   bazel-bin/test
> INFO: Elapsed time: 0.152s, Critical Path: 0.00s
> INFO: 1 process: 1 internal.
> INFO: Build completed successfully, 1 total action
> //:test                                                         (cached) PASSED in 0.1s
> 
> Executed 0 out of 1 test: 1 test passes.
> INFO: Build completed successfully, 1 total action
> INFO: Analyzed target //:test (0 packages loaded, 0 targets configured).
> INFO: Found 1 test target...
> Target //:test up-to-date:
>   bazel-bin/test
> INFO: Elapsed time: 0.156s, Critical Path: 0.00s
> INFO: 0 processes.
> INFO: Build completed successfully, 0 total actions
> //:test                                                               **NO STATUS**
> 
> INFO: Build completed successfully, 0 total actions
> **Return code: 3**

**Comment by stagnation** [comment]
It is a little bit involved. We want to set the same invocation-id for all bazel invocations for a given commit in the CI pipeline. So staggered bazel invocations get the same priority in Buildbarn, @Gormo can explain this in further details.

The problem comes from our coverage handling. Where we have an old post-build script that we adapted from our old build systems. And we use --show_result to print what targets and files were built to feed the post-hoc script with which inputs to read (we convert from bazel-bin to bazel-out as this script is then executed through bazel-run).

So to build and capture the results it seemed best to do a two-step build. One without show_result, so any build errors would be printed to the console log without all the result information, it is unwieldy to say the least. Then a second time with show_result and a file redirection that can be parsed later.

The overall structure looks something like this:

`
set -eu
console_log="$(mktemp --suffix coverage_log)"
trap EXIT '{ test $? = 0 || cat "$console_log"; rm -f "$console_log"}'

options=(--instrumentation_filter=..., --config=remoteexecution_download_all)
bazel coverage "$options[@]" @repo//...
bazel coverage "$options[@]" --show_result=MAX_INT @repo//... > "$console_log" 2>&1

bazel run @repo//:post-hoc-report --console-log="$console_log"
`

So if the coverage invocations fails the first invocation would show all errors as one may expect. Otherwise the first would do all the work, and the latter just pick it up from cache and write the result into a console log. This is essentially a poor man's build event protocol. Then recently we wanted to reuse invocation IDs to optimize throughput in our CI systems and Buildbarn.
Adding it to the options array gave us the bug above. The workaround we use now is to generate a dummy invocation_id for the secondary build

`
bazel coverage "$options[@]" --invocation_id="$SHARE_BUILDBARN_PRIORITY" @repo//...
bazel coverage "$options[@]" --invocation_id="$(uuidgen)" --show_result=MAX_INT @repo//... > "$console_log" 2>&1
`

This looks funny, the latter invocation_id is redundant. That is because the first one is not what we do, we put it into our bazel shell wrapper with some args manipulation. So we always set the invocation_id if some external environment variables are available, and to unset the same invocation_id we just use the flag again later in the command line and rely on that taking precedence.

This is more accurate of our test.
`
# invocation_id is set inside the bazel shell wrapper
bazel coverage "$options[@]" @repo//...
# invocation_id is set inside the bazel shell wrapper (incorrect) but reset later on the commandline
bazel coverage "$options[@]" --invocation_id="$(uuidgen)" --show_result=MAX_INT @repo//... > "$console_log" 2>&1
`

Other solutions to our post-hoc reporting script:

1. The same information is present in the build event protocol, and it would be better to use that instead. But if I recall correctly our coverage builds tended to crash on developer machine when writing out the .bep file. That is an issue we should look into further and report

2. When we wrote the show_result parsing code we noticed that the data is written to standard error, and not standard out. So we could not pipe it directly, if it was written to standard out instead we could live without the secondary invocation.

3. As I type this out, it strikes me that we did not experiment with listing all the files in bazel-bin, that is also a way to find all the files that were part of the previous build. Just that this cannot be done through bazel-run.

**Comment by janakdr** [comment]
It seems like there's a lot going on here. I'm still unclear why you need multiple invocations to have the same invocation id. You could set `--bes_keywords`, or `--tool_tag`, or possibly other flags if you want to "tag" some invocations as grouped. Does BuildBarn actually want you to give multiple invocations the same id? It also seems like maybe you need some outer invocation to set the id, but then you don't care if the actual Bazel invocation has that id, so overriding it works fine? (You could just unset the environment variable rather than passing --invocation_id explicitly, but either is ok.)

Second, as you say, BEP seems like the right solution here, not this workaround. We're much more likely to take a BEP crash report and fix it than address this invocation id behavior.

Third, I'm not sure what environment all this is running in, but you can pipe stderr using `2>&1 >/stdoutfile | ` or just `&|` if you are ok with stderr and stdout being intermingled. But again, this is probably not the right way to solve your problem. (And maybe I misunderstood "we could not pipe it directly".)

**Comment by janakdr** [comment]
You could also use the --build_request_id field if you wanted to group certain invocations together: that's what Google does internally for retrying invocations, and other use cases that sound somewhat similar to yours.

**Comment by Gormo** [comment]
Hi,
The reason for setting the invocation Id is that buildbarn uses the toolInvocationId for scheduling all actions related to the same invocation in the order the invocations are created.

In our case we have an external CI-System that triggers multiple jobs that in turn invokes Bazel multiple times on different hosts (and even multiple platforms).

So by setting the toolInvocationId to the same for all invocations triggered by the same change we will have all related actions to a specific change to be prioritized together in buildbarn..

But sounds like this contradicts the idea behind invocationIds in Bazel?

I guess we could look into --build_request_id and if we could extend buildbarn to use that instead.

**Comment by janakdr** [comment]
Yes, the build request id is definitely what build barn should be using
here, at least to correspond to Google's internal usage.

**Comment by stagnation** [comment]
Thank you for the feedback! Build request id sounds exactly like what we want. And I understand perfectly that we should migrate to the build event protocol. You raise a good point about piping. The main point was the build errors should be printed to the console, but that can be done by tee in the pipeline, and printing the console log in our EXIT trap. Something we introduced as part of troubleshooting the invocation-id errors anyway.

```
bazel coverage "${options[@]}" --show_result=MAX_INT @repo//...  2>&1 | tee "$console_log" | bazel run ...
```

**Comment by janakdr** [comment]
Ok, it sounds like this isn't a bug that needs fixing then? I will close as WAI.
