### ISSUE TITLE
--host_cxxopt and --cxxopt are passed to the compiler also for .c files on Windows

### ISSUE THREAD

**Issue by foxandi** [bazelbuild/bazel#15073]
### Description of the problem / feature request:

Since Bazel 5.0.0 `--host_cxxopt` and `--cxxopt` are passed to compilers compiling .c files on Windows.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Use the autoconfigure toolchain to build (with -s) a .c file in Windows. Set `--host_cxxopt`  and `--cxxopt` in the .bazelrc and see in the compiler call the passed opts from the .bazelrc. Doing the same on Linux show, that the opts here are not passed.

### What operating system are you running Bazel on?

Windows 10 Enterprise (Version 10.0.19042 Build 19042)

### What's the output of `bazel info release`?

release 5.0.0

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/pull/14005
https://github.com/bazelbuild/bazel/pull/14131

### Any other information, logs, or outputs that you want to share?

This commit https://github.com/bazelbuild/bazel/commit/861584ca049b1b2f3474c3977c4a54d1901f9458 introduced case insensity for files types on Windows 

https://github.com/bazelbuild/bazel/blob/88499f615bc03d1b6a3e4e38f2890a4e987a954d/src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java#L28

The change also leads to .c files under Windows match to C_SOURCE (.c extension) and CPP_SOURCE (.C extension)

https://github.com/bazelbuild/bazel/blob/88499f615bc03d1b6a3e4e38f2890a4e987a954d/src/main/java/com/google/devtools/build/lib/rules/cpp/CppFileTypes.java#L33-L34

Which results in passing cxxopt for .c files

https://github.com/bazelbuild/bazel/blob/88499f615bc03d1b6a3e4e38f2890a4e987a954d/src/main/java/com/google/devtools/build/lib/rules/cpp/CcCompilationHelper.java#L1605-L1610

**Comment by meteorcloudy** [comment]
Maybe this is a similar bug that should be fixed like https://github.com/bazelbuild/bazel/commit/edfe2a17e3434cce660757f59b14f2e9d6ab944e?

**Comment by kkpattern** [comment]
We also encounter this problem. Unfortunately this causes us to not be able to compile Android on windows. Which is a major block for our project. Is there a rough estimate of when this will be fixed? Or is there any way we can workaround this? Thanks.

**Comment by oakad** [comment]
The worst thing here is that this issue is not even particularly complicated, even with `WindowsOsPathPolicy` rework included (the right thing to do: support for case sensitive directories on Windows 10+ will solve a lot of problems). Yet, it breaks a whole lot of plain C libraries on Windows putting a big question mark on Bazel's viability in general.

Which is a pity.

**Comment by kkpattern** [comment]
> The worst thing here is that this issue is not even particularly complicated, even with `WindowsOsPathPolicy` rework included (the right thing to do: support for case sensitive directories on Windows 10+ will solve a lot of problems). Yet, it breaks a whole lot of plain C libraries on Windows putting a big question mark on Bazel's viability in general.
> 
> Which is a pity.

Currently, you can workaround this by replacing `--cxxopt` with `--per_file_copt=.*\.cpp\$@`.

But I agree that it's very confusing why this issue is a feature request and is P4.

**Comment by oakad** [comment]
It won't work for flags which are set in the actual BUILD files. The primary issue here, is that bazel offers no way to say "this file is plain C" explicitly. So, in a project with several dozens of third party dependencies a lot of patching and testing is needed to get anywhere with Bazel v5.

Bazel v4 sort of works, but then it can not be used with VS2022 due to another open issue.

**Comment by oakad** [comment]
VS2022 is broken pretty badly, we had to go back to VS2019/bazel v4 for now. We may figure something out going forward; possibly by making all sources C++ compatible (this appears to be the best option on the cost/benefit scale).

Still, not nice.

**Comment by meteorcloudy** [comment]
@oquenchil This issue seems to have wide user impact on Windows. Is it caused by starlarkfifying the cc rules? Do you know which exact change caused this and how hard is it to fix this?

**Comment by kkpattern** [comment]
@meteorcloudy Looks like is caused by #14005. The `.c` extension is matched with `.C` cause bazel treat it as a C++ source. I think this can be fixed like https://github.com/bazelbuild/bazel/commit/edfe2a17e3434cce660757f59b14f2e9d6ab944e . I understand bazel team has many things to do and may not have the capacity to fix this. If you have the bandwidth to review a PR I can give this a try.

**Comment by meteorcloudy** [comment]
Not sure why `.c` and `.C` should mean different file types on Windows because file names are already case insensitive. Is this a Linux convention? Can you just change files with `.C` to `.cpp`?  
But given we are already making an exception in https://github.com/bazelbuild/bazel/commit/edfe2a17e3434cce660757f59b14f2e9d6ab944e, a PR to fix this sounds plausible, @oquenchil @comius should decide eventually.

**Comment by kkpattern** [comment]
> Can you just change files with `.C` to `.cpp`?

We don't actually have any `.C` files. I think it's bazel that treated all `.c` files as `.C` files causing the problem.

**Comment by oakad** [comment]
@meteorcloudy Also see #15550 for some further info.

**Comment by oakad** [comment]
Bazel can compile things on Windows, it just requires jumping through ugly loops with `--per_file_copt=` and possibly some patching.

But yes, this issue is bad and the lack of proper support for case sensitive abilities of NTFS is also unfortunate - that is, bazel would have worked fine on Windows with some extra configs if not for the rather stupid case forcing inside the Windows path resolver.

**Comment by kalimaul** [comment]
This bug is still causing significant problems in a project, forcing us to use an old bazel version which causes further compatibility issues and surfaces other bugs without fixes. Will it ever be looked at?

**Comment by meteorcloudy** [comment]
@oquenchil I think this shouldn't be a P4 issue, can you take a look?

If anyone has a fix for this, a PR is also very welcome!

**Comment by FaBrand** [comment]
Created the referenced Cherrypick @kkpattern Any objections agains the attempt?

**Comment by kkpattern** [comment]
> Created the referenced Cherrypick @kkpattern Any objections agains the attempt?

Not at all😃.

**Comment by kkpattern** [comment]
I did a simple test. When compile with MSVC with ` --cxxopt=/std:c++17`, bazel 5.1.1 added the flag to a C source file:

```
C:\...\cl.exe ... -D__TIME__="redacted" /std:c++17 ... /c hello.c
                                         ^^^^^^^^^
```

while bazel 6.3.2 didn't:

```
C:\...\cl.exe ... -D__TIME__="redacted" ... /c hello.c
```

**Comment by aaron-michaux** [comment]
I'm using Ubuntu 22.04... so I'm seeing the problem on Linux.
