### ISSUE TITLE
External repository referring unexported files

### ISSUE THREAD

**Issue by linzhp** [bazelbuild/bazel#15185]
### Description of the problem / feature request:

When an external repository refers to an unexported files, builds can still succeed, only queries with `deps` would fail. This is inconsistent.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* Create a workspace like this:
```
-- WORKSPACE --
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_google_protobuf",
    sha256 = "d0f5f605d0d656007ce6c8b5a82df3037e1d8fe8b121ed42e536f569dec16113",
    strip_prefix = "protobuf-3.14.0",
    urls = [
        "https://mirror.bazel.build/github.com/protocolbuffers/protobuf/archive/v3.14.0.tar.gz",
        "https://github.com/protocolbuffers/protobuf/archive/v3.14.0.tar.gz",
    ],
)

load("@com_google_protobuf//:protobuf_deps.bzl", "protobuf_deps")

protobuf_deps()
-- BUILD.bazel --
```
* Run `bazel build @zlib//:all`, it would succeed
* Run `bazel query 'deps(//external:zlib)'`, it would fail with:
```
ERROR: /private/tmp/protobuf/WORKSPACE:15:14: no such target '@com_google_protobuf//:third_party/zlib.BUILD': Label '@com_google_protobuf//:third_party/zlib.BUILD' crosses boundary of subpackage '@com_google_protobuf//third_party' and referenced by '//external:zlib'
ERROR: /private/tmp/protobuf/WORKSPACE:15:14: no such target '@com_google_protobuf//:third_party/zlib.BUILD': target 'third_party/zlib.BUILD' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["third_party/zlib.BUILD"])' to /BUILD?) defined by /private/var/tmp/_bazel_zplin/67edb565efa10fe0537e4ddaba8aef74/external/com_google_protobuf/BUILD and referenced by '//external:zlib'
ERROR: Evaluation of query "deps(//external:zlib)" failed: errors were encountered while computing transitive closure
```

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 5.1.0

### Any other information, logs, or outputs that you want to share?
This bug has existed for a long time. #8175 is a symptom of it. #15134 fixed the symptom, but it doesn't prevent it from coming back.

**Comment by meteorcloudy** [comment]
I think the reason is that protobuf should use `@com_google_protobuf//third_party:zlib.BUILD` at [here](https://github.com/protocolbuffers/protobuf/blob/7f9901c5f640fe0fbcd5dbdd303a269908fb3b62/protobuf_deps.bzl#L33)

But somehow we didn't check if the label is valid when using in the WORKSPACE file.

**Comment by meteorcloudy** [comment]
I think the underlying problem is that when a label is used in the WORKSPACE file to reference a file, we are actually not loading the target (that's when we [check](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/TransitiveBaseTraversalFunction.java;l=307) if the label is crossing boundary). But we do try to load targets from the label when running `bazel query`.

**Comment by linzhp** [comment]
@bazelbuild/triage Can you keep this open?

**Comment by Wyverald** [comment]
`bazel query deps(//external:foo)` was never going to work as targets under `//external` are pseudo-targets and don't actually behave like other, actual build targets. Regardless, we won't be fixing this as the entire `//external` package will be going away with WORKSAPCE deprecation.
