### ISSUE TITLE
Periods missing in skylark API docs

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#1522]
see http://www.bazel.io/docs/skylark/lib/JavaSkylarkApiProvider.html#transitive_deps

"Returns information about annotation processing for this Java target May return None."

"May return None" is added automatically, but the '.' is missing.

**Comment by katre** [comment]
The problem is actually more general. We are very inconsistent in the doc strings about ending with a period or no punctuation. I am writing a change to add the final period if one is not present. I've just scanned the usages of @SkylarkConfiguration(doc="non-empty string"), and I didn't find any cases that weren't either:
a) Already ends with a period, or
b) Ends with no punctuation, so a period could be added automatically.

**Comment by brandjon** [comment]
There's a lot of documentation with double periods now. See for instance [transitive_exports](https://www.bazel.io/docs/skylark/lib/JavaSkylarkApiProvider.html#transitive_exports), or all the parameters of [runfiles](https://www.bazel.io/docs/skylark/lib/ctx.html#runfiles).

**Comment by katre** [comment]
Taking a look, thanks for pointing this out.
