### ISSUE TITLE
Dynamically Adjust Multiplex Workers For File Descriptors

### ISSUE THREAD

**Issue by EdbertChan** [bazelbuild/bazel#15278]
### Description of the feature request:

The assignment of multiplex workers in WorkerParser should take into account the number of file descriptors that need to be opened. New jobs and workers should be spun up if the additional number of file descriptors that are needed would cause a worker to exceed the number of file descriptors allowed per process.

We may also want to keep track of the system-wide number of file descriptors as well to make sure Bazel does not exceed those either.

### What underlying problem are you trying to solve with this feature?

When compiling a large number of modules (5000+) into an APK, we frequently will fail compilation because of "Too many open files". This occurs because there are more file descriptors that are being opened than what the system allows on a per process or system wide basis.

On MacOS, this is particularly pernicious because Mac sets the [maximum number of file descriptors ](https://wilsonmar.github.io/maximum-limits/)to be 12288 despite changing the ulimit numbers.

Temporarily, we get around this by restricting the number of multiplex workers to 1 just to get around the mega module being built. We have tried to increase the limit via various ulimit and launchctl commands but to no avail. Mac appears to implicitly set a limit of around 10240, even if we request more.

### Which operating system are you running Bazel on?

MacOS 12.3.1 (ARM 64)

### What is the output of `bazel info release`?

5.1.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

We have cherry-picked a few commits as well but nothing substantial that would affect workers. 

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
We base our fork on 5.1.0-uber

815d9e499a32fd4d87525ac0c698c293cf26433d
```

### Have you found anything relevant by searching the web?

Question has been raised in the bazel-discuss with no avail
https://groups.google.com/g/bazel-discuss/c/apv8tPqUxS4

**Comment by meisterT** [comment]
cc @wilwell

**Comment by arunkumar9t2** [comment]
We got similar issue as well when Kotlin Kapt was running and the worker would fail with `Too many open files`. 

>  We have tried to increase the limit via various ulimit and launchctl commands but to no avail. Mac appears to implicitly set a limit of around 10240, even if we request more.

According to [this](https://github.com/gradle/gradle/issues/17274#issuecomment-849491157), it seems child process by default will have default limits when parent process sets the `-XX:-MaxFDLimit` flag, however they can be increased if child process also sets the flags. In Bazel's case, Bazel does set the flag for bazel process.

In our case, since it was Kotlin workers, I tried adding the [flags](https://github.com/bazelbuild/rules_kotlin/pull/811) to builder jar and the error went away. 

A global fix would be nice. I tried adding [--jvmopt](https://bazel.build/reference/command-line-reference#flag--jvmopt) to force each `java_binary` to have that flag but for some reason it did not work.

**Comment by larsrc-google** [comment]
@EdbertChan Does @arunkumar9t2's suggestion work for you? 

@arunkumar9t2: `--jvmopt` only applies to Bazel itself, not to workers. There's `--worker_extra_flags`, but they are always placed at the end of the argument list, so one couldn't do a `-XX` flag there. I would rather keep this kind of specific parameter tuning in the individual worker definitions - only a minority of workers implementations would need this.

Relevant post https://superuser.com/questions/1634286/how-do-i-increase-the-max-open-files-in-macos-big-sur shows how to set the global total limit and per-process limit. With that available, adding complexity to the already-complex multiplex worker implementation is really not necessary.
