### ISSUE TITLE
`maybe` doesn't work in a `bzlmod` module implementation function

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#15377]
### Description of the bug:

A common pattern to avoid needing to determine whether or not to create new workspaces in a repository rule or macro is to use `maybe` to check the `native.existing_rules()` for the presence of a particular well-known name. This used to work in a `bzlmod` implementation function, but now no longer does.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
git clone https://github.com/shs96c/rules_jvm_external.git
cd rules_jvm_external
git checkout bzlmod
cd examples/java-export
bazel build //...
```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.1.1

### Have you found anything relevant by searching the web?

Not yet

**Comment by Wyverald** [comment]
This is actually intentional. An extension has its own "namespace" and can name its repos anything without fear of conflicting with something else. In fact, an extension cannot see repos generated by other extensions at all. What behavior are you expecting `maybe` to have here?

> This used to work in a bzlmod implementation function, but now no longer does.

IIUC `maybe` never worked in bzlmod. What's the behavior you remember?
