### ISSUE TITLE
no such package '@protobuf//' when installed syntax from source

### ISSUE THREAD

**Issue by wujun** [bazelbuild/bazel#1549]
my envrinoment: ubuntu==15.10, bazel==0.2.2b, protobuf==0.3.0.0b2 and I've confirmed that the network is no problem. while I run bazel test syntaxnet/... util/utf8/...  I got the following error every time.

ERROR: package contains errors: syntaxnet.
ERROR: no such package '@protobuf//': Error cloning repository: https://github.com/google/protobuf: cannot open git-upload-pack caused by https://github.com/google/protobuf: cannot open git-upload-pack caused by https://github.com/googl
e/protobuf: cannot open git-upload-pack caused by https://github.com/google/protobuf: cannot open git-upload-pack caused by https://github.com/google/protobuf: cannot open git-upload-pack.
INFO: Elapsed time: 1.421s
ERROR: Couldn't start the build. Unable to run tests.

**Comment by damienmg** [comment]
The bazel version is rather old, can you try to update to 0.3?

**Comment by hermione521** [comment]
No response for 2 weeks, so close. Feel free to reopen when come back.

**Comment by fyjthcy** [comment]
Excuse me ,have you solve the problem, wujun ? I met the same one , waiting for your anwser, thank you!

**Comment by kchodorow** [comment]
@fyjthcy, what version are you using?

**Comment by fyjthcy** [comment]
ubuntu 15.10bazel 0.2.0
protobuf 3.0.0b2
When I run bazel test syntaxnet/... util/utf8/...,always got the error.
在2016-09-09，Kristina <notifications@github.com> 写道:-----原始邮件-----
 发件人: Kristina <notifications@github.com>
 发送时间: 2016年9月9日 星期五
 收件人: bazelbuild/bazel <bazel@noreply.github.com>
 抄送: Jason Han <hanchuanyu@tju.edu.cn>, Mention <mention@noreply.github.com>
 主题: Re: [bazelbuild/bazel] no such package '@protobuf//' when installed syntax from source (#1549)

@fyjthcy, what version are you using?

**Comment by kchodorow** [comment]
Bazel 0.2.0 is very old, can you please try using a more recent version of Bazel? 0.3.1? https://github.com/bazelbuild/bazel/releases/tag/0.3.1

**Comment by fyjthcy** [comment]
The first time to install bazel I used "$ sudo apt-get update && sudo apt-get install bazel", the version was 0.3.1, but it also get the same error, because the installation document said "**versions 0.2.0 - 0.2.2b, NOT 0.2.3**",see the attachment在2016-09-09，Kristina <notifications@github.com> 写道:-----原始邮件-----
 发件人: Kristina <notifications@github.com>
 发送时间: 2016年9月9日 星期五
 收件人: bazelbuild/bazel <bazel@noreply.github.com>
 抄送: Jason Han <hanchuanyu@tju.edu.cn>, Mention <mention@noreply.github.com>
 主题: Re: [bazelbuild/bazel] no such package '@protobuf//' when installed syntax from source (#1549)

Bazel 0.2.0 is very old, can you please try using a more recent version of Bazel? 0.3.1? https://github.com/bazelbuild/bazel/releases/tag/0.3.1

**Comment by kchodorow** [comment]
Please try 0.3.1, it should at least give you a better error message.
