### ISSUE TITLE
test_tag_filters not used from bazelrc

### ISSUE THREAD

**Issue by ishaangandhi** [bazelbuild/bazel#15508]
### Description of the bug:

The `test_tag_filters` specified in the bazelrc are not used.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel.rc` content: `test --test_tag_filters=-my-tag`

BUILD:
```
py_test(
   name = "foo",
   srcs = ["foo.py"],
   tags = ["my-tag"],
)
```

Then run:
```bash
$ bazel test //:foo
  //:foo                         PASSED in 0.2s
```

Whereas if you specify that filter on the command line, the test is not run:
```bash
$ bazel test --test_tag_filters=-my-tag //:foo
INFO: Build completed successfully, 3 total actions
```

### Which operating system are you running Bazel on?

Red Hat 8

### What is the output of `bazel info release`?

4.2.1

### Have you found anything relevant by searching the web?

Could not find anyone else with this issue.

**Comment by ishaangandhi** [comment]
Sorry, you are right, I oversimplified the reproduction. I think this case _should_ reproduce. There are 2 bazelrc's, with one importing another.

`bazel1.rc`:
```
test:config1 --test_tag_filters=-no-abc,-no-xyz
```
and then `bazel.rc`:
```
import /path/to/bazel1.rc
coverage --test_tag_filters=-my-tag
```

Then when you run `bazel coverage`, targets with tag `my-tag` still get tested, which is somewhat unexpected. I've observed the error goes away if you remove the `test_tag_filter` from `bazel1.rc`.

**Comment by michajlo** [comment]
I believe what's happening is that `--test_tag_filters` doesn't accumulate, so when you do `bazel coverage  --config=config1 ...` what this is logically expanding to is `bazel coverage --test_tag_filters=-my-tag --test_tag_filters=-no-abc,-no-xyz ...`. In this event both `--test_tag_filters=` are present because the `coverage` command inherits from the `test` command, but the last occurrence wins. Unfortunately I can't think of a good way of accomplishing what I assume is your goal is without duplicating the full filter list.

**Comment by haxorz** [comment]
@ishaangandhi Does this new information change you mind about this being a Bazel bug and would you like to close this? Or are you thinking of a feature request where we make it so multiple specifications of the `--test_tag_filters` flag cause their values to be concatenated? (Fwiw though that'd be a consequential change and the outcome of research of existing usage of the flag might cause us to reject such a FR.)

**Comment by haxorz** [comment]
I filed #15535 as a generalization of your preference. I'll close this here as WAI.
