### ISSUE TITLE
I get jdk errors with `bazel build`

### ISSUE THREAD

**Issue by meftunca** [bazelbuild/bazel#15561]
### Description of the bug:

devloops@MacBook-Pro bazel_simple % bazel build //lib:hello-time
Starting local Bazel server and connecting to it...
ERROR: /private/var/tmp/_bazel_devloops/3c71a09d214a65591637b0ad911fdcd5/external/bazel_tools/tools/jdk/BUILD:432:8: In rule 'proguard_whitelister_test', size 'medium' is not a valid size.
ERROR: /private/var/tmp/_bazel_devloops/3c71a09d214a65591637b0ad911fdcd5/external/bazel_tools/tools/jdk/BUILD:432:8: In rule 'proguard_whitelister_test', timeout 'illegal' is not a valid timeout.
ERROR: Analysis of target '//lib:hello-time' failed; build aborted: error loading package '@bazel_tools//tools/jdk': Package 'tools/jdk' contains errors
INFO: Elapsed time: 9,773s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (29 packages loaded, 6 targets configured)
    Fetching @local_jdk; fetching
    Fetching @local_config_cc_toolchains; Building xcode-locator

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bazel build //lib:hello-time

### Which operating system are you running Bazel on?

MacOS BigSur 11.6

### What is the output of `bazel info release`?

release 5.1.1-homebrew

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

I created manually
```

### Have you found anything relevant by searching the web?

Unfortunately I couldn't find a sample solution.

**Comment by meftunca** [comment]
> Hello @meftunca, Could you please provide complete steps to reproduce the above error. Thanks!

Of course

1.  `brew install bazel`
2. i copied the [example stage 3](https://github.com/bazelbuild/examples/tree/main/cpp-tutorial/stage3) to my desktop directory 
3. `bazel build //main:hello-world`

**Comment by meftunca** [comment]
Hi,  I fixed the bug by changing macos system language from turkish to English.

**Comment by UlasSAYGINIM** [comment]
@sgowroji, i think python or Starlark Language has problem about turkish characters. because there is one letter causes problem.
i am writing this because it is ancient problem for computer programming history for turkish people.
we have capital I and İ. last one is dotted I and we have little ı but english alphabet has lower i with dot. but upper case is not dotted. because of this, some programming languages or databases has problem when turkish characters used.
for example, if you use database field name "id" and if you use english alphabet for upper letters it is "ID" but if you take upper letters for turkish alphabet it is "İD" dotted I and it is problem. it think similary thing is happening.
