### ISSUE TITLE
dependency in java_binary runtime_deps can't be used as arg of $(location ...)

### ISSUE THREAD

**Issue by mzhaom** [bazelbuild/bazel#1566]
This works:

```
java_binary(
  name = 'test',
  main_class = 'Test',
  srcs = glob([
    'Test.java',
  ]),
  jvm_flags = [
    '-Xbootclasspath/a:$(location //third_party/java/allocation-instrumenter:allocation_agent_deploy.jar)',
    '-javaagent:$(location //third_party/java/allocation-instrumenter:allocation_agent_deploy.jar)',
  ],
  deps = [
    '//third_party/java/allocation-instrumenter:allocation_agent_deploy.jar',
  ],
)
```

But changing the "deps" to "runtime_deps" doesn't work:

```
java_binary(
  name = 'test',
  main_class = 'Test',
  srcs = glob([
    'Test.java',
  ]),
  jvm_flags = [
    '-Xbootclasspath/a:$(location //third_party/java/allocation-instrumenter:allocation_agent_deploy.jar)',
    '-javaagent:$(location //third_party/java/allocation-instrumenter:allocation_agent_deploy.jar)',
  ],
  runtime_deps = [
    '//third_party/java/allocation-instrumenter:allocation_agent_deploy.jar',
  ],
)
```

Error message:

```
ERROR: /usr/local/home/mzhao/s/m2/main/codelab/java/memory-allocation/BUILD:9:15: in jvm_flags attribute of java_binary rule //codelab/java/memory-allocation:test: label '//third_party/java/allocation-instrumenter:allocation_agent_deploy.jar' in $(location) expression is not a declared prerequisite of this rule.
ERROR: /usr/local/home/mzhao/s/m2/main/codelab/java/memory-allocation/BUILD:9:15: in jvm_flags attribute of java_binary rule //codelab/java/memory-allocation:test: $(location //third_party/java/allocation-instrumenter:allocation_agent_deploy.jar) not defined.
ERROR: /usr/local/home/mzhao/s/m2/main/codelab/java/memory-allocation/BUILD:9:15: in jvm_flags attribute of java_binary rule //codelab/java/memory-allocation:test: label '//third_party/java/allocation-instrumenter:allocation_agent_deploy.jar' in $(location) expression is not a declared prerequisite of this rule.
ERROR: /usr/local/home/mzhao/s/m2/main/codelab/java/memory-allocation/BUILD:9:15: in jvm_flags attribute of java_binary rule //codelab/java/memory-allocation:test: $(location //third_party/java/allocation-instrumenter:allocation_agent_deploy.jar) not defined.
```

**Comment by ulfjack** [comment]
LocationExpander has a fixed list of attributes it checks for dependencies. Adding runtime_deps would fix this problem, but not the more general problem that a hard-coded list is just not a good idea.

The current hard-coded list is srcs, for which it gets files-to-build, and deps, tools, and data, for which it gets files-to-run.

Additionally, the LocationExpander is not called explicitly, but implicitly through RuleContext, so the rules don't have a chance to pass in a list of attributes. It's not obvious how to change it to be called explicitly, as the framework is doing a bunch of 'magic' work for binaries and tests.

I think the most straightforward fix is to annotate the attributes to indicate whether the labels from that attribute should be expanded. If we do that, however, we should not iterate over all attributes in the location expander, because that would likely be expensive (number of attributes * number of rules in the workspace; ideally, we'd have a benchmark which would tell us whether that's ok or not). Instead, we should probably keep a list of expanded attributes in the rule class.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
