### ISSUE TITLE
Several downstream projects broken by repository rule changes

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#15667]
### Description of the bug:

https://github.com/bazelbuild/bazel/commit/3c07a3416ebd784d00c75b40388217bab4e743e2 seems to have broken a number of downstream projects. https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/938

Example failure log:
```
ERROR: Traceback (most recent call last):
--
  | File "/var/lib/buildkite-agent/builds/bk-docker-l5tx/bazel-downstream-projects/protobuf/WORKSPACE", line 65, column 20, in <toplevel>
  | kotlin_repositories()
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/22bc6feb06bf3d09950f383d42d078bc/external/io_bazel_rules_kotlin/src/main/starlark/core/repositories/initialize.bzl", line 96, column 21, in kotlin_repositories
  | rules_repository(
  | Error in repository_rule: invalid repository name '': must start with a letter and contain only letters, digits, '.', '-', or '_'
```

Identified broken projects:

Protobuf
rules_go
rules_kotlin
rules_rust
rules_scala

**Comment by c-parsons** [comment]
Looks like https://github.com/bazelbuild/bazel/pull/15666 is a fixforward

**Comment by Wyverald** [comment]
hmm, the fixforward and part of the original offending CL were rolled back yesterday (https://github.com/bazelbuild/bazel/commit/4ccc21f2f089971e5f4032397764a4be3549c40a). That fixed some of the breakages but more still remain.

The rules_kotlin breakage is intentional and should be fixed by https://github.com/bazelbuild/rules_kotlin/pull/772, though that PR causes yet more failing tests...

rules_jvm_external and protobuf are broken due to rules_kotlin.

That leaves rules_go, which I'll take a look at next.
