### ISSUE TITLE
OSX enviroment PATH gets truncated

### ISSUE THREAD

**Issue by k6project** [bazelbuild/bazel#1571]
Hi,

I have py_binary rule with PY3 set as default_python_version. When the build runs, it fails to locate python3:

Traceback (most recent call last):
  File "bazel-out/local-py3-fastbuild/bin/testws/test-builder", line 122, in <module>
    Main()
  File "bazel-out/local-py3-fastbuild/bin/testws/test-builder", line 107, in Main
    raise AssertionError('Could not find python binary: ' + PYTHON_BINARY)
AssertionError: Could not find python binary: python3

I have modified standard template for the script to print every path it checks. Seems like environment path is truncated to /bin:/usr/bin

The problem is that under OSX python3 (installed via Homebrew) is under /usr/local/bin

What would be a correct way to adjust default environment?

**Comment by damienmg** [comment]
The python binary is mostly hard coded IIRC, you need to set --python3_path in the command line.

**Comment by damienmg** [comment]
Also it seems like the python rules does not pass around the default shell environment.

**Comment by brandjon** [comment]
Related issue about invoking the python interpreter, though sounds like a different cause: #4815.

**Comment by brandjon** [comment]
The plan is that this will be addressed by Python toolchains (#7375). In the meantime, you can set the Python version with `--python_top` / `py_runtime`, or with `--python_path`.

Both of those will ignore whether the target is configured for PY2 or PY3 though, due to #4815. See the `--python_top` / `py_runtime` based workaround [there](https://github.com/bazelbuild/bazel/issues/4815#issuecomment-465194800).

I'll close this as a dup of the toolchain feature work and that bug.

**Comment by brandjon** [comment]
@k6project Rereading your initial post I may have acted hastily -- Are you saying that you are identifying the Python binary by its executable name (not path), e.g. via `--python_path=python3`, and that it's not finding it even though the right directory is on `PATH` in your env?

In that case Damien's point about passing the shell env is probably the issue, but it's not obvious that we want the user's shell env to affect the behavior of the stub template. This can be worked around in a more robust way by using an absolute path, for instance, especially in a py_runtime target/toolchain.
