### ISSUE TITLE
Allow .pyi (python interface) files to be sources for py_library/binary

### ISSUE THREAD

**Issue by joe-polin** [bazelbuild/bazel#15727]
### Description of the feature request:

We sometimes use `.pyi` files to define type hints/interfaces for tools such as mypy ([docs](https://mypy.readthedocs.io/en/stable/stubs.html)). In particular, I'm using [mypy-proto](https://github.com/nipunn1313/mypy-protobuf) to generate mypy-friendly files for type checking.

The expected use for mypy is to have `foo.py` and `foo.pyi` in the same folder, and mypy will choose the `.pyi` version when type checking. However, bazel prevents this since `.pyi` files are not a recognized extension for python (relevant line [here](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/python/PyRuleClasses.java#L42)).

Thus, I propose that we recognize `.pyi` as a valid python extension so that they can be included in python-related rules (eg py_library).

### What underlying problem are you trying to solve with this feature?

Work seamlessly with mypy and mypy-proto.

### Which operating system are you running Bazel on?

Ubuntu

**Comment by joe-polin** [comment]
What do you all think? Wondering if we can make this happen, or I need to take a much hackier approach (that I'm sure others will need to do as well)

**Comment by dzbarsky** [comment]
I would prefer the python rules take a separate attribute called `stub_srcs` for pyi files. That would let mypy and other tools consume those without polluting other users of the sources attribute. But otherwise, +1 for this feature request!

**Comment by joe-polin** [comment]
> I would prefer the python rules take a separate attribute called `stub_srcs` for pyi files. That would let mypy and other tools consume those without polluting other users of the sources attribute. But otherwise, +1 for this feature request!

I could be onboard with that! I believe we'll still need them to end up in the same folder for mypy to pick them up.

**Comment by comius** [comment]
cc @rickeylev

**Comment by rickeylev** [comment]
I think overall, I'm +1 to the idea of having them as a separate attribute on the `py_*` rules. The main compelling rationales being (1) srcs are understood to be "runnable" python code (that should go in runfiles), and pyi files aren't necessarily (there's a few minor differences between pyi and py IIUC), and (2) ergonomics (putting pyi files next to py is commonplace, lets make it straight forward). So I'd accept a PR implementing such an attribute.

Long term, there are richer and more complex cases that will need some more thought into how to handle this (see below).

Let's bike shed over the name a bit? "stub_srcs" sounds a bit misleading -- source code that does nothing? Maybe "pyi_srcs" (we use this name internally) or "type_stub_srcs"? Is there a standard/de-facto/normative term established by e.g. a PEP somewhere we can re-use (is "stubs" exactly that?)? I don't have particularly strong feelings re: naming.

> I could be onboard with that! I believe we'll still need them to end up in the same folder for mypy to pick them up.

Well, yes and no. That's really up to mypy and how it wants to integrate with Bazel. Internally, with Pytype, we have a couple different ways that type stubs are passed around. The "basic" rules have a separate `pyi_srcs` arg, and it's presumed they live next to the .py files. For some more complex cases (e.g. protocol buffers, C extensions, boot strapping, generated code, etc), targets (e.g. a cc_library) are able to specify (via a special provider directly or by a target in `data` providing said special provider) pyi files (or equivs) and their logical "root prefix". A case that is more germane/familiar to non-mono repo use is probably things like typeshed or the `foo-stubs` packages (whose file locations wouldn't be alongside the py files).

#### Those richer and more complex future cases that will need some more thought

I asked some other Starlark experts their thoughts on whether pyi files should be an attribute or not. Some good points were raised. Here's a summary, for posterity

* Why not just put them in srcs? This is what the cc rules do.
  * The gist I got from briefly asking cc folks was that behavior wasn't exactly intentional, and can be a pain in some various ways.
  * Today, tools consuming py rules assume the things in sources are legit py files. Type stubs don't seem like a strong reason to change that assumption.
  * pyi info is meant to be sent to consuming rules; py files less so (py files are, at their core, just files put in runfiles, while pyi are build-time files passed along to tools); with very different purposes, different attributes makes sense.
* Why not have a separate rule entirely, with its own providers etc?
  * Ergonomics, basically.
  * A separate rule might be an unavoidable in the future (see below).
* There's some prior art for this with the cc rules and hdrs and srcs attributes.
* There end up being complications around optimal dependencies when there's another srcs attribute, in two regards:
  * build-time only (superset) dependencies. Things like `if typing.TYPE_CHECKING` basically introduce build-time-only dependencies. i.e., an attribute that means "add these deps, in addition to regular deps" is needed
  * Different interface vs implementation (disjoin) dependencies. e.g., a module's interface can be `def get_username(server: str) -> str`, which is effectively no dependencies. However, an implementation might depend on e.g. protocol buffers (i.e. expensive code gen). The most optimal dependency configuration allows a consuming target of `get_username` to build immediately using the pyi file, while the type-checker waits for the more expensive dependencies to finish building before running. i.e., you need a "only use these deps, not regular deps" attribute (e.g. "implements") is needed.
* Augmenting non-py rules makes a dedicated "stubs library" rule almost unavoidable.
  * As an example, a `cc_library` can provide an importable CPython module. But the cc rules shouldn't depend on the py rules (philosophically problematic, but also it creates circular dependencies i think). So another mechanism (e.g. a special target in `data`) has to be used (the `data` trick is one way Google solves this for its internal pytype rules).
  * Another example is to allow pyi files for "foo" to located elsewhere, i.e. not alongside foo.

**Comment by joe-polin** [comment]
Hey @rickeylev thanks for the thorough and well though out response. These are all great questions! I don't have answers for most of them (at least, not good ones). A few thoughts:

> Let's bike shed over the name a bit?

I believe that the `i` in `.pyi` stands for interface. The mypy [documentation](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages) mostly uses the words "stubs." Given that this is pretty common in pip packages, hopefully there are some patterns to draw from there.

> Why not just put them in srcs? This is what the cc rules do.

Actually, no objection on my end. This seems like the cleanest integration with mypy. If this also worked with my IDE's autocomplete, that would really be ideal!

**Comment by adam-azarchs** [comment]
Another thing that was alluded to but maybe not called out explicitly is it would be useful to have an attribute like `type_checking_deps` to represent dependencies which are required for type checking but which are not required at runtime.  That is, in particular, `PyInfo.transitive_sources` would include the `srcs` for a `py_library` and its transitive `deps`, and `.transitive_type_checking_sources` (or whatever) would include that plus `pyi_srcs` (or whatever) and transitive `type_checking_deps`.

Example use case I have in mind here is a module which contains a bunch of `TypedDict`s used for type annotations, but the module contains comments discussing things we don't want to have exposed to customers, so we don't want that to be sucked in through normal dependencies.
