### ISSUE TITLE
genquery should support wildcards in expression

### ISSUE THREAD

**Issue by grimreaper** [bazelbuild/bazel#15894]
### Description of the feature request:

It should be possible to support wildcards in expressions in genquery

```
genquery(
    name = "prism-core", # this would be the root directory
    expression = "deps(//prism/...)",
    scope = [
        "//prism/...",
    ],
)
```

### What underlying problem are you trying to solve with this feature?

We have specific desires to be able to assert information about our build graph. For example "no target under directory X should depend on anything in package Y" or "nothing in the "src" directory should depend on the "tests" directory [0].

It is currently possible to do this on a target-by-target basis by writing genquery rules but it isn't possible to assert something about "all subpackages" or even "all packages".

[0] testonly is a minimal and incomplete special case of the sort of rule we wish to capture

**Comment by zhengwei143** [comment]
I'm afraid this is by design and will not be supported: https://bazel.build/reference/be/general#genquery

> The reasons for this are two-fold: first, because `genquery` has to specify a scope to prevent targets outside the transitive closure of the query to influence its output; and, second, because `BUILD` files do not support wildcard dependencies (e.g. `deps=["//a/..."]` is not allowed).

**Comment by zhengwei143** [comment]
I haven't tested this but, you could try a combination of [existing_rules](https://bazel.build/rules/lib/native#existing_rules) to define "top-level" targets per package (which has all the targets in its package under its transitive closure) and [subpackages](https://bazel.build/reference/be/functions#subpackages) to collect these "top-level" targets. Then construct the genquery accordingly.

This might not be too sustainable since you'd have to remember to create a "top-level" target for each package, but I can't think of another alternative yet.
