### ISSUE TITLE
bazel should support inherited visibility

### ISSUE THREAD

**Issue by grimreaper** [bazelbuild/bazel#15893]
### Description of the feature request:

It should be possible to define visibility on an inherited basis. 
for example 

```
package_and_subpackages(default_deprecation, default_testonly, default_visibility, features)
```

naming is left as exercise to the readers.

### What underlying problem are you trying to solve with this feature?

We have a specific code structure we try to enforce. For example
```
src/<language>/com/...//lib/<lib>/api
	- contains the API of the library
	- external users may depend on this

src/<language>/com/.../lib/<lib>/internal
	- contains the implementation details.
	- can only be depended on by the `factory`
	- may not be depended on from outside the library

src/<language>/com/.../lib/<lib>/factory
	- produces actual object instances.
	- depends on `api` and `internal`
	- external users may depend on this
....
```

as an entirely different example some of our directories are considered "leaf only" and thus nothing outside of these directories may depend on them.  Without this work we need to explicitly add visibility rules to *every* BUILD file in said directory.

to do this we rely on a mixture of things
- explicit visibility rules
- home grown external tests of these rules
- translation layers that implicitly add visibility rules

this is a problem for multiple reasons
1. each new package under internal must add visibility rules
2. each new library must copy these rules
3. it is not uncommon for engineers to not fully understand the issues and thus add additional whitelisted directories to the visibility rules

while this is not a complete solution it would be nice to be able to set up default visibility rules for a package *and its sunpackages*. This would allow for fewer places to encode the rules and thus less cargo-culting. 

future feature requests will address other parts of the problem

**Comment by dgoldstein0** [comment]
+1 to this proposal, though I'm not sure if I want the same semantics for inherited visibility and default visibility.  it's a good starting place though.

At Dropbox, we have similar problems - we have needed to go outside of bazel to enforce desired code organization.  From a social perspective, the general problem is there's some engineers who will just do the easiest thing available to them at the moment, and sometimes that means "I'll just import this helper function from another service" and ignore the massive dependency bloat it can cause.  In particular we've ended up with a folder structure where different service's controller code go in different subfolders, and we have a test that whitelists what visibility the subpackages of those subfolders are allowed to have - with the main effect of banning cross-service dependencies and forcing shared code to live in other subtrees of our git repo.

Other pieces of our puzzle are how ownership and code reviews interact - our ownership system is roughly "each file is owned by one team, and they can have blocking reviews on it".  The problem with visibility then is that a lot of teams don't really care who imports their code and are lax about setting and then enforcing stronger visibility constraints at code review time.  A related problem is that as we try to lock down usage of code via visibility, we usually have to encode all the existing violations into the current visibility and once our visibility list has >10 packages on it, people start assuming the right thing to do is just add to it.

So anything that can give us a little more capability to centrally manage visibility in bazel seems worthwhile.

Re
> Having inherited visibility also means that Bazel now has to (potentially) load more packages because it needs to read all the BUILD files from parent directories of the packages Bazel reads today, which increases memory consumption and the risk of OOMs.

Perhaps bazel could be smart and just lex/parse enough of the BUILD file to find the visibility declaration? And can only bother reading the rest of the BUILD file if it actually needs a label within it?

**Comment by haxorz** [comment]
Hi, I'm the lead of the team responsible for the `team-Core` GitHub label (and the associated "Core" part of Bazel).

I'm going to reject this FR from a technical perspective. My reasoning is below. I understand the product-land motivation and merits of the FR though. If you want to pursue those I recommend filing a separate GH issue (that doesn't get routed to `team-Core`), or just reopen this one, and engage with the Bazel leadership from a product perspective (@sventiffe fyi).

> [@Yannic] Having inherited visibility also means that Bazel now has to (potentially) load more packages because it needs to read all the BUILD files from parent directories of the packages Bazel reads today,

The concern is larger than just the extra work.

A key property of package loading is packages can be loaded independently. Lots of Bazel's internals rely on this property, for both correctness and performance and also just for the general architecture. Iiuc, the proposed feature would necessarily violate the property.

> [@dgoldstein0] Perhaps bazel could be smart and just lex/parse enough of the BUILD file to find the visibility declaration? And can only bother reading the rest of the BUILD file if it actually needs a label within it?

Theoretically possible, but a lot more difficult than it sounds.

We encounter the same technical issue, and have the same high-level solution idea, in situations like "The only target in package //b on which //a:a transitively depends is //b:b, so how come when a do `bazel build //a:a` Bazel isn't smart and instead loads the entirety of package //b?"

The core technical issue is that `BUILD` files are executed line-by-line, and features like `native.existing_rule[s]` mean the execution order is semantically relevant. Also, there's no magic "index" for a `foo/BUILD` that says something like "if you want target `//foo:t` to exist, execute this list `L` of subsequences of lines". So Bazel needs to read, lex, parse, and execute the entirety of `foo/BUILD` just to understand what `//foo:t` means.

Fwiw, one principled way to address this would be to

(a) Remove all features like `native.existing_rule[s]` that allow observation of execution order.
(b) Rearchitect the Starlark interpreter to have "need-based" semantics.
(c) Rearchitect Bazel's package loading internals to be able to operate on parts of packages and parts of `BUILD` files.
(d) Rearchitect Bazel's package loading internals to be implemented in terms of a "need graph". Fwiw, this would be very possible from a technical perspective once (b) and (c) are in place since it fits nicely in the Skyframe computation model :)
