### ISSUE TITLE
References to a local repository subdirectory should only be allowed through @repo syntax

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#1592]
That is, if you have:

```
foo/
  WORKSPACE
  BUILD
  bar/
    WORKSPACE
    BUILD
```

and foo/WORKSPACE contains `local_repository(name = "bar", path = "bar")`, then foo/BUILD should not be able to depend on `//bar:whatever`.  Similarly, `bazel build //...` should not include targets in `@bar`.

**Comment by kchodorow** [comment]
John, could you take a look at this? It's the same part of the code that your BUILD file naming changes touched.

**Comment by katre** [comment]
Sure, I'll investigate.

**Comment by katre** [comment]
I've written a shell test that catches this error, and debugged through the PackageFunction, PackageLookupFunction, and LocalRepositoryFunction code that is involved. I'm not sure we have enough data to catch this currently.

Currently, we have a mapping of "repository name"->"repository directory" which is used to load the package. In order to catch this case, we'd need the reverse mapping, and we'd have to check it for every package (which means a lot more skyframe nodes to cache the data).

Would it be acceptable to simply disallow local_repository for a path that is a child of the workspace? If that was the case, then the example above would be an error (in the local_repository rule), but the case where your local_repository is outside the workspace (and which seems to be the more common usecase) would be fine.

In the documentation for local_repository, we're already requiring (although not enforcing) that this be an absolute path: http://bazel.io/docs/be/workspace.html#local_repository

**Comment by kchodorow** [comment]
Keeping repository directory->repo name mapping seems like the most reasonable solution to me: we can generate it when the WORKSPACE file is parsed and I don't think it would be too many more skyframe nodes. One other thought is that ContainingPackageLookupFunction.java already does something sort of similar, perhaps we could hook in there without too much of a performance penalty?

One part of this that might be easier/sufficient-for-now is to forbid //... (and globbing **) from descending into workspaces.

The documentation is out of date. This feature is pretty popular and is used by tensorflow and many other users.

**Comment by katre** [comment]
Makes sense, I'll keep looking.
