### ISSUE TITLE
Bzlmod: `repository_ctx.name` includes module + extension prefix

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#15936]
### Description of the bug:

With Bazel @ HEAD, when a repository rule is instantiated by a module extension, the value of `repository_ctx.name` in the implementation function of the repository rule includes the `@<module name>.<extension name>~` prefix. This breaks e.g. `rules_java`, which uses the name as a base to derive further names of targets.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```bash
git clone https://github.com/bazelbuild/rules_java
cd rules_java
git checkout c1aa568d1a64267139d14857587e1dcb640a1987
USE_BAZEL_VERSION=9a25d92bd5f177d24de35a4b662248234c37af4d bazelisk build --experimental_enable_bzlmod //examples/...
```

### Which operating system are you running Bazel on?

Linux

**Comment by Wyverald** [comment]
I believe rules_java needs to be fixed -- it's also somewhat of a breaking change to make `repository_ctx.name` *not* represent the canonical repo name here.

rules_java actually tried to address this in https://github.com/bazelbuild/rules_java/commit/ac7cc454f76326af731ab6f932cc3cdc6470d86d, but I think a better fix is to explicitly pass in the information needed as a separate argument, instead of parsing it out of "name". I'll send a follow-up PR there.
