### ISSUE TITLE
Crash when trying to call Label.relative() in a BzlMod module extension implementation function

### ISSUE THREAD

**Issue by digit-google** [bazelbuild/bazel#16034]
### Description of the bug:

As the title says, trying to call Label.relative() within a module extension implementation function results in a runtime crash.
I have uploaded a reproduction case to my github account (see below).

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/digit-google/bazel-experiments/tree/main/bzlmod-module-extensions/crash-with-label-relative-call

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 5.3.0rc1

**Comment by andyrinne12** [comment]
Thanks for reporting that! I've tested your example on the latest `main` commit of this GitHub repo (i.e. using Bazilisk with the `USE_BAZEL_VERSION=last_green` option) and the issue seems to not be present anymore. However, your code fails because there is no repository called `@ext_module` with a rule called `:files`. After I fix these, your example works fine for me. Please let me know if you have any other issues with this.

**Comment by Wyverald** [comment]
As @andyrinne12 pointed out, this is fixed on HEAD. The fix is not trivial to cherry-pick back to 5.3.0, so we might just ask you to test with `last_green` instead. Thanks!
