### ISSUE TITLE
Building signed APK for release for Android app?

### ISSUE THREAD

**Issue by cardshuffle** [bazelbuild/bazel#1613]
Recently I've been working on a simple app based on [TensorFlow's Android demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android), which depends on Bazel for building/running. However, I've gotten stuck on building an APK for release in the Play Store. The [tutorial](http://www.bazel.io/docs/tutorial/android-app.html) in the docs for building an Android app doesn't cover generating signed APKs, and while I've tried uploading the APKs that are generated by Bazel (in the bazel-bin folder), they've been rejected for various reasons. `app.apk` was rejected for being signed for debugging and `app-signed.apk` was rejected for not being zipaligned, and `app-unsigned.apk` is unsigned. Additionally, I haven't had any luck with instructions given [here](https://github.com/tensorflow/tensorflow/issues/3444). Since trying to import the demo into Android Studio and build with Gradle only creates a whole slew of new errors, is there a way to use Bazel to generate a signed APK for release?

**Comment by hermione521** [comment]
@ahumesky can you help with this? Thanks.

**Comment by ahumesky** [comment]
Bazel will produce 3 apks (assuming the `android_binary` rule is named "app"):
`app.apk`: This is signed with the debug key and zipaligned
`app_unsigned.apk`: An unsigned (and not zipaligned) apk
`app_signed.apk`: Signed with the debug key, but not zipaligned

You'll want to sign app_unsigned.apk with your release keys:
https://developer.android.com/studio/publish/app-signing.html#signing-manually

Bazel doesn't sign with release keys because bazel generally expects files to come from your depot, and release keys shouldn't be checked in. Now that repository rules can be written in skylark though, it should be possible to create a skylark repository rule that will indicate to bazel where your release keys are, and a corresponding skylark rule that takes an `android_binary` and signs it with release keys.
