### ISSUE TITLE
[5.3.1] Bazel 5.3 fails to run external tests

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#16153]
Forked from #16003

**Comment by fmeum** [comment]
At Bazel HEAD, https://github.com/bazelbuild/bazel/pull/16008#issuecomment-1224267553 could be fixed by adding yet another rpath entry using https://github.com/bazelbuild/bazel/pull/14600 which is going to be merged soon.

For 5.3.1, one option would be to cherry-pick https://github.com/bazelbuild/bazel/pull/14600 and that additional rpath entry.

Alternatively, we could revert both https://github.com/bazelbuild/bazel/commit/e745468461f93839491a4f80d0c1883d9007f9c0 and https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe in Bazel 5.3.1, but that could regress users that started to rely on tests being executed from the runfiles root.

@oquenchil What do you think is the best path forward here? Would having up to three different rpaths on every binary have the potential to cause issues? As far as I understand, the names of dynamically linked binaries are relatively unique within Bazel, but could additional rpath entries that don't apply to the way the binary is actually executed lead to non-hermetic behavior?

**Comment by oquenchil** [comment]
> What do you think is the best path forward here? Would having up to three different rpaths on every binary have the potential to cause issues? As far as I understand, the names of dynamically linked binaries are relatively unique within Bazel, but could additional rpath entries that don't apply to the way the binary is actually executed lead to non-hermetic behavior?

I don't know to be honest. I'd prefer if we do it the cleaner way and revert whatever commits need to be reverted.

**Comment by Wyverald** [comment]
Unfortunately it's unlikely we can revert https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe since it's needed for Roboleaf and has been behavior for over a year now.

According to @oquenchil, @lberki is the best person to talk to about rpaths, but unfortunately he's still on leave for another two weeks.

So, as someone who knows absolutely squat about rpaths (and after consulting @fmeum), I think the best course of action now is merge #14600 into master, cherry-pick it into 5.3.1, cherry-pick another change that adds that extra rpath, and let tests take care of the problem of "do all these combinations work together".

**Comment by fmeum** [comment]
I think that the current issue could be fixed along the lines of #14600 without introducing the breakage on commas. I can have a PR ready by Monday.

**Comment by pcjanzen** [comment]
> How severe is the breakage you noted in https://github.com/bazelbuild/bazel/pull/16008#issuecomment-1224267553 ?

I don't think the case of running a test from an external repository from the command line is especially severe; however, the problem also affects local execution of cc_binary tools that are either dynamically linked, or that contain a reference to a shared library via cc_import.

See https://github.com/RobotLocomotion/drake/issues/17763 for a real-world example.
