### ISSUE TITLE
Document flagfile behavior

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1620]
1. @philwo Already gave a rough outline in (https://groups.google.com/forum/#!msg/bazel-discuss/oAEnuhYOPm8/ol7hf4KWJgAJ). Not sure yet whether it encompasses everything (still seeing errors trying to use workers) but anyway, this really should be documented.
2. Would it be possible to automatically generate the py bindings for `worker_protocol`?
3. And probably document that it is not:
   
   ```
   execution_requirements = {"supports-workers": 1},
   ```
   
   but:
   
   ```
   execution_requirements = {"supports-workers": "1"},
   ```
4. Although I really would like the `execution_requirements` to take any mapped type instead of strings only.

**Comment by abergmeier** [comment]
And recently there is `supports-workers`!?

**Comment by abergmeier-dsfishlabs** [comment]
And probably document that it is not:

    execution_requirements = {"supports-workers": 1},

but:

    execution_requirements = {"supports-workers": "1"},

**Comment by Ubehebe** [comment]
As far as I know, this has not been documented officially anywhere. See https://github.com/bazelbuild/bazel/issues/7997, which is about documenting persistent workers more generally.

I recently implemented a persistent worker in Python, and the @flagfile behavior was a [gotcha](https://github.com/Ubehebe/bazel-worker-examples#argfile-convention). It was initially unclear to me what component is responsible for expanding `@flagfile` into the flags it contains. (It looks like it might be shell magic, and it is hard to Google for or even know what to call it.)

It turns out that it is just a convention, and the worker executable is responsible for reading `flagfile` and parsing the args therein. This convention seems to be popular in the JVM world, and Java flag-parsing libraries do it automatically, but flag-parsing libraries in other languages (like Python) need to be explicitly configured to do it.

**Comment by larsrc-google** [comment]
We have added documentation for persistent workers: https://docs.bazel.build/versions/4.1.0/persistent-workers.html, https://docs.bazel.build/versions/4.1.0/multiplex-worker.html, and https://docs.bazel.build/versions/4.1.0/creating-workers.html. If any pertinent information is missing from there, please re-open this bug and tell me what you would like added.
