### ISSUE TITLE
Provider instances created inline aren't immutable

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#16420]
### Description of the bug:

When creating a `provider` instance and immediately adding to a `depset`, the error: `Error in depset: depset elements must not be mutable values` is displayed and the build fails. If the `provider` instance is created via a function, then everything works as expected.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```starlark
FooInfo = provider(fields = ["name"])
bob = FooInfo(name = "bob")
depset(direct = [bob])
```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.3.1

**Comment by shs96c** [comment]
Note, as of e8547351f7f840950f0d7309bfba99783c57b31e this problem still occurs, so it's not just a Bazel 5 issue.

**Comment by shs96c** [comment]
Here's an example workspace showing the problem [example.tar.gz](https://github.com/bazelbuild/bazel/files/9733570/example.tar.gz)

**Comment by brandjon** [comment]
I believe this is because the provider `FooInfo` is not "exported" until the end of the evaluation of the .bzl's top-level code. Until it's exported, its identifier is not known to the system and its instances don't have enough information to finalize their hash code, so they're considered mutable.

The typical use case of a provider is that it'd be declared at the top-level of a .bzl file and its instances wouldn't be added to depsets until later on during rule analysis. So this issue shouldn't arise often in practice. But it is a bit of a wart.

It's not clear that this is something we can (or want to) change. I believe in the past we exported providers immediately upon declaration, so you wouldn't run into this issue. But that complicates Starlark's evaluation model, so we did away with immediate exports.
