### ISSUE TITLE
bazel golang dependency build error

### ISSUE THREAD

**Issue by praetorian-thendrickson** [bazelbuild/bazel#16442]
### Description of the bug:

I'm trying to build a third party dependency with bazel (`github.com/microsoftgraph/msgraph-sdk-go v0.42.0`) https://github.com/microsoftgraph/msgraph-sdk-go. However, this third party dependency has a folder called "external" in it, which I think is bugging the bazel build system out. I reproduced the issue in a minimal bazel build configuration to confirm. I tried to build with the `--experimental_sibling_repository_layout` and `--experimental_disable_external_package` flags but neither fixed the error. The exact message when trying to create a bazel project and include the msgraph-sdk-go as a dependency is:
```
ERROR: /private/var/tmp/_bazel_user/66fd3004f0bb0404166f2e3be708ec70/external/com_github_microsoftgraph_msgraph_sdk_go/BUILD.bazel:3:11: no such target '//external:external': target 'external' not declared in package 'ext
ernal' defined by /Users/user/Desktop/bztest/WORKSPACE and referenced by '@com_github_microsoftgraph_msgraph_sdk_go//:msgraph-sdk-go'
ERROR: Analysis of target '//src:src' failed; build aborted:
```
I think the fix should be simple and involves passing one of those flags on the command line, but all the documentation I've seen does not seem to address the issue when it is a third party dependency using the `external` name. How might I build such a project? 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a bazel golang project and attempt to include `github.com/microsoftgraph/msgraph-sdk-go v0.42.0` as a dependency in the go.mod file, then attempt to run `bazel build //...`. 

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 5.3.0-homebrew

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
fatal: not a git repository (or any of the parent directories): .git
```

### Have you found anything relevant by searching the web?

I think this issue is related: https://github.com/bazelbuild/bazel/issues/16220

### Any other information, logs, or outputs that you want to share?

root BUILD.bazel:
```
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix src/main.go
gazelle(name = "gazelle")

gazelle(
    name = "gazelle-update-repos",
    args = [
        "-from_file=go.mod",
        "-to_macro=deps.bzl%go_dependencies",
        "-prune",
    ],
    command = "update-repos",
)
```

WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_go",
    sha256 = "099a9fb96a376ccbbb7d291ed4ecbdfd42f6bc822ab77ae6f1b5cb9e914e94fa",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.35.0/rules_go-v0.35.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.35.0/rules_go-v0.35.0.zip",
    ],
)

http_archive(
    name = "bazel_gazelle",
    sha256 = "501deb3d5695ab658e82f6f6f549ba681ea3ca2a5fb7911154b5aa45596183fa",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-gazelle/releases/download/v0.26.0/bazel-gazelle-v0.26.0.tar.gz",
        "https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.26.0/bazel-gazelle-v0.26.0.tar.gz",
    ],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")
load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
load("//:deps.bzl", "go_dependencies")

# gazelle:repository_macro deps.bzl%go_dependencies
go_dependencies()

go_rules_dependencies()

go_register_toolchains(version = "1.19.1")

gazelle_dependencies()
```

src/BUILD.bazel:
```
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/example/project
gazelle(name = "gazelle")

go_library(
    name = "project_lib",
    srcs = ["main.go"],
    importpath = "github.com/example/project",
    visibility = ["//visibility:private"],
    deps = [
        "@com_github_azure_azure_sdk_for_go_sdk_azidentity//:go_default_library",
        "@com_github_microsoftgraph_msgraph_sdk_go//:go_default_library",
    ],
)

go_binary(
    name = "src",
    embed = [":project_lib"],
    visibility = ["//visibility:public"],
)
```

src/main.go:
```
package main

import (
    azidentity "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
    // a          "github.com/microsoft/kiota-authentication-azure-go"
    msgraphsdk "github.com/microsoftgraph/msgraph-sdk-go"
    "context"
    "fmt"
)




func main() {
	fmt.Println("running!\n")
	cred, err := azidentity.NewDeviceCodeCredential(&azidentity.DeviceCodeCredentialOptions{
	    TenantID: "<the tenant id from your app registration>",
	    ClientID: "<the client id from your app registration>",
	    UserPrompt: func(ctx context.Context, message azidentity.DeviceCodeMessage) error {
	        fmt.Println(message.Message)
	        return nil
	    },
	})
	
	if err != nil {
	    fmt.Printf("Error creating credentials: %v\n", err)
	}
	_ , err  = msgraphsdk.NewGraphServiceClientWithCredentials(cred, []string{"Files.Read"})
	if err != nil {
	    fmt.Printf("Error creating client: %v\n", err)
	    return
	}
}
```

**Comment by meteorcloudy** [comment]
This is a known issue that repositories having `external` folder in their source root will break with Bazel, can you file this issue against the original repo and find out a solution? (potentially avoid having the `external` directory).

**Comment by jin** [comment]
I don't think we ever tested the aforementioned flags in the context of external repos. AOSP's issue is with //external in the main repo.

**Comment by lberki** [comment]
Yeah, these flags only allow packages *under* `//external` but not `//external` itself (that'd be an even bigger change)

Where does `BUILD.bazel` come from and why does it reference `//external`?

**Comment by fmeum** [comment]
The `BUILD.bazel` is presumably generated by Gazelle because the `external` directory contains a Go source file. Other Go targets in the repo reference it and since Gazelle doesn't treat `external` as anything special, it ends up referencing `//external:external` (Gazelle defaults to creating a `go_library` named after the package).

Gazelle could try to work around this by renaming any top-level `external` directories but keeping their import paths. That will necessarily be brittle though as there could also be code references to the original `external` name.

@lberki Is there anything fundamentally blocking renaming `external` to e.g. `__bazel-external__` behind an incompatible flag? It would be interesting to see how many downstream projects actually rely on the exact name. Based on a cursory `grep`, most issues I found were related to C++ include paths and all could be worked around. Having such a flag would allow rulesets to prepare for any changes to how `external` is represented.

**Comment by lberki** [comment]
I don't think there is anything blocking such a rename, other than that then there would be a conflict with the string `__bazel-external__` :)

I'll defer to @meteorcloudy as to whether that is workable; `//external` is currently used for querying repository rules and replacing it with an ugly string would make that use case much uglier (`bazel query //__bazel-external__:$REPO` instead of `bazel query //external:repo`). It is also used with `bind()` rules, which are themselves deprecated but not removed.

@meteorcloudy has been working on `bazel modquery` which I hope will replace `bazel query //external:` but then getting rid of  `//external:` has the dependency of removing the legacy WORKSPACE file, which won't happen in at least a year, probably two.

@meteorcloudy : will `modquery` replace all the use cases of `bazel query //external:`?

I could imagine adding that flag to rename `//external:` to tide you over in the meantime, but only if we are confident that `modquery` is the future; otherwise, it would stay as yet another "forever incompatible flag" that fragments the Bazel ecosystem . I'm not too worried about `query //external:`, but I am worried about `bind()` because its use requires the string `//external:` in BUILD files which would be invalidated by the proposed rename.

**Comment by meteorcloudy** [comment]
The module query mechanism is entirely based on the new Bzlmod resolution result, we don't require the `//external` package. `bind` is also not supported in Bzlmod. So I don't see any blocker from Bzlmod side.

I think we can try to rename this with an incompatible flag, the migration would only be easier if Bzlmod is widely adopted.

**Comment by lberki** [comment]
How about instead a flag that 1. disables `bind()` 2. disables `//external`? I'm not sure how easy it is to implement (IIRC `//external` was implementation shortcut which ended up growing usages) but that's more forward-looking than an incompatible flag that just renames the package.

**Comment by lberki** [comment]
Yeah, flipping `--experimental_sibling_repository_layout` would be nice, but I thought it's a big enough change that it should be a big-ticket item for Bazel 7.0 instead of just casually flipping it in response to this bug.

I thought that if the above flag was implemented, people who need it can also use `--experimental_sibling_repository_layout` because having to use an ugly flag is better than not being able to get Bazel to work.

**Comment by bartekmi** [comment]
For what it's worth, I also ran into the exact same issue (working at Google in Git-on-Borg environment in the Anthos space). So this is not an isolated problem.

**Comment by Wyverald** [comment]
This is a very hard problem to work around, unfortunately -- short of renaming your "external" directory to something else, that is.

Realistically, this will probably be addressed by 2024 or so, when we remove WORKSPACE functionality from Bazel.

**Comment by arjantop-cai** [comment]
Linking workaround so it is easier to find: https://github.com/microsoftgraph/msgraph-sdk-go/issues/545
