### ISSUE TITLE
Worker configuration does not work standalone

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#1646]
Once you change the Action to "worker format" it no longer works in standalone mode.
IMO if standalone encounters the "worker format" it should extract arguments same as with workers.

While I could built in worker format in my executable I think it would be better if it would just work:tm:.
CC @philwo

**Comment by philwo** [comment]
With "change the action to worker format", do you mean adding the @flagfile parameter as the last argument? If not, please explain.

If yes, we can't do this - argument lists routinely become too long (see https://github.com/bazelbuild/bazel/issues/1650 for a report), so the trick is to write them to a file and then reference that file via @flagfile in the command-line args. The tool is responsible for handling this itself, similar to how JavaBuilder (https://github.com/bazelbuild/bazel/blob/master/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/OptionsParser.java#L222) and the linux-sandbox (https://github.com/bazelbuild/bazel/blob/master/src/main/tools/linux-sandbox.c#L370) do it.

Actually, it's debatable whether the worker strategy should even expand the flagfile. It maybe shouldn't, because it can't know for sure how the tool escapes the "@" sign - some tools use a duplicated "@@", some just don't escape it, some only want to expand the first @flagfile, but not recursively.

**Comment by abergmeier-dsfishlabs** [comment]
> Actually, it's debatable whether the worker strategy should even expand the flagfile. It maybe shouldn't, because it can't know for sure how the tool escapes the "@" sign - some tools use a duplicated "@@", some just don't escape it, some only want to expand the first @flagfile, but not recursively.

I am strongly against having multiple code paths that handle arguments differently just based on strategy.
So removing the @ expansion yes pretty please with mustard and honey :+1: 

> That said, I definitely need to improve our documentation on this whole topic. Sorry about the lack of good docs here. :(

True but quite frankly I can wait until 1.0 for that. Currently Bazel is not for the faint of heart anyways.

Would be better if some guys would frequent IRC since@damienmg and @kchodorow not holding the flag anymore.

**Comment by abergmeier-dsfishlabs** [comment]
So the best I could come up with was:

    # Write arguments to file to prevent exceeding various limitations
    packed_args = ctx.new_file(ctx.label.name + ".args")
    ctx.file_action(
      packed_args,
      "\n".join(arguments), # TODO: Escape \n in arguments first
    )

    if True: # Worker
      arguments = ["@" + packed_args.path]
    else: # Standalone
      arguments = [
        "--packed-arguments",
        packed_args.path,
      ]

    ctx.action(
      outputs = [output],
      inputs = inputs,
      executable = builder,
      arguments = arguments,
      execution_requirements = {"supports-workers": "1"},
      mnemonic = "Foo",
    )

This still does not work for both `worker` and `standalone` but at least you only have to negate the `if` when you switch strategies.
By now I think having a way to select via strategy would be way better:

    arguments = select({,
      ":fooIsWorker": ["@" + packed_args.path],
      "//conditions:default": [
        "--packed-arguments",
        packed_args.path,
      ],
    }),

Although I am not sure whether this then in turn leads to a invalidation of all `Foo` actions.
Optimally you would configure this so all strategies may work.

**Comment by abergmeier-dsfishlabs** [comment]
@philwo Or would you be willing to make the protobuf protocol a first class citizen in `ctx` AKA being able to write protobuf files?

**Comment by abergmeier-dsfishlabs** [comment]
Closing since I will close account.
