### ISSUE TITLE
Canonical repo for root workspace (@) has workspace_root "external"

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#16528]
### Description of the bug:

`Label("@@//js/private/node-patches:fs.js").workspace_root` returns "external".

I'm not sure if this is expected behavior of canonical labels (https://github.com/bazelbuild/bazel/issues/15593) or not. The  workspace_root of a label in the root workspace with apparent label literal (single "@") is the empty string.

/cc @Wyverald 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/aspect-build/rules_js/pull/544

(note, I tried to reproduce directly in aspect-build/bazel-lib but for reasons I don't understand, I couldn't observe the bug there. Maybe it's only visible when the label is created in an external repo created by a module extension)

### What is the output of `bazel info release`?

bazel 6.0.0-pre.20220922

**Comment by fmeum** [comment]
@Wyverald Looked into this and I *think* I know what's happening: The repro ends up evaluating `Label("@//js/private/node-patches:fs.js")` from the `rules_js` module's repo, which, since there is no repo with apparent name `""` visible from there, creates a label with a non-visible empty `RepositoryName`, which however doesn't compare equal to `RepositoryName.MAIN`. Thus, in this `RepositoryName`'s `getExecPath`, `"external" + "/" + ""` is constructed, which is normalized to just `"external"`.

Maybe `workspace_root` should just fail with an `EvalError` if `!this.packageIdentifier.getRepository().isVisible()`?
