### ISSUE TITLE
fastbuild inconsistency: sets -DDEBUG, -O0 on mac but not on linux

### ISSUE THREAD

**Issue by mobileink** [bazelbuild/bazel#16890]
### Description of the bug:

Building cc_library or cc_binary targets on macos with -c fastbuild generates a compile command that includes `-DDEBUG` and `-O0`.  Building the same code on Linux does not generate these args.

Using `-O0` for fastbuild makes sense, but I don't think `-DDEBUG` does. That has nothing to do anything the build tools can do to speed the build, really; it's something the user should control using copts.  I think it should be removed, but failing that it should be added to Linux so that builds are the same.

- 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run `build aquery //pkg:tgt` for a cc target.

### Which operating system are you running Bazel on?

Macos 13.0.1 (ventura)

### What is the output of `bazel info release`?

release 6.0.0rc3

### Have you found anything relevant by searching the web?

No.

**Comment by sgowroji** [comment]
Hello @mobileink, Could you please provide a sample example to test the above scenario. Thanks!

**Comment by mobileink** [comment]
On Thu, Dec 1, 2022 at 11:15 AM Keith Smiley ***@***.***>
wrote:

> shouldn't need a repro case here, it's just that
> https://github.com/bazelbuild/bazel/blob/1620b6eb0f19ef60a87ede9eb7b69ce5d0ee78ce/tools/osx/crosstool/cc_toolchain_config.bzl#L2070-L2087
> exists in the macOS crosstool and not the unix one
>
Thanks, I'm a little pressed for time.

I can see that changing either of those toolchains might be considered a
breaking change.  Another option would be to just provide a means to cancel
-DDEBUG.  Maybe by changing the 'defines' attribute to accept something
like "-UDEBUG", or maybe by defining an "undefines" attrib to go with it.

G

**Comment by keith** [comment]
yea im not sure what the right semantic decision is here. i could imagine that builds either expect `-DDEBUG` or `-DNDEBUG` always, but idk

**Comment by gvol** [comment]
The right semantic decision is to just remove the DEBUG define completely.  This is *not* a standard C/C++ define (that's NDEBUG).  It seems like it might be an Objective-C define (I'm not an Objective-C user so I don't know).  My guess is that it was accidentally added on Mac because of that association.  

Moreover, the define isn't the in `dbg` compilation mode, so if a build depends on `DEBUG`, it's already broken.  The build is similarly broken on linux, so I don't see how anyone can complain if it's removed.

I recently ran into this issue because we define our own `DEBUG` which is a macro to print to stdout, and we got a redefinition warning.  I didn't notice it until it broke a coworker's build because I always build in `dgb` mode locally and our CI/CD servers are all linux.
