### ISSUE TITLE
Symlink warnings since upgrading to Bazel 6

### ISSUE THREAD

**Issue by pdeva** [bazelbuild/bazel#17081]
### Description of the bug:

Seeing this message in output since upgrading to Bazel 6 (from Bazel 5):
```
WARNING: cleared convenience symlink(s) bazel-bin, bazel-testlogs because their destinations would be ambiguous
 ```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

upgrade to bazel 6 from bazel 5 and run build 

### Which operating system are you running Bazel on?

linux

### What is the output of `bazel info release`?

release 6.0.0

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
git@github.com:astradot/monorepo.git
55e066072b359d1bc55555c23bdc1476e79042f5
55e066072b359d1bc55555c23bdc1476e79042f5
```

**Comment by sgowroji** [comment]
Hi @pdeva, Minimal reproduce case is required for the above issue. Thanks!

**Comment by simmonmt** [comment]
not minimal, but pull https://github.com/simmonmt/advent-of-code  and bazel build in the 2022 directory with bazel 6 will reproduce it.

**Comment by fmeum** [comment]
As the reproducer uses the `nogo` rule, this is caused by https://github.com/bazelbuild/rules_go/issues/3409. Updating rules_go to commit https://github.com/bazelbuild/rules_go/commit/de2074e0af1df1a34a862ca6108ed15f760520df fixes the warning and results in symlinks being created correctly.

**Comment by simmonmt** [comment]
Thanks Fabian! Can confirm that adding the manual tag to the `nogo` rule fixed the problem. That's what the commit you referenced does, so it seemed easy to do that rather than updating `rules_go` to an unreleased commit. Happy New Year!

**Comment by sluongng** [comment]
This is a troublesome change from Bazel upstream. In a large project with rules_go's `nogo`, or rules_docker's `container_image` or any targets with `transition` applied, it would cause a lot of noise and some cases... cause builds to fail.

@fmeum hinted, to the discussion thread over at rules_go, but did not point out the root cause being this flag flipped in Bazel 6.0 https://github.com/bazelbuild/bazel/commit/6452024a0106ab901f38027db65e8ab831201288.

What is the long-term solution for this flag flip? Do we discourage folks from configuring top-level targets with `transition`?

@sgowroji Is it possible to contact the author of this CL for more info?

```
PiperOrigin-RevId: 454603210
Change-Id: I9bb2f0a46beeff27798b2a6006d5763ae5ff75c7
```

**Comment by bolitt** [comment]
Got the same message after upgrading 6.0.0.

```
Build label: 6.0.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Dec 19 16:07:42 2022 (1671466062)
Build timestamp: 1671466062
Build timestamp as int: 1671466062
```

I find the doc of output directory layout is still indicating `bazel-bin` and `bazel-testlogs`: 
https://bazel.build/remote/output-directories#layout-diagram

It is confusing: Are `bazel-bin` and `bazel-testlogs` recommended to be used or not after bazel 6?

**Comment by aranguyen** [comment]
Hi all, apologies for the late response. 
@fmeum I'm not familiar with the manual tag in your fix, could you please help explain its functionality?

> What is the long-term solution for this flag flip? 
@sluongng Since this flag is enabled by default, the long term goal is to remove it and the current behavior would stick. You also mentioned that this caused breakages, could you please help me with a repro for a known breakage? We can talk more about the current `WARNING` being noisy and perhaps consider its removal after I have a better understanding of your breakage. 

As a recap for this flag: When it is enabled, for a build with a single top-level target, this will guarantee that blaze-bin points to whatever the output directory of that top-level target. If there are multiple top level configurations making the output directories ambiguous it clears the symlinks.

@bolitt setting `--use_top_level_targets_for_symlinks=false` would be a temporary workaround if you want to preserve those symlinks. However, since the flag will be eventually removed and the default behavior would stick, this won't be a long term solution. Is your code somehow dependent on `blaze-bin`?

**Comment by fmeum** [comment]
@aranguyen `tags = ["manual"]` makes it so that the tagged target is not matched by wildcard patterns.

OSS users tend to do `bazel build //...` frequently simply because their repos are small enough that this is feasible. But with targets that self-transition, the new algorithm means that they will essentially always use their convenience symlinks with this pattern.

**Comment by sluongng** [comment]
@aranguyen Here is one of our latest PR where we have to apply @fmeum 's suggested fix to mitigate the issue https://github.com/buildbuddy-io/buildbuddy/pull/3393. This has an obvious downside: these code paths that are marked with `"manual"` tag are excluded from our CI and thus, not verified.

Targets with self-transition are very common in the Go ecosystem: engineers often develop on a MacOS machine and deploy on a Linux environment (as a container via rules_docker's go_image), so it's typical for a Bazel + rules_go setup to use transition to help provide cross-compilation between these environments and architectures.

**Comment by bolitt** [comment]
> Hi all, apologies for the late response. @fmeum I'm not familiar with the manual tag in your fix, could you please help explain its functionality?
> 
> > What is the long-term solution for this flag flip?
> 
> @sluongng Since this flag is enabled by default, the long term goal is to remove it and the current behavior would stick. You also mentioned that this caused breakages, could you please help me with a repro for a known breakage? We can talk more about the current `WARNING` being noisy and perhaps consider its removal after I have a better understanding of your breakage.
> 
> As a recap for this flag: When it is enabled, for a build with a single top-level target, this will guarantee that blaze-bin points to whatever the output directory of that top-level target. If there are multiple top level configurations making the output directories ambiguous it clears the symlinks.
> 
> @bolitt setting `--use_top_level_targets_for_symlinks=false` would be a temporary workaround if you want to preserve those symlinks. However, since the flag will be eventually removed and the default behavior would stick, this won't be a long term solution. Is your code somehow dependent on `blaze-bin`?

I have a bunch of scripts to build and run, like 
```
bazel build //a/b:c
./bazel-bin/a/b/c
```

So my question is: what is the suggested final solution? Only to use OS-dependent command:
 
```
./bazel-out/darwin-opt/bin/a/b/c
```

**Comment by aranguyen** [comment]
Hi all, sorry for the late reply but here are updates from our team on this issue:

- As there is a workaround for this issue, we are going to proceed with the flag removal. However, we also understand your use case and propose to change the behavior of this flag to only clear out convenient symlinks of those that match the top-level configuration. What do you all think of this option?
- We're also not prioritizing this work at the moment but would be open to provide guidance if anyone would like to contribute for this changes.

**Comment by sluongng** [comment]
I would argue that the current workaround is a UX degradation that needs to be addressed. Not quite sure why flag removal is being pushed forward so aggressively while there are unaddressed problems stated here.

Clearing symlink automatically based on top-level target configurations feels "magical" at best and confusing/anti-user at worst. If a big repo has complicated transitions that are used for purposes other than building a binary (i.e. `nogo` used as linter), at least offer an optional API to mark such transition as secondary permanently so related binaries are never included in the symlink.

**Comment by photex** [comment]
I seem to have discovered this as an unfortunate interaction with the CLion plugin.

If I build my target `bazel build //plugin:foo` then I'll have stable output in `bazel-bin`, but if I use the CLion command to "Build Project", bazel will remove these symlinks.

This is really confusing and a bit frustrating because there is already *a lot* to digest with bazels output directory structure, but as a user of a build system who is trying to build a plugin for a host application I really need a way to have a stable output location of the targets I define. 

I don't really mind the details of how that's arrived at, but from the user point of view it should work about as easily as `bazel build //...` creating a folder called `bazel-products` or `bazel-<workspace>/products` and finding everything there.

**Comment by nikhil-marathe-skydio** [comment]
`bazel-testlogs` no longer being reliably available means tooling that builds on this no longer works.
For example, Jenkins has a `junit` function that takes a glob pattern and extracts test failures from the `test.xml` files Bazel produces.

What is the long term solution for these workflows?

**Comment by gregestren** [comment]
Thanks for all this feedback. @fmeum , @aranguyen , and I are currently re-reviewing based on your experiences.

**Comment by gregestren** [comment]
We talked and we'll work on an adjustment from the above feedback. Ball is currently in my court. I'll plan to visit this (ideally with a PR we can review) in June. Feel free to ping if time passes by and you're unsure where things stand.

**Comment by SanjayVas** [comment]
Just to be clear on what expectation I believe that was violated: A workspace dependency should not affect the convenience symlinks.

**Comment by gregestren** [comment]
@SanjayVas can you elaborate more precisely?

**Comment by SanjayVas** [comment]
@gregestren My understanding is that the default behavior change means that transitions can result in the convenience symlinks being cleared. Simply depending on rules from workspaces that use transitions (e.g. [rules_docker](https://github.com/bazelbuild/rules_docker)) can therefore trigger this behavior.

**Comment by gregestren** [comment]
That shouldn't trigger if you're only building the depender. You've noticed otherwise?

**Comment by SanjayVas** [comment]
Simple repo that demonstrates this issue: https://github.com/world-federation-of-advertisers/containers

There are no transitions in this code. Any use of transitions is due to use of rules from the `rules_docker` dependency.

**Comment by gregestren** [comment]
We're aiming to get https://github.com/bazelbuild/bazel/commit/ceb9955cc36e65e48923dbe51437f589ce277eef into Bazel [6.3.0](https://github.com/bazelbuild/bazel/issues/18368), which will be cut on Wednesday.

Note this doesn't guarantee `bazel-bin` always exists. Guaranteeing that is a complicated project, described at https://github.com/bazelbuild/bazel/issues/15005.

But it should remove the 6.0 regression and (I hope) make 6.3.0 a strict improvement over < 6.0.

Appreciate anyone's feedback if you can test the change out.
