### ISSUE TITLE
cc_proto_library doesn't get linked for binary with dynamic_deps

### ISSUE THREAD

**Issue by eagleonhill** [bazelbuild/bazel#17091]
### Description of the bug:

Because `cc_proto_library` doesn't use `deps` for linking dependencies, it's never part of `GraphNodeInfo`.
This happens even the `cc_binary` has empty list of `dynamic_deps`

As a result, https://github.com/bazelbuild/bazel/blob/f79ec3dd9f58905ccbf485d2c3cf28960f9e47ab/src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl#L383 it's not statically nor dynamically linked.

https://github.com/bazelbuild/bazel/blob/f79ec3dd9f58905ccbf485d2c3cf28960f9e47ab/src/main/starlark/builtins_bzl/common/cc/cc_binary.bzl#L393 Such libraries are excluded for build.

I made a local workaround by removing the 2nd term, that assumes all unknown targets are staticaly linked.

### Which operating system are you running Bazel on?

ubuntu

### What is the output of `bazel info release`?

5.2.0

**Comment by eagleonhill** [comment]
Actually, this bug isn't just cc_proto_libray. Using cmake rule from foreign_rules_cc also won't work.

**Comment by sgowroji** [comment]
Hi @eagleonhill, Could you please provide minimal steps to reproduce the above issue. Thanks!

**Comment by oquenchil** [comment]
I am unable to reproduce this for `cc_proto_library`. If you have a `cc_binary` that depends on a `cc_proto_library` whose `proto_library` depends on another one, everything works as expected. The Graph structure aspect is propagated along the edges of the `deps` attribute of the `proto_library` rule (the aspect is applied on the CcProtoAspect aspect itself). So to know exactly what was going on in your case, I'd need a repro.

In any case, the bug report is useful, I can certainly believe this happens to the cmake for foreign_rules_cc. The problem is this PR https://github.com/bazelbuild/bazel/commit/ff927f72644b4d1c3036ea8b3b821c58c34c92fa which was a red-herring and not the actual reason for https://github.com/bazelbuild/bazel/issues/16296#issuecomment-1263395886 . 

We can restore the change that propagated across all attributes. Also the `static_deps` attribute has been removed from the cc_shared_library rule https://github.com/bazelbuild/bazel/commit/9815b76121d4e36bdaae110de7e68131916478ca so everything remaining (not coming from `dynamic_deps`) will be linked statically anyway, we still need to aspect to look at the LINKABLE_MORE_THAN_ONCE hint though. We can even make it more efficient so that propagation only happens when the CcInfo provider is advertised. I will start working on that.

The cmake rule will only have to advertise CcInfo if it doesn't already. There won't be a need for any other hints.

**Comment by oquenchil** [comment]
We can't actually have `required_providers` on the aspect either because of protos and aspects. So it will inefficiently propagate across more than is needed but it will work for all cases.

**Comment by iancha1992** [comment]
@bazel-io fork 6.4.0

**Comment by iancha1992** [comment]
@oquenchil @hvadehra @fmeum We tried to cherry-pick this to release-6.4.0, but there were some conflicts.
1) src/main/starlark/builtins_bzl/common/cc/experimental_cc_shared_library.bzl
Currently, below is missing in the release-6.4.0 branch
```
if hasattr(ctx.rule.attr, "deps") and type(ctx.rule.attr.deps) != "Target":
        for dep in ctx.rule.attr.deps:
            if GraphNodeInfo in dep:
                children.append(dep[GraphNodeInfo])
```

Can you please take a look? Thank you!

cc: @bazelbuild/triage

**Comment by hvadehra** [comment]
cc @buildbreaker2021

**Comment by oquenchil** [comment]
I put everything from head cc_shared_library into 6.3. There have been no changes to cc_shared_library since then.

**Comment by Wyverald** [comment]
Just a heads up that 6.4.0rc1 will be cut next Monday, so this needs to be cherry-picked before then if we want to backport it into 6.4.0.

**Comment by fmeum** [comment]
This was done in https://github.com/bazelbuild/bazel/pull/19534
