### ISSUE TITLE
genrule() should infer tools prerequisites from the command implicitly

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#1721]
The existence of `tools` attribute in `genrule` is violation of DRY principle and is enforcement of WET principle:

```
genrule(
    name = "foo",
    srcs = [":bar"],
    cmd = "$(location :baz) $< $@",
#    tools = [":baz"],
    outs = ["foo.txt"],
)
```

is failing with:

```
ERROR: /home/davido/projects/bazel_test/BUILD:11:11: in cmd attribute of genrule rule //:foo: label '//:baz' in $(location) expression is not a declared prerequisite of this rule.
ERROR: /home/davido/projects/bazel_test/BUILD:11:11: in cmd attribute of genrule rule //:foo: $(location :baz) not defined.
ERROR: Analysis of target '//:foo' failed; build aborted.

```

I'm considering stating the dependency in `location` macro to be "declared prerequisite of this rule". In fact the error message above indicates, that during the analysis phase such prerequisites can be inferred and added to the rule dependency list implicitly. The source `:bar` is added implicitly to the prerequisites of `genrule`, so that the whole construct is not consistent too.

Moreover, `tools` attribute in `genrule` should die, so that i should be able to say just that:

```
genrule(
    name = "foo",
    srcs = [":bar"],
    cmd = "$(location :baz) $< $@",
    outs = ["foo.txt"],
)
```

FWIW, Buck build tool fixed this issue: [1] years ago: [2].

* [1] https://github.com/facebook/buck/issues/128
* [2] https://github.com/facebook/buck/commit/d632c70e2191b25c26c2f86c38165c8c9060f55b

**Comment by ahyangyi** [comment]
I'm not sure if parsing the `cmd` is viable, since bash is Turing-complete and trying to figure out whether a Turing-complete code will or will not call `$(location foo)` is at best an estimation, and such estimation is doomed to confuse the user now and then.

I'm looking at ctx.action and I notice that we have a prettier syntax to run a command, via `executable` and a list of `arguments`. I think it's a cleaner alternative to `cmd` in most situations, and in cases it cannot replace `cmd`, it's usually because said `cmd` calls a system command and then we can't infer implicit dependency of system commands anyway.

**Comment by kchodorow** [comment]
Despite syntactic similarities, Bazel's configuration machinery is somewhat more complicated than Buck's.    Bazel can determine what the dependency is, but not what configuration to build it for.  

For example, let's say I'm building on my Linux box, but I want Bazel to build a Windows .exe.  The _host configuration_ is Linux, the _target configuration_ is Windows.  If you put a target in "tools", it's build for the host configuration (a Linux binary). If you put it in srcs, it'll be built for the target configuration, and then Bazel will try to execute baz.exe on your Linux box and fail.

See also https://bazel.io/versions/master/docs/be/general.html#genrule.tools.
