### ISSUE TITLE
Breaking change to http_archive checksum

### ISSUE THREAD

**Issue by philstahlfeld** [bazelbuild/bazel#17363]
### Description of the bug:

The `http_archive` macro's sha256 implementation seems to have changed in a way that isn't compatible with previous versions. I have several `http_archive`s in my project that had been working for ~6 months and all of a sudden started failing due to the following error: 
```
Step #0: INFO: Repository rules_python instantiated at:
Step #0:   /workspace/WORKSPACE:8:13: in <toplevel>
Step #0: Repository rule http_archive defined at:
Step #0:   /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/http.bzl:355:31: in <toplevel>
Step #0: WARNING: Download from https://github.com/bazelbuild/rules_python/archive/refs/tags/0.10.2.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was c0f20be94f39f4fd28152ba90b47569f26478faf680125185bda0d479e1130b7 but wanted a3a6e99f497be089f81ec082882e40246bfd435f52f4e82f37e89449b04573f6
Step #0: ERROR: An error occurred during the fetch of repository 'rules_python':
Step #0:    Traceback (most recent call last):
Step #0: 	File "/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
Step #0: 		download_info = ctx.download_and_extract(
Step #0: Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/archive/refs/tags/0.10.2.tar.gz] to /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/rules_python/temp2282572248062645828/0.10.2.tar.gz: Checksum was c0f20be94f39f4fd28152ba90b47569f26478faf680125185bda0d479e1130b7 but wanted a3a6e99f497be089f81ec082882e40246bfd435f52f4e82f37e89449b04573f6
Step #0: ERROR: /workspace/WORKSPACE:8:13: fetching http_archive rule //external:rules_python: Traceback (most recent call last):
Step #0: 	File "/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
Step #0: 		download_info = ctx.download_and_extract(
Step #0: Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/archive/refs/tags/0.10.2.tar.gz] to /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/rules_python/temp2282572248062645828/0.10.2.tar.gz: Checksum was c0f20be94f39f4fd28152ba90b47569f26478faf680125185bda0d479e1130b7 but wanted a3a6e99f497be089f81ec082882e40246bfd435f52f4e82f37e89449b04573f6
Step #0: ERROR: no such package '@rules_python//python': java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_python/archive/refs/tags/0.10.2.tar.gz] to /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/external/rules_python/temp2282572248062645828/0.10.2.tar.gz: Checksum was c0f20be94f39f4fd28152ba90b47569f26478faf680125185bda0d479e1130b7 but wanted a3a6e99f497be089f81ec082882e40246bfd435f52f4e82f37e89449b04573f6
```
I've haven't changed the url this rule points at (https://github.com/bazelbuild/rules_python/archive/refs/tags/0.10.2.tar.gz).

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Add the following to a WORKSPACE and try to run `bazel build` on a target.
```
http_archive(
    name = "rules_python",
    sha256 = "a3a6e99f497be089f81ec082882e40246bfd435f52f4e82f37e89449b04573f6",
    strip_prefix = "rules_python-0.10.2",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.10.2.tar.gz",
)
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 6.0.0

**Comment by brentleyjones** [comment]
https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-1409438954

**Comment by sgowroji** [comment]
Hello @philstahlfeld, I could see some of the users are able to work with the git revert changes. Please let us know if you are still seeing the same. Thanks!

**Comment by bscott-zebra** [comment]
The breakage was due to a change in git to use an internal gzip implementation for `git archive gzip` use:
https://github.com/git/git/commit/4f4be00d302bc52d0d9d5a3d4738bb525066c710

For now github has reverted their use of this change (note that github dynamically generates these source archives on-demand...):
https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/

Going forward, it appears a better solution is required, rather than relying upon checking the sha256 of dynamically generated source archives that are not guaranteed to be bit-for-bit identical.  Static copies of source archives should be used instead, where feasible, but perhaps there's an argument for providing a different validation mechanism that may be used, when necessary.

Perhaps some integrity check of the files extracted from an archive, rather than on the archive itself?  A downside to this would be that you may open yourself up to vulnerabilities in archive decompression being exploited by a nefarious actor that can hijack a URL...

Alternatively, maybe some sha256 override file could be provided to bazel that provides a single place to use to provide an alternative list of "good" sha256 values for archives so at least the changes could be addressed in a single place, rather than chasing down all problematic references in historical archives of sub-projects of sub-projects...

**Comment by philstahlfeld** [comment]
> Hello @philstahlfeld, I could see some of the users are able to work with the git revert changes. Please let us know if you are still seeing the same. Thanks!

Everything is working for me now. Thanks for checking!
