### ISSUE TITLE
Root modules should better support multiple Bazel versions

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#17372]
### Description of the feature request:

I want to be able to have a workspace that uses bzlmod support more than a single Bazel version at a time. To do that, there has to be a way for one (or multiple in the case of some sort of conditionals) `bazel_dep` to support multiple `version`s.

### What underlying problem are you trying to solve with this feature?

rules_apple 1.x versions support Bazel 5, while the 2.x versions support Bazel 6, mutually exclusive (can't use 2.x with Bazel 5, can't use 1.x with Bazel 6). rules_apple doesn't adjust it's `compatibility_mode` (and there is a different conversation on if it should), but it does set `bazel_compatibility`. That means that if a root `MODULE.bazel` declares `bazel_dep(name = "rules_apple", version = "1.5.1")` it can only use Bazel 5, and if it declares `bazel_dep(name = "rules_apple", version = "2.0.0")` it can only use Bazel 6.

With WORKSPACE macros one can conditionally load in the version of rules_apple based on Bazel version. We should be able to support the same thing with bzlmod.

One wrinkle is how this impacts the coming lockfile. I think it can encode this conditionality (or however it's implemented) quite easily, as it should only be supported in root `MODULE.bazel` files.

### Any other information, logs, or outputs that you want to share?

https://bazelbuild.slack.com/archives/C014RARENH0/p1675176300407969

**Comment by brentleyjones** [comment]
cc @Wyverald

**Comment by brentleyjones** [comment]
cc @meteorcloudy

**Comment by meteorcloudy** [comment]
I think we all agree that there are two different compatibilities to maintain:

- The compatibility of the APIs exposed by the module to its users. This should be indicated by the `compatibility_level` just like the major version in SemVer. But realistically, this could be both over-constrained and over-promising because users may depend on a subset of APIs or depend on subtle behaviours of the module.
- The compatibility between the module and the APIs exposed by Bazel. This can be specified by the `bazel_compatibility` attribute in MODULE.bazel.

> rules_apple 1.x versions support Bazel 5, while the 2.x versions support Bazel 6

This is not the best practice since it's using the major version number to represent Bazel compatibility. When Bazel 6 is out, if rules_apple 1.5.1 is broken, there should be a minor/patch release for 1.x that's compatible with both Bazel 5 and 6 (e.g. 1.6.0). This way, users can simply upgrade rules_apple to a compatible version (1.x should be backwards compatible), then they can upgrade the Bazel version.

> I want to be able to have a workspace that uses bzlmod support more than a single Bazel version at a time.

I wonder what's the exact reason behind this. Is this for Bazel rules or leaf projects? In general, I feel allowing conditional dependencies based on Bazel version could introduce more problems than benefits, since it not only complicates the lock file support (what if I want it checked in), but could also make it harder to debug your build (you are building different things if you change your Bazel version).

> rules_apple doesn't adjust it's compatibility_mode (and there is a different conversation on if it should), but it does set bazel_compatibility. That means that if a root MODULE.bazel declares bazel_dep(name = "rules_apple", version = "1.5.1") it can only use Bazel 5, and if it declares bazel_dep(name = "rules_apple", version = "2.0.0") it can only use Bazel 6.

In [this doc](https://docs.google.com/document/d/1ReuBBp4EHnsuvcpfXM6ITDmP2lrOu8DGlePMUKvDnXM/edit#), I'm thinking about keeping the bazel compatibility information for each module in its metadata.json file, and later we can use the `bazel mod` command (still WIP) to easily upgrade or downgrade a module to a compatible version or we can suggest what would be a suitable Bazel version for the current build graph.

I think ultimately we want to make it easy for users to choose module version and Bazel version at their desires, and I believe we can do that without allowing Bazel version based conditional dependencies.

**Comment by brentleyjones** [comment]
And it's not possible because there isn't a way to reliable detect Bazel version in Starlark. Something that is quite often asked for, but ultimately shot down.

**Comment by brentleyjones** [comment]
> I wonder what's the exact reason behind this. Is this for Bazel rules or leaf projects?

Mainly Bazel rules. I assume most leaf projects (people's actual apps and whatnot) will have a fixed Bazel version; rules that support multiple Bazel versions will need to be able to run CI against those multiple versions.

**Comment by meteorcloudy** [comment]
Sorry for the late reply..

> Ideally, yes, but in reality, because of the tight integration with the apple/objective-c code inside of Bazel, this isn't possible.

I understand there could be a tight integration with Bazel, but I still don't think it justifies using the major version number to indicate Bazel compatibility.

> And it's not possible because there isn't a way to reliable detect Bazel version in Starlark. Something that is quite often asked for, but ultimately shot down.

Ideally, the rule should branch out to different logics depending on if certain API is available or not, instead of directly checking the Bazel version. /cc @comius is that something we can improve in the Bazel build api?

> rules that support multiple Bazel versions will need to be able to run CI against those multiple versions.

That makes sense, but I think we should make sure the same transitive sources of the rule work for multiple Bazel versions, instead of pushing the branching out logic to dependency resolution level.

**Comment by brentleyjones** [comment]
>  if certain API is available or not

Currently we can use `hasattr` for completely new functions, but when attributes are added or removed we don't have a way to easily check for that.

**Comment by meteorcloudy** [comment]
> but when attributes are added or removed we don't have a way to easily check for that.

That's exactly Xudong told me one hour ago, @comius any idea on how to improve that?

**Comment by Wyverald** [comment]
Maybe we should repurpose this issue into a discussion about how to do feature detection. But leaving it as is for now until someone can find the time to commit to a design.

**Comment by Wyverald** [comment]
The design has been agreed on (https://docs.google.com/document/d/1HJf3gMYIrzmTRqbD4nWXH2eJRHXjLrOU0mmIeZplUzY/edit#heading=h.5mcn15i0e1ch) and the project is being developed at https://github.com/bazel-contrib/bazel_features. Please follow there for updates.
