### ISSUE TITLE
Java executable provided by toolchain breaks dependency analysis

### ISSUE THREAD

**Issue by Ubehebe** [bazelbuild/bazel#17389]
### Description of the bug:

I maintain a few toolchains that expose Java-based tools for rules to use. I recently updated the source code of one of these tools, ran `bazel build ...`, and was surprised that the actions across the repo that used the tool were not rerun.

After some trial and error, I discovered that passing the tool through the toolchain as a FilesToRunProvider instead of a bare executable fixes the problem. This was surprising to me, because the executable param of ctx.actions.run is [documented](https://bazel.build/rules/lib/actions?hl=en#run) to take either a File or FilesToRunProvider.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Minimal repro: https://github.com/Ubehebe/bazel-toolchain-bug

### Which operating system are you running Bazel on?

I reproed this on both MacOS and Linux.

### What is the output of `bazel info release`?

release 6.0.0

### Any other information, logs, or outputs that you want to share?

I think this is a Java-specific bug. I could not repro when I changed the tool to an sh_binary. (I haven't tried other languages yet.)

**Comment by tjgq** [comment]
This is WAI, although admittedly the failure mode is surprising.

`java_binary` doesn't produce a self-contained executable file; the executable is a shell script that expects the runfiles tree to be available. In order to propagate the runfiles tree in addition to the executable, you need to use a `FilesToRunProvider`. A `sh_binary` will work as long as the script doesn't have any dependencies; otherwise it will also break.

The reason you don't usually run into this is that `ctx.actions.(run|run_shell)` will silently promote a bare executable to the corresponding `FilesToRunProvider`, *as long as the executable in question is a direct dependency of the target declaring the action*. Unfortunately, a toolchain adds an extra layer of indirection (action target -> toolchain target -> executable target) which causes the promotion to no longer work.

**Comment by Ubehebe** [comment]
Thanks for the explanation -- it fits the observed behavior perfectly. Changing the source code of the Java tool doesn't change the java_binary wrapper script, so that's why my actions that depended on the bare executable didn't run.

Is this auto-promotion behavior documented anywhere? It's a potentially scary feature, since it can cause actions to effectively be stale. I'm going to audit all my actions that use toolchain tools ASAP.

**Comment by tjgq** [comment]
@Ubehebe do your actions use sandboxing? If so, I would have expected them to fail (instead of silently reading stale files) since the runfiles should be missing from the sandbox entirely.
