### ISSUE TITLE
Why Bazel a crossplatform building tool need mysys2??????

### ISSUE THREAD

**Issue by jinfagang** [bazelbuild/bazel#17419]
### Description of the bug:

I really don't understand, Bazel is sooooo hard to use, why it need mysy2?

Error in fail: BAZEL_SH environment variable is not set

I build any repo tensorflow meidap[ipe got this damn it error on windows.

So confusing.... why it need BAZEL_SH???? AM on on windows!!!

**Comment by sgowroji** [comment]
Hi @jinfagang, Could you please share complete details on your above query. What are the steps you followed and what error you encountered. 

  Bazel requires the MSYS2 environment on Windows because it provides a Unix-like shell environment, which is necessary for running the various Unix tools that Bazel relies on for building software. MSYS2 provides a stable and well-supported environment for running these tools, and ensures that Bazel builds are consistent across different Windows environments.

Thanks !!
