### ISSUE TITLE
args.use_param_file(use_always=True) appears not to work with run_shell under Windows

### ISSUE THREAD

**Issue by ghost** [bazelbuild/bazel#17432]
### Description of the bug:

While testing https://github.com/google/bazel-common/pull/162 on Windows, I discovered that `ctx.actions.run_shell` fails to pass arguments using a paramfile even with `use_param_file("@%s", use_always=True)`. The paramfile is generated on disk, but the command's argv always contains the individual parameters instead of `@path/to/foo-0.params`.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Repro case available here: https://github.com/beasleyr-vmw/repro-bazel-runcommand-useparamfile

It succeeds on Linux but fails on Windows.

### Which operating system are you running Bazel on?

Windows 11 w/ msys2 for Bash

### What is the output of `bazel info release`?

release 6.0.0

### Have you found anything relevant by searching the web?

No.

**Comment by beasleyr-vmw** [comment]
I spent some time tracing Bazel, and this turns out to be a bug/feature of MSYS2/Cygwin described at https://www.cygwin.com/cygwin-ug-net/using-specialnames.html#pathnames-at .

I now wonder whether this should (a) be resolved, (b) turn into a documentation bug/task, or (c) involve a change to the `run_shell` handler to perform additional quoting on Windows. (Regarding (c), I can work around this in Starlark by using `use_param_file("'@%s'", use_always=True)`, but I wonder if Bazel could/should do this implicitly.)

**Comment by comius** [comment]
It would be nice to have proper quoting on Windows and params files work. If I understand this correctly, such a change would be general and not only Cygwin specific.
