### ISSUE TITLE
Windows 10 / MSYS64: frequent "Tools symlink creation failed" while running tests

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#1743]
I started seeing this virtually every time I try to run tests.
Only thing that reliably helps is deleting `C:\tools\msys64\var\tmp\Bazel\MGAgSgPx\execroot\bazel2\_bin`.

```
$ bazel test //src/test/java/com/google/devtools/build/lib:*
ERROR: Tools symlink creation failed: failed to copy 'C:/tools/msys64/var/tmp/_bazel_laszlocsomor/install/7661bc63cf1206fc339d263724ef3d4c/_embedded_binaries/embedded_tools/src/tools/android/java/com/google/devtools/build/android/idlclass/classes_deploy.jar': C:\tools\msys64\var\tmp\Bazel\MGAgSgPx\execroot\bazel2\_bin\classes_deploy.jar (Access is denied).
INFO: Elapsed time: 0.244s
```

**Comment by meteorcloudy** [comment]
I am also getting this error frequently, And I noticed when I get this, there are more than one java.exe process in Windows Task Manager. Killing them also helps. //cc @lberki Do you have any idea why this is happening? Maybe 76b3fb9869af6dac0d872176a2e6aebe55f69c90 ?

**Comment by lberki** [comment]
@meteorcloudy says that these are Bazel server processes, which means that 76b3fb9 is probably not the culprit. I'm guessing some recent change made the detection of an existing server flaky? The file it complains about is the deploy .jar where the code of the Bazel server lives, so I assume this is because a client tries to overwrite it even though another server is still running.

Things to check:
  * Whether the Java processes are actually Bazel servers. If you look at them with Process Explorer or Process Monitor (especially at their open file handles), there should be some clues. 
  * run `blaze version server_pid` in a loop and check what PID is returned or if this triggers the issue. If yes, it's a clear indication that the gRPC protocol is at fault.

**Comment by lberki** [comment]
It would also be possible that `_bin/classes_deploy.jar` is a symlink, and creating it requires write access to the same file in the install directory, but IIRC on Windows, we copy files instead of symlinking, so that shouldn't be a problem.

**Comment by lberki** [comment]
According to @meteorcloudy , we have two files whose basename is `classes_deploy.jar` in the Bazel binary. This is a problem, because this code:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/config/BinTools.java#L134

will try to copy them into the same place, which is obviously a recipe for disaster. I don't know why this surfaced only now, though; those files have been there since a long time. Maybe that file is still used by some other process due to an unrelated bug in process control?
