### ISSUE TITLE
@bazel_tools requires //:license which doesn't work in rules

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#17507]
### Description of the bug:

After this commit https://github.com/bazelbuild/bazel//commit/bd0e3f84a64353c3f32ffd2f07c87884ffd0231c, rules that used action_names.bzl fail with:

```
(20:15:09) ERROR: /private/var/tmp/_bazel_buildkite/4c6321893027bb8685bbe2ce68942c4b/external/bazel_tools/tools/build_defs/cc/BUILD:28:10: every rule of type filegroup implicitly depends upon the target '@bazel_tools//:license', but this target could not be found because of: no such package '@bazel_tools//': BUILD file not found in directory '' of external repository @bazel_tools. Add a BUILD file to a directory to mark it as a package.
```

https://buildkite.com/bazel/rules-apple-darwin/builds/6686#0186566e-f571-40a7-a10b-540d1142b1f5

**Comment by aiuto** [comment]
The root cause is a Google internal change where we are making sure all third_party code in our repository has proper license attestations. 
- @teeler did the original change
- @meteorcloudy may be able to help

I am OOO on vacation, but can probably consult on this sporadically.  My suggestions.

1. revert the license addition changes. We can do that most easily from the google side.
2. The bazel team will have to take over the roll forward of the original change.
3. We can update the copybara rules to strip default_applicable_licensees from most of the files on the export to github.

**Comment by keith** [comment]
@aiuto are you back, maybe you can push this one 🙃

**Comment by aiuto** [comment]
Not back until next week. Option 3 from my comment last week is the best solution. @meteorcloudy's team could do that independently of my involvment.

**Comment by meteorcloudy** [comment]
OK, I'm rolling back the original change first.

**Comment by meteorcloudy** [comment]
Rollbacked in https://github.com/bazelbuild/bazel/commit/cd620ddf8e1132252ab36e8be45e50ca311bdda8, not sure why the commit message is missing.
