### ISSUE TITLE
Cquery output is inconsistent

### ISSUE THREAD

**Issue by nikhilkalige** [bazelbuild/bazel#17523]
### Description of the bug:

I am trying to run `cquery let targets = //board/... in $target except attr("tags", "manual", $target)`. `board` has multiple targets, all but 4 targets  are tagged `manual`. `board` target applies a transition to a different platform and hence the rest of the helper targets are `manual`.

So, here are the outputs I get
```
# CUSTOM_FILTER=let targets = //board/... in $target except attr("tags", "manual", $target)`

1. query //board/... -> 52 targets ✔️ 
2. query CUSTOM_FILTER -> 4 targets ✔️ 
# Duplicated targets due to host & target configurations, but fails to complete for 6 targets due to different platform errors
3. cquery //board/... -> 109 targets
# List's manual targets too, but suprisingly doesn't fail like 3
4. cquery //board/... --nobuild_manual_tests -> 109 
5. cquery CUSTOM_FILTER -> (throws an error like 3)
6. cquery CUSTOM_FILTER -k -> 4 target (This matches the expected result as query, but shows the same error as 3)
7. cquery CUSTOM_FILTER --nobuild_manual_tests -> 4 targets ✔️ 
```

Observations:
- cquery runs the `let` pattern, and then runs the `attr` filter, so filter doesn't make a difference if the pattern already crashes. Does it make sense to do this similar to how query does, and then pass the result to the build request.
- `build_manual_tests` option which is enabled by default for cquery, does not seem to differentiate between build/test targets when it does the filtering.

### Which operating system are you running Bazel on?
Ubuntu 22.04
### What is the output of `bazel info release`?
7.0.0-pre.20230123.5

**Comment by nikhilkalige** [comment]
Closely related https://github.com/bazelbuild/bazel/issues/11222

**Comment by gregestren** [comment]
@nikhilkalige does this also happen with `query`? Or just `cquery`?

**Comment by nikhilkalige** [comment]
@gregestren Just for cquery.

**Comment by gregestren** [comment]
Broadly, I'm not sure how straightforward it's going to be to get cquery to act like query. Particularly because they run on totally different engines. cquery actually runs the build - minus action execution. query has its own custom logic to approximate what the build graph would look like. So they fundamentally evaluate their expressions differently.

It looks like you're saying `--nobuild_manual_tests` is key to avoiding the failures, and therefore getting correct results.

I suspect it's going to be hard to get clean results as long as the "build" fails.

**Comment by gregestren** [comment]
Would setting [`target_compatible_with`](https://bazel.build/extending/platforms#skipping-incompatible-targets) help with the failures?
