### ISSUE TITLE
cc_inc_library contents stale

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazel#1778]
```
$ cat BUILD
cc_inc_library(name="hdrs", hdrs=["foo.h", "bar.h"])
cc_binary(name="prog", srcs=["foo.c"], deps=[":hdrs"]) # includes both foo.h and bar.h via <>
$ bazel build :prog
...
$ cat BUILD
cc_inc_library(name="hdrs", hdrs=["foo.h"])
cc_inc_library(name="bar_hdrs", hdrs=["bar.h"])
cc_binary(name="prog", srcs=["foo.c"], deps=[":hdrs", ":bar_hdrs"])
$ bazel build --spawn_strategy=standalone :prog
this rule is missing dependency declarations for the following files included by 'foo.c':
  'bazel-out/local-fastbuild/include/_/hdrs/bar.h'.
Target //:prog failed to build
```
Bazel fails to remove now stale links due to modifications to the hdrs of :hdrs, and with `--spawn_strategy=standalone`, this deps order-dependent stale artifact is seen - flipping the order presumably changes the include chain and the compiler sees the bar_hdrs path providing bar.h.  The disparity between the manifest of hdrs and the contents of its include directory persists until a clean occurs.

**Comment by laszlocsomor** [comment]
@calpeyser - are you currently working on C++?

**Comment by laszlocsomor** [comment]
@philwo - On second thought, this looks like an issue with `--spawn_strategy=standalone` because it works with the default spawn strategy. Do you know what could be going on?

**Comment by philwo** [comment]
I don't think it can be an issue with the standalone strategy, because the standalone strategy basically just executes a command and does nothing else (like cleaning up, sandboxing, etc.), which is ok, because it isn't supposed to do so. :)

The contract within Bazel is that:
- Skyframe promises to an action (and its executing strategy) that the input files of the action will be there (no missing files, no dangling symlinks), the declared output files of that action will not be there (if they existed from an earlier build, they will be deleted by Skyframe).
- The SpawnActionContext promises to Skyframe that after the action ran the declared output files will be there. If they're not there, Skyframe aborts the build.

(At least this is my understanding :))

The reason why it probably works with the sandboxed strategy is that the stale links are not put into the sandbox, so the action doesn't see them (so it looks as if everything is fine). But if you'd check the execroot, you'd probably see that the stale links are still there.

If Bazel is supposed to clean these up, and I think it should, the SpawnActionContexts are not the droids we are looking for :D I'm not sure which part of the code is supposed to do this, but maybe this one? https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skyframe/SkyframeActionExecutor.java#L697

**Comment by werkt** [comment]
I will post a PR for review on my solution to this - I did the work in the symlink action (and added tests to that effect), additionally specifying the includePath domain to the action, cleaning up anything that was not in the manifest to be symlinked.

**Comment by laszlocsomor** [comment]
@philwo Thanks for the detailed analysis!
@werkt Thanks for the PR! Let me pull in the experts of this domain :)

**Comment by laszlocsomor** [comment]
@janakdr Could you please look at PR https://github.com/bazelbuild/bazel/pull/1810 to see if that's the right way to solve this issue? I'm wondering (though doubt it) if this bug signals a deeper problem in Skyframe, or indeed just a problem with SymlinkAction.

**Comment by janakdr** [comment]
Thanks for the report. This is indeed an issue. However, I'm not sure what the principled fix is. I can create the same issue with a genrule that creates headers:
```
$ cat BUILD
genrule(name = 'make_headers', outs = ['foo.h', 'bar.h'], cmd = 'touch $(OUTS)')
cc_library(name = 'foo', srcs = ['foo.cc', 'make_headers'])
$ cat foo.cc
#include "foo.h"
#include "bar.h"
$ bazel build //:foo --spawn_strategy=standalone
# succeeds
$cat bar/BUILD
cc_library(name = "bar", includes = ["."], srcs = ['bar.h'], visibility = ["//visibility:public"])
$cat BUILD
genrule(name = 'make_headers', outs = ['foo.h'], cmd = 'touch $(OUTS)')
cc_library(name = 'foo', srcs = ['foo.cc', 'make_headers'], deps = ['//bar:bar'])
$ bazel build //:foo --spawn_strategy=standalone
...
ERROR: /Users/janakr/bazel/BUILD:4:1: undeclared inclusion(s) in rule '//:foo':
this rule is missing dependency declarations for the following files included by 'foo.cc':
  'bazel-out/local-fastbuild/genfiles/bar.h'.
Target //:foo failed to build
```
Admittedly, this situation may be less common than the cc_inc_library case, especially because of the use of the discouraged (at least by me) "includes" attribute in //bar:bar.

An aside as to why the normal Blaze mechanisms for clearing outputs don't work: cc_inc_library creates one action per file that it has to symlink. When the library is changed to no longer generate bar.h, the bar.h symlink action isn't created, and so there's no action that thinks it has to delete bar.h beforehand.

Long-term, I think the solution to this is to ensure that every action outputs its files to a unique directory. Then we can unconditionally delete that directory before every execution, which guarantees no stale files like this. Since cc_inc_library already has a unique directory, I think the easy solution is to delete that directory in Action#prepare. I'll put together a change for that and see how it goes.

**Comment by werkt** [comment]
So I (and most of !google) don't know what 'normal Blaze mechanisms for clearing outputs' are, but unless they're different than Bazel, there's only one action for all symlinks under a cc_inc_library.

The long term solution is fine, but will have exactly the same complexity as syncing inc dir contents with the map from my PR (a little more in fact, with the deletion of valid links), but obviously has the benefit of being able to run in parallel with the symlink action with a rename (though not if you put it in Action#prepare).

**Comment by janakdr** [comment]
Sorry, that part of my response was incorrect (noted during my writing, but
forgot to change it). The normal mechanism is AbstractAction#prepare. I
think it makes more sense to delete the directory during #prepare than try
to delete every file individually during action execution. Will send out a
commit soon.

**Comment by janakdr** [comment]
Sent out https://bazel-review.googlesource.com/#/c/6250. @werkt: not sure how to add you as reviewer, but please add yourself!
