### ISSUE TITLE
Bzlmod: Help Keep Modules Up to Date

### ISSUE THREAD

**Issue by cpsauer** [bazelbuild/bazel#17981]
Hi wonderful Bazelers,

First and foremost, thanks for all the great work you do :)

**Summary**: Opportunity for Bzlmod to help keep users and module metadata up to date, which seems important for a distribution mechanism/package manager.

**Context**: I was just pondering adding bzlmod support for the rules I help maintain, and ended up temporarily holding, on two distribution concerns, so I figured I should write in.

1) **Primary need**: Helping users stay on the latest published version of a module. 
  **Feature request**: Could bzlmod prompt people about out-of-date modules and help them upgrade?
  **Why it's worthwhile for users**: Without automated help, people fall behind, incur manual work, and experience fixed bugs and security issues. Think about pre-bazelisk Bazel.
  **Why it's important for our rules**: To keep people up to date, we currently rely on recommending Renovate, [which doesn't support bzlmod just yet](https://github.com/renovatebot/renovate/issues/13658). (Renovate auto-files PRs about updates.) Update prompts are such a win that I think we personally wouldn't happily switch to bzlmod until Renovate supports or bzlmod has update prompts. I'm pretty sure I remember @alexeagle saying that official bazel repos use Renovate, too. 
 **Sketch of feature:** By default, print warning messages for out of date modules on build, silenceable via a "pin" attribute. Add a `bazel upgrade` command that auto resolves those warnings. Add a bazel flag, addable to .bazelrc, that auto upgrades before building, printing a message about upgraded packages. (This seems preferable to, say, setting the version to "latest", like .bazelversion, given Bazel's embodied preference for reproducibility.)
2) **Secondary need**: Help packages stay up to date.
  **Feature request**: Have the registry auto-track GitHub repos.
  **Why it's worthwhile for users**: Modules are more likely to stay up to date, available for use.
  **Why it's important for rules**: Living at head, abseil-style, or quickly publishing tagged releases on GitHub is very convenient as a rules author. This would automate the busy work for those authors, letting them focus more on great features, and automate central registry PR approval work. It would also greatly help the case where you're convincing a repo to support Bazel as a secondary build system, increasing the bazel ecosystem.
 **Sketch of feature:** Perhaps a bot auto-updates the central registry, given a different metadata type, for flexibility, rather than having bazel interpret a different metadata type.

Thanks again,
Chris
(ex-Googler, rules_boost collaborator, [compile_commands_extractor](https://github.com/hedronvision/bazel-compile-commands-extractor) author, etc.)

[If this is already planned...or worse, exists and I've missed it, I apologize and ask for your patience.]

**Comment by alexeagle** [comment]
For 1  - that Renovate PR now has a committed contributor https://github.com/renovatebot/renovate/issues/13658#issuecomment-1496584817 so assuming that goes well, it will have the feature to send upgrade PRs.
I would also like to see an `update` workflow baked more into the Bazel CLI. However as Google doesn't use bzlmod internally, it's hard to get anyone to review a design or PRs. I've been planning for the https://github.com/aspect-build/aspect-cli to grow that sort of feature instead.

For 2 - the "well-maintained" rulesets I know of are using https://github.com/bazel-contrib/publish-to-bcr so that releases are automatically mirrored to the central registry. For example, the rules-template sets up a ruleset so that you merely push a tag to the repo, then everything else is automated with GitHub Actions: https://github.com/bazel-contrib/rules-template/tree/main/.bcr

**Comment by cpsauer** [comment]
Thanks for being great as usual, @alexeagle :)
[With you on both. I was just thinking there might be ways to make things even better if the folks creating bzlmod for the community were game to pick the low hanging fruit here, ripened by bzlmod's version understanding and registry. I'm hoping they'll positively surprise those expectations!]

**Comment by Wyverald** [comment]
> I would also like to see an `update` workflow baked more into the Bazel CLI. However as Google doesn't use bzlmod internally, it's hard to get anyone to review a design or PRs.

Have you tried? :P I've made sure to allocate a fair amount of my time to review community designs around Bzlmod. A `bazel mod upgrade` command sounds very much like a good addition.

---

For 1, I don't think warning by default is a good choice. The need to stay on the latest version is often at odds with the need for reproducible builds. As @cgrindel is already working on renovate+Bzlmod, and `bazel mod upgrade` is on our radar, I'd consider this point addressed.

For 2, publish_to_bcr should cover all your needs there.

So I'll go ahead and mark this as fixed. Please reopen if you have further concerns.

**Comment by cpsauer** [comment]
Thanks for taking the time to reply, Xùdōng.

I'd love to track the `bazel mod upgrade` somehow. Is there an issue 
 you all are already using to track it that we could follow? (If not and you want to use this one, I think only you have the power to reopen, since you closed.)


Some other quick thoughts back:
For (2): My read is that publish_to_bcr works for the tags case, but perhaps not for the (widely used) live-at-HEAD case, also championed also by google repos like abseil? You guys are much closer to this than I am, but it seems like a repo-level whitelist, like proposed above, might save you all a lot of central registry PR approval work in those cases?
For (1): I'm missing how auto-informing folks about newer versions is at odds with reproducibility, given specified versions (presumably checked into source control)? I'm certainly down to get my update notifications from Renovate; I just think most users will fall way behind on updates and security improvements unless batteries are included.

Thanks!
Chris

**Comment by cpsauer** [comment]
@Wyverald, wanted to gently resurface the above, especially now that bzlmod is on in the latest rolling.

**Comment by Wyverald** [comment]
My stance on this hasn't really changed.

For 1: auto-informing itself doesn't interfere with reproducibility. It's the idea that one could just say `version="latest"` or some such that is problematic (and that is a case that we're unlikely to support any time soon, if ever). Renovate now does have Bzlmod support since Chuck's work finished. The point of contention then seems to be whether Bazel itself should auto-inform, to be "batteries included"; I'm not convinced it should, but perhaps a community discussion could change that opinion.

For 2: The live-at-head model doesn't work well with MVS (which Bzlmod uses), at least not without a `version="latest"`-esque setting (which, see above), or flooding the registry with versions on each commit. Neither seems great. If we just get these live-at-head projects to publish new versions at regular intervals (say daily or weekly), Renovate could cover the use case.

**Comment by cpsauer** [comment]
Thanks for taking the time to update, Xùdōng! Really appreciate it--and all your efforts.

(I ofc would still advocate for including those batteries, but am personally using Renovate, and it is, of course, your call.)

On the other, got it; makes sense. If you ever see good automation for that auto-releasing, perhaps for abseil (which seems to have fallen behind rather than do it), and think of this and me, I'd love it if you'd give me a heads up, and we'll adopt in the rules we provide people. (I think many projects that want the low friction model would average pushing commits < 1/wk, but that it'd enable many, many more of them.)

As a semi-related thing: I know some folks tried to add rules_boost to the registry and gave up. Figured you might want a heads up in case it was of interest to you in encouraging adoption. https://github.com/nelhage/rules_boost/pull/482

Thanks again for all you do!
Chris
