### ISSUE TITLE
Python providers loaded during workspace fail due to stub provider

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#18131]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2967#01879289-b1c2-48af-a43c-0e8961a8618d

```
"py2_runtime": attr.label(
Error in label: Illegal argument: element in 'providers' is of unexpected type. Either all elements should be providers, or all elements should be lists of providers, but got an element of type Provider. 
```

Culprit finder:  https://buildkite.com/bazel/culprit-finder/builds/5297#0187928b-2541-4ce6-9235-e674cb8b496e
Bisect shows https://github.com/bazelbuild/bazel/commit/18aeb52a59e65efcbeac7041faf60d81f9d434cb is the culprit

@rickeylev
Could you please guide whether this is a bug to be fixed in Bazel or the downstream project (Bazel bench) should adapt this change.

CC @meteorcloudy

**Comment by fmeum** [comment]
Could be worth trying whether https://github.com/bazelbuild/bazel/pull/18022 fixes this breakage.

**Comment by rickeylev** [comment]
Does that build have this commit? https://github.com/bazelbuild/bazel/commit/4392eb678c4444f52b3f6fc3cbce87d622f777f8

When rewriting the first couple providers in Starlark, I initially put None as their value. A couple days later, #17713 was pointed out to me, so I changed None to `new ProviderStub()`, as done in https://github.com/bazelbuild/bazel/commit/e2d406c0eb8b6ec489cfe4dc2a7bf124a364da72 for ProtoLibrary

The error message says "but got an element of type Provider" instead of "NoneType". So this would lead me to believe "fix" commit is present, but that work around isn't working for this case for some reason. Maybe because it's used as part of toolchain rules? Which usually have more setup/usage during WORKSPACE evaluation.

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2967 indicates Bazel was built at https://github.com/bazelbuild/bazel/commit/5848524ec9133e11f90cea13702dfdad813ae7a6 which is after https://github.com/bazelbuild/bazel/commit/4392eb678c4444f52b3f6fc3cbce87d622f777f8

**Comment by meteorcloudy** [comment]
@sgowroji Maybe it's also help to give a few commands to reproduce this failure? I know it's not hard to figure it out from the build log, but having that directly in the issue would help people to diagnose the problem.

**Comment by sgowroji** [comment]
Please find the below steps to reproduce the above error :

1. git clone https://github.com/bazelbuild/bazel-bench.git
2. cd bazel-bench
3. git reset f525eb78939c139df53c8e77b8f680f1ea96a2ab --hard
4. export USE_BAZEL_VERSION=5848524ec9133e11f90cea13702dfdad813ae7a6
5. bazel build //...

**Comment by rickeylev** [comment]
I think part of the problem is that ProviderStub implements ProviderApi, but the attribute validation code (in StarlarkAttrModule) requires them to be instances of Provider (which extends ProviderApi).

I would expect the ProtoLibrary change to also have this problem? But it seems to have worked in that case.

TBH I don't see how the ProviderStub workaround could have worked at all -- subsequent code casts to Provider and asks for its provider key, which couldn't work with a stub implementation of just ProviderApi.

I'll try implementing a stub provider that, extends Provider. I'm uncertain if this will work, though, because a fake provider key ill be returned, which, if that is getting stored in the rule def (why wouldn't it?), would then mean the rule requires a provider that can't be satisfied. (If so, maybe I can make the fake key refer to the real provider location or something, we'll see).

/cc @comius because he did the workaround for ProtoLibrary, which doesn't seem to be working in this case.

**Comment by rickeylev** [comment]
Ok, I think I understand now. During workspace evaluation, the various bzl files get loaded, rules get defined, and the regular validation logic is run. However, all that work is largely thrown away because, when the regular loading phase occurs, all those bzl files get re-evaluated and the rules re-defined (but this time with the builtins injected).

During the workspace phase, we just have to get past validation; the particular object (or the provider key it represents) used doesn't matter because its thrown away. I'll cleanup the fake Provider-derived class and send out a change.

**Comment by comius** [comment]
Sorry for the confusion, ProviderStub didn't fix the issue with proto_library, because as Richard said is not derived from Provider class.

https://github.com/bazelbuild/bazel/pull/18022 should fix it though.

**Comment by rickeylev** [comment]
Yes, that fixes it. Thanks, Ivo!
