### ISSUE TITLE
Feature request: Allow a list of external URLs to fetch remote repositories

### ISSUE THREAD

**Issue by vrv** [bazelbuild/bazel#1814]
See https://github.com/tensorflow/tensorflow/issues/67#issuecomment-248797048 for details, but the basic idea would be to allow for a list of external sources to fetch remote repositories from.

Background: TensorFlow would love to host code (via http_archive, for example) to minimize the number of external servers that need to be contacted for its dependencies when building.  However, the sources we control are typically firewalled in China, so we have currently found external sources that are available in China.  Unfortunately, with multiple external servers, the chances of one being unavailable can be high.

It would be ideal to provide a list of sources to fetch from, and have bazel try them in some order before failing.  That way we can provide our own copies for the common case, as well as other sources if they are not available in some countries or if the servers are down.

cc: @jart @gunan @martinwicke @damienmg

**Comment by jart** [comment]
Copying my comment from https://github.com/tensorflow/tensorflow/issues/67#issuecomment-248809632

> @vrv @damienmg Does [repository_ctx.download](https://www.bazel.io/versions/master/docs/skylark/lib/repository_ctx.html#download) throw an exception when a download fails? Because then we could write our own custom repository rule that has failover.
> 
> But to be honest, I would rather just mirror the files to a server that works everywhere in the world, including China. I think I figured out how to do this with Google's production environment. So I'm going to be looking into that.

**Comment by laszlocsomor** [comment]
> @vrv @damienmg Does repository_ctx.download throw an exception when a download fails? 

@jart : I haven't tried, but reading the code indicates that it does:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/skylark/SkylarkRepositoryContext.java#L494

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/repository/downloader/HttpDownloader.java#L108

> But to be honest, I would rather just (...) So I'm going to be looking into that.

Shall I assign this bug to you?

**Comment by jart** [comment]
It looks like the transient exception thing tells the downloader to just retry immediately, correct? That doesn't help if GitHub or SourceForge goes down for a few hours. 

You can assign the issue to me if you want. But that might give people the impression that I'm coding this feature request into Bazel. When in reality, what I'd be doing is setting up a better mirror than GCS and then sending pull requests out to all the Bazel rules projects updating their dependencies.

**Comment by laszlocsomor** [comment]
> It looks like the transient exception thing tells the downloader to just retry immediately, correct? That doesn't help if GitHub or SourceForge goes down for a few hours.

Not immediately, only upon the next build/fetch/etc.

> You can assign the issue to me if you want. But that might give people the impression that I'm coding this feature request into Bazel. When in reality, what I'd be doing is setting up a better mirror than GCS and then sending pull requests out to all the Bazel rules projects updating their dependencies.

Thanks, that makes sense. I'l leave it unassigned then.

**Comment by laszlocsomor** [comment]
Pulling in @kchodorow in case she has any comments about this FR.

**Comment by kchodorow** [comment]
This has come up before: people want to be able to switch on where dependencies come from (e.g., a local server for development, the filesystem for CI, a different mirror while in China, whatever).

I circulated a design doc a couple months ago about allowing mapping repo names to different resolvers (e.g., being able to customize how @foo is looked up), but the reviewers didn't like the idea much and for now, users seem to be making do with workarounds.

**Comment by jart** [comment]
Does TensorFlow honor the HTTP_PROXY environment variable?

**Comment by jart** [comment]
Does Bazel honor the HTTP_PROXY environment variable?

**Comment by kchodorow** [comment]
Anything that goes through HttpDownloader (http_* and Skylark download()) respects HTTP_PROXY. git_repository and maven_jar do not, IIRC.

**Comment by ChadTaljaardt** [comment]
Im getting this issue too, i'm not behind any proxies or anything though?

**Comment by bennetyee** [comment]
It would be nice to be able to administratively provide a list of (local) mirrors. That way, business continuity risks can be addressed: any remote repo that might disappear and thus make building impossible because of the lack of an SLA could be mirrored. NB: ideally this is not a per sub-repo decision since where to mirror and what to mirror is a top-level project decision, and a top-level configuration file that allows specifying mirrors would allow the use of unchanged git submodules.

**Comment by jart** [comment]
Good news: We've written a change internally that's currently being reviewed. It's going to fix this issue. That change also comes in addition to the amazing reliability improvements offered by https://github.com/bazelbuild/bazel/commit/4c67807964e37cfd55bbcda4c6374fcc480bcecc. The way it's going to work is all the workspace rules are now going to have a `urls` attribute instead of a `url` attribute. Although the latter will remain around to maintain backwards compatibility.

@bennetyee Right now we're of the opinion that this is a per-rule decision. We believe that Bazel builds should be reliable for *everyone*. For example, if a user downloads TensorFlow, or depends on rules_closure, then we don't want him to have to configure a mirror server in order to get reliability. We're going to modify every project so every download rule has mirrors so continuity risks are addressed at all layers of the stack. Organizations wishing to add an additional layer of reliability can set up a caching squid proxy and configure it via the HTTP_PROXY environment variable.

**Comment by bennetyee** [comment]
@jart if a random open-source project decides to use bazel to build their code and bazel doesn't depend on it (and why would it?), the bazel team is not going to find it and start mirroring their code, is it?  But maybe a proxy can be made clever enough to recover build dependency information and to set up mirrors; that seems to be a complex solution, at first glance, but maybe it'll grow on me.

**Comment by jart** [comment]
Bazel will not mirror files automatically as a service. The duty is going to fall on every Bazel user who wants to be a good citizen to [mirror his or her own files](https://github.com/bazelbuild/rules_closure/blob/master/closure/repositories.bzl#L136) on a GCS bucket (or whatever CDN is preferred.) The Bazel team has already created `bazel-mirror.storage.googleapis.com` which is used to mirror external files for all core Bazel projects. We're going to be posting blog posts about this best practice in the future and doing everything within our power to make sure this best practice is followed, in order to mitigate tragedy of the commons.

As I mentioned earlier, enterprises will not need to rely on upstream projects to do the right thing. A squid proxy can be configured regardless and Bazel will hit that proxy with exponential backoff retries. There's going to be so many layers of reliability with downloads in the future that you're just not going to believe it.

**Comment by bennetyee** [comment]
if git_repository and maven_jar does not respect HTTP_PROXY as @kchodorow said, then it seems to be an incomplete solution.

@jart I'm sorry i wasn't writing as clearly as i should have. I was saying that I *don't* expect bazel to provide mirroring as a service, and so for bazel---or any other "top level" project---to ensure reliability via SLAs or other mechanisms is a messy problem.  In particular, if a top level project decides it has a certain reliability requirement but an underlying library that it wishes to rely on has a different, lower reliability requirement, then either the top level project has to do something hacky (and incomplete) like HTTP_PROXYing suggested above, or somehow convince the libraries to (transitively) push reliability requirements to the leaf projects.  In essense, all libraries will eventually get pushed to provide the best SLA possible.  and i think this is bad for the ecosystem, since not all 3rd party libraries are created by people with the resources needed to do this. is it the case that there are enough free hosting services with high SLA that this is not in practice a worry?

**Comment by jart** [comment]
The reliability of maven_jar() was greatly enhanced by https://github.com/bazelbuild/bazel/commit/4c67807964e37cfd55bbcda4c6374fcc480bcecc. However it was not updated to support multiple URLs, and probably won't be. This is because maven_jar() is going to be soft deprecated soon in favor of [java_import_external](https://gist.github.com/jart/70bdc88e662a5078a7d8682e5411ae8c). That Skylark rule replacement is going to be committed to the repository soon. But you can actually start using it today.

**Comment by jart** [comment]
When it comes to reliability requirements, one thing to remember is that bazel provides an escape hatch if libraries weren't able to devote the resources to do mirroring. For example, let's assume Closure Rules' [repositories.bzl](https://github.com/bazelbuild/rules_closure/blob/master/closure/repositories.bzl) pointed to a lot of unreliable mirrors. I could just copy that file into my codebase and define those maven dependencies on my own, while still referencing the project.
