### ISSUE TITLE
java_proto_library failed

### ISSUE THREAD

**Issue by is03wlei** [bazelbuild/bazel#1817]
proto_library(
    name = "coord_proto",
    srcs = ["coord.proto"],
)

java_proto_library(
    name = "coord_proto_lib",
    deps = [":coord_proto"],
)

 every rule of type java_proto_library implicitly depends upon the target '//third_party/protobuf:protobuf', but this target could not be found because of: no such package 'third_party/protobuf': BUILD file not found on package path.

**Comment by laszlocsomor** [comment]
Which version of bazel are you using?
Which commit of https://github.com/bazelbuild/bazel/ do you have checked out?

I just built bazel at https://github.com/bazelbuild/bazel/commit/33ad37612ab7edc32d5e82c3912acebacaef42dc then used that binary to build your example and suceeded.

**Comment by pcj** [comment]
@laszlocsomor are you building within bazel's `WORKSPACE`, or from a different `WORKSPACE` outside of the bazel repo dir that calls `java_proto_library`?  

I've always seen this same behavior and assumed that one has to setup the third_party directory to match bazel's expectations in each project.  If not, it could be a `Label(relative_to_caller_repository)` issue.

@is03wlei You can also use https://github.com/pubref/rules_protobuf/tree/master/java#java_proto_library.

**Comment by laszlocsomor** [comment]
@pcj: yes, inside bazel's own workspace, with a stock `WORKSPACE` file in a clean checkout

**Comment by laszlocsomor** [comment]
```
$ cat foo/BUILD
proto_library(
    name = "coord_proto",
    srcs = ["coord.proto"],
)

java_proto_library(
    name = "coord_proto_lib",
    deps = [":coord_proto"],
)


$ cat foo/coord.proto 
syntax = "proto2";

package foo;

message A {
  optional int32 hello = 1;
}


$ bazel query foo:*
//foo:coord_proto_lib
//foo:coord_proto
//foo:coord.proto
//foo:BUILD


$ bazel build foo:all
INFO: Analysed 2 targets.
INFO: Found 2 targets...
INFO: Elapsed time: 0.137s, Critical Path: 0.00s
INFO: Build completed successfully, 1 total action
```

**Comment by pcj** [comment]
Looks like it's working for you, but within bazel itself (?).  What happens if you:

```
$ mkdir test-project
$ cd test-project
$ touch WORKSPACE 
$ mkdir bar/ && cp ~/path/to/foo/coord.proto ~/path/to/foo/BUILD bar/
$ bazel build bar:coord_proto_lib
$ find bazel-genfiles/bar
```

**Comment by laszlocsomor** [comment]
@pcj : In this case the build fails, because the workspace is empty and missing the necessary tools. Do you think this is broken? Do you think `proto_library` should have the [implicit dependency](https://github.com/bazelbuild/bazel/blob/75f367c6b5f26244777e26134c61f0c26af2549c/src/main/java/com/google/devtools/build/lib/rules/proto/BazelProtoLibraryRule.java#L41) on `@<some_repo>//:protoc` instead?

**Comment by pcj** [comment]
I'm not sure if it's broken or not (I guess it's in the eye of the beholder) but I do think it's confusing for end-users.  

It's not clear (to me) what kind of rule `//third_party/protobuf:protobuf` is supposed to be.  Is this the `protoc` binary, a `cc_library`, a jar, or something else?  In https://github.com/google/protobuf/blob/master/BUILD, it's a `cc_library`.

Perhaps something in `//external:` would be better?  Then at least it's a clear path to `bind()`'ing it in one's workspace.  Or default to providing it in `@bazel_tools//` somewhere?  Or since `google/protobuf` has a good BUILD file (above), maybe just default to that?

**Comment by laszlocsomor** [comment]
@cgrushko to the rescue! :) Please see the previous comment. Could you advise a principled way forward?

**Comment by cgrushko** [comment]
I'm currently introducing a concept of proto-lang toolchains which will hopefully clean this up.
It should land in Bazel HEAD by end of week, I hope.

--------

In the meanwhile, to use java_proto_library, you need 
1. a proto-compiler (e.g., [1])
2. a Java proto-runtime (e.g., :protobuf_java from [2]). The runtime contains base-classes that the generated code depends on.

To point at the compiler, use the `--proto_compiler` flag to point at an executable rule. In Bazel itself, it's a filegroup that points at a regular file. [3]

To point at the runtime, bind the `//external:protobuf/` rule to point at a java_library rule. See Bazel's example [4]

[1] - https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-osx-x86_32.zip
[2] - https://github.com/google/protobuf/releases/download/v3.1.0/protobuf-java-3.1.0.zip
[3] - https://github.com/bazelbuild/bazel/blob/master/third_party/protobuf/3.0.0/BUILD#L21
[4] - https://github.com/bazelbuild/bazel/blob/master/WORKSPACE#L53

**Comment by xfxyjwf** [comment]
I got a working example of java_proto_library after putting protobuf repo at third_party/protobuf and adding a binding for proto java runtime:
https://github.com/xfxyjwf/bazel_proto_examples

Right now protobuf directory has to be at third_party/protobuf because bazel references the protoc as //third_party/protobuf:protoc. There is no way to configure it as far as I know. I think bazel should change this implicit dependency to either "@protobuf//:protoc" or "//external:protoc" so we can configure protobuf dependency in the WORKSPACE file.

Another problem I got into is that the java_proto_library rule doesn't work when you import a proto file from an external repo, such as you will do when using protobuf well-known types. It fails to find the file right now.

**Comment by cgrushko** [comment]
Update: I think this is essentially fixed.

Usage example:

1. Clone protobuf: `git clone https://github.com/google/protobuf.git`. (I committed a diff ~40 minutes ago that you'll need)

2. Create a directory, and put the following files in it -

   WORKSPACE
 
   ```  
   local_repository(
       name = "com_google_protobuf",
       path = "path/to/protobuf",
   )

   local_repository(
       name = "com_google_protobuf_java",
       path = "path/to/protobuf",
   )
   ```

   BUILD

   ```
   proto_library(
       name = "coord_proto",
       srcs = ["coord.proto"],
   )
   
   java_proto_library(
       name = "coord_java_proto",
       deps = [":coord_proto"],
   )
   ```
   
   coord.proto
   
   ```
   syntax = "proto2";
   package foo;
   message A {
     optional int32 hello = 1;
   } 
   ```  

3. Build Bazel from HEAD (sorry...)
4. Profit: `bazel-head build --proto_compiler=@com_google_protobuf//:protoc   :coord_java_proto`


(I plan to make `--proto_compiler` point at `@com_google_protobuf//:protoc` by default, in the future)

~ ~ ~

If you're curious - `java_proto_library` implicitly depends on `@com_google_protobuf_java//:java_toolchain`, which your `WORKSPACE` file points at. That target teaches `java_proto_library` how to call proto-compiler, and how to compile the generated code.

~ ~ ~

If that works, let's close this issue.

**Comment by cgrushko** [comment]
Closing for now, feel free to reopen this issue.
