### ISSUE TITLE
platform_mappings files cannot set build flags

### ISSUE THREAD

**Issue by Colecf** [bazelbuild/bazel#18199]
### Description of the bug:

When trying to set a build flag in a platform_mappings file (using `--//:my_flag="foo"`), bazel gives `ERROR: Unrecognized option: --//:my_flag="foo"`. 

This is something we'd like to use in android until proper new mechanisms are added to manage build settings/flags more easily.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a directory with an empty `WORKSPACE` file, and then these other files:

BUILD:
```
load(":string_flag.bzl", "string_flag")
load(":write_build_setting.bzl", "write_build_setting")

platform(
    name="my_platform",
)

string_flag(
    name = "my_flag",
    build_setting_default = "",
)

write_build_setting(
    name = "top",
    build_setting = ":my_flag",
)
```

platform_mappings:
```
platforms:
    //:my_platform
        --//:my_flag="Hello from platform_mappings!"
```

string_flag.bzl:
```
BuildSettingInfo = provider(
    doc = "A singleton provider that contains the raw value of a build setting",
    fields = {
        "value": "The value of the build setting in the current configuration. " +
                 "This value may come from the command line or an upstream transition, " +
                 "or else it will be the build setting's default.",
    },
)

def _impl(ctx):
    return BuildSettingInfo(value = ctx.build_setting_value)

string_flag = rule(
    implementation = _impl,
    build_setting = config.string(flag = True),
)
```

write_build_setting.bzl:
```
load(":string_flag.bzl", "BuildSettingInfo")

def _impl(ctx):
    out = ctx.actions.declare_file("out.txt")
    ctx.actions.write(out, ctx.attr.build_setting[BuildSettingInfo].value + "\n")
    return [DefaultInfo(files=depset([out]))]

write_build_setting = rule(
    implementation = _impl,
    attrs = {
        "build_setting": attr.label(),
    },
)
```

Then running `bazel build //:top --platforms=//:my_platform && cat bazel-bin/out.txt` will reproduce the error message.

Running `bazel build //:top --//:my_flag="Hello, world!" && cat bazel-bin/out.txt` works just fine though.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

Tested on release 6.1.2 and android's ~month old develepment-built version

**Comment by katre** [comment]
Okay, this is quite the rabbithole. I added some simple tests (see https://github.com/bazelbuild/bazel/pull/18200), and then starting figuring out where to add the support.

It turns out that [`PlatformMappingValue.parse`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/PlatformMappingValue.java?q=symbol%3A%5Cbcom.google.devtools.build.lib.skyframe.PlatformMappingValue.parse%5Cb%20case%3Ayes) creates an [`OptionsParser`](https://cs.opensource.google/bazel/bazel/+/refs/heads/master:src/main/java/com/google/devtools/common/options/OptionsParser.java?q=symbol%3A%5Cbcom.google.devtools.common.options.OptionsParser%5Cb%20case%3Ayes), but what's needed for Starlark option support is a [`StarlarkOptionsParser`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/runtime/StarlarkOptionsParser.java?q=symbol%3A%5Cbcom.google.devtools.build.lib.runtime.StarlarkOptionsParser%5Cb%20case%3Ayes).

Unfortunately, to [create a `StarlarkOptionsParser`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/runtime/StarlarkOptionsParser.java?q=symbol%3A%5Cbcom.google.devtools.build.lib.runtime.StarlarkOptionsParser.newStarlarkOptionsParser%5Cb%20case%3Ayes), you need an instance of `CommandEnvironment` (in order to parse and handle arbitrary targets). There isn't one of these available in `PlatformMappingValue`.

We'd probably need to pre-create the parser and pass it into PlatformMappingFunction, so that PlatformMappingValue could use it.

**Comment by jin** [comment]
@katre checking in, did you make any progress on the StarlarkOptionsParser issue?

**Comment by gregestren** [comment]
I just prototyped a similar approach to what @katre described (except I recreated the parser directly in `PlatformMappingFunction`).

The implementation is way more technically complicated than I think it should be. But that doesn't have to be the user's concern. 

I'll share a WIP PR tomorrow.

**Comment by gregestren** [comment]
Let us know if you need further adjustments..
