### ISSUE TITLE
Improve CC Toolchain Feature Provides functionality

### ISSUE THREAD

**Issue by t-rad679** [bazelbuild/bazel#18386]
### Description of the feature request:

The solution I propose is to allow negating features from the `implies` attribute of toolchain features, but I am open to other solutions.

### What underlying problem are you trying to solve with this feature?

The key purpose of the `provides` attribute of toolchain features is to create a set of mutually exclusive options. There are cases where there is benefit to having a default (i.e., `enabled = True`) and, at the same time, another feature may rely on (i.e., `implies`) a non-default option. This case is currently difficult to handle, as the `implies` attribute does not appear to allow the negation of the default option. The workaround I am using is to negate the feature in a transition, but it would be really nice to be able to handle this straight from the toolchain.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

development version

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

Not entirely sure. Working on the migration of AOSP to Bazel, so we're kinda doing our own thing.

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text

https://github.com/bazelbuild/bazel.git
43306947cc5448df2215ebbb2aa5a5e3c64c754c
43306947cc5448df2215ebbb2aa5a5e3c64c754c
```

### Have you found anything relevant by searching the web?

Not really.

**Comment by limdor** [comment]
I face a similar issue when trying to combine `provides`, `enabled = True`, and `not_features`. I think what I'm trying to do is quite a common use case, maybe I just miss something.

In my case it is a project where it wants to support multiple C++ versions but still wants to set one as a default.
My first approach was:

```
    standard_cpp_14_feature = feature(
        name = "standard_cpp_14",
        enabled = True,
        flag_sets = [
            flag_set(
                actions = all_cpp_compile_actions,
                flag_groups = [flag_group(flags = ["-std=c++14"])],
            ),
        ],
        provides = ["standard_cpp_version"],
    )

    standard_cpp_17_feature = feature(
        name = "standard_cpp_17",
        flag_sets = [
            flag_set(
                actions = all_cpp_compile_actions,
                flag_groups = [flag_group(flags = ["-std=c++17"])],
            ),
        ],
        provides = ["standard_cpp_version"],
    )
```

This works but it is not user friendly, because to build with c++17 needs to negate the c++ 14 feature `--features=standard_cpp_17,-standard_cpp_14`

The next thing I tried was to use the `not_features` but this only applies to the flag and the feature is still provided and because of that they conflict and I would still have to negate the c++14 feature.

```
    standard_cpp_14_feature = feature(
        name = "standard_cpp_14",
        enabled = True,
        flag_sets = [
            flag_set(
                actions = all_cpp_compile_actions,
                flag_groups = [flag_group(flags = ["-std=c++14"])],
                with_features = [
                    with_feature_set(
                        not_features = ["standard_cpp_17"],
                    ),
                ],
            ),
        ],
        provides = ["standard_cpp_version"],
    )

    standard_cpp_17_feature = feature(
        name = "standard_cpp_17",
        flag_sets = [
            flag_set(
                actions = all_cpp_compile_actions,
                flag_groups = [flag_group(flags = ["-std=c++17"])],
            ),
        ],
        provides = ["standard_cpp_version"],
    )
```

**Comment by limdor** [comment]
I withdrawal what I said here:

> This works but it is not user friendly, because to build with c++17 needs to negate the c++ 14 feature --features=standard_cpp_17,-standard_cpp_14

It does not complain about having the 2 features but for whatever reason standard_cpp_14 is applied but not standard_cpp_17.

**Comment by oquenchil** [comment]
> This worked just fine, but we still had to negate the feature we didn't want from a transition, which I find to be a pretty hacky solution. However, it is important to note that, in our case, requirements changed so that this was no longer necessary.

If I understand correctly you had something like this:
```
feature(
    name = A,
    provides = ["X"],
    with_features = [
     with_feature_set(
         features = ['Y'],
         not_features = ['Z'],
    ),
)

feature(
    name = B,
    provides = ["X"],
    with_features = [
     with_feature_set(
         features = ['Z'],
         not_features = ['Y'],
    ),
)
```

If you wanted `A`, you need a transition to negate `Y` (assuming that's the case, omitting that it'd probably be easier to directly enable/disable A and B on the transition), then it makes sense that you have to do that because you cannot have both. This is what it says for `provides` on the docs:
```
Indicates that this feature is one of several mutually exclusive alternate features. For example, all of the sanitizers could specify provides = ["sanitizer"].

This improves error handling by listing the alternatives if the user asks for two or more mutually exclusive features at once.
```
So my understanding is that it exists to help with debugging by triggering an error, it doesn't exist to disambiguate between the two (it can't).

If my two features above are not what you had then please write out an example showing what you had because it's really hard to go from text to actual features.

In any case what Lukacs said `if this feature is enabled, that another must not be` cannot be supported regardless of the syntax you use because it would introduce unresolvable cycles:
```
foo implies bar
bar implies -foo
```

**Comment by limdor** [comment]
> I withdrawal what I said here:
> 
> > This works but it is not user friendly, because to build with c++17 needs to negate the c++ 14 feature --features=standard_cpp_17,-standard_cpp_14
> 
> It does not complain about having the 2 features but for whatever reason standard_cpp_14 is applied but not standard_cpp_17.

Ok, all my reasoning might be wrong. I just realize that when setting feature on command line you cannot pass multiple features comma separated. Unfortunately Bazel does not issue any warning or anything, basically is the same like not passing it at all.

**Comment by limdor** [comment]
> > I withdrawal what I said here:
> > > This works but it is not user friendly, because to build with c++17 needs to negate the c++ 14 feature --features=standard_cpp_17,-standard_cpp_14
> > 
> > 
> > It does not complain about having the 2 features but for whatever reason standard_cpp_14 is applied but not standard_cpp_17.
> 
> Ok, all my reasoning might be wrong. I just realize that when setting feature on command line you cannot pass multiple features comma separated. Unfortunately Bazel does not issue any warning or anything, basically is the same like not passing it at all.

Here I created a bug/feature ticket for this topic #18725 

When I have time I will check if what I said with the provide still applies or everything can be thrown away. Sorry for the misunderstanding and noise.

**Comment by oquenchil** [comment]
No problem. Since we aren't going to go with the feature request here of being able to negatively imply other features I will close this issue.
