### ISSUE TITLE
Do not create runfile trees unnecessarily when building without the bytes

### ISSUE THREAD

**Issue by tjgq** [bazelbuild/bazel#18580]
Currently, `--remote_download_toplevel` causes *all* runfiles symlink trees to be created (not just the top-level ones), while `--remote_download_minimal` implies `--nobuild_runfile_symlinks` and activates a separate code path (see `RunfilesTreeUpdater`) to create input runfiles trees just before local action execution.

Instead, we should:

1. Return true from `RemoteOutputService#canCreateSymlinks` and provide an empty `RemoteOutputService#createSymlinks` implementation; this ensures the runfiles tree is never materialized as a direct result of running the `SymlinkTreeAction`.
2. Have `SpawnRunner#prefetchInputs` create the runfiles tree before local action execution (as is already the case for other local action inputs).
3. Have `AbstractActionInputPrefetcher#finalizeAction` create the runfiles tree for toplevel targets (as is already the case for other top-level outputs).

This would ensure a minimal set of runfile trees is created in all cases, and let us omit `--nobuild_runfile_links` from the expansion of `--remote_download_minimal`.

**Comment by dgoldstein0** [comment]
Hey, is there any ETA here? I see there's a linked PR, wondering when that might be done.  We just ran headfirst into this problem today, trying to add about 100 runfiles-heavy actions to our builds - despite using remote execution & build-without-bytes, we see the runfiles being built locally for the ~100ish actions we've added, and these unnecessary runfiles actions are adding almost 20 minutes to what was previous an 8m bazel build. We would love to see a fix for this as we'd be interested in consuming it ASAP; without a fix or workaround, we'll probably have to do some fairly significant refactoring of our rules to avoid the need for runfiles.

**Comment by fmeum** [comment]
Can you run with `--nobuild_runfile_links`? I'm still working on the linked PR and how to land it eventually, but this area is pretty tricky and we first need to fix some staleness issues.

**Comment by dgoldstein0** [comment]
unfortunately no, we need the final runfiles folder.  If there's a way to tell bazel to *just* make that final runfiles folder we'd be happy to do that.

This problem is showing up most prominently with itest-* commands (https://github.com/dropbox/dbx_build_tools) in combination with remote execution & build without bytes - itest-run/start/reload all use `build` and expect the runfiles folders to be produced from the build they invoke.  We usually expect `bazel build //target` to be the build-subset of `bzl itest-start //target` so it breaks user expectations if we use `--nobuild_runfile_links` just in itest-* commands, and we would probably need to mutate bazel-bin/ to build the symlinks trees ourselves to do that (quite ugly, may have unexpected side effects) or risk breaking tools built on top of this stack that assume the presence of the symlink tree in that location.

any idea how long this PR is going to take? a few days? weeks? months?

**Comment by fmeum** [comment]
I want to get back to it after BazelCon, but it may take some time to get merged into master and then be cherry-picked into 9. 9.1.0 might be possible, but no promises.

**Comment by dgoldstein0** [comment]
ah.  Ok well that makes it a pretty big nonstarter for me to wait for it, "after bazelcon" is already a while for us and we're still on bazel 7, I don't think there's hope of getting to 8 by EoY.  I'll try the route of avoiding the need for more runfiles usage.
