### ISSUE TITLE
[Mirror] JDK19 Linux s390x

### ISSUE THREAD

**Issue by zhengwei143** [bazelbuild/bazel#18692]
### Please list the URLs of the archives you'd like to mirror:

https://github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.2%2B7/OpenJDK19U-jdk_s390x_linux_hotspot_19.0.2_7.tar.gz

**Comment by Pavank1992** [comment]
Please find the below mirror artifact below 

https://mirror.bazel.build/github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.2%2B7/OpenJDK19U-jdk_s390x_linux_hotspot_19.0.2_7.tar.gz

**Comment by zhengwei143** [comment]
Hi, the link seems to be invalid, clicking on the link shows:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

**Comment by Pavank1992** [comment]
Hi @zhengwei143, This is encrypted url, replacing `%` with `%25 ` should work.
please find the link here: https://mirror.bazel.build/github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.2%252B7/OpenJDK19U-jdk_s390x_linux_hotspot_19.0.2_7.tar.gz

**Comment by zhengwei143** [comment]
I see! It works now, thank you! :)

**Comment by coeuvre** [comment]
The original link was normalized, i.e. `jdk-19.0.2+7` is normalized `jdk-19.0.2%2B7`. The mirrored version should provide the same URL instead of normalizing the `%`.

That is, we should provide link `https://mirror.bazel.build/github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.2%2B7/OpenJDK19U-jdk_s390x_linux_hotspot_19.0.2_7.tar.gz` instead of link `https://mirror.bazel.build/github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.2%252B7/OpenJDK19U-jdk_s390x_linux_hotspot_19.0.2_7.tar.gz`.

**Comment by zhengwei143** [comment]
Hi @Pavank1992 @sgowroji, could you have a look at this again? @coeuvre is right that the link should be https://mirror.bazel.build/github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.2%2B7/OpenJDK19U-jdk_s390x_linux_hotspot_19.0.2_7.tar.gz instead since it is already normalized.

Similarly for https://github.com/bazelbuild/bazel/issues/18688. Thank you!

**Comment by keertk** [comment]
@zhengwei143 @coeuvre the right link works now. Could you please check? 
https://mirror.bazel.build/github.com/adoptium/temurin19-binaries/releases/download/jdk-19.0.2%2B7/OpenJDK19U-jdk_s390x_linux_hotspot_19.0.2_7.tar.gz

**Comment by zhengwei143** [comment]
Works now, thanks!
