### ISSUE TITLE
`bazel query` after `bazel clean` hangs

### ISSUE THREAD

**Issue by brian-peloton** [bazelbuild/bazel#1869]
I have an automated script which runs `bazel --output_base=foo clean` and then `bazel --output_base=foo query` immediately afterwards. That usually works, but recently it hung for a day and counting. I think the Bazel server is confused. It cleans up a lot of files, so the clean does not finish quickly.

The stdout/stderr of the command just has `Another command (pid=49796) is running.  Waiting for it to complete...`, and there is no process with PID 49796. I suspect that PID was the clean, but I have no way to check. Further `bazel --output_base=foo version` (or any other subcommand) get the same message.

The java.log file has some interesting-looking warnings in it. Something about slow interrupts from GRPC. I'm pretty sure `Oct 01, 2016 9:57:53 PM` is when the query was run, so I don't know why those other warnings have datestamps from a day earlier, and they might be completely unrelated. The server might've been running for that whole day without any other commands being run, which could explain those.

I uploaded the log files (I also grabbed a stacktrace of all the threads via ctrl+\ in the client in case that's useful) at [gist 417d5c37162852ff0ee5c7b6d176a49e](https://gist.github.com/417d5c37162852ff0ee5c7b6d176a49e).

This is using version 4257ff9d3d24ceb10d1d88166c0a8a8d6a30d2b5, which uses the new gRPC client-server communications implementation.

CC: @lberki

**Comment by lberki** [comment]
https://www.youtube.com/watch?v=W6MkESn1v1w

When you took this thread stack dump, was the Bazel client that ran `bazel query` still running? From the dump, it seems like there is a query command that cannot finish for some reason. I can imagine that there is an issue with the Bazel server not noticing that the client died, but even then, the running `bazel query` command should eventually finish.

@janakdr @michajlo for some extra wisdom

**Comment by lberki** [comment]
My best theory is that when the client unexpectedly goes away, GrpcServerImpl cancels the command:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/server/GrpcServerImpl.java#L215

And it causes the implementation of `bazel query` to deadlock for some reason. I don't see the log message in @brian-peloton 's Gist, but maybe that's because he didn't grab the whole log file?

**Comment by michajlo** [comment]
It seems like you have a dangling thread in HttpDownloader, which for some reason wasn't interrupted or didn't acknowledge the interrupt.

Are you able to readily reproduce it? Your best bet is to try a newer version - a lot of improvements have been made in this area since your build, including better interrupt support and timeouts on http requests.

**Comment by brian-peloton** [comment]
Yes, the original hung `bazel query` client was still running, along with another `bazel query` or `bazel version` (I forget which) I was running to send the ctrl+\.

The lack of that log is because the version I'm using doesn't have it...

I can not reproduce this. This same script has been running ~20 time every day for almost 2 months now, and it just happened once.

Looking at it, there are a lot of changes to the relevant code since my version. In fact, e1f6380e5d80a2a98b159e4025c338e344a6c824 sounds like it solves this exact problem. Looking at that commit brings to mind that the server from the clean should be shutting down, and not interacting with the query client at all... Sounds like I should upgrade to the upcoming release, which I will do soon (pending a resolution to #1836). Thanks for looking!
