### ISSUE TITLE
Broken-symlink ~/.bazelrc doesn't produce an error

### ISSUE THREAD

**Issue by xiongchiamiov** [bazelbuild/bazel#1872]
We've run into an issue a few times recently where we moved the location in a repo of a shared bazelrc file, breaking the `~/.bazelrc` symlink.  However, Bazel silently ignores this file when the symlink is broken, just as it does when the file doesn't exist, which means that people continued on assuming all of the appropriate default options were set (but in reality, they were using Bazel's defaults).

An entirely missing bazelrc is normal.  A broken symlink, however, shows that the user _intended_ to put a config in place, and so I'd like it to be an error.

**Comment by aehlig** [comment]
> Seems reasonable, pinging @aehlig to see what he thinks of it.

There are reasons for both behaviours (e.g., not everybody likes the
need of keeping an empty file to not break symlinks if the intention
is to switch back to entirely default behaviour).

But, to be honest, I don't have a strong opinion on this question (so,
chaning as suggested seems fine and may be even marginally better than
the current behaviour), as rc-files being symlinks usually are symptoms
of bad use of rc-files anyway. Bazel, as most other tools, has for very
good reasons that whole hierarchy of rc-files (global, machine/binary
wide, user, project, user-project-checkout) with different scope
(cummulating the effects with latest-wins semantics) so that options
can be added in one single place for the appropriate scope. Symlinks
are usually an indication that some options should have been added to
an rc-file with different scope.


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
