### ISSUE TITLE
OSX sandboxing doesn't seem to restrict network access

### ISSUE THREAD

**Issue by mightyguava** [bazelbuild/bazel#1881]
We've run into this issue a few times now, where unit tests written on OS X pass, but then fail when run on Linux machines, and we need to go back and either change the test or add the `requires-network` tag.

It looks like it's possible to restrict network on os x with `sandbox-exec -n no-network command`. Is there any reason why Bazel doesn't do this?

We are running off of 60af9db, somewhere past 0.3.1.

**Comment by abergmeier-dsfishlabs** [comment]
Keep in mind that in future this limit must only apply for actions not using remote execution.

**Comment by hermione521** [comment]
OSX sandboxing do restrict network access, although we changed it to allow network access by default for build (still deny by default for test). The change is here: https://github.com/bazelbuild/bazel/commit/6488b3bc824a0f19ad2924d5f7c87181f06beed9

FYI, the sandbox script is here: https://github.com/bazelbuild/bazel/blob/95a87d0d8b26d9ca7d8d957dc23373b6a89e3d68/src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxRunner.java#L127
the network check is here:
https://github.com/bazelbuild/bazel/blob/95a87d0d8b26d9ca7d8d957dc23373b6a89e3d68/src/main/java/com/google/devtools/build/lib/sandbox/SandboxHelpers.java#L70

If you are running tests and not debugging, network should be denied by default. But local network is allowed since bazel itself needs it.

If it's not the case, please provide more detailed info about your target.

**Comment by mightyguava** [comment]
Here's a repro case https://github.com/mightyguava/bazel-network

Run `bazel test src:NetworkTestSuite`

For me, with a Bazel binary off of head (27cd7f6bb4a02f56f9ad73e57e71e69a1c00d5ea), it succeeds on Mac, but fails on Linux.

**Comment by mightyguava** [comment]
The environments I've tested this in are OS X 10.11 and 10.12, Ubuntu 12.04 and 14.04.
