### ISSUE TITLE
We should test `bazel fetch ...` on a clean repository

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1886]
See #1880 for more context.

**Comment by aj-michael** [comment]
Yes, we should put an android_binary in one of the fetch integration tests.

#1880 happened because tensorflow has an android_binary as a sample app and I accidentally introduced an implicit dependency from android_binary on something from the android_sdk_repository. So `bazel fetch tensorflow/...` failed inside `./configure` if you didn't have an android_sdk_repository in the WORKSPACE.

**Comment by aj-michael** [comment]
`bazel fetch //some/android:target` will intentionally fail without an `android_sdk_repository` set up in the `WORKSPACE` as of 0b9ebfe. See https://github.com/bazelbuild/bazel/issues/1819#issuecomment-266460423 for context on this decision. Tensorflow's use case was cleaned up in tensorflow/tensorflow#6225.
