### ISSUE TITLE
bazel does not enforce testonly

### ISSUE THREAD

**Issue by benjaminp** [bazelbuild/bazel#1923]
Consider this BUILD file:
```
filegroup(
  name = 'foo',
  testonly = True,
)
filegroup(
  name = 'bar',
  srcs = [':foo'],
)
```
I would expect building `:bar` to not work because it is a non-testonly rule that depends on a testonly one. However, bazel is more than happy to build `:bar`:
```
$ bazel build :bar
INFO: Found 1 target...
Target //:bar up-to-date (nothing to build)
INFO: Elapsed time: 0.387s, Critical Path: 0.00s
```

**Comment by jart** [comment]
Uh oh spaghettios.

I can confirm this issue is correct. I would recommend prioritizing this issue.

**Comment by hermione521** [comment]
I'm surprised that `testonly` does not work at all..

**Comment by damienmg** [comment]
I am suprised this is even in Bazel :). Ok I am trying to understand how important this is.

We could remvoe that feature all together because it can be implemented by the constraints system.

@benjaminp, @jart: What is your use-case for such a feature?

**Comment by benjaminp** [comment]
My usecase is essentially what's in the `testonly` documentation: 
> This attribute is intended to mean that the target should not be contained in binaries that are released to production... rules that are dangerous to even link in, perhaps because they unconditionally override normal behavior, should definitely be marked testonly.

This bug report is a consequence of me discovering code that reset for databases in production.

The advantage of `testonly` at the moment is that the `test` flag partitions all Bazel rules. If I wanted to use the constraint system, I would either have to mark all production or all testing rules appropriately. Perhaps `test = True` could put rules in an implicit environment.

**Comment by jart** [comment]
Let's say I write a naïve HTTP server intended for development that's vulnerable to attacks like [slowloris](https://en.wikipedia.org/wiki/Slowloris_(computer_security)), [billion laughs](https://en.wikipedia.org/wiki/Billion_laughs), localhost:8000/../../../../etc/passwd, etc. I wouldn't normally be able to live with myself writing such a thing—unless I was able to guarantee it'll never end up in production. That's why I need `testonly`.

Otherwise we end up like Knight Capital, which lost almost half a billion dollars in forty-five minutes back on August 1^st, 2012 because code that wasn't supposed to be in production suddenly activated.

I also believe that being able to define what sources are and what their relationships are to each other is what sets Bazel apart from other build systems. It's very abstract and definitional. And those definitions get enforced at build time. It can also be bazel query'd. So whatever we can do to help our build graph be better defined is a good thing. Looking at my notes file, I can see there have been situations in the past where I've written queries that look for `testonly`.

**Comment by damienmg** [comment]
@jart: I mean the constraint system could be used to create a "test" environment that you could apply with "restricted_to".

Ok in the future we might want to migrate it to constraint system but let make it work for now. I'll try to put it in my queue. do not hesitate to ping if I forgot to update this bug with progress.

**Comment by jart** [comment]
Having it be migrated to the constraint system would be acceptable to me.

**Comment by damienmg** [comment]
Well because having a nice support with the constraint system is not going to happen soonish (this is doable right now but not built-in, so you have to mark all your test targets as "restricted_to"), we are going to fix testonly.

**Comment by jart** [comment]
Awesome. I'm so happy to hear that Damien.

**Comment by damienmg** [comment]
Ok I sent a fix for it :) It wasn't too hard. Might be in release 0.4 but it won't block it (meaning that if the CI is green tomorrow we will cut it without that change in).

**Comment by jart** [comment]
You're amazing Damien. Thank you for fixing this important issue.
