### ISSUE TITLE
Remove `_allowlist_function_transition` requirement

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#19233]
### Description of the feature request:

It seems like at this point anyone who wants to use a starlark transition just adds this attribute and moves on, I feel like given how long this has been around maybe it's reasonable to remove this requirement now so folks don't have to jump through this hoop?

**Comment by NextThread** [comment]
can i work on this?

**Comment by katre** [comment]
Unfortunately we still need this for Bazel's google-internal version, so we can't remove it entirely.

We could explore if it's possible to set it up so that Bazel users don't need to set it, however.

@NextThread Because this touches code inside and outside of Google it's not a good project for a non-team member, I'm sorry to say.

I'll bring this up with the team at our next meeting.

**Comment by katre** [comment]
We discussed this today: we agree that it's a pain point and it'd be good to fix. Unfortunately, due to the way the internal and external versions of Bazel work, it's not a trivial fix, and we're not sure anyone will have time in the near future to dive in and understand the code better, but we're going to keep this open for now.

**Comment by fmeum** [comment]
@comius Hasn't this been fixed by https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e? If so, could this be cherry-picked into 7.1.0?

**Comment by comius** [comment]
Yes, it was fixed. It doesn't appear to be in 7.0.0 and yes it can be cherry-picked.

**Comment by fmeum** [comment]
@bazel-io fork 7.1.0

**Comment by iancha1992** [comment]
@fmeum @comius https://github.com/bazelbuild/bazel/commit/bb7fb2d32f055f2a70a5ab394cf5aef29bc74b2e was already cherry-picked in https://github.com/bazelbuild/bazel/commit/60f3319ebca47080b7af823c8aba52b391a8baa6.

Let me know if you want to close this.
