### ISSUE TITLE
Windows: support --watchfs

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#1931]
Everything is in the title :) /cc @dslomov

**Comment by laszlocsomor** [comment]
Do you know what's available already?

**Comment by damienmg** [comment]
I believe the java interface should work out of the box. So probably just wiring it and then testing it :)

**Comment by dslomov** [comment]
Here is a link to IntelliJ IDEA's implementation: https://github.com/JetBrains/intellij-community/tree/master/native/fileWatcher

**Comment by damienmg** [comment]
Java WatchService should work as intended so there is probably no change needed to the Linux one. The OSX case is tricky because the java implementation is wrong.

**Comment by damienmg** [comment]
(sorry wrong button)

**Comment by laszlocsomor** [comment]
I'm not aware of anyone waiting for this feature, and it doesn't seem critical. (It would be nice to have, of course.)

**Comment by alexeagle** [comment]
@meteorcloudy we still have `--watchfs` disabled for Angular, presumably this is hurting us for Mac/Linux rebuild performance. ( https://github.com/angular/angular/issues/29541 referenced above)

I'm now creating a .bazelrc file to share with all frontend projects. I would rather not copy this setting for everyone, but we do need things to work on Windows out of the box.

A shorter term solution would be if the .bazelrc setting could be platform-dependent, similar to how the --config flag lets us scope bazelrc settings to specific scenarios. @laszlocsomor do you think we should have a feature request so that --watchfs could be disabled on a single platform? OR maybe we should just disable the feature on windows generally?

**Comment by meteorcloudy** [comment]
I think it makes sense to make `--watchfs` a non-op on Windows for now. But in the long term this could be a useful feature to improve Windows performance as well, since IO operation on Windows is much slower than Mac/Linux.

**Comment by laszlocsomor** [comment]
I agree with @meteorcloudy .

@alexeagle , I don't think we should support disabling a flag just on one platform. I see no problem with making it a no-op on Windows though.

**Comment by meteorcloudy** [comment]
Cool, I will send a change for this

**Comment by laszlocsomor** [comment]
2019-07-08 state:
- `--watchfs` is both a (deprecated) startup flag [1] and a command flag [2]
- e73f881b66e5540051f92f8ffab5570b6856fea8 marked the startup flag deprecated; it was @ulfjack's request to do so in the internal code review
- a TODO(ulfjack) [3] says the startup flag should be deleted in favor of the command flag
- d04d7baa1605c8c3a637255bd61c00dba73ad800 made the command flag a no-op on Windows, but didn't change the startup flag

I don't know if anyone wants `--watchfs` on Windows or if anyone supports it.

[1] https://github.com/bazelbuild/bazel/blob/c26e3396cb341e173b4be5c780cafac3ec386df5/src/main/java/com/google/devtools/build/lib/runtime/BlazeServerStartupOptions.java#L333

[2] https://github.com/bazelbuild/bazel/blob/c26e3396cb341e173b4be5c780cafac3ec386df5/src/main/java/com/google/devtools/build/lib/skyframe/LocalDiffAwareness.java#L51

[3] https://github.com/bazelbuild/bazel/blob/c26e3396cb341e173b4be5c780cafac3ec386df5/src/main/java/com/google/devtools/build/lib/runtime/BlazeOptionHandler.java#L277

**Comment by meteorcloudy** [comment]
I found the loading and analysing time on Windows for Angular and TensorFlow is quite long (1 ~ 2s) due to scanning every input file and directory for every bazel command. If watchfs is enabled, we can avoid many file operations, so potentially we could improve the performance a lot. I'm planning to work on this in 2019 Q3.

**Comment by konste** [comment]
We are trying to migrate big codebase to Bazel and, although we support all three platforms, primary Dev machines are Windows. Typical Dev workflow includes frequent incremental rebuilds after making very small changes. Attempt to take big external dependencies (think Boost and Qt) as sources makes this even more important. We expect that working --watchfs on Windows would improve Dev experience dramatically.

@meteorcloudy were you able to start working on this feature? Any bits we can try? We are waiting for this feature desperately.

**Comment by meteorcloudy** [comment]
@konste I'm sorry, --watchfs for Windows is no longer a priority currently. I don't have plan to work on this, but contribution is always welcome!
