### ISSUE TITLE
 Long runtime classpaths slow down unit test execution

### ISSUE THREAD

**Issue by rsalvador** [bazelbuild/bazel#19480]
### Description of the bug:

The classpath pre-processing loop in `java_stub_template.txt` is inefficient for very long classpaths and slows down unit test execution. The slowdown is in this loop in java_stub_template.txt: https://github.com/bazelbuild/bazel/blob/fcfcb929366dd3faac9643302b19c88bcf871ec6/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L309 for classpaths with ~250,000 and ~700,000 entries the loop takes 28 and 50 seconds, respectively, on an intel MacBook.

### Which category does this issue belong to?

Performance

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run a unit test with a very long runtime classpath.

### Which operating system are you running Bazel on?

OSX

### What is the output of `bazel info release`?

release 6.1.0

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Performance regression seems to have been introduced in https://github.com/bazelbuild/bazel/commit/d0ee889fca77e36f2c76ac07de3048055b8428c9

### Have you found anything relevant by searching the web?

No

**Comment by cushon** [comment]
This is part of the logic that generates a separate jar file as a way to configure classpath that are too long to pass on the command line.

@rsalvador I'm curious which JDK you're using, is it newer than JDK 8? The long term plan here is to replace this logic in the stub template with an `@argument` file: https://github.com/bazelbuild/bazel/issues/6354

(I'm also not sure why the stub template generates this every time it's executed, instead of having Bazel create a separate action that generates the separate jar file once; that came up in https://github.com/bazelbuild/bazel/issues/19036.)

**Comment by rsalvador** [comment]
> @rsalvador I'm curious which JDK you're using, is it newer than JDK 8? The long term plan here is to replace this logic in the stub template with an `@argument` file: #6354

@cushon using JDK 11: OpenJDK 64-Bit Server VM (build 11.0.19+7-LTS, mixed mode) by Azul Systems, Inc.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 6.4.0 RC1](https://releases.bazel.build/6.4.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!

**Comment by rsalvador** [comment]
@iancha1992 verified that the generated test script executables include the fix and that the test execution is faster than with 6.3.2 for a sample test (35 seconds with 6.3.2 vs 12 seconds with 6.4.0rc1)
