### ISSUE TITLE
Generated C++ header not symlinked in execroot

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#1950]
Let's say I'm writing `swig.BUILD` for `@swig//`. I might write a `genrule` to produce a config header.

``` py
genrule(
    name = "swigconfig_h",
    outs = ["Source/Include/swigconfig.h"],
    cmd = "cat <<EOF >$@\n" +
          "#define HAVE_BOOL\n" +
          "EOF",
)
```

In which case I want to be able to do this:

``` py
cc_binary(
    name = "swig",
    srcs = [...],
    copts = ["-Iexternal/swig/Source/Include", ...],
)
```

The problem is I get:

```
In file included from external/swig/Source/DOH/dohint.h:17:0,
                 from external/swig/Source/DOH/base.c:15:
external/swig/Source/DOH/doh.h:18:24: fatal error: swigconfig.h: No such file or directory
 #include "swigconfig.h"
                        ^
compilation terminated.
```

Because the generated file isn't in a place where the compiler can find it.

I found the execroot by saying `bazel build -s @swig//:swig` which we'll call `.../execroot/tensorflow-clean`. If I do this:

```
$ find -L .../execroot -name swigconfig.h\*
.../execroot/tensorflow-clean/bazel-out/local-fastbuild/genfiles/external/swig/Source/Include/swigconfig.h
.../execroot/tensorflow-clean/external/swig/Source/Include/swigconfig.h.in
.../execroot/tensorflow-clean/external/swig/vms/swigconfig.h
.../execroot/org_tensorflow/bazel-out/local-fastbuild/genfiles/external/swig/Source/Include/swigconfig.h
.../execroot/org_tensorflow/external/swig/Source/Include/swigconfig.h.in
```

There are two workarounds to this:
1. Use `includes = ["Source/Include"]`. This works even better and avoids the `external/swig/` prefix. The problem is that `includes` is a horrible last resort. For example, if it's used on a `cc_library` then it slows down compilation for all dependent rules.
2. Use `copts = ["-Ibazel-out/local-fastbuild/genfiles/external/swig/Source/Include"]`. I'm not sure if this is optimal either, because 

It would be nice if Bazel just symlinked that file.

Attn: @kchodorow 

---

```
Build label: 0.3.2-2016-10-14 (@183147e)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 14 21:34:37 2016 (1476480877)
Build timestamp: 1476480877
Build timestamp as int: 1476480877
```

**Comment by philwo** [comment]
I understand your use case and agree that this should work! :)

I'm having some trouble following the example though: From looking at your example cc_binary, I don't understand how Bazel is supposed to know that that header file is required for compilation? Is it referenced in the "srcs" attribute? Because "copts" is just raw strings that are not parsed by Bazel. Directories that show up there are not considered by Bazel to be or contain dependencies of the action.

In general this seems like it would break with sandboxing enabled, even with your proposed two solutions, unless I'm missing something here?

Can you add the generated file to the srcs attributes? In that case bazel should correctly symlink it (but I'm not exactly sure under which path, to be honest).

**Comment by jart** [comment]
Here's the [complete SWIG BUILD file](https://gist.github.com/jart/427445a58ef2023113d955e8605cee0e) I wrote. You'll notice that `Source/Include/swigconfig.h` is generated by a genrule and it's listed in the `cc_library` `srcs`. I also pass the `-Iexternal/swig/Source/Include` copt.

**Comment by jart** [comment]
@philwo I'm helping with OKR planning. Is it possible this issue is the cause of the sandbox bug workaround we've had to employ here? https://github.com/tensorflow/tensorflow/blob/a86b86a2d25efbc5767ac5d270725bf85db183ff/tensorflow/tensorboard/defs.bzl#L34

**Comment by philwo** [comment]
@jart I can't follow. I got here from a document that listed outstanding issues from the TensorFlow team. This bug is about a generated C++ header not being symlinked by the sandbox for cc_binary targets. But the file you linked to concerns TypeScript?

Could you give me a minimal reproduction example of what is supposed to work? Then I can turn it into an integration test and fix the underlying issue.

**Comment by mhlopko** [comment]
Is this issue still relevant? Reproducible?

**Comment by mhlopko** [comment]
Feel free to comment and I'll reopen if still relevant.
