### ISSUE TITLE
gcc path always contains package path in cc_common.create_cc_toolchain_config_info()

### ISSUE THREAD

**Issue by Okayu0010** [bazelbuild/bazel#19545]
### Description of the feature request:

I created a custom cc-toolchain in a BUILD file in a subdirectory(a package) of my bazel workspace. In the impl function of this custom-cc-toolchain rule, I use cc_common.create_cc_toolchain_config_info() to return a ccToolchainInfo. 

This custom toolchain can run perfectly if I use absolute path as gcc path which specified in tool_path, for example:

```
tool_paths = [
        tool_path(name = "gcc",     path = "/usr/bin/gcc"),
        ...
    ]
return cc_common.create_cc_toolchain_config_info(
       ...
        tool_paths = tool_paths,
    )
```

But if I use relative path as gcc path (for example when my gcc comes from an external repository), it works incorrectly, for example:

`tool_path(name = "gcc",     path = "external/my_repository/bin/gcc")`
In fact, the path "external/my_repository/bin/gcc" will be replaced automatically with "package_name/external/my_repository/bin/gcc", which not exists in the exec directory, so that the custom gcc cannot be found.

The only solution I have found so far is to put the BUILD file which implements my custom cc-toolchain to the root directory of the workspace. I think there should be a better way.

In the source code of bazel, I found the cause of my problem in src/main/java/com/google/devtools/build/lib/rules/cpp/CcModule.java:1319. It works like this:
```
linkerToolPath =   // gcc_path
              starlarkRuleContext
                  .getRuleContext()
                  .getLabel()
                  .getPackageIdentifier()
                  .getExecPath(starlarkRuleContext.getConfiguration().isSiblingRepositoryLayout())
                  .getRelative(PathFragment.create(tool.second))
                  .getPathString();
```
This code below above makes a substitution to the gcc path I specified, and I think it should be removed.

### Which category does this issue belong to?

C++/Objective-C Rules

### What underlying problem are you trying to solve with this feature?

The implementation of cc toolchain can be more flexible and free.

### Which operating system are you running Bazel on?

centos 7

### What is the output of `bazel info release`?

release 6.2.1

**Comment by fmeum** [comment]
Cc @illicitonion

**Comment by illicitonion** [comment]
It sounds like you're expecting to specify an exec-path in the `tool_path`, but in reality what's accepted is a path relative to the BUILD file. In general we don't expect people to specify exec paths anywhere, because they leak internal implementation details of Bazel (e.g. the fact that `external_repository` should be accessed by exec-path as `external/external_repository` is an implementation detail which has changed in the path, and so one which shouldn't be assumed when writing BUILD files).

I suspect the solution to this problem is going to be to treat the string as a label, if it isn't an absolute path. The existing behaviour I think is correct assuming you're not crossing between multiple repositories, but there's no way to cleanly express a cross-repository path. By supporting resolving `@other_repository//path/to:gcc` to the exec path `external/other_repository/path/to/gcc`, this would be fixed in a nice general way.

These are roughly the desired behaviours:

## Already supported cases

### Absolute path

If an absolute path is passed, an absolute path should be used by the action:

```starlark
tool_path(name = "gcc", path = "/usr/bin/gcc") # Should use /usr/bin/gcc
```

### Path relative to the BUILD file in the main repository

Need an exec path, so if a toolchain is defined in the main repository, a relative path should be relative to the BUILD file

In `@//toolchain:BUILD.bazel`
```starlark
tool_path(name = "gcc", path = "path/to/gcc") # Should use toolchain/path/to/gcc
```

### Path relative to the BUILD file in an external repository

Need an exec path, so if a toolchain is defined in an external repository, a relative path should be transformed from being relative to the BUILD file to relative to the exec root

In `@external_toolchain//toolchain:BUILD.bazel`
```starlark
tool_path(name = "gcc", path = "path/to/gcc") # Should use external/external_toolchain/toolchain/path/to/gcc
```

### Path in an external repository which isn't a child of the package

Need an exec path, so if a toolchain is defined in an external repository, a relative path should be transformed from being relative to the BUILD file to relative to the exec root

In `@external_toolchain//toolchain:BUILD.bazel`
```starlark
tool_path(name = "gcc", path = "../path/to/gcc") # Should use external/external_toolchain/path/to/gcc
```

## Desired cases

As this issue notes, crossing repositories is currently broken. There's no _nice_ way to say "my file is in another repository". This probably works, but hard-codes repository layout information:

In `@external_toolchain//toolchain:BUILD.bazel`
```starlark
tool_path(name = "gcc", path = "../../external/other_toolchain/path/to/gcc") # Should use external/other_toolchain/path/to/gcc
```

But ideally one could write:

In `@external_toolchain//toolchain:BUILD.bazel`
```starlark
tool_path(name = "gcc", path = "@other_toolchain//path/to:gcc") # Should use external/other_toolchain/path/to/gcc
```

---

I'll also note that this behaviour was re-implemented in Starlark in 04ab2c0449d6f257cccf659f106e86f36c58b3d4, so any fixes here may need implementing in both the Java implementation linked in the original issue, as well as in the new starlark implementation.

**Comment by Okayu0010** [comment]
@illicitonion I will try it, thank you very much

**Comment by sbjorkle-qualcomm** [comment]
Also note that, when implementing this, it would also be desirable if generated files could be used as input as well. That way the toolchains does not need to be repository rules but could instead be actions which would limit the amount of data a client needs when running remote-execution build-without-the-bytes.
Example:
tool_path(name = "gcc", path = "@other_toolchain//path/to:generated_gcc") # Should use bazel-out/pclinux64-opt-ST-b2bbad280e7e/bin/external/other_toolchain/path/to/generated_gcc
