### ISSUE TITLE
header files in `hdrs` of cc_library not accessible in other directory

### ISSUE THREAD

**Issue by wyhao31** [bazelbuild/bazel#19716]
### Description of the bug:

I'm not sure whether I misunderstand something. Here's the details.

A simple bazel project, directory structure:
```
.
├── foo
│   ├── BUILD.bazel
│   ├── foo.cpp
│   ├── foo.h
│   └── test
│       └── foo_test.cpp
└── WORKSPACE
```

Content in BUILD.bazel:
```
cc_library(
    name = "foo",
    srcs = ["foo.cpp"],
    hdrs = ["foo.h"],
)

cc_binary(
    name = "foo_test",
    srcs = ["test/foo_test.cpp"],
    deps = [":foo"],
)
```

I think foo_test.cpp should be able to include foo.h like this `#include "foo.h"`, but I got `fatal error: foo.h: No such file or directory`.

If I add `include_prefix` or `strip_include_prefix` in cc_library of foo, like this
```
cc_library(
    name = "foo",
    srcs = ["foo.cpp"],
    hdrs = ["foo.h"],
    include_prefix = ".",
    # or
    # strip_include_prefix = ".",
)
```
The build can pass.

It looks like the virtual includes symlinks and `-I.../_virtual_includes/foo` option are only used when having include_prefix or strip_include_prefix specified. I noticed that `-iquote .` are used in the compiling command, so if foo_test.cpp is in the same directory of foo.h, the build can still pass without include_prefix and strip_include_prefix.

Is this expected behavior? Thanks!

### Which category does this issue belong to?

C++/Objective-C Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Already mentioned in the bug description.

### Which operating system are you running Bazel on?

Ubuntu 18.04

### What is the output of `bazel info release`?

release 6.3.2

**Comment by martis42** [comment]
This is the expected behavior. Bazel assumes you include headers with their path relative to the workspace root. In your case `#include "foo/hoo.h`. In other words, Bazel sets the workspace root with `-iquote` as path for the compiler to search for headers.

`#include "foo.h"` works given `foo.h` and `foo_test.cpp`are in the same directory as the compiler tries to find header files relative to the source file it is processing.

As you discovered, there are several cc_library attributes allowing to manipulate the include paths at which users of your library can consume the library headers. My personal opinion is one should always include headers relative to the workspace root and not use virtual includes unless there is a good reason to do so.

One word of warning about `includes = [...]`. This does not just change the paths at which headers can be included using `#include <..>`. It models those paths as `-isystem` which ignores compiler warnings for the headers included from those paths.

**Comment by wyhao31** [comment]
@martis42 I see. Thanks for your detailed explanation!
