### ISSUE TITLE
Building Bazel@HEAD results in many Java-related warnings

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/bazel#19837]
### Description of the bug:

Running `bazel build //src:bazel-dev` on current `master` (e.g. 38bf100) of Bazel itself results in the following warning being emitted for what appears to be almost every Java target:

```
warning: [options] system modules path not set in conjunction with -source 11
```

### Which category does this issue belong to?

Java Rules

**Comment by fmeum** [comment]
CC @cushon

**Comment by cushon** [comment]
I tried and wasn't able to repro.

I don't see `38bf100`, I tested at `2ddacab80af1dca3c04e74809827c47ec4bc8498`.

```
bazel build //src:bazel-dev
bazel-bin/src/bazel-dev build //src:bazel-dev
```

I don't see `warning: [options] system modules path not set ...` in the logs.

I tested with `openjdk full version "17.0.6+10-LTS"` as the local JDK, on a mac.

Am I holding it wrong?

**Comment by fmeum** [comment]
Sorry for the false alarm, I only see this on https://github.com/bazelbuild/bazel/pull/18262, not `master`. I had the wrong branch checked out. It's still surprising.

**Comment by cushon** [comment]
Thanks, I can repro with

```diff
diff --git a/MODULE.bazel b/MODULE.bazel
index 4068f2e297..a4adc84765 100644
--- a/MODULE.bazel
+++ b/MODULE.bazel
@@ -24,7 +24,7 @@ bazel_dep(name = "zstd-jni", version = "1.5.2-3.bcr.1")
 bazel_dep(name = "blake3", version = "1.3.3.bcr.1")
 bazel_dep(name = "zlib", version = "1.3")
 bazel_dep(name = "rules_cc", version = "0.0.9")
-bazel_dep(name = "rules_java", version = "6.3.1")
+bazel_dep(name = "rules_java", version = "6.5.1")
 bazel_dep(name = "rules_proto", version = "5.3.0-21.7")
 bazel_dep(name = "rules_jvm_external", version = "5.2")
 bazel_dep(name = "rules_python", version = "0.24.0")
diff --git a/distdir_deps.bzl b/distdir_deps.bzl
index 8c2f8e20c7..593ebc4cca 100644
--- a/distdir_deps.bzl
+++ b/distdir_deps.bzl
@@ -106,9 +106,9 @@ DIST_DEPS = {
             "rules_java_builtin",
             "rules_java_builtin_for_testing",
         ],
-        "archive": "rules_java-6.3.1.tar.gz",
-        "sha256": "117a1227cdaf813a20a1bba78a9f2d8fb30841000c33e2f2d2a640bd224c9282",
-        "urls": ["https://github.com/bazelbuild/rules_java/releases/download/6.3.1/rules_java-6.3.1.tar.gz"],
+        "archive": "rules_java-6.5.1.tar.gz",
+        "sha256": "7b0d9ba216c821ee8697dedc0f9d0a705959ace462a3885fe9ba0347ba950111",
+        "urls": ["https://github.com/bazelbuild/rules_java/releases/download/6.5.1/rules_java-6.5.1.tar.gz"],
         "workspace_file_content": "",
         "used_in": [
             "additional_distfiles",
```

```
bazel clean; bazel shutdown; bazel build --toolchain_resolution_debug=bootstrap_runtime_toolchain_type  -s //src/main/java/com/google/devtools/build/lib/cmdline:query_exception_marker_interface
...
warning: [options] system modules path not set in conjunction with -source 11
```

The issue is that `--system` is not getting passed to javac:

```
$ bazel aquery 'mnemonic(Javac, //src/main/java/com/google/devtools/build/lib/cmdline:query_exception_marker_interface)' | grep -A 1 -E 'bootclasspath|system'
...
    --bootclasspath \
    bazel-out/darwin_arm64-fastbuild/bin/external/bazel_tools/tools/jdk/platformclasspath.jar \
```

I wonder if something is going wrong here: https://github.com/bazelbuild/rules_java/blob/0cdcecb2ee3a1da92f95ba0af036f20fa4179fb5/toolchains/default_java_toolchain.bzl#L246-L249

**Comment by benjaminp** [comment]
It's unsurprising to see this if host Bazel is <7 as 149cbce5418fadaac329dd007b1411407fea55c3 was not backported.

**Comment by davido** [comment]
I can reproduce this problem on Bazel@HEAD (2ddacab80af1dca3c04e74809827c47ec4bc8498), when building with RBE:

```bash
  $ bazelisk build --config=remote --remote_instance_name=$PROJECT src:bazel-bin-dev
[...]
warning: [options] system modules path not set in conjunction with -source 11
[...]
```

**Comment by fmeum** [comment]
@davido Bazel is currently using a pre-7 Bazel version to build itself, which doesn't have https://github.com/bazelbuild/bazel/commit/149cbce5418fadaac329dd007b1411407fea55c3. 

https://github.com/bazelbuild/bazel/commit/149cbce5418fadaac329dd007b1411407fea55c3 has always been missing in the 6.X releases, but this warning is only showing up with a newer rules_java. I am not sure whether https://github.com/bazelbuild/bazel/commit/149cbce5418fadaac329dd007b1411407fea55c3 could break anything if we backport it.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
This should be fixed by https://github.com/bazelbuild/rules_java/pull/142 + having a rules_java release for Bazel 7+.

**Comment by JohnnyMorganz** [comment]
Apologies for bringing up an old issue, but this seems most relevant to a problem I am currently facing.

We currently have a Bazel 6.4.0 repository that we recently enabled Bzlmod on. Our `java_runtime_version` and `java_language_version` is set to 11. When enabling bzlmod, it caused the JDK version of the compiler to switch from JDK 11 to JDK 17. From what I read based off https://github.com/bazelbuild/bazel/issues/19934#issuecomment-1779674035, this is expected. The rules_java version for bzlmod on 6.4.0 is 5.5.1.

When we enabled bzlmod, we started getting the same warnings `warning: [options] system modules path not set in conjunction with -source 11`. But what is more of a problem, is we started to get build failures `reference to Record is ambiguous`, due to a collision with the class `java.lang.Record`. This is odd, because that class was only introduced from 16+, but makes sense if the `system` flag is not being passed to javac.

However, based on this issue, it should be solved by the revert of the platformclasspath commit. But, AIUI this commit was not present for rules_java version 5.5.1 -https://github.com/bazelbuild/rules_java/blob/cc25058f4dcb66d9eaa40f1ccd72a856aa3f6e04/toolchains/default_java_toolchain.bzl#L83. Aquery also shows that bootclasspath is set to `bazel-out/k8-fastbuild/bin/external/rules_java~5.5.1/toolchains/platformclasspath.jar`. Also, using the temporary workaround in https://github.com/fmeum/bazel/commit/6daa5682e3e7f21b6e7fdf6a424aa7fc9d9e4c35 does not help. So, is there a separate reason why this is happening?

Here is a minimal repro setup: https://github.com/JohnnyMorganz/bazel-java-system-bug

Command causing failure:
```sh
$ USE_BAZEL_VERSION=6.4.0 bazel build //foo
```

Note that the build is successful when either:
a) disabling bzlmod (removing `common --enable_bzlmod`)
b) using Bazel 7.0.0+ (`USE_BAZEL_VERSION=7.0.0 bazel build //foo`), probably because of  https://github.com/bazelbuild/bazel/commit/149cbce5418fadaac329dd007b1411407fea55c3 - this is a longer term effort for us so we cannot do this immediately.

I can work around the compilation error by adding explicit imports (which we will need to do anyways if we want to upgrade JDK versions). But, we still get the warning on every java target build.

If this is better served as a new issue, let me know.
