### ISSUE TITLE
[7.0 regression] Unable to load workspace "@myworkspace" where `new_local_repository.build_file` refers to BUILD file w/ label "@myworkspace//path/to:BUILD.bazel"

### ISSUE THREAD

**Issue by beasleyr-vmw** [bazelbuild/bazel#19963]
### Description of the bug:

Bazel 7.0.0rc2 fails to load my project's main workspace, where I have a `new_local_repository` whose `build_file` argument contains a fully qualified label inside the workspace itself. The `build_file` label is fully qualified because it appears in a macro which is shared among multiple repositories.

### Which category does this issue belong to?

Loading API

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please see repro repo at https://github.com/beasleyr-vmw/repro-bazel7-new_local_repository .

The main repository is named "canon", and I try to instantiate a `new_local_repository` with `build_file = "@canon//:BUILD.shared.bazel"`.

```console
$ USE_BAZEL_VERSION=7.0.0rc2 bazelisk build :dummy
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: .../b7-new_local_repository_cannot_refer_to_self/WORKSPACE.bazel:5:12: fetching new_local_repository rule //external:shared: Unable to load package for @canon//:BUILD.shared.bazel: not found.
ERROR: no such package '@shared//': Unable to load package for @canon//:BUILD.shared.bazel: not found.
ERROR: .../b7-new_local_repository_cannot_refer_to_self/BUILD.bazel:1:8: //:dummy depends on @shared//:dummy in repository @shared which failed to fetch. no such package '@shared//': Unable to load package for @canon//:BUILD.shared.bazel: not found.
ERROR: Analysis of target '//:dummy' failed; build aborted: Analysis failed
INFO: Elapsed time: 5.126s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
```

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.0.0rc2

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

Yes.

```console
$ git rev-parse release-7.0.0rc2
2cb3159aed5b73eb13a866d8fe63953d388cd30b
```

`bazelisk --bisect 7.0.0-pre.20230917.3..2cb3159aed` points to <https://github.com/bazelbuild/bazel/commit/9be1be93ff17dbb4cf0effb4f885911ec99cc30c>.

### Any other information, logs, or outputs that you want to share?

See https://github.com/bazelbuild/bazel/issues/1248 for other use cases of this feature.

**Comment by fmeum** [comment]
Cc @Wyverald

**Comment by Wyverald** [comment]
Thanks for the repro. This bug is specific to `new_local_repository`, since the `build_file` attribute is actually of type `str` rather than `Label` (see [docs](https://bazel.build/reference/be/workspace#new_local_repository.build_file)). This, in turn, seems to be in order to support a legacy use case where a path (instead of a label) could be used for this attribute (see [code](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/repository/NewRepositoryFileHandler.java;drc=08463dcc09d65fa8fea64b1411be9b0c3941186e;l=219)). This is otherwise fine, but in case a label is used, it's treated as a canonical label, forgoing repo mapping altogether (see [code](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/repository/NewRepositoryFileHandler.java;drc=08463dcc09d65fa8fea64b1411be9b0c3941186e;l=185)).

The proper fix would be to change the attribute type to a label, which is potentially backwards-incompatible but well, we are allowed to do that.

**Comment by Wyverald** [comment]
@bazel-io fork 7.0.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.0.0 RC5](https://releases.bazel.build/7.0.0/rc5/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!

**Comment by beasleyr-vmw** [comment]
> A fix for this issue has been included in [Bazel 7.0.0 RC5](https://releases.bazel.build/7.0.0/rc5/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!

Confirmed resolution w/ RC5. Thanks!

**Comment by andrewkatson** [comment]
I think this still happens with Mac.  Should I open a new issue?

**Comment by fmeum** [comment]
Please do!

**Comment by andrewkatson** [comment]
Well I made an example but it actually succeeded so never mind :) https://github.com/andrewkatson/bazel_mac_new_local_repo
