### ISSUE TITLE
Kythe and Protobuf are failing with Release 7.0

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazel#19973]
**Kythe :** 
-----------

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3379#_

**Platform**: Ubuntu

**Logs**:
```
ERROR: no such package '@io_kythe//kythe/data': The repository '@io_kythe' could not be resolved: Repository '@io_kythe' is not defined
(03:57:19) ERROR: /var/lib/buildkite-agent/builds/bk-docker-r8lq/bazel-downstream-projects/kythe/WORKSPACE:63:19: no such package '@io_kythe//kythe/data': The repository '@io_kythe' could not be resolved: Repository '@io_kythe' is not defined and referenced by '//external:vnames_config'
(03:57:19) ERROR: Analysis of target '//kythe/cxx/indexer/cxx/testdata/proto:proto_semantic_ref_aw_test_proto_kzip' failed; build aborted: Analysis failed
(03:57:19) INFO: Elapsed time: 1.389s, Critical Path: 0.04s
(03:57:19) INFO: 1 process: 1 internal.
(03:57:19) ERROR: Build did NOT complete successfully
(03:57:19) FAILED:
```

**Steps**:
```
git clone -v https://github.com/kythe/kythe.git
git reset 47d8a9a27d280e7c71150a1b267f46790ead5fb7 --hard
export USE_BAZEL_VERSION=b3a83a3a3dab0b87952b67cfc7ea8516eabeec4b
sudo apt update && sudo apt -y install bison flex uuid-dev asciidoc graphviz source-highlight
bazel build //kythe/...
```

**Protobuf**
-------------

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3379#018b2723-e292-48fc-8571-d7d09097bced

**Platform** : Windows, MacOs, Ubuntu

**Logs**:
```
ERROR: no such package '@com_google_protobuf//': The repository '@com_google_protobuf' could not be resolved: Repository '@com_google_protobuf' is not defined
(03:55:15) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a270cf9078705688cac67ea00d82328b/external/bazel_tools/tools/proto/BUILD:10:6: no such package '@com_google_protobuf//': The repository '@com_google_protobuf' could not be resolved: Repository '@com_google_protobuf' is not defined and referenced by '@bazel_tools//tools/proto:protoc'
(03:55:15) ERROR: Analysis of target '//java/core:conformance_test' failed; build aborted: Analysis failed
(03:55:15) INFO: Elapsed time: 1.367s, Critical Path: 0.03s
(03:55:15) INFO: 1 process: 1 internal.
(03:55:15) ERROR: Build did NOT complete successfully
(03:55:15) ERROR: No test targets were found, yet testing was requested
(03:55:15) FAILED:
```

**Steps**:
```
git clone -v https://github.com/google/protobuf.git
git reset 42fe8b9927911cc81bf9a47c680c34b4413ee179 --hard
export USE_BAZEL_VERSION=b3a83a3a3dab0b87952b67cfc7ea8516eabeec4b
bazel test  --proto_toolchain_for_cc=//:cc_toolchain //:all //java/...
```

**Reference** : https://github.com/kythe/kythe/issues/5893#issuecomment-1772433650

CC Greenteam @comius @meteorcloudy

**Comment by meteorcloudy** [comment]
@bazel-io fork 7.0.0

**Comment by Wyverald** [comment]
Both failures can be traced back to the removal of the implicit `local_repository(name="$WORKSPACE_NAME", path=".")` clause in 9be1be93ff17dbb4cf0effb4f885911ec99cc30c.

The Kythe failure is due to usage of `bind` (https://github.com/kythe/kythe/blob/80d78947efb899a4f81bd6ce8e2118e925f8f05e/external.bzl#L1777), which does not respect repo mapping at all (see https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/packages/WorkspaceGlobals.java;drc=9be1be93ff17dbb4cf0effb4f885911ec99cc30c;l=139)

The Protobuf failure is much more annoying... [`@bazel_tools//tools/proto:BUILD`](https://cs.opensource.google/bazel/bazel/+/master:tools/proto/BUILD) defines a few aliases pointing into `@com_google_protobuf`. But since `bazel_tools` is injected in a WORKSPACE prefix, which happens before the `workspace` call, these aliases don't know that `@com_google_protobuf` actually means `@` (the main repo). Luckily this is a WORKSPACE-only problem (goes away with `--enable_bzlmod` and a minimal MODULE.bazel file containing `module(name='protobuf',repo_name='com_google_protobuf')`). But given https://github.com/protocolbuffers/protobuf/issues/14313, this might be rather tricky to tackle.

I'll try to fix the Kythe failure first.

**Comment by Wyverald** [comment]
For the Protobuf failure, I'm considering just adding an explicit `local_repository(name="com_google_protobuf", path=".")` line to protobuf's WORKSPACE. This only affects Protobuf's own build and immediately alleviates the problem, without us having to migrate it to Bzlmod first.

**Comment by Wyverald** [comment]
hmm, Kythe is still failing in downstream (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3440#018ba2ca-5fc1-4226-8f57-0d8a2b1d72ad). Re-opening until investigated.

**Comment by Wyverald** [comment]
It turns out Kythe uses bind within a `maybe()` macro from `@bazel_tools`, which causes the `actual` parameter to be interpreted from `@bazel_tools`'s perspective.

There's really no good way to fix without just nuking `bind`. I'm going to push a change to remove the `maybe` wrapper in Kythe.

**Comment by Wyverald** [comment]
Sent https://github.com/kythe/kythe/pull/5926

**Comment by pdecks** [comment]
This is still a problem for protobuf. As I noted in https://github.com/protocolbuffers/protobuf/issues/15615, I was able to successfully build using bazel 6.5.0. Both bazel 7.0.0 and 7.0.2 fail.

**Comment by debkanchan** [comment]
@pdecks Today I hit this bus and I was also able to repro this on 7.0.0 and 7.0.2. Due to this all our CI jobs are failing

**Comment by debkanchan** [comment]
Desperately need help here

**Comment by debkanchan** [comment]
I was able to pinpoint the issue comes from google.golang.org/protobuf v1.33.0

If you're depending on google.golang.org/protobuf directly in go then add the following line
```go
// HACK: pin protobuf version to fix build failure
replace google.golang.org/protobuf => google.golang.org/protobuf v1.32.0
```

**Comment by debkanchan** [comment]
I was further able to pinpoint the issue [here](https://github.com/golang/protobuf/issues/1611)
