### ISSUE TITLE
sandbox link tree is different with user's expectation

### ISSUE THREAD

**Issue by kevmoo** [bazelbuild/bazel#2000]

**Comment by kevmoo** [comment]
@dslomov See https://github.com/dart-lang/rules_dart/tree/bazel_repo_issue_2000
at https://github.com/dart-lang/rules_dart/commit/c60f6de2b728c188055a16bdc505212de41f15e7

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/sample-pop_pop_win with branch `bazel_issue_2000_repo`

`bazel run --curses=no --verbose_failures main_ddc_serve`

**Comment by natebosch** [comment]
We have 3 interesting files:
dart-sdk/bin/dartanalyzer, dart-sdk/bin/dart, dart-sdk/bin/snapshots/dartanalyzer.dart.snapshot

At run time, the script (dartanalyzer) expects that the binary (dart) is in [exactly the same directory](https://github.com/dart-lang/sdk/blob/66b5248bf937ef1202f04b106c63730e57a008b8/sdk/bin/dartanalyzer_sdk#L19).

What bazel does is copy dartanalyzer to a different directory, but not copy the other 2 files to the same place. The copy that get's executed has a different absolute path than the path to it's data, which breaks its assumptions.

**Comment by natebosch** [comment]
Ideally the semantics we'd like are (this is about what we're doing today with filegroup):

- Make a set of files available via glob (dart-sdk/**)
- Run a script/binary from within that set of files *from* that set of files

**Comment by dslomov** [comment]
so this only on mac sandbox right? Linux sandbox seems fine, or am I doing something wrong?

**Comment by hermione521** [comment]
So there are two problems:

1. It's not a not idea to follow symlinks [here](https://github.com/dart-lang/sdk/blob/66b5248bf937ef1202f04b106c63730e57a008b8/sdk/bin/dartanalyzer_sdk#L19), because in sandbox path, we first hardlink all the input files to <sandbox_path>/input and then symlink all the hardlinks to <sandbox_path>/exec. We execute the action in the latter path, where everything is a symlink. And I don't think it's necessary to follow symlinks, unless you have any special need. But this doesn't really cause your problem.
(If you want to know how sandbox directory looks like, you can simply add `--sandbox_debug` and go to the directory we cd)

2. The link tree generated in the sandbox path is not the same as you want (not sure which one we should fix). There are several `dartanalyzer` and `dart` binaries in the same directories, but the actually called binary is `analyzer` instead of `dartanalyzer`, and the `analyzer` is not in the same directory as other binaries.

I don't have any idea to fix the second problem, but I will keep trying. And if you have any idea, feel free to write here. Thanks!

**Comment by hermione521** [comment]
Update: this is related to sh_binary rule instead of sandboxing. Shell script should know its runfiles now. And we should fix this.

**Comment by kevmoo** [comment]
Thanks for the update @hermione521 – we'll keep watching this bug.

**Comment by kevmoo** [comment]
@hermione521 @dslomov Could ya'll look at this again?

Happy to provide a fresh setup, etc.

**Comment by jmmv** [comment]
Is this still relevant? I have a very hard time understanding what this is about with a subject line that is not objective and a first message that provides no further details. Please don't make me have to dig through bugs in other projects to *guess* what's happening. If you could summarize the problem, it'd be great.

**Comment by kevmoo** [comment]
I'd close this out. I've lost context w/ the original issue.

**Comment by jmmv** [comment]
OK thanks. Please reopen if you hit this again and the details come back.
