### ISSUE TITLE
[Duplicate] Automated rollback of commit fc3460e

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#20024]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/0a1dce27650a233d8acb1f09a1181279f510cae8

### Category

team-ExternalDeps

### Reviewers

@meteorcloudy, @Wyverald

**Comment by Wyverald** [comment]
@meteorcloudy @iancha1992 any idea why this is not working? I tried a few times but it always fails like https://github.com/bazelbuild/bazel/actions/runs/6734287774/job/18304851055. I thought it was because [this line](https://github.com/bazelbuild/continuous-integration/blob/cd29abd9cfc814169d3f16b4118ae533b5461bca/actions/cherry_picker/vars.py#L12) for some reason required three newlines after "Commit IDs" but that wasn't it.

**Comment by iancha1992** [comment]
@Wyverald I'll take a look

**Comment by iancha1992** [comment]
@Wyverald I have no idea why it works for me. But I'll take a look to fix it. Here's the PR that worked: https://github.com/bazelbuild/bazel/issues/20029
