### ISSUE TITLE
Clean up GitHub release page

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/bazel#20203]
### Description of the feature request:

We should remove all rolling releases from the GitHub release page since they introduce too much noise.

There should be a new index page somewhere that lists all rolling releases and that is being linked to from the documentation on https://bazel.build

### Which category does this issue belong to?

Documentation

**Comment by brentleyjones** [comment]
Related, after this is done, it would be nice to have the actual RCs listed as pre-releases in GitHub releases. I know many people that look for them there and are confused when they can't find them (or when I tell them there is a new RC, since they watch the releases on this repository and don't get notified about the RCs).

**Comment by fweikert** [comment]
Yes, that's on our todo list :)

**Comment by meteorcloudy** [comment]
Still, we should update our release scripts to publish release candidates on github, but that will likely have to wait until 7.1
