### ISSUE TITLE
Progress message no longer available in the execution logs

### ISSUE THREAD

**Issue by rsalvador** [bazelbuild/bazel#20268]
### Description of the bug:

This commit in 7.0.0rc4 removed the progressMessage from the execution log: https://github.com/bazelbuild/bazel/commit/3b0b6ed419e68046ac516c60b236624ee6f570c4
We were using this message to create a user-friendly report that shows the user the build actions executed and what inputs/outputs changed. Basically we implemented an external tool as recommended in https://github.com/bazelbuild/bazel/pull/15833
Could the progress message be put back, or a flag added to optionally add the progressMessage to the execution log?

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

build any project with `--execution_log_json_file`:
```
bazel build --execution_log_json_file=execlog.json ...
```
the `progressMessage` that was there before 7.0.0rc3 is no longer available:
```
  ...
  "cacheable": true,
  "timeoutMillis": "0",
  "progressMessage": "Building source jar util/libutil-src.jar",  <== GONE
  "mnemonic": "JavaSourceJar",
  "actualOutputs": [{
  ...
```

### Which operating system are you running Bazel on?

MacOS

### What is the output of `bazel info release`?

release 7.0.0rc4

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

https://github.com/bazelbuild/bazel/commit/3b0b6ed419e68046ac516c60b236624ee6f570c4

**Comment by tjgq** [comment]
This is a deliberate change; the execution log is too expensive to produce (even if we introduce a leaner format as discussed in #18643) so we'd prefer to exclude redundant fields entirely. The progress message seemed a good candidate because (1) the combination of target label, mnemonic and/or output file ought to be sufficient to uniquely identify the action, and (2) the progress message can still be retrieved via `bazel aquery 'mnemonic($mnemonic, $target_label)` if necessary.

**Comment by rsalvador** [comment]
Ok, will close the issue then.
