### ISSUE TITLE
Skylark: Expose `os` attribute in context

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazel#2045]
/CC @ekuefler 

`Repository_ctx` exposes this attribute already, by providing `SkylarkOS` class:

```
/** A Skylark structure to deliver information about the system we are running on. */
@Immutable
@SkylarkModule(
  name = "repository_os",
  category = SkylarkModuleCategory.NONE,
  doc = "Various data about the current platform Bazel is running on."
)
final class SkylarkOS {
```

In some cases regular (non repository) rule also requires access to this information. Say to GWT compilation rule, classpath has to be constructed:

https://github.com/GerritCodeReview/gerrit/blob/master/tools/bzl/gwt.bzl#L149

```
cmd = "external/local_jdk/bin/java %s -Dgwt.normalizeTimestamps=true -cp %s %s -war %s -deploy %s " % (
    " ".join(ctx.attr.jvm_args),
    ":".join(paths),
    GWT_COMPILER,
    output_dir,
    deploy_dir,
  )
```

But, with hard coded class path delimiter:

```
    ":".join(paths),
```

we would end up with non-portable command, that would fail on that another operating system (that expects the delimiter to be `;`) with error, like main class for GWT compiler isn't found or some such.

**Comment by ekuefler** [comment]
I notice that the Scala rules seem to have the same issue: https://github.com/bazelbuild/rules_scala/blob/6e1561e077e2f902d53cc934d4f6f2056efa0400/scala/scala.bzl#L137

**Comment by davido** [comment]
Indeed. Looks like nobody had ever tried to build Scala with Bazel on that other operating system.

**Comment by ekuefler** [comment]
Though isn't it an even more significant issue that many Skylark rules (including both Scala and GWT) use Linux commands like `cd`, `cp`, `mkdir`, etc? Unless Bazel's doing some sort of fancy emulation I can't quite see how it would be possible for Skylark rules to support windows without having a lot of dedicated work to do so for each rule.

**Comment by davido** [comment]
It's all there and is called MSYS. There is even [chocolatey Bazel package](https://chocolatey.org/packages/bazel/0.4.0) that bundles all prerequisites for you:

* MSYS
* JDK
* Python
* Bazel

Anyway, if you install all that, and clone the latest Gerrit Code Review, and try to build GWT module:

```
  $ bazel build gerrit-gwtui:ui_optdbg
```

it's failing to detect GWT compiler because of wrong delimiter char in class path construction.

**Comment by davido** [comment]
@damienmg @dslomov @aehlig

What is needed/missing to implement that feature? This prevents Gerrit Code Review (and other projects) to write platform independent Skylark rules.

**Comment by hanwen** [comment]
what is this request for? AFAICT ';' vs ':' is only relevant for Windows. Do we have a need to create a windows build of gerrit?

**Comment by davido** [comment]
Yes.

**Comment by natebosch** [comment]
+1 on being able to tell OS in a skylark rule.

We might need to do things like choose between `.sh` and `.bat` depending on the OS. The native Java rules [need to do this](https://github.com/bazelbuild/bazel/commit/775dc683615d466b565a195abc30b09d90320eb7) so skylark rules should be able to as well.

**Comment by davido** [comment]
So, I found a simple workaround for my original issue. It's already now exposed in Skylark the platform speific path separator: `ctx.configuration.host_path_separator`.

But now I'm hitting a completely different issue: classpath cnstructed is porbably too long:

```python
 cmd = "external/local_jdk/bin/java %s -Dgwt.normalizeTimestamps=true -classpath %s %s -war %s -deploy %s " % (
    " ".join(ctx.attr.jvm_args),
    ctx.configuration.host_path_separator.join(paths),
    GWT_COMPILER,
    output_dir,
    deploy_dir,
  )
```

And the command produced doesn't work on MSYS: 

```python
 ctx.actions.run_shell(
    inputs = list(deps) + ctx.files._jdk + ctx.files._zip + gwt_user_agent_modules,
    outputs = [output_zip],
    mnemonic = "GwtBinary",
    progress_message = "GWT compiling " + output_zip.short_path,
    command = cmd,
  )
```

I think the only known workaround is to do a classpath.jar with artificail MANIFEST.MF, that was donw in #2242?

[1] http://paste.openstack.org/show/619930

**Comment by laszlocsomor** [comment]
I'm removing the "Windows" label because this is feature request is independent of platforms.

As I understand it, retrieving the execution platform isn't the real issue.
The real issue is to write platform-independent skylark rules.

Looking at it like that we have at least two options:

- Expose a `ctx.os` field. **I think this approach won't work.** It'd require Bazel to know at analysis-time what execution platform it'll send the action to. In a potentially mixed remote execution system (with multiple execution platforms) this is impractical to know before execution-time.

- Support something like an execution-time `select()` on platform constraints: allow the skylark rule author to write platform-specific actions, and let Bazel choose the right one at execution-time. **I think this is the right solution.**

AFAIK Bazel supports neither of these today. Nor does it yet have a notion of execution platform(s) (where actions run) as opposed to host platforms (where Bazel itself runs). @katre's and his team's work fall into this domain, he may know more about this.

**Comment by laszlocsomor** [comment]
One more thing: the way I envision it, the rule could create entirely different action graph fragments for different platforms, producing different artifacts, while the rest of the rule logic (i.e. computing providers) could be the same or mostly the same.

**Comment by katre** [comment]
The full and complete answer is to use [toolchains](https://docs.bazel.build/versions/master/toolchains.html) and [platforms](https://docs.bazel.build/versions/master/platforms.html).

By defining the appropriate toolchains for Linux, Windows, whatever other system GWT can be compiled on, you can properly handle the platform-specific parts.

There may be a need for some more basic toolchain type built in to Bazel, which defines things like path separators, and executable extensions. It's tricky to figure out exactly what would need to be in there, however, so I don't want to start implementing too early.

Currently, select() and config_setting() do understand platforms and constraints, but only on the target platform, not the execution platform. We could consider implementing config_settings for execution platform constraints, which would then allow other ways to configure builds, but this will quickly run into problems when people try to use your rules on new systems. Toolchains are designed so that other people can add toolchains for new platforms and the rules just work. Select cannot handle that, so any attempt to build your project on a new platform would require re-writing the select statements.

**Comment by laszlocsomor** [comment]
@katre :  thanks for the detailed answer!

@davido: a workaround I came up with is to smuggle the platform information into the rule via an attribute whose value you fill using `select()`. Then in the rule implementation you can instantiate Windows- or Linux-specific actions based on the attribute's value.

**Comment by davido** [comment]
@laszlocsomor: thanks for this suggestion. Is that any better, that just use `ctx.configuration.host_path_separator` as mentioned in my previous comment?

**Comment by laszlocsomor** [comment]
@davido : i don't think it's better.

**Comment by noel-yap** [comment]
I'm also in need of having a bazel rule know the host os. In my case, it's so it can decide a value of a variable, something like:

```
DEFAULT_CLUSTER_ALIASES = {
    "local": select({
        "@platforms//os:osx": "docker-desktop",
        "@platforms//os:linux": "minikube",
    })
}
```

**Comment by meteorcloudy** [comment]
@noel-yap 
This issue was in the context of repository rule, but the example you gave here is for the build rule, can you file another issue for this? 
Maybe you what you need is similar to https://docs.bazel.build/versions/main/skylark/lib/ctx.html#target_platform_has_constraint, but for the host platform? /cc @katre

**Comment by laszlocsomor** [comment]
Also, this bug can be closed: [`repository_ctx.os`](https://bazel.build/rules/lib/repository_ctx#os) returns a [`repository_os struct`](https://bazel.build/rules/lib/repository_os) about the host OS.

**Comment by noel-yap** [comment]
@meteorcloudy , OP says, "Repository_ctx exposes this attribute already, by providing SkylarkOS class:
…
In some cases regular (non repository) rule also requires access to this information. Say to GWT compilation rule, classpath has to be constructed:
"

**Comment by katre** [comment]
You almost always actually want to know facts about the _current_ target's target platform, not the host or exec platform. In these cases, you should use [`ctx.target_platform_has_constraint`](https://docs.bazel.build/versions/main/skylark/lib/ctx.html#target_platform_has_constraint), as @meteorcloudy suggested.

If you actually care about the specific execution platform, you probably need to restructure your rule to encapsulate that information in a tool dependency.
