### ISSUE TITLE
[6.5.0] Java `--add-opens` should not be passed to javac; breaks with `-Werror`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#20468]
Forked from #19876

**Comment by iancha1992** [comment]
@hvadehra @cushon @Wyverald @meteorcloudy
I cannot cherry-pick this (https://github.com/bazelbuild/bazel/commit/367994ab9f3bb8d06a39d6bd0c139f00dcf47f3e) to release-6.5.0 because `src/main/starlark/builtins_bzl/common/java/java_common_internal_for_builtins.bzl` is missing in the branch.

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20472 @hvadehra
