### ISSUE TITLE
[6.5.0] Flip `--incompatible_visibility_private_attributes_at_definition`

### ISSUE THREAD

**Issue by mai93** [bazelbuild/bazel#20479]
### Commit IDs

- 7a537ca644ac17d565585cd4b3e21bf6243dc001
- 0656103c9bc23b627e1a49fe4544f068469f8f1b
- bc1df918074883660b74c40e0ee43db9aa0ced87
- 7b97147263700067e4397fa6c9a25318fa2e98f7

### Category

team-Rules-API

### Reviewers

@iancha1992

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/-7a537ca644ac17d565585cd4b3e21bf6243dc001
-0656103c9bc23b627e1a49fe4544f068469f8f1b
-bc1df918074883660b74c40e0ee43db9aa0ced87
-7b97147263700067e4397fa6c9a25318fa2e98f7.
Please resolve manually.
cc: @bazelbuild/triage
