### ISSUE TITLE
[6.5.0] Flip --incompatible_visibility_private_attributes_at_definition

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20480]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/7a537ca644ac17d565585cd4b3e21bf6243dc001, https://github.com/bazelbuild/bazel/commit/0656103c9bc23b627e1a49fe4544f068469f8f1b, https://github.com/bazelbuild/bazel/commit/bc1df918074883660b74c40e0ee43db9aa0ced87, https://github.com/bazelbuild/bazel/commit/7b97147263700067e4397fa6c9a25318fa2e98f7

### Category

team-Rules-API

### Reviewers

@mai93

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20481: https://github.com/bazelbuild/bazel/commit/7b97147263700067e4397fa6c9a25318fa2e98f7.
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/7a537ca644ac17d565585cd4b3e21bf6243dc001, https://github.com/bazelbuild/bazel/commit/0656103c9bc23b627e1a49fe4544f068469f8f1b, https://github.com/bazelbuild/bazel/commit/bc1df918074883660b74c40e0ee43db9aa0ced87

The failed commits are NOT included in the PR. Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
@mai93 looks like only one commit was cherry-picked since others had conflicts.

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/20520 by @mai93
