### ISSUE TITLE
Rename the new Label.local_target_label to Label.same_package_label

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20652]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/6cb2d860b025b0cfdbadb4943c8eabaff3497696, https://github.com/bazelbuild/bazel/commit/0cbf8c567c428fe4cded17b47254a923231c76e8, https://github.com/bazelbuild/bazel/commit/913b3e825f33d8c2ecbc1bba0b9927687100e48b

### Category

team-ExternalDeps

### Reviewers

@Wyverald

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/6cb2d860b025b0cfdbadb4943c8eabaff3497696, https://github.com/bazelbuild/bazel/commit/0cbf8c567c428fe4cded17b47254a923231c76e8, https://github.com/bazelbuild/bazel/commit/913b3e825f33d8c2ecbc1bba0b9927687100e48b.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
This is in regards to: https://github.com/bazelbuild/bazel/issues/16210#issuecomment-1856810839

cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
Failed commmits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/6cb2d860b025b0cfdbadb4943c8eabaff3497696, https://github.com/bazelbuild/bazel/commit/0cbf8c567c428fe4cded17b47254a923231c76e8, https://github.com/bazelbuild/bazel/commit/913b3e825f33d8c2ecbc1bba0b9927687100e48b.
Please resolve manually.
cc: @bazelbuild/triage
