### ISSUE TITLE
java_library should be able to have aar_import in its deps

### ISSUE THREAD

**Issue by aj-michael** [bazelbuild/bazel#2071]
Many Android library projects are shipping as AARs these days, even if they only contain java code (for example, https://github.com/ReactiveX/RxAndroid). As such, a java_library should be to depend on an aar_import that only provides the java code within it.

**Comment by ahumesky** [comment]
A way to do this is to write a genrule around the aar that extracts the jar and then a java_import rule around the jar.

**Comment by aj-michael** [comment]
Hmmm, alternatively we could add an implicit output for the classes_and_libs_merged.jar to aar_import.

Then you could do something like,

```
aar_import(
    name = "rxandroid",
    aar = "rxandroid-1.1.6.aar",
)

java_library(
    name = "lib",
    srcs = glob(["**.java"]),
    deps = [":rxandroid_classes_and_libs_merged.jar"],
)
```

@ahumesky , WDYT?

**Comment by ahumesky** [comment]
Hmm, I see pros and cons for both. This is a bit of a corner case so I don't feel too strongly about either. Going the jar implicit output way will keep the string "aar_import" out of the java rule code since you'd need to allow java rules to depend on aar_import, so that's a nice thing about the implicit output. And it might be nice anyway to have the jar as an implicit output.

**Comment by aj-michael** [comment]
I'm starting to think that this is a less-than-great idea. If a library does not require any Android-specific parts, it should be packaged as a JAR, not an AAR. If it is an AAR, it should not be in the deps of a java_library because either java_library would need to "know" about Android or it would drop the Android-specific parts. Neither of which is a good idea.
