### ISSUE TITLE
Add tree artifact metadata for the coverage post-processing spawn, Rewrite paths of writable directories that are under the execroot, Always add containing trees of input tree file artifacts to the metadata map

### ISSUE THREAD

**Issue by iancha1992** [bazelbuild/bazel#20818]
### Commit IDs

https://github.com/bazelbuild/bazel/commit/c48392c54a92b7bc5b04883bd6499c7a5677205d, https://github.com/bazelbuild/bazel/commit/bc1d9d38bea907beea8fd82c362c9882ddf48cfd, https://github.com/bazelbuild/bazel/commit/b0db044227d62178a7e578b8e03c452d8c17af33

### Category

team-Local-Exec

### Reviewers

@lberki

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20819: https://github.com/bazelbuild/bazel/commit/b0db044227d62178a7e578b8e03c452d8c17af33.
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/c48392c54a92b7bc5b04883bd6499c7a5677205d, https://github.com/bazelbuild/bazel/commit/bc1d9d38bea907beea8fd82c362c9882ddf48cfd

The failed commits are NOT included in the PR. Please resolve manually.
cc: @bazelbuild/triage

**Comment by bazel-io** [comment]
The following commits were cherry-picked in https://github.com/bazelbuild/bazel/pull/20820: https://github.com/bazelbuild/bazel/commit/b0db044227d62178a7e578b8e03c452d8c17af33.
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/c48392c54a92b7bc5b04883bd6499c7a5677205d, https://github.com/bazelbuild/bazel/commit/bc1d9d38bea907beea8fd82c362c9882ddf48cfd

The failed commits are NOT included in the PR. Please resolve manually.
cc: @bazelbuild/triage
