### ISSUE TITLE
Sandbox disables strict C++ header checks

### ISSUE THREAD

**Issue by jart** [bazelbuild/bazel#2092]
If I run Bazel with `--spawn_strategy=sandboxed` then I no longer get error messages about the hermeticity of cc_library rules. I.e. errors like these go poof:

```
ERROR: /usr/local/google/home/jart/.cache/bazel/_bazel_jart/534cc9069a4bd39f8bace6b1039c6506/external/jpeg/BUILD:128:1: undeclared inclusion(s) in rule '@jpeg//:simd_x86_64':
this rule is missing dependency declarations for the following files included by 'external/jpeg/simd/jsimd_x86_64.c':
  'bazel-out/local-fastbuild/genfiles/external/jpeg/jconfig.h'.
Target @jpeg//:jpeg failed to build
```

**Comment by hermione521** [comment]
Can you provide a repo for reproduce? Thanks.

**Comment by philwo** [comment]
@jart I think that is because the builds will just fail if dependencies are missing, won't they? E.g. you'll get a compiler error complaining about a missing header file, because that file won't be in the sandbox. But yes, you lose that Bazel specific "strict header checks" error message. If yes, that is WAI and I don't think we can fix it - the compiler doesn't generate the necessary information if the compilation fails.

If you mean that with --spawn_strategy=sandboxed those kind of missing dependency builds actually compile and there's no error message at all about this, then this is a P0 sandboxing bug.

**Comment by hermione521** [comment]
No response for a long time. Feel free to reopen.
