### ISSUE TITLE
Bazel can't build itself as an external dependency.

### ISSUE THREAD

**Issue by danshoutis** [bazelbuild/bazel#2103]
### To reproduce:

Create a fresh workspace, with WORKSPACE: 
```
git_repository(
    name='io_bazel',
    remote='https://github.com/bazelbuild/bazel.git',
    commit='a1699bd77f1770670eac191d701757b98556b1c5')  # v 0.4

bind(name = "protobuf/java_runtime", actual = "//third_party/protobuf:protobuf")
```
And a stub third_party/protobuf/BUILD:
```
package(default_visibility = ["//visibility:public"])
licenses(["notice"])

alias(name='protoc',
      actual='@io_bazel//third_party/protobuf:protoc')

alias(name='protobuf',
      actual='@io_bazel//third_party/protobuf:protobuf')
```

Then try to `bazel build @io_bazel//src:bazel`.

The culprit appears to be relative paths in `//third_party/grpc/BUILD:cpp_plugin`'s `CC_FLAGS`; which are tripping over the fact that in this scenario, paths to source files have the additional prefix of `external/io_bazel/`.

There's no clear workaround that I can see.

(There may be further failures too, but this is as far as I was able to get).

**Comment by kchodorow** [comment]
This will be partially solved by #1262: every repository will be a sibling in the directory structure, so a repository can always refer to files as ../reponame/path/to/file.  However, I'm starting to think that we might want to have Bazel use a repository-local execroot for actions, so that people don't always have to remember to add ../reponame to their paths.

**Comment by dslomov** [comment]
@kchodorow any chance you can take take a look at this? I can too, but I am sheriffing this week.

**Comment by jmillikin-stripe** [comment]
https://github.com/bazelbuild/bazel/pull/5703 was recently closed without being merged, but this bug is still present at master HEAD.

Partial list of things that need to be fixed:
* The CI config extensions and .bzl path calculation fixes from https://github.com/bazelbuild/bazel/pull/5703
* Use of `@//` in `third_party/` local workspaces, such as `third_party/googleapis/`. This was to be fixed by https://github.com/bazelbuild/bazel/pull/4435, but it had to be rolled back due to https://github.com/bazelbuild/bazel/issues/4678.

**Comment by meisterT** [comment]
This works now, I just tried.
