### ISSUE TITLE
No such package error messages should follow standard error output format

### ISSUE THREAD

**Issue by dmaclach** [bazelbuild/bazel#2104]
Right now errors coming out of bazel don't follow the standard "error" output format of 

filename:line:col:type: description

and instead use

ERROR: filename:line:col: description

example:
ERROR: /Users/dmaclach/src/foo/bar/bam/BUILD:22:1: no such package 'foo/bar/bam/baz': BUILD file not found on package path and referenced by '//foo/bar/bam:Private'.

It would be really nice for those of us using external systems wrapping Bazel (like Xcode) to be able to get the error in standard format so that our external systems can display them correctly in their output, and give us the ability to jump immediately to the file with the problem.

**Comment by dslomov** [comment]
@aehlig, what do you think?

**Comment by aehlig** [comment]
Adding my opinion, since I'm asked for it. But please note that a lot
of the design decissions were made before I joined the team.

> Right now errors coming out of bazel don't follow the standard "error"
> output format of 

I assume you're speaking of bazel's stderr output. One of those mentioned
earlier-made design decisions is that stderr was designed for human
consumption. (You can see this design in the fact that, depending on
what bazel guesses your terminal is capable of and command-line options
overwriting this guess, curses control characters are sent.) And, as
such a stream, it is useful for a human to first distintuish between
ERROR / FAIL and less important messsages. To mess things up even
further, the stderr of actions is also merged into this stream.

One might argue whether that was a wise decision in the first place to
have a stderr stream for human consumption (probably not), but people
started relying on this now. As a consequence of this is, attempts of
parsing bazel's stderr are fragile (to say the least) and caused lot
of problems in the past; therefore doing so is strongly discouraged.
To get out of that situtation (and also to solve other problems) there
is work in progress towards a stream describing the build designed for
machine consumption[1,2]. It will eventually also contain reports about
errors in the BUILD files.

So my suggestion is to wait for the binary protocol to be ready and try
to get forward with this. In the mean time, it would be good to stop
bikeshedding about output formats, especially as the quoted "standard
format" is not that clear a standard; bazel is not the only tool using
a different format.

[1] https://bazel-review.googlesource.com/#/c/3967/
[2] https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by dmaclach** [comment]
Closing since we are now using BEP
