### ISSUE TITLE
maven_jar/maven_aar 'settings' attribute requires absolute file path

### ISSUE THREAD

**Issue by JakeWharton** [bazelbuild/bazel#2117]
### Description of the problem / feature request / question:

The `maven_jar` and `maven_aar` rules take a `settings` attribute which points to a Maven `settings.xml` file. This is a replacement for the native `maven_jar`'s `server` and `repository` attributes. The problem is that the value of this attribute is passed to the underlying `mvn` command directly which means that it needs to be an absolute path since the `mvn` command runs deep inside the `external/` directory.

```
[ERROR] The specified user settings file does not exist: /private/var/tmp/_bazel_jw/5af54c0f74d57a8e819d551fc0d216ae/external/rxjava/my_settings.xml
```

This attribute should either be changed to support a file target _or_ the path should be normalized to the workspace directory prior to being added to the command arguments. This will allow the use of relative paths for settings files checked into the repo.

### If possible, provide a minimal example to reproduce the problem:

```
$ tree
.
├── BUILD
├── WORKSPACE
└── my_settings.xml

$ cat WORKSPACE
load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_jar")

maven_jar(
    name = "rxjava",
    artifact = "io.reactivex.rxjava2:rxjava:2.0.1",
    settings = "my_settings.xml"
)

$ cat BUILD
java_library(
    name = "example",
    srcs = glob(["*.java"]),
    deps = [
        "@rxjava//jar",
    ]
)

$ cat my_settings.xml
<settings/>
```

### Environment info
* Operating System: Mac OS 10.11.6

* Bazel version (output of `bazel info release`): release HEAD-7585552-homebrew

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

The behavior is defined here: https://github.com/bazelbuild/bazel/blob/f926f3e1f43b008e034b4e8ecd16f5935ad35434/tools/build_defs/repo/maven_rules.bzl#L182-L185

### Anything else, information or logs or outputs that would be helpful?

```
$ bazel build :example
ERROR: /Users/jw/dev/other/temp/BUILD:1:1: no such package '@rxjava//jar': Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jw/5af54c0f74d57a8e819d551fc0d216ae/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 269
		_maven_artifact_impl(ctx, "jar", _maven_jar_build_file_te...)
	File "/private/var/tmp/_bazel_jw/5af54c0f74d57a8e819d551fc0d216ae/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 243, in _maven_artifact_impl
		_mvn_download(ctx = ctx, paths = paths, fully_qual...)
	File "/private/var/tmp/_bazel_jw/5af54c0f74d57a8e819d551fc0d216ae/external/bazel_tools/tools/build_defs/repo/maven_rules.bzl", line 196, in _mvn_download
		fail("%s
%s
Failed to fetch Maven dep...))
[ERROR] Error executing Maven.
[ERROR] The specified user settings file does not exist: /private/var/tmp/_bazel_jw/5af54c0f74d57a8e819d551fc0d216ae/external/rxjava/my_settings.xml

+ mvn -s my_settings.xml org.apache.maven.plugins:maven-dependency-plugin:2.10:get -Dtransitive=false -Dartifact=io.reactivex.rxjava2:rxjava:2.0.1:jar

Failed to fetch Maven dependency and referenced by '//:example'.
ERROR: Analysis of target '//:example' failed; build aborted.
```

**Comment by aj-michael** [comment]
Again, thanks for the very detailed issue.

There is certainly a documentation problem. I intentionally have not documented the `aar_import` and `maven_aar` rules yet due to the presence of the other issue that you reported about `aar_import`.

This does not solve your problem, but the settings attribute is an optional override of the two locations that `mvn` will already look for `settings.xml`: `${maven.home}/conf/settings.xml` and `${user.home}/.m2/settings.xml`. So if the maven repository is already configured there, there is no need to pass the settings attribute.

The `settings` path is an absolute filepath because AFAIK, WORKSPACE rules do not support relative filepaths. @kchodorow is that correct, or do you know of any way to make this work?

**Comment by JakeWharton** [comment]
My use case here, which might help, is the desire to force the use of our internal artifact host / Maven central proxy for everything without needing a local machine config. Some of the dependencies that we pull are only available through this host, so if you run a build without using it you get a 404 back from Maven central. I would prefer to keep this configuration inside the repository so that it just works wherever you build.

**Comment by aj-michael** [comment]
Sorry for the delay on this. I have a potential fix. However, instead of making the settings attribute a relative path string, it makes it a label. As such, you would have to specify

    settings = "//:my_custom_settings.xml"

 Furthermore, this will require that a `BUILD` file be present at or above the directory containing the `settings.xml` so that the label is actually created. I hope to get this fix out in the next few days.
