### ISSUE TITLE
cc_configure rules do not work with Clang on Linux

### ISSUE THREAD

**Issue by shahms** [bazelbuild/bazel#2121]
### Description of the problem / feature request / question:
The cc_autoconf repository rule does not work with Clang on Linux, but rather spits out a number of warnings:
clang: warning: -Wl,-z,-relro,-z,now: 'linker' input unused

and the error:
clang: error: unsupported option '-pass-exit-codes'

I suspect there are further issues, but these are just the first encountered.  Additionally, it would be nice if the repository rule itself allowed a bit more flexibility.  I know they are experimental, but it would be nice if there was a middle ground between "entirely automatic" and "entirely manual" when configuring the C compiler to use.  Some nice-to-haves:

Compiler name (used by _find_cc).  In our case, GCC doesn't work and we need Clang.
`cxx_flags`: In particular, specifying the required version of C++ via `-std=c++11`, etc.

### If possible, provide a minimal example to reproduce the problem:
CC=/usr/bin/clang bazel build //any:cc_rule

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): release 0.4.0 (But still present in HEAD)

**Comment by mhlopko** [comment]
Hi Shahms,

Thank you for the report, I'll try to improve the clang support in cc_configure.bzl when I'll have spare cycles. If in the meantime you feel like it, feel free to tackle it yourself, cc_configure.bzl is not too complicated. If not, no worries, I will get to it eventually :)
Cheers

**Comment by PiotrSikora** [comment]
Piggybacking on this, since it's the same issue, just on different OS: builds on macOS fail if GCC is installed in the system, because Bazel prefers it over Clang (even though `/usr/bin/cc` still points to `clang`), which leads to a case when Clang-only flags are passed to GCC, because `if darwin` check in `cc_configure.bzl` should really be a `if clang` check.

**Comment by mhlopko** [comment]
Hi Piotr,

bazel doesn't look at /usr/bin/cc, but what you could do is to set CC env var to clang and blaze will take it. Altough it is probably reasonable to autodetect gcc on macOS, cc_configure.bzl can only get you so far. At some point you will have to provide your own CROSSTOOL file with all the specific requirements of your environment. Luckily, we are making CROSSTOOL more expressive and nicer to work with almost every day now :)

**Comment by PiotrSikora** [comment]
Marcel, but my problem is not with (lack of) auto-detection of GCC on macOS, it's with the fact that Bazel prefers GCC over Clang (i.e. behavior changes without any changes to Bazel usage, depending on whether or not GCC is available in the `$PATH`), which results in failed builds, because the checks in `cc_configre.bzl` are platform-specific and not compiler-specific.

**Comment by mhlopko** [comment]
I see, that is indeed incorrect. I'll take a look once I get rid of some higher priority issues in my queue. Thanks Piotr!

**Comment by mmlac** [comment]
Created a minimal patch adding `-pass-exit-codes` through the `_add_option_if_supported` guard.
https://bazel-review.googlesource.com/#/c/8070/

**Comment by mhlopko** [comment]
Thanks Markus so much!  Importing.

**Comment by mhlopko** [comment]
This looks fixed to me, please shout if it's not true.
