### ISSUE TITLE
Add support to allow credential helper to return of JSON payloads larger than 4K

### ISSUE THREAD

**Issue by RiverPup** [bazelbuild/bazel#21287]
### Description of the feature request:

It seems that the current implementation of credential helper only works for the return of JSON payloads less than 4K. JSON payloads larger than 4K will cause the credential helper call to hang and timeout.

### Which category does this issue belong to?

CLI, Remote Execution

### What underlying problem are you trying to solve with this feature?

Credential helper JSON payloads greater than 4K are timing out.

### Which operating system are you running Bazel on?

Windows and Linux

### What is the output of `bazel info release`?

version 6.3.1 to 7.x

**Comment by tjgq** [comment]
The issue here is that Bazel reads the credential helper output from a pipe, and we don't start reading from the pipe until the process terminates. So if the response is too big to fit in the pipe buffer, we deadlock and timeout.

I can think of two possible fixes: increase the size of the pipe buffer or read the response in a separate thread that does its own buffering. Either way, we definitely want to cap the response size at some sane value (say, 64KB).
