### ISSUE TITLE
py_binary's srcs_version is ignored

### ISSUE THREAD

**Issue by justbuchanan** [bazelbuild/bazel#2132]
I have a python binary that is only compatible with python2, so I set the `srcs_version` to "PY2ONLY".  However, the script is still getting run with python3.

Here's the `BUILD` file:

~~~python
py_binary(
    name = "script",
    srcs = ["script.py"],
    srcs_version = "PY2ONLY",
)
~~~

And `script.py`:

~~~python
import sys
v = sys.version_info
print(v)
if v.major != 2:
    raise RuntimeError("Not using python 2!")
~~~

When I run `bazel run :script`, the exception gets raised and the version info that prints shows that it is being run with python 3.5.2.

My computer is running Arch Linux with both python 3.5.2 and python 2.7.12 installed.  Note that `/usr/bin/python` is a symlink to `python3`, which may be causing this issue.

**Comment by iirina** [comment]
Hi Justin,

the `srcs_version` attribute doesn't tell Bazel what Python version to use, it is used only to ensure that the source files  listed in the `srcs` of the rule are compatible with the given `srcs_version`. In your case it checks whether your source file is compatible with python2, which it is.

The default Python version is `Python2`, but it calls `python` by default. So it will call `python3`, since you have a symlink to `/usr/bin/python`. You can change the path of `python2` using the command line flag `python2_path`. You can find more information about this [here](https://www.bazel.io/docs/command-line-reference.html) (look for `python2_path`).

Cheers,
Irina

**Comment by justbuchanan** [comment]
Hi iirina,

Thanks for the explanation, that makes sense now.  I think the `python2_path` flag is just what I was looking for!

Cheers,
Justin
