### ISSUE TITLE
[7.2.0] cquery: more precise results

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#21776]
Forked from #16310

**Comment by gregestren** [comment]
It turns out this was already 

You can verify by running [one of](https://github.com/bazelbuild/bazel/blob/b5f463e694e37313cb2266d2dde95117eb428d67/src/test/java/com/google/devtools/build/lib/query2/cquery/ConfiguredTargetQuerySemanticsTest.java#L634) the tests  https://github.com/bazelbuild/bazel/commit/81e1333c2e4e0f7db7cf3e38be750fe8cc58420c introduced:

```
$ git checkout release-7.2.0
$ bazelisk test  //src/test/java/com/google/devtools/build/lib/query2/cquery:ConfiguredTargetQuerySemanticsTest --test_filter=testAspectDepsAppearInCqueryDeps
```

You can also verify with

```
$ bazelisk (synced to 7.2.0) cquery --experimental_explicit_aspects //...
```

and check there's no "flag doesn't exist" error.

Recall this functionality is experimental and lots of queries probably won't work well. I'd start with the most basic `deps(//foo)` or maybe `somepath(//foo, //bar)`. Feedback on breakages welcome, as well as willingness to patch fixes.
