### ISSUE TITLE
Make `bazel mod tidy` work with `include()`

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/bazel#22063]
After https://github.com/bazelbuild/bazel/pull/21855 is in, we'll need to address the case where `include()`d files need tidying. This would require Bazel itself to generate proper fixup events for included files (potentially only for extension proxies that are bound to a variable, IOW 'exported'), and for Buildozer to properly handle files that are MODULE.bazel-like but not exactly named "MODULE.bazel" (per discussion in the PR, they would be called `foo.MODULE.bazel`).

**Comment by fmeum** [comment]
Since every repo can only be `use_repo`ed in a single segment and the extension proxy needs to have been exported in the same segment, could we do the following?

1. For every import to remove, obtain the file that contained the `use_repo` and emit a `use_repo_remove` command for that file and the particular extension proxy.
2. For every import to add, find the first file with an extension usage (of the correct prod/dev) type for it and add the `use_repo_add` command for it.
3. For all segments, emit a `format` command.

**Comment by Wyverald** [comment]
Sounds good to me!

**Comment by Wyverald** [comment]
@bazel-io fork 7.2.0
