### ISSUE TITLE
Bazel HEAD broke rules_apple dynamic framework linking

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/bazel#22095]
### Description of the bug:

Starting with https://github.com/bazelbuild/bazel/commit/128c8635150d13a37e930fe1b94be96d9c42acff,  **rules_apple** CI is failing: https://buildkite.com/bazel/rules-apple-darwin/builds/9096#018f084c-cec2-4925-bc13-3c36134ece02

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In **rules_apple**:

```
$ USE_BAZEL_VERSION=last_green bazelisk build //test/starlark_tests/targets_under_test/ios:basic_framework_with_dynamic_framework_dependency

...

ERROR: /Users/brentley.jones/Developer/rules_apple/test/starlark_tests/targets_under_test/ios/BUILD:3564:22: Linking test/starlark_tests/targets_under_test/ios/basic_framework_with_dynamic_framework_dependency_bin failed: (Exit 1): wrapped_clang failed: error executing ObjcLink command (from target //test/starlark_tests/targets_under_test/ios:basic_framework_with_dynamic_framework_dependency) external/apple_support~~apple_cc_configure_extension~local_config_apple_cc/wrapped_clang ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
ld: Undefined symbols:
  BasicFramework.BasicFramework.__allocating_init() -> BasicFramework.BasicFramework, referenced from:
      DirectDependencyWithDynamicFrameworkTest.DirectDependencyTest.directDependencyTest() -> () in libbasic_framework_with_dynamic_framework_dependency_lib.a[2](DirectDependencyTest.swift.o)
  type metadata accessor for BasicFramework.BasicFramework, referenced from:
      DirectDependencyWithDynamicFrameworkTest.DirectDependencyTest.directDependencyTest() -> () in libbasic_framework_with_dynamic_framework_dependency_lib.a[2](DirectDependencyTest.swift.o)
```

This works though:
```
USE_BAZEL_VERSION=latest bazelisk build //test/starlark_tests/targets_under_test/ios:basic_framework_with_dynamic_framework_dependency
```

### Which operating system are you running Bazel on?

macOS

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

https://github.com/bazelbuild/bazel/commit/128c8635150d13a37e930fe1b94be96d9c42acff

**Comment by allevato** [comment]
Odd, there's no special logic in the `AppleDynamicFramework` provider so translating it to a Starlark `provider` should be a no-op. Would you be able to provide print outs of the providers on dynamic framework target before and after the commit, so I can see what's different between them?

**Comment by allevato** [comment]
Actually, this line looks very suspicious: https://github.com/bazelbuild/rules_apple/blob/6e357422f99947c37716f69d8221d69d0397d8f6/apple/internal/ios_rules.bzl#L1659

This is a logic error in those rules, because that kind of provider runtime reflection isn't supported by Bazel, to my knowledge. At least for any Starlark provider `p`, `type(p)` will **always** return `"struct"`. The fact that it worked with native providers isn't a feature meant to be relied on as a general feature.

There's no blessed way to ask "was this instance of a provider created by this specific `provider` function". Can you update that function to take the `AppleDynamicFramework` provider as an explicit argument instead of passing in a list and extracting it? If not, you may need to do something like a few `hasattr` checks to see if the provider "looks like" the one you want.

**Comment by luispadron** [comment]
Thanks for the info!

Trying to fix it over here: https://github.com/bazelbuild/rules_apple/pull/2453 with an `hasattr` check.
