### ISSUE TITLE
Should disable request with Range to use remote_downloader

### ISSUE THREAD

**Issue by hunshcn** [bazelbuild/bazel#22207]
### Description of the bug:

I'm using https://github.com/chainguard-dev/rules_apko. It depends on Range download. (2 ways, credential_helper or headers attr(>=7.1.x)(processing https://github.com/chainguard-dev/rules_apko/pull/56)

But Remote API do not support Range download.

There seems to be no solution at present.

I can think of two paths.
1. add Range support for Remote API.
2. it is forbidden for Range request to use remote_downloader.(it can be intelligent, or it can be a no_remote_downloader, just like a no_proxy).

### Which category does this issue belong to?

Remote Execution

### Which operating system are you running Bazel on?

macos

### What is the output of `bazel info release`?

7.1.1

**Comment by tjgq** [comment]
At this time, we'd prefer to avoid making the download logic header-dependent (because it opens the door for doing the same for other HTTP headers, in the limit bringing the full complexity of the HTTP spec into Bazel). Can you open a feature request for Range header support at https://github.com/bazelbuild/remote-apis?

I'm also wondering why rules_apko must download individual artifacts via Range requests (which is a bit of an odd thing to do) instead of using a separate URL for each; if a rules_apko maintainer could comment here, it would help us understand how to prioritize this in the future.

**Comment by harshita-gupta** [comment]
> I'm also wondering why rules_apko must download individual artifacts via Range requests (which is a bit of an odd thing to do) instead of using a separate URL for each; if a rules_apko maintainer could comment here, it would help us understand how to prioritize this in the future.

I'm not a `rules_apko` maintainer, but can comment on this. See the [`Alpine` section of this blog post](https://blog.aspect.build/custom-download-headers#heading-alpine) by @thesayyn from [Aspect](https://github.com/aspect-build/)

It's necessary to use range headers when fetching packages for Linux Alpine. Per the APK format spec*, **_alpine packages are formatted as archives, which are always multiple gzip streams of tars combined_**. See the [apk spec](https://wiki.alpinelinux.org/wiki/Apk_spec) for more on the format of these binaries. This format is somewhat similar to `.deb` archives.

This issue is important because it essentially captures "remote downloads in bazel cannot support fetching alpine packages and `.deb` archives", which is a fairly major limitation. 

This is a big drawback for those of us who use bazel remote execution; we're limited in how we can use bazel as a source-of-truth for hermetic builds of distroless-style lightweight base images 


* for those not already familiar, apk is the package manager for alpine linux

**Comment by harshita-gupta** [comment]
@tjgq would it be possible to re-evaluate this issue given the info provided above? ^

**Comment by tjgq** [comment]
Thanks for the additional context! However, I maintain my opinion that the best way forward is to add Range support to the Remote Asset API.

**Comment by harshita-gupta** [comment]
created https://github.com/bazelbuild/remote-apis/issues/305
