### ISSUE TITLE
OS X Sandbox should mount ~/Library/Logs and ~/Library/Cache read-write by default

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2231]
Most of the tutorial failures come from tools trying to write there and getting permission denied. See #2189 for more context.

**Comment by damienmg** [comment]
Assigning to Philip since @hermione521 is busy with coverage.

**Comment by philwo** [comment]
I think we can make these paths read-write without decreasing hermeticity of builds (much). I'll send a patch.

Of course it would be even better if we could mount a private tmpfs there, so that tools can write there, but the written files won't persist, but I don't know of any way how to do this on macOS.

**Comment by damienmg** [comment]
+1 if we can do with tmpfs but meh :/

**Comment by philwo** [comment]
Fix is in code review.
