### ISSUE TITLE
Support SOURCE_DATE_EPOCH

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2240]
This is a placeholder to investigate how SOURCE_DATE_EPOCH should be used in Bazel.

See https://reproducible-builds.org/specs/source-date-epoch/

I am just filing for now and will investigate later.

/cc @infinity0

**Comment by damienmg** [comment]
Just replacing all the stamping information should do it.

**Comment by ixdy** [comment]
I see that there was a commit to add some support for `SOURCE_DATE_EPOCH` to bazel, but it's not clear how this can be consumed by stamping rules, since it does not appear in stable-status.txt or volatile-status.txt.

It also seems that `BUILD_TIMESTAMP` is still reflecting the actual build time, which is possibly intentional.

**Comment by damienmg** [comment]
Right now the only support we have is to set the timestamp when building
Bazel. I have a few thoughts on how to implement it across Bazel but I did
not got around to do it yet.
