### ISSUE TITLE
Kleaf broken with Bazel 7.2.0-rc2

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#22600]
Possible culprit is https://github.com/bazelbuild/bazel/pull/22407

```
mkdir android-kernel && cd android-kernel
repo init -u https://android.googlesource.com/kernel/manifest -b common-android-mainline
repo sync # Around 15 minutes
bazel build //common:kernel_kythe --//common:kernel_kythe_corpus=android.googlesource.com/kernel/superproject//common-android-mainline
```
The above requires first replacing the bazel binary at `prebuilts/kernel-build-tools/bazel/linux-x86_64/bazel-7.2.0rc1-linux-x86_64` with `rc2`, keep the same file name when replacing (i.e. `bazel-7.2.0rc1-linux-x86_64`), so that the symlinks don't break (or fix the symlinks).

More info about building the kernel: https://source.android.com/docs/setup/build/building-kernels. 

Error log: https://ci.android.com/builds/submitted/11909039/kleaf_kythe/latest/view/logs%2Fbuild.log

**Comment by oquenchil** [comment]
@fmeum

**Comment by oquenchil** [comment]
I can confirm that d98b02ec09 is the culprit.

**Comment by oquenchil** [comment]
@metti @jacky8hyf

It looks like `/tmp/bazel-source-roots` is hardcoded in your build scripts. This is an implementation detail that was used with the previous implementation of hermetic tmp. The old implementation had bugs, an obvious one is that if you wrote a symlink from an action when everything is under `/tmp` even if that doesn't correspond to the real path on the  system, when the action finishes the symlink wouldn't point to the real file but to the mounted path which wouldn't exist anymore.

Could you please remove the hardcoding of `/tmp/bazel-source-roots` from your scripts? Alternatively if you need something mounted there you could pass the flag `--sandbox_add_mount_pair`, without being familiar with your build scripts I couldn't say exactly what value you'd need to pass to that flag though.  Could you please look into this?

**Comment by keertk** [comment]
@bazel-io fork 7.2.0

**Comment by jacky8hyf** [comment]
https://ci.android.com/builds/submitted/11909039/kleaf_kythe/latest/view/logs%2Fbuild_error.log

FTR this is the publicly visible log

**Comment by jacky8hyf** [comment]
The action and the line failing is this:

https://cs.android.com/android/kernel/superproject/+/common-android-mainline:build/kernel/kleaf/impl/kernel_kythe.bzl;l=106;drc=75b9a4916b360ba5683783f5a0e222302eb0e214

runextractor and cxx_extractor are described here: https://kythe.io/examples/#runextractor-tool though I can't find their sources at this moment. cxx_extractor is the one invoking clang.

**Comment by jacky8hyf** [comment]
I think I found the root cause. I added `file common/arch/arm64/crypto/aes-ce-core.S; realpath common/arch/arm64/crypto/aes-ce-core.S` to the KernelBuild action, and this is the output:

```
rc1:
common/arch/arm64/crypto/aes-ce-core.S: symbolic link to /mnt/sdc/android/kernel/out/bazel/output_user_root/1b6b21355d7d8de5177bf0bcb725bd7f/execroot/_main/common/arch/arm64/crypto/aes-ce-core.S
/mnt/sdc/android/kernel/common/arch/arm64/crypto/aes-ce-core.S

rc2:
common/arch/arm64/crypto/aes-ce-core.S: symbolic link to /tmp/bazel-source-roots/0/common/arch/arm64/crypto/aes-ce-core.S
/tmp/bazel-source-roots/0/common/arch/arm64/crypto/aes-ce-core.S
```

Kbuild gen_compile_commands.py always [puts the realpath of the given source file](https://cs.android.com/android/kernel/superproject/+/common-android-mainline:common/scripts/clang-tools/gen_compile_commands.py;l=176;drc=dae4a0171e25884787da32823b3081b4c2acebb2) ([patch](https://patchwork.kernel.org/project/linux-kbuild/patch/20231206012034.833057-2-xujialu@vimux.org/)) in the generated `compile_commands.json` file. To eliminate the ir-reproducibility and make sure the file makes sense across different actions, we attempt to drop the **"source tree root"** and replace it with a dummy variable in KernelBuild action, then restore the dummy variable with actual $PWD (execroot) in the KernelKythe action.

The trick in https://r.android.com/2952813 used to work because the source tree root is always `/tmp/bazel-source-roots/number`, so it is easy to drop it. But with rc2, the source tree root becomes the real workspace root (in my case it is /mnt/sdc/android/kernel/), causing the issue.

The fix would be to find out the real workspace root and drop it. But I haven't figure out a way to do this cleanly.

**Comment by jacky8hyf** [comment]
I am reverting the upstream [[v3] gen_compile_commands.py: fix path resolve with symlinks in it](https://patchwork.kernel.org/project/linux-kbuild/patch/20231206012034.833057-2-xujialu@vimux.org/) as a workaround.  This is done in [ANDROID: Revert^3 "gen_compile_commands.py: fix path resolve with symlinks in it"](http://r.android.com/3110403).

**Comment by jacky8hyf** [comment]
> @metti @jacky8hyf
> 
> It looks like `/tmp/bazel-source-roots` is hardcoded in your build scripts. This is an implementation detail that was used with the previous implementation of hermetic tmp. The old implementation had bugs, an obvious one is that if you wrote a symlink from an action when everything is under `/tmp` even if that doesn't correspond to the real path on the system, when the action finishes the symlink wouldn't point to the real file but to the mounted path which wouldn't exist anymore.
> 
> Could you please remove the hardcoding of `/tmp/bazel-source-roots` from your scripts? Alternatively if you need something mounted there you could pass the flag `--sandbox_add_mount_pair`, without being familiar with your build scripts I couldn't say exactly what value you'd need to pass to that flag though. Could you please look into this?

The change [Kleaf: Hack: Match all combinations for ROOT_DIR](https://r.android.com/2952813) is not the culprit; it is simply not effective any more after rc2, but it doesn't do any harm either. I reverted it in the same topic only because it is not useful any more after [ANDROID: Revert^3 "gen_compile_commands.py: fix path resolve with symlinks in it"](http://r.android.com/3110403)..

**Comment by oquenchil** [comment]
Fixed by @jacky8hyf . Thank you!

**Comment by jacky8hyf** [comment]
Hi,

Our builds are fixed with various hacks. However, I just want to mention that we really like the original behavior that 
- mounts the source root under `/tmp/bazel-source-roots` so that `realpath` on a source file always yields a path under `/tmp/bazel-source-roots` 
- runs an action with $PWD at `/tmp/bazel-working-directory`

This is because it greatly helps with:

- Reproducibility. Sometimes paths to sources sneaks in to the built artifacts. If it is always `/tmp/bazel-working-directory` then we get consistent artifacts. (Internal bug https://issuetracker.google.com/346559442 and https://issuetracker.google.com/345452375; and this bug with the `//common:kernel_kythe` target https://issuetracker.google.com/343803993)
- Shorter paths in error logs, if we are supplying realpaths of sources to toolchains (internal bug https://issuetracker.google.com/231936415)

This feature automatically solves or mitigates many of these issues. So, we hope the Bazel team can consider bringing back that feature in the future, possibly via some flags (e.g. --sandbox_add_mount_pair).
