### ISSUE TITLE
Remote cache / execution require manually passing SHA1 bazel.DigestFunction

### ISSUE THREAD

**Issue by ivucica** [bazelbuild/bazel#2261]
### Description of the problem / feature request / question:

With Bazel 0.4.2, one is unable to use `--rest_cache_url` out of the box.

### If possible, provide a minimal example to reproduce the problem:

```bash
bazel build --rest_cache_url http://localhost:1234 //src:libunix
```

Output:

```
ERROR: Remote cache/execution requires SHA1 digests, got MD5, run with --host_jvm_args=-Dbazel.DigestFunction=SHA1
INFO: Elapsed time: 0.041s
FAILED: Build did NOT complete successfully
```

Error also does not make it clear that the flag needs to be specified as a startup flag.

```bash
bazel --host_jvm_args=-Dbazel.DigestFunction=SHA1 build --rest_cache_url http://localhost:1234 //src:libunix
```

### Environment info
* Operating System:

   ```bash
    $ cat /etc/lsb-release 
   DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
    ```

* Bazel version (output of `bazel info release`):
    ```
    release 0.4.2
    ```

    Installed from the official apt repository.

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

This is [actually documented](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/README.md), but it still very painful.

Can you, please, either make remote execution and remote cache not dependent on SHA1 (perhaps using keys such as "md5-HASH_HERE" or "sha1-HASH_HERE"), or fix it so that Bazel is smart enough to use the correct hash as required?

**Comment by dslomov** [comment]
@philwo @kchodorow what is the right category for this request? what is the priority?

**Comment by ola-rozenfeld** [comment]
Hey Ivan! The general problem here is that a particular remote execution implementation will depend on a particular hashing function, and the function needs to be a startup flag, because it affects how digesting is done in the Bazel server. In other words, you cannot run one Bazel command with one digest function and another command with another function, unless you restart the server every time.

Now, because the current remote execution code in Bazel is no more than a prototype, I cloud make it work with both hash functions. But that would be misleading -- in the end, we do need to specify one, and it has to match the one in the startup options.

In the long run, we plan for this option, as well as other remote execution options, to be set automatically based on the WORKSPACE configuration.

In the mean time, why is specifying the startup option a pain? Can I maybe improve the wording of the error message, e.g. add the words "startup option" in the end?

Thank you!

**Comment by hhclam** [comment]
I think in the long run Bazel should just use SHA1 hashing by default. md5 has security issues.

In the mean time you can put this in  your .bazelrc:
`startup --batch --host_jvm_args=-Dbazel.DigestFunction=SHA1`

**Comment by kchodorow** [comment]
(Removing myself, since this is related to remote execution.)

**Comment by damienmg** [comment]
Side-note: please do not add this as a workspace configuration. That should be a bazel flag (so people configure it with .bazelrc)

**Comment by ishikhman** [comment]
This is not an issue anymore. Please feel free to reopen the issue otherwise.
