### ISSUE TITLE
feature request: environment variable for setting output_base or output_user_root

### ISSUE THREAD

**Issue by jowagner** [bazelbuild/bazel#2274]
Having to type --output_base or --output_user_root each time using bazel when $HOME is on NFS is annoying. $TEST_TMPDIR could be used but maybe there are unexpected side effects with bazel or other software as this variable is intended for running unit tests.

Desired behaviour:
bazel checks not just for $TEST_TMPDIR but also for another variable intended and documented for normal use.

I tried to work around the problem with a shell alias:
```
export BAZEL_OUTPUT_BASE="/tmp/${USER}-bazel-cache"
mkdir -p "${BAZEL_OUTPUT_BASE}"
alias bazel="bazel --output_base=${BAZEL_OUTPUT_BASE}"
```
but this fails because bazel commands like "fetch" and "clean" must go before the first option.

Related issues:
 * issue #2042

**Comment by kchodorow** [comment]
Can you set it in your user's or project's .bazelrc?

**Comment by mhlopko** [comment]
Friendly ping @jowagner, is setting the flag in the .bazelrc working for your case?

**Comment by jowagner** [comment]
Thanks. In December, I worked around the problem with a symlink from ~/.cache/bazel to /tmp/bazel...

I don't have time to fully understand https://bazel.build/versions/master/docs/bazel-user-manual.html but the warnings about NFS are gone when I add the line 

`startup --output_base=/tmp/bazel-Se4j7kiUhyiZii4`

to .bazelrc and create the target folder. (For this test, I removed ~/.cache/bazel from the previous bazel runs and configured and started the build process for TensorFlow.)

The output_base appears to be used during building (currently 924 MB and rising). Still, ~/.cache/bazel was created as well and takes about about 131 MB (the size has not changed over the last 2 minutes of building TensorFlow).

**Comment by mhlopko** [comment]
Ok that sounds good. Thanks!

**Comment by riklopfer** [comment]
The symlink work around worked for me as well. 

```shell
rm -rf $HOME/.cache/bazel
ln -fs /tmp/${USER}.bazel $HOME/.cache/bazel
```

**Comment by ddj116** [comment]
Late to the party but wanted to ask if there's a better way to solve this problem now.  For our use case we're trying to deploy `bazel` across a large lab environment, and `$HOME/` is NFS so the default cache location `$HOME/.cache/` is not an option. On our systems, we want the cache to default to `/local/$USER/bazel_cache`, so my naive solution was to deploy this `/etc/bazel.bazelrc` with the rpm as part of the installation process:

```
startup --output_base=/local/$USER/bazel_cache/ 
```
However, `$USER` is interpreted literally since ENV vars aren't supported in the `bazelrc` notation, so the cache location isn't user-specific as we intended.  The ability to tell bazel system-wide to use an alternate cache path specifically using the value of `$USER` is what I'm looking for. 

The only other alternative path I can think of is to instead deploy hundreds of `~<user>/.bazelrc` files which use the hardcoded paths:
```
startup --output_base=/local/<user>/bazel_cache/ 
```
This is a bit of a pain since really what we're after is a system-level default config, not a user-specific config.  Is there a better way to get what we want? Thanks!
