### ISSUE TITLE
[bazel.build] Intermittent issue while trying to fetch remote blob 

### ISSUE THREAD

**Issue by ashukumar0712** [bazelbuild/bazel#22822]
### Page link:

https://bazel.build/remote/cache-remote

### Problem description (include actual vs expected text, if applicable):

I am trying to run bazel build with remote cache option, but seems like build is failing quite often with below error types.

`BUILD.bazel:3:11: GoCompilePkg go/vms/mgmt/common/apiproxy/go_default_library.a failed: Failed to fetch blobs because they do not exist remotely.: Missing digest: fbd40ec8dbe0ae82202efcc85ed2eb1f6a8fbaaf9eea4e5be3cbb67337097bf4/349056 for bazel-out/k8-opt/bin/go/lib/api_cloud_connector_client/go_default_library.x`

Option which I am passing is only --remote_cache . bazel remote cache is running on EKS cluster. 

### Where do you see this issue? (include link to specific section of the page, if applicable)

CI tool : Gitlab ( kubernates executor ) 
OS : Ubuntu

**Comment by tjgq** [comment]
This error should only happen if Bazel has previously observed the blob to exist in the remote cache, but it has since been deleted. If your remote cache can spuriously evict blobs, you might want to experiment with the `--experimental_remote_cache_ttl` and `--experimental_remote_cache_lease_extension` flags to avoid running into this.
