### ISSUE TITLE
Remote downloader does not respect the digestFunction in the grpc response.

### ISSUE THREAD

**Issue by hunshcn** [bazelbuild/bazel#22863]
### Description of the bug:

after https://github.com/bazelbuild/bazel/pull/21996

FetchBlobResponse.DigestFunction will declare the digestFunction of BlobDigest.

But Remote Downloader will still use sha256sum for blob of other digest.

And will always get error
```
Output null download failed: Expected digest '5de5a7e869ace4c69059d8fe0b87eec6ea3f21ccbc72487e0700088a3857d8b2911c7b753ae72d2cb2e507417810f8b9e66d885093539eff051fd912048ece83/1311' does not match received digest '9ade2f118703e4115bc1226fb366b06365130f3f04832cebe0d82ffd9008ff33/1311'
```

### Which category does this issue belong to?

Remote Execution

### Which operating system are you running Bazel on?

macos

### What is the output of `bazel info release`?

7.2.0/latest

**Comment by tjgq** [comment]
The spec says that `FetchBlobRequest.digest_function` is `The digest function the server must use to compute the digest`. Should we interpret this as a `MUST`, or is it actually a `SHOULD`? Is there a reason a server might not be capable of honoring the hash function that was requested by Bazel?

cc @sluongng since he authored this part of the spec.

**Comment by sluongng** [comment]
I don't mind loosening up the spec from `must` to `should`.

However, I do want to note that we are only using `must` in the client-initiated request, the same client is expected to call `GetCapabilities` rpc to know which digests the server could handle. So the client should not be making requests with digest_function that the server did not advertise in the first place.

In Bazel case, I think we are currently doing this in `RemoteModule.java`: we create a `downloaderChannel` before creating a GrpcRemoteDownloader. The `downloaderChannel` creation verifies which digest function is being used against the server capabilities.

I guess it's possible that the `rctx.download_and_extract` was declared to use a different `integrity` than Bazel's own `startup --digest_function=`? If that's the case, then Bazel should/could verify the digest declared in `integrity` to see if it matches with remote downloader capabilities and perhaps opt for a direct download (plus warning) if it does not match?

**Comment by hunshcn** [comment]
I really didn't notice `must`. But I think it should be loosened to `should`.

Let's think about this example.
`startup --digest_function=sha256`, but have http resource with sha512 integrity. (This is very common when we use rules_js. Integrities of all packages are sha512.)
Then request this like
```
qualifiers:
  name: "checksum.sri"
  value: "sha512-aaaaaaaaaa"
digest_function: "SHA256"
```
If remote cache sever use SHA256 as hasher, server will store the asset in cas using key "sha256-bbbbb". And never be hit every next time.

In this scenario, the server should need to use sha512 digestFunction.

**Comment by sluongng** [comment]
@hunshcn please take a closer look into how `downloaderChannel` was created inside `RemoteModule.java`

https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/RemoteModule.java;l=704-705;drc=0814308a619d68dd16b3a958ec5347d6f8d3457e

It should take you to `GoogleChannelConnectionFactory.getAndVerifyServerCapabilities()` where the digest function is verified against server capabilities.

https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/GoogleChannelConnectionFactory.java;l=106;drc=b5c273acbbaea9dbf6c218ec98b1310e0dde442e

```
qualifiers:
  name: "checksum.sri"
  value: "sha512-aaaaaaaaaa"
digest_function: "SHA256"
```

This scenario is special.

First of all, is a request valid if the checksum qualifier uses a different digest than the digest_function? I have discussed this with @EdSchouten in the past and he kindly commented:

> It’s completely reasonable to say: “Please download this file, which has MD5 sum bla, and store it in this remote cache which uses BLAKE3”

So that's fine.

However, should the client initiate a request with (a) qualifier that the server does not support and (b) digest_function that the server does not support?

For (a), it should be "yes". In REAPI `qualifiers.md`, it states:

> This lexicon defines standard qualifier names that servers
**MAY** support in the `Qualifier` message to facilitate interoperability.

so the qualifier could be optionally verified by the server.

For (b), it should be "no". Because there is no way the server would be able to cache/validate such a request. Note that the fetch response does not return a bytestream array, but merely a `blob_digest`, which is a reference to the actual object in the cache. So if the server cannot compute the digest and store it in the cache, then it should not be able to make a valid response.

**Comment by hunshcn** [comment]
For this scenario
```
qualifiers:
  name: "checksum.sri"
  value: "sha512-aaaaaaaaaa"
digest_function: "SHA256"
```

Cache server has two processing methods.

A. digest with sha512. The next request will hit the cache. 
B. digest with sha256 and return. Cache the asset with sha256 digest. And also digest with 512. If it's equal to value of `checksum.sri`, make cas/sha512/aaaaa -> cas/sha256/bbbbb ?

This issue is put forward according to A.
So do you think the server should follow B?
@sluongng

**Comment by sluongng** [comment]
First, Bazel would have to call `GetCapabilities` RPC to check what the server is capable of. This will return `ServerCapabilities -> CacheCapabilities -> digest_functions`, a list of digest functions the server supports.

If the server supports both `[SHA512, SHA256]`, then the request could be made by the client (Bazel). The server will download the blob from the upstream remote. It could _optionally_ hash the downloaded blob with SHA512 and validate the hash based on the given qualifier value. If this _optional_ validation fails, then the server could return an error to the client indicating the issue. Then it would have to hash the blob again using SHA256 to store it in the CAS backend, before returning the `FetchBlobResponse` to the client with the SHA256 `blob_digest`. 

If the server only supports `[SHA256]`, the client could still send the same request. The server will ignore the qualifier and do the same as in the scenario above.

If the server does NOT support `[SHA256]`, the client should not request the server to use SHA256 digest function. The client should instead pick another supported digest function as the server advertised in its capabilities. If the client still tries to make a request using a not-supported digest function, the server could simply be returning an error as it does not have any way to hash and store the blob into its CAS.

See how https://github.com/bazelbuild/remote-apis/blob/main/build/bazel/remote/asset/v1/qualifiers.md defined that the qualifier support is optional for the server with `servers MAY support`.

**Comment by sluongng** [comment]
Actually there is this paragraph here

```
  // Servers *MUST* ensure Fetch'd content matches all the specified
  // qualifiers except in the case of previously Push'd resources, for which
  // the server *MAY* trust the pushing client to have set the qualifiers
  // correctly, without validation.

...

  // In the case of unsupported qualifiers, the server *SHOULD* additionally
  // send a [BadRequest][google.rpc.BadRequest] error detail where, for each
  // unsupported qualifier, there is a `FieldViolation` with a `field` of
  // `qualifiers.name` and a `description` of `"{qualifier}" not supported`
  // indicating the name of the unsupported qualifier.
```

So the qualifier might not be "optional" after all.

This means for the 2nd case, where the server only supports `[SHA256]`, the server should return a BadRequest response. 🤔 

cc: @EdSchouten am I reading this correctly?

**Comment by hunshcn** [comment]
Thank you. I think I understand what to do. Close this.

**Comment by sluongng** [comment]
Here is an interesting question: if a user or a rule tells Bazel to use a remote asset downloader service, while giving the `rctx.download()` API a non-SHA-256 digest, then what should Bazel do in that case? I.e. rules_js is using SHA-512 is a good example.

Bazel check downloader service capabilities, see SHA-512 not supported, and then:

Option 1: still send the request but skip the unsupported qualifiers. Once downloaded, Bazel validates the blob SHA512 locally.

Option 2: Bazel skips the downloader service entirely and downloads the assets directly. Validate the blob SHA512 locally after download.

Option 3: Bazel error out. By either sending the invalid request to get server's BadRequest response, or skip sending the request entirely.

I think option 3 + skip sending the request might be ideal here? WDYT @tjgq?
