### ISSUE TITLE
[feature request] Allow users to add extra extension names for C/C++ toolchains.

### ISSUE THREAD

**Issue by ahyangyi** [bazelbuild/bazel#2298]
Hi,

One of the reasons that I am still using an internal fork of Bazel is that we need to support CUDA programs with their .cu extensions. As CUDA is deeply integrated with C/C++ toolchains, and is usually supposed to be linked together with C/C++ object files with shared headers, it does not really make sense to treat it as a separate language.

My current solution to support CUDA is that I modified Bazel to include ".cu" as another file extension to indicate a C++ source file. Then I grabbed a wrapper from Tensorflow and slightly modified it so it would call `nvcc` when a `.cu` file is given and call `gcc` otherwise.

This works nicely. However, I believe there's some insight in this home-baked solution: a simple feature that allows us to instruct Bazel to **treat some file extensions in the same way as some existing extensions**, would enable users to   support the many existing C/C++ compatible languages without reinventing the wheel that is C/C++ toolchain support.

Thanks.

**Comment by mhlopko** [comment]
@lberki Wdyt?

**Comment by lberki** [comment]
We'll eventually need to do this. The original motivation is not source files, but that output files (object files, libraries, executables and such) have different extensions in different operating systems. And once we have that, it's not a big stretch to extend the same thing to source files, too.

**Comment by hlopko** [comment]
This has been already done (we still require the extension to be from a limited set). I see `artifact_name_pattern` is not documented on https://docs.bazel.build/versions/master/crosstool-reference.html so I'll leave this issue open to improve the docs.

**Comment by Riatre** [comment]
IIUC `artifact_name_pattern` controls what @lberki mentioned above, but the original feature request is slightly different, it asks for adding extra extensions for input source files instead of artifacts, so I don't think this has been already done and is a documentation-only issue.

To be more precise, what is requested here is to allow modifying `com.google.devtools.build.lib.rules.cpp.CppFileTypes.CPP_SOURCE` and `CPP_HEADER` (adding `.cu` and `.cuh` correspondingly) without patching Bazel itself.

**Comment by celentes** [comment]
Friendly ping. What is the status on this?

Various compilers introduce different extension names for different kind of inputs/outputs, e.g. emscripten can compile libraries into .bc files and executable output is going to be several files of .js, .wasm and some optional extras, which currently need to be resorted to workarounds when working with bazel.
I feel like all of that configuration should be specified in the toolchain providers rather than hardcoded in bazel internals for each different os/arch/compiler combination.

What is the motivation behind restricting these?

**Comment by oquenchil** [comment]
I think different actions are triggered depending on the extension. Last time someone sent a PR to remove all checks, we got tests failing internally in our mono-repo because of the way a file with an assembly extension was being handled. We won't spend time on this for now but you are welcome to investigate a refactoring that would remove the restriction while keeping current behavior, i.e.: which actions are triggered by which files stays the same.
