### ISSUE TITLE
Platform-based flags are cached incorrectly

### ISSUE THREAD

**Issue by tpudlik** [bazelbuild/bazel#22995]
### Description of the bug:

Bazel fails to rebuild affected targets after changes to the `flags` attribute of `platforms`. @katre @gregestren 

### Which category does this issue belong to?

Configurability

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

https://github.com/tpudlik/pbf_cache_example is a minimal example with instructions for reproduction.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 8.0.0-pre.20240618.2

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

Not a regression, platform-based flags are a new feature.

### Any other information, logs, or outputs that you want to share?

We ran into this in a (small) real project: https://pwbug.dev/352389854

**Comment by katre** [comment]
Definitely concerning: I'm back from vacation today and will take a look.

**Comment by katre** [comment]
Okay, I can reproduce that, it's very odd. Looking into it today.

**Comment by katre** [comment]
Hmm, this is interesting.

The actual error from the invalid flag comes from [`SkyframeExecutor.createBuildConfigurationKey`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/SkyframeExecutor.java?q=symbol%3A%5Cbcom.google.devtools.build.lib.skyframe.SkyframeExecutor.createBuildConfigurationKey%5Cb%20case%3Ayes), which creates the initial top-level configuration based on the command line (and bazelrcs, etc).

During the sequence here, we see:
1. The `platform` has only valid flags: `SkyframeExecutor.createBuildConfigurationKey` is called, creates a configuration object, and returns it.
2. The `platform` has invalid flags: `SkyframeExecutor.createBuildConfigurationKey` is called, **finds a previously-created configuration object**, uses that and continues.

It looks like calling into skyframe at this point is **before** any invalidation checking due to changed file, but I'm not sure, I need to check with the experts. An important question (which I can check) is whether or not [`BuildConfigurationKeyFunction`](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/config/BuildConfigurationKeyFunction.java?q=BuildConfigurationKeyFunction&ss=bazel) is being called again or not.

I suspect this is actually worse: I suspect that edits to change flags in  avalid way are also being ignored.

**Comment by katre** [comment]
Current ideas I am investigating:
1. Clear the cache at the start of every build
2. Hoist the cache into ConfiguredTargetFunction so that it isn't static but has a shorter lifetime
   1. I'm worried about making it too short
3. Skyframe magic (I've reached out to the experts to find out if anything useful exists)
   1. The best idea would be to invalidate the cache if the requested PlatformMappingValue.Key or ConfiguredTargetKeys are invalidated, but I don't know if this is detectable

I'll update when I know more.
