### ISSUE TITLE
Documentation of "manual" tags is misleading

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#2303]
From [bazel-discuss@googlegroups.com](https://groups.google.com/d/msgid/bazel-discuss/CAM%3Ddnvctotra2VL_oG3-g-ukegYf1r47GcYF3PF_ReqFwDja%3DA%40mail.gmail.com?utm_medium=email&utm_source=footer):
```
https://bazel.build/versions/master/docs/bazel-user-manual.html

Targets with tags=["manual"] will not be included in wildcard target patterns (..., :*, :all, etc). You should specify such test targets with explicit target patterns on the command line if you want Bazel to build/test them.

Either the documentation or the behavior should be fixed.
```

Make people thinks that manual tags applies to build target but it only applies to test target in fact (for running them, not building them).

**Comment by trimbo** [comment]
FWIW, I think it would be nice to have explicit build targets

**Comment by ohler** [comment]
I just tested this with bazel 0.4.2, and as far as I can tell, targets with `tags=["manual"]` are in fact excluded if I run `bazel build //path/to/package/...`.  This is true both for (customized versions of) go_library targets and go_test targets.  This seems like the desired and expected behavior.  Is the bug just about documenting it unambiguously, or are there cases where targets marked "manual" aren't being excluded?  The bug description suggests the latter, but I can't reproduce it.

**Comment by mboes** [comment]
See #707.

**Comment by Globegitter** [comment]
Yeah it is interesting, it does seem to work for some rules but not for others. It does work for example for `py_image` but not for `par_binary` or `py_library`. Would be great if that would work consistently for all targets.

**Comment by elklein** [comment]
Also, I discovered that `manual` tags aren't taken into account for wildcards in queries. For example `cquery somepath(//..., //some/package/...)` will wind up dredging up all sorts of targets with manual tags (that wouldn't otherwise be in the build graph). You have to use --build_tag_filters to manually filter out manual targets when using queries with wildcard paths. That is not what I would have expected.

**Comment by matshch** [comment]
@bazelbuild/triage it is still not obvious, and probably should be more consistent.
