### ISSUE TITLE
generate_workspace doesn't include runtime dependencies of maven artifact

### ISSUE THREAD

**Issue by tigersoldier** [bazelbuild/bazel#2316]
example:
bazel run //src/tools/generate_workspace -- --artifact=org.mockito:mockito-core:2.4.2

mockito-core has 4 runtime dependencies, none were generated.

**Comment by petroseskinder** [comment]
I believe the cause of this issue is this [line](https://github.com/bazelbuild/bazel/blob/master/src/tools/generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/Resolver.java#L156) in the Maven Resolver:

```java
public Model resolveEffectiveModel(ModelSource modelSource, Set<String> exclusions, Rule parent) {
    Model model = modelResolver.getEffectiveModel(modelSource, handler);
    ...
    for (Dependency dependency : model.getDependencies()) {
      if (!dependency.getScope().equals(COMPILE_SCOPE)) {
        continue;
      }
    ...
    }
```

Any maven dependencies that aren't [scoped](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) for compile time are ignored.
