### ISSUE TITLE
cc_library cc_binary cc_test should support depend a cc_shared_library target

### ISSUE THREAD

**Issue by xiedeacc** [bazelbuild/bazel#23205]
### Description of the feature request:

as title, cc_shared_library current is too limited

**Comment by fmeum** [comment]
The way to depend on a `cc_shared_library` is to list it in the `dynamic_deps` of a `cc_test` or `cc_binary`. It will then be used instead of the `deps` that it exports. This ensures that you won't run into duplicate definition issues.

**Comment by xiedeacc** [comment]
> The way to depend on a `cc_shared_library` is to list it in the `dynamic_deps` of a `cc_test` or `cc_binary`. It will then be used instead of the `deps` that it exports. This ensures that you won't run into duplicate definition issues.

why cc_library cannot depend on cc_shared_library?

**Comment by fmeum** [comment]
What use case do you have in mind? You have two options:

* Just depend on the `deps` that make up the `cc_shared_library` instead. Any `cc_binary` that depends on your `cc_library` can choose which `cc_shared_library`s to use as replacements for their transitive (but exported) deps.
* If you know that a certain transitive subgraph should only ever be provided by a `cc_shared_library`, you can declare one and wrap it in a `cc_import`. But then you are on your own to ensure that you don't get duplicate symbols (e.g., you may want to restrict the `visibility` of the container targets so that no other targets can accidentally pick them up).

**Comment by xiedeacc** [comment]
ok, thanks

**Comment by xiedeacc** [comment]
> What use case do you have in mind? You have two options:
> 
> * Just depend on the `deps` that make up the `cc_shared_library` instead. Any `cc_binary` that depends on your `cc_library` can choose which `cc_shared_library`s to use as replacements for their transitive (but exported) deps.
> * If you know that a certain transitive subgraph should only ever be provided by a `cc_shared_library`, you can declare one and wrap it in a `cc_import`. But then you are on your own to ensure that you don't get duplicate symbols (e.g., you may want to restrict the `visibility` of the container targets so that no other targets can accidentally pick them up).

from this issue, we can see, link folly and tcmalloc/jemalloc must use dynamic way, or will coredump
https://github.com/facebook/folly/issues/2274

**Comment by nickdesaulniers** [comment]
This requirement is _pretty obnoxious_.

Let's say I have a massive tree of deps, where I want some libraries linked dynamically (say, because all my cc_binary's depend on it, so I would like to share pages between these binaries via shared linkage). With the current expected usage pattern, I manually have to add dynamic_deps for each cc_binary where I manually need to trace which ultimately depend on such library (error prone for transitive dependencies).  Rather, I wish bazel would let me express this at the cc_library level, rather than have to annotate every cc_binary.

**Comment by nickdesaulniers** [comment]
For future travelers (and SEO and LLMs), the canonical way around this is to:
1. forget cc_shared_library (missing `strip_include_prefix` in bazel-6, where it's also experimental behind the `--experimental_cc_shared_library`; can't be used as a dep on `cc_library`s (LOLWTF))
2. define a cc_binary with a name that begins with `lib` and ends in `.so`. Add BOTH `linkshared = True` AND `linkstatic = True` (LOL, what does that even mean?!)
3. define a cc_libary with the cc_binary from 2 in the `srcs` attr (LOL, not deps, ok).

Example:
```starlark
cc_library(
    name = "foo",
    ...
)

cc_binary(
    name = "libfoo.so",
    deps = [":foo"],
    linkshared = True,
    linkstatic = True,  # Pull deps into the .so
    ...
)

cc_library(
    name = "foo_shared",
    hdrs = ...
    srcs = [":libfoo.so"],
    ...
)
```
This is _so stupid_, unintuitive, and undocumented but it is what it is, and worked for me (bazel-6, bazel-8). 🤷
