### ISSUE TITLE
Provide the 'pkg_zip' rule that is already suggested in the documentation.

### ISSUE THREAD

**Issue by Helcaraxan** [bazelbuild/bazel#2336]
The documentation for [packaging rules](https://bazel.build/versions/master/docs/be/pkg.html) suggests that the `pkg_zip` should be provided later on in Bazel's development.

With the ongoing stabilization effort for Bazel on Windows I think it would be great if this rule is added in the near future as ZIPs are the more usual package format for that platform.

It could for example be used to package libraries build with Bazel in order to export them easily as an end-product / build-artifact.

**Comment by petemounce** [comment]
That would be really useful.

**Comment by dslomov** [comment]
@kchodorow is this the right category for this request?

**Comment by ulfjack** [comment]
I think the report is that pkg_zip doesn't work on Windows yet, and that we need to make it work. That suggests the multi-platform > windows category. Is that correct?

**Comment by j3parker** [comment]
Would it be cool if I picked this one up?

**Comment by laszlocsomor** [comment]
AFAICT there's no `pkg_zip` rule at all, neither internally nor in public Bazel.
Google-internal version has a `genzip` rule though, not sure if the comment in the documentation that @Helcaraxan linked meant to reference that.

@kchodorow : Do you know of any plans to opensource `genzip`?

**Comment by ulfjack** [comment]
I apparently misread the original post. :-/

Personally, I prefer the name pkg_zip over genzip, but we might want to try to match the current genzip feature set; otherwise migration will be a lot harder for us. There are no plans to opensource genzip that I know of, and it's unfortunately not trivial because it depends on some other rules (pkg_library, pkg_symlink, pkg_directory, and pkg_runfiles) that contain functionality that is specific to Google, and not actually useful (or used) for genzip.

Ideally, we'd come up with a way to hide / remove the extra functionality and open source the pkg_* rules. :-/

As for genzip, it's using a Python script to do the actual zipping - the zip command-line tool is just not flexible enough to allow us to everything we want directly (e.g., renaming files on the fly, removing timestamp for determinism).

**Comment by ulfjack** [comment]
Moving to rules > misc native, but there's not really an owner for this.

**Comment by j3parker** [comment]
Ah, okay. My plan was to mirror the `pkg_tar` implementation (mostly) and do it in Python with `zipfile` (depending on the `zip` CLI probably also sucks because its not necessarily available...)

But if there is co-ordination that needs to happen with an internal rule it probably doesn't make sense for an external contributor. Let me know if you decide differently :)

**Comment by johnynek** [comment]
python is not hermetic, no? Will such a rule be safe to run?

**Comment by ulfjack** [comment]
Python can be hermetic. We're working on funneling all uses of tools though *_toolchain rules, which can refer to hermetic or non-hermetic toolchains. At Google, we use checked-in Python interpreters, which should also work with Bazel - but it's a bunch of work to implement.

Another hermetic option is to use docker containers for execution (it's hermetic in the sense that if we add the container id to the action cache entry, we correctly detect if you're running with a different docker container and re-run the actions), which is supported in the remote worker, and the remote execution protocol, though not currently from Bazel itself (we should add that to Bazel, and probably also make sure that the id is in the action cache).

That said, while using a local python is non-hermetic, it's also fairly unlikely to cause problems for simple pure-python tools, like for zipping a bunch of files.

**Comment by GinFungYJF** [comment]
Any updates ?

**Comment by mzeren-vmw** [comment]
FWIW the nomulus project has a `zip_file` rule:
https://github.com/google/nomulus/tree/master/java/google/registry/builddefs

**Comment by meisterT** [comment]
> Bazel binary distros (or the rule releases) could include a pre-built binary for it to mollify users with that complaint.

Please don't include more tools in the bazel binary unless really necessary. We want to cut down size as much as possible.

**Comment by aiuto** [comment]
This should be done in bazelbuild/rules_pkg.

**Comment by dslomov** [comment]
Filed as https://github.com/bazelbuild/rules_pkg/issues/30
