### ISSUE TITLE
6.5.0 documentation is starting to wither away

### ISSUE THREAD

**Issue by grepwood** [bazelbuild/bazel#23480]
### Page link:

https://bazel.build/versions/6.5.0/rules/lib/builtins/repository_ctx

### Problem description (include actual vs expected text, if applicable):

It should not be 404. There are still people who have barely migrated from 5.x.x.

### Where do you see this issue? (include link to specific section of the page, if applicable)

On the specified link

### Any other information you'd like to share?

Please stop pre-emptively burning the documentation for older releases.

**Comment by Wyverald** [comment]
cc @fweikert

The old page is actually still there (https://bazel.build/versions/6.5.0/rules/lib/repository_ctx -- note the missing `builtins` segment between `lib` and `repository_ctx`); the new version selector makes it go to the "imaginary" new URL.

I wonder if this is as simple as fixing the `set_var` clause in the 6.5.0 pages? Also need to figure out why the navbar on the left is empty.

**Comment by meteorcloudy** [comment]
Yeah, for older docs, please start navigating from https://bazel.build/versions/6.5.0

**Comment by fweikert** [comment]
There are two problems:

1. Because of https://github.com/bazelbuild/bazel/commit/6dbac49ef52c1cb142779c2ef0e26a04170f6330 the generated Starlark docs prior to 7.x have a different layout. The only solution is adding redirects.

2. Between 6.2 and 6.3 the left navbar disappeared: https://bazel.build/versions/6.2.0/reference/be/overview vs https://bazel.build/versions/6.3.0/reference/be/overview

**Comment by fweikert** [comment]
Both of the aforementioned issues have been fixed.

There is still a problem, though: Whenever we introduce new Starlark symbols, the version selector will lead to 404 errors when switching to versions that don't contain these symbols yet. I guess we need to set up another bunch of redirects when 8.0 comes out.
