### ISSUE TITLE
Expand `experimental_add_exec_constraints_to_targets` to support mnemonics

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#23606]
### Description of the feature request:

`--experimental_add_exec_constraints_to_targets` is super useful for some things like "give all these targets this constraint", but for some custom rules it would also be useful to do this for entire mnemonics. For example if you have a custom rule that always does a heavy compilation action, adding a large remote exec machine constraint to all targets of that type can be useful. This can be done with exec_groups but sometimes it's desirable to do this only temporarily like if you want to run a set of tests against a machine with a GPU just once.

**Comment by katre** [comment]
Okay, first, the actual answer to your request: this isn't possible, because exec constraints are relevant before actions are created, and so before action mnemonics are known.

The flow during analysis is (roughly):
1. Toolchain resolution
   1. Based on the configuration, the requested toolchain types, and any target-specific exec constraints, the specific toolchain implementations and exec platforms are chosen
2. Other dependencies are resolved
3. The rule implementation is invoked
   1. The rule implementation then creates actions, based on the dependencies and toolchains from the previous steps.

Because of this, it's not possible to check mnemonics and add exec constraints, and if it were possible, it would be too late.

**Comment by katre** [comment]
Secondly, the `--experimental_add_exec_constraints_to_targets` flag was added for a migration that is now completed, and barring any heavy use I think we should get rid of it now.
