### ISSUE TITLE
[7.4.0] Fix the documentation for `bazel fetch --configure`

### ISSUE THREAD

**Issue by bazel-io** [bazelbuild/bazel#23666]
Forked from #23665

**Comment by iancha1992** [comment]
> Cherry-pick was attempted but there were merge conflicts in the following file(s). Please resolve manually.
> 
> `site/en/extending/repo.md` `third_party/cncf_udpa/BUILD`
> 
> cc: @bazelbuild/triage

@fmeum @Wyverald @meteorcloudy

**Comment by fmeum** [comment]
Something is wrong here, this commit shouldn't have touched third_party

**Comment by meteorcloudy** [comment]
@iancha1992 Can you try to manually cherry-pick https://github.com/bazelbuild/bazel/commit/c04a5617d2c960e19177d6299f00a81624857925?

**Comment by iancha1992** [comment]
> @iancha1992 Can you try to manually cherry-pick [c04a561](https://github.com/bazelbuild/bazel/commit/c04a5617d2c960e19177d6299f00a81624857925)?

@meteorcloudy @fmeum  I am getting the merge conflicts in the same files as well.

**Comment by meteorcloudy** [comment]
We probably need https://github.com/bazelbuild/bazel/commit/1ab2c824e54fd27896f14c5257ab737815463dc1 as well, /cc @Wyverald

**Comment by meteorcloudy** [comment]
@iancha1992 Can you try to cherry pick https://github.com/bazelbuild/bazel/commit/1ab2c824e54fd27896f14c5257ab737815463dc1 and then https://github.com/bazelbuild/bazel/commit/c04a5617d2c960e19177d6299f00a81624857925?

**Comment by iancha1992** [comment]
@meteorcloudy I am having a same issue because the two files changes from https://github.com/bazelbuild/bazel/commit/c04a5617d2c960e19177d6299f00a81624857925 are `site/en/extending/repo.md` and `src/main/starlark/builtins_bzl/common/xcode/semantics.bzl.oss`. But after cherry-picking the https://github.com/bazelbuild/bazel/commit/1ab2c824e54fd27896f14c5257ab737815463dc1, and while cherry-picking the https://github.com/bazelbuild/bazel/commit/c04a5617d2c960e19177d6299f00a81624857925, `third_party/cncf_udpa/BUILD`, instead of `src/main/starlark/builtins_bzl/common/xcode/semantics.bzl.oss` is having a merge conflict. Is this okay?

This is the draft PR that has the cherry-picked commit, https://github.com/bazelbuild/bazel/commit/1ab2c824e54fd27896f14c5257ab737815463dc1: https://github.com/bazelbuild/bazel/pull/23723

**Comment by iancha1992** [comment]
@meteorcloudy
Looks like `src/main/starlark/builtins_bzl/common/xcode/semantics.bzl.oss` also isn't in the `release-7.4.0` branch yet

**Comment by meteorcloudy** [comment]
@iancha1992 I see, then let's ignore the change in `src/main/starlark/builtins_bzl/common/xcode/semantics.bzl.oss` and only make sure `site/en/extending/repo.md` is up-to-date.

**Comment by Wyverald** [comment]
I'll send a PR -- a lot of doc updates were never cherry-picked to the 7.x branches.

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/23741
