### ISSUE TITLE
visibility on external repositories

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#2369]
As far as I can see now, when one has defined an external repository, the entire repo can see that and depend on things in that external repository.

It would be nice to have visibility so that we can scope who can see an external repository.

One use case: I need to have two versions of a particular jar. One old version for a few projects, and one current version. The old version may be shaded with jarjar or the like so I actually only want the shading rule to be able to see it.

A second use case: I want to minimize the use of external deps for very special use cases. So, I don't want every target to just start depending on an external dep, when possibly another, internal dep would do.

**Comment by kchodorow** [comment]
Yeah, right now you could put the visibility on the targets (e.g., `@foo//:x` has limited visibility) but it might be nice to have visibility available at a repository level.

**Comment by brandjon** [comment]
It kind of sounds like you want different BUILD/.bzl files in the same repo to have different views on what external repos are available. This is not planned.

You could probably get something similar with a target visibility that specified some but not all packages of an external repo. Personally I think it's dubious to provide visibility that is greater than the current repo but less than fully public, since the author of the visibility declaration may not be the same as the person deciding what repos are imported by what names. Maybe this makes sense in some cases though.

On a related note, the upcoming bzlmod proposal by @Wyverald will likely have strict deps for repo dependencies, so you can avoid propagating the repo names you import to everyone downstream of you.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
