### ISSUE TITLE
Include pruning doesn't work

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#2372]
...as reported by @werkt on bazel-discuss.

He also has a pull request outstanding (https://github.com/bazelbuild/bazel/pull/2243), but I tried to implement the same by myself thinking that it's a trivial matter and ended up stuck in the mud in `CppCompileAction`.

Also unfortunately, a large part of our test cases is internal-only (no big secrets, simply haven't found time to open source yet) so one of us is probably in a better position to tackle the issue. I'll see if I can get to it this week. I think I have fixed the last failing test case!

@janakdr 
@mhlopko

**Comment by lberki** [comment]
We don't have the same optimization even internally. Well, we do, but only in our remote execution backend, which arguably is out of scope.

**Comment by lberki** [comment]
I also have the change cleaned up and I sent it for review internally. Hopefully people smarter than me won't discover any issues with it :)

**Comment by janakdr** [comment]
To respond a little more to the question of @user28657 , as you say, all available headers are part of the CppCompileAction [key computation](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java#L1243). But this is true whether or not include scanning is available, because a priori changing the set of headers could lead to a new header being picked up. I suppose we could do a later check, after include scanning, that didn't include that set as part of the key, but that's not currently a feature.

**Comment by ulfjack** [comment]
I'm afraid that the change caused Bazel to recompile on every re-analysis or server shutdown. I will need to disable the code for now as the fix is more complicated, and I need to wait for another change to land.

**Comment by ulfjack** [comment]
Actually, let me close this one again - I'm working on the fix in #2490, so please follow that if you're interested.
