### ISSUE TITLE
Potential racy pid writing

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2383]
Looking at where the Bazel Server writes the pid to `server.pid.txt` (in `blaze_util_posix.cc`), I was wondering why there is no file locking or similar done.

I would have expected something along the lines of `createPidFile` from _tlpi_ (isn't that the goto implementation by now?).
Since I am not the biggest *nix guru, how is it ensured without locking, that the pid writing is not racy 😕 ?

**Comment by lberki** [comment]
This is tricky, but is actually working as intended, as far as I can tell. We do use `flock()`:

https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze.cc#L1339

And we keep the lock held until we have started talking to the server:

https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze.cc#L1616

Server startup and thus the `ExecuteDaemon()` call happens in between the two and is thus protected by the lock. 

The reason we relinquish the lock is so that we can eventually support running multiple commands at the same time. It's a long-standing feature request internally and TBH, it's kinda embarrassing that we can't even run `bazel help` in parallel with a build. Now the only thing that remains until that is possinble is some refactoring of the `BlazeModule` interface, which @ulfjack is doing in his copious free time.

**Comment by abergmeier-dsfishlabs** [comment]
> The reason we relinquish the lock is so that we can eventually support running multiple commands at the same time.

So you mean having multiple Server instances running on the same machine in the same cwd?

**Comment by lberki** [comment]
No, it's two running commands for the same server. The aforementioned locking makes sure that there is only one server instance for the same output base.

As a sidenote, you *can* run two server instances for the same source tree by making them have different output bases with the `--output_base` command line option. This works and is well supported.
