### ISSUE TITLE
[7.4.0] Cherrypick --incompatible_autoload_externally implementation

### ISSUE THREAD

**Issue by comius** [bazelbuild/bazel#23905]
### Commit IDs

f9ed0b03269ee5364f01e1d177129e4597ba0a48
cc3ba22c3e9256dc2d9f419e25c9b653d7f81577
7e1393937c56ca25ad678851ec0de93c913eae7d
0f6d0d839381e9ccee5fd8857c449d6d76ba8714
38239d9d71eefb577c3966d17a4fbaae3eedf4fb
3cb5beaa1550896e0df54d00b66ea215b1e47048
3bc5dea1f0e9105489c641c72f322b9e17548b94
7518bbb4a67021ec8efcc64e74ebaa72074311d9
963e7a230aa31c06e3c4d695e9eb5f9947c8fd6e
ae0274497028964751310f4fd15117953bf30806
8d3bd0e0f95f2abeb9b6d9fc8b32ab4af717fa0f

### Category

team-Rules-API

### Reviewers

@hvadehra @Wyverald

**Comment by bazel-io** [comment]
Failed commits (likely due to merge conflicts): https://github.com/bazelbuild/bazel/commit/f9ed0b03269ee5364f01e1d177129e4597ba0a48
cc3ba22c3e9256dc2d9f419e25c9b653d7f81577
7e1393937c56ca25ad678851ec0de93c913eae7d
0f6d0d839381e9ccee5fd8857c449d6d76ba8714
38239d9d71eefb577c3966d17a4fbaae3eedf4fb
3cb5beaa1550896e0df54d00b66ea215b1e47048
3bc5dea1f0e9105489c641c72f322b9e17548b94
7518bbb4a67021ec8efcc64e74ebaa72074311d9
963e7a230aa31c06e3c4d695e9eb5f9947c8fd6e
ae0274497028964751310f4fd15117953bf30806
8d3bd0e0f95f2abeb9b6d9fc8b32ab4af717fa0f.
Please resolve manually.
cc: @bazelbuild/triage

**Comment by comius** [comment]
Additional cherry-pick: dbb9670fb2719323c3e9b5df8ab045d187cf8c63

**Comment by comius** [comment]
And: 84c15a00d4a756fb82af5079b4e71f5cf933fe94

**Comment by iancha1992** [comment]
Cherry-picked in https://github.com/bazelbuild/bazel/pull/23906
