### ISSUE TITLE
Runfiles Tree Structure

### ISSUE THREAD

**Issue by ilinam** [bazelbuild/bazel#2437]
Hi,

We recently began the process to upgrade our bazel from 0.2.3 to 0.4.3, and I see that the runfiles tree structure has changed, as documented here:

https://github.com/bazelbuild/bazel/wiki/Updating-the-runfiles-tree-structure

Would it be possible to add back support for the --legacy_external_runfiles flag? We have to manually change a lot of paths in our source code otherwise, as currently our binaries look for data resources directly under the .runfiles directory, which is now broken.

Thanks,
Ilina
@mzhaom

**Comment by laszlocsomor** [comment]
Hi Ilina,

I don't think we would add it back -- we probably phased it out so we wouldn't have to maintain the logic behind it in the future, and/or to fix/avoid bugs. (I'm not aware of the exact reasons in this particular case, but these tend to be the motivating factors.)

Is there any reason preventing you from updating the source files to use the newer style paths?

**Comment by ilinam** [comment]
Well, we have to fix the file paths in a lot of source files to support the new file structure, so we were hoping there would be some way to support the legacy structure too. I suppose we'll just have to schedule a FIX IT to transition all the source files to use the new style paths. Thanks for your prompt response!

**Comment by mzhaom** [comment]
Even if a decision has been made and this issue is closed, I would still like to make my comment here, :)

I think such a change is to give a nice feature provided by bazel, which is the test and genrule used to have a same view of the source tree no matter whether it's run through bazel, or run manually through bazel-bin/foo/bar_test. Now with this change, to access a data file located in the source tree, there is no universal way to access the data files, which is really annoying.

Btw, have you convinced your internal users to accept this change?

**Comment by kchodorow** [comment]
I'm working on getting #1262 in, whcih will make runfiles & execution root consistent (and chops off the external/repo prefix for srcs).  So, once that's in it should be even more "universal."

This has no effect on internal users.
