### ISSUE TITLE
Changes to `--credential_cache_duration` don't take effect until `clean` or `shutdown`

### ISSUE THREAD

**Issue by tjgq** [bazelbuild/bazel#24437]
Originally reported by @acecilia in https://github.com/bazelbuild/bazel/issues/23368:

It looks like, if using `--credential_helper`, when a credential is cached with:
```
common --credential_helper_cache_duration=60m
```

Changing to:
```
common --credential_helper_cache_duration=0
```

Does not have effect: the credential stays cached. Will only take effect after running `bazel clean` or `bazel shutdown`

**Comment by tjgq** [comment]
I looked into the code history for this feature, and it's not clear to me that `--credential_helper_cache_duration` was ever intended to affect existing cache entries; I believe it was only meant to provide a default for new insertions. It's also not obvious to me that it makes sense to retroactively update existing entries (especially if the original expiration was provided by the credential helper and not the command line flag).

However, I acknowledge that it's convenient to be able to clear the cache without running a `clean` command. Therefore I'm willing to compromise by declaring that `--credential_helper_cache_duration=0` also has the effect of clearing the cache (but any other value will not retroactively update entries).

@acecilia @Yannic does that sound like a reasonable compromise?

**Comment by Yannic** [comment]
I think that‘s a reasonable approach, yes.

I‘d probably make it < 0 to clear the cache though TBH as I can see setting it to 0 being useful for debugging a helper

**Comment by Yannic** [comment]
I think it would also be reasonable to discard and reject a stale read if the cache duration changes. Not sure how hard that‘d be to implement though. Either approach is fine with me

**Comment by acecilia** [comment]
I would say the proposed solution will not solve the current confusing behaviour of the flag. I could argue it makes it more confusing, as there will be a magical value for this flag (zero) that will have one behaviour (clear the cache), while all others values wont.

> compromise by declaring that --credential_helper_cache_duration=0 also has the effect of clearing the cache

Is there a difference in terms of complexity, between the proposed solution, and clearing the cache every time the flag changes value? I think the latter would be a more expected behaviour, as the common in bazel is that -> invalidate the cache when inputs change.

If latter is not possible, I personally find it more clear to treat all values in the same way, and would vouch for leaving the flag as-is now, maybe just improving its documentation

**Comment by tjgq** [comment]
I'm also fine with clearing the entire cache whenever the value of the flag changes. I'll move forward with that version.
