### ISSUE TITLE
Windows: Visual Studio should not be a requirement, only MSVC

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#2448]
Bazel currently looks for an installed Visual Studio, but it actually only needs the C++ compiler.
Microsoft offers that as a standalone product: http://landinghub.visualstudio.com/visual-cpp-build-tools

We should make do with just that if the user doesn't have VS installed.

**Comment by petemounce** [comment]
That would be great. I try to avoid installing VS onto build machines because of the sprawl and time required.

**Comment by laszlocsomor** [comment]
Do you if the Build Tools is the leanest compiler installation?

**Comment by petemounce** [comment]
Unfortunately, I don't know for sure, no.

**Comment by meteorcloudy** [comment]
I did some investigation on this.

I completely uninstalled Visual Studio, including manually deleting some environment variables set by the installer, eg. `VS140COMNTOOLS`. 

Then I installed Visual C++ 2015 Build Tools, the build tools are installed in the same place as in Visual Studio.
But `reg query HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0 -v InstallDir` no longer returns the VS install directory, which means our current way of detection won't work.

However, I found a script named `vcvarsqueryregistry.bat` who knows how to find VC install directory properly and it set `VCINSTALLDIR` env as result. The script is always located at `%VS140COMNTOOLS%` directory. And even the VC++ build tool installer would set `VS140COMNTOOLS` env. (Might be `VS120COMNTOOLS`, `VS110COMNTOOLS`... if you have different version of VS or VC++ installed) So I think this could be the new approach of MSVC detection.

And since we don't require Visual Studio, it's better we let users set `BAZEL_VC` env instead of `BAZEL_VS`.

Besides, for Visual Studio 2017, the build tool layout is quite different, I'll do more work on that. A related blog is here:
https://blogs.msdn.microsoft.com/vcblog/2016/10/07/compiler-tools-layout-in-visual-studio-15/

**Comment by laszlocsomor** [comment]
Awesome, thanks @meteorcloudy . SGTM on every account.

**Comment by laszlocsomor** [comment]
I clean-installed Windows on a machine, and only installed the VC Build Tools. After setting `BAZEL_VS`, it works like a charm.

**Comment by meteorcloudy** [comment]
Ha, that's actually expected! Because the install path doesn't change. But if `Bazel_VS` is not set, the auto configuration will just fail. I am working on this! ;)
