### ISSUE TITLE
genrule fails with non-existent path using `--build_tests_only` on Windows

### ISSUE THREAD

**Issue by avdv** [bazelbuild/bazel#24546]
### Description of the bug:

In a genrule, trying to run a command which gets expanded from a template variable results in an error when using Bazel >= 7.3.0:

```
C:/b/bk-windows-j20f/bazel-org-repo-root/output/rules_sh-0.5.0/tests/sh_binaries/BUILD.bazel:3:23: Executing genrule //sh_binaries:genrule failed: (Exit 127): bash.exe failed: error executing Genrule command (from target //sh_binaries:genrule)
...
/usr/bin/bash: line 1: c:\\b\\3mrahdhj\\execroot\\_main\\bazel-out\\x64_windows-fastbuild\\bin\\sh_binaries\\hello_world.exe.runfiles/_main/sh_binaries/hello_world: No such file or directory
```

Note the path looks fishy: `c:\\b\\3mrahdhj\\execroot\\_main\\bazel-out\\x64_windows-fastbuild\\bin\\sh_binaries\\hello_world.exe.runfiles/_main/sh_binaries/hello_world`

Removing the `--build_tests_only` flag makes this work.

cc @fmeum 

### Which category does this issue belong to?

Local Execution

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

You can use rules_sh as reproducer (I'll try to give a minimal example later):

1. `gh repo clone tweag/rules_sh`
2. `cd rules_sh/tests`
3. `bazel test --build_tests_only ...`

### Which operating system are you running Bazel on?

Windows

### What is the output of `bazel info release`?

7.3.0 - 7.4.1

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

Bisecting this points to ~https://github.com/bazelbuild/bazel/commit/282ac623df3523e2e31a2de9c002e5c50da19fec~ 610fe7bb25c8853fd9b55d85cb08d2bf4e3ee8b7

### Any other information, logs, or outputs that you want to share?

I ran into this error for https://github.com/bazelbuild/bazel-central-registry/pull/3288, see https://buildkite.com/bazel/bcr-presubmit/builds/9106.

**Comment by fmeum** [comment]
@advd Do you know what the path looked like before the breaking commit?

**Comment by avdv** [comment]
> Do you know what the path looked like before the breaking commit?

No, I don't know. But I suspect that this is related to the data that is appended to the launcher.exe on Windows. I don't have a Windows machine, which makes this always a bit tricky to debug.

**Comment by avdv** [comment]
@fmeum I just realized that the commit were this starts to fail is actually 610fe7bb25c8853fd9b55d85cb08d2bf4e3ee8b7 -- which also makes a lot more sense. (the bazel wrapper we are using always returned exit code 0 so bazelisk bisect reported success for that commit although it failed)

**Comment by fmeum** [comment]
Thanks for the update. I think I know what's up, but will need to confirm my theory. The commit you originally identified as the culprit actually has a bug, so thanks for making me aware of that. :-)

**Comment by fmeum** [comment]
While it is true that the culprit commit changed how the `sh_binary` launcher finds the script, it did so in a way that is transparent to consumers that correctly include the targets runfiles. If that's not done, an `sh_binary` target that uses runfiles also wouldn't have worked before that change. I am seeing failures on https://github.com/tweag/rules_sh/pull/95 locally on macOS that point to this being the issue (rather than a Bazel bug).

**Comment by fmeum** [comment]
This is ultimately caused by https://github.com/tweag/rules_sh/blob/dfd9051483ebcd0cd84902291b52270617ca8028/sh/private/defs.bzl#L35-L38: Genrule tools expect a runfiles structure in which each has a sibling `.runfiles` directory or `.runfiles_manifest` file, but Bazel will instead create a single one next to this fake executable.

Without a solution to https://github.com/bazelbuild/bazel/issues/15486, you probably have to create a wrapper script around each individual tool that sets the runfiles environment variables to the single shared runfiles location.

**Comment by avdv** [comment]
Thank you for digging into this @fmeum! 

> This is ultimately caused by https://github.com/tweag/rules_sh/blob/dfd9051483ebcd0cd84902291b52270617ca8028/sh/private/defs.bzl#L35-L38: Genrule tools expect a runfiles structure in which each has a sibling `.runfiles` directory or `.runfiles_manifest` file, but Bazel will instead create a single one next to this fake executable.

OK, I see. Closing.
