### ISSUE TITLE
Sandbox Debug does not drop me into a bash shell

### ISSUE THREAD

**Issue by natebosch** [bazelbuild/bazel#2505]
### Problem: running the sandbox command does not leave me in a bash shell

According to [this article](https://bazel.build/blog/2016/03/18/sandbox-easier-debug.html) I should be able to copy/paste the parenthesized command to rerun a failing executable and then end up in a shell inside the sandbox. When I try this it reruns the failing command and I end up back in my old shell.

### Minimal repro:

* Clone this repo and checkout the branch `no-sandbox-debug` : https://github.com/natebosch/bazel-repro
* Run `bazel build --verbose_failures --sandbox_debug :foo`
* Copy/paste the parenthesized command and run it

### Environment info

* Operating System: *Linux (goobuntu)*
* Bazel version (output of `bazel info release`): *release 0.4.4*

### Workarounds

I can replace everything after the `--` in the command with `bash` and at least drop into a shell in something under `execroot`, but I'm not sure if this really matches the sandbox. As far as I can tell my root hasn't changed, but [this article](https://bazel.build/blog/2015/09/11/sandboxing.html#how-does-it-work) indicates that `pivot_root` should have changed what root looks like. If I `ls /` then it's my actually filesystem root. Should it be?

**Comment by or-shachar** [comment]
If it helps, I noticed that in the article the command inside the parentheses starts with `cd`, but when running it with version 0.4.4 it doesn't have that part.
Parts of the command has relative path so you must `cd` before you run it.

This is how I found the correct `cd` - locate the directory with the `.sb` file. inside it - locate `exec-root/<workspace-name>`

BTW: it happens to me in mac os x.

**Comment by philwo** [comment]
@natebosch: The feature that the sandbox drops you into a shell on failure was removed, because with the new Linux sandbox (and the macOS sandbox) allowing read access to the entire filesystem, it was deemed no longer necessary. The blog article that you linked to is out of date and should probably be removed or updated.

@or-shachar: That said we should definitely make sure that you can copy & paste the command-line of failed actions and try them in a terminal. I'm sorry if that got accidentally broken in 0.4.4? I'll try to reproduce this in the next days and will get back to you.

**Comment by TheButlah** [comment]
This blog article still exists - I tried to do this today

**Comment by gonzojive** [comment]
Still relevant I think. Please do update the blog post.

I don't follow what "because with the new Linux sandbox (and the macOS sandbox) allowing read access to the entire filesystem, it was deemed no longer necessary" means.

I'm trying to write BUILD.bazel files for a C++ library, and I'm having trouble understanding why headers aren't being picked up. Viewing what files exist in the sandbox would help.

clone https://github.com/gonzojive/zstd and then run `bazel build --verbose_failures --sandbox_debug @com_github_facebook_zstd//:everything` to see what I'm dealing with if interested.
