### ISSUE TITLE
External repositories are refetched on server restart

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#251]
Even if they don't need to be.

**Comment by janakdr** [comment]
This means I need a network connection capable of downloading a 100+ MB file every time I want to compile Bazel with a fresh server. That's basically a dealbreaker for offline development, no?

**Comment by ekuefler** [comment]
You can pass `--fetch=false` to bazel to disable this, which will probably suffice for offline development if you've already downloaded the artifacts.

IMO this should be higher than a P3 though as it's a fairly significant productivity sink for my team, since we have to constantly wait to redownload a 60MB Boost library. Training developers when to use fetch=false is tough and I don't really want everyone to get into the habit of using it all the time since that'll presumably cause correctness issues down the road.

**Comment by bsilver8192** [comment]
I just pushed https://bazel-review.googlesource.com/1650 to fix this for {new_,}git_repository. It's easy for git repositories because there's already something which knows exactly which version is downloaded and if anything has been modified.

**Comment by kchodorow** [comment]
I think @janakdr is working on a fix for this.

**Comment by janakdr** [comment]
Working on one, but since it'll require some changes to
google-internal-side code and I'm OOO for the rest of the week, it may take
some time. My strategy is to give FilesystemValueChecker a way to
invalidate arbitrary SkyKeys based on some files changing, so bazel can
request that changes to the zip file invalidate the HttpDownloadFunction
(or whatever it's called). This corresponds to how we invalidate actions if
one of their outputs has changed.

**Comment by lberki** [comment]
What are the desired semantics for this, i.e. what should happen for each value of `--fetch` on:
 * Build commands (I guess we should to the same thing with or without server restart)?
 * Changes to the files in the output directory that are not done by Blaze?
 * Changes to the local source files of the repository command, if any?

Options:
 * Do not do anything
 * Ask the server, if any, if we have the latest version of whatever we download and update the local files if there is a change (only applies to non-hermetic repositories)
 * Forcibly set up the repository from zero 

I'm somewhat surprised that this depends on code in FilesystemValueChecker, since if a repository function depends on a file, that dependency should be recorded in Skyframe, shouldn't it? (I thought we can now maintain Skyframe values for files outside of the source tree, can't we?)

**Comment by janakdr** [comment]
Fetching a repository is very much like running an action. If an action's
output changes, we need to re-run that action, but that takes special
handling in FilesystemValueChecker. The same is true for repositories. The
action doesn't depend on its outputs because that doesn't make sense -- the
outputs depend on the action.

We want to re-fetch the repository if the hash of the zip has changed since
we downloaded it. I should have a change out soon that does that, and then
a follow-up change that actually fixes this bug (I just realized that the
first change isn't really necessary for this bug -- oh well).

**Comment by lberki** [comment]
Ooh, I was wondering what FilesystemValueChecker actually does. Now it make sense :)

**Comment by janakdr** [comment]
Machinery from 205a3d6 should be sufficient for remaining cases.

**Comment by hanwen** [comment]
is this still valid? new_http_archive seems to be working (ie. not refetching on server start.)

**Comment by janakdr** [comment]
Kristina, are all cases fixed? I left it open after my cl because I thought
there were different repository flavors that all needed this.

**Comment by lberki** [comment]
On a related note, when are external repositories re-fetched now? Only after "bazel clean"?

**Comment by hanwen** [comment]
bazel clean --expunge, i think.

**Comment by janakdr** [comment]
there is logic to notice a change and redownload. I think if the zip file
changes.

**Comment by kchodorow** [comment]
bazel clean --expunge will definitely make it get refetched.  It will also be refetched if the sha256 of the downloaded file does not match the one listed in the WORKSPACE file.  Note that the sha256 of the downloaded file isn't recomputed if the file changes (and the server isn't shut down), as we assume external/ is immutable (for now).

@janakdr you're right, maven_jar still needs this implemented.

**Comment by janakdr** [comment]
On Fri, Sep 25, 2015 at 10:09 AM, Kristina <notifications@github.com> wrote:
>
> bazel clean --expunge will definitely make it get refetched. It will also be refetched if the sha256 of the downloaded file does not match the one listed in the WORKSPACE file. Note that the sha256 of the downloaded file isn't recomputed if the file changes (and the server isn't shut down), as we assume external/ is immutable (for now).
Kristina, I think we use a different mechanism for this invalidation:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/BazelRepositoryModule.java#L162
. As far as I know this is independent of external files being
immutable.

**Comment by kchodorow** [comment]
Ah, yes, it is.

**Comment by kchodorow** [comment]
This also needs to be fixed for git_repository.

**Comment by davidzchen** [comment]
Understood. I'll take a look at fixing it for git_repository.

**Comment by lberki** [comment]
This was fixed in https://github.com/bazelbuild/bazel/commit/f1ffe3621002231fe4828fe4ecfd5f64df9d2052 in a bit more general way that works for all repository types except the local ones, but those can be re-generated on server startup very cheaply, so I suppose it's OK.
