### ISSUE TITLE
a way to make the skylark worker mode default

### ISSUE THREAD

**Issue by oscar-stripe** [bazelbuild/bazel#2518]
Using the worker API for skylark rules has been great for the scala rules: https://github.com/bazelbuild/rules_scala

One thing that would be great is for the rule to be able to declare that the default mode for a rule to be worker, and users can opt-out.

If we have 10 custom rules in a build, it is a shame that people have to also each configure the .bazelrc or command line parameters to get the worker modes. This has led many in our org not using the worker because they don't each spend the (small) effort to set it up. Checking the .bazelrc into the repo is also bad because many users want customizations of number of jobs since not all machines are equal.

**Comment by jmmv** [comment]
I think we should actually use workers by default whenever they are available.

The problem is that enabling workers automatically for all rules that support them is dangerous, because if we enable too many of them at once, we overload the machine. We need better controls in Bazel to limit what workers do concurrently, and once we have them, we could enable workers by default.

As per your request: sometime last year, `--worker_max_instances` gained the ability to specify a quantity relative to the local host's resources. So that, combined with a checked-in blazerc file, should let you enable workers by default while accounting for hardware differences. Thus I think we can say that this is resolved.
