### ISSUE TITLE
Bazel design documents links are broken

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#2561]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

When going to "Design documents" the links to "Environment" and "Sandboxing" are broken.
https://www.bazel.build/versions/master/docs/designs/

**Comment by steren** [comment]
Thanks for the report.
We have much more design docs in https://github.com/bazelbuild/bazel/tree/master/site/designs/_posts 

And they are correctly listed in https://www.bazel.build/designs/

The problem here seems to be that the page https://www.bazel.build/versions/master/docs/designs/ should just not exist.

**Comment by ittaiz** [comment]
I got to it from the site search

**Comment by steren** [comment]
I suppose it is a consequence of #2556, and potentially #2555
I will clean up the page you found and add a redirect

**Comment by ittaiz** [comment]
Thanks!

**Comment by steren** [comment]
I deleted https://www.bazel.build/versions/master/docs/designs/
It should be removed from the site search index. No need to put a redirect I believe.
