### ISSUE TITLE
TensorFlow r0.12 crashes on Bazel 0.4.4

### ISSUE THREAD

**Issue by bogatyy** [bazelbuild/bazel#2569]
Steps to reproduce:
```sh
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow/
git checkout r0.12
./configure
```

Error message:

> ERROR: /usr/local/google/home/bogatyy/.cache/bazel/_bazel_bogatyy/f77c1ae611df428e4152c9dc78b83cb1/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:1: no such target '//external:android/dx_jar_import': target 'android/dx_jar_import' not declared in package 'external' defined by /usr/local/google/home/bogatyy/tensorflow/WORKSPACE and referenced by '@bazel_tools//src/tools/android/java/com/google/devtools/build/android/dexer:dexer'.

Is TF 0.12 no longer supported? Any suggestions to make it work?

**Comment by iirina** [comment]
TF currently can not be built with Bazel 0.4.4. This should be fixed in the next release. Can you please try with a previous release?

**Comment by aj-michael** [comment]
The error you are getting is https://github.com/tensorflow/tensorflow/pull/6225 which was fixed in TensorFlow after r0.12.

So the answer is either:
* Use more recent TensorFlow: `git checkout r1.0`
* Apply the one-line change in https://github.com/tensorflow/tensorflow/pull/6225 to your tensorflow repository.
