### ISSUE TITLE
Bazel requires protobuf-java-3.x.y.jar to bootstrap

### ISSUE THREAD

**Issue by cgrushko** [bazelbuild/bazel#2578]
This prevents us from including the https://github.com/google/protobuf/ repository as is in `//third_party/protobuf/`.

The aforementioned jar is included in the bootstrapping in [1].

Later today we'll be able to build the Java proto runtime from head:

    bazel build //third_party/protobuf:protobuf_java

so we can in principle get rid of the checked-in precompiled `protobuf-java-3.x.y.jar`

[1] - https://github.com/bazelbuild/bazel/blob/master/scripts/bootstrap/compile.sh#L20, hash = 2e689c2

**Comment by cgrushko** [comment]
@damienmg that's the issue I referred to in the mail thread.

**Comment by damienmg** [comment]
Oh we should be able to work around that by building the jar with javac from compile.sh.

**Comment by cgrushko** [comment]
I tried for an hour and gave up :) realized Klaus probably knows much better how all of this works.

**Comment by aehlig** [comment]
> Oh we should be able to work around that by building the jar with javac from compile.sh.

I don't think, compile.sh is the correct place to build it. A jar is,
fortunately, machine independent; so if we build it with `bazel build
//third_party/protobuf:protobuf_java`, the best way (definitely the
most easy way) to do it, is to just add it to the distribution artefact.
I'll have a closer look and try to make this work.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by aehlig** [comment]
> I don't think, compile.sh is the correct place to build it. A jar is,
> fortunately, machine independent; so if we build it with `bazel build
> //third_party/protobuf:protobuf_java`, the best way (definitely the
> most easy way) to do it, is to just add it to the distribution artefact.
> I'll have a closer look and try to make this work.

For the time being, this is blocked on having the full protobuf sources
under third_party. Then it will be an involved 3-step dance, as what we
actually want is to atomically
- remove the jar,
- change third_party/protobuf/3.x.y/BUILD to build the jar instead of importing it,
- change the generation of the distribution artefact to include the generatred jar, and
- change compile.sh to also search in the derived directory for jars needed for bootstrapping.

Unfortunately, we can only atomically commit changes either completely inside
or completely outside third_party.

Anyway, I will wait till we have complete sources in third_party/protobuf and
then attempt to change the bootstrapping.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Matthew Scott Sucherman, Paul Terence Manicle

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
