### ISSUE TITLE
Printer should handle recursion-loops to prevent StackOverflowError

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2581]
### Description of the problem / feature request / question:

When having a recursive list with loops, `com.google.devtools.build.lib.syntax.Printer` should gracefully fail and not result in a `java.lang.StackOverflowError`.
With complex nesting, these errors may be very hard to figure out.

### If possible, provide a minimal example to reproduce the problem:

    l = []
    l.append(l)
    "\n".join(l)
    # Booom

### Environment info
* Operating System: Linux
* Bazel version (output of `bazel info release`): 0.4.3

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)
Nope

### Anything else, information or logs or outputs that would be helpful?
Ideas would be either to track the already printed object(/hash) or to handle the `StackOverflowError`.

**Comment by laurentlb** [comment]
Did you find this in a real situation, or was it just to test the limits of the system? :)

**Comment by abergmeier-dsfishlabs** [comment]
> Did you find this in a real situation, or was it just to test the limits of the system? :)

I really had a similar mistake in my `.bzl`. Maybe there are others as dumb as me out there ;)

**Comment by cgruber** [comment]
Isn't a stack-overflow the quintessential evidence of a cycle in your data? I think for things like Join you might have very different behavior than a walk of an str() call, and adding the state management needed to detect cycles might not be worth the payoff here.  Doing this right probably would mean going and finding all recursive algorithms and deciding how to handle a cycle, add a reference stack to check against, etc.

That said, the error cited above seems like it is its own kind of error - you're appending `l` to itself... but accidentally adding a sequence as an element of itself. Maybe the issue is that is too easy to do by accident?

**Comment by brandjon** [comment]
Indeed. See #4295 for any remaining infinite recursion issues with Starlark data types.
