### ISSUE TITLE
Bazel android example still need add --spawn_strategy=standalone when build on mac

### ISSUE THREAD

**Issue by coroner4817** [bazelbuild/bazel#2597]
### Environment info
* Operating System:
Mac OS X 10.12.2 (16C67)
* Bazel version (output of `bazel info release`):
0.4.4-homebrew

I basically try to build the [example android project](https://github.com/bazelbuild/bazel/tree/master/examples/android). However, if I follow the README, bazel will give me this error:

```
➜  bazel_android_test bazel build //android/java/bazel:hello_world
WARNING: Bazel Android NDK crosstools are based on Android NDK revision 12. The revision of the Android NDK given in android_ndk_repository rule 'androidndk' is '14.0.3675639-beta2'.
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_YingnanWang/e66eaf7095002f1ad1ac35cfaac2ae23/external/androidsdk/com.android.support/BUILD:3785:1: Processing Android resources for @androidsdk//com.android.support:support-compat-25.2.0 failed: Process exited with status 2 [sandboxed].
Error parsing command line: While parsing option --primaryData: invalid UnvalidatedAndroidData: bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/external/androidsdk/com.android.support/_aar/unzipped/resources/support-compat-25.2.0 does not exist
Try --help.
Use --strategy=AndroidAapt=standalone to disable sandboxing for the failing actions.
Target //android/java/bazel:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 20.734s, Critical Path: 10.19s
```

My WORKSPACE is:
```
android_sdk_repository(
    name = "androidsdk",
    path = "/Users/YingnanWang/Library/Android/sdk",
    api_level = 25,
    build_tools_version="25.0.2"
)

android_ndk_repository(
    name = "androidndk",
    # Replace with path to Android NDK on your system
    path = "/Users/YingnanWang/Library/Android/sdk/ndk-bundle",
    # Replace with the Android NDK API level
    api_level = 24
)
```

My BUILD file is:
```
filegroup(
    name = "srcs",
    srcs = glob(["**"]),
    visibility = ["//android:__pkg__"],
)

android_library(
    name = "lib",
    srcs = ["Lib.java"],
)

android_binary(
    name = "hello_world",
    srcs = glob([
        "MainActivity.java",
        "Jni.java",
    ]),
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
    deps = [
        ":jni",
        ":lib",
        "@androidsdk//com.android.support:appcompat-v7-25.2.0",
    ],
)

cc_library(
    name = "jni",
    srcs = ["jni.cc"],
    deps = [":jni_dep"],
)

cc_library(
    name = "jni_dep",
    srcs = ["jni_dep.cc"],
    hdrs = ["jni_dep.h"],
)
```

If I add the `--spawn_strategy=standalone`, build pass.

**Comment by aj-michael** [comment]
Hmmm, you should not need it as of bazel 0.4.4. What is the output of `bazel version`?

**Comment by coroner4817** [comment]
```
Build label: 0.4.4-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Feb 2 01:05:15 2017 (1485997515)
Build timestamp: 1485997515
Build timestamp as int: 1485997515
```

Is that because I use higher version NDK (r14-beta2)?

**Comment by hochhaus** [comment]
I am seeing a similar issue on bazel 0.4.4 only using the SDK (no NDK). Please let me know if you need more details and I'll post a full reproducer.

**Comment by aj-michael** [comment]
Hmmm, I'll try to take a look tomorrow. For the sake of linking things together, the tracking issue for this bug was https://github.com/bazelbuild/bazel/issues/1928.

I noticed that you changed the target in the example from 25.0.0 to 25.2.0. Perhaps that is related? I will admit I have not tried any builds with the 25.2.0 app compat library, however I can't imagine any difference in its contents causing this error.

Do both of the following builds fail?

```
$ bazel build @androidsdk//com.android.support:appcompat-v7-25.0.0
$ bazel build @androidsdk//com.android.support:appcompat-v7-25.2.0
```

@hochhaus, are you also using mac?

**Comment by hochhaus** [comment]
@aj-michael Yes, I'm compiling the same target both on linux and mac. Linux works as expected. The error only occurs on the mac for me.

**Comment by coroner4817** [comment]
@aj-michael Both of build failed for the same not exist error.

**Comment by aj-michael** [comment]
Hmm, both https://github.com/bazelbuild/bazel/blob/0f119a4db515105217244e4db5d4fed9371ef1a4/src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedStrategy.java and https://github.com/bazelbuild/bazel/blob/0f119a4db515105217244e4db5d4fed9371ef1a4/src/main/java/com/google/devtools/build/lib/sandbox/LinuxSandboxedStrategy.java invoke https://github.com/bazelbuild/bazel/blob/0f119a4db515105217244e4db5d4fed9371ef1a4/src/main/java/com/google/devtools/build/lib/sandbox/SpawnHelpers.java#L166 which is what mounts empty directories for empty TreeArtifacts.

@philwo do you have any idea of what might cause this discrepancy in the sandbox strategies?

**Comment by aj-michael** [comment]
Ah, I think I see the problem. That DarwinSandboxedStrategy uses a HardlinkedExecRoot, while the LinuxSandboxedStrategy uses a SymlinkedExecRoot. Since you can't make hard links to directories... we may be out of luck here.

**Comment by hochhaus** [comment]
Icky. This is a show stopper for `android_binary()` to work well cross platform.

Is it possible to force bazel on darwin to use the `SymlinkedExecRoot` for `android_binary()` rules?

**Comment by aj-michael** [comment]
So I spoke a bit too soon. HardlinkedExecRoot does handle directory inputs, however the way it handles them is by hard linking each of the directory entries:

https://github.com/bazelbuild/bazel/blob/0f119a4db515105217244e4db5d4fed9371ef1a4/src/main/java/com/google/devtools/build/lib/sandbox/HardlinkedExecRoot.java#L151

Then, in the process of creating the hardlinks for the children, it creates the parent directory. However, in the case of an empty tree artifact (_aar/unzipped/resources/support-compat-25.2.0), this means that the directory never gets created.

So it seems a simple fix is to call `FileSystemUtils.createDirectoryAndParents(source);` at https://github.com/bazelbuild/bazel/blob/0f119a4db515105217244e4db5d4fed9371ef1a4/src/main/java/com/google/devtools/build/lib/sandbox/HardlinkedExecRoot.java#L151.

@philwo is there any reason that we would not want to do this? Otherwise I will send you a patch to review.

**Comment by aj-michael** [comment]
Hmmm, one last thing I'm still confused by. We have a test for this:

https://github.com/bazelbuild/bazel/blob/0f119a4db515105217244e4db5d4fed9371ef1a4/src/test/shell/bazel/android/android_integration_test.sh#L198

@damienmg Does Bazel CI run on mac with sandboxing disabled?
