### ISSUE TITLE
PHP Build Rules

### ISSUE THREAD

**Issue by lswith** [bazelbuild/bazel#2652]
### feature request:
are there any rules for PHP7/HHVM?

**Comment by damienmg** [comment]
What is HHVM?

What is special with php7 vs earlier version of php? I think there is some contribution from the community for PHP but I don't remember where.

**Comment by skyred** [comment]
PHP 7+ are the only supported versions. http://php.net/supported-versions.php

**Comment by lswith** [comment]
HHVM is the [HipHop VM](http://hhvm.com/). 

Having rules for PHP7 would be super helpful.

**Comment by lswith** [comment]
Rules for [Hacklang](https://docs.hhvm.com/hack/) is what I meant by referring to HHVM. I think building in the [Hackificator](https://docs.hhvm.com/hack/tools/hackificator) and the [hack transpiler](https://docs.hhvm.com/hack/tools/transpiler) would be useful in these circumstances.

**Comment by kburnik** [comment]
FYI,
I started fiddling around with Bazel and PHP. At this point it's far from perfect, mostly experimenting, although it seems to produce results which I need so far. I use PHP 5.6, but I imagine using PHP 7 would be easy to apply as well.

Some of the features:

* php_library
* php_binary
* php_test
* php_image
* composer_repository (workspace rule)

https://github.com/kburnik/php_codebase

**Comment by mhlopko** [comment]
We don't plan to write these rules ourselves, therefore closing this issue.

**Comment by hashar** [comment]
Since I am leaning toward building a proof of concept for PHP I found this task and a few repositories on GitHub. Here is a summary in case someone reaches this issue:

https://github.com/adam-rocska/rules_php (no license)
[Builds PHP from source](https://github.com/adam-rocska/rules_php/blob/master/php/repositories.bzl)

https://github.com/greggdonovan/rules_php (no license)
Can run phar packages and offers phan (static analyzer from Esty). Main implementation file is [//php:php.bzl](https://github.com/greggdonovan/rules_php/blob/master/php/php.bzl)

https://github.com/kburnik/php_codebase (MIT LIcense)
Looks the most advanced, but at a quick glance it imposes a specific layout to the source repository and is tied to Laravel. It has:
* A long README!
* Generates PHP autoloader files that only have the dependencies of the target
* [implementation for composer commands](https://github.com/kburnik/php_codebase/blob/master/tools/build/composer.bzl)
* [php rules](https://github.com/kburnik/php_codebase/blob/master/tools/build/php.bzl) such as `php_test` with PHPUnit, `php_image` with a Docker image.
* And more

**Comment by hashar** [comment]
> @hashar Any luck w/PHP?

Not really, the learning curve is steep and I am only doing it on my limited spare time! I guess I should polish up the poor code I have, publish it somewhere :)
