### ISSUE TITLE
Windows: Error: Cannot terminate server process with PID 4284: (error: 5): Access is denied.

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2684]
Output is like
```
pcloudy@pcloudy0-w MSYS ~/meteorcloudy/tensorflow
$ bazel
Error: Cannot terminate server process with PID 14660: (error: 5): Access is de@
...
```

If revert c8cd6bd2728e93c052ea217b5a93707a8a876f40, the problem is gone. So it should be the culprit

**Comment by laszlocsomor** [comment]
I'll take a look

**Comment by laszlocsomor** [comment]
I think the behavior is WAI -- every time we run on the CI, it's a new binary and new bazel client, so it shouldn't assume it can connect to the server from the previous binary.

I can repro this locally by building an msys-less binary, running it in server mode, then changing the source and rebuilding (thus simulating new changes on the CI), rebuilding, and running again in the same output root as before. But then subsequent runs with the second binary correctly connect to the running server, without showing any error.

So i think the only thing wrong here is that bazel says it cannot kill the process, but in fact it can. Yet it's weird that TerminateProcess fails. I'll look into why that happens.

**Comment by laszlocsomor** [comment]
Ah, there it is: we try to kill the process twice. The first attempt succeeds, the second fails and prints the error. Let me find out why we do this and fix it.

**Comment by laszlocsomor** [comment]
The culprit is the VerifyServerProcess method -- on Windows it always returns false, meaning that the PID we read from the pid file doesn't correspond to a bazel server, assuming the PID was handed out to another process (because the machine was restarted since, or something). This is of course too conservative, and I have a pending change that'll verify the server process the same way we do it on Linux, but this change is not ready yet.

For the time being, the error reporting in KillServerProcess can be safely turned off.
