### ISSUE TITLE
0.4.5 - Possible breaking-change to cycle analysis in toolchains

### ISSUE THREAD

**Issue by david-german-tri** [bazelbuild/bazel#2691]
### Description of the problem / feature request / question:

I've upgraded to Bazel 0.4.5, and when I build [RobotLocomotion/drake](https://github.com/RobotLocomotion/drake) with `bazel build ...`, I get an error from Bazel that doesn't occur on 0.4.3 or 0.4.4.

It's entirely possible that our BUILD files are defective and Bazel is right to report an error.  We're actively investigating.  However, this does at least suggest an incompatible change not listed in https://github.com/bazelbuild/bazel/blob/master/CHANGELOG.md#release-045-2017-03-16, which is why I'm reporting it before we have a full analysis.

```
~/drake/drake-distro$ bazel build ...
WARNING: /home/dgerman/drake/drake-distro/drake/util/BUILD:43:1: target '//drake/util:app_util' is deprecated: Please use gflags instead of drakeAppUtil.h.
ERROR: /home/dgerman/drake/drake-distro/tools/BUILD:128:1: in filegroup rule //tools:linux_toolchain_deps: cycle in dependency graph:
    (//tools:apple_toolchain_deps(
    //tools:universal_toolchain_deps
    //tools:ccache.txt
    //tools:ccache_is_bad
    //tools:cc_toolchain_linux
.-> //tools:linux_toolchain_deps (host)
|   //tools:universal_toolchain_deps (host)
|   //tools:ccache.txt (host)
|   //tools:ccache_is_bad (host)
|   //tools:cc_toolchain_linux (host)
`-- //tools:linux_toolchain_deps (host)
This cycle occurred because of a configuration option.
ERROR: Analysis of target '//tools:apple_toolchain_deps' failed; build aborted.
INFO: Elapsed time: 7.653s
```

I've tried `bazel query "deps(//tools:apple_toolchain_deps)"` before-and-after.  There are differences - I find it interesting that the 0.4.5 query traversed the toolchain rules, whereas the 0.4.4 one didn't - but I'm not confident it's a smoking gun.  In particular, there apparently isn't a `--crosstool_top` flag for `bazel query`, so I can't force it to walk the alleged cycle in our custom toolchain rules.

* 0.4.4 [here](https://gist.github.com/david-german-tri/9a988d9b0b3916a5bf40b8f1a6bbad6e)
* 0.4.5 [here](https://gist.github.com/david-german-tri/070828f2fd3ee21578caffdcc4aaa734)

### If possible, provide a minimal example to reproduce the problem:

The BUILD file that defines our toolchain is [here](https://github.com/RobotLocomotion/drake/blob/master/tools/BUILD).

_EDIT: We've created a minimal example at https://github.com/david-german-tri/bazelbuild2691._

### Environment info

* Operating System: We've thus far reproduced this on both Ubuntu 14.04 and OS X El Capitan.

* Bazel version (output of `bazel info release`):  `release 0.4.5`

###  Have you found anything relevant by searching the web? (e.g. GitHub issues, email threads in the [bazel-discuss@googlegroups.com](https://groups.google.com/forum/#!forum/bazel-discuss) archive)

Nope.

**Comment by hermione521** [comment]
Hi, I tried to build your project with bazel 0.4.4 but I get the following error. Is there anything that I should configure? Thanks.

```
WARNING: /usr/local/google/home/yueg/Documents/upper_workspace/test_workspace/drake/drake/util/BUILD:63:1: target '//drake/util:app_util' is deprecated: Please use gflags instead of drakeAppUtil.h.
WARNING: /usr/local/google/home/yueg/.cache/bazel/_bazel_yueg/dc5864d025bea50eb434fbfa75c25e07/external/drake_visualizer/BUILD:2:48: soft_failure.bzl: @drake_visualizer//:drake-visualizer does not work because /usr/local/google/home/yueg/Documents/upper_workspace/test_workspace/drake/build/install/bin/drake-visualizer was missing.
ERROR: /usr/local/google/home/yueg/.cache/bazel/_bazel_yueg/dc5864d025bea50eb434fbfa75c25e07/external/lcm/BUILD.bazel:27:1: no such package '@glib//': 
Error processing glib-2.0: Unable to find module

Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
 and referenced by '@lcm//:lcm'.
```

**Comment by soonho-tri** [comment]
@hermione521 , http://drake.mit.edu/ubuntu_trusty.html#other-prerequisites lists the required dependencies. Could you install them and build it again?

**Comment by david-german-tri** [comment]
@soonho-tri's reference is good, but I hate to put the Bazel team to that much trouble.  I'll try to produce a smaller repro example.

**Comment by david-german-tri** [comment]
@hermione521 Here's a much smaller repro project that builds with Bazel 0.4.4, and errors in the same manner as the OP on Bazel 0.4.5:

https://github.com/david-german-tri/bazelbuild2691

Thanks very much for your willingness to take a look!

**Comment by hermione521** [comment]
Thank you for the repro! Let's see if @gregestren can help with this.

**Comment by gregestren** [comment]
Thanks for the detailed analysis and simplified repro, David. That's indeed suspicious if you see clearly different behavior in 0.4.4. vs. 0.4.5. I'm looking in further now...

**Comment by gregestren** [comment]
David,

This is indeed an incompatible change between 0.4.4 and 0.4.5 that did not make the release notes. Specifically: https://github.com/bazelbuild/bazel/commit/1f42581891cc5f463edc94f8e96502f1b3aff033#diff-dc563e4148084671f7d953e1fee35737R55 ("_Update GenRule to include the Cpp and Jdk toolchains and properly handle_").

What this change did was make it possible for genrules to write code like:

`genrule(
    name = "foo",
    cmd = "echo $(CC) > $@",
    ....)`

and have `$(CC)` automatically expand to the C++ compiler specified by the crosstool.

In order for this to work, this adds a new implicit attribute `:cc_toolchain` on all genrules that resolves to your build's crosstool, which in your case is `//tools:cc_toolchain_linux`. But since `//tools:cc_toolchain_linux` also depends on the genrule that makes `ccache.txt`, you get the cycle you see.

The ideal solution is for Bazel to only apply that dependency when there are actually `$(CC)` (etc.) references in the genrule. In your case there aren't, so the cycle is unnecessary. We actually have code that [half](https://github.com/bazelbuild/bazel/blob/e36a66cd6e35e5b4b276f2b6ce63e1c691bcb02c/src/main/java/com/google/devtools/build/lib/rules/genrule/GenRuleBase.java#L63) [does](https://github.com/bazelbuild/bazel/blob/73726a8a46cd5260fd0cc1cbf32c93922ca6ffb8/src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/BazelCppRuleClasses.java#L127) this, but it doesn't go as far as actually breaking that link. I'll try putting up a change that actually does that.

In the meantime, you somehow have to break the dependency from your toolchain onto that genrule. I'm unfortunately not sure there's a natural way to do that. You may be able to hack something out by manipulating `--crosstool_top` and `--host_crosstool_top` (if they're different you can presumably get the genrule to depend on a simpler cc_toolchain that doesn't reference `ccache.txt`).

You're right about query not catching this. For subtle reasons, query is not yet powerful enough to apply command-line flags, so it has to "guess" from the defaults. We do intend to change this eventually, but that will take time.

**Comment by david-german-tri** [comment]
@gregestren Awesome, thanks for the explanation!  I've worked-around by converting the genrule that makes `ccache.txt` into a Skylark rule, which seems to avoid the implicit `:cc_toolchain` dependency.

https://github.com/RobotLocomotion/drake/pull/5595

**Comment by gregestren** [comment]
I've fixed the underlying issue: https://github.com/bazelbuild/bazel/commit/bf0b990f5c00b9fb3d60f1c54956f4a22cabc687
