### ISSUE TITLE
Output of MSVC Bazel is not colorful under MSYS

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#2724]
And it doesn't refresh, just output everything to the terminal.
```
pcloudy@pcloudy0-w MSYS ~/workspace/bazel
$ bazel build examples/cpp:hello-world
...............
____Loading package: examples/cpp
____Loading package: @bazel_tools//tools/cpp
____Loading package: @local_config_xcode//
____Loading package: @local_jdk//
____Loading complete.  Analyzing...
____Found 1 target...
____Building...
____[0 / 9] BazelWorkspaceStatusAction stable-status.txt
Target //examples/cpp:hello-world up-to-date:
  C:/tmp/_bazel_pcloudy/7uxoax_v/execroot/bazel/bazel-out/msvc_x64-fastbuild/bin/examples/cpp/hello-world.exe
____Elapsed time: 6.551s, Critical Path: 1.26s

```
//cc @laszlocsomor 

But works like a charm under cmd.exe, thanks for all your awesome work!

**Comment by laszlocsomor** [comment]
> And it doesn't refresh, just output everything to the terminal.

I suppose you mean it doesn't update the build status, right?

Yes, this runs now as if you passed `--color=no --curses=no` (the latter is the one enabling/disabling this "update" feature), because bazel believes that msys is not a "standard" terminal, i.e. it may be a file that we redirected the output to, so we don't print control characters.  I can take a look at this.

**Comment by meteorcloudy** [comment]
Yes, thanks, but it's not very urgent problem.

**Comment by laszlocsomor** [comment]
Found the culprit why `_isatty` was returning false under MSYS/Cygwin even if stdout/err weren't redirected.

When you run a MSVC-built binary under both MSYS and Cygwin, all 3 standard streams are connected to pipes by default (according to `_fstat32`). This makes sense -- bash is a Windows process, bazel is its subprocess most likely created with `CreateProcess` and a redirected std{in,out,err}, exactly the same way Bazel itself spawns subprocesses.

**Comment by laszlocsomor** [comment]
And the workaround is very simple: just pass `--curses=yes --color=yes` to bazel and voila, colored output under MSYS. Even on Linux if you pipe std{out,err} into something, Bazel will not use color/curses by default, because isatty returns false, which is cprecisely what happens on MSYS even without redirection.

In light of my previous comment, everything is working as intended.

**Comment by meteorcloudy** [comment]
Got it! Thanks for looking into this!
