### ISSUE TITLE
Expand a label to pathnames in a macro?

### ISSUE THREAD

**Issue by wiktortomczak** [bazelbuild/bazel#2803]
Hello,

Is it possible to expand a label eg. `//mypkg:target` into a list of pathnames inside a macro implementation?

I'm writing an extension (a macro or a rule) that rewrites an arbitrary set of files. Output pathnames should be automatically derived from input pathnames. I think I need to write a macro because it allows to compute the list of outputs dynamically, unlike a rule. However, I don't know how to access the list of input pathnames if the input is a label, not a list of explicit pathnames.

What I'd like to say in a BUILD file is

```
# Rewrites:
# file1.cc to bazel-genfiles/file1.cc.rewritten
# file2.cc to bazel-genfiles/file2.cc.rewritten
my_extension(
  name = "files_rewritten",
  srcs = [
    "file1.cc",
    "file2.cc"
  ]
)
```

I need advice how to handle the case below:

```
filegroup(
  name = "files",
  srcs = [
    "file1.cc",
    "file2.cc"
  ]
)

my_extension(
  name = "files_rewritten",
  srcs = [
    ":files"
  ]
)
```

Thanks

**Comment by katre** [comment]
One piece of advice: are the files being rewritten all related, or separate?

If they are separate, having this:
my_rewriter(
  srcs = ["file1.cc"])
my_rewriter(
  srcs = ["filec.cc"])

is more efficient than this:
my_rewriter(
  srcs = ["file1.cc", "file2.cc"])

because if only file1.cc is changed, Bazel will only re-write one file, not the entire set at once.

As far as the implementation, if you are handling a single file per rule as I suggest, a rule is better than a macro. Rules are fully part of Bazel, and any errors will be reported correctly. Macros, on the other hand, are pre-processed to generate rules, and so if there are error messages they will refer to rule names that don't necessarily exist in your BUILD file.

As far as handling filegroups specifically, if your rule supports filegroups you would need to check each item in ctx.attr.srcs to see if it is a file or a filegroup, and if so to expand the filegroup. I don't believe Bazel will auto-expand that for you.

**Comment by wiktortomczak** [comment]
The set of files that needs to be rewritten is a large library (hundreds of files), let's say `//mypkg:target`. This target is where the exact set of files is defined. Listing each file explicitly again at `my_rewriter` call site in `srcs` is not feasible and prone to error, should the set of files in `//mypkg:target` change.

Given that the set of input files to `my_rewriter` can be arbitrary and of variable size, I don't see how to implement it as a rule. The problem specifically is that a rule has either a fixed set of outputs or requires the outputs to be listed explicitly in the BUILD file. The outputs can't be listed explicitly for the same reason the inputs can't.

This is why I think that a macro is the only option, pending my original question.

**Comment by ittaiz** [comment]
This might not be of great help and you might already know this but AFAIU
the many dynamic outputs use-case is solved via having your rule output an
archive (like a jar/tar/zip for example).

P.S. I think this might be more suited for StackOverflow than a github
issue but I might be wrong

**Comment by buchgr** [comment]
Hey @wiktortomczak! As @ittaiz suggested, it would be great if you could ask this question on stackoverflow using the bazel tag, so that other users can also benefit from an answer :). We use GitHub mainly for bug reports.

**Comment by buchgr** [comment]
Thanks!
