### ISSUE TITLE
How to get remote aar file like what maven_jar does?

### ISSUE THREAD

**Issue by ldjhust** [bazelbuild/bazel#2816]
How to get remote `aar` file like what `maven_jar` does?

Thank you very much!

**Comment by aj-michael** [comment]
Hi @ldjhust , Bazel ships with a Skylark `maven_aar` rule. You can see a previous issue requesting it here: https://github.com/bazelbuild/bazel/issues/561. You can see its source here: https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/maven_rules.bzl.

You can use it like this:

In your `WORKSPACE` file

    load("@bazel_tools//tools/build_defs/repo:maven_rules.bzl", "maven_aar")
    maven_aar(
        name = "facebook_android_sdk",
        artifact = "com.facebook.android:facebook-android-sdk:3.19.0",
    )

In your `BUILD` file

    android_binary(
        name = "my_app",
        ...
        deps = [
            "@facebook_android_sdk//aar",
            ...
        ],
    )

If you have any more questions about how to use this rule, please post them on https://stackoverflow.com/questions/tagged/bazel so that other people come across them in the future :smile:

**Comment by ldjhust** [comment]
OK, thank you very much @aj-michael !

**Comment by ldjhust** [comment]
@aj-michael How to specify a maven repository for the maven_aar rule? It seems like that the maven_aar doesn't recognize my maven_server:

maven_server(
    name = "default",
    url = "http://xxx"
)

Thank you very much!

**Comment by aj-michael** [comment]
Yea, the maven_server rule is just for the native maven_jar rule. We made the skylark maven_jar and mane_aar rules differently. Instead it uses the standard maven settings XML convention.

https://maven.apache.org/settings.html

You can either put your repository in the global maven settings file on your machine, or you can create a custom settings.xml and put the path to it in the 'settings' attribute of maven_aar.

**Comment by ldjhust** [comment]
OK, I get it. Thanks very much @aj-michael , you help me a lot!
