### ISSUE TITLE
{stable, volatile}-status.txt not found on macOS.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#2819]
Recently we had several CI failures regarding `bazel-out/stable-status.txt` and `volatile-status.txt` not being found. The failures only happend on macOS.

Here are the logs:
 
http://ci.bazel.io/job/Tutorial/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/874/console
http://ci.bazel.io/job/gerrit/308/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/console

cc: @lberki (as discussed offline).

**Comment by damienmg** [comment]
Is it dues to sandboxing?

**Comment by lberki** [comment]
That's my guess. I'll be OOO next week, so I can't investigate.

**Comment by philwo** [comment]
The WorkspaceStatusAction is not a SpawnAction, thus it does not use sandboxing, process-wrapper or anything else. Instead it constructs its own Command object and simply calls .execute() on it.

**Comment by damienmg** [comment]
Well but the problem happens during normal action, not during the workspace status action. The file is not found. It could be related to the slave also (since this slave ends up in a terrible state the week after).

**Comment by damienmg** [comment]
FTR another instance: http://ci.bazel.io/job/gerrit/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/335/console

**Comment by damienmg** [comment]
http://ci.bazel.io/job/gerrit/BAZEL_VERSION=HEAD,PLATFORM_NAME=darwin-x86_64/339/console <-- another instance, might be related to the slave itself.

**Comment by damienmg** [comment]
@philwo @lberki: can we get update on that bug?

**Comment by philwo** [comment]
Do we have a way how to reproduce this issue?

**Comment by damienmg** [comment]
It fails systematically on both darwin slaves so I would say use bazel head. `git clone --recursive https://gerrit.googlesource.com/gerrit` and `bazel build //:release` several time

**Comment by philwo** [comment]
Alright, thanks! I'll try to reproduce it on my MacBook Pro now.

**Comment by damienmg** [comment]
Thanks!

**Comment by philwo** [comment]
Considering that this always refers to stable-status.txt, I've modified Gerrit's `tools/workspace-status.sh` to output a key-value pair with a random generated value, which means the `bazel-out/stable-status.txt` file changes on every build.

Then I've built Gerrit in an infinite loop ("but" is "bazel under test", a fresh Bazel HEAD binary):
`while but build --verbose_failures //:release; do true; done`

This works. No failures in ~100 runs now.

I suspected that maybe other actions run before the BazelWorkspaceStatusAction is done with generating the stable-status.txt, so I added a "sleep 1200" in the tools/workspace-status.sh file, ran clean and build again, but Bazel correctly waits for it to finish before doing anything else.

**Comment by philwo** [comment]
(And o-m-g how I hate it that we don't print a stack trace here...)

**Comment by philwo** [comment]
I still cannot reproduce this, but I manually built the situation that I think is happening: When one of the failing genrules runs, the stable-status.txt or volatile-status.txt does not exist when the sandbox tries to build its filesystem. The reason why it doesn't exist is unknown, but this allowed me to get the stack trace of the error:

```
java.io.FileNotFoundException: /private/var/tmp/_bazel_philwo/0fb0de3fd0e04c7d7bd7d075613d44d9/execroot/gerrit/bazel-out/volatile-status.txt (No such file or directory)
	at com.google.devtools.build.lib.unix.NativePosixFiles.lstat(Native Method)
	at com.google.devtools.build.lib.unix.UnixFileSystem.statInternal(UnixFileSystem.java:173)
	at com.google.devtools.build.lib.unix.UnixFileSystem.stat(UnixFileSystem.java:163)
	at com.google.devtools.build.lib.unix.UnixFileSystem.resolveOneLink(UnixFileSystem.java:118)
	at com.google.devtools.build.lib.vfs.FileSystem.appendSegment(FileSystem.java:413)
	at com.google.devtools.build.lib.vfs.FileSystem.resolveSymbolicLinks(FileSystem.java:479)
	at com.google.devtools.build.lib.vfs.Path.resolveSymbolicLinks(Path.java:905)
	at com.google.devtools.build.lib.sandbox.HardlinkedExecRoot.linkInputs(HardlinkedExecRoot.java:112)
	at com.google.devtools.build.lib.sandbox.HardlinkedExecRoot.createFileSystem(HardlinkedExecRoot.java:65)
	at com.google.devtools.build.lib.sandbox.DarwinSandboxedStrategy.actuallyExec(DarwinSandboxedStrategy.java:183)
	at com.google.devtools.build.lib.sandbox.SandboxStrategy.exec(SandboxStrategy.java:101)
	at com.google.devtools.build.lib.sandbox.DarwinSandboxedStrategy.exec(DarwinSandboxedStrategy.java:58)
	at com.google.devtools.build.lib.sandbox.SandboxStrategy.exec(SandboxStrategy.java:80)
	at com.google.devtools.build.lib.sandbox.DarwinSandboxedStrategy.exec(DarwinSandboxedStrategy.java:58)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.internalExecute(SpawnAction.java:266)
	at com.google.devtools.build.lib.rules.genrule.GenRuleAction.internalExecute(GenRuleAction.java:73)
	at com.google.devtools.build.lib.analysis.actions.SpawnAction.execute(SpawnAction.java:274)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeActionTask(SkyframeActionExecutor.java:779)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.prepareScheduleExecuteAndCompleteAction(SkyframeActionExecutor.java:722)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.access$800(SkyframeActionExecutor.java:100)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:624)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.call(SkyframeActionExecutor.java:581)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:392)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:439)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:200)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:398)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:497)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Steps:
- Set breakpoint in `SandboxStrategy#exec` on the call to actuallyExec.
- Run bazel build //:gen_version.
- When the breakpoint hits, remove the *-status.txt files, continue code execution.
- Break on the thrown exception and save the stack trace.

I verified that if the *-status.txt files are deleted after the code has already passed the position shown in the stack trace above, execution would succeed normally.

IMHO this also confirms that this is not a sandboxing issue. Instead, we have to find out why the files have not been generated by the BazelWorkspaceStatusAction (but that should trigger the failure of that action) or why they disappear in the time between BazelWorkspaceStatusAction creating them and the genrule needing them.

**Comment by damienmg** [comment]
@lberki back for his wits on the workspace status.

The number of correctness issue in Bazel is way to high.

**Comment by philwo** [comment]
I ran through some other possible flows, namely "BazelWorkspaceStatusAction fails to actually create those files", which correctly triggers an action failure due to missing output files and "status files disappear somewhere between SkyframeActionExecutor#completeAction was called on the BazelWorkspaceStatusAction and the genrule running", which shows the behavior seen on CI and the stack trace above.

**Comment by damienmg** [comment]
So that's a bad error message basically because the workspace status command fails?

**Comment by philwo** [comment]
No, the workspace status command seems to correctly generate the two files, bazel-out/stable-status.txt and bazel-out/volatile-status.txt. If it wouldn't for some reason, Skyframe would abort the build due to missing output artifacts with a very different error message.

What's also interesting is that not the genrules themselves are failing (e.g. because some sub-command returns an error exit code), but the failure happens inside Bazel before they even run, because the sandbox cannot access the file.

It looks like a race condition to me, but I have no clue where it could be... why would anything delete the bazel-out/*-status.txt files during a build?

**Comment by philwo** [comment]
I traced all I/O syscalls during a build using Xcode Instruments and that also doesn't show anything suspicious like a possible race condition where the *-status.txt files are deleted during a build.

I'm out of ideas...

**Comment by kchodorow** [comment]
It looks like the sandbox is trying to symlink the wrong path (from the link): 

```
ERROR: /Users/ci/workspace/gerrit/BAZEL_VERSION/HEAD/PLATFORM_NAME/darwin-x86_64/gerrit-launcher/BUILD:12:1: Executing genrule //gerrit-launcher:gen_root failed: I/O exception during sandboxed execution: /private/var/tmp/_bazel_ci/ecb628661259d45b1bcf8030dc6f079b/execroot/darwin-x86_64/bazel-out/volatile-status.txt (No such file or directory).
```
This should be `ecb628661259d45b1bcf8030dc6f079b/execroot/gerrit/bazel-out/darwin-...`.  Are your repro's paths like this?

I'm guessing this is a side effect of some of the execroot stuff I've been doing (although I thought all the changes that would have effected this were rolled back...)

**Comment by philwo** [comment]
@kchodorow Wow, well spotted! I'll have a look at the sandboxing code right now to see where that could come from.

**Comment by philwo** [comment]
It's too late today to figure this out here, I'll have another look at it tomorrow.
Kristina, if you have any idea, feel free to dig further.

**Comment by kchodorow** [comment]
I'll take a look.

**Comment by kchodorow** [comment]
Actually, wait, I hadn't realized that darwin-x86_64 was the directory name... so the execroot is right.  Still looking, but fewer ideas.

**Comment by philwo** [comment]
I'll just summarize what we found out so far:

About these files:
- Bazel always creates the `bazel-out/stable-status.txt` and `bazel-out/volatile-status.txt` files, even for empty builds (just running `bazel build` with no targets).
- If the --workspace_status_command would fail for some reason, Bazel would print `ERROR: Process exited with status 1: Process exited with status 1` and the build would fail. I have tried this on my machine that this really happens.
- If for some reason the `BazelWorkspaceStatusAction` would fail to do produce these files, Skyframe would immediately abort the build with a "action failed to produce output artifacts" error. I have also tried this on my machine that this really happens.
- If the files for some reason disappear after the action ran successfully, but before the genrules are run, we would see exactly the error message as on CI and in the stack trace above.

About the path in the log:
- The path to the files as shown in the error messages is correct, the files are really supposed to be there on a normal Bazel system (e.g. `/private/var/tmp/_bazel_philwo/7a01905b4627ca044e5e3f5ad5b14d26/execroot/bazel/bazel-out/volatile-status.txt`). Verified on my machine.

About the failing genrules:
- genrules that have `stamp = 1` depend on the `bazel-out/stable-status.txt` and `bazel-out/volatile-status.txt` artifacts, which guarantee that Bazel will only run the genrules once these artifacts have been produced. There is additional proof that this is indeed happening, because the I/O Exception that we're getting from the sandbox happens, *because* it tries to resolve these two artifacts from the inputs of the failing genrule.
- If someone would forget to set `stamp = 1`, there might be race condition, but the error message would be different (we'd instead see bash failing to use these files, not an I/O exception from Bazel). Verified on my machine.
- The code that fails and throws the I/O exception is calling `Path#resolveSymbolicLinks()` on the path that we know should exist. It fails with "No such file or directory". This means that a file that we know must be there either doesn't exist or is a dangling symlink.

So, what *could* possibly trigger this error?
- No clue. I even played around with --noexperimental_check_output_files and --nostamp, but I couldn't reproduce the failure seen on CI.

**Comment by lberki** [comment]
Whatever the reason for this bug is, it must be specific to Darwin because we don't see this failure on any other platform.

**Comment by lberki** [comment]
We could try disabling the sandbox Just In Case. That would either pin the blame on the sandbox or exonerate it.

**Comment by damienmg** [comment]
sgtm let me try that.

**Comment by damienmg** [comment]
It fails without sandbox too.

**Comment by damienmg** [comment]
Cannot repro on my machine i'll CRD into the slave.

**Comment by damienmg** [comment]
The error still happens after a clean...

**Comment by damienmg** [comment]
clean expunge made the problem goes away.

**Comment by damienmg** [comment]
So this bug goes on standby until the issue is reproduced.

Action for next time: tar up the output base for analysis

**Comment by damienmg** [comment]
So the results of my investigation shown that clean expunge clear it and the problem is the workspace go into a weird state where it output part of the file under "darwin_x86-64" and other part under  "io_bazel". I  suspect it to be the fallout of #2936.

Assigning to Kristina for her expertise regarding the execroot.

I uploaded the output base of 2 failures at:

* https://mirror.bazel.build/ci.bazel.io/output_base_darwin-1-bazel-tests-latest.tar.gz
* https://mirror.bazel.build/ci.bazel.io/output_base_darwin-2-gerrit-HEAD.tar.gz

**Comment by lberki** [comment]
The convenience symlinks exist only in the workspace (where you run Bazel from). So I can't think of a way for changes to convenience symlinks to cause this.

**Comment by damienmg** [comment]
Right indeed, but the confusion might exists somewhere else, no?

**Comment by kchodorow** [comment]
I don't think it could exist anywhere else... now the symlinks & the execroot point to the directory basename. 

I'll take a look at the output dirs (thanks for harvesting them!) but regardless, this isn't a breakage anymore.

**Comment by kchodorow** [comment]
This was basically caused by attempts at #1681, so I'm going to roll this into testing that works.
