### ISSUE TITLE
Correct label_list docs

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#2821]
### Description of the problem / feature request / question:

Following I will reference to `label_list` as _labels_.
From the docs:

> Creates an attribute which is a list of type Target which are specified by the labels in the list. See label for more information.

Which is not true.

1. Lists are mutable, which AFAIK _labels_ are not.
2. You cannot add the same label multiple times.
3. Not sure whether indices are preserved (probably not - see 4.).
4. I would expect multi-file labels to expanded into multiple entries in _labels_.

So please properly document what _labels_ is.

Bonus points if you rename _label_list_ to _labels_. This way no (wrong) limitations are enforced by the name.

**Comment by c-parsons** [comment]
https://docs.bazel.build/versions/master/skylark/lib/attr.html#label_list has improved a bit since this bug was filed, but I'm happy to address each of these concerns:

> * Lists are mutable, which AFAIK _labels_ are not.

Lists are frozen between evaluation contexts. See https://docs.bazel.build/versions/0.23.0/skylark/language.html#mutability

> * You cannot add the same label multiple times.

True! Lets remark that the labels must be unique. (I'll make a change)

> * Not sure whether indices are preserved (probably not - see 4.).

They are preserved.

> * I would expect multi-file labels to expanded into multiple entries in _labels_.

I think this is covered by the improvements on the documentation for `label_list` and for `Target` -- particularly, `Target` has a field `files`, which implies that a single target may have multiple files.
