### ISSUE TITLE
name conflicts of .so file in android binary

### ISSUE THREAD

**Issue by ldjhust** [bazelbuild/bazel#2851]
Hi, I'm linking a `cc_library` to an `android_binary` and getting a naming issue. Can someone tells me how to solve it?

The error messages are like this:

    ERROR: /the/path/to/BUILD:10:1: in android_binary rule //:debug_apk: Each library in the transitive closure must have a unique basename to avoid name collisions when packaged into an apk, but two libraries have the basename 'libSound.so': libs/armeabi/libSound.so and libs/armeabi-v7a/libSound.so.
    ...

The `cc_library`:

    cc_library(
        name = "native_library",
        srcs = glob(["libs/**/*.so"])
    )

The `android_binary`:
```
android_binary(
    name="debug_apk",
    custom_package = "com.xtbc.zc",
    manifest = "AndroidManifest.xml",
    legacy_native_support = 0,
    resource_files = glob(["src/main/res/**"], exclude=["res/.DS_Store"]),
    deps = [
        ":zc_lib",
        ":native_library"
    ],
)
```

>PS: I also add `legacy_native_support = 0` to `android_binary` but nothing changed, it still failed with the same error

The version of bazel I'm using:

```
Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:39:33 2017 (1489671573)
Build timestamp: 1489671573
Build timestamp as int: 1489671573
```

The contents of libs directory:

    libs
    ├── armeabi
    │   ├── libSound.so
    │   ├── libSec.so
    │   ├── libWatch.so
    │   └── libTec.so
    ├── armeabi-v7a
    │   ├── libSound.so
    │   ├── libSec.so
    │   └── libWatch.so
    ├── x86
    │   ├── libSound.so
    │   ├── libSec.so
    │   ├── libWatch.so
    │   └── libTec.so
    |—— other jars

**Comment by aehlig** [comment]
To me it seems that your glob is overly broad; do you really want to link `armeabi/libSound.so`, `armeabi-v7a/libSound.so`, and `x86/libSound.so` in a single binary? The layout of the `libs` directory suggests dispatching on the architecture you're building for.

Over to our experts to comment on best practices for doing this dispatch.

**Comment by ldjhust** [comment]
OK, thanks very much for your response! Looks like it's not the bazel's problem. I should rename each `so` file with a unique name.

**Comment by aj-michael** [comment]
Hmmm, I think this is a valid use case and I am surprised to see this error. We definitely support multiple native libs of the same name with --fat_apk_cpu, although typically they are built from source and are not prebuilt .so files. @ahumesky, WDYT?

**Comment by ahumesky** [comment]
So you could rename the .so files, but then you'd have to detect the architecture at runtime in order to choose the right library to load.

One way to select the .so files to include in the apk is to use `config_setting`, `select`, with `--android_cpu` (and `--fat_apk_cpu`):

```
android_binary(
  name = "app",
  ...
  deps = [":jni"],
)

config_setting(
  name = "android_x86",
  values = {
    "android_cpu": "x86",
  }
)

config_setting(
  name = "android_armeabi-v7a",
  values = {
    "android_cpu": "armeabi-v7a",
  }
)

cc_library(
  name = "jni",
  srcs = select({
    ":android_x86": glob(["libs/x86/*.so"]),
    ":android_armeabi-v7a": glob(["libs/armeabi-v7a/*.so"]),
  }),
)
```

When you do `bazel build //your:app --android_cpu=x86 --fat_apk_cpu=""`, you'll get the x86 .so files in the apk, and when you use `--android_cpu=armeabi-v7a`, you'll get the arm .so files. (The `--fat_apk_cpu=""` is necessary because `--fat_apk_cpu` is the default to use, where `cc_library` rules in the dependencies of `android_binary` rules are compiled for each architecture specified with `--fat_apk_cpu`)

Having separate apks with the different architectures could be desirable if you don't want users to have to download .so files for all architectures when they're only going to use one set of .sos. If however you do want to include all .so files in the apk, you can use `--fat_apk_cpu` with `config_setting` and `select`:

```
android_binary(
  name = "app",
  ...
  deps = [":jni"],
)

config_setting(
  name = "cpu_x86",
  values = {
    "cpu": "x86",
  }
)

config_setting(
  name = "cpu_armeabi-v7a",
  values = {
    "cpu": "armeabi-v7a",
  }
)

cc_library(
  name = "jni",
  srcs = select({
    ":cpu_x86": glob(["libs/x86/*.so"]),
    ":cpu_armeabi-v7a": glob(["libs/armeabi-v7a/*.so"]),
  }),
)
```

Then with `bazel build //your:app --fat_apk_cpu=armeabi-v7a,x86` both sets of .so's should be in the apk. (The the reason that the `config_setting` rules here use `cpu` instead of `android_cpu` as above is basically that `--fat_apk_cpu` gets translated into multiple instances of `--cpu` for `cc_library`)

**Comment by luoyushouchai** [comment]
@ahumesky  I run the commend: bazel build //my:app --fat_apk_cpu = x86. The fatal information is:No toolchain found for cpu 'x86', Valid cpus are:[
  k8,
  armeabi-v7a,
  x64_windows_msvc,
  x64_windows_msys,
  s390x,
  ios_x86_64,
]

**Comment by ldjhust** [comment]
@luoyushouchai The toolchains are provided by NDK, have you declared the `android_ndk_repository` in your `WORKSPACE` file?

**Comment by luoyushouchai** [comment]
@ldjhust Thanks

**Comment by luoyushouchai** [comment]
@ldjhust How to dependencies compiler jar, which is "apt 'com.jakewharton:butterknife-compiler:8.5.1'" in
gradle ?  ISome suggestions？

**Comment by aj-michael** [comment]
Hey @luoyushouchai, for the sake of organization can you open a new github issue about butter knife?

**Comment by aj-michael** [comment]
@luoyushouchai , I threw together https://github.com/aj-michael/bazel-butterknife-example to demonstrate how to use butterknife with bazel.

Please open a separate github issue if you have any questions about it.

**Comment by luoyushouchai** [comment]
@aj-michael Sorry and thanks!
