### ISSUE TITLE
android_library with CollectionIncompatibleType Error

### ISSUE THREAD

**Issue by ldjhust** [bazelbuild/bazel#2872]
Hi guys, I'm using bazel to build my android project, which originally build with gradle and works fine. But now I'm meeting a strange error during the build process with bazel:
```
.../xxx.java:71: Error: [CollectionIncompatibleType] Argument 'argA' should not be passed to this method; its type typeA is not compatible with its collection's type argument typeB
           return xxx.get(argA);           
                              ^
    (see http://errorprone.info/bugpattern/CollectionIncompatibleType)
```

I have already checked the source code, the type of A and type of B are both implemented  the `android.os.Parcelable` interface, so the incompatible type error shouldn't appear in theory. What's maybe the problem here?

Thanks very much for any help!

**Comment by aj-michael** [comment]
Hey @ldjhust, could you post a minimal reproduction example of your code that gets this error? My theory is that type A does not inherit from type B (even though they both implement the same interface).

Also, this issue may be better suited to be asked at https://github.com/google/error-prone since the error you are seeing is from error prone.

**Comment by ldjhust** [comment]
OK thanks very much @aj-michael ! You are really an experts!
