### ISSUE TITLE
DefaultInfo doesn't work as examples show

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3016]
Code:
https://gist.github.com/endobson/06448eb94f28c1e2d364e282ef6a0cc6

Working of example like:
https://bazel.build/versions/master/docs/skylark/cookbook.html#runfiles-and-location-substitution

Error message:
```
endobson@yggdrasil () ~/tmp/bazel-bug % bazel build //...
INFO: Reading 'startup' options from /Users/endobson/.bazelrc: --watchfs
ERROR: /Users/endobson/tmp/bazel-bug/rule.bzl:7:11: name 'DefaultInfo' is not defined.
ERROR: package contains errors: .
ERROR: Skipping '//...': no targets found beneath ''.
WARNING: Target pattern parsing failed. Continuing anyway.
INFO: Found 0 targets...
ERROR: command succeeded, but there were errors parsing the target pattern.
INFO: Elapsed time: 0.198s, Critical Path: 0.00s
```

### Environment info
* Operating System:
macOS

* Bazel version (output of `bazel info release`):
release 0.4.5- (@non-git)
Used the same code as 4.5, but built myself.

**Comment by iirina** [comment]
I tried building your example with bazel built @ HEAD and it worked, so I assume these changes will be available in the new release. Since the release should happen in the next couple of days, updating the documentation won't be necessary. You could try [the latest RC](https://storage.googleapis.com/bazel/0.5.0/rc8/index.html ).
