### ISSUE TITLE
Bazel's grep-based bash completion isn't always sufficient

### ISSUE THREAD

**Issue by EricCousineau-TRI** [bazelbuild/bazel#3021]
### Description of the problem:

As we are developing [drake](https://github.com/RobotLocomotion/drake/), we have noticed that we frequently do not get all valid / any bash completion with `bazel test` or `bazel run`, but we do seem to be able to consistent do bash completion with `bazel build`.

### If possible, provide a minimal example to reproduce the problem:

```bash
$ cd $(mktemp -d)
$ git clone https://github.com/RobotLocomotion/drake drake-distro
$ cd drake-distro/drake/solvers
$ bazel test :<TAB><TAB>
<NO OUTPUT>
$ bazel test //drake/<TAB><TAB>
<Packages only, no targets>
$ bazel test //drake/solvers:<TAB><TAB>
<NO OUTPUT>
```

As a workaround, if I add the following two lines in `~/.bash_completion` (to mimick `build` completion):
```bash
BAZEL_COMMAND_RUN_ARGUMENT="label"
BAZEL_COMMAND_TEST_ARGUMENT="label"
```
See: https://github.com/EricCousineau-TRI/repro/commit/733fff94136b6b2e124788f99fcdf7dcbc1223b6
Then I get at all buildable targets, which is more convenient than none.

### Environment info
```
$ cat /etc/issue
Ubuntu 16.04.2 LTS \n \l
$ bazel info release
release 0.4.5
```

###  Have you found anything relevant by searching the web?
Not in a quick search.

### Anything else, information or logs or outputs that would be helpful?
Perhaps with how we configure `drake_cc_test`, it escapes the `"label-test"` and `"label-bin"` argument types and their filtering mechanisms in `_bazel__expand_target_pattern`?

**Comment by EricCousineau-TRI** [comment]
Yup, since `BAZEL_COMPLETION_USE_QUERY=false` by default (and it's way too slow if it's on, as indicated by the comments), then the text matching in `_bazel__matching_targets` of `.*_test|test_suite` was not matching against our specification as `drake_cc_googletest(...)`. We would not have seen this if we had defined our target as `drake_cc_test`, or `drake_cc_google_test(...)`.

Relaxing the patterns to the following (removing the underscore) permits them to work a little more easily:
```bash
# In ~/.bash_completion
BAZEL_BUILD_MATCH_PATTERN__test='.*test|test_suite'
BAZEL_QUERY_MATCH_PATTERN__test='test|test_suite'
BAZEL_BUILD_MATCH_PATTERN__bin='.*(binary|test)|test_suite'
BAZEL_QUERY_MATCH_PATTERN__bin='binary'
```

**Comment by haxorz** [comment]
hi.

coincidentally, we got a request internally to flip the default BAZEL_COMPLETION_USE_QUERY behavior (that is, have the bash completion script use 'bazel query' by default).

> and it's way too slow if it's on, as indicated by the comments

the comments are many many years old and i don't think anyone has reconsidered this in a while, until a few days internally.

in your opinion, what would be "too slow"? would you be willing to wait up to a few seconds* if it meant you got correct results? i'm trying to weigh the pros and cons of changing the default behavior. your opinion would be valued, especially as someone who has taken the time to read through the existing bash completion implementation.

i am personally not happy with the grep-based implementation. for example, it predates skylark (bazel's extension mechanism) and doesn't support it. i think it's lame for bazel's bash completion mechanism to not support the use-case we're trying to encourage!

*the first time you ever use bash completion in your bazel workspace. the bash completion script starts up its own bazel server, so the first completion ever will have to the bazel server startup cost. subsequent completions should take ~100ms, because there will be an existing bazel server and it's caches will be hot.

**Comment by EricCousineau-TRI** [comment]
Howdy, and thanks for the follow-up!

I re-tested it on my machine, and once the cache is hot, it's definitely usable (albeit still a tad slower than the grep-based completion).
Problem is, the initialization time you mentioned is more like 10-15 seconds on [`drake-distro`](https://github.com/RobotLocomotion/drake/), which at present freezes the prompt and prevents me from seeing any input - which would make it a deal-breaker for me.
I think even the 2-3 second range would make me want to look at an alternative.
(If there is something in the works that would speed that up to 0.5 seconds, please do let me know!)

However, if there were a progress bar that indicated that (a) the caching is warming up, and (b) how to disable slow-and-accurate for dirty-but-fast, I think I'd be happier with the result.

I made a rough prototype script of that behavior, showing a pseudo-progress bar, and inlining instructions\*:
[sample_command_completion.sh ](https://gist.github.com/EricCousineau-TRI/3f611ea11a2b5c6ddd27ed860cc86116)

\* `bash` completion functions, registered with `complete -F`, activates on a single tab, but doesn't display until the second tab - if a user presses tab only once, they will see the progress bar, but the prompt won't be refreshed (hence the `show-prompt` hack); if they press it twice, it will refresh (and the hack will show the prompt twice - though I prefer two prompts on double-tab than no prompt on a single tab).
I didn't look too hard to see if there is a way to discriminate between single tabs and double-tabs.

**Comment by haxorz** [comment]
> (If there is something in the works that would speed that up to 0.5 seconds, please do let me know!)

given blaze's client-server architecture and the fact that the blaze server is a massive java binary and is not optimized for startup time, this isn't currently realistic.

> Do you think it might be useful to do something akin to this?

your idea of displaying a bar indicating that something is actually happening is a good one.

but how about this idea: the default (hybrid) behavior is
-if there's already a running bazel server for the bash completion script (that is, one with --output_base=/tmp/bazel-completion-$USER), use that
-otherwise, startup a bazel server with --output_base=/tmp/bazel-completion-$USER, but don't block on that. instead, just print a message explaining what's happening (and how to opt-out of the behavior and the message) and use the grep-based completion.

**Comment by EricCousineau-TRI** [comment]
Sorry for the late follow-up -

> given blaze's client-server architecture and the fact that the blaze server is a massive java binary and is not optimized for startup time, this isn't currently realistic.

Quite understandable - given bazel's present awesomeness, was just hopeful :)

> but how about this idea: the default (hybrid) behavior is...

Sounds good to me!

**Comment by meisterT** [comment]
Closing this as we are not working on it.
