### ISSUE TITLE
Support remote caching + {sandboxing, workers}

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#3027]
Bazel currently always falls back to local, non-sandboxed execution when remote caching is enabled. We should support fallback to sandboxed, and to local workers.

**Comment by softprops** [comment]
It took me a decent amount of time to figure out the current behavior m was by design and not a bug when trying to figure out a performance problem with scala rules with caching enabled -
 https://github.com/bazelbuild/rules_scala/issues/196. It would be great to get the current expected behavior documented. Bonus points for actually enabling fallback on workers!

**Comment by AustinSchuh** [comment]
Any idea on which release this is scheduled for?  We have rules which don't work without sandboxing enabled, which makes this a show-stopper for enabling distributed caching.

**Comment by ulfjack** [comment]
Marking as dupe of #1531.
