### ISSUE TITLE
The docs and the help disagree on whether --batch is ever a good idea

### ISSUE THREAD

**Issue by mmorearty** [bazelbuild/bazel#3051]
### Description of the problem / feature request / question:

`bazel help --long startup_options` includes this:

>  --[no]batch (a boolean; default: "false")
>    If set, Blaze will be run in batch mode, instead of the standard
>    client/server mode. Running in batch mode prevents Blaze from caching data
>    in memory, which makes it a lot slower. We recommend against using this
>    flag.

But several different places on https://bazel.build/versions/master/docs/bazel-user-manual.html describe `--batch` as being a useful option in some scenarios. In fact, one place on that page says that `--batch` is "strongly recommended" when doing scripting. This directly contradicts the above wording, "We recommend against using this flag."

If my understanding is correct, the docs have it right. If that's true (and you would know better than I do), then the help message should be reworded to be less discouraging. Perhaps something like this:

>  --[no]batch (a boolean; default: "false")
>    If set, Blaze will be run in batch mode, instead of the standard
>    client/server mode. Bazel will run slower in batch mode, compared
>    to client/server mode. Therefore, using batch mode often makes 
>    more sense in cases where performance is less critical, such as
>    continuous builds.

### Environment info
* Operating System:

All

* Bazel version (output of `bazel info release`):

0.4.5

**Comment by laszlocsomor** [comment]
You're right, that is contradictory.

The `bazel help` text was written with interactive builds in mind, that is, for the use case of running bazel as part of the development cycle, when you edit your code and want to rebuild or rerun tests. Batch mode shuts down the bazel server after the build (test/run/query/etc.) is done, which is unnecessary in this case and just slows you down, therefore we don't recommend it.

As I see it, batch mode is useful when Bazel is executed from a script as a one-shot run, and the script author wants to ensure that Bazel shuts down afterwards, in order to avoid leaving behind a Bazel server process with its sizable memory footprint. (Batch mode is also useful for us Bazel developers to debug server mode bugs or when we run shell integration tests of Bazel itself.)

Either way the documentation needs to be clarified, thanks for bringing that to our attention! If you feel like fixing the doc, I'd be happy to review the change / PR.

**Comment by mmorearty** [comment]
Okay @laszlocsomor, I wrote something up — feel free to edit it! I just simplified the help message to explain what `--batch` does, without getting into editorializing about whether it's appropriate to use, since that's a pretty long discussion that is covered quite well in the docs. Thanks!

**Comment by laszlocsomor** [comment]
Thank you!
