### ISSUE TITLE
Remove depset equality operation

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3111]
### Description of the problem / feature request / question:

From the docs:

> Depsets use reference equality

IMO allowing to check equality of a depset only makes sense if that actually deep check depsets.
Anyone not reading the fine print of the documentation will expect depsets to deep check.
So it would be way clearer if depsets could not be checked for any equality at all, especially since I cannot think of a use case where you would like to check in the first place.

**Comment by laurentlb** [comment]
Every object can be checked for equality. A common pattern is to check whether is an object is `None`. It would be very surprising if the `==` operator would raise an error.

**Comment by brandjon** [comment]
Equality is a required operation of all Starlark values. Well, I'm not sure the spec necessarily mandates that equality works for application-defined types, but I've always thought of it that way. We even [require](https://github.com/bazelbuild/starlark/blob/1fe16b4cf5d208e148c73f67a6667a9f7dab4544/spec.md#comparisons) that `NaN == NaN`.

The reason for depset reference equality is precisely because we can't do an implicit deep traversal over it. I understand users who expect it to behave as a structural collection may be surprised, but it's kind of fundamental to how depsets are used. If anything we can clarify documentation if it's lacking.
