### ISSUE TITLE
maven_aar does not work with empty res/ directory

### ISSUE THREAD

**Issue by aaronj1335** [bazelbuild/bazel#3116]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

`maven_aar` does not seem work for aar's with an empty `res/` directory.

### If possible, provide a minimal example to reproduce the problem:

1. clone https://github.com/aaronj1335/bazel-kotlin-android/tree/broken_build_empty_res_dir
2. run `bazel build :app`
3. observe error:

```
aaronstacy∂oɹdʞooqɔɐɯ-ʎɔɐʇsuoɹɐɐ ☠ ~/Downloads/test  11:11:04 Jun02
§ bazel build :app
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_aaronstacy/95464d7f40ee656ba804ea72b90dd3fa/external/google_tasks/aar/BUILD:4:1: Processing Android resources for @google_tasks//aar:aar failed: Process exited with status 2 [sandboxed].
Error parsing command line: While parsing option --primaryData: invalid UnvalidatedAndroidData: bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-fastbuild/bin/external/google_tasks/aar/_aar/unzipped/resources/aar does not exist
Try --help.
Use --strategy=AndroidAapt=standalone to disable sandboxing for the failing actions.
Target //:app failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.409s, Critical Path: 1.20s
```

The corresponding AAR, confusingly, has a `res/` directory, but it's empty:

```
aaronstacy∂oɹdʞooqɔɐɯ-ʎɔɐʇsuoɹɐɐ ☠ ~/Downloads/test  11:12:55 Jun02
§ unzip -l ~/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-tasks/10.2.6/play-services-tasks-10.2.6.aar
Archive:  /Users/aaronstacy/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-tasks/10.2.6/play-services-tasks-10.2.6.aar
  Length      Date    Time    Name
---------  ---------- -----   ----
      205  01-01-1980 00:00   AndroidManifest.xml
    24087  05-11-2017 20:26   classes.jar
     2177  05-11-2017 20:26   proguard.txt
        0  01-01-1980 00:00   res/
---------                     -------
    26469                     4 files
```

### Environment info
* Operating System: OS X 10.12.5

* Bazel version (output of `bazel info release`): release 0.4.5-homebrew

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

[this issue](https://github.com/bazelbuild/bazel/issues/561#issuecomment-259458533) and [the corresponding commit](https://github.com/bazelbuild/bazel/commit/26de97ba7c2725680e8e9a424362e31935c647f4?diff=split) have been most useful to me, but i haven't found anything else.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by aaronj1335** [comment]
FWIW, this `play-services-tasks` AAR is a base dependency for any Android app that uses the Play services SDK, which is most Android apps. IDK if it's valid to have that empty `res/` directory, but given the popularity of the library, it's probably worth fixing.

I'd be happy to send a PR if you could point me to the change that needs to be made!

**Comment by aj-michael** [comment]
Hey @aaronj1335 , this was a mac-specific bug in the underlying `aar_import` rule that `maven_aar` uses. It was previously reported as https://github.com/bazelbuild/bazel/issues/2597. Unfortunately, the fix (https://github.com/bazelbuild/bazel/commit/acdd43bf8832db562312c6b273687dd6f1d219b7) barely missed the cutoff for the 0.4.5 release. It should work in 0.5.0, however we actually pulled 0.5.0 off of homebrew for some other reasons (see https://github.com/bazelbuild/bazel/issues/3107 if you're interested). Hopefully 0.5.1 will be on homebrew soon, but in the mean time you can workaround this issue with `bazel build --strategy=AndroidAapt=standalone` or by downloading the 0.5.1 release candidate from https://storage.googleapis.com/bazel/0.5.1/rc1/index.html.


The technical reason for this bug was that most of Bazel was designed with the assumption that we can know all of the artifacts needed for the build reasonably early in the build. The AAR file format is basically a grab bag of directories that may-or-may-not be present, and we cannot know until we open it.
