### ISSUE TITLE
Make the artifact attribute of maven_jar available in aspect of jar target

### ISSUE THREAD

**Issue by natansil** [bazelbuild/bazel#3120]
I'm writing a post-build tool that synthesizes maven pom files after a bazel build. I'm using *aspects* to gather relevant information on the various *targets*.

One of the features involves adding **external** jar dependencies to the relevant pom files.

Lets assume our ***workspace*** contains the following target:

    maven_jar(
     name = "com_google_guava_guava",
     artifact = "com.google.guava:guava:19.0",
    )
and one of our **BUILD** files contains a target which has *guava* as a dependency

    scala_library(

    name = "somename",
    srcs = glob(["*.scala"]) + glob(["*.java"]),
    deps = [
        "@com_google_guava_guava//jar:file" , 
    ],

In an *aspect* for this target I want to be able to retrieve the **artifact** of the *guava* jar target dependency

**Comment by petroseskinder** [comment]
Natan, it is unclear what you're question is or what you're post-build tool is trying to accomplish. Can you expand?

**Comment by natansil** [comment]
Sure,
The tool allows for bazel-maven interop, meaning that a repo built with bazel will be available in the form of maven jars (with coarser granularity)+pom files.

The tool analyzes the build files using aspects.
in order to add a dependency for the external jar, we need the artifact attribute from the maven_jar in the workspace.

Hope this makes it more clear

**Comment by kchodorow** [comment]
If you mean the `artifact = "com.google.guava:guava:19.0"` line from the WORKSPACE file, you cannot get that from an aspect.  That would be similar to `somename` carrying around a reference about your project's git clone URL.

However, you can get the filename of the artifact, if that helps you, e.g.,

```
for d in ctx.rule.attr.deps:
  for f in d.files:
    print('dep: %s' % f.path)
```

**Comment by ittaiz** [comment]
We know we currently can't get it but Damien said he thinks it's a
reasonable request and asked us to open a feature request.
Not sure how he thought to fit it in.

**Comment by kchodorow** [comment]
Ah, okay. It might not be feasible to do with aspects and Damien's on vacation right now so I'm not sure what he had in mind, but I would like to make it easier to grab info from WORKSPACE file rules.

**Comment by helenalt** [comment]
@damienmg  looks like we're looking for your input on this issue - please check when you're back

**Comment by ittaiz** [comment]
Btw,
One can also plug in through jvm_maven_import_external if a simple
maven_import rule is contributed (that will be like java_import but with
the provider).
This will have the benefit of using the import_external infrastructure

**Comment by dslomov** [comment]
This is a reasonable feature for maven interop - @dkelmer wdyt?

**Comment by dkelmer** [comment]
Since maven_jar is being deprecated I won't go down that route. 

But Ittai, how do you envision this maven_import rule to interop with jvm_maven_import_external? Or are you saying you would write extra maven_import rules for the jars that you need to collect using your post-build tool?

**Comment by ittaiz** [comment]
My idea is that we have another macro:
java_maven_import_external that calls jvm_maven_import_external with two
additional attributes:
1. rule_name (already exists) and gives it java_maven_import
2. Adds the “artifact” as an additional attribute (because
jvm_import_external proxies those to the rule)
This is the small part since we have most of the infra in place.
The bigger part (which isn’t that big) is adding java_maven_import which
will work just like java_import but will also add an attribute for
artifact. The value of the attribute can be exposed as a file or as a
provider of both. It can be exposed structured or encoded (with “:”).

A small alternative on this is that java_maven_import_external will decode
the maven coordinates and pass several attributes to the rule. The value
there is that this will make usage of bazel query much more powerful. For
example we often get the question of “what is the version of commons-IO”
given that the definition is in a different repository of managed
dependencies.
If taking this route we should try to share the implementation of the
decode between java_maven_import_external and jvm_maven_import_external.

Finally if java_maven_import will expose a “use_ijar” attribute then maybe
we (rules_scala) will be able to use all of this as is

**Comment by jin** [comment]
The coordinates are now accessible as a `maven_coordinates` keyed string value in the `tags` list.

https://github.com/bazelbuild/bazel/blob/e75ed02dbd19d753790853e63adf553eb92609c2/tools/build_defs/repo/jvm.bzl#L271-L272
