### ISSUE TITLE
How to understand Bazel's output time?

### ISSUE THREAD

**Issue by shuzhang1989** [bazelbuild/bazel#3164]
Hi, 

maybe a simple question. Everytime after a build is done, i see something like:

Elapsed time: 1034.748s, Critical Path: 257.54s

Wondering what's the difference between Elapsed Time and Critical Path? what can be causing the time difference?

**Comment by meteorcloudy** [comment]
@laszlocsomor Can you help answering this question?

**Comment by laszlocsomor** [comment]
Hey, thanks for your question!

We recommend posting Bazel related questions on [StackOverflow using the 'bazel' tag](https://stackoverflow.com/questions/tagged/bazel). We will be happy to answer it there, so that other users can also benefit.

@meteorcloudy : Could you please ask this question on SO for me? I've already forwarded 6 questions today to SO and they won't let me ask more.

**Comment by meteorcloudy** [comment]
Done, forwarded to https://stackoverflow.com/questions/44498316/how-to-understand-bazels-output-time

**Comment by laszlocsomor** [comment]
Thanks, answered.

**Comment by shuzhang1989** [comment]
thank you guys!
