### ISSUE TITLE
Issues while running bazel with textsum

### ISSUE THREAD

**Issue by JafferWilson** [bazelbuild/bazel#3213]
![capture](https://user-images.githubusercontent.com/13446197/27272053-dc84f35a-54e5-11e7-8c59-1624f633e266.PNG)
The image shows the pop up I am getting while running the bazel in windows. Kindly let me know what I can do to make it run comfortably.

**Comment by laszlocsomor** [comment]
Hey,

How did you install Bazel?

**Comment by laszlocsomor** [comment]
...I mean, did you install from Chocolatey, download a release binary, built one yourself?

**Comment by mhlopko** [comment]
Please do not send screenshots, it makes it harder to read, reproduce, or to google your issue for other people.

**Comment by mhlopko** [comment]
I'm very sorry if it came across as harsh, I didn't mean that. I was shooting for emotion-less informal black-tea-dry style :)

**Comment by JafferWilson** [comment]
@mhlopko No hard feelings. I will keep that in mind when I have any issues.

**Comment by JafferWilson** [comment]
I have followed the windows installation process from the website: https://bazel.build/versions/master/docs/install-windows.html using the part `Use the binary distribution` that's it. 
But could not install owing to the issue.

**Comment by JafferWilson** [comment]
This is the error what I am getting:
```
The procedure entry point
_ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteS1_EEPFvvE could not be located in the dynamic link library
C:\bazel.exe
```

**Comment by laszlocsomor** [comment]
@JafferWilson : Thanks for the info! This issue looks similar to https://github.com/bazelbuild/bazel/issues/2756, and the reason is likely the same: you are using the MSYS-ful version of Bazel (as opposed to the MSYS-less version, i.e. the one built with MSVC), and your `PATH` environment variable is set up incorrectly, such that Windows finds an MSYS dll file but it's the wrong version. This is typically caused by having tools installed that use MSYS behind the scenes, such as Git for Windows, but they typically use a different version than the one Bazel is linked against, and their path comes sooner on `PATH` than the right MSYS's path, and so Bazel tries to load an incompatible dll. Another possibility is you installed a newer MSYS version than the one Bazel is linked against, and it comes first on your `PATH`, again leading to Bazel finding an incompatible dll.

Try our MSYS-less version: it is not linked to the MSYS dll (though it still needs MSYS at runtime in order to run shell commands): it's available either [with a bundled JDK](https://github.com/bazelbuild/bazel/releases/download/0.5.1/bazel-msvc-0.5.1-windows-msvc-x86_64.exe) or [without one](https://github.com/bazelbuild/bazel/releases/download/0.5.1/bazel-msvc-0.5.1-without-jdk-windows-msvc-x86_64.exe).

**Comment by JafferWilson** [comment]
Yes it did worked tanks.
