### ISSUE TITLE
Rsync in test works without requires-network

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3214]
### Description of the problem / feature request / question:

I have the following test:

    # BUILD
    sh_test(
        name = "rsync_test",
        srcs = [
            "deploy.sh",
        ],
    )

    # deploy.sh
    #!/bin/sh

    echo FOOOOO > localFile
    rsync localFile user@remote_server:/var/www/remoteFile

Executing that test uploads to remote just fine :(

### Environment info
* Operating System: Ubuntu 16.04.2
* Bazel version (output of `bazel info release`): 0.5.1

**Comment by philwo** [comment]
Yes, that changed with Bazel 0.4.0 - due to a performance issue in the Linux kernel involving tear down of network namespaces that we can't work around, we had to disable network blocking by default in the sandbox.

Instead of "requires-network" for tests that need it, you have to opt-in to the possibly slower, but network blocked execution by adding the tag "block-network".

**Comment by abergmeier-dsfishlabs** [comment]
> due to a performance issue in the Linux kernel involving tear down of network namespaces

Has that been flagged in the kernel?

**Comment by philwo** [comment]
A couple of times in the past, but no one seemed to care: https://lkml.org/lkml/2014/8/28/584
I even got a proposed kernel patch for that from a colleague, but no one got around to try it. :|

One reason is that even if we'd fix this in the kernel, it'd take years to show up in distros so that we could rely on it.

It would still be great to make it faster. I'll put it on my list.
