### ISSUE TITLE
Archive incomplete extraction using new_http_archive

### ISSUE THREAD

**Issue by minorhacks** [bazelbuild/bazel#3283]
### Description of the problem / feature request / question:

I'm trying to migrate a new_local_repository rule to a new_http_archive rule. I'm having issues with Bazel claiming that expected files within the http archive do not exist. I'm not confident from an inspection of outputBase/external that the archive is being fully extracted.

My question(s):
* What is the behavior of extracting archives defined by (new_)http_archive?
* What logs/output can I enable/look at to ensure that the archive is being extracted successfully?

### If possible, provide a minimal example to reproduce the problem:
(not a minimal example, but here is what I am doing)

Confirm (with new_local_repository rule in place) that `bazel build ...` is successful

Packaging the directory of the new_local_repository using a command like:

    tar -czf my_repo.tar.gz -C my_repo .

Making my_repo.tar.gz available on an HTTP fileserver

Changing the new_local_repository rule to new_http_archive pointing to the appropriate URL

Execute `bazel build ...` which fails with errors such as:
   
    no such package '@my_repo//': $OUTPUTBASE/external/my_repo/some/path (No such file or directory)

where $OUTPUTBASE is the path to `outputBase` as defined [here](https://bazel.build/versions/master/docs/output_directories.html)

The specific file/directory it complains about is present in the archive as a symlink, and certainly not present at the outputBase path it complains about (i.e. the file was not extracted as expected from the archive).

Furthermore, when I examine the unpacked archive under outputBase/external/my_repo, there are clearly entire folders and files missing compared to a manual extraction of the same archive using `tar -xhf`

### Environment info
* Operating System:
Ubuntu 16.04

* Bazel version (output of `bazel info release`):
release 0.5.2

**Comment by dmitry-xnor** [comment]
Could be similar to the issue we are experiencing. In our case the culprit seems to be a recursive symlink that [Buildroot](https://buildroot.org/) uses to hook up `/usr` on the host. We use Buildroot to build custom toolchains for cross build to the various ARM boards.

Bazel does support recursive symlinks, but a symlink to `.` triggers a bug in Bazel. It tries to normalize the path, and ends up normalizing `.` to an empty string, and calling `symlink("", "/.../external/buildroot/usr")`, which returns ENOENT (due to the empty string) and Bazel fails.

Don't know if it's the same issue, but this too manifests itself as `usr` directory missing from the directory into which crosstool is unpacked.

If someone from Bazel team could comment, I could file this as a separate issue, along with a temporary workaround. Credit for investigating the issue goes to @alex-xnor.

**Comment by alex-xnor** [comment]
Well, in case it's useful, here's the workaround we have for our issue (which looks suspiciously similar to your issue but could potentially be something else):

* While Bazel mis-normalizes `.` to empty string, and also `dir/..` (if you're trying to be clever) to empty string, you can be even more clever: from a directory `dir`, Bazel will *not* normalize `../dir`. Hence, you can create a symlink to the current directory by making the symlink go up one directory and then back down.

* Bazel also changes how absolute paths within the targets of symlinks are interpreted. Specifically, it re-roots them at the repository base. Hence, if your symlink that you find unable to be created is at the top level of your TAR file, you can make the symlink point to `/` rather than to `.` (although this makes the symlink _only_ work when Bazel extracts it&mdash; standard `tar` will dutifully symlink to `/` which is _not_ the current directory or repository root).

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
