### ISSUE TITLE
Weird interaction between expand_location and alias

### ISSUE THREAD

**Issue by carl-stripe** [bazelbuild/bazel#3309]
I'm seeing a very bizarre error when using `expand_location` and `alias` together. Here's a minimalish reproducer:

https://gist.github.com/carl-stripe/b2eef191561b880445c91dafd7f40462
(I just plopped those three files and nothing else into a scratch directory in `/tmp`)

Here's what happens when I attempt to build:
```
/private/tmp/blub$ bazel build //...
ERROR: /private/tmp/blub/BUILD:8:1: in sad rule //:oh_noes:
Traceback (most recent call last):
	File "/private/tmp/blub/BUILD", line 8
		sad(name = 'oh_noes')
	File "/private/tmp/blub/sadness.bzl", line 2, in _sad_impl
		ctx.expand_location("$(location :hi)", ctx.attr.blub)
expected type 'Target' for 'targets' element but got type 'Target' instead.
ERROR: Analysis of target '//:oh_noes' failed; build aborted.
```

Certainly the error message is a bug—it makes no sense. I suspect the underlying incompatibility is also a bug, but I'm very new to Bazel and could just be misunderstanding something

### Environment info
`release 0.5.2-homebrew` (also saw it with `0.4.5`) on OS X 10.12.5

###  Have you found anything relevant by searching the web?
No (I googled for variants of `expand_location alias`)

**Comment by katre** [comment]
The specific error is that `alias()` rules create an instance of [AliasConfiguredTarget](https://github.com/bazelbuild/bazel/blob/259c9e8014ad960985c0ed99db2a879cdd2ac301/src/main/java/com/google/devtools/build/lib/rules/AliasConfiguredTarget.java), but `expand_location` requires instances to be [AbstractConfiguredTarget](https://github.com/bazelbuild/bazel/blob/259c9e8014ad960985c0ed99db2a879cdd2ac301/src/main/java/com/google/devtools/build/lib/analysis/AbstractConfiguredTarget.java) instances.

This error message is confusing, because both AbstractConfiguredTarget and AliasConfiguredTarget implement [TransitiveInfoCollection](https://github.com/bazelbuild/bazel/blob/259c9e8014ad960985c0ed99db2a879cdd2ac301/src/main/java/com/google/devtools/build/lib/analysis/TransitiveInfoCollection.java), which declares that its name is "Target".

The fix is probably for AliasConfiguredTarget to extend AbstractConfiguredTarget, or for expand_location to relax what it's willing to work with.

**Comment by katre** [comment]
Sending https://bazel-review.googlesource.com/c/12770/ to fix this.

**Comment by carl-stripe** [comment]
Amazing—thanks @katre!
