### ISSUE TITLE
rule function doesn't check its arguments sufficiently

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3334]
The [rule function](https://docs.bazel.build/versions/master/skylark/lib/globals.html#rule) says that its `implementation` argument must have exactly one parameter.
> the function implementing this rule, must have exactly one parameter: ctx.

But this is not checked until the rule is actually applied and then gives a poor error message.
```
Built-In: insufficient arguments received by _yaspl_srcs_impl(target, ctx) (got 1, expected at least 2)
```

I expect to see an error message that says more or less "rule: implementation argument is invalid: got: a function that requires at least 2 arguments, expected a function that can take 1 argument."

By delaying to function application and having the implementation function raise the error, the expectation is on the wrong side.

### Environment info
* Operating System:
macos 10.11.6

* Bazel version (output of `bazel info release`):
release 0.5.2- (@non-git)

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):
Release 5.2 zip file

**Comment by brandjon** [comment]
The error message is currently:

```
ERROR: /home/brandjon/src/test/pkg/BUILD:3:8: in my_rule rule //pkg:myrule: 
Traceback (most recent call last):
	File "/home/brandjon/src/test/pkg/test.bzl", line 1, column 5, in _rule_impl
		def _rule_impl(ctx, blah):
Error: _rule_impl() missing 1 required positional argument: blah
```

The wording on the last line is generated by the generic Starlark interpreter machinery, without any extra dressing up by Bazel. I don't think it's necessary to provide much more context, since the next step by the user is probably to check the documentation of the `implementation` parameter to `rule()`.

That said, the implementation function has a [declared type](https://github.com/bazelbuild/bazel/blob/968422dd6e6735b6066ccbe862b6bc6ab38ce4d6/src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java#L281) of `StarlarkFunction`, so we should be able to inspect the signature at the point where we declare the rule and provide a slightly cleaner experience.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
