### ISSUE TITLE
Add option for genrules to output to source directory

### ISSUE THREAD

**Issue by calder** [bazelbuild/bazel#3376]
I realize that modifying anything in the source tree is ideologically scary to Bazel. However, **this would be very useful for generating version controlled intermediate files.** With the right design, I think it can be both safe and intuitive.

I'm imagining adding an `output_to_srcdir` argument to the `genrule` rule. When set, the genrule's output is dumped back into the source directory instead of the genfiles directory. This would be mutually exclusive with `output_to_bindir`.

Autogenerated source files would _never_ be modified during a normal build. Instead, each genrules's outputs would be compared to the current version of that output in the source directory. If they matched, the build would proceed as normal. If not, it would fail and suggest rerunning with either an additional command line flag (`--regenerate_autogenerated_sources`) or a top level Bazel command (`bazel regenerate-autogenerated-sources ...`) to regenerate the out-of-date source files.

**Comment by laszlocsomor** [comment]
As I understand the use-case, this is out-of-scope for building and in the scope of, perhaps, workspace configuration. What I'm sure of is that an external tool would be both easier and safer to write for this purpose, than to introduce such a deep design change to Bazel.

The tool would copy the files from the output tree into the source tree, and update a manifest file that lists the path-digest pairs. A `genrule` or a `sh_test` would depend on the file-generating genrules, as well as on this manifest file, and compare the genrule-generated outputs' digests (in the output tree) to those in the manifest file, and would fail if there's a mismatch. In that case the user would need to run the external tool, thus update the source tree and the manifest, then rerun the build. This is exactly the same workflow as you described, except you'd run this tool instead of `bazel regenerate-autogenerated-sources`.

**Comment by laszlocsomor** [comment]
In light of my previous comment I don't think we'll support this.

**Comment by urbasus** [comment]
Though not supported I think an example of the technique could benefit people such as myself. Surely there is some repo somewhere doing it right.
