### ISSUE TITLE
Print understandable error message if bazel's and remote cache/executor hash functions mismatch.

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#3383]
cc: @ulfjack @ola-rozenfeld

**Comment by buchgr** [comment]
The remote execution protocol needs to support querying for which hash function to use.

**Comment by ola-rozenfeld** [comment]
> The remote execution protocol needs to support querying for which hash function to use.

If you mean that the API needs to be able to support more that one hash function, this is very problematic from the API standpoint. We have discussed this multiple times, and decided we just cannot do this.

You can, however, catch it and print a very clear error message, since the size always differs on different hash functions.

**Comment by buchgr** [comment]
I wasn't part of this discussion. Would you mind explaining the reason why the API can't support this? A remote execution server doesn't need to support multiple different hash functions, just one. If it had an API call, where the client could query the hash function that would be good enough already.

**Comment by ola-rozenfeld** [comment]
Oh, sorry, I misunderstood, I was talking about supporting multiple hash functions on the server. Querying alone should be fine -- although, it won't be easy to switch hash functions on demand in the Bazel server. We'd need to invalidate and recreate all the ActionInput caches -- this is why the digest function is a startup option and not a regular flag. 
What is the use-case, exactly? In the API, we plan to standardize the API on SHA256 soon and just not support anything else. Is someone building a SHA1 server that they don't want to migrate?

**Comment by ulfjack** [comment]
The primary use case is that we want to give a good error message if the server and client disagree on the hash.

In addition, there are reasons (legacy systems, integration with other existing systems) that someone might want to run a server with a specific hash rather than whatever is specified in the API. We'd have that problem internally, if we wanted to reuse the API for some of our internal systems.

Finally, how are you going to handle migration from SHA256 to a more secure hash when SHA256 gets broken at some time in the future?

I think it wouldn't hurt to allow querying the hash, although we could do that in a slightly hacky way with the existing protocol, e.g., try to upload an empty file and see if we get a hash mismatch on the server.

**Comment by ola-rozenfeld** [comment]
Oh, if we don't intend the client to recover from this, then it's much
simpler.
The API already specifies that the server should raise an INVALID_ARGUMENT
error when the hashes mismatch; maybe just the hash size on the server and
alter the error message to include the expected digest function? Something
like "Expected a SHA1 digest of size 64 bytes, got a digest of size 32
bytes (possibly MD5)." In the remote worker specifically, we can even add a
pointer to how the server and client digests can be modified.

**Comment by buchgr** [comment]
I would be in favor of keeping it simple and introducing a new rpc that simply allows to query for the hash function. In my opinion there is simply no need for any of the suggested hackery.

**Comment by ola-rozenfeld** [comment]
So in Bazel, the call will have to be in the buildStarting handler, right?

**Comment by alercah** [comment]
We originally discussed an RPC to query the hash. I can't remember offhand why we decided against it; possibly because we just didn't think it was necessary.

**Comment by ulfjack** [comment]
Do we also want to query other information from Foundry? E.g., whether Win
/ Mac platforms are supported?

**Comment by ola-rozenfeld** [comment]
I still don't understand why the query is needed. Even if we do have the query, we still need to print an understandable user message if we somehow get a digest mismatch (imagine a server-side bug, or a client connecting to a different instance of the server running a previous release with a different hash function, or anything). I mean, querying is not enough anyway, so why do it? Why not just return and print a good message to begin with?

> Do we also want to query other information from Foundry? E.g., whether Win / Mac platforms are supported?

(Ulf, I edited your comment to exclude a reference to an internal product) That's a totally different can of worms. We may add an API for that using our Platform message, but we need to design it carefully. Do we want to report current availability, or general availability, etc. But this is something we definitely want to do in the future, yes.

**Comment by buchgr** [comment]
That's been fixed a while ago when we added support for Capabilities
