### ISSUE TITLE
Support block-network by default for tests

### ISSUE THREAD

**Issue by gorset** [bazelbuild/bazel#3453]
We would like a way to enable network sandboxing by default. Currently this can only be enabled by adding the block-network tag to every test, which is error prone and cumbersome.

We have a bunch of tests that can crash when multiple tests accidentally binds to the same port. This is not the common case, but happens often enough to be annoying.

Adding block-network tag solves this on linux, but fails on macos with `java.net.SocketException: Operation not permitted`. See #2669 for more details for sandboxing problems with macos.

Support for a bazel startup flag would make it possible for us to run with block-network as default on linux machines and avoid any issues with macos.

Relevant code from the current master: https://github.com/bazelbuild/bazel/blob/7a38e2702f70003a9bbc6ef21e70ace74aebdad0/src/main/java/com/google/devtools/build/lib/sandbox/SandboxHelpers.java#L144-L152

**Comment by ittaiz** [comment]
@gorset have you considered the option of using a "remote-local" worker using docker? That should fix the macos problem.
It will still leave the problem of having to specify this tag on each test.
@philwo are there still substantial costs for using `block-network`? If not I think I'd also like to be able to turn it on by default

**Comment by philwo** [comment]
@ulfjack This might be a use case for our generic "--execution_info" flag, so that @gorset could just use something like --execution_info=TestAction+=block-network (exact flag syntax to be discussed) to make this the default for their setup.

@ittaiz I haven't checked the most recent Linux kernels whether they solved the performance problem or not - unfortunately there's nothing on the Bazel side that we can do.

For long-running tests it might not be too bad anyway - it was mostly an issue when using it as the default and then running a highly parallelized build consisting of many small actions.

I'd just give it a try.

**Comment by susinmotion** [comment]
It looks like this is fixed based on the comment above. Please reopen if you are still having issues here.
