### ISSUE TITLE
Document the "@..." label syntax

### ISSUE THREAD

**Issue by drigz** [bazelbuild/bazel#3550]
I can't find any documentation for the `@//` syntax for labels. I needed it to load a `.bzl` file in my workspace from a `project.BUILD` file for a non-Bazel external dependency, and found it in the end through guesswork. Additionally, I can't find definitive documentation for the more common `@external_repo//` syntax, although it is mentioned.

The [Labels](https://docs.bazel.build/versions/master/build-ref.html#labels) doc describes neither `@...` syntax. Is this intentional? I think it should either define both, or refer to their definitions.

[Depending on non-Bazel projects](https://docs.bazel.build/versions/master/external.html#depending-on-non-bazel-projects) is where I discovered the `@external_repo//` syntax, so it may be worth mentioning the `@//` syntax here.

**Comment by ensonic** [comment]
The docs for it are here:
https://docs.bazel.build/versions/master/skylark/repository_rules.html

The labels stuff needs to be updated when the feature leaves experimental.

**Comment by mmcloughlin** [comment]
I could not find `@//` documented anywhere. Apologies if I missed it, but I think I looked in reasonable places.

Thankfully I was able to find someone at my company who could explain it to me. I think it would be great to add a sentence explaining what this does, since the difference between `//a/b/c` and `@//a/b/c` is subtle and in some cases very important.

Perhaps https://docs.bazel.build/versions/master/build-ref.html#labels is the right place to clarify this? Maybe something like:

"Labels starting `@//` are references to the main repository, which will still work even from external repositories. Therefore `@//a/b/c` is subtly different from `//a/b/c` when referenced from an external repository; the former refers back to the main repository, while the latter looks for `//a/b/c` in the external repository itself. This is especially relevant when writing rules in the main repository that refer to targets in the main repository, and will be used from external repositories."
