### ISSUE TITLE
How to generate llvm ir binary(.bc) while compiling project with Bazel?

### ISSUE THREAD

**Issue by Becavalier** [bazelbuild/bazel#3566]
I am currently trying to compiling tensorflow c standalone library to llvm ir binary format with Bazel. But the Bazel dose not have the same parameters like clang, what should I do if I want to emit llvm binary format using Bazel?

**Comment by mhlopko** [comment]
That's possible, but not very simple. You would need to write your own CROSSTOOL that will use clang to produce the .bc files, and llvm-link for linking. File extensions are not yet customizable in the CROSSTOOL, so you will have to work with .o and .a. This is also a question better suited for Stack Overflow, feel free to continue there. 

There are some docs on writing custom crosstool, although the process is still hard and frustrating (so feel free to ask on StackOverflow and add 'bazel' tag, we monitor these questions and answer them regularly):
https://github.com/bazelbuild/bazel/wiki/About-the-CROSSTOOL
https://github.com/bazelbuild/bazel/wiki/Building-with-a-custom-toolchain
https://bazel.build/designs/2016/02/16/cpp-autoconf.html

I'll close this issue here as it's not really an issue.
