### ISSUE TITLE
Hermetic Python 3 test is missing

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3567]
### Description of the problem / feature request / question:

While Python 2 is getting tested in https://github.com/bazelbuild/bazel/blob/master/src/test/java/com/google/devtools/build/lib/bazel/rules/python/BazelPyRuntimeTest.java, there is no such test for Python 3.
Since Bazel is notorious for breaking Python 3 - please ensure that this gets tested.

**Comment by abergmeier-dsfishlabs** [comment]
Here is what this leads to: https://github.com/bazelbuild/bazel/issues/3568

**Comment by brandjon** [comment]
I'm not exactly clear on what test coverage this issue is requesting, or that it's specifically a Py 2/3 issue as opposed to just a py_runtime issue.

**Comment by brandjon** [comment]
Closing this because the problem's unclear.

For `py_runtime` analysis-time tests we now have [`PyRuntimeConfiguredTargetTest`](https://github.com/bazelbuild/bazel/blob/19185fcb8b2e5c690661dbf57f1aec72f148fd5a/src/test/java/com/google/devtools/build/lib/rules/python/PyRuntimeConfiguredTargetTest.java).

For end-to-end tests we have some attempt to launch both a Python 2 and Python 3 runtime, though the coverage could stand to be improved (#6868). This will wait until at least after the toolchain work is done.
