### ISSUE TITLE
http_archive, git_repository repetition when nesting WORKSPACE

### ISSUE THREAD

**Issue by ajbouh** [bazelbuild/bazel#3597]
I'm trying to build a project that depends on TensorFlow. I've modeled my BUILD files on those in https://github.com/tensorflow/serving.

Why is the following block required in https://github.com/tensorflow/serving/blob/master/WORKSPACE?
```
# TensorFlow depends on "io_bazel_rules_closure" so we need this here.
# Needs to be kept in sync with the same target in TensorFlow's WORKSPACE file.
http_archive(
    name = "io_bazel_rules_closure",
    sha256 = "4be8a887f6f38f883236e77bb25c2da10d506f2bf1a8e5d785c0f35574c74ca4",
    strip_prefix = "rules_closure-aac19edc557aec9b603cd7ffe359401264ceff0d",
    urls = [
        "http://mirror.bazel.build/github.com/bazelbuild/rules_closure/archive/aac19edc557aec9b603cd7ffe359401264ceff0d.tar.gz",  # 2017-05-10
        "https://github.com/bazelbuild/rules_closure/archive/aac19edc557aec9b603cd7ffe359401264ceff0d.tar.gz",
    ],
)
```

When I extended my project to depend on https://github.com/ajbouh/go-ipfs,
I ended up having to duplicate 100+ of these types of external declarations in my top-level WORKSPACE for everything in https://github.com/ajbouh/go-ipfs/blob/bazel/WORKSPACE.

I'm hoping that I've missed something obvious and there's a much simpler way to make this work. Keeping these lines in sync across multiple git repositories is rough!

**Comment by damienmg** [comment]
Normally the correct way is to declare a skylark macros that create those dependency so you can just recall that skylark macro. It can also use native.existing_rules to not recreate them when there where already created.

We have a design for recursive inclusion but it is not trivial to do right so it takes time.

(side-note: since this is a support question more than a FR or a bug report, it would have been at a better place on Stack overflow where the audience is bigger).

**Comment by ajbouh** [comment]
Got it. Are there any examples of how to do this properly?

**Comment by damienmg** [comment]
Well tf_serving itself is doing it for tf dependencies: https://github.com/tensorflow/serving/blob/master/WORKSPACE#L21 I don't know why they are not doing it for closure itself, maybe because they want a different version than the one provided by tensorflow.
