### ISSUE TITLE
Document how to run a shell command from a rule

### ISSUE THREAD

**Issue by kevinburke** [bazelbuild/bazel#3607]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

I'd like to run a shell command from a rule, e.g. provide a "mocha_test" rule that calls mocha with some arguments. The documentation for rule doesn't really explain how to do this.

### Environment info
* Operating System:

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?

Searching on Google generally leads me to the `sh_binary` docs but I'm pretty sure you can't just call `sh_binary` from inside of a rule.

Reading rules_X repos and it's difficult to determine the mapping between rules and actual shell commands; there's a lot of abstraction and it's not clear where exactly the "run this shell" declaration occurs.

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by c-parsons** [comment]
Sorry that this issue is so stale. Responding to it in case others happen upon this issue in the future:

I would suggest looking at our [Rules documentation](https://docs.bazel.build/versions/master/skylark/rules.html) for details on how to get started writing rules.

Additionally, we have [several examples for rule implementations](https://github.com/bazelbuild/examples/tree/master/rules), if learning by example is more your thing. You might particularly be interested in the [shell_command](https://github.com/bazelbuild/examples/tree/master/rules/shell_command) example.

Please feel free to reopen this issue if you have any specific questions, or file a new issue!
Thanks!

**Comment by c-parsons** [comment]
Here are some resources on receiving Bazel support:
https://bazel.build/help#community

I've also responded to the stackoverflow link you've provided.

**Comment by netskink** [comment]
Yes, I saw that.  Many thanks.  I am still trying to get it to resolve.  I'll take a look at your link.  Many thanks again!
