### ISSUE TITLE
Introduce attr.host_executable

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [bazelbuild/bazel#3612]
### Description of the problem / feature request / question:

In the past we wrote lines like

    "_foo": attr.label(default = Label("//foo:exec"), executable = True, cfg = "host"),

everywhere. To make that easier we introduced a macro `host_executable`:

    "_foo": host_executable("//foo:exec"),

As a middle ground, I think it would be beneficial to expose a shortcut `attr.host_executable`:

    "_foo": attr.host_executable("//foo:exec"),

**Comment by brandjon** [comment]
This is no longer applicable as stated, because we've deprecated the `host` configuration in favor of the `exec` configuration. But I suppose you could make the same request for an `attr.exec_executable` (though the naming is a bit alliterative).

Still, there's some value in being orthogonal and explicit for the sake of consistency (i.e., repeating `executable = True` and not inferring it from the attribute type). There's also a very decent workaround. So I'll close this request.
