### ISSUE TITLE
docker image is 292 years old if build from bazel

### ISSUE THREAD

**Issue by gyliu513** [bazelbuild/bazel#3625]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

Check out more for https://groups.google.com/forum/#!topic/istio-dev/nuv6UaBFGDk

Some istio docker images are 292 years old and the reason is that bazel is not aware of git commit.

```
root@pc004:~# docker images | grep istio
istio/examples-bookinfo-reviews-v2                latest              a2e4ca83561b        4 months ago        445 MB
istio/examples-bookinfo-productpage-v1            latest              a5dc661788bf        4 months ago        691 MB
istio/examples-bookinfo-ratings-v1                latest              5ffcd281499b        6 months ago        653 MB
istio/pilot                                       0.1.6               e0c24bd68c04        292 years ago       144 MB
istio/proxy_debug                                 0.1                 5623de9317ff        292 years ago       825 MB
istio/proxy_debug                                 0.1.6               5623de9317ff        292 years ago       825 MB
istio/istio-ca                                    0.1.6               c25b02aba82d        292 years ago       154 MB
istio/init                                        0.1                 0cbd83e9df59        292 years ago       119 MB
```

_If asking a question or requesting a feature, also tell us about the underlying problem you're trying to solve._

### Environment info
* Operating System:

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by mattmoor** [comment]
FWIW, `bazelbuild/rules_docker` is a better forum for this.

> Some istio docker images are 292 years old and the reason is that bazel is not aware of git commit

This isn't entirely accurate.  In general, Bazel uses a constant timestamp to get reproducible builds.  Most files coming out of a Bazel build (e.g. within archive files) will have the Unix epoch.  Git commit is a red herring; I can (and very often do) have two builds at different git commits that produce the exact-same image.

**So why 292 years old?**

You'd have to ask Docker.  We actually do not use the Unix epoch in `docker_build`, we omit creation time altogether.  Docker should probably be reporting the age of the image as unknown.

This is ultimately a trade-off between reproducibility / verifiability and the optics of how the image appears in `docker images`.  Within the world of Bazel dogma, this isn't even a choice really.  Reproducibility improves everything from verifiability to distributed cache hit rates to image push/pull times.


I think the ideal solution would be to upstream a fix for the Docker client for when this field is omitted from the image config, but it has never been a priority because this has always been regarded as a cosmetic issue (please correct me if I'm wrong, or I've missed something).

**Comment by ldemailly** [comment]
The corner case that 2 git commit can sometime yield the same image shouldn't be the driving function here. the driving function is (should be/imo) usability/meaningfulness of the result:

if a CI system or releng decides to (re)create artefacts for a given set of source, they use a source control system, why shouldn't the date of the last change in said source control system not the "right" (default) date to use for images ? or at minimum allow the user to specify the date (which they would probably get from the git commit log)
