### ISSUE TITLE
Cannot build tensorflow with bazel command with gcc-5.4.0 on centos6

### ISSUE THREAD

**Issue by cobbwho** [bazelbuild/bazel#3667]
### Description of the problem / feature request / question:
Hi , I can only install tensorflow by compiling the source code without the Internet , but I meet a fatal problem with bazel command . When I use the command

>  bazel build -c opt //tensorflow/tools/pip_package:build_pip_package ,

I got an error and warnings as follow:

> /path/.cache/bazel/_bazel/67d89f1fb2d91f3afbe5713ca23b114/external/boringssl/BUILD:116:1:C++
>  compilation of rule '@boringssl//:crypto' failed : gcc failed : error executing command /path/gcc-5.4.0/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/path/gcc-5.4.0/bin -B/usr/bin -Wunused-but-set-parameter ... (remaining 49 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
> external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S: Assembler messages:
> external/boringssl/linux-x86_64/crypto/chacha/chacha-x86_64.S:1002: Error: no such instruction: vbroadcasti128 .Lsigma(%rip),%ymm11'

and the I add the option` --verbose_failures  `, it show some specific description:

> /path/.cache/bazel/_bazel/67d89f1fb2d91f3afbe5713ca23b114/external/boringssl/BUILD:116:1:C++
>  compilation of rule '@boringssl//:crypto' failed : gcc failed : error executing command(cd /path/.cache/bazel/_bazel/67d896f1fb2d91f3afbe5713ca23b114/execroot/tensorflow && \
>   exec env - \ +All my system environment variables

At first , I notice the keywords  "Assembler message", I thought that is because I lack of assembler. So, I setup binutils , but it isn't work for me .
Then, I try add some options like,because some keywords like `vpxor` `vpaddd` `vpsrld` belong to Assembly instruction set.

> bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma  //tensorflow/tools/pip_package:build_pip_package

And the error message is same. Then I really find a solution.
[Cannot make tensorflow to use a local gcc installation? #649 ](https://github.com/bazelbuild/bazel/issues/649)
unfortunately, it's not work for me .As the author said, I add the code:

>  linker_flag: "-L/home/user/clibs/lib64"
>    linker_flag: "-lstdc++"
>    linker_flag: "-Wl,-rpath,/home/user/clibs/lib64"

btw, when I add the command below to compile.sh, it says the file is readonly.
> export LDFLAGS="-Wl,-rpath,/path/to/your/lib64"

Finally, I spent too long on this issue. I don't kown what's the problem? Can anyone help? I'll appreciate it. Thanks!
### Environment info
* Operating System: win10&centos6

* Bazel version (output of `bazel info release`):bazel-0.4.5

* GCC version: gcc-5.4.0

* Python version: Python-2.7.0

I have already installed gcc、python & bazel ,and they all works.This problem is just happen at tensorflow build with bazel.

**Comment by philwo** [comment]
You need a newer version of binutils (GCC uses the "as" assembler from binutils under the hood). From what I found on the internet by searching for "Error: no such instruction: vbroadcasti128" it seems like you need at least binutils 2.22. (cf. https://github.com/briansmith/ring/issues/551)

The reason why only TensorFlow fails is that they seem to use AVX instructions in their assembly code, which requires the newer version of binutils.

Closing this as it's not a Bazel bug. If you need help on how to configure your build to use the newer binutils, I'd suggest to ask either the TensorFlow people or on StackOverflow and tag it with "bazel" so that our community supporters will find it and can try to get you an answer. :)
