### ISSUE TITLE
BuildEventService does not allow for race free reading of Test Logs and other files.

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#3689]
I want to be able to implement a BuildEventService server and read the test log files without dealing with races. This is not currently possible without changing the workflow of the client (https://stackoverflow.com/questions/46044506/bazel-overwriting-test-logs-and-buildeventprotocol-via-buildeventservice) beyond `.bazelrc` changes or slowing it down with `--nobes_best_effort`.

Likely this will require storing the test logs in a per invocation location. This then brings in the issue of expiration of these files as otherwise they will grow without bound.

My end goal is to be able to build a server which can show test logs and build results in a non CLI environment.

**Comment by buchgr** [comment]
Thanks for raising the issue!

We properly don't want to store log files in an invocation specific location. This would also only help if the BES service was running on localhost or similar (network drive etc.).

I argue that what we actually need to think about is some mechanism to upload log files to a remote location. Maybe that could be as simple as embedding the log file content in the build event?

@endobson In the meantime you could have your own little process to do the uploading?

cc: @ulfjack @aehlig

**Comment by endobson** [comment]
Short term I will probably risk the race condition/not read the test logs and only show the pass/fail results.

Uploading to a remote location was the likely longer term solution that I was imagining. That still has the issue of expiry, but it is now the remote side's issue.

**Comment by ulfjack** [comment]
You'd run the server on the same machine as the build? Otherwise the server can't access the logs, since they're on the machine where the build is run. We actually support uploading the logs from Bazel with --remote_cache; note that the remote cache doesn't actually have to support caching, and it also doesn't require uploading all files - you can implement a 'fake' remote cache that only gets log files uploaded, and always returns cache misses (or configure Bazel not to check the cache in the first place).

**Comment by endobson** [comment]
Yep I currently run the server on the same machine (my laptop). I just
started working on it over the long weekend. I eventually plan on using a
different machine, but that is not a priority at the moment.

The remote cache looks like exactly what I want. I'll try it out and report
back (probably not till the weekend).

**Comment by buchgr** [comment]
The remote cache works (everyone should use one!), but the problem is that you can't only accept test.log files. Bazel uploads generic blobs referred to by their hash to the remote cache without associating a file name to it. The BEP will then also contain references to these blobs instead of filenames. You can probably come up with some strategy on deleting files that are not referenced in the BEP, but at this point you might just want to have a real remote cache because you are already paying the cost (upload) without the benefit of it (download).

**Comment by buchgr** [comment]
@endobson 
Shamless Plug: I recently built a remote cache for Bazel and also plan on adding support for the BEP with nice web dashboard. It's not on the top of my priorities though. Next up are monitoring/logging and authentication. If you are interested we might be able to team up.

**Comment by endobson** [comment]
Thanks for the offer, but I'm not trying to build a production dashboard/server as much as explore.  This is giving me a good excuse to build a gRPC server that I will actually use more than just a toy demo.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
