### ISSUE TITLE
--test_tag_filters do not allow to select tests that contains flag A and B

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#3705]
In issue #3704, we were executing too many tests because of confusion:

`-a,-b` is going to look for all tests that have neither `a` or `b` tag whereas `a,b` will match all tests that have either `a` or `b` tag. There is no way to select all tests that matches both `a` and `b`.

The [documentation](https://docs.bazel.build/versions/master/user-manual.html#flag--test_tag_filters) talks about positive flag as "required tags" which leads to believe that we apply a AND whereas it is a OR. The preceding '+' is also confusing... If the '+' sign is not used anywhere, maybe we should make it a way to say always required?

**Comment by sladyn98** [comment]
@jin @damienmg I guess this is a simple enough issue to begin with, any sort of pointers to begin
CC : @aiuto

**Comment by aiuto** [comment]
You would being the same way as any new feature.
- propose the design for exactly how the semantics of test_tag_filters would change
- get some feedback and iterate until people agree it makes sense
- come up with a PR that implements it (with tests)

It sounds like the simple plan is to actually make + mean required, so +a,+b means both a and b must be present.

**Comment by ehkloaj** [comment]
Here is a pull request that solves this, #11733.

This behavior is already supported by bazel when using the rule [test_suite](https://docs.bazel.build/versions/master/be/general.html#test_suite) which means that it was just a boolean that needed to be flipped. 

We decided to not use the syntax where +a,+b means that both _a_ and _b_ must be present, as suggested by @aiuto, since it would conflict with the way users are used to how --test_tag_filters is working. Also, there is not really any point in specifying tags both with and without + since the once without + wouldn't have any affect. For example a,+b would mean that only _b_ must be present and it does not matter if _a_ is present or not.  

Instead we decided to use a syntax where you add _&&_ as an extra tag since this allowed for an easy implementation.

**Example of usage**:
`bazel test //... --test_tag_filters="&&,tag1,tag2"`
This will only run the tests that have tag1 and tag2.

What do you think about this solution? Do you have a suggestion for a more elegant syntax?

**Comment by alandonovan** [comment]
Please let's not add yet more alien notations to Blaze. Can we reuse Starlark, restricted to the following expressions:

  expr = IDENT   |   '(' expr ')'   |   expr AND expr   |   expr OR expr   |  NOT expr

Tokens and precedence are as defined by the spec. We can detect the old syntax by looking for a comma and continue to support it for a grace period.

This way users don't have to learn a new thing.

**Comment by gregestren** [comment]
That's an interesting proposal. @alandonovan is it advised / straightforward to inject actual Starlark evaluation to accomplish this? Or just model that specific expression natively?

@ehkloaj what do you think of this suggestion? I suspect, depending on what @alandonovan says, this wouldn't be substantially more complicated than your current PR.

**Comment by alandonovan** [comment]
You could use the evaluator, but it's overkill. Just use the parser, then write a function to visit the expression tree, computing values of tags at the leaves (identifiers) and computing and/or/not at the non-leaves. It shouldn't be more than 20 lines of code.

**Comment by ehkloaj** [comment]
I think this a good solution. 

How do we move on with this?

@alandonovan where can I find the parser you are referring to?

**Comment by alandonovan** [comment]
The parser is syntax.Expression.parse. Then you'll want a recursive function something like this:
```
boolean evalBooleanFormula(Expression e) {
   switch e.kind() {
        case IDENT:                                                                                                                                                           
          lookup tag e in environment; fail if not found.
        case BINOP:                                                                                                                                                       
          reject op unless AND or OR.
          return evalBooleanFormula(e.X) op evalBooleanFormula(e.Y)
        case UNOP:                                                                                                                                                       
          reject op unless NOT.
          return !evalBooleanFormula(e.X)
      default: 
          reject
      }
}
```

**Comment by ehkloaj** [comment]
I have created a PR that solves this based on the suggestions of @alandonovan, #11900 . Take a look at it and if it looks good we might be able to close this issue.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen (or ping me to reopen) if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
