### ISSUE TITLE
CI, bazel-tests: CI machines don't have latest Android SDK

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#3754]
I see this error in the bazel-tests log:

```
[node=ubuntu_16.04-x86_64] ERROR: /home/ci/workspace/bazel-tests-node=ubuntu_16.04-x86_64/src/test/java/com/google/devtools/build/android/desugar/BUILD:19:1: no such target '@androidsdk//:platforms/android-25/android.jar': target 'platforms/android-25/android.jar' not declared in package '' (did you mean 'platforms/android-24/android.jar'?) defined by /home/ci/.cache/bazel/_bazel_ci/f576cbcb4b5fe364bb084077db8fda2f/external/androidsdk/BUILD.bazel and referenced by '//src/test/java/com/google/devtools/build/android/desugar:android_jar_for_testing'.
```

http://ci.bazel.io/view/Dashboard/job/bazel-tests/1033/consoleFull

**Comment by laszlocsomor** [comment]
P0 per our sheriff policy, becasue it's making bazel-tests red

**Comment by laszlocsomor** [comment]
I'm trying to repro this on one of the Mac CI machines.

**Comment by laszlocsomor** [comment]
I'm trying to repro this on one of the Mac CI machines.

**Comment by laszlocsomor** [comment]
Thanks Yun! https://github.com/bazelbuild/bazel/issues/3755 has more info than this bug.

**Comment by aj-michael** [comment]
Sorry about this, the culprit is d60e0d02eb56e27f98086d764c6d9f88898d920d. I think the easiest thing to do is to change the test to expect android-24. It doesn't depend on which version is installed, however it had to rely on one of them because it has a dependency on the android.jar target.

Medium term, I could update this line to install all the platforms:
https://github.com/bazelbuild/continuous-integration/blob/master/gce/linux-android.sh#L41

However, I don't have a solution for what will happen when Android releases P that doesn't involve needing to reimage our VMs. Maybe that's not so bad, seeing as platform releases are only once a year.

**Comment by laszlocsomor** [comment]
Thanks Adam!

Could you please fix the test to expect android-24 for now so we can get bazel-tests to pass again?

**Comment by vladmos** [comment]
The culprit was submitted after the baseline for the upcoming 0.6.0 (which is 87cc92e5df35d02a7c9bc50b229c513563dc1689) so technically it's not a release blocker (unless we decide to cut a release again).

**Comment by laszlocsomor** [comment]
@vladmos : OK, removing tag. Thanks!

**Comment by aj-michael** [comment]
For posterity, I'll note that the culprit CL was merely open-sourcing some tests, so even if we recut the release, this is not a blocker.

**Comment by aj-michael** [comment]
Mailed an internal change to switch to using android-24, and also created https://bazel-review.googlesource.com/#/c/continuous-integration/+/16850/ to add android-25 and android-26 to the linux and mac bazel CI.

**Comment by laszlocsomor** [comment]
https://github.com/bazelbuild/bazel/commit/06d1988534c17a7fb69afe5fc1f9725efe246b37 resolved this issue. Thanks Adam!
