### ISSUE TITLE
Please add context action for creating archives (tar, zip, maybe jar?)

### ISSUE THREAD

**Issue by jmillikin** [bazelbuild/bazel#3768]
Creating archives is a common task of Skylark rules, but today it's difficult to do correctly. Bazel itself packages a `pkg_tar` rule that (1) depends on Python and (2) generates non-deterministic output (https://github.com/bazelbuild/bazel/issues/1844). This has downstream effects on every rule built on `pkg_tar` (see `pkg_deb` bug https://github.com/bazelbuild/bazel/issues/3723), and complicates life for rule authors (see timestamp hoop-jumping in [rules_docker](https://github.com/bazelbuild/rules_docker)).

Bazel already depends on [Apache Commons Compress](https://commons.apache.org/proper/commons-compress/examples.html), which supports creating various types of archive. It should be straightforward to wrap their tar/zip logic with a repository action. Also useful is `.ar` for pkg_deb, and `.xz` because the XZ utilities are not installed by default on Mac OS.

Example of use:

```python
def _some_rule(ctx):
  entry_a = ctx.actions.declare_archive_entry(
    input = ctx.file.some_file,
  )
  entry_b = ctx.actions.declare_archive_entry(
    input = ctx.file.some_other_file,
  )
  archive = ctx.actions.declare_file("big_blob_of_bytes.tar.gz")
  ctx.actions.write_archive(
    output = archive,
    inputs = [entry_a, entry_b],
  )
```

The `declare_archive_entry` method would have optional parameters to override the path, permissions, metadata, and so on.

**Comment by mattmoor** [comment]
+1 I think the portability argument alone is a strong one (OSX is a walk in the park next to Windows).  The `xzcat` dependency in `pkg_tar` is a good example, I have places I'm relying on `g[un]zip` in `rules_docker` (I could fallback on a Python `gzip` utility, like we do for `sha256`, but Python's `gzip` performance is known to be terrible and build performance would suffer).

I think at a minimum having something like OSS skylib to create a canonical repo for these kinds of common actions (written in portable ways) would be very useful, regardless of whether they are built into Bazel itself (frankly, I like the idea of decoupling so that fixes can be made independent of Bazel's release cycle).

@dslomov @damienmg FYI

**Comment by ittaiz** [comment]
+1 but please note there are at least two other issues which are related or
even duplicates. AFK so can't link them now.

**Comment by rlguarino** [comment]
I think a separate repo would be an interesting idea but it might make more sense to just perform the action in Java is it's already portable and the necessary dependency is already there.

Wouldn't it be a little strange to have a dep cycle?  The `bazelbuild/bazel` implementation of `pkg_tar` relying on the OSS skylark lib, which depends back on `bazelbuild/bazel` for it's run-time? I get that this isn't an actual hard dependency cycle but it would be a little awkward to reason about and slightly annoying to configure the first time you setup a slylark lib which depends on the OSS lib. It also introduces another dependency version pair you need to worry about getting right. Instead of `this rule work with Bazel  version > x` you would also need to include the version of  the "commons" repo you support. Again, this isn't a blocker but it's a little more awkward UX for end users.

**Comment by aiuto** [comment]
I don't know if having a built-in action is going to win. If we have remote execution, the action is running on the remote machine, so we would have to provide a binary portable to the execution environment. The blaze binary is not running there.

What I do support is adding a set of rules to rules_pkg that make defining complex package structures easier. At the bottom they can call tar or zip or a python equivalent for now. Over time we can replace these with faster (and more portable) compression tools.  For reference, to any ex-Googlers, what I would like to do is export the pkgfilegroup() rule, but with a cleaned up design.

**Comment by jmillikin** [comment]
Since Bazel's built-in rules for C++/Java/etc are being moved out to their own rule sets, I agree that building this functionality as a Starlark rule instead of `ctx.actions` makes sense.

I'll close this since https://github.com/bazelbuild/bazel/issues/8857 covers it.
