### ISSUE TITLE
Replace transitive_*_jars in java_common.create_provider with deps

### ISSUE THREAD

**Issue by iirina** [bazelbuild/bazel#3769]
The current `transitive_*_jars` arguments in `java_common.create_provider` are hard to understand and present some shortcomings. For example, you cannot create a provider with transitive source jars or other transitive information that `JavaInfo` encapsulates (and might not even be exposed).

The current (**old**) API:

```python
java_common.create_provider(
  actions,
  use_ijar = ...,
  compile_jars = [...],
  runtime_jars = [...],
  source_jars = [...],
  transitive_compile_time_jars = [...], 
  transitive_runtime_jars = [...],
  java_toolchain = ....
)
```

**should be replaced** by this:

```python
java_common.create_provider(
  actions,
  use_ijar = ...,
  compile_jars = [...],
  runtime_jars = [...],
  source_jars = [...],
  deps = [...], # this should be a list/set of JavaInfo, to encapsulate the transitive information
  java_toolchain = ....
)
```

**Comment by iirina** [comment]
cc: @ittaiz

**Comment by ittaiz** [comment]
Great, thanks.
Just to make sure- this will respect neverlink semantics, right?

**Comment by ittaiz** [comment]
Friendly ping

**Comment by ittaiz** [comment]
@iirina Stumbled on to a problem and I'm not sure if it should be a new issue or an expansion of this one.
The `use_ijar=True` in `java_common.create_provider` is currently unusable if one needs `exports`.
Tried a few alternatives and all of them failed:
1.  `compile_time_jars = outputs.full_jars,` #error since provider doesn't propagate exports
2. `compile_time_jars = outputs.full_jars + exports_jars.compile_jars.to_list(),`  #error since provider ijars existing ijars (e.g.g `foo-ijar-ijar.jar`)
3.  `compile_time_jars = outputs.full_jars + exports_jars.full_compile_jars.to_list(),`# If passing full compile jars of the exports it fails since we generate outputs for a different target
#Output artifact 'external/com_twitter__scalding_date/jar/scalding-date_2.11-0.17.0-ijar.jar' not under package directory 'test' for target '//test:jar_export'.
# ERROR: Analysis of target '//test:jar_export' failed; build aborted: Analysis of target '//test:jar_export' failed; build aborted.

The reason I think this is related to this issue is because I think the real problem is the level of abstraction the current provider allows. Ideally I think it should support the API you mentioned above but also include `runtime_deps`, `exports` and `neverlink`.

WDYT?

You can see my attempt of using this feature in the following rules_scala [branch](https://github.com/bazelbuild/rules_scala/tree/use_build_ijar_feature)

**Comment by iirina** [comment]
@dbabkin is currently implementing this.

**Comment by ittaiz** [comment]
Exciting! Thanks!

**Comment by ittaiz** [comment]
Hi,
Any idea if this will hit the 0.10.0 release?

**Comment by dbabkin** [comment]
Hi, 
Bazel contributor here. :) Terribly sorry for delay in reply. 

This task is in the progress right now. 
First, very limited part of new API is about to be finished. Commit will be pushed today or tomorrow.
I'm not sure about release 0.10.0. Please follow the status of release 0.10 cut on this ticket:
https://github.com/bazelbuild/bazel/issues/3958

New API supports creating JavaInfo with JavaCompilationArgsProvider only. 
The next sub-task in scope of this story is to implement the list of all others providers.

**Comment by ittaiz** [comment]
Hi,
Thanks for the update!
This isn't exposed to skylark right? AFAIR JavaCompilationArgsProvider
isn't exposed to skylark

**Comment by iirina** [comment]
No, it's not. It's just an implementation detail, meaning more work will be needed to make the new API 100% reliable.

I cannot tell right now if this will make the release, since it seems difficult to even cut an RC right now.

**Comment by dbabkin** [comment]
Hi Ittai,

We do not expose JavaCompilationArgsProvider itself. 
If you take a look at JavaInfo class [1], it has 4 methods based on JavaCompilationArgsProvider
 getCompileTimeJars()
 getFullCompileTimeJars()
 getTransitiveDeps()
 getTransitiveRuntimeDeps()
This methods are exported already. And during creating JavaInfo using new API, JavaCompilationArgsProvider is populated now. So you can use this four methods now. 


To create JavaInfo, you need to use constructor [2]. Please refer our tests for example [3]

```
javaInfo = JavaInfo(
    output_jar = ctx.file.output_jar,
    use_ijar = False,
    runtime_deps = dp
)
javaInfo.transitive_runtime_deps
```

Others methods from JavaInfo returns empty result now. To fix that I need to implement other providers. This is my priority at the moment.

[1] https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/java/JavaInfo.java;l=335

[2] https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/java/JavaInfo.java;l=113

[3] https://source.bazel.build/bazel/+/master:src/test/java/com/google/devtools/build/lib/rules/java/JavaSkylarkApiTest.java;l=1593

**Comment by dbabkin** [comment]
Hi, 
Small update from my side: 
JavaSourceJarsProvider had been created inside JavaInfo

**Comment by dbabkin** [comment]
Hi,
Update from my side:
Recently added JavaRuleOutputJarsProvider, JavaExportsProvider , JavaSourceJarsProvider.
Added support for 'exports' parameter. 
I think we are pretty finish with functionality except minor things:
1) Input parameter 'sources' is ignored at the moment. 
2) merge function for JavaInfo doesn't merge all providers.

**Comment by johnynek** [comment]
@dbabkin Thanks a lot! It sounds like there are a lot more moving pieces now. Will the documentation be updated when this ships?

**Comment by dbabkin** [comment]
Hi Oscar,

I'll be back to you with the answer to your question in few days.

**Comment by dbabkin** [comment]
changes pushed.

**Comment by ittaiz** [comment]
Thanks!
Any chance for a link to the commit?

**Comment by dbabkin** [comment]
https://github.com/bazelbuild/bazel/commit/bb64d2f299e39788f7d1e80fb1e3c92536e498a2

https://github.com/bazelbuild/bazel/commit/cf79305f79f627ae20c4da5e832a633fc3994d5a

**Comment by bpatters** [comment]
Looks like it's been released. Any ETA when this will be coming?
