### ISSUE TITLE
Bazel doesn't work with Java 9

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel#3789]
Java 9 was released today. When running bazel, the following output is given on OS X:

```
bazel test //...:all
Problem with java installation: couldn't find/access rt.jar in /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
```

I'd expect Bazel to work with the latest released official JRE, even if it's not yet able to take advantage of new Java 9 features yet.

**Comment by davido** [comment]
This was already reported: [1]. Also see discussion here: [2].

* [1] #3410
* [2] https://groups.google.com/d/topic/bazel-discuss/YR7e2wDDjzg/discussion

**Comment by shs96c** [comment]
Then I'll close this issue :) Thanks @davido!

**Comment by kamalmarhubi** [comment]
As mentioned in https://github.com/bazelbuild/bazel/issues/3410#issuecomment-347915814, I think the issue of running bazel under jvm 9 should be broken out from the issue of compiling with jdk 9. This issue seems focused on running, so I suggest reopening it and perhaps making the title more specific.
