### ISSUE TITLE
Should Bazel automatically update a maven_jar if the version is SNAPSHOT?

### ISSUE THREAD

**Issue by GinFungYJF** [bazelbuild/bazel#3824]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:
We have 20+ projects which are built with bazel. A project will have some dependencies on some other projects, and it will download the artifact that has been described as a maven_jar:
```
maven_jar(
         name = "XXXX",
         artifact = "someGroupId:someArtifactId:1.0.0-SNAPSHOT",
         sha1 = "XXXXXX",
)
```
The trouble is, the artifacts with SNAPSHOT version are updated frequently. So we have to frequently update the sha1 of the maven_jar, which would take quite a bit of work. AFAIK, if I use maven to build and set the version of a dependency to SNAPSHOT, maven will alway automatically update the artifact if the remote artifact is newer through comparing the timestamps. So, if the artifact's version is SNAPSHOT and I omit the sha1 in the maven_jar, I would like bazel can automatically update the artifact through comparing the timestamps of the downloaded one and the remote one.
Is this reasonable? Or is there a reasonable solution that we don't have to frequently update the sha1?

**Comment by ittaiz** [comment]
@GinFungYJF have you tried changing the sha1 already? Asking since I seem to remember this will cause an error from Bazel saying there's a mismatch between the sha1 you specified and the one found on disk.
Additionally I think the feature you're suggesting is very dangerous and IMHO shouldn't be in Bazel.
The reason is that this causes your bazel build to be non deterministic and non-reproducible. It means you can't rely on your cache and moves Bazel a lot closer to maven.
When we had this problem what we were working on internally was to depend on these jars with their timestamps and have an automatic service to commit an update to the WORKSPACE file with the version/timestamp. This keeps the same agility of getting frequent updates from maven but keeps your build hermetic and reproducible.

**Comment by GinFungYJF** [comment]
Ok, got it. Thanks for the suggestion! We will try to make an automatic service.
