### ISSUE TITLE
Macros no longer allowed in prelude_bazel?

### ISSUE THREAD

**Issue by chaoren** [bazelbuild/bazel#3835]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

1. Define a macro in prelude_bazel:
```
$ bazel info
ERROR: tools/build_rules/prelude_bazel:1:1: syntax error at 'def': This is not supported in BUILD files. Move the block to a .bzl file and load it
```
It complains that `def` is not support in BUILD files, but prelude_bazel is not a BUILD file. 

2. Move the macro definition to //tools/build_rules:rules.bzl and load it in prelude_bazel:
```
$ bazel info
ERROR: error loading package '@bazel_tools//tools/jdk': Extension file not found. Unable to load file '@bazel_tools//tools/jdk:rules.bzl': file doesn't exist or isn't a file
```
It seems that prelude_bazel loads the bzl file relative whatever (potentially external) package is processing the prelude instead of `//tools/build_rules`.
It is also illegal to `bind()` bzl files to `//external`.

The only solution is to place the bzl file containing the macros in a nested workspace, add it to the WORKSPACE file as a `local_repository()`, then load it in prelude_bazel through the nested external 
workspace.

This is extremely convoluted to just have macros in the prelude.

### Environment info
* Operating System: Debian

* Bazel version (output of `bazel info release`): release 0.6.0

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by laurentlb** [comment]
Prelude file is inserted at the top of BUILD files. It should have the same restrictions as BUILD files.

Maybe you should do with the prelude file?

**Comment by chaoren** [comment]
> Prelude file is inserted at the top of BUILD files. It should have the same restrictions as BUILD files.

In a regular BUILD file, I would put my macros in a bzl file next to the BUILD file, then load them. Pretty simple. Can't do that in prelude now. There's no way to load a bzl file except from an external workspace. Because the prelude will run for things like `@bazel_tools//tools/jdk`.

Perhaps prelude shouldn't be inserted in BUILD files from other workspaces? Then an loading a local bzl file with an absolute label would work.

**Comment by seanmcl** [comment]
This is particularly hard on CentOS users, since we install through your yum repo and 0.5.2 is no longer published there.

**Comment by varming** [comment]
Any news on this issue?

**Comment by chaoren** [comment]
So there will be no way to redefine a rule/macro without having to update every single BUILD file with load statements?

**Comment by ittaiz** [comment]
Wow, this is a feature we’re using very strongly. Why remove it?

**Comment by laurentlb** [comment]
I didn't want to scare you; there's no decision.

To summarize the current state:

* The prelude file is not documented (I don't think there's any reference on the website).
* It's not well tested or designed. For example, I don't even know if it works with external repositories.
* It has performance problems: when you modify the prelude (or any of its dependencies), every BUILD file has to be reloaded. For this reason, we stop using it at Google.

But since some people use it, we can keep it in Bazel for now (it's not difficult to keep it working).

In the future, we may provide better tooling for maintaining load statements (insert / remove them automatically).

**Comment by ittaiz** [comment]
👍🏽
Re external repositories- it works. There were a few bugs with it but they
were resolved.

**Comment by ittaiz** [comment]
+1 if it wasn’t clear

**Comment by laurentlb** [comment]
Thanks for the feedback.

> Say if the prelude file was restricted to only containing load statements.

This is a good idea. I'd like to make this change: restrict the prelude to contain only `load` statements. I expect this won't make a big difference for the users, and it will help us in the future.

**Comment by laurentlb** [comment]
With https://github.com/bazelbuild/bazel/commit/2a73a730da2a1be79ecdc1ee9bce9249111c8c1b, the prelude is handled in a saner way (cc @brandjon):

* the prelude is evaluated once and then cached (instead of being append in each BUILD file)
* you can no longer call macros/rules from the prelude (but no one was doing that, right?), just load them
* error messages are better, with a proper stack trace

**Comment by brandjon** [comment]
This bug appears to no longer repro now that we're using the new prelude semantics.

It is still recommended to use the prelude sparingly if at all. Injecting custom symbols into BUILD files on a per-repo basis can make builds less readable.
