### ISSUE TITLE
Add an option for generating WORKSPACE files from artifacts

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#385]
Something like `generate_workspace --artifact=foo:bar:1.2`.

**Comment by pgr0ss** [comment]
FWIW, here's how we've been doing it: https://github.com/pgr0ss/bazel-deps

**Comment by damienmg** [comment]
See http://bazel.io/docs/external.html. We have the `bazel run
src/main/java/com/google/devtools/build/workspace:generate_workspace` that
does just that :)

**Comment by pgr0ss** [comment]
Our script is based on yours, but with a few advantages for us:
* It already accepts artifact ids instead of local paths
* It formats the WORKSPACE entries as a single line, which makes sorting and uniquing them much easier.
* It allows you to exclude common dependencies. For example, if you're using `dropwizard-core`, `dropwizard-client`, `dropwizard-testing`, etc., you don't want to duplicate all of the transitive dependencies for each one. You just need the additional dependencies on top of core.

I fully expect that your version will keep improving and surpass ours at some point, and then we'll switch.

**Comment by damienmg** [comment]
Actually, the third case is already handled if you put all your current workspace as input too, the first one is the subject of this bug, and we use the BUILD file convention for generating the workspace artifacts. Once we have load statements in the WORKSPACE we will probably generated .bzl file instead of the WORKSPACE file itself and that shouldn't be a problem anymore.

**Comment by pgr0ss** [comment]
Good to know. Thanks!

**Comment by kchodorow** [comment]
This was fixed via https://github.com/bazelbuild/bazel/commit/cefb639f3d2c0a8e331d46332f78bfa4ed1d8691.
