### ISSUE TITLE
Homebrew Recipe

### ISSUE THREAD

**Issue by nikestep** [bazelbuild/bazel#386]
It would be great if bazel had a Homebrew recipe to make installation on OSX super easy.

**Comment by DomT4** [comment]
We've passed on Bazel before because of lack of tagged releases and other issues described in https://github.com/Homebrew/homebrew/pull/38061. If those issues have since been resolved though, we'd love to see it in Homebrew (with tagged releases) or in `head-only` for now if there aren't any.

**Comment by nikestep** [comment]
Yes, there's a few requirements missing, but should be easily resolvable. That's why I filed against the bazel team, hoping they can fix it quickly.

**Comment by ulfjack** [comment]
We'll start tagging releases very soon. :-)

**Comment by damienmg** [comment]
So here to confirm that we will tag releases and do binary releases. Testing distribution using brew by the end of the year is also on our roadmap.

@DomT4 I am a bit curious what were the other issues (we do not use libarchive anymore so we don't call brew anymore in compile.sh)? Also, does brew requires to build on the machine or can we ship a binary and brew install it on the machine?

**Comment by DomT4** [comment]
>  I am a bit curious what were the other issues

As far as I remember:
* No tagged stable releases
* Calling `brew` to determine where to find things. (Homebrew removes `brew` from `$PATH` during builds).

You can still use dependencies that are available via Homebrew, but calling them via `brew --prefix xyz` will break per the above inside Homebrew itself. Ideally if there need to be dependencies they'd be scooped up from the environment or allow us to pass correct paths to them.

> Also, does brew requires to build on the machine

Kind of, yes. We provide our own binaries (We call them bottles) which our CI generates for the most three recent stable OS X versions. So although we build from source, the vast majority of our users will get a binary download, just from us rather than you.

> can we ship a binary and brew install it on the machine?

There's always the Homebrew/binary or Cask/Caskroom taps for this, if you want to formally support that via `brew`.

**Comment by damienmg** [comment]
So for the blocker there is no more problem. We will start tagging *stable* release next week (we are still in beta, but the release will be stable enough for Google :)) and we have no more reference to brew in our scripts.

For the binary it is just because we might drop the compile.sh script at one point of time and do cross-compile using bazel instead (so we have a really simpler bootstrap script that would work only on a few machine). Or maybe that's something that brew could support at once (building next bazel with previous bazel)?

**Comment by DomT4** [comment]
Yup, if those two issues have or will be soon solved, shouldn't be any issues preventing inclusion in Homebrew. We'd love to support bazel.

> Or maybe that's something that brew could support at once (building next bazel with previous bazel)?

We could do this, absolutely. We're already doing this for [Go/Golang per the 1.5 release](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/go.rb#L26-L47), so there's precedent for that kind of bootstrapping.

**Comment by 2rs2ts** [comment]
+1 to this.

**Comment by kashif** [comment]
see Homebrew/homebrew/#45881

**Comment by damienmg** [comment]
This is done :)
