### ISSUE TITLE
Please always provide absolute paths for compiler autoconfiguration

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#3910]
The `$(CC)` make variable is sometimes an absolute path (such as `/usr/bin/gcc`) and sometimes a relative path (such as `external/local_config_cc/cc_wrapper.sh`). This makes it pretty awkward to use when Bazel-ifying external repos, which often have build scripts that `cd` around the source tree.

Can you please change the make variable handling so this path is always absolute?

**Comment by lberki** [comment]
/cc @mhlopko 

We can't set `$(CC)` to an absolute path if the C++ compiler is hermetic, i.e. considered a source file, because then the local path of either your workspace or execroot would leak into the action and thus cross-user caching would be impossible and the paths would not make sense when shipped to a remote machine for execution.

If needed, you can always do a `CC=$(realpath -f ${CC})` within the action itself, though.
