### ISSUE TITLE
Can not build android_library with embedded so file (using ndk)

### ISSUE THREAD

**Issue by spinorx** [bazelbuild/bazel#3924]
### If possible, provide a minimal example to reproduce the problem:
Created a simple android_library which encloses java and needed so file at:  https://github.com/spinorx/bazel_android_test

doing:  bazel build --config android :and_lib -s

Getting compilation error:
```
ERROR: /Users/param/bazel_android_test/BUILD:3:1: C++ compilation of rule '//:liband_cpp.so' failed (Exit 1).
clang: error: unknown argument: '-m<platform_for_version_min>-version-min=11.0'
Target //:and_lib failed to build
```

I am trying to get android ndk to build so file using libc++ using bazel.
(Note that I has to push include under libcxx for libc++ because of: 
https://github.com/bazelbuild/bazel/issues/3923)

### Environment info
* Operating System:
Mac OS  10.12.6

* Bazel version (output of `bazel info release`):
release 0.6.1-homebrew

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by spinorx** [comment]
command issued is also using local clang rather than one in android ndk.
```
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' '-std=c++14' -iquote . -iquote bazel-out/stub_armeabi-v7a-fastbuild/genfiles -iquote external/bazel_tools -iquote bazel-out/stub_armeabi-v7a-fastbuild/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -MD -MF bazel-out/stub_armeabi-v7a-fastbuild/bin/_objs/liband_cpp.so/jni.pic.d '-frandom-seed=bazel-out/stub_armeabi-v7a-fastbuild/bin/_objs/liband_cpp.so/jni.pic.o' -fPIC '-isysroot __BAZEL_XCODE_SDKROOT__' '-m<platform_for_version_min>-version-min=11.0' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c jni.cc -o bazel-out/stub_armeabi-v7a-fastbuild/bin/_objs/liband_cpp.so/jni.pic.o)
```

**Comment by spinorx** [comment]
@aj-michael who is doing most android changes.

**Comment by aj-michael** [comment]
+ @ahumesky , because I'm not sure I'll have time to look at this week.

What is your NDK version?

This is almost certainly the same bug that was reported in #3641. I started a fix a bit ago, but have not submitted it.

**Comment by spinorx** [comment]
Thanks for response.

I am using android-ndk-r14b/

More updates.  If I build through android_binary rather than android_library things work well.  Also need to explicitly add lib path --linkopt=-Lexternal/android_ndk/ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a to build.

**Comment by ahumesky** [comment]
The more typical way for an android app to depend on native code is to depend on a cc_library directly:

```python
android_binary(
  name = "and_bin",
  srcs = glob([
    "java/**/*.java",
  ]),
  custom_package = "",
  manifest = "AndroidManifest.xml",
  deps = [
    ":native_deps",
    "@android_sdk//com.android.support:support-annotations-25.3.1",
  ],
)

cc_library(
  name = "native_deps",
  srcs = [
    "jni.cc",
  ],
  linkopts = [
    "-llog",
  ]
)
```

The reason that local clang was being used was that you were building the `android_library` as the top-level target, and not the `android_binary`. It's unfortunately a bit complicated. `android_binary` has special treatment for its native deps (`cc_library` rules) where they will be built in the "android configuration", which is controlled by `--fat_apk_cpu` and `--android_crosstool_top` (among others). `--android_crosstool_top` is automatically set to the NDK if you use an `android_ndk_repository` rule, and `--fat_apk_cpu` defaults to `armeabi-v7a`. It can be set to `armeabi-v7a,x86` to create two .so files in the apk, one for each architecture. Since the change to the android configuration only happens for `android_binary`, when you were building the `android_library` directly, the CC rules below it didn't get the android configuration, and hence were getting the "normal" CC configuration (whatever `--cpu` and `--crosstool_top` were set to).

Basically, all you should need to do is use a `cc_library` as in the example above and invoke `bazel build :and_bin` (no `--config android` required). If you want to build the native code for an x86 device (e.g. an emulator) then you can add `--fat_apk_cpu=x86`.

If you still want to be able to build the `android_library` as a top-level target (i.e. from the command line directly), then you'll need to set the CC configuration to android: `--crosstool_top=@android_ndk//:toolchain-libcpp --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain`. Note that this changes the CC configuration for the whole build to android (not just the dependencies of `android_binary` rules), so if you wanted to build, say, some other `cc_binary` in the same invocation, or your entire codebase (e.g. `//...`) which might include non-android things, then they probably won't build.

See https://docs.bazel.build/versions/master/user-manual.html#flag--fat_apk_cpu

**Comment by spinorx** [comment]
Thanks Adam.  I was expecting android_library to behave like android_binary in terms of changing cc_library's special treatment since what one can deduce from android_binary can be deduced from android library.  My initial plan was to use bagel to produce the aar file which included so file (the model pieces) and use android studio project for UI pieces.

Last paragraph will help with that.  FWIW iOS_framework behaves similarly.  Given workarounds definitely sounds like lower priority.  (Assuming the linking issues with libc++ will be addressed with the include issue).

**Comment by spinorx** [comment]
Hi Adam,  Another question partially related to cross tool top.  What is good way to detect bagel is building android.  In protobuf lib I see:  
config_setting(
    name = "android",
    values = {
        "crosstool_top": "//external:android/crosstool",
    },

Which does not look compatible with using --android_crosstool_top.
I added flag which can be passed in with --define PLATFORM=android.  But not sure if there is better approach.
 
https://github.com/google/protobuf/pull/3778

**Comment by aj-michael** [comment]
That's a hard question, because Bazel doesn't really know about "building android". When bazel analyzes cc_library rules, it uses the values of --crosstool_top and --cpu. When a Bazel analyzes an android_binary, it changes the values of --crosstool_top and --cpu based on --android_crosstool_top, --android_cpu and --fat_apk_cpu. Furthermore, while the Bazel team provides some built-in crosstools like //external:android/crosstool, there is nothing to stop a third_party from creating their own crosstool with a different name.

Protobuf's config_setting looks like it should support your use case, if you are building an android_binary with --android_crosstool_top. Because the cc_librarys underneath it will see --crosstool_top set to --android_crosstool_top.

**Comment by spinorx** [comment]
It was not working because I am using --android_crosstool_top=@android_ndk//:toolchain-libcpp.  I have to use that because grpc uses some cpp functions which are not in libstdcpp: https://stackoverflow.com/questions/22774009/android-ndk-stdto-string-support

Adding:
config_setting(
    name = "android_libcpp",
    values = {
        "crosstool_top": "@android_ndk//:toolchain-libcpp",
    },
)

works.

@xfxyjwf

**Comment by aj-michael** [comment]
So just to summarize, the issue here is that "building for Android" can mean multiple things and it's not reasonable for protobuf team to keep an exhaustive list of all of them. (I'd argue it's also not reasonable for Bazel team to keep an exhaustive list, since users can define their own Android crosstools. But maybe that's another discussion.)

@spinorx , you can try adding this to the bottom of your WORKSPACE:

```
bind(name = "android/crosstool", actual = "@android_ndk//:toolchain-libcpp")
```

This will override the value of `//external:android/crosstool` from `@android_ndk//:gnu-libstdcpp` to `@android_ndk//:toolchain-libcpp`. Then you can use --android_crosstool_top=//external:android/crosstool.

**Comment by spinorx** [comment]
Thanks Adam,  this is much more elegant solution.

**Comment by aj-michael** [comment]
FWIW, we have a long-term solution called "constraint-based platforms" that is still in the works. It should us to express things like, "this cross tool is usable for building against the Android platform". And the config settings can select on the well-defined "Android platform". You can read a bit about it here:

https://docs.google.com/document/d/1-G-VPRLEj9VyfC6VrQBiR8To-dZjnBSQS66Y4nargGM
