### ISSUE TITLE
GitHub mirroring is broken

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#3932]
Changes exported to GoB no longer appear on GitHub.

A commit was made directly to the GitHub repository [1] (by clicking edit on the README and merging directly). Since then, new code changes exported to GoB [2] no longer appear on GitHub.

@damienmg I am looking for guidance on this one - I am not sure how the mirroring to GitHub works. Would it be sufficient to delete these two commits from the github repository by force pushing to it, and then GoB changes will sync again?

[1] https://github.com/bazelbuild/bazel/commit/2eeaa153e481f771dda12e282690a2e7966ba390
[2] https://bazel.googlesource.com/bazel/

**Comment by buchgr** [comment]
cc: @katre

**Comment by buchgr** [comment]
Chatted with @katre. We decided to reset the gist history to `4b07f7ed6ab8007284e9d4f075b70b004fe0c25d` and then force push this change to GitHub. So that GitHub will be behind GoB again. Re-exporting should make mirroring work again.

Unfortunately, this will break `git pull` for everyone who has checked out this latest changes.

**Comment by damienmg** [comment]
Never ever force push to GitHub

**Comment by buchgr** [comment]
Is there an alternative?

**Comment by Reflexe** [comment]
Is there an alternative? With GitHub and GoB history diverged?

You can set the mirroring to pull (and merge) GoB's head to Github's head instead of pushing GoB's commits to Github. However, I have no idea how the mirroring works or if it is possible.

I don't think that reverting would work since it look like the mirroring doesn't like GoB's HEAD and Github's HEAD being different (reverting would not make them equal).

**Comment by damienmg** [comment]
As discussed offline, we are going to overwrite gerrit HEAD

**Comment by buchgr** [comment]
Fixed
