### ISSUE TITLE
Bazel installer missing?

### ISSUE THREAD

**Issue by myphysicslab** [bazelbuild/bazel#403]
I'd like to try using Bazel, but where is the Bazel installer?  The link at <http://bazel.io/docs/install.html> that says "download the Bazel installer for your operating system" leads to <https://github.com/bazelbuild/bazel/releases> which says "There aren’t any releases here".  Do I need to build the Bazel installer myself?

**Comment by ulfjack** [comment]
Sorry about that. We were about to push our first beta release earlier today but then discovered a bug in the Android rules. We discussed this and decided to push a release candidate (not a release quite yet) as soon as we have the bug fixed (working on that right now), and then do some more manual testing tomorrow before promoting that to release.

So, if you can wait, you'll be able to get a binary tomorrow. Otherwise, you can build an installer from the github repository.

**Comment by TeBoring** [comment]
Do you have instruction to build from github repository?

**Comment by kchodorow** [comment]
Download the repository and run ./compile.sh.

(We should add compiling from source instructions to the documentation.)

**Comment by ulfjack** [comment]
Did I say tomorrow? I meant today, of course. :-P

**Comment by myphysicslab** [comment]
FYI, I was able to build Bazel from source, and it seems to be working.

**Comment by damienmg** [comment]
Release candidate is here:
https://storage.googleapis.com/bazel/0.1.0/rc1/index.html

**Comment by damienmg** [comment]
We issued a new candidate: https://storage.googleapis.com/bazel/0.1.0/rc2/index.html

**Comment by damienmg** [comment]
We issued the release yesterday :)
