### ISSUE TITLE
Canonical naming for external repositories

### ISSUE THREAD

**Issue by ronshapiro** [bazelbuild/bazel#4038]
There's a discrepancy within documentation on how to best name external repositories and common practice, and I think we should formalize this in order to make importing bazel projects as easy as possible.

The [WORKSPACE docs](https://docs.bazel.build/versions/master/be/workspace.html#maven_jar_name) recommend a way to name jars that are on maven. That's great, but it's often redundant, which has led to the naming proposal for [`java_import_external`](https://github.com/bazelbuild/bazel/blob/67c84b1036ad02ba2384fa75fb28e779a488f3d4/tools/build_defs/repo/java.bzl#L87). And yet others name things differently (for java libraries, perhaps the java package?). Furthermore, I don't believe there is any guidelines on any of the other workspace rules.

Consistency is key, otherwise it becomes very difficult for projects to integrate two libraries that use the different conventions. This has come up recently as [Dagger](https://github.com/google/dagger) has been trying to integrate with [Kythe](https://github.com/google/kythe) and also get [rules_closure](https://github.com/bazelbuild/rules_closure) to use the defined Dagger bazel rules instead of downloading maven jars.

I personally don't care much about what convention we select, I think there are tradeoffs to both, but I do think this is something that is worth documenting clearly. When a project is not in accordance with the convention, we need a good place to point them so that we can achieve consistency.

**Comment by jart** [comment]
I support bringing greater consistency to names.

I would like to see Bazel project leaders (and ideally Google leadership as well) to join the community in defining a standard naming convention for Bazel repositories. We need one that can apply not only Maven, but other languages as well.

I support the imperfect yet readable approach I proposed with `java_import_external`. It makes a tradeoff on edge cases to eliminate redundancy. Please consider that names are an imperfect thing. The restriction on repo name characters alone most likely already made the possibility for a perfect mapping for Maven impossible. Even if a perfect mapping for Maven was possible, Maven names are not required to derive their legitimacy from DNS.

In order to standardize such an imperfect approach, without the creation of a centralized registry service, a "soft" opt-in registry approach could be taken, by simply creating an official public spreadsheet of recommended names.

**Comment by damienmg** [comment]
The current convention is defined in the [workspace function documentation](https://docs.bazel.build/versions/master/be/functions.html#workspace):

```
A workspace name must start with a letter and can contain letters, numbers, and underscores (this is to maximize the number of languages for which this string can be a legal package/module name). It should describe the project in reverse-DNS form, with elements separated by underscores. For example, if a project is hosted at example.com/some-project, you might use com_example_some_project as the workspace name.
```

We had some discussion with @ittaiz and @johnynek about that yesterday. As I said I am open to have improvement over that naming convention and agree that we should have canonical names.

**Comment by johnynek** [comment]
I would really love to expand the characters that can be used in workspace names to accommodate existing naming schemes without collisions.

For instance:
```
@maven:com.google.guava:guava//:jar
``` 
being an example. So, concretely, you have a prefix naming scheme (maybe `npm:` or `maven:` or `cargo:` etc...) then we can use any character other than `/`. So basically, any unicode character other than `/` allowed between `@` and `//`.

Lastly, bazel's job is to encode (use UTF-7 or encode in base32 or whatever) to get it onto the filesystem, but that may be independent of how names are actually encoded.

**Comment by jart** [comment]
I'm not opposed to @johnynek's suggestion. The only concern I would have is that a label like `@maven:com.google.guava:guava//:jar` might communicate to the user that a deeper collaboration is happening between Bazel and the Maven registry, or if those colons represent a logical hierarchical structure, rather than simply being a naming convention in a flat namespace.

**Comment by ronshapiro** [comment]
If I declare `@maven:com.google.guava:guava//:jar` dependency, then everyone who wants to use my library downstream has to use guava from Maven (or name it incorrectly). What if they want to use one of the many other workspace definitions?

One of the compelling reasons I think about @jart's proposal is that a `maven_jar` doesn't necessary encode that it comes from maven. Example:

Dagger uses bazel currently. It has a dep on Guava (via a `maven_jar`). Someone uses Dagger and declares a `com_google_guava_guava` workspace rule to match. All is fine and dandy.

But then comes Guava and decides to start using bazel also, and now the canonical name for the repo will be `@com_google_guava`. I guess it's already an issue, as there's no way to get `@com_google_guava_guava//jar` to migrate well to a bazel workspace, but even if there were, the repository name would change under this situation.

**Comment by johnynek** [comment]
we handle this case in https://github.com/johnynek/bazel-deps by making no-op targets that just export the items you need. So, we can replace jars with targets built natively with bazel so it is opaque to users (it is just a target in `3rdparty/...` for repo users), but dealing with this in a way that works transitively with recursive workspaces will be a challenge.

**Comment by ittaiz** [comment]
@ronshapiro I think you make a good point but I'm not sure I understand your proposal.
Why will `guava` be named `com_google_guava` if they use bazel? Thanks to what convention?
I think that part of the problem is trying to generalize naming over several domains without having successfully identifying the identifiers.

**Comment by ronshapiro** [comment]
`com_google` for the reverse DNS and then just `guava` for the name of the project. Right now there's the duplication of `guava` since  the maven coordinates are `com.google.guava:guava`

**Comment by johnynek** [comment]
I think we should try to make a doc and talk about goals and non-goals.

Using a naming scheme such that migration from a package manager to a bazel build and that being transparent to downstream recursive dependencies seems to be very challenging and I would not be eager to try to do this.

How do you do that with python, for instance? Python requirements are not namespaced in a way that ensures you won't collide with c-libraries or even maven projects (not all of which use the reverse DNS approach).

I currently lean towards using a lossless mapping to existing package manager approaches namespaced by the package manager.

**Comment by jart** [comment]
My understanding of the point @ronshapiro was making earlier, is that naming shouldn't reflect where a library comes *from* but rather should reflect what it *is*. A canonical mapping for Maven can never be canonical in Bazel, because Bazel can obtain those very same Maven artifacts from places other than Maven.

**Comment by johnynek** [comment]
I agree the name should be what it is, but my point is that a compiled jar is hard to be sure it is the same as some bazel target that someone else made that should represent the same thing built by maven (or sbt for instance).

So, I would argue that these two things (a jar built by maven vs a rule in a bazel repo) are sufficiently different that they should have different names.

**Comment by jart** [comment]
Assuming that's correct, would it not be better to have the label be `@maven:com.google.guava:guava:23.4-jre//:jar`, because `23.4-jre` is much difference from `19.0`?

My argument is that the differences between various Guavas don't matter. What matters is that each Bazel deployment chooses exactly one and only one of them. Otherwise evil classpath errors happen. If more than one label exists for Guava, then it just adds alias() toil.

**Comment by ittaiz** [comment]
@jart who advocated having multiple instances of guava?

**Comment by cgruber** [comment]
I don't read @jart as accusing advocacy of multiple versions, but more noting that if we see dagger-from-maven as different (in label) from dagger-from-blaze, then there's no good reason not to also distinguish the N versions of dagger also.  

This whole problem comes from bazel and maven having very different ways of slicing the problem up, bazel assuming one-version (or rather a view of the universe that is version-locked within that view).  Maven looks at a dependency graph as having flavors and aspects (versions and classifiers, properly), where bazel flattens those dimensions into extra nodes and edges.  Maven and bazel, during a build, triangulate things more definitely , in maven's case, to a specific version for each node, and a particular classifier) and with bazel, it's just whatver sub-graph of available nodes you've picked.  So this is a mapping problem, in essence.

So then the question is... what does a label mean, in the context of a bazel graph. I think @jart and @ronshapiro are saying that in bazel, a target's label should reflect "what is this dependency _to me_ " as opposed to "what is this dependency _in itself_".  It's sort of an API vs. implementation distinction of a sort.   From a bazel project's perspective, that thing is dagger, not dagger-2.13, because it can only use one dagger at a time, so it doesn't care (from a deps graph perspective) which dagger... that's a configuration detail.  So this view lends itself to support a more abstract labelling scheme. 

I agree with @jart and @ronshapiro (assuming I've not misunderstood that view).  I think that there is SOME merit in one aspect of the maven situation, which is the idea of canonical naming of artifacts.  Indeed, I think it's ron's frustration with a lack of such canonical naming in the bazel-verse that lead to this issue being filed.

The complications that have come up in my own experimentation on this (specifically trying to tinker with swapping in bazel and maven versions of dagger in a project) are also that ":" are namespace separators for maven, but a very different mechanism in bazel. 

Maybe it's possible to have a convention that is a hybrid, in the following way.  That is, where bazel and maven agree is - you have a graph of nodes.  Maven uses a groupId:artifactId pair to locate a node with a third value (version) to provide the implementation, so to speak. That's not bad.  The duplication of, say, com.google.guava:guava is an accident of naming choices because guava and guava-testlib both want to be qualified by com.google.guava in the maven universe.  I could live with that level of duplication.

I'm thinking of something like a `import_maven_java_library(artifact="com.google.guava:guava:21.0)` in the workspace which automatically (in the workspace) generates a java_library target in an "exports only" package space that looks like `@external//java/com/google/guava:guava`, which is backed-by the extracted jars.  Hey, if we want to be super fancy, it could even automatically build and import the deps too.  But the important bit here, is that this maps nicely to maven, but can also be mapped in other projects.  Want to swap it, use a

```
import_bazel_java_library(
    project="google/guava[@version_tag]",
    import_target="java/com/google/guava:guava",
    project_target = "path/from/workspace/to/project:target")
```

> note: I don't know how much of the above could be inferred from sane defaults, I'm just expanding it out here - maybe more can be inferred.

The point here is that it provides a consistent worldview for a project to reference its deps.  It does privilege the maven group/artifact a bit, but it's not that terribly different from package:target in blaze, except for prefixing like `somerepo@` or `//third_party/java/` prefixing.  But in my project I could list `@external//java/com/google/dagger:dagger` and get the right artifact whether I was importing the maven artifact or the project at head/tag from github.  I think the namespace:label grouping isn't the worst. But the whole scheme needs to be done in a way that one can consistently declare one's dependencies, and not do thirty-million steps to set up the conditions so that the scheme works (in the WORKSPACE/.bzl files I mean). 

Using some special space like `@external/type` to provide a consistent parent gives a consistent namespace for external projects and using a bazel-friendly translation (not underscores, for god's sake, as underscores can be part of artifact names) gives package:target consistency.  The import mechanism is then nicely separated, and can be managed separately.  But this is a "who are these things to me" view of the world, but one that can map nicely to maven and be arbitrarily mapped back from any project structure. 

Open issues and notes:

* An implication of this is that projects which expect to be consumed may well want to declare an entry point target - that may be as simple as adding an "artifact" parameter to java_library and maybe several other relevant ones which exposes this, and transitive inclusions can be overridden by local imports with the same artifact. 
* If these are to include any transitivity, there needs to be a way to prune the graph, to say "exclude guava" from dagger, in case I'm pulling it in differently from that project. 
* I would have suggested //third_party/type as a prefix, but early uses of //third_party/java as a file-import approach have sort of made that harder.
* This is a fairly java-ecosystem-centric concern, though in fairness, maven is not only a java artifact repo. But it may be that a totally different set of norms for not-typically-maven-supporting ecosystems is recommended... but the same `@external/type` mechanism could be used there too. 
* having all eternal deps live in `@external/type` could make managing inter-project deps easier, insofar as the above points suggest some short-circuiting of the graph... if the deps all are named in consistent ways, then the `@external` namespace for two projects which share deps should look the same (to the consuming project), making a lot of the above easier. 

Anyway - this is a bit of a brain dump, apologies for the wall of text.  In one sense, it isnt' that far from `@maven:...` but it makes it a teensy bit more abstract, yet familiar to maven users, and mappable to several import strategies.  If we develop some .bzl rules (or bake them into bazel) that assume these patterns by default, we can reduce a lot of boilerplate, with a list of maven deps in WORKSPACE turning into a well-formed set of targets in bazel-space that surprise no one... but github imports would look the same.

**Comment by cgruber** [comment]
>So, I would argue that these two things (a jar built by maven vs a rule in a bazel repo) are sufficiently different that they should have different names.

Further clarification... I think they deserve different names... as implementation details in the workspace.  But in the project's bazel-universe, they only need different labels if they can both be coherently referenced, which they can't, because they're substitutes.  Just like, in a maven pom, you can't simultaneously see com.google.dagger:dagger:2.11 and com.google.dagger:dagger:2.13, because they're substitutes. Try to reference them both and it's bad.  If you've got your enforcer plugin set up, it'll bomb out as an error. 

So yes they're different, but they mean the same thing, conceptually, to the BUILD files in the project using them. So they should have the same "key" (so to speak)

**Comment by cgruber** [comment]
I should point out, that a fair chunk of the idea I had is achieved by the maven bazel config generator mentioned early in this thread, though I had in mind that it not be generated and checked in, but implemented in bazel natively or in skylark, with the various bits cached after first fetch.  But I think that a lot of the fiddling one might do with the configuration generated from such a tool would be less and less necessary if we can solve this "standard label/coordinate" concern.

**Comment by ittaiz** [comment]
Before I go into the details I'll say a general +1, I think the direction is good.

Your suggestion sounds to me like incorporating 'bind' into the external repositories machinery which I like but I think others (like @jart) don't. It's similar to bind in the sense that I declare what I need and I allow wiggle room in *where* it comes from.

Not that I think that you’re disagreeing with me but it’s important for me to say that to me the canonical and unique part of the namespace is very important to eliminate duplications and so shortcuts like com_google_guava are a real problem.

Re interface vs implementation- I like your analogy greatly. The problem with it is that if you think of interfaces from the consumer’s standpoint (which is how I read your post) I see a mismatch since this post is about canonicalization and "what is this dependency to me” might vary greatly in name than what is this dependency to a different project. WDYT about the following description- "what is this dependency in itself” as opposed to “where it came from”. Might be only semantics but I think semantics are important in this discussion.

Re transitive dependencies retrieval of workspace rules- I think that’s a good idea but it should wait for this to be reproducible; A relevant discussion about it is in the [A Brave New World for the Bazel WORKSPACE File](https://docs.google.com/document/d/1HfRGRW4MwnVUG24rw3HJIBkdEYfXlESnlKOboO97A3A/edit) doc
+1 on pruning transitive graph since this sounds like an important feature in the many-repo external dependencies discussion we have overlooked.

Re your suggestion of having repository rules which have a generated name- I think that’s a great idea which @mattmoor  and myself also raised in the conference.
@damienmg - do you think we should open a separate issue to discuss the option of having generated names for repository rules or should it be part of this discussion? It stands on its own but it gets great resonance here

Btw, all of these issues were discussed in the conference greatly which is to reinforce the importance of this discussion.

**Comment by alexeagle** [comment]
Angular also needs to expand WORKSPACE names.

We use EcmaScript modules, which use file paths as module identifiers. Thus an import looks like
`import from 'package-name'`
or 
`import {thing} from '@scope/package/deep/import'`

Under Bazel, we use the workspace name as the beginning of import statements:
`import from 'my_wksp/path/to/file'`

but now I cannot publish these files to npm under my package name if it's `@angular/core` for example.

to merge these semantics, we need to be able to encode arbitrary strings as workspace names.

**Comment by katre** [comment]
Downgrading priority.
