### ISSUE TITLE
Swig failure on Centos 6.2 for tensorflow

### ISSUE THREAD

**Issue by barche** [bazelbuild/bazel#4053]
Hi,

As reported here: https://github.com/tensorflow/tensorflow/issues/14211

Looking on stackoverflow, I found this:
https://stackoverflow.com/questions/45859371/error-building-tensorflow-on-centos-7

I can confirm building tensorflow 1.3.1 using bazel 0.5.1 does work, as suggested.

Unfortunately, the suggestion of using bazel 0.5.1 is no longer valid for tensorflow 1.4, since it requires at least bazel 0.5.4. I have verified this error happens on bazel 0.5.3, 0.6.0 and 0.7.0. For completeness my original report to the tensorflow issues:

```text
INFO: $TEST_TMPDIR defined: output root default is '/tmp'.
........................
WARNING: /home/username/src/tensorflow/tensorflow/core/BUILD:1787:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /home/username/src/tensorflow/tensorflow/tensorflow.bzl:1073:30.
WARNING: /home/username/src/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /home/username/src/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
INFO: Found 1 target...
ERROR: /home/username/src/tensorflow/tensorflow/python/BUILD:2974:1: SWIGing tensorflow/python/tensorflow.i failed (Exit 1): swig failed: error executing command
  (cd /tmp/_bazel_username/dcca333cc36b578f4473c754fbbc85ff/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/swig/swig -c++ -python -module pywrap_tensorflow_internal -o bazel-out/local-py3-opt/bin/tensorflow/python/pywrap_tensorflow_internal.cc -outdir bazel-out/local-py3-opt/bin/tensorflow/python -ltensorflow/python/client/device_lib.i -ltensorflow/python/client/events_writer.i -ltensorflow/python/client/tf_session.i -ltensorflow/python/client/tf_sessionrun_wrapper.i -ltensorflow/python/framework/cpp_shape_inference.i -ltensorflow/python/framework/python_op_gen.i -ltensorflow/python/grappler/cluster.i -ltensorflow/python/grappler/cost_analyzer.i -ltensorflow/python/grappler/item.i -ltensorflow/python/grappler/model_analyzer.i -ltensorflow/python/grappler/tf_optimizer.i -ltensorflow/python/lib/core/py_func.i -ltensorflow/python/lib/core/strings.i -ltensorflow/python/lib/io/file_io.i -ltensorflow/python/lib/io/py_record_reader.i -ltensorflow/python/lib/io/py_record_writer.i -ltensorflow/python/platform/base.i -ltensorflow/python/pywrap_tfe.i -ltensorflow/python/training/quantize_training.i -ltensorflow/python/training/server_lib.i -ltensorflow/python/util/kernel_registry.i -ltensorflow/python/util/port.i -ltensorflow/python/util/py_checkpoint_reader.i -ltensorflow/python/util/stat_summarizer.i -ltensorflow/python/util/tfprof.i -ltensorflow/python/util/transform_graph.i -ltensorflow/python/util/util.i -Ibazel-out/local-py3-opt/genfiles -Iexternal/eigen_archive -Iexternal/grpc -Iexternal/protobuf_archive -Iexternal/swig -Iexternal/boringssl -Ibazel-out/local-py3-opt/genfiles/external/local_config_python -Iexternal/nsync -Iexternal/gemmlowp -Iexternal/jpeg -Iexternal/com_googlesource_code_re2 -Iexternal/jsoncpp_git -Iexternal/zlib_archive -Iexternal/highwayhash -Iexternal/gif_archive -Ibazel-out/local-py3-opt/genfiles/external/jpeg -Iexternal/lmdb -Iexternal/png_archive -Iexternal/farmhash_archive -Iexternal/local_config_cuda -Iexternal/sqlite_archive -Iexternal/swig/Lib -Iexternal/swig/Lib/cffi -Iexternal/swig/Lib/python -Iexternal/swig/Lib/std -Iexternal/swig/Lib/typemaps tensorflow/python/tensorflow.i).
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by boegel** [comment]
I'm running into the same problem...

I have tried by updating the SWIG version that is used (by applying this patch: https://gist.github.com/boegel/1686e07e402293e6e8d428a16be93c6b), but that didn't help.

Digging in further now.

**Comment by boegel** [comment]
This patch fixes the problem for me:

```diff
--- tensorflow/tensorflow.bzl.orig	2017-11-01 21:21:13.000000000 +0100
+++ tensorflow/tensorflow.bzl	2017-11-09 11:49:41.536361562 +0100
@@ -920,6 +920,7 @@
   args += [src.path]
   outputs = [ctx.outputs.cc_out, ctx.outputs.py_out]
   ctx.action(
+      use_default_shell_env = True,
       executable=ctx.executable._swig,
       arguments=args,
       inputs=list(inputs),
```

I'm not sure what the problem *is* though, since I'm not seeing any error messages being produced by `SWIG`, only `exit 1`. Maybe `ctx.action` (the Bazel method used for running commands) is swallowing the output?

In addition, if I run the `swig` command that fails manually, it works fine. So maybe it's the environment that Bazel runs it in by default is broken somehow?

Unsure how to gather more information on the actual problem, any suggestions are appreciated.

**Comment by barche** [comment]
Aha, great to have a workaround for newer versions. I have exactly the same behavior and I also don't know how to get the error message from swig, it seems bazel prints only the command but not the output.

**Comment by damienmg** [comment]
This looks like a TensorFlow issue to me. I'll close and feel free to suggest the patch to the tensorflow repository.

**Comment by boegel** [comment]
@damienmg An issue was opened in the TensorFlow repo initially for this, see https://github.com/tensorflow/tensorflow/issues/14211, and it was deemed "not a bug" there. I'm not convinced either way though...

We're kind of blind here; it's not clear at all what the problem actually is, since other than `exit 1` there's no actual error message...
`swig` is being run via Bazel's `ctx.action`, which seems to be swallowing all output (both stdout & stderr) of the `swig` command. Running the same command manually works, and the patch seems to confirm the problem is somehow caused by the environment in which `swig` is being run.

Is there any way we can get a hold of the output produced by `swig` when being run via `ctx.action`, so we can figure out what the actual problem is?

I did a naive attempt by appending `> swig.out 2> swig.err` at the end `args`, but that didn't work. Anything else we can try?
