### ISSUE TITLE
Design question: Will --platforms build in a unique subdirectory of the build tree?

### ISSUE THREAD

**Issue by pcj** [bazelbuild/bazel#4111]
In discussing cross-compile for rules_go (https://github.com/bazelbuild/rules_go/issues/1030#issuecomment-345254805), @ianthehat brought up the question of whether the penultimate manifestation of `--experimental_platforms` will build on a separate area of the build tree (like `--cpu`). 

Is this known?

As an add-on question, do we have a timeline for platform transitions (and design doc that discusses it?)

**Comment by katre** [comment]
We are actually moving away from having cpu affect the output path directly. The issue is that the data that was previously in the output path was being read from the CROSSTOOL file, not directly from the cpu flag, and thus required every single target to depend on CROSSTOOL, regardless of whether it was doing cpp compilation or not.

We have a lot of open design questions around the proper handling of output paths. The eventual goal is to cache build artifacts based on the unique configuration, but we're still figuring out exactly what that means. As we keep adding more features to control configurations, this is becoming more important, as you are aware.

The eventual goal is to have a platforms attribute on rules, which will let you set the target platform there directly, as part of our larger goal to have flagless builds. A future improvement on that will be allowing multiple configuration builds in the same invocation, so you can build all architectures of a target at once, but that is even further away. One point we're looking into is the target graph size: if you build for two architectures, the number of compile actions roughly doubles, and gets worse very quickly as people add more architectures. We have a lot of performance improvements to make before we want to turn on features that can blow out memory like this.

So the final answer is: yes, we're aware of the questions and problems, no, we don't have any good answers, but we're working on it.
