### ISSUE TITLE
Provide functionality to not retry a test on certain conditions

### ISSUE THREAD

**Issue by Utsav2** [bazelbuild/bazel#4145]
In certain conditions, we don't want a test to retry, even if `--flaky_test_attempts` is set. For example, we run go tests in race mode, and if a test fails due to a data race, we don't want the test to retry (and pass). 

Ideally, we would like to mark the test failed, due to the data race.

This could be implemented via a magic exit code.

**Comment by meteorcloudy** [comment]
@damienmg What do you think of this suggestion?

**Comment by damienmg** [comment]
This seems like something that belongs to the test framework, i.e.:

```
for (int i = 0; i < nbAttempts; i++) {
  if (callTest()) {
    return 1;
  }
}
return 0;
```

You can do that by wrapping the test in a shell wrapper. The only advantages of doing that in Bazel would be to get a clean sandbox for every test and executing multiple test in // (flaky test does not do parallel testing, it is just to reduce noise from flaky tests, and should be used sparingly)...

/cc @ulfjack @davidstanke to follow but I don't think we should have that in Bazel.

**Comment by ulfjack** [comment]
Why are you using --flaky_test_attempts?

It seems to be that the problem is that flaky_test_attempts configures two independent things at the same time. If you don't set it, then Bazel observes the flaky test tag, but if you do set it, Bazel ignores the flaky test tag, in addition to changing the number of runs to the given value.

**Comment by ulfjack** [comment]
In principle, I wouldn't mind splitting flaky_test_attempts into two orthogonal flags, but only if there's a strong use case for doing so.

**Comment by benjaminp** [comment]
I don't think the issue is about overly broad `--flaky_test_attempts` semantics. The idea is that some test failures are so serious—the OP proposes Go race detector errors as an example—that retrying, whether induced by `--flaky_test_attempts` or the `flaky` tag, should simply not continue. So, it would be nice if the test runner could ask Bazel to not attempt further retries.

**Comment by ulfjack** [comment]
I suppose that would be possible. I think we'd like to see a design doc for such a proposal, since it's a significant change to the Bazel-Test-protocol.

**Comment by jmmv** [comment]
I'd agree with the original assessment that this belongs in the test framework and not in Bazel. So, given the staleness of this request and the lack of a design doc, I'll close as stale.
