### ISSUE TITLE
Since Bazel 0.5.0, it's impossible to build a python3 py_binary on one OS and run on another

### ISSUE THREAD

**Issue by mishas** [bazelbuild/bazel#4146]
Since both the `--python_path` flag, and the `interpreter` label of the `python_runtime` targets only accept full paths, it makes it impossible to build and run programs on different systems when using python3.

By default, without setting the flag or the runtime targets, `python` (python2) is used, and the autogenerated "runner" file from `py_binary` targets searches the env of the system it's running on for where `python` is. But if I want to use `python3`, I have to specify a full path.
This is problematic, as the full path on the machine I'm building/testing on might be different from the one on the machine I'm actually running on.

For example, on Mac, python3 is installed either in `/usr/local/bin/python3` (when using brew) or in '/Library/Frameworks/Python.framework/Versions/3.X/bin/python3` when installing from a .pkg file. But on Linux, it is installed in `/usr/bin/python3`.
So - when building and testing on mac, I must have a --python_path defined to one folder, but during final build to another.

A simple solution would be to do `ln -s <wherever python is> /usr/bin/python3` on my build machine, but this is actually impossible on mac, as the `/usr` tree is read-only (https://stackoverflow.com/questions/32659348/operation-not-permitted-when-on-root-el-capitan-rootless-disabled)

Another solution would be to test with one flag, but then to build with another, but that approach fails if there are custom rules (skylark) that execute other targets via ctx.action during build.

This is somewhat related to this issue: https://github.com/bazelbuild/bazel/issues/3517

Proposed solution:
Allow setting "python3" (without full path) as `--python_path` or `interpreter` in `py_runtime`. It will actually work without any other changes to the code.
I'll attach a pull request shortly.

**Comment by meteorcloudy** [comment]
//cc @nlopezgi Can we make --python_path allow just "python3"?

Another approach I can think of is that in https://github.com/bazelbuild/bazel/blob/7585dcd677f650160917550cc29a9fb185f35cc3/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L35-L37

We fallback to "python" or "python3" if %python_binary% doesn't exist.

**Comment by brandjon** [comment]
Unless I'm mistaken this issue has submitted code and should be marked closed.

**Comment by paulspixels** [comment]
> Unless I'm mistaken this issue has submitted code and should be marked closed.

This still seems to be an issue, and after many hours wasted searching for a solution, all I can think of is that between Nov 2017 and Oct 2018 the original reporter lost interest or worked around the problem somehow. Basically the python_launcher relies on the py toolchain's path at compile time. But, what if you're cross compiling a python .zip file for a different platform? You can't run its python interpreter because it doesn't run on your native machine. But you can't change "PYTHON_BIN_PATH" because then none of the python will run on your native machine.

It seems the logic in this block is the cause: 

https://github.com/bazelbuild/bazel/blob/1b3eb424139cf907d708ab193cba8f2256313290/src/main/java/com/google/devtools/build/lib/bazel/rules/python/python_stub_template.txt#L40-L72

As a simple example: suppose you're cross-compiling on OSX with /usr/local/bin/python3, and your target machine is an embedded linux system which has no /usr/local directory; instead its python3 exists at /usr/bin/python3. I don't see how you can extricate the python specified by %python_binary% from the python used everywhere in bazel.
