### ISSUE TITLE
Does Bazel do something to make desugaring default/static interface methods not require clean builds?

### ISSUE THREAD

**Issue by hzsweers** [bazelbuild/bazel#4186]
Forgive the broad question. I'm asking with regards to this commit from @cushon - https://github.com/bazelbuild/bazel/commit/611ea1cad400879c64af196032222defd47fb82b

Our understanding from talking with the D8 engineers that this forces builds to be clean every time (similar to retrolambda before it). Gradle can get by with this with incremental compilation, but for non-incremental systems like Bazel and Buck, this seems like it'd be a potential performance cost. Since it was all enabled here though, I was curious if there's any added color to making this manageable.

CC @msridhar @kageiit

**Comment by cushon** [comment]
@kevin1e100

**Comment by kevin1e100** [comment]
Bazel has no such limitation; its support for default method differs from retrolambda and Android Studio 3.0 in this way.  Desugaring of default and static interface methods happens on a jar-by-jar basis.  On incremental rebuilds, Bazel only re-desugars Jars that need to be reprocessed.  Together with Bazel's incremental dexing feature, which is also enabled by default and makes it so that dx only runs over changed (desugared) Jars again, this means that incremental Android builds in Bazel typically only reprocess a fraction of your app.

**Comment by hzsweers** [comment]
Thanks Kevin! Really appreciate the details, will take this info to our build tools folks and the buck team
