### ISSUE TITLE
Wtf

### ISSUE THREAD

**Issue by GoteroDeBragas** [bazelbuild/bazel#4190]
I would like to know specifically and in clear english words what the flip tjis is

**Comment by jbduncan** [comment]
Bazel is, simply put, a build tool. In other words, it turns source code into software.

If you've ever heard of Make, Maven or Gradle, Bazel does the same thing as those tools.

The big difference between Bazel and other build tools is it can build software faster than other tools, because it uses clever techniques like caching, which allow it to avoid doing work whenever it can.

I hope this helps! :)

**Comment by jin** [comment]
Closing this issue since @jbduncan has provided a good answer :+1:
