### ISSUE TITLE
The environment variables set by bazel test doesn't match the document

### ISSUE THREAD

**Issue by mzhaom** [bazelbuild/bazel#422]
The "Initial conditions" section of http://bazel.io/docs/test-encyclopedia.html says:
TZ is US/Pacific, but it's actually "UTC"
And it doesn't set USER.

**Comment by kamalmarhubi** [comment]
UTC is preferable I think; perhaps just a doc bug? Not sure about USER.

**Comment by bsilver8192** [comment]
It also sets quite a few additional environment variables, and doesn't set several of the ones that are documented. For example, I know that it doesn't set LOGNAME and Kythe's Go rules rely on it setting XML_OUTPUT_FILE. Probably time for somebody to actually look through it and clean it up (it's non-trivial because the environment variables come from so many different places in the code).

**Comment by ulfjack** [comment]
I also stumbled over XML_OUTPUT_FILE not being documented, and I thought I had filed a bug for that, but apparently not. It's certainly going to stick around, as we're about to push our Java test runner, which will also rely on it.

The TZ entry needs to be fixed.

**Comment by helenalt** [comment]
This issue seems to have been fixed. Closing. Please re-open if there are still concerns.
