### ISSUE TITLE
genrule doesn't rebuild its dependencies completely

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#4223]
### Description of the problem / feature request / question:

When a genrule depends on a py_library rule, and the py_library depends on a cc_binary (through data attribute), then the genrule doesn't rebuild when the cc_binary changes.

### If possible, provide a minimal example to reproduce the problem:
```
$ cat BUILD
cc_binary(
  name = "lib_cc.so",
  srcs = ["lib.cc"],
  linkshared = 1,
)

py_library(
  name = "lib",
  srcs = ["lib.py"],
  data = [":lib_cc.so"],
)

genrule(
  name = "gen",
  srcs = [":lib"],
  outs = ["gen_file"],
  cmd = "touch $@",
)

$ bazel build :gen
$ echo "" >> lib.cc
$ bazel build :gen (no effect)
```

### Environment info
* Operating System:
All platforms

* Bazel version (output of `bazel info release`):
0.8.0, and probably all versions

My question is should genrule reexcute in such case? /cc, @lberki @ulfjack

**Comment by benjaminp** [comment]
`lib_cc.so` doesn't end up being an input to the genrule because it's simply in `lib`'s runfiles, and `lib`, being non-executable, doesn't have a runfiles tree. So, the lack of rebuilding is correct. Using a `py_library` in the `srcs` of a genrule doesn't seem too useful. If you want to build Python extensions, the Python rules need to gain some native dep support.

**Comment by ulfjack** [comment]
I agree with @benjaminp's assessment.

**Comment by meteorcloudy** [comment]
I also agree, thanks!

**Comment by dgoldstein0** [comment]
just dealt with a similar situation, the solution I came up with was to build a binary from the libraries and then include that binary in the `tools` of the genrule.  sort of hacky but it did the job.
