### ISSUE TITLE
Saving the remote cache from cache poisoning?

### ISSUE THREAD

**Issue by Utsav2** [bazelbuild/bazel#4276]
Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.

### Description of the problem / feature request / question:

We use a distributed remote cache to cache build and test outputs. In the remote cache protocol, there's two prefixes `ac/` and `cas/`. Outputs for both can be validated as `ac/` values should deserialize to action cache protos, and `cas/` outputs are content addressable. 

Let's say though there's a badly performing instance (perhaps due to running out of disk space), for which one of the action exits 0, but the output is malformed. If the wrong action proto gets uploaded to the cache, the cache will be poisoned. We've seen this in production.

Our particular cache setup makes this problem hard to solve, so I'm trying to find out if someone else has a good approach/or a good cache design that makes this problem easier to solve. 

We don't let the developer machines write to the cache, but this was a CI instance.

We've only seen this problem once, so it doesn't happen that often. But we still want a solution.

### Environment info
* Operating System:

* Bazel version (output of `bazel info release`):

* If `bazel info release` returns "development version" or "(@non-git)", please tell us what source tree you compiled Bazel from; git commit hash is appreciated (`git rev-parse HEAD`):

###  Have you found anything relevant by searching the web?
(e.g. [StackOverflow answers](http://stackoverflow.com/questions/tagged/bazel),
[GitHub issues](https://github.com/bazelbuild/bazel/issues),
email threads on the [`bazel-discuss`](https://groups.google.com/forum/#!forum/bazel-discuss) Google group)

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by laszlocsomor** [comment]
I think this is outside the scope of Bazel.
Paging @ola-rozenfeld who I believe may know more about this domain.

**Comment by ola-rozenfeld** [comment]
Yes, allowing machines to set your remote cache results is a big problem. CI-specific machines is better than dev ones, because you do have more control over them, but it's still not bulletproof.

Once the cache is poisoned, you can do things:
- run with remote_accept_cached=false will repopulate the entry, assuming that the problematic action usually succeeds
- if the problematic action usually fails, though, and the success was the poisoned outlier, that is a harder problem. You would need to clear the cache result manually. Currently, we do not have enough open-sourced tooling for that, although we have API work in progress.

In our implementation of remote build service we have not yet encountered this particular problem (a misbehaving succeeding action with malformed outputs that do get uploaded correctly into the CAS), but maybe that is because we use remote execution together with remote caching, and only the remote execution server is allowed to write the AC entry, after the action has succeeded on the worker. In our case, if the worker, say, runs out of disk, it is unlikely that the whole execution will succeed.

Hope that helps!

**Comment by Utsav2** [comment]
Thanks @ola-rozenfeld! That's extremely useful information
