### ISSUE TITLE
Test temp directory isn't cleaned up

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#431]
Reproduction:
$ bazel test //src/test/cpp:all --nocache_test_results
$ bazel test //src/test/cpp:all --nocache_test_results

The test fails when run the second time claiming that it can't create an empty file:
[ RUN      ] BlazeUtilTest.MakeDirectories
src/test/cpp/blaze_util_test.cc:205: Failure
Value of: CreateEmptyFile(non_dir)
  Actual: false
Expected: true
[  FAILED  ] BlazeUtilTest.MakeDirectories (1 ms)

When I print the path and then check it on my local machine, it turns out the output from the first test is still there, and so we fail to create a new file. At least, that last part is my theory. The open() man page doesn't say that it can fail in that case.

**Comment by damienmg** [comment]
I guess that's without sandboxing?

**Comment by ulfjack** [comment]
Default flags, I think it's with sandboxing

**Comment by philwo** [comment]
This can theoretically happen, because the TEST_TMPDIR directory is in the writable part of the sandbox (basically, the same as the output files) and we don't mount a tmpfs over it (yet). When the sandbox directory is not deleted fast enough after execution finishes, you can probably see the files still lying around. (We're talking about a few hundred milliseconds here in the normal case, though, unless something is blocking the removal of the directory). You should definitely not see even the empty sandbox directory after a few seconds, though.

A new test run should use a new sandbox directory anyway and not reuse the old one, so even if the old one isn't deleted fast enough, it shouldn't matter.

This is weird. I'll investigate today.

**Comment by philwo** [comment]
Can't reproduce on my machine using Bazel from HEAD with the sandbox enabled, even when running it in a loop with "while true".

As just discussed personally with ulfjack - it turned out that in the initial report Bazel ran on Mac, thus without sandboxing and the test doesn't properly clean up its stuff (and the StandaloneTestStrategy also doesn't seem to do so).
