### ISSUE TITLE
/src/test/py/bazel:bazel_windows_test broken

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/bazel#4318]
see, e.g., https://ci.bazel.io/blue/rest/organizations/jenkins/pipelines/bazel-tests/runs/1506/nodes/29/steps/415/log/?start=0

**Comment by laszlocsomor** [comment]
Looking.

**Comment by laszlocsomor** [comment]
Cannot repro yet, however I suspect https://github.com/bazelbuild/bazel/commit/8b3ba50246fed6ff13d70299fb039cc66be465c4.

**Comment by laszlocsomor** [comment]
Yes, confirmed the culprit. /cc @tomlu FYI

Meanwhile I noticed that https://github.com/bazelbuild/bazel/commit/6a4247b10f5cf040c1a7176498bef69c75b1b286 removed from `src/test/py/bazel/test_base.py` the logic that propagates `$BAZEL_VC` to the inner Bazel, and that was hindering my repro attempts. Also, I didn't have `c:/tools/msys64`, only `c:/msys64`, and needed a junction at the former path to point to the latter, because the MSYS GCC crosstool expects msys at the former path specifically.

**Comment by meteorcloudy** [comment]
I have a fix for it

**Comment by meteorcloudy** [comment]
It's because we have `/usr` in MSYS CROSSTOOL, and Bazel is unable to translate it after 8b3ba50246fed6ff13d70299fb039cc66be465c4
