### ISSUE TITLE
bazel sandbox failure when using dazel (permission denied due to symlink layout)

### ISSUE THREAD

**Issue by ensonic** [bazelbuild/bazel#4320]
### If possible, provide a minimal example to reproduce the problem:

This simple genrule failes when I run this using [dazel](https://github.com/nadirizr/dazel) (thats is bazel in docker to make deps hermetic).
```
genrule(
    name = "registration_app",
    srcs = ["registration/app.coffee"],
    outs = ["app.coffee"],
    cmd = "sed -e \"s%^url = \\\"http.*$$%url = \\\"http://www.$${PRJ_DOMAIN}\\\"%\" $< >$@",
)
```
```bash
> dazel build -s -j 1 //src/polymer:registration_app
...
SUBCOMMAND: # //src/polymer:registration_app [action 'Executing genrule //src/polymer:registration_app']
(cd /usr/local/google/home/ensonic/.cache/dazel/_dazel_ensonic/fa0b62599a6d69c63d52c0a39b895cb7/execroot/__main__ && \
  exec env - \
    PATH=/usr/lib/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PRJ_DOMAIN=demo.example.com \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; sed -e "s%^url = \"http.*$%url = \"http://www.${PRJ_DOMAIN}\"%" src/polymer/registration/app.coffee >bazel-out/local-opt/genfiles/src/polymer/app.coffee')
ERROR: /home/projects/demo/src/polymer/BUILD.bazel:57:1: Executing genrule //src/polymer:registration_app failed (Exit 2)
sed: can't read src/polymer/registration/app.coffee: Permission denied
Target //src/polymer:registration_app failed to build
```

If I change the genrule cmd:
```patch
-cmd = "sed -e \"s%^url = \\\"http.*$$%url = \\\"http://www.$${ROBCO_DOMAIN}\\\"%\" $< >$@",
+cmd = "id; ls -al $<; ls -al $$(readlink $<); touch $@",
```
we get this:
```shell
uid=0(root) gid=0(root) groups=0(root)
lrwxrwxrwx 1 root root 145 Dec 15 14:48 src/polymer/registration/app.coffee -> /usr/local/google/home/ensonic/.cache/dazel/_dazel_ensonic/fa0b62599a6d69c63d52c0a39b895cb7/execroot/__main__/src/polymer/registration/app.coffee
ls: cannot access /usr/local/google/home/ensonic/.cache/dazel/_dazel_ensonic/fa0b62599a6d69c63d52c0a39b895cb7/execroot/__main__/src/polymer/ registration/app.coffee: Permission denied
```

According to https://blog.bazel.build/2015/09/11/sandboxing.html all the /usr path are visible from the sandbox, but not /usr/local. Anyway the project root must be visible, right? If I set `local=1' in the genrul it build, but I would need to do this all over (is there a global param to disable the sandbox as a workaround for the time being?).

### Environment info
* Operating System:
linux (debian testing)

* Bazel version (output of `dazel info release`):
release 0.7.0
release 0.8.0
release 0.8.1

**Comment by aehlig** [comment]
Assigning to our sandbox expert for further triage.

**Comment by philwo** [comment]
> According to https://blog.bazel.build/2015/09/11/sandboxing.html all the /usr path are visible from the sandbox, but not /usr/local.

The way the sandbox works these days is like this:
- Create a new temporary directory below Bazel's output_base.
- For each input file, create a symlink inside the new temporary directory pointing to the actual file (in the workspace for source files or the output_base for intermediate artifacts).
- Run the action with the working directory set to this new temporary directory, instead of the actual execroot.
- If possible on the current platform (macOS and modern Linux, but not inside Docker, unless privileged mode is enabled for the container), restrict file system access of the running action so that it cannot write anywhere except to the temporary directory.
- Move the output files out of the temporary directory into the actual execroot.
- Delete the temporary directory.

We don't restrict the read part of anything in the sandbox - all files can be read.

**Comment by ensonic** [comment]
I've tried `--strategy=Genrule=standalone` but with that I get a lot of errors like
'''
declared output 'xxx'  was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
'''

**Comment by philwo** [comment]
Please re-open if this is still a problem.
