### ISSUE TITLE
does bazel support cloud or cluster compile?

### ISSUE THREAD

**Issue by startcode** [bazelbuild/bazel#4347]
Does bazel support cloud compile? Does anyone have the experience to make it possible?

**Comment by buchgr** [comment]
Yes it's being worked on under the term "remote execution": https://github.com/bazelbuild/bazel/tree/master/src/main/java/com/google/devtools/build/lib/remote

It's currently being worked on. Also check out https://github.com/bazelbuild/bazel-buildfarm for the remote execution backend.

**Comment by gongwei** [comment]
@buchgr which one is best practice for remote cache and remote execution? Document mentioned several ways including hazelCast, bazel remote worker. And there are https://github.com/bazelbuild/bazel-buildfarm and https://github.com/buchgr/bazel-remote on github and looks both of them are under you. Which one is fully tested and recommended?

**Comment by buchgr** [comment]
@gongwei 

Hey! I don't have experience with BuildFarm, so I can't comment on that. I know of people using Hazelcast and they are happy with it. I am also personally using https://github.com/buchgr/bazel-remote and I know others who do too. So both of them should work.

I personally would recommend using Google Cloud Storage (GCS) as a caching backend, because it's fully managed and scales automatically with your needs.

**Comment by ksnamburu** [comment]
Is the bazel remote compilation on NFS store is supported?

**Comment by buchgr** [comment]
No it's not.
