### ISSUE TITLE
Android assets in separate folder

### ISSUE THREAD

**Issue by XperielIndigo** [bazelbuild/bazel#435]
Hi,

I've got a common C++ codebase that I share between iOS and Android. As part of this codebase I have some shared resources (e.g. shaders).

From the documentation and my testing with `android_binary` it seems all resources have to live under one `assets` folder. Is there someway to use `filegroup`s in packages that are not named `assets`? And are separate from each other? Is there some other option I'm not seeing that would allow me to keep my shared resources in a shared location without having to duplicate them?

Cheers
Indigo

**Comment by kchodorow** [comment]
@ahumesky feel free to reassign if this isn't related to what you're working on.

**Comment by aj-michael** [comment]
You can create an `android_library` target for each assets folder. We don't allow multiple asset directories for a target because we use the relative paths to the assets from the `assets_dir` to determine where to put them in the APK. In theory, `android_binary` could instead take in a map from `assets_dir` to list of assets, but I think its much simpler just to create multiple `android_libraries` and have the `android_binary` depend on all of them.
