### ISSUE TITLE
new_http_archive fails with "no such package" when using `build_file` argument

### ISSUE THREAD

**Issue by jschaf** [bazelbuild/bazel#4371]
### Description of the problem / feature request / question:

Using `new_http_archive` with a `build_file` argument fails.  However, if I clone the repo and use it locally, it succeeds.

```
ERROR: /home/jschaf/bazels/error-reporting/BUILD:1:1: no such package '@com_github_square_okio//': Unable to load package for //okio_build.bzl: not found. and referenced by '//:okio'
ERROR: Analysis of target '//:okio' failed; build aborted: no such package '@com_github_square_okio//': Unable to load package for //okio_build.bzl: not found.
```

### If possible, provide a minimal example to reproduce the problem:

**Non-working example:** https://github.com/jschaf/error-reporting
```
git clone git@github.com:jschaf/error-reporting.git
cd error-reporting
bazel build :okio
```

Additionally here's a **working example**, using the same BUILD file as the non-working example: https://github.com/jschaf/okio
```
git clone git@github.com:jschaf/okio.git
cd okio
bazel build :okio
```

### Environment info
* Operating System:

Linux jschaf 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

* Bazel version (output of `bazel info release`):
release 0.9.0

###  Have you found anything relevant by searching the web?

No luck.  I tried `bazel clean --expunge` and `bazel shutdown`

### Anything else, information or logs or outputs that would be helpful?
(If they are large, please upload as attachment or provide link).

**Comment by edbaunton** [comment]
The problem is that you are referring to the local build file using `//`. Additionally your glob wasn't working because there is an additional dir in the way that was throwing off the glob so adding `strip_prefix` should solve that problem (might have been throwing you off earlier?)
You can see in other examples that build files are best referred to using the name https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE#L45

Fixed your issue with: https://github.com/jschaf/error-reporting/pull/1

**Comment by jschaf** [comment]
Oh, thank you.  So, the reason the `//` reference wouldn't work is because bazel is executing it in another workspace.  Is that right?

**Comment by edbaunton** [comment]
I think if you want to use a label like that you need to use `//:okio_build.bzl`.

There is a good rundown of the syntax at `bazel help target-syntax`
