### ISSUE TITLE
Bazel installer failed to produce bazel binary

### ISSUE THREAD

**Issue by agoulti** [bazelbuild/bazel#4390]
### Description of the problem / feature request:

Bazel installer failed to produce bazel binary

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The same script usually works, but at some point it failed for unknown reason.

On 2018/01/05 around 00:37 EST, we obtained a nightly bazel release as follows:

`curl --compressed -L https://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/bazel/job/nightly/lastSuccessfulBuild/artifact/node=linux-x86_64/variation=/bazel--installer-linux-x86_64.sh -o <redacted>/bazel--installer-linux-x86_64.sh`

We then ran the script:
`<redacted>/bazel--installer-linux-x86_64.sh --prefix=<redacted>/foundry-demo-ascit.114572848`

It gave the following output:

```
Bazel installer
---------------

Bazel is bundled with software licensed under the GPLv2 with Classpath exception.
You can find the sources next to the installer on our release page:
   https://github.com/bazelbuild/bazel/releases

# Binary package at HEAD (@55f1e58)
   - [Commit](https://github.com/bazelbuild/bazel/commit/55f1e58)
Uncompressing...chmod: cannot access `<redacted>/lib/bazel/bin/bazel': No such file or directory
```

When we inspected the directories, we found that the directory `<redacted>/lib/bazel/bin/` existed but was empty. Re-running the script succeeded.

### What operating system are you running Bazel on?

Goobuntu

### What's the output of `bazel info release`?

N/A

**Comment by jin** [comment]
Is this a one time issue or has it happened repeatedly?

**Comment by agoulti** [comment]
One time so far

**Comment by agoulti** [comment]
We're seeing this repeat. E.g., sponge/4a1b1621-ae8d-4396-b371-45c675373cbc

Is there any additional information we could collect to help diagnose this?

**Comment by jin** [comment]
@philwo, do you mind taking a look at this?

**Comment by philwo** [comment]
@agoulti I can think of three possible cases:

1) The installer somehow doesn't contain a ZIP file that contains a bazel binary and thus it happily does its job, but doesn't actually extract any files and then chmod fails.
2) The installer is corrupt, but I think unzip would complain then during unzip.
3) Your environment is somehow strange and the Bazel binary doesn't exist immediately after unzip created it.

I think we can rule out 2) because it would print an error message. We can probably also rule out 1), because I just vetted all nightly installers stored on the Jenkins master and made sure that they contain the right files.

The installer is just a shell script with an attached ZIP file - you can open it in a text editor and see what it does, or run "unzip -l bazel--installer-linux-x86_64.sh" on it to see the files it contains. Could you debug a bit locally when this happens next time? If you'd like to improve the installer to have better logging or error handling, a CL or pull request would be very welcome :)

**Comment by agoulti** [comment]
We are no longer using the installer, so I wasn't able to check if it would reproduce again.
