### ISSUE TITLE
potential overlfow in 0.9.0

### ISSUE THREAD

**Issue by plinnell** [bazelbuild/bazel#4394]
openSUSE has OBS, which has a lightweight overflow checker it fails the build with the following log:

[  585s] ... running 02-check-gcc-output
[  585s] ... testing for serious compiler warnings
[  585s]     (using /usr/lib/build/checks-data/check_gcc_output)
[  585s]     (using //.build.log)
[  586s] 
[  586s] I: A function overflows or underflows an array access. This could be a real error,
[  586s]    but occasionaly this condition is also misdetected due to loop unrolling or strange pointer
[  586s]    handling. So this is warning only, please review.
[  586s] W: bazel arraysubscript ./src/tools/singlejar/zip_headers.h:146
[  586s] 
[  586s] I: Program returns random data in a function
[  586s] E: bazel no-return-in-nonvoid-function src/main/cpp/blaze_util_posix.cc:402
[  586s] 
[  586s] I: Program returns random data in a function
[  586s] E: bazel no-return-in-nonvoid-function src/main/cpp/blaze_util_posix.cc:402
[  586s] 
[  586s] lamb57 failed "build bazel.spec" at Sun Jan  7 06:18:06 UTC 2018.
[  586s] 
[  586s] ### VM INTERACTION START ###
[  589s] [  581.575227] reboot: Power down

Full log here:  https://build.opensuse.org/package/live_build_log/devel:tools:building/bazel/openSUSE_Leap_42.3/x86_64

This occurs on all versions enabled in the repo: https://build.opensuse.org/package/show/devel:tools:building/bazel

0.8.1 did not have this issue.

**Comment by jin** [comment]
It looks like the build failed because of the no-return-in-nonvoid-function error instead of overflow warning?

**Comment by katre** [comment]
I don't understand what the error from OBS is saying. It looks like it has found two problems:

1. https://source.bazel.build/bazel/+/master:src/tools/singlejar/zip_headers.h;l=146?q=src%2Ftools%2Fsinglejar%2Fzip_headers.h doesn't do bounds testing before dereferencing the array.
2. https://source.bazel.build/bazel/+/master:src/main/cpp/blaze_util_posix.cc;l=341?q=src%2Fmain%2Fcpp%2Fblaze_util_posix.cc returns -1 for error.

I'm not sure why OBS characterizes 2 as "Program returns random data in a function". Can we get more clarification from the reporter about what is meant by "random data" and why this is bad?

For 1 we should either add a bounds check or verify that it can't be used to overflow.

**Comment by lberki** [comment]
I don't understand either -- `ExecuteDaemon()` does have a return statement on every code path and its return value is not used to index into anything. Peter?

**Comment by ivucica** [comment]
I think this is coming from GCC: [check_gcc_output source code](https://github.com/openSUSE/post-build-checks/blob/8f470bcade61e546593c00d2c78365f5ffdd69b7/checks-data/check_gcc_output)

Having it say that the problem is on line 402 is weird, except [it seems to be the end of the function in 0.9.0](https://source.bazel.build/bazel/+/ddd5ac16aeffa6c4693c348f73e7365240b1abc5:src/main/cpp/blaze_util_posix.cc;l=402?q=src%2Fmain%2Fcpp%2Fblaze_util_posix.cc) (sidenote: codesearch doesn't contain tags except 0.2.1 for some reason? and the commit of the release itself is unavailable, so I picked the baseline)

But, the thing might be misinterpreting this codebranch (taken from master):

```
    pid_t server_pid;
    ReadFromFdWithRetryEintr(fds[0], &server_pid, sizeof server_pid,
                        "cannot read server PID from server");
    string pid_file = blaze_util::JoinPath(server_dir, kServerPidFile);
    if (!blaze_util::WriteFile(ToString(server_pid), pid_file)) {
      pdie(blaze_exit_code::INTERNAL_ERROR, "cannot write PID file");
      return -1;
    }

    WriteSystemSpecificProcessIdentifier(server_dir, server_pid);
    char dummy = 'a';
    WriteToFdWithRetryEintr(fds[0], &dummy, 1,
                       "cannot notify server about having written PID file");
    *server_startup = new SocketBlazeServerStartup(fds[0]);
    return server_pid;
```

Perhaps the service/the compiler believes `server_pid` might end up uninitialized after `ReadFromFdWithRetryEintr`, even though `DieAfterFork` is called in case of any failure. Maybe a defensive initialization to a zero is in order (`pid_t server_pid = 0;`)?

More likely however: looking at the 0.9.0 version, there is no `return -1` after the first `pdie()`. So the compiler might not believe that `pdie()` is program termination?

**Comment by ivucica** [comment]
(i.e. perhaps OP should try this with the latest master?)

**Comment by lberki** [comment]
I think the most plausible explanation is that the linter doesn't know that `server_pid` is set by the `ReadFromFdWithRetryEintr()` call. Even though there is a `return` statement missing after the first `pdie()`, the function as a whole still returns things.

I'll initialize `server_pid` to zero and assume that that was the problem.
