### ISSUE TITLE
bazel shutdown should have an option to kill all bazel workers including workers from other workspaces

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/bazel#4505]
### Description of the problem / feature request:

I have a large number of java processes spawned by bazel hanging around when I don't need them. I have several workspaces, and bazel shutdown stops workers only from the current workspace.

### Feature requests: what underlying problem are you trying to solve with this feature?

I want to free resources occupied by them. It would be nice to introduce additional flag for shutdown like --shutdown-all

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Launch docker in 2 separate workspaces. Go to some directory not under the workspaces. Type bazel shutdown. Workers won't be shut down.

### What operating system are you running Bazel on?

Mac OS

### What's the output of `bazel info release`?

release 0.9.0-homebrew

**Comment by philwo** [comment]
Unfortunately, each Bazel server only knows about its own workspace and doesn't have a mechanism to know or signal other running Bazel servers / workers on the system.

**Comment by philwo** [comment]
Closing as infeasible.

**Comment by solomatov** [comment]
@philwo What do you think about using IPC to signal that all workers in specified workspace should shut down? I think, it's absolutely possible.

**Comment by philwo** [comment]
@solomatov I agree that it should be possible. We'd need some kind of discovery mechanism so that Bazel servers are aware of other running Bazel servers and then a communication mechanism so that they can signal each other. This might also be interesting to better constrain overall resource usage in case someone is running multiple Bazel builds on the same machine. However, it would also add a lot of complexity to Bazel. I'm not sure it's really worth it.

Could you maybe just use `killall bazel`? This essentially does the same as a "bazel shutdown". It might currently not work due to process names not being exactly `bazel`, but we could fix that. What do you think?

**Comment by solomatov** [comment]
@philwo That's what I usually do as a workaround. But I am concerned about breaking caches or other persistent data structures by bazel.
