### ISSUE TITLE
FR: Add option to make resource ids final in android_library

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/bazel#4528]
### Description of the problem / feature request:

Make this controllable through a flag on android_library: https://github.com/bazelbuild/bazel/blob/master/src/tools/android/java/com/google/devtools/build/android/AndroidResourceProcessor.java#L427

### Feature requests: what underlying problem are you trying to solve with this feature?

If the values are not final, they can't be used in Java `switch` or Scala `match`.

**Comment by meteorcloudy** [comment]
Hi, @aj-michael! Can you take a look?

**Comment by aj-michael** [comment]
Hi @iphydf - I don't think we will do this. There is a fundamental reason that they are intentionally not final. Say you have an android_binary, A, that depends on two android_libraries, B and C. Suppose that we generated final resource identifiers in B and C, and that each one of them has a resource that is assigned to "4". Since the java compiler is smart, it may inline "4" whereever it sees references to these resources in B or C. Since Android resources are currently not name spaced, when we build A we have to choose either B's resource 4 or C's resource 4 to put in the APK. Then, at runtime either B or C would misbehave because it's resource has changed out from under it.

Bazel solves this problem by leaving the IDs as non-final until we get to an android_binary. The android_binary reassigns all of the resource IDs so that there are no conflicts between libraries. Since the resource IDs were not final in the library, the java compiler will not have inlined them.

**Comment by iphydf** [comment]
Ok, this makes sense. Thanks for clarifying.
