### ISSUE TITLE
How would you recommend to describe DLL with some header files?

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#4560]
### Description of the problem / feature request:

Hi.

As I can see, generating DLLs is implemented using `cc_binary()` rules:
https://github.com/bazelbuild/bazel/blob/master/examples/windows/dll/BUILD

Sometimes we ship these libraries along with some definitions in headers like custom types and signatures of functions. Unfortunately, `cc_binary()` does not allow to specify `hdrs` to cleanly consume these headers by users.

I could describe these headers by `exports_files()` though, but that is not much convenient. I guess one need to move DLL functionality to `cc_library()` because as a matter of fact DLLs are libraries.

Please feel free to prove me wrong.

**Comment by meteorcloudy** [comment]
@excitoon Actually, we are able to build DLL from `cc_library`, but there are two caveats:

1. The extension is `.so` instead of `.dll`, I'm planing to fix the file extensions on Windows in next quarter.
2. Due to lack of ability to build [C++ transitive library](https://docs.google.com/document/d/1d4SPgVX-OTCiEK_l24DNWiFlT14XS5ZxD7XhttFbvrI/edit#heading=h.jwrigiapdkr2). The DLL only contains code from its own `srcs`, all of its dependencies from `deps` are required to be built as DLL as well so that it can link to them. You can use `windows_export_all_symbols` (mentioned in #4561) to help you export symbols.

If you want to build a DLL containing all of its dependencies, and you want other cc rules to depend on this DLL with its header files, you can do it with the help of [cc_import ](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import)rule:
```
cc_binary(
  name = "mylib.dll",
  srcs = ["mylib.cc"],
  deps = ...,
)

filegroup(
    name = "mylib_import_lib_file",
    srcs = [":mylib.dll"],
    output_group = "interface_library",
)

cc_import(
  name = "mylib",
  hdrs = ["mylib.h"],
  interface_library = ":mylib_import_lib_file",
  shared_library = "mylib.dll",
)
```
This way, other cc rules can depend on `//:mylib`, the import library `mylib.ifso` will be used for linking, and `mylib.dll` will be copied to your binary directory so that it can be loaded at runtime.

**Comment by excitoon** [comment]
Thank you very much.

**Comment by excitoon** [comment]
It's resolved for me, I don't know if I am to close this.
