### ISSUE TITLE
Build statistics report

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#4569]
### Description of the problem / feature request:

Hi.

How should I find out how many targets were built and how many targets failed/did not build (specifically, when using `-k` flag)?

Also, see https://github.com/bazelbuild/bazel/issues/2846.

###  Have you found anything relevant by searching the web?

Nothing.

**Comment by meisterT** [comment]
@agoulti is working on printing a summary after a build.

**Comment by excitoon** [comment]
Hi @agoulti .

How are you doing?

Kind regards,
Vladimir.

**Comment by agoulti** [comment]
Hi Vladimir,

Thanks for pinging. I didn't realize I was assigned here.
The bug Tobias mentioned was fixed, and Bazel now prints a summary of spawned processes.
That is different from what you seem to need, since it's not by target, and we do not include failures.

Sorry for having you wait so long, it seems there has been a miscommunication about what needs to be done.

I think you should be able to do what you need using Build Event Protocol: https://docs.bazel.build/versions/master/build-event-protocol.html

You're looking for [target_completed](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/buildeventstream/proto/build_event_stream.proto;l=210?q=target_completed) messages. 

A successful execution looks something like this:
```
event {
id {
  target_completed {
    label: "//:uid"
    ...
  }
}
completed {
  success: true
  ...
}
}
```

Note that the label will give you the target you are looking for, and completed.success will be true if the execution succeeded (note that false is the default value in a proto, so if "success:" is absent from the text representation, assume false).


Here's an increadibly hacky and fragile proof of concept:
bazel build -k --build_event_text_file=output.log //:all

grep "(?s)\nid {\n *target_completed {\n * label.*?(\n\n|children {\n)" -Pzo  output.log > out2.log

To get the list of targets:
cat -v out2.log | egrep "(label:|success:)"

You'll see the labels of targets, followed by "success: true" for the ones that succeeded (false is the default in a proto, so "success: false" is not written).


I would advice using build_event_binary_file or build_event_json_file and do proper parsing.

My script above relies on the exact way the proto is serialized, which is not guaranteed to be stable (e.g., things may be printed in a different order with different whitespace etc.). Also note that I had to exclude "children" subsection since it contains other messages that have a "label" field.

**Comment by agoulti** [comment]
@meisterT , could you sanity check my answer and tell us if there's any corner cases I might be missing?
