### ISSUE TITLE
BEP: Add a config option for results base URL (feature request)

### ISSUE THREAD

**Issue by davidstanke** [bazelbuild/bazel#4628]
When streaming results to a BEP endpoint, we should notify the user as to where they can view those results. (Currently, the user has to manually construct the URL from the invocation ID reported in Bazel CLI and a base URL of the BEP server.)

**Please add a flag:** `--results_url_base`

...this will be used like: `bazel build //... --results_url_base=https://example.com/results/invocations/`

when this flag is present, Bazel will print to the log (as soon as the invocation ID is known:)
`streaming results to ${results_url_base}${invocation_id}`

e.g. `streaming results to https://example.com/results/invocations/XXXX-YYYY-ZZZZ`

**Comment by davidstanke** [comment]
We should expect that most users will want to specify this flag in a .bazelrc file

**Comment by aehlig** [comment]
Over to @buchgr who wrote the current notification about streaming target and identifier.

**Comment by buchgr** [comment]
Hi Dave,

I am not convinced that a flag is the right way to go about this. I think instead we should extend the BES protocol to be able to return a URL that the user can look at. This would be a much nicer user experience in my opinion. What do you think?

**Comment by willsc79** [comment]
Ya I agree that would be ideal - but we discussed this idea with the BES team and they were not on board with it. BES does not know what the URL should be since it's up to the post processors of the BES data to generate results from it. For example, there could be multiple URLs or none depending on what's done with the data once it's uploaded to BES.

I think having as a convenience the ability to provide this via flag is the only path forward for now.

**Comment by davidstanke** [comment]
Thanks willsc79 for the background. @buchgr can we proceed to implement the flag?

**Comment by davidstanke** [comment]
Ping?

**Comment by buchgr** [comment]
I apologize it slipped through my radar. Will implement asap.
