### ISSUE TITLE
android_import_external

### ISSUE THREAD

**Issue by ronshapiro** [bazelbuild/bazel#4654]
### Description of the problem / feature request:

`java_import_external` is awesome. We should add an Android equivalent for `.aar` files.

###  Have you found anything relevant by searching the web?

Somewhat related: https://groups.google.com/d/msg/bazel-discuss/t0BOBD9UYn0/1YEvlZQHAwAJ

**Comment by jin** [comment]
There's [`aar_import`](https://docs.bazel.build/versions/master/be/android.html) and [`maven_aar`](https://github.com/bazelbuild/bazel/issues/561#issuecomment-259458533). `maven_aar` is unfortunately not documented yet. It also shells out to a local `mvn` install.

**Comment by jin** [comment]
cc @aj-michael

**Comment by jin** [comment]
It doesn't seem too nontrivial to adapt the `java_import_external` implementation to use `aar_import`.

**Comment by ittaiz** [comment]
I’d recommend considering not adopting the java_import_external API which
is somewhat low-level (for example no attribute for coordinates) but only
taking the implementation (maybe exposing part of the current
implementation for reuse) and thinking of a maven_import_external rule
which also supports aar. You can see the “design a publish story” for some
more thoughts on the subject

**Comment by jin** [comment]
I've implemented `aar_import_external` in https://github.com/bazelbuild/gmaven_rules/blob/master/import_external.bzl. I'll see how I can bring this upstream to either Bazel or the upcoming Skylark home at https://github.com/bazelbuild/rules_android

The use case is specific to gmaven_rules because gmaven_rules resolves and generates targets automatically. I agree with @ittaiz that it's low-level and that can be an intermediary abstraction to resolve coordinates to URLs. In gmaven_rules, there's a [`gmaven_artifact` macro](https://github.com/bazelbuild/gmaven_rules#usage-instructions) that converts an artifact coordinate to the generated target na,e.

**Comment by ittaiz** [comment]
My colleague @natansil also started work on this direction here (
https://github.com/bazelbuild/rules_scala/pull/473) and we'll probably send
upstream the majority of it.
There's also someone interested in working on maven_import which is like
java_import but will expose a MavenCoordinates provider for consumption

**Comment by jart** [comment]
I recommend using `java_import_external` with verbatim URLs. We need to be able to grep URLs (see [GitHub BigQuery](https://cloud.google.com/bigquery/public-data/github) dataset) to offer high availability mirroring via mirror.bazel.build. Folks who do things like `https://%s` or `maven:abbreviation:v1` will miss out on those reliability and performance benefits. Yes it makes your WORKSPACE file ugly, but it's worth it.
