### ISSUE TITLE
android_device osx support

### ISSUE THREAD

**Issue by codesuki** [bazelbuild/bazel#4679]
After playing around with this rule it seems only linux is supported.
Is there a timeline for osx support?

**Comment by jin** [comment]
There isn't a timeline for macOS support. The Linux constraint, AFAIK, is due to a dependency of `android_device` called [unified launcher](https://github.com/bazelbuild/bazel/blob/af79eb49df9fb9a4b5a00194e5068a6cfedf12ae/tools/android/emulator/BUILD.tools#L45), which is hosted in [android-testing-support-library](https://github.com/google/android-testing-support-library). I have opened https://github.com/google/android-testing-support-library/issues/39 for this feature request.

**Comment by codesuki** [comment]
Thanks for the info and opening an issue in the right place!
I didn't confirm yet but at least it seems to work with manually started emulators, too.
Looking forward to the `android_instrumentation_test` rule to run unit tests on the device.

**Comment by jin** [comment]
Downgrading to P4 as there's a rewrite of the `android_device` rule happening, and the launcher will also be rewritten with multiplatform support as a goal.

**Comment by cgruber** [comment]
Is there a github issue for the android rules rewrites that can be referenced here, for tracking? (and more generally we can subscribe to)

**Comment by jin** [comment]
https://github.com/bazelbuild/bazel/issues/5354 (cc @ahumesky)

**Comment by jgavris** [comment]
cc @larryng
