### ISSUE TITLE
Please allow use of providers in output calculating functions

### ISSUE THREAD

**Issue by DmytroLapshyn** [bazelbuild/bazel#4708]
### Description of the problem / feature request:

I would like to have a possibility to access provider-supplied data in a function that dynamically calculates outputs for a rule (i.e. in a function that can be specified instead of a hard-coded dictionary enumerating all the rule outputs)

### Feature requests: what underlying problem are you trying to solve with this feature?

Use information available from the providers to generate a proper list of rule's outputs.

At a higher level, this is an attempt to closely follow the DRY rule and pass a certain tag that should appear in the file name of the final output (but this tag is also required elsewhere in the build sequence) only once and thus avoid specifying the tag in subsequent rules's attributes.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Define a rule that returns a custom provider with some data.
Define a rule that uses a function to compose the dictionary of outputs.
Make the first rule one of the inputs to the second rule.
Try to access the provider data generated by the first rule from the outputs-calculating function  

The latter would fail with an error message reading `type 'Label' has no operator [](Provider)`

**NB**: the very same provider data are perfectly accessible in the rule implementation function so this does not appear to be a faulty provider setup

### What operating system are you running Bazel on?

macOS Sierra

### What's the output of `bazel info release`?

release 0.10.1-homebrew

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A - see above

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

Not sure if that would help as this is a private GitHub repo

###  Have you found anything relevant by searching the web?

Unfortunately, nothing relevant 😞

**Comment by brandjon** [comment]
It's not feasible to make the outputs arg to rule() (whether it's a dict or a function that computes a dict) able to inspect provider values. This is because this map is for predeclared outputs -- outputs that have labels that are known at loading time, before the providers are computed.

You can still generate output files from your provider data, it's just that they can't be predeclared. Rather, you'd have to do it in your rule's implementation function, using ctx.actions.declare_file() instead of ctx.outputs. These files can be passed to other rules by putting them in providers, but they can't be referred to by a label.

For more information, see

    https://docs.bazel.build/versions/master/skylark/rules.html#files

which was recently updated.

**Comment by dmytrol** [comment]
Thanks! For others who might stumble upon this discussion: make sure you are returning the DefaultOutput provider from your rule if the rule has no predeclared outputs but only generated ones. Otherwise, the rule won't be built if this is a "terminal" rule in your rule chain (i.e. there are no other rules consuming the generated outputs)

**Comment by brandjon** [comment]
See [here](https://docs.bazel.build/versions/master/skylark/rules.html#requesting-output-files) for more on declaring default outputs via the DefaultInfo provider. (This too was recently rewritten so no worries if you haven't seen it.)

**Comment by dmytrol** [comment]
Thanks Jon - that was exactly _the_ documentation update that saved my day!
