### ISSUE TITLE
Missing VCRUNTIME140.dll on Windows 7 SP1 -- document dll requirement

### ISSUE THREAD

**Issue by hatstand** [bazelbuild/bazel#4740]
### Description of the problem / feature request:

Cannot run bazel on Windows 7 Enterprise SP1 without admin due to missing VCRUNTIME140.dll

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run released bazel.exe (v0.11.0) on a fresh Windows 7 Enterprise SP1 install.

### What operating system are you running Bazel on?

Windows 7 Enterprise SP1

###  Have you found anything relevant by searching the web?

Perhaps bazel could statically link the VC redistributable? Or ship it as part of the released zip?

### Any other information, logs, or outputs that you want to share?

Without admin access, Microsoft's redistributable installer cannot be used either.

**Comment by laszlocsomor** [comment]
Thanks for reporting this issue!

I think this is working as intended, because:
- Bazel needs additional software to run anyway (MSYS shell, Python, VC++, etc.)
- Bazel needs a C++ compiler (VC++ on Windows) and I don't see that requirement going away any time soon
- installing VC 2013 or newer will install runtime DLLs for all VC versions

I'm not 100% sure on the last point, but I believe it is true. If you know otherwise, please let me know!

For these reasons I believe it's OK not to statically link to this DLL, so I think everything is working as intended.

**Comment by hatstand** [comment]
Perhaps the documentation just needs updating to include VC++ as a hard requirement then? [According to the current docs](https://docs.bazel.build/versions/master/windows.html), it's only required if you want support for C++ rules.

**Comment by laszlocsomor** [comment]
I agree, that's a fair point. Let me repurpose the bug for that!

**Comment by laszlocsomor** [comment]
@hatstand : Would you be willing to contribute a PR to document this?

**Comment by hatstand** [comment]
Sure. No promises on when though.

**Comment by laszlocsomor** [comment]
Thanks! If you start working on it, please ping this thread, so anyone else who may also work on it won't step on your toes.

**Comment by laszlocsomor** [comment]
Marking it P4 to indicate that I hope for external (non-Bazel-core-team) help.

**Comment by hatstand** [comment]
https://github.com/bazelbuild/bazel/pull/4768
