### ISSUE TITLE
external/ in output root should be readonly

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#480]
since we don't notice changes in the external/ tree, it should probably made chmod -w

**Comment by kchodorow** [comment]
There's actually a change in progress to make changes in external/ noticed.  But more of it certainly could be -w anyway.

**Comment by benjaminp** [comment]
It would be a great if directories and files in `external/` were all read-only. A nasty sequence of events I've witnessed several times goes like this:
1. A developer writes a `new_http_repository` rule to fetch a tarball and uses a broad rule like `filegroup(srcs=glob(['**/*'])` in the associated `BUILD` file, the intent being to capture the entire contents of the tarball.
2. An action writes some files into the unpacked tarball's directory in `external/`. (Python `pyc` files, for example.)
3. The extra files are picked up by the `glob` and poison all subsequent incremental builds (even sandboxed ones). The only way to fix the problem is then to use the `clean --expunge` hammer.

**Comment by alexanderlobov** [comment]
I had the exact issue recently: because of an external target that changes files inside its directory a test restarts every time.

It would be also nice to improve bazel's diagnostics facilities. Now it is unclear what file has changed when a test is restarted.  See also https://stackoverflow.com/questions/58454610/explain-the-reason-of-a-test-restart-in-bazel

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
