### ISSUE TITLE
//src/test/shell/bazel:bazel_determinism_test is given too short a timeout on macOS

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#4849]
https://buildkite.com/bazel/bazel-bazel/builds/711#e8dcaba1-ff40-423c-b766-f2f567e7e9a5

See also https://github.com/bazelbuild/bazel/issues/4770

**Comment by buchgr** [comment]
I have temporarily disabled bazel determinism test on macOS

**Comment by mhlopko** [comment]
Friendly ping, @c-parsons @rupertks, deprioritizing since it's not a breakage when the test is disabled :)

**Comment by rupertks** [comment]
From the logs the test doesn't actually seem broken, just that it takes a long time and is timing out. 

Normally I would suggest we increase the timeout, but the timeout is already set to 'eternal'. 

Specifically, the test builds bazel, uses the built bazel to build bazel again, and compares that the outputs (e.g. bazel-bin/*) for both builds were the same. So it's gonna be slow. 

It looks like both builds complete in the retries, but only one build completes in the first attempt. 

Is the test actually being given 3600 seconds (timeout=eternal) to run? From the logs it looks like it is only given 914 seconds instead of 3600 seconds... ?

**Comment by rupertks** [comment]
What was the resolution here? Did we remove the --test_timeout=900 override to allow 'eternal' timeouts again... ?

**Comment by buchgr** [comment]
No, the test has been completely disabled on macOS for the past month because of https://github.com/bazelbuild/bazel/issues/4770. Once that has been fixed, we can enable it again

**Comment by rupertks** [comment]
Do you know if this test was also failing in our CI, before we disabled it?

My impression from the log is that it was timing out, but not necessarily failing.

**Comment by buchgr** [comment]
@rupertks yes it was definitely failing, although I don't have a log for you to proof that :).
