### ISSUE TITLE
CI script misses many border cases

### ISSUE THREAD

**Issue by ekuefler** [bazelbuild/bazel#485]
The script at https://github.com/bazelbuild/bazel/blob/master/scripts/ci/ci.sh is useful for doing some basic detection of what tests need to be run for a set of changed files, but it fails on enough common cases that it's difficult to rely on for a real project. Here are some of the problems I've encountered so far, each of which have led to broken builds for me at one time or another:

 * Doesn't detect changes to BUILD files, since BUILD files aren't actually a source of a rule
 * Doesn't detect changes to the WORKSPACE file for the same reason
 * Doesn't detect changes to .bzl files for the same reason
 * Doesn't notice flag changes, such as when caused by changes to tools/bazel.rc
 * Doesn't see file deletions since bazel query doesn't know anything about deleted files.

I could file bugs for these issues separately but I'm doing it as one since I suspect it might be better to rethink the approach than to incrementally hack around issues in the script. As I understand it, the logic for deciding what to run should be exactly the same as deciding when tests can be cached vs. rerun, which Bazel already has built in. So exposing that mechanism or giving some deeper control over the test cache might easily give the correct behavior here.

For example, adding a command to "mark all tests as passed" without actually running them would allow a CI server to work very easily by doing the following for each change:

  1. checkout master
  2. mark all tests as passed
  3. patch in the change
  4. run all tests (which would cause unaffected tests to be skipped as cached)

Thoughts on this?

**Comment by ulfjack** [comment]
If you can keep a running bazel server, then the best thing to do is to
just checkout the latest changes and run "bazel test //...". If you can't
keep the state around, for whatever reason, then it's more complicated. We
don't mark tests as passed in bazel, as such. Tests are actions like
everything else, so we use the action cache to determine if we need to
rerun them, but that's hard to fake. In addition, when you run bazel test
//..., we'll also build all non-test targets, so I'm not sure that this
would save a lot of time.

That said, we certainly have plans to improve the situation. I agree that
Bazel has all of the necessary information, in principle, but we need to
figure out where to store that. Depending on the scenario, a remote cache
might be a bigger improvement than a local cache, which will probably be a
better than a cold start.

**Comment by philwo** [comment]
Ulf: Could we simply let passing tests generate an output artifact saved to disk that serves as a marker? If the marker is there next time Bazel starts up, it can deduce that the test passed before and if the inputs haven't changed, it doesn't have to rerun. If its missing, the test was never run or failed the last time, so it has to rerun it.

**Comment by ulfjack** [comment]
The action cache is supposed to do that, as long as you don't run "bazel
clean".

**Comment by ekuefler** [comment]
Will the remote cache also cache test results between machines? That would probably do it - I'm really looking forward to remote caching.

Keeping a long-running server isn't viable for two reasons. For one, we run several build servers in docker containers distributed across a cluster, so the server that picks up the build is nondeterministic. We do get some incidental caching of lower-level artifacts that were built on the previous run, but there tends to be enough change that we don't get a whole lot of test caching. The bigger problem is that the servers are mostly used to test unrelated pull requests, so the previous run will likely be against an arbitrary change rather than a golden master. What I really want is to run tests that have changed relative to master rather than relative to the last build.

Maybe there would be a way to hack this together by copying a golden workspace / cache directories around and restoring from it, but that would be pretty tricky. Sounds like remote caching might naturally handle this though. Do you see remote caching obsoleting the CI script?

**Comment by damienmg** [comment]
Some quick points

- ci.sh is an external contribution and should probably use the [buildfiles](http://bazel.io/docs/query.html#buildfiles) operator in query.
- distributed caching should cache test results too. The set-up you describe definitely fall into the kind of setup to be addressed by distributed caching.
- No hack will handle correctly multiple bazel running at the same time if you don't rely on a distributed cache.

**Comment by ulfjack** [comment]
A remote cache would indeed help, but it can't guarantee cache hits. It
would be better to use the Skyframe information that Bazel already has to
determine which tests to run, and not even attempt any of the others.

I'm thinking something like this:
1. checkout master (does not have to be a fresh checkout, updating to head
should work just fine, see below)
2. run "bazel build --nobuild //..." to initialize the Skyframe dependency
graph
3. apply patch
4. query bazel to find all affected tests
5. run bazel test with just those tests

Step 4 is tricky - we haven't run a build before, so we need to fake it. As
long as Bazel doesn't discover any new files during execution (which it
shouldn't, and sandboxing helps ensure this), it should be doable since the
data is all in Skyframe. This might even be useful internally, though we do
discover files during execution in Blaze.

Note that steps 2 and 5 will be faster if Bazel has some information about
the workspace in memory already, and it should be correct regardless of
which commit was in the workspace before (assuming we don't have any
remaining incremental correctness bugs in Bazel). May require additional
work in step 1 to clean out any non-bazel-controlled non-checked-in files
from the workspace.

**Comment by damienmg** [comment]
Closing as obsolete. This is not really actionable.

**Comment by philwo** [comment]
@jlisee Sure! Either is fine with me. Do you want to send a pull request? :)
