### ISSUE TITLE
git_repository doesn't print any warning or error on duplicate conflicting definitions

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/bazel#4865]
Three (or more) bugs here. They're all in the `git_repository` so I put them in the same issue, feel free to refactor if they should be separate.

The below behavior _might_ be working as intended, but at minimum I would expect some warnings to be printed out. Other repository types such as `local_repository` print errors in similar configurations.

### BUG 1: Native `git_repository` silently overrides earlier definitions

```
git_repository(
    name = "com_github_bazelbuild_buildtools",
    commit = "NOEXIST-A",
    remote = "https://github.com/bazelbuild/buildtools",
)
git_repository(
    name = "com_github_bazelbuild_buildtools",
    commit = "NOEXIST-B",
    remote = "https://github.com/bazelbuild/buildtools",
)
```

```
$ bazel query @com_github_bazelbuild_buildtools//...
ERROR: Invalid branch, tag, or commit: Ref NOEXIST-B can not be resolved
$
```

### BUG 2: Skylark `git_repository` silently overrides earlier definitions

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
    name = "com_github_bazelbuild_buildtools",
    commit = "NOEXIST-A",
    remote = "https://github.com/bazelbuild/buildtools",
)
git_repository(
    name = "com_github_bazelbuild_buildtools",
    commit = "NOEXIST-B",
    remote = "https://github.com/bazelbuild/buildtools",
)   
```
```
$ bazel query @com_github_bazelbuild_buildtools//...
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jmillikin/72f4f2b536263b66a36bf3d5538b0840/external/bazel_tools/tools/build_defs/repo/git.bzl", line 83
		_clone_or_update(ctx)
	File "/private/var/tmp/_bazel_jmillikin/72f4f2b536263b66a36bf3d5538b0840/external/bazel_tools/tools/build_defs/repo/git.bzl", line 51, in _clone_or_update
		fail(("error cloning %s:\n%s" % (ctx....)))
[...]
+ git fetch origin NOEXIST-B:NOEXIST-B
fatal: Couldn't find remote ref NOEXIST-B
$
```

### BUG 3: Native `git_repository` silently overrides Skylark `git_repository` 

```
 git_repository(
    name = "com_github_bazelbuild_buildtools",
    commit = "NOEXIST-A",
    remote = "https://github.com/bazelbuild/buildtools",
)   
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(
    name = "com_github_bazelbuild_buildtools",
    commit = "NOEXIST-B",
    remote = "https://github.com/bazelbuild/buildtools",
)
```

```
$ bazel query @com_github_bazelbuild_buildtools//...
ERROR: Invalid branch, tag, or commit: Ref NOEXIST-A can not be resolved
$
```

### What operating system are you running Bazel on?
MacOS

### What's the output of `bazel info release`?
```
$ bazel info release
release 0.11.1
```

cc @gkossakowski

**Comment by buchgr** [comment]
assigning @aehlig who is working on repositories I believe?

**Comment by aehlig** [comment]
> The below behavior _might_ be working as intended, but at minimum I would expect some warnings to be printed out. [...]

Unfortunately, most of this is working as designed&mdash;and that design also makes it hard to even generate warning in the more interesting cases. `WORKSPACE` files are the only files in bazel, where the `load` statements don't have to come all at the beginning of the file. The reason is that we want to have the ability to load from a file coming from an external repsitory itself (so we first have to know its definition). Therefore, bazel internally splits the `WORKSPACE` file into chunks, splitting just before each block of `load` statements; now, if the definition of a repository is needed, the chunks are searched for in order, till a definition is found. If we wanted to generate warnings for dropped definitions from a later chunk, the reading would have to continue, which usually requires fetching a repository. That might be really expensive (and otherwise not needed for the particular build) or even the repository in question (so that a warning about a double definition of a repository could only be generated once the very repository is fetched).

Inside each chunk, the latest definition wins, as is expected from an imperative programming language. However, the question remains indeed, why we don't warn about double definitions here while we forbid double definitions of targets in a `BUILD` file. Nevertheless, given that everything beyond the next `load` statement is infeasible to look at anyway, such a partial warning would probably be of limited use.

**Comment by jmillikin-stripe** [comment]
Given that `native.existing_rules()` works for repository rules in the expected way, is it really not possible for the second definition to warn that it's overriding an earlier one? I understand that the presence of external loads means it's not possible to statically determine whether this problem exists in a non-trivial `WORKSPACE`, but clearly there's some sort of state being kept and an "if key already exists" check seems like it should be possible to implement.

**Comment by gmesch** [comment]
FWIW, I have observed the same surprising and undocumented behavior for the `http_archive()` rule.

We use overrides of workspaces in order to align the version of the same transitive dependencies of different external workspaces. We used to do this by loading the same workspaces at different versions after the execution of `*_deps()` functions from those workspaces. This worked, until we moved the loading of the workspaces out of the `WORKSPACE` into `.bzl` files, where the overrides got silently dropped.

Now it seems the solution is to always move the overrides *before* the `load()` call, not merely the invocation, of the `*_deps()` functions. This way, we would not even rely on the `*_deps()` function checking for the presence of the repository.
