### ISSUE TITLE
stable-status stamp BUILD_HOST doesn't update until bazel shuts down

### ISSUE THREAD

**Issue by dfabulich** [bazelbuild/bazel#4941]
On macOS, Bazel to be caching the machine's hostname in the `stable-status.txt` stamp file after changing it with `scutil`

Use the following Bazel repository. https://github.com/dfabulich/bazel-hostname-caching

It has a blank `WORKSPACE` and a `BUILD` file with a single `genrule`.

```python
genrule(
	name='out',
	outs=['out.txt'],
	stamp=1,
	cmd='cat bazel-out/stable-status.txt > $@',
)
```

Run it like this:

```
bazel build out && cat bazel-genfiles/out.txt
```

It will print out your hostname, matching the output of `hostname`.

Now use `scutil` to change your hostname, like this:

```
scutil --set HostName newname
hostname # shows the new host name
bazel build out && cat bazel-genfiles/out.txt
```

Expected: `newname`
Actual: The old host name

The correct host name shows up after running `bazel shutdown`.

### What operating system are you running Bazel on?

macOS 10.13.3

### What's the output of `bazel info release`?

`release 0.11.1`

**Comment by jmmv** [comment]
Bazel has to cache this information in memory for performance reasons, as hostname resolution can take a long time.

I can't seem to find any API to monitor for hostname changes, at least on macOS, but this is not an Apple-specific issue because the same problem would raise on any platform when the hostname changes. And it's not only due to calls to `hostname` or `scutil`: a DHCP update could change the hostname. Without kernel-level support for notifications on changes like this, we have no option.

So there is nothing we can do really, short of having a background thread that tries to refresh this information... but then, we'd still risk occasional incorrect output if we race between that thread and a build. Considering that Bazel also caches more things in memory (Xcode version information, and even details about files to avoid redigesting them all the time), I'll have to say that this is working as intended.
