### ISSUE TITLE
Support auth from settings.xml

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#498]
This is already implemented on the Bazel side, so similar code can probably be used for generate_workspace.

**Comment by ittaiz** [comment]
@kchodorow is this closely related to using repositories from settings.xml? 
I tried to use generate_workspace but couldn't because I couldn't get it to use the organizational artifactory defined in my ~/.m2/settings.xml
I ended up hacking the `MavenConnector` and changed the `MAVEN_CENTRAL` url to point to our artifactory.

**Comment by kchodorow** [comment]
Yeah, basically it should use all of the local (settings.xml) configuration options.

**Comment by zvh** [comment]
I think I've run into a similar requirement; I'm trying to use robolectric as in:

> bazel run //src/tools/generate_workspace --   --artifact=org.robolectric:robolectric:3.1.2

However, robolectric depends on maven-ant-tasks which depends on some org.codehaus.plexus artifacts. Codehaus.org no longer appears to host code, but bazel is attempting to use it to retrieve the plexus assets:

ERROR: Unable to resolve Maven model from http://snapshots.maven.codehaus.org/maven2/org/codehaus/plexus/plexus-utils/1.0.4/plexus-utils-1.0.4.pom: 1 problem was encountered while building the effective model
[FATAL] Non-parseable POM http://snapshots.maven.codehaus.org/maven2/org/codehaus/plexus/plexus-utils/1.0.4/plexus-utils-1.0.4.pom: Expected root element 'project' but found 'html' (position: START_TAG seen <!DOCTYPE html>\n<html>... @2:7)  @ line 2, column 7

I think that if I could specify a settings.xml, then I might be able to resolve this with something like:

http://www.codehaus.org/mechanics/maven/

or:

http://stackoverflow.com/questions/30288097/how-to-resolve-codehaus-service-unavailable-maven-build-error

But since this issue seems to state that there is no way to specify a settings.xml when using generate_workspace, does anyone know of some workaround I can use in the meantime?

Thanks!

**Comment by systemlogic** [comment]
@kchodorow any solution so far on using any protected maven repository thru settings.xml

**Comment by systemlogic** [comment]
@ittaiz @kchodorow Any solution where I can use my settings.xml for accessing protected repository ?

**Comment by jin** [comment]
@systemlogic check out https://github.com/bazelbuild/rules_jvm_external, which is our recommended ruleset for managing Maven artifacts. It doesn't integrate with settings.xml directly, but supports authenticating with HTTP Basic Authentication. 

https://github.com/bazelbuild/rules_jvm_external/issues/80

**Comment by systemlogic** [comment]
We are developing monorepo and using maven_jar. Example you have shared will bring all the dependencies using maven_install. Anything for maven_jar ?
