### ISSUE TITLE
rules_nodejs downstream dependency broken at HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5028]
rules_nodejs is broken on all platforms with:

```
ERROR: java.io.IOException: Cannot run program "echo BUILD_SCM_VERSION 1.2.3" (in directory "/var/lib/buildkite-agent/builds/buildkite-ubuntu1404-q6xf-1/bazel-downstream-projects/rules_nodejs"): error=2, No such file or directory
```

Failure log:
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/201#033578ee-a114-4fbe-be77-9327536634cd

Bisect shows the culprit is commit 073ea095a6c6a826ccdbbce1b213de47115e701a

**Comment by laszlocsomor** [comment]
Culprit is that https://github.com/bazelbuild/rules_nodejs/blob/1931156c232a08356dfda02e9c8b0275c2e63c00/tools/bazel.rc#L7 uses `--workspace_status_command` incorrectly, specifying a Bash command instead of a path to a binary.

Though the documentation says you must use a path, Bazel didn't use to verify that, so users couldn't have known. Bazel used to just run the flag's value through Bash so a raw command worked too.

https://github.com/bazelbuild/bazel/commit/073ea095a6c6a826ccdbbce1b213de47115e701a changed Bazel so it now executes the command expecting it to be a binary.

I'll add error checking to Bazel, then probably I have to fix some broken projects in BuildKite, then I'll re-submit https://github.com/bazelbuild/bazel/commit/073ea095a6c6a826ccdbbce1b213de47115e701a.

**Comment by c-parsons** [comment]
Closing, as the original breakage was rolled back.
