### ISSUE TITLE
TMPDIR not set to TEST_TMPDIR in tests

### ISSUE THREAD

**Issue by schroederc** [bazelbuild/bazel#504]
The TMPDIR environment variable is the standard name for the temporary directory in unix binaries.  It be set, by default, to TEST_TMPDIR in //tools/test:runtime.

**Comment by hanwen** [comment]
damien is on leave.

$TMPDIR  is not documented in the test encyclopedia, and inside google is not set either. 

Why do you need TMPDIR to be specified? Shouldn't tests survive it not being set?

**Comment by ulfjack** [comment]
There may be third-party code in the build that reads TMPDIR. I think we
should set it for all actions, not just tests - otherwise getting the OSX
sandbox to work will be even more difficult. I'm not sure we even need
TEST_TMPDIR (it predates me being on the project).

On Tue, Oct 13, 2015 at 12:43 PM, Han-Wen Nienhuys <notifications@github.com

**Comment by hanwen** [comment]
What should it be set to, though? I believe on MacOS it should be set differently than on Linux, for example.

I think the OSX sandbox based on App sandbox is a lost cause.

**Comment by ulfjack** [comment]
For the OSX sandboxing prototype, I've been setting TMPDIR to a unique
per-action directory underneath the system TMPDIR (so we can clean it up
after the action is finished). That would also allow us to get rid of any
'mktemp -d' in our genrules, because TMPDIR is already unique. However,
that would make it a bit harder to run genrules manually.

On Tue, Oct 13, 2015 at 12:54 PM, Han-Wen Nienhuys <notifications@github.com

**Comment by helenalt** [comment]
@ulfjack  is this issue still relevant?

**Comment by ulfjack** [comment]
Good question. We've been changing Bazel to always set TMPDIR, although we're not currently setting TEST_TMPDIR to TMPDIR. I think it would generally be a good idea to make such a change, although we might want to first make it so TMPDIR is always set to an empty directory. TEST_TMPDIR is currently always a per-test empty directory, and setting TEST_TMPDIR to TMPDIR now would regress on that, I think. That said, I don't consider this a bug.

**Comment by aiuto** [comment]
Closing for staleness. People have been living with this and not seeing escalation for 2 years. Much of execution and especially sandboxing has been redone since then.
