### ISSUE TITLE
make bazel cpu counter container aware

### ISSUE THREAD

**Issue by hanwen** [bazelbuild/bazel#5042]
https://github.com/bazelbuild/bazel/blob/827007729889126cd7e07a08116f9bcb82f819a9/src/main/java/com/google/devtools/build/lib/actions/LocalHostResourceManagerLinux.java 

reads the number of CPUs from /proc/cpuinfo. AFAIK, Docker doesn't virtualize /proc/ , so if you try to control resource usage on a machine with Docker CPU limits, bazel will disregard this an thrash the machine.

**Comment by janakdr** [comment]
Giving to philwo@, who's much more of an expert in this area than I am.

**Comment by jwbee** [comment]
Mostly just subscribing to this ... but I have to say the way bazel subverts the Linux CPU mask is quite annoying. It starts a number of parallel tasks equal to the number of logical processors in the machine, yes, that's weird, but it's not as weird as the fact that it runs on all CPUs regardless of the fact that I run it under `taskset -c 10 bazel test ...`. My intention is to isolate it on one CPU but it just goes right ahead and uses all CPUs anyway. It must be something about the way the sandbox is started, because with plain old fork the cpumask would be inherited by descendants all the way down.

The only effective workaround I know is to create a cgroup without access to other CPUs and run the build inside that.
