### ISSUE TITLE
Tests depend on non existent //tools/defaults:coverage_support

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#5052]
### Description of the problem / feature request:

Blaze query when run on test targets returns a label corresponding to a target that doesn't exist.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In the following repo
https://gist.github.com/endobson/072c6a358cc9dc4b40e0d2874a5bc02b
Run:
`bazel query 'deps(//:foo_test)'`

### What operating system are you running Bazel on?

Mac OS X 10.11.6

### What's the output of `bazel info release`?

release 0.9.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Checked out a release tag of bazel and built it. Also added local changes and rebuilt when debugging/fixing issues.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
d7a2f112cc668f4dcd0ea905f9d53bb6f8d3d550
1aad4b99f19469599a42f3516197275e6ecd71f0

###  Have you found anything relevant by searching the web?

No.

**Comment by c-parsons** [comment]
I believe the issue here is that our base dependency on //tools/default:coverage_support needs to be correctly labeled as a "tool dependency":
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/BaseRuleClasses.java#L156

(we should be using `env.getToolsLabel()`)

**Comment by lberki** [comment]
Well, actually the target `//tools/defaults:coverage_support` does exist at least in Bazel's head: try `bazel query //tools/defaults:all` or `bazel build //tools/defaults:crosstool`.

Arguably, it shouldn't though: that package is special-cased and is a legacy of the way Bazel used to handle dependencies that depend on command line options. 

An immediate fix would be putting that repository in the `@bazel_tools` repository so that the package Bazel hallucinates is at least hidden from sight, but since @dbabkin is working on removing `//tools/defaults` altogether, I'll let him make the call on whether this is worth doing before that package is history.
