### ISSUE TITLE
Provide support for tree artifacts with all languages 

### ISSUE THREAD

**Issue by marcohu** [bazelbuild/bazel#5093]
For e.g. code generators where the output is not known at analysis phase, there is currently lacking support. It works nicely with the .srcjar approach taken by the Java rules, but poses major hurdles for others.

As the tree artifacts approach seems to be the way forward to support such use cases in the future, it should be supported by all languages. Ideally in a language agnostic manner. With at least C++, you currently have to add a language specific extension to the directory to make things work (to a certain degree).

**Comment by ulfjack** [comment]
WAI? It's impossible to make it work in a language-agnostic manner. Every rule set has to be updated individually to support tree artifacts. Just take Java and C++ as examples. C++ wants to generate one compile action per source file, Java is happy to put all the source files into the same action. These are fundamentally incompatible approaches, and a language-agnostic solution is not feasible.

**Comment by marcohu** [comment]
@ulfjack I did not mean a uniform implementation that supports all languages, but rather that tree artifacts should ideally be transparent to the user.

With the C++ support you currently have to provide a language specific extension (which poses problems in itself. What if you generate headers as well?). With my multi-language code generator use case in mind, I don't find that ideal because you have to cater for each supported language, instead of using just one directory name for all languages. It's not a showstopper, but it would be nice if tree artifacts would not require language specifics from the outside.

**Comment by ulfjack** [comment]
Right. I agree that tree artifacts should be more transparent for users. However, I'm not sure what exactly you're asking for. Is it just to fix the C++ issue? I'm not sure how we can make it more consistent across languages.

**Comment by marcohu** [comment]
The main request is that all language rules should support tree artifacts as input.

Secondly, tree artifacts should ideally not require language specific extensions. E.g. instead of `path/dirname.cc`, just `path/dirname` should be enough. This way directories could be consumed by different language rules, not just rules for a specific language.

My use case is a code generator for different languages that would have to cater for each language if language rules require distinct tree artifact names. This would demand that the generator target language has to be specified upfront, while the generator could otherwise figure it out automatically (depending on the input).

**Comment by ulfjack** [comment]
Certainly, path/dirname should work - using dirname.cc is a hack. AFAICT, that will require extensive work on the C++ rules side and possibly the Skylark APIs, contributions welcome.

However, I don't see any way of doing this in a language-neutral way. C++ requires special work in order to enable path/dirname consumption, and it's specific to C++. While there may be some sharing of code and concepts between rules, other language rules will also have to do their own special work to support tree artifact consumption.

Put differently, path/dirname.cc is a special hack that happens to work for C++, but I don't see any obvious reason to believe that other languages will be the same. It's more likely that other language rules will either work with path/dirname or, more likely, not accept tree artifacts at all.

This is annoying, yes, but I don't see any technical solution to the problem. Tree artifacts are still fairly new, and I don't see any way around updating every rule set individually to support them.

Maybe we should be talking about non-technical solutions then?

**Comment by marcohu** [comment]
> However, I don't see any way of doing this in a language-neutral way.

As said earlier, my concern was just regarding the visible contract, not the actual implementation. If the `.cc` extension is just a temporary workaround and path/dirname will work in the final API, I'm all for it.

Feel free to close the ticket if common support for tree artifacts is not considered a worthwhile/realistic goal for all language rules. I can certainly live with other means (like the Java .srcjar approach), but I think all language rules should at least provide some way to easily support the "output not known at analysis phase" use case.

**Comment by renau** [comment]
We have a similar problem. We want to use bazel for synthesis, but the problem is that the outputs are not know until execution. We tried to use the ctx.actions.declare_directory to handle the output[s] by
placing them in a directory.

The declare_directory works but only if the contents inside is c or h files. It does not work for generic blob binary files.

It would be great if bazel were more generic. I mean, given a set of inputs, a node can create many outputs. The number of outputs is controlled by the node execution. This delays the graph until run-time, but it allows more potent optimizations.

Notice that the previous thing does not say anything about specific languages. The rule names would match.
This is potentially useful even for C++ programs. E.g: the compiler could spill the output in multiple files. One for each class in the source file. Then, only the consumers of the object file would be required to be fired again.
