### ISSUE TITLE
partial downloads can cause confusing error messages.

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/bazel#5103]
### Description of the problem / feature request:

Occasionally, a maven_jar download seems to fail, but partially keep some state. Bazel then reports the referenced file is not found, but does not try to fetch it again. I don't really know what is happening behind the scenes, but a `clean --expunge` will generally fix in this case. I think it may be that we have a partial download, but that download does not match the sha. Rather than removing the partial download and retrying, it seems bazel reports the file does not exist. This is only a speculation.

example error output:
```
ERROR: missing input file '@org_antlr_stringtemplate//jar:stringtemplate-3.2.1.jar'
ERROR: /Users/travisbrown/stripe/zoolander/3rdparty/jvm/org/antlr/BUILD:17:1: //3rdparty/jvm/org/antlr:antlr_runtime: missing input file '@org_antlr_stringtemplate//jar:stringtemplate-3.2.1.jar'
ERROR: /Users/travisbrown/stripe/zoolander/3rdparty/jvm/org/antlr/BUILD:17:1 1 input file(s) do not exist
```
this error wars fixed by running `clean --expunge`. So, it seems the file was not so much missing, and bazel was being blocked from fetching it somehow.

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like at least a better error in this case with a suggested remedy, but ideally bazel would retry a failed download, possibly with some reporting of the retry.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I don't know. It happens rarely by chance to our users. Perhaps manually modifying files in the cache could trigger this.

### What operating system are you running Bazel on?

OSX

### What's the output of `bazel info release`?
```
MacBook-Pro:zoolander oscar$ bazel info release
.........................
release 0.12.0
```

###  Have you found anything relevant by searching the web?

I have found other references to using `clean --expunge` for random failures, e.g.

https://github.com/bazelbuild/rules_typescript/issues/52

**Comment by meteorcloudy** [comment]
@aehlig Can you take a look?

**Comment by ittaiz** [comment]
I think we’re saying the same thing.
Especially on new workspaces which have many (hundreds) of external
dependencies

**Comment by ittaiz** [comment]
*seeing

**Comment by roblg** [comment]
I reproduced this on bazel 0.13.0rc5 as well. I think the 4h run without errors must have just been lucky or something.

Additional information: it looks like when we get this error, there's a broken symlink under `$(output_base)/external` for the file in question:

Error:

```
(16:56:21) ERROR: missing input file '@xml_apis__xml_apis__1_0_b2//jar:xml-apis-1.0.b2.jar'
(16:56:21) ERROR: /home/roblg/code/main/redfin.businessLogicPOM/redfin.util/BUILD:4:1: //redfin.businessLogicPOM/redfin.util:redfin.util: missing input file '@xml_apis__xml_apis__1_0_b2//jar:xml-apis-1.0.b2.jar'
(16:56:21) ERROR: /home/roblg/code/main/redfin.businessLogicPOM/redfin.util/BUILD:4:1 1 input file(s) do not exist
```

Investigation attempt:

```
$ bazel info output_base
/home/roblg/.cache/bazel/_bazel_roblg/8ea9c866733234ef0a2f2d7faf3de3bc/

$  ls -l /home/roblg/.cache/bazel/_bazel_roblg/8ea9c866733234ef0a2f2d7faf3de3bc/external/xml_apis__xml_apis__1_0_b2/jar
total 8
-rw-rw-r-- 1 roblg roblg 322 Apr 28 16:55 BUILD.bazel
lrwxrwxrwx 1 roblg roblg 160 Apr 28 16:55 xml-apis-1.0.b2.jar -> /home/roblg/.cache/bazel/_bazel_roblg/8ea9c866733234ef0a2f2d7faf3de3bc/external/org_apache_httpcomponents__httpcore/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar

# symlink points to non-existent file
$ unzip -l /home/roblg/.cache/bazel/_bazel_roblg/8ea9c866733234ef0a2f2d7faf3de3bc/external/xml_apis__xml_apis__1_0_b2/jar/xml-apis-1.0.b2.jar
unzip:  cannot find or open /home/roblg/.cache/bazel/_bazel_roblg/8ea9c866733234ef0a2f2d7faf3de3bc/external/xml_apis__xml_apis__1_0_b2/jar/xml-apis-1.0.b2.jar, /home/roblg/.cache/bazel/_bazel_roblg/8ea9c866733234ef0a2f2d7faf3de3bc/externa
l/xml_apis__xml_apis__1_0_b2/jar/xml-apis-1.0.b2.jar.zip or /home/roblg/.cache/bazel/_bazel_roblg/8ea9c866733234ef0a2f2d7faf3de3bc/external/xml_apis__xml_apis__1_0_b2/jar/xml-apis-1.0.b2.jar.ZIP.

# appears non-existent, not just busted
$ cat /home/roblg/.cache/bazel/_bazel_roblg/8ea9c866733234ef0a2f2d7faf3de3bc/external/xml_apis__xml_apis__1_0_b2/jar/xml-apis-1.0.b2.jar
cat: /home/roblg/.cache/bazel/_bazel_roblg/8ea9c866733234ef0a2f2d7faf3de3bc/external/xml_apis__xml_apis__1_0_b2/jar/xml-apis-1.0.b2.jar: No such file or directory
```

I'm happy to post other info/try fixes as well, since we've got a reliable repro.

**Comment by ittaiz** [comment]
Any chance you can try to run this on 0.11.1 to see that it indeed started
from 0.12.0?

**Comment by roblg** [comment]
I haven't seen a single repro in 20+ iterations on vanilla bazel release 0.11.1. I can easily repro with bazel 0.11.1 plus `--experimental_repository_cache=<path>`.

Probably worth noting at this point that we're seeing this behavior with the native `maven_jar`. I just tried to repro with the skylark `maven_jar` impl, and it blew up trying to run `mvn` in a way totally unrelated to this issue.

**Comment by ittaiz** [comment]
Oh for us this is without the experimental repository cache. Sorry I missed
that detail

**Comment by roblg** [comment]
@ittaiz Sorry, it was slightly confusing the way I dropped that in there. In bazel 0.12.0, the `--experimental_repository_cache` flag was made the default behavior, so I tested bazel 0.11.x both with and without it to try to rule out the repository_cache as the cause.

I'm pretty sure I found the bug last night though... I realized while staring blankly at the error that the symlink value isn't just pointing into thin air; it's _wrong_:
/home/roblg/.cache/bazel/_bazel_roblg/8ea9c866733234ef0a2f2d7faf3de3bc/external/org_apache_httpcomponents__httpcore/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar

The dependency that ends up busted is: `xml_apis:xml_apis:1.0.b2`: 
`(16:56:21) ERROR: missing input file '@xml_apis__xml_apis__1_0_b2//jar:xml-apis-1.0.b2.jar'`

But that symlink is pointing to something that can't ever exist (it's not a real dependency, and it's certainly not listed in _our_ dependencies):
`xml-apis-1.0.b2.jar -> ....../external/org_apache_httpcomponents__httpcore/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar
`

That `org_apache_httpcomponents__http_core` in the path _is coming from something else that's happening simultaneously_. 🙀 

I found a bug in `MavenDownloader.java` that could explain the behavior (https://github.com/roblg/bazel/commit/8f410bb9c35f698f7d94d491e625cb1401ef263f). Working on testing it. Currently 10 iterations in with no issues.

If that turns out to be the fix, it looks like this issue has been sitting there for a year and a half (since MavenDownloader was refactored into a subclass of HttpDownloader) and is just really rarely hit, probably because network latency for the downloads used to add a lot of variability. The `repository` cache in 0.12 gives us a lot more contention. Wild.
