### ISSUE TITLE
Add an attribute to expose repository as an archive file

### ISSUE THREAD

**Issue by anchlovi** [bazelbuild/bazel#5167]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Add an attribute to expose repository (`git_repository` and `http_archive`) as an archive file, e.g., 
> ```python
> git_repository(
>    name = "some_repo_name",
>    remote = "git@github.com:....git",
>    ...
>    create_archive = true
> )
> ```
>
> So targets would specify `@some_repo_name//archive` as a dependency to depend on the repo archive

### Feature requests: what underlying problem are you trying to solve with this feature?

> This would make it easier for tests to depend on the whole repo without the need to download it again

### What operating system are you running Bazel on?

> Mac OS Sierra - 10.12.6

### What's the output of `bazel info release`?

> `release 0.12.0-homebrew`

###  Have you found anything relevant by searching the web?

> No

### Any other information, logs, or outputs that you want to share?

> The suggested functionality can be achieved today using `patch_cmds`:
>
> 
> ```python
> git_repository(
>    name = "some_repo_name",
>    remote = "git@github.com:....git",
>    ...
>    patch_cmds = ["""
>       mkdir -p archive
>       tar -czvf archive/repo.tar.gz .
 >       echo "filegroup(name = 'archive', srcs = ['repo.tar.gz'], visibility = ['//visibility:public'])" > archive/BUILD.bazel
>    """]
> )
> ```

**Comment by ittaiz** [comment]
@ahelig wdyt? This is following our discussion on how we can depend on an
entire repository for an e2e that runs bazel

**Comment by aehlig** [comment]
I think in general, it would be a good idea, even though it is probably not on top of my priority list.

However, `patch_cmd` doesn't seem to be the correct solution (even though it is, of course, a programatic transformation of repository). A natural place to add it would be directly to https://github.com/bazelbuild/bazel/blob/3aa9107ebefebbf4b98b382254ff83cfb8def865/tools/build_defs/repo/http.bzl and https://github.com/bazelbuild/bazel/blob/3aa9107ebefebbf4b98b382254ff83cfb8def865/tools/build_defs/repo/git.bzl. Also, we have to keep in mind, that the archive has to be reproducible and not depend on randomness of the system, like `readdir(3)` order.
- For `http_archive`, that's straight forward. Instead of `download_and_extract`, just download and unpack separately, not throwing away the originally downloaded archive.
- For `git_archive`, one would have to think what the intended semantics should be (given that the contents of the `.git` directory are not canoncial, even for a fixed commit); one option that would work for the described use case would be to ignore the `.git` directory and archive the rest in a canonical traversal order with fixed owners and time stamps.

If someone finds the time earlier than I do to implement it, feel free to grab the issue.

**Comment by aehlig** [comment]
Interestingly enough, for bazel we also had to solve the problem of packing certain archives (to allow offline builds, see #5202). 3c9cd82b847f3ece8ec04b2029bd5e8ad0eb7502 solved that problem by adding new skylark code, but again, only for the simple case of downloaded files, not `git` checkouts.
