### ISSUE TITLE
getattr() should work whenever hasattr() is True

### ISSUE THREAD

**Issue by mboes** [bazelbuild/bazel#5224]
### Description of the problem

`hasattr()` returns `True` even when for the given attribute `getattr()` always throws an exception. This has the unfortunate side effect that one cannot safely `getattr()` the value of an attribute, even when guarding it with `hasattr()` beforehand.

I would expect the following intuitive property to hold:

> getattr(x, "foo") returns a value (does not raise an exception) if and only if `hasattr(x, "foo") == True`.

But since at least https://github.com/bazelbuild/bazel/commit/e5e3e9193a457ace9043bf70ff0253333c3435e5, this 
 does not hold.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```python
x = struct(a = 1)
print(dir(x))
for f in dir(x):
  if hasattr(x, "a"):
    print(getattr(x, "a", "method"))
```

raises an exception because `hasattr(x, "to_json")` is `True` but `getattr(x, "to_json")` doesn't work, even when a default value (`"method"`) is provided.

### What's the output of `bazel info release`?

v0.13.0

###  Have you found anything relevant by searching the web?

Nothing in GitHub issues.

**Comment by brandjon** [comment]
From inspection of the [code](https://github.com/bazelbuild/bazel/blob/9a02760e732632671ddde48ab841b9b0ab788e67/src/main/java/net/starlark/java/eval/Starlark.java#L668-L724), it looks like this is fixed by Alan's refactoring. `hasattr` checks for both annotated methods/fields and `Structure` fields. And `getattr` has supported accessing builtin methods for quite a while now.
