### ISSUE TITLE
TF fails for Windows on Bazel CI

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#5243]
Log: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/248#3c6c4f25-b0b6-484a-8d03-0d6cb281ac70

The actual error is:
```
ERROR: C:/build/buildkite-worker-windows-java8-lfl8-1/bazel-downstream-projects/tensorflow/tensorflow/python/BUILD:3424:1: Couldn't build file tensorflow/python/_pywrap_tensorflow_internal.so: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed (Exit -1). Note: Remote connection/protocol failed with: execution failed: link.exe failed: error executing command
--



command is longer than CreateProcessW's limit (32768 characters)
```

**Comment by meteorcloudy** [comment]
Thanks @katre ! I'm on it!

**Comment by rongjiecomputer** [comment]
I hit the max command length limit a few times already, usually at link step. Most build systems work around this with response file which both `cl.exe` and `link.exe` support. If possible, please implement response file for compile step too while fixing this issue.

**Comment by meteorcloudy** [comment]
@rongjiecomputer We do have parameter file (response file?) for link action. But this issues is just introduced yesterday by 5c4f3b59fb4aa06da2c368c764cf0d9056ab287a.

The reason is we hard-coded the file extensions when deciding which arguments goes into parameter file. See https://github.com/bazelbuild/bazel/blob/a51b436f4290a79f77157b9e1f2f2e7b26283a5c/src/main/java/com/google/devtools/build/lib/rules/cpp/LinkCommandLine.java#L324

I'm not sure you are encountering the same issue. Can you share more information about your failure?

**Comment by meteorcloudy** [comment]
@rongjiecomputer Thanks for the explanation, please make sure you use a Bazel containing https://github.com/bazelbuild/bazel/commit/9b964fcec25d29cef542e314cfffd223785063be, which is a fix for this issue. Looking forward to your feedback!
