### ISSUE TITLE
Integrate external dependencies with their native build system

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#5255]
When migrating projects to Bazel, users often have to migrate their third party dependencies to Bazel. This is usually a significant amount of work which could slow down migration process a lot. See envoy's migration story: https://github.com/bazelbuild/bazel/issues/2792

To help our users, Bazel could provide some Skylark rules that invoke the native build systems of the dependencies, then provide the outputs as targets that can be depended on by other targets.

This method is worthy as it will help our users migrating to Bazel more easily. An experimental rule for cmake/configure&make is planned in Q2 2018 with productionisation in Q3

Related docs: 
[TensorFlow Bazel Build Issues](https://docs.google.com/document/d/1azmOk0MLZVr20YPle7amGrs7YjDLMPQ4RbsN8CJSHVU/edit#heading=h.8dp4wmw2emjm)
[Bazel External Dependencies Roadmap](https://docs.google.com/document/d/1ZGoqeUI5zz2IP2LP09aTellSRNRi53bCCW6tbnKAc8o/edit#heading=h.3hwrnijlfgzn)

**Comment by meteorcloudy** [comment]
@dslomov As the engineer who's going to work on this is leaving the team, can you find a proper assignee for this issue?

**Comment by jin** [comment]
Also see: https://github.com/bazelbuild/rules_foreign_cc

**Comment by jbduncan** [comment]
I'm not sure if I'm overstepping my boundaries here, but I wanted to share my thoughts about this issue.

On top of migrating from CMake for a C++ project, as #2792 discusses, this would be brilliant for other build systems, such as Gradle in my case.

I've been interested in a while now for a solution that would allow me to build my Gradle-based vanilla Java projects with Bazel (mainly so that I have a reason to learn and play around with Bazel :wink:), but also to be able to continue using certain Gradle plugins and tasks that I've grown dependent on (e.g. [Spotless](https://github.com/diffplug/spotless), [gradle-dependencies-plugin](https://github.com/ben-manes/gradle-versions-plugin)). I've also been hoping for an incremental solution, so that I can take my time to fully migrate things to Bazel if I so wish.

I was hoping that the [OkBuck](https://github.com/uber/okbuck/) Gradle plugin would allow me to do this, as some time ago @aj-michael proposed initial support for Bazel (https://github.com/uber/okbuck/issues/232), but sadly at the time of me writing this that issue seems to have petered out.

So if there's anything I can do to help move this issue forward, then I would love to be involved. :)

**Comment by jin** [comment]
@jbduncan You might be interested in Spotify's https://github.com/menny/bazel-leaf, which lets you incrementally build Gradle modules using Bazel.

**Comment by jbduncan** [comment]
Thanks @jin! I'll have a proper look at it when I'm next free. :)

**Comment by jbduncan** [comment]
@jin AFAICT, bazel-leaf doesn't seem to have any installation instructions yet. Am I missing something? :)

**Comment by jin** [comment]
@jbduncan It looks like there are setup instructions here: https://github.com/menny/bazel-leaf#module-setup

**Comment by jin** [comment]
@jbduncan Ah, I see. I am not familiar with how you can specify bazelleaf as a local Gradle plugin. Perhaps there is a way to do that?

**Comment by jbduncan** [comment]
@jin Yep, I'm sure there is. I will either have to compile the plugin locally on my machine and store the jar in a `lib` directory in my project, or use jitpack.io. Not terribly ideal, but hey ho - for experimentation purposes, it should work. :)

**Comment by kageiit** [comment]
Sidenote, Okbuck is migrating to skylark for all generated build file definitions in buck - https://github.com/uber/okbuck/issues/598

okbuck is going to use custom rules i.e disallow native rules in the generated BUCK files. It could be a lot easier potentially to tweak the loads for the `.bzl` files that define these rules and make them use the bazel native rules instead. This would make inter-op a lot easier (buck specific files in the rules can just be ignored or converted over in pure skylark)

This might be an easier path to support bazel via okbuck

**Comment by jin** [comment]
@kageiit thanks for the update! The Bazel Android rules are not implemented in bzl yet, but it'll be interesting to see if Bazel will be able to use these new `.bzl` files.

**Comment by bbarnes52** [comment]
"An experimental rule for cmake/configure&make is planned in Q2 2018 with productionisation in Q3"

Is this timeline still accurate?

**Comment by petroseskinder** [comment]
@bbarnes52 
Might want to check with:
 https://github.com/bazelbuild/rules_foreign_cc

**Comment by jbduncan** [comment]
I'm not entirely sure if this issue is intended to be resolved by the time Bazel 1.0 is released. (I understand from https://blog.bazel.build/2019/06/06/Bazel-Semantic-Versioning.html that Bazel 1.0 is intended to be a "milestone" for implementing the Bazel Vision, and that implementing this issue is part of the vision.)

Could someone clarify this for me? :)
