### ISSUE TITLE
Ubuntu 15.10 doesn't like unfiltered -isystem directories

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#526]
Normally, when a user specifies a relative include path via `includes` in an `cc_library()`, Bazel will generate two `-isystem` references for GCC: one in the source tree and one in the genfiles tree.  Presumably this is because Bazel doesn't know which tree you mean.  That has worked very well until Ubuntu 15.05, when GCC now fails if an `-isystem` directory is not found.  In my case, it does not exist in the source tree but it does in the genfiles tree.

**Comment by kayasoze** [comment]
The error is:

```
cc1plus: error: <redacted>: Not a directory
```

**Comment by kayasoze** [comment]
Actually, in my particular case my `includes` path is a directory in `genfiles` and a non-directory in the source tree, which is the issue.  Thus, while filtering is still a benefit, this bug will not likely hit most users.

**Comment by ulfjack** [comment]
There's no easy fix for this, unfortunately. I think we could look at the header files in each cc_library, and only add each path entry if there are actual header files on that path. If all header files are declared (and they should be), then this should be safe. Migrating Google internally will be very painful. The code for that is in CcLibraryHelper.java.

Since I just installed 15.10 on my private machine, I may give this a shot.

I can't think of a quick workaround, unless there is a gcc option to disable the new behavior. Maybe use a wrapper script and remove any -isystem options that refer to non-existent directories?

**Comment by kayasoze** [comment]
That was my thought--just remove the non-existent directories.  It might not be worth it to apply even that change, though, since GCC only complains if the directory exists and is a file.  I'm fine with wontfix but I wanted to document for posterity.
