### ISSUE TITLE
//src/test/py/bazel{:runfiles_test,windows_remote_test}

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#5315]
When trying to move Bazel's host javabase to JDK9 (https://github.com/bazelbuild/bazel/pull/5312) these two tests fail:

```
//src/test/py/bazel:runfiles_test
//src/test/py/bazel:windows_remote_test
```

Here's a detailed log:

https://source.cloud.google.com/results/invocations/bb12c897-b46a-4e75-938f-1d956699d8dc/targets

The errors all look like:

```
11:1: //bar:bar-java: missing input file '@local_jdk//:jre/lib/jce.jar'
ERROR: C:/users/b/_bazel_b/1fz8gp--/execroot/io_bazel/_tmp/c3b0bbd16b12dcab62c45e413ccc8e32/tests_root/tmp9u5kc82s/bar/BUILD:11:1 1 input file(s) do not exist
```

IIUC correctly files like `jre/lib/jce.jar` no longer exist in JDK9.

cc: @jasharpe @meteorcloudy @cushon @laszlocsomor

**Comment by cushon** [comment]
Are they only failing on windows?

**Comment by aehlig** [comment]
@laszlocsomor can you help triaging further and assign as appropriate? Thanks.

**Comment by meteorcloudy** [comment]
@aehlig Laszlo is on vacation this week, I can take a look at this.

**Comment by meteorcloudy** [comment]
@buchgr https://github.com/bazelbuild/bazel/blob/c924cf6f464cf24ac6ba4fb1c1d34aa2fe567e3f/src/main/tools/jdk.BUILD#L74-L78

Did you see this?

@cushon Not sure why it's only failing on Windows, any idea how to fix for JDK 9?

**Comment by cushon** [comment]
We shouldn't be using JDK 9 as a `--javabase` yet, just as a `--host_javabase`, so that TODO shouldn't be a problem.

Can you confirm that the `JAVA_HOME` environment variable is being set correctly for those windows tests, and that this logic is locating the local JDK 8 instead of the embedded JDK 9?

https://github.com/bazelbuild/bazel/blob/f4cf006a4e1189b1ff6c757a90af22038fa6b943/src/main/java/com/google/devtools/build/lib/packages/WorkspaceFactory.java#L542-L546

**Comment by meteorcloudy** [comment]
@buchgr Can you confirm the Windows setup for `JAVA_HOME`?

**Comment by cushon** [comment]
I saw there's some windows-specific `JAVA_HOME` handling, but I don't totally understand how it all fits together:

* https://github.com/bazelbuild/bazel/blob/38a36ccd369e66a8a9bca8e6753d342a1cec05a1/src/test/shell/testenv.sh#L58
* https://github.com/bazelbuild/bazel/blob/b84e1a6fd960af6553a0581990cca182c6d51a05/.bazelci/presubmit.yml#L77

Since both of the failing tests as python integration tests, maybe there's some setup that needs to handle for python tests that isn't currently happening? Maybe something needs to happen for py tests here?

https://github.com/bazelbuild/bazel/blob/38a36ccd369e66a8a9bca8e6753d342a1cec05a1/src/test/py/bazel/test_base.py#L258

**Comment by meteorcloudy** [comment]
The `JAVA_HOME` set in `bazel/src/test/shell/testenv.sh` should be irrelevant to python tests.
`--test_env=JAVA_HOME` will pass `JAVA_HOME` to all tests. But looks like we are not respecting it in `test_base.py` 
So, maybe adding a `env['JAVA_HOME'] = TestBase.GetEnv('JAVA_HOME')` will fix it?

**Comment by cushon** [comment]
@meteorcloudy thanks!

I got the python tests passing on windows with this patch:

```
diff --git a/src/test/py/bazel/test_base.py b/src/test/py/bazel/test_base.py
index 5e279da9ef..f3c361a030 100644
--- a/src/test/py/bazel/test_base.py
+++ b/src/test/py/bazel/test_base.py
@@ -360,7 +360,9 @@ class TestBase(unittest.TestCase):
           # TODO(pcloudy): Remove this after no longer need to debug
           # https://github.com/bazelbuild/bazel/issues/3273
           'CC_CONFIGURE_DEBUG':
-              '1'
+              '1',
+          'JAVA_HOME':
+              TestBase.GetEnv('JAVA_HOME'),
       }
     else:
       env = {'HOME': os.path.join(self._temp, 'home')}
diff --git a/src/test/py/bazel/windows_remote_test.py b/src/test/py/bazel/windows_remote_test.py
index fc9a03a139..5ffdc6434d 100644
--- a/src/test/py/bazel/windows_remote_test.py
+++ b/src/test/py/bazel/windows_remote_test.py
@@ -203,7 +203,7 @@ class WindowsRemoteTest(test_base.TestBase):
 
     # Test.
     exit_code, stdout, stderr = self._RunRemoteBazel([
-        'test', '--test_output=all', '--host_javabase=//foo:jdk8',
+        'test', '--test_output=all',
         '--javabase=//foo:jdk8', '//foo:foo_test'
     ])
     self.AssertExitCode(exit_code, 0, stderr, stdout)
```

@buchgr can you include that change in #5312?

**Comment by laszlocsomor** [comment]
Can we close this bug?

**Comment by buchgr** [comment]
Yep!
