### ISSUE TITLE
Add attr.string_keyed_label_dict?

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/bazel#5356]
### Description of the problem / feature request:

I have a rule that does templating. I use `label_keyed_string_dict` and it is ok, but what if I want several strings to be replaced with the same label's output? `string_keyed_label_dict` would be useful (+ https://github.com/bazelbuild/bazel/issues/5355).

**Comment by excitoon** [comment]
Basically, `label_list` is enough to make everything. One can pass this dict as a list of labels plus a list of string and zip it inside the rule. This approach have an issue though, because `label_list` cannot contain the same labels, but it can be worked around by one more list of indices to smaller `label_list`.

**Comment by mboes** [comment]
This and #7989 are duplicates of each oher.
