### ISSUE TITLE
Is `win_def_file` input or output?

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#5357]
### Description of the problem / feature request:

Trying to move from `native.genrule()` to my custom rule with actions, I encountered an issue which does not allow `win_def_file` to be generated one when file name is equals to target name plus `.def`. It somehow conflicts with `cc_binary`, `DefParser` to be specific.

**Funny thing the same is working well with `native.genrule()`.**

I guess this is low priority bug, but the second part needs some attention. That may be a problem.
Ideally `DefParser` should write to the file with more rare name than just target plus `.def`.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Please find an example here:
https://github.com/excitoon/bazel-issues/tree/master/is-win-def-file-input-or-output

### What operating system are you running Bazel on?

Windows 10 x64

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Tried on 0.14 and 0.11.1

###  Have you found anything relevant by searching the web?

I found only these (possibly irrelevant):
https://github.com/pubref/rules_node/issues/52
https://github.com/bazelbuild/rules_docker/issues/40

### Any other information, logs, or outputs that you want to share?

```
C:\Users\Chebotarev_V\Documents\src\bazel-issues\is-win-def-file-input-or-output>bazel build ...
ERROR: file 'hello-world.dll.def' is generated by these conflicting actions:
Label: //:hello-world.dll-def, //:hello-world.dll
RuleClass: _generate_def rule, cc_binary rule
Configuration: e76b7d562bb114e7e8c729dea5085547
Mnemonic: FileWrite, DefParser
Action key: 37eb577b77479a0d2bc34ab3a1dec3d5, 79689c6c8c244c469dbe1548c6257bc6
Progress message: Writing file hello-world.dll.def, DefParser hello-world.dll.def
PrimaryInput: (null), File:[[<execution_root>]bazel-out/x64_windows-fastbuild/bin]_objs/hello-world.dll/sources/hello-world.o
PrimaryOutput: File:[[<execution_root>]bazel-out/x64_windows-fastbuild/bin]hello-world.dll.def
ERROR: Analysis of target '//:hello-world.dll-def' failed; build aborted
INFO: Elapsed time: 1.112s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by excitoon** [comment]
Most probably the second part is because of different locations of that file (binfiles and genfiles).

**Comment by meteorcloudy** [comment]
@excitoon Thanks for raising this issue.
The `win_def_file` is for users to specify a DEF file that will be used during linking time. So it is an input (which's only effective on Windows)

On Windows, if users build dynamic library with `--features=windows_export_all_symbols`, Bazel will use DefParser to generate a DEF file which exports all symbols from the provided object files. And it names the output file as `<target name>.def`. Although you didn't enable this feature, the action was created, that's why there're conflict actions.

I think it's a good idea to rename the def file so that it doesn't conflict with the name people often use. I will send a fix for this.
