### ISSUE TITLE
uses-permissions in AndroidManifest.xml are not exported to App

### ISSUE THREAD

**Issue by steeve** [bazelbuild/bazel#5411]
### Description of the problem / feature request:

As per the documentation, `uses-permissions` attributes are never exported to the main app. What is the rationale behind this decision?
Is there any way to have an `android_library` export its permissions to an app that includes it ?

Thanks!

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

```
release 0.14.1-homebrew
```

###  Have you found anything relevant by searching the web?

They are manually removed here:
https://github.com/bazelbuild/bazel/blob/bb4ffd680cf102d6dc2b32895b7bedde8e0cd695/src/tools/android/java/com/google/devtools/build/android/ManifestMergerAction.java#L157-L185

**Comment by jin** [comment]
I have no idea - @asteinb @ahumesky?

**Comment by ahumesky** [comment]
It's mostly because changing the permissions of your app prevents auto-updating on the play store.

If you have a code base where there are many apps that are independently owned by different teams, and you have many libraries that are similarly independently owned by other teams, and if you inherit permissions from your dependencies, then it means that other teams can change the permissions of your app without your permission or noticing. Another way to put it is that app owners should own the permissions their app asks for. If a new permission gets by and ends up in a release, then your app can't be auto-updated.

One possible response is that this could instead be taken care of in a test where the test asserts the set of permissions that the app has. But this results in basically the same situation: a flat list somewhere of the permissions the app is allowed, just in a test rather than the top-level manifest.

That said, it should be possible to add an attribute to `android_binary` that will enable permissions inheritance. It should also be possible to write a skylark aspect that traverses the dependencies of an `android_binary` that will at least give you all the permissions from the dependencies.

**Comment by steeve** [comment]
I'm closing this as the rationale makes sense.
