### ISSUE TITLE
switching compilers un-caches all host tools

### ISSUE THREAD

**Issue by bsilver8192** [bazelbuild/bazel#546]
When switching compilers (`--compiler=foo` flag), cached `cc_binary`s which are compiled for the HOST configuration get dropped. This is a big performance issue for things like protoc which are used to create inputs to many other actions, because all of those other actions then have to get re-run upon switching back. I don't see any way to use separate "host" output directories, which would fix the problem.

**Comment by ahumesky** [comment]
I believe this is because --compiler applies to both the host and target configurations. An exception here is --android_compiler, which was recently added (and might be considered a hack). Can you give some more detail on how this affects protoc? --compiler is used in the selection of the appropriate c++ toolchain in the crosstool file. I would expect that protoc is compiled in the host configuration, executed on the host, then its outputs consumed by other actions.

**Comment by bsilver8192** [comment]
Yes, that is all correct. After doing a build with `--compiler=gcc`, a subsequent build with `--compiler=clang` ends up recompiling basically everything because protoc changed (because it's built with a different compiler). That means all the protoc actions get run again, which means all the actions which consume the outputs of the protoc actions are run again too, which is the majority of my codebase.

**Comment by ahumesky** [comment]
Ok I see. If your host configuration doesn't change much, what you could do is specify --host_crosstool_top, and bazel will find a default_toolchain in the host crosstool using --host_cpu, and then use the toolchain (which has the compiler, etc) specified in the default_toolchain. I think you should be able to use the same crosstool file for both --host_crosstool_top and --crosstool_top

**Comment by bsilver8192** [comment]
That fixes it. Thanks!

I'm going to submit a change mentioning this in the docs, because that's really useful and not at all obvious.
