### ISSUE TITLE
Error message about objc_binary with implicit dependency on missing tool: iossim

### ISSUE THREAD

**Issue by adamhowardprice** [bazelbuild/bazel#560]
Trying to build a fairly straightforward `objc_binary`, getting this error message.

```
ERROR: /Users/adamprice/Code/client-ios/components/GLUE/BUILD:82:1: every rule of type objc_binary implicitly depends upon the target '//third_party/iossim:iossim',  but this target could not be found. If this is an integration test, maybe you forgot to add a mock for your new tool?.
ERROR: Loading failed; build aborted.
```

**Comment by adamhowardprice** [comment]
@cgrushko ^

**Comment by cgrushko** [comment]
It used to work :) 
What changed? do you happen to have a minimal repro project?

**Comment by cbrauchli** [comment]
This happens to me whenever I add a `.bazelrc` file to my project. The contents do not matter; it can even be empty. The presence of a `.bazelrc` makes this error message pop up.

**Comment by tetsuok** [comment]
I also encountered same issue (OS X10.11.2, Xcode: 7.2, iOS SDK 9.2, Bazel 0.1.3). I created a minimal repro project at https://github.com/tetsuok/bazel-ios-app-test, which can be built as follows:
```
git clone https://github.com/tetsuok/bazel-ios-app-test.git
cd bazel-ios-app-test
bazel build --verbose_failures --ios_sdk_version=9.2 //:ios-app-binary
```

**Comment by cgrushko** [comment]
@damienmg can you route this to the right person?

**Comment by damienmg** [comment]
Humm, `bazel info package_path`?


Also Kristina is fixing the latest part in which we use the base_workspace so that issue should be resolved when this get merged (today?)

**Comment by damienmg** [comment]
Oh wait I saw:

  This happens to me whenever I add a .bazelrc file to my project. The contents do not matter; it can even   
  be empty. The presence of a .bazelrc makes this error message pop up.

So, the .bazelrc in your workspace file take precedence over your ~/.bazelrc, so your package path must be wrong because the new bazelrc file does not declare it.

If you want to share a bazelrc it's better to use a master path so `%workspace%/tools/bazel.rc` (see http://bazel.io/blog/2015/07/01/Configuration-File.html).

**Comment by damienmg** [comment]
Carmi: I let you follow-up that discussion.

**Comment by damienmg** [comment]
No update so I guess this is resolved, closing, please ping back if you have more questions.
