### ISSUE TITLE
Feature request: Android build should generate BuildConfig for each BUILD module

### ISSUE THREAD

**Issue by menny** [bazelbuild/bazel#563]
Unlike _Gradle_ Android plugin, _Bazel_ will not generate `BuildConfig` class for `android_binary` or `android_library` targets.
To overcome this issue, @cgrushko suggested the following quick hack:

```
genrule(
    name = "build-config-genrule",
    outs = ["BuildConfig.java"],
    cmd = "echo 'package com.example.lib;" +
            "public class BuildConfig {" +
            "public static final boolean DEBUG = true;" +
            "}' > $(@)",
)
```

And then add that `genrule` to the sources:

```
android_library(
    name = "my-lib",
    srcs = glob(["src/main/java/**/*.java"]) + [":build-config-genrule"],
   ....
```

**Comment by cgrushko** [comment]
I can write a Skylark macro that emits this `genrule`, and also sets the `DEBUG` constant's value according to the current dynamic configuration. Haven't decided where I'd put it, though.

**Comment by damienmg** [comment]
Since android reassigning to Alex for correct triaging.

**Comment by mhlopko** [comment]
Hello Alex, is this still expected to be fixed in 0.5?

**Comment by ahumesky** [comment]
We haven't had time to look at this in depth, most people can use the genrule mentioned above. We're also working on dynamic configurations within android_binary that could enable a more robust BuildConfig-like rule, where an android_binary could pass configuration down to the BuildConfig-like rule, which would avoid having to have parallel trees of genrules. It's not quite there yet though. I moved this to 0.6.

**Comment by mhlopko** [comment]
Cool, thanks for the info and moving to 0.6.

**Comment by pfn** [comment]
```python
def _values_to_const(k, vs):
  return "public final static %s %s = %s;" % (vs[0], k, vs[1])

def _build_config_impl(ctx, **kwargs):
  o = ctx.actions.declare_file("BuildConfig.java")
  head = [
    "package %s;" % ctx.attr.package,
    "public class BuildConfig {",
  ]
  xs = []
  debug = "false" if ctx.var['COMPILATION_MODE'] == "opt" else "true"
  values = ctx.attr.values + {
    "DEBUG": ["boolean", 'Boolean.parseBoolean("%s")' % debug],
    #"APPLICATION_ID": ["String", '"TODO"']
  }
  for x in values:
    xs.append(_values_to_const(x, values[x]))
  last = ["}"]
  ctx.actions.write(o, "\n".join(
    head + xs + last
  ))
  return [DefaultInfo(files = depset([o])), OutputGroupInfo(all_files = depset([o]))]

build_config = rule(
  implementation = _build_config_impl,
  output_to_genfiles = True,
  attrs = {
    "values": attr.string_list_dict(doc = "BuildConfig values, KEY -> [TYPE, VALUE]"),
    "package": attr.string(mandatory = True, doc = "package for generated class"),
    #TODO "application_id": attr.string(mandatory=True),
  },
)
```

I wrote something like this for generating a BuildConfig.java

**Comment by cgruber** [comment]
For what it's worth, I did something very similar to @pfn  but then merged it into a company-local version of android_library so you can just do
```
load(..., "my_android_library")
my_android_library(
  //normal stuff,
  constants = [
    'String FOO = "foo"'
  ]
)
```

That said, I think it should be smarter, but for now, in our context, that's good enough. I'd probably rather it be a stronger tuple of stuff, like:

```
load(..., "my_android_library")
my_android_library(
  //normal stuff,
  constants = [
    ("String", "FOO", "foo"),
    ("long", "BAR", 4),
    ("my.custom.Type", "BAR", "my.custom.Type.INSTANCE"),
  ]
)
```

and have it figure out string literals and primitive types and pass those in as literals, and then for everything else pass in the value string as an expression.   Though honestly it's a bit overkill.

**Comment by feliwir** [comment]
Is there any chance something similar to `BuildConfig` will land in a new release?

**Comment by ahumesky** [comment]
Something like this would likely not be part of a bazel release itself, but released separately as part of the tools_android repo: https://github.com/bazelbuild/tools_android

It will probably be very similar to what pfn@ shared above (or even simpler, such as a macro and a genrule as shared at the top of the issue).

**Comment by ahumesky** [comment]
I took a few minute to look at what would be needed to generate a compatible BuildConfig file.

This appears to be the task that generates the BuildConfig:
https://android.googlesource.com/platform/tools/build/+/16c22b991956b6ad6ac4634b2b9aa88bea8eb335/gradle/src/main/groovy/com/android/build/gradle/tasks/GenerateBuildConfig.groovy

It looks like the default items are "DEBUG", "PACKAGE_NAME", "BUILD_TYPE", "FLAVOR", "VERSION_CODE", "VERSION_NAME", and the other flavors in the build.

Build type and flavor aren't applicable to bazel, so compatible entries for those would probably have to be manually created.

Debug can be derived from --compilation_mode, as in the code from @pfn. (The value of this flag is also what is used to set "debuggable" in the AndroidManifest)

Automatically filling in the package name, version code, and version name is somewhat tricky. These values initially come from the AndroidManifest, and can be overridden in android_binary.manifest_values. This means that the final values for these entries are not available until after manifest processing, which happens in android_binary, which means that any macro or starlark rule won't have access to these values.

Generating a build config file could happen within android_binary after manifest processing, but this means that java compilation couldn't be parallelized with manifest processing (since the java code would depend on the BuildConfig file). This also means that code in android_library targets below the android_binary couldn't depend on the BuildConfig. One way around that is to generate a stub BuildConfig, where the final values are filled in at the top level, like what's done for the R file. This is a lot of trickery though just to avoid duplicating a few values. These could probably be de-duplicated at the build file level through macros or variables.

**Comment by gydeveloper** [comment]
Hello,

Our team is exploring building via bazel. We have about 300+ modules. 

I understand that the existing solution of putting a `genrule` in our bzl files works, but what is the plan to get this as part of the tool itself? This will avoid users such as us with 300+ modules to have such a genrule for each module.

Thanks!

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
