### ISSUE TITLE
Stop unconditionally adding -B/usr/bin flag to C/C++ toolchains

### ISSUE THREAD

**Issue by georgi-d** [bazelbuild/bazel#5634]
The addition of this flag was done as a fix to Issue #760 

The problem with this is that it completely breaks any custom toolchain setup because it forces use of tools such as `ld`, `as`, `ar` and others from /usr/bin. And since this is added so early in the process it is not possible override it in the build files.

I see that the original problem in #760 was that `process-wrapper` and `build-runfiles` could not run because they failed to find libstdc++ which has a better solution to just link them statically as described in #4137

At the end of #760 there are other comments mentioning that hard coding -B/usr/bin is wrong.

**Comment by mhlopko** [comment]
Thanks for the report. I don't plan to work on this until https://github.com/bazelbuild/bazel/issues/5187 is done. And I can see an universe in which we won't need so many env vars to tweak C++ toolchain. But nothing concrete yet. If this is urgent, let me know, and I will help the PR.

**Comment by ilya-biryukov** [comment]
+1 to fixing this. This blocks using non-standard toolchains with bazel.
E.g. in our experiments with downloading a toolchain on-the-fly in Tensorflow, we can't currently use the LLD linker from the downloaded package, because -B flag is added by bazel and can't be overriden (so we end up picking LLD in /usr/bin/ if it's installed).

My intuition is that there should be a fix for https://github.com/bazelbuild/bazel/issues/760 that does not involve setting -B.
