### ISSUE TITLE
rules_go failing in downstream projects

### ISSUE THREAD

**Issue by dkelmer** [bazelbuild/bazel#5682]
The rules_go pipeline is failing with bazel at head.

Buildkite run: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/360#c239be72-20fc-4c59-ad7a-e5b852efc108

ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-x775-1/bazel-downstream-projects/rules_go/proto/wkt/BUILD.bazel:3:1: in compilers attribute of go_proto_library rule //proto/wkt:descriptor_go_proto: '//proto:go_proto_bootstrap' does not have mandatory providers: 'GoProtoCompiler'.

Jay, do you know what is going on?

**Comment by jayconrod** [comment]
@dkelmer I looked into this a bit. I think it's related to the fix for #3115 (thanks for working on it by the way, and sorry I didn't have time to verify it earlier). I think we're getting an error because we're expecting the `GoProtoCompiler` provider from `@io_bazel_rules_go`, but we're getting the provider from `@` (they should be the same).

I was able to reproduce this with 5194dfd8bafd27dfc2d86efba1265bf2b8b3fa78 (I wasn't able to build directly from master, but this is pretty recent). I noticed that I'd get the error when building `//proto/wkt:duration_go_proto` but not `@io_bazel_rules_go//proto/wkt:duration_go_proto`. Those labels should refer to the same target.

There are a couple of BUILD.bazel and .bzl files that load symbols from `//proto` instead of `@io_bazel_rules_go//proto`. I tried changing those, but it didn't make the issue go away, so I don't think it makes a difference.

I made a minimal example that reproduces the issue. You can apply the patch below in an empty directory with `patch -Np1 -i repro.patch`.

```
diff -urN a/proto/BUILD.bazel b/proto/BUILD.bazel
--- a/proto/BUILD.bazel	1969-12-31 19:00:00.000000000 -0500
+++ b/proto/BUILD.bazel	2018-07-27 13:22:32.567251101 -0400
@@ -0,0 +1,6 @@
+load("//proto:compiler.bzl", "go_proto_compiler")
+
+go_proto_compiler(
+    name = "go_proto_bootstrap",
+    visibility = ["//visibility:public"],
+)
diff -urN a/proto/compiler.bzl b/proto/compiler.bzl
--- a/proto/compiler.bzl	1969-12-31 19:00:00.000000000 -0500
+++ b/proto/compiler.bzl	2018-07-27 13:19:25.692736252 -0400
@@ -0,0 +1,8 @@
+GoProtoCompiler = provider()
+
+def _go_proto_compiler_impl(ctx):
+    return [GoProtoCompiler()]
+
+go_proto_compiler = rule(
+    _go_proto_compiler_impl,
+)
diff -urN a/proto/def.bzl b/proto/def.bzl
--- a/proto/def.bzl	1969-12-31 19:00:00.000000000 -0500
+++ b/proto/def.bzl	2018-07-27 13:24:31.328852437 -0400
@@ -0,0 +1,14 @@
+load("@example_repo//proto:compiler.bzl", "GoProtoCompiler")
+
+def _go_proto_library_impl(ctx):
+    return []
+
+go_proto_library = rule(
+    _go_proto_library_impl,
+    attrs = {
+        "compilers": attr.label_list(
+            providers = [GoProtoCompiler],
+            default = ["@example_repo//proto:go_proto"],
+        ),
+    },
+)
diff -urN a/proto/wkt/BUILD.bazel b/proto/wkt/BUILD.bazel
--- a/proto/wkt/BUILD.bazel	1969-12-31 19:00:00.000000000 -0500
+++ b/proto/wkt/BUILD.bazel	2018-07-27 13:25:00.017239516 -0400
@@ -0,0 +1,7 @@
+load("@example_repo//proto:def.bzl", "go_proto_library")
+
+go_proto_library(
+    name = "duration_go_proto",
+    compilers = ["@example_repo//proto:go_proto_bootstrap"],
+    visibility = ["//visibility:public"],
+)
diff -urN a/WORKSPACE b/WORKSPACE
--- a/WORKSPACE	1969-12-31 19:00:00.000000000 -0500
+++ b/WORKSPACE	2018-07-27 13:18:05.919662908 -0400
@@ -0,0 +1 @@
+workspace(name = "example_repo")
```

**Comment by dkelmer** [comment]
Thanks so much for the repro case, the issue is with the load statement in the def.bzl file. If you leave everything as is (or even mess around with the other labels to have/not have @example_repo) but just change the load in def.bzl to be:
load("//proto:compiler.bzl", "GoProtoCompiler")
then the build succeeds. I'm not sure why that's the case yet, but I'm investigating.

**Comment by laurentlb** [comment]
Is it still a release blocker?

**Comment by jin** [comment]
@dkelmer is OOO, I’m not sure what the status is.

**Comment by jayconrod** [comment]
I filed #5971 to track the root cause of the test failure. It sounds like this is intended behavior, so I don't think it should be a release blocker.

I'll disable the failing test when I get a chance and then close this issue when I've verified CI is green. I may be a bit delayed this week -- I'm at GopherCon.

**Comment by laurentlb** [comment]
Duplicate of https://github.com/bazelbuild/bazel/issues/5971
