### ISSUE TITLE
Zipper fails if target name contains the equals sign

### ISSUE THREAD

**Issue by anchlovi** [bazelbuild/bazel#5768]
Bazel `zipper` fails if in the `file_list` there is a target with `=` sign

**Comment by ittaiz** [comment]
@joshfischer1108
<https://github.com/joshfischer1108>
if you are proficient in C this should be a fairly easy issue to pick as
your first one.
I think it’s similar or maybe even a duplicate of the pkg_tar one that you
commented on

**Comment by joshfischer1108** [comment]
@ittaiz Thanks for the message. Let me start looking around and see what I can find.  I'm sure I will have some questions.  I'll make sure to reply to this issue thread to keep conversations all in one spot.

**Comment by joshfischer1108** [comment]
Right off the bat using version `0.16.0` I built a c++ target with `=` in the name and all seemed well.

```
Joshs-MBP-2:scratch joshfischer$ bazel build main/...
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target //main:target=with=sign (10 packages loaded).
INFO: Found 1 target...
Target //main:target=with=sign up-to-date:
  bazel-bin/main/target=with=sign
INFO: Elapsed time: 4.118s, Critical Path: 2.15s
INFO: 4 processes: 4 darwin-sandbox.
INFO: Build completed successfully, 7 total actions
Joshs-MBP-2:scratch joshfischer$ bazel version
Build label: 0.16.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 31 17:10:14 2018 (1533057014)
Build timestamp: 1533057014
Build timestamp as int: 1533057014
```
I'll need to do a little more digging.

**Comment by joshfischer1108** [comment]
I've been able to reproduce the issue #4063 that @ittaiz mentioned earlier.  I'll start working on it this week.

**Comment by ittaiz** [comment]
Great! Is it indeed a problem with the zipper or something else? Because
AFAIR the bug we saw didn’t have pkg_tar

**Comment by joshfischer1108** [comment]
Good point @ittaiz. When I wrote starting to work on it, I meant do more digging to diagnose the issue to understand what the underlying issue is.  Sorry for not writing a clear response!

**Comment by aiuto** [comment]
This is not a Java rules problem. This is a utility issue.
It should be closed.  There is no reason to use @bazel_tools//tools/zip:zipper in your own code.  Use @rules_pkg//:pkg.bzl%pkg_zip  (or pkg_tar) which are easier to use and do not exhibit this bug.

**Comment by aiuto** [comment]
Let me see if I understand. You currently use the zipper executable as something you invoke in a `ctx.actions.run() `from `scala_*()`.    That is, the special thing you care about is having zip available pre-built alongside bazel, more than having a` pkg_zip(`) rule.

If I understand that correctly, then the best path here is fixing ijar, but that is not a quick fix. Without redesigning the input syntax to ijar, it would never be clear how to parse an arg with multiple = signs in it. Would the first = be part of a path, or the delimiter?

**Comment by ittaiz** [comment]
We also use zipper in internal rules in a similar fashion and not all archives we create are jars.
Maybe some escaping is needed (and for the tool to support it)?

**Comment by aiuto** [comment]
Well, yes. We would need to change the tool and possibly any rules that use it. But there is really no way around that, since people are building their command lines any way they want.

I'm not a fan of command line escaping. It is hard to do right portability, in the face of various shells.
What I would prefer is the list of input files output paths was written to a file in a structured manor, then zipper/ijar could read that file and interpret it, without worrying about command line processing.
zipper/ijar already can read pairs from a file, but it would need a bit of work. 

One path forward might be to define a helper in third_party/ijar/def.bzl do invoke the zipper. It would take args for (ctx, File, map{path in jar, File}).  It would create the action to run the zipper, passing args however needed. This would isolate changes to the escaping/encoding to a single method shipped with ijar, so rules would have to migrate once and be done with it.

**Comment by adam-bedrock** [comment]
Did this ever get fixed?
