### ISSUE TITLE
incompatible_bzl_disallow_load_after_statement: Require load() be at the top of bzl files

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5815]
This is a tracking issue for offering a migration solution for
`--incompatible_bzl_disallow_load_after_statement`

This flag would enforce that bzl files have load() statements listed first.

**Comment by ittaiz** [comment]
should the title change? It talks ab out BUILD files but the content seems to be about bzl files?
Also is this a constraint on the WORKSPACE file as well?

**Comment by c-parsons** [comment]
Apologies, yes, this is about bzl files. I've changed the title.
This would not be a constraint on WORKSPACE files.

**Comment by laurentlb** [comment]
We should do the same for BUILD files (we can track it in a separate issue). But not for WORKSPACE files, because they are evaluated in a relatively different way: previous statements affect the semantics of `load`.

**Comment by dslomov** [comment]
What is missing for migration are: migration docs, length of migration window. After these are done, please add "migration-ready" label

**Comment by laurentlb** [comment]
cc @aehlig

**Comment by laurentlb** [comment]
I agree the current situation feels unnatural, mainly because evaluation of WORKSPACE first splits the file. I think we don't split bzl files at all, even when they're loaded from a WORKSPACE file, right? So the main problem with incompatible_bzl_disallow_load_after_statement is that it prevents you from changing the semantics (but it doesn't affect current users)?

We can continue the discussion on the mailing-list, and see what we can do.

**Comment by ittaiz** [comment]
+100. As someone trying to maintain mutual complex definitions over 50
repositories these restrictions are cumbersome.
