### ISSUE TITLE
supply flag for no warning when output base is an nfs mount

### ISSUE THREAD

**Issue by talya** [bazelbuild/bazel#5897]
### Description of the problem / feature request:

This warning causes noise:
`WARNING: Output base '/bazel-nfs-volume/outputs' is on NFS. This may lead to surprising failures and undetermined behavior.`
A flag that could request to supress this warning would allow us to solve this.

### Feature requests: what underlying problem are you trying to solve with this feature?

To allow developing from the IDE on a mac OSx, with bazel running inside a local docker container.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Run bazel with `startup --output_base=../outputs` and get the above warning

###  Have you found anything relevant by searching the web?
#1361 seems to discuss something related, but in our use case we see no issues with the nfs export.

**Comment by ittaiz** [comment]
@dslomov,
Can this flag be added?
Btw,
I think bazel has a lot of existing infra/plumbing which make it non
trivial to contribute such a change.
Wdyt about documenting how one should add a simple configuration option
from cli to consumption in the contributing.md?

**Comment by jmmv** [comment]
This warning comes from the Bazel client so adding a flag isn't that easy/nice.

From what I can see in the code, these warning messages are printed to stderr, not stdout, so the IntelliJ plugin shouldn't be confused and `bazel info`'s output should continue to be parseable. That said, this may not always have been the case. The logging functionality in the client has changed a lot since this was filed, so it wouldn't surprise me if the behavior here changed and this is not an issue any longer.

So... without further data and seeing the current code, I'll say that this is not a big problem any longer. But if you still observe this and is still causing problems, please let us know here.
