### ISSUE TITLE
Bazel query docs suggest deprecated feature

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/bazel#5937]
What's the set of BUILD files needed to build //foo?
```
bazel query 'buildfiles(deps(//foo))' --output location | cut -f1 -d:
```

#4835 deprecated this feature, and now, executing this command outputs
```
ERROR: Query expressions involving 'buildfiles' or 'loadfiles' cannot be used with --output=location
```

**Comment by haxorz** [comment]
Sorry for the lack of response over the past ~20 months.

I'm a little confused about the timeline here:
1.  [Jun 2017] Commit 9e26369575f04776c0416fd75a9434a22b4d5e9a (authored by me, coincidentally) bans `--output=location` in combinarion with `buildfiles` or `loadfiles`
1.  [Mar 2018] Commit 2d0b73e00c6ce0b43108218c7d0073e9f9ded612 (from PR #4835) updated the query-how-to.md doc.
1.  [Aug 2018] This issue was filed.

ISTM that commit 2d0b73e00c6ce0b43108218c7d0073e9f9ded612 fixed the documentation problem, and this issue is complaining about a problem that no longer exists.

Therefore I'm going to close this, but feel free to reopen if I've misunderstood you.

**Comment by petroseskinder** [comment]
Yeah this should have been closed. 

The html still included the [suggestion at the time](https://github.com/bazelbuild/bazel/pull/5936/commits/66f218d4bac0c5577f7e871a847da0504faecab8). You linked to the markdown
