### ISSUE TITLE
int() function's failure behavior decreases its usability

### ISSUE THREAD

**Issue by allevato** [bazelbuild/bazel#5940]
The form of Skylark's `int()` function that takes a string is only useful if you know for sure that the string being passed to it is a valid integer in the desired radix. If it is not (for example, a rule that iterates over `copts` looking for particular flags and wanting to get an integer value from them), then the build fails with an error message similar to the following:

```
invalid literal for int() with base 10: "foo"
```

This unconditional failure makes it impossible for a build rule author to provide a better, more context-specific error message to the user by using just the existing API (or to even _ignore_ the malformed argument and let the tool catch it later, if so desired). They must iterate over the characters in the string and manually verify that it's valid before calling `int()`, which is kind of a drag.

It makes sense that the failure is inherited from Python's semantics of raising `ValueError` in such cases, but at least in Python the user could catch the exception and react differently.

**Comment by laurentlb** [comment]
Sorry, we don't have a good solution for this now.

**Comment by brandjon** [comment]
Yes, this is a general problem with Starlark's (arguably intentional) inability to "ask for forgiveness, not permission".

It'd be ugly to add a separate method or parameter for the sake of checking whether a failure would occur. And we'd really want to be cautious about adding something like an error handling primitive (which we can do now that we have lambdas, and have indeed done for our unit test dialect within Starlark's own test suite).

But I wonder how often this use case comes up, and whether it's generally confined to input validation.
