### ISSUE TITLE
Cannot use --plugin with --distinct_host_configuration=false

### ISSUE THREAD

**Issue by jfancher** [bazelbuild/bazel#5972]
### Description of the problem / feature request:
Attempting to apply a Java plugin at the command line (`--plugin=<label>`) when operating under `--distinct_host_configuration=false` fails to build due to a cyclical dependency.

Presumably, prior to building the requested library, it is trying to compile the plugin target using `--plugin=<itself>`, which is obviously a cycle. I can understand _why_ this would happen given how build configurations [work](https://docs.bazel.build/versions/master/user-manual.html#distinct_host_configuration-false), but it seems less than ideal that this flag makes `--plugin` unusable (and possibly other flags, if there are others that allow you to specify Java labels).

Is there a workaround or proper way to achieve the same effect?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Complete reproducer here:
https://github.com/jfancher/bazel-issues/tree/plugin%2Bdistinct_host_configuration

I would expect any invocation with `--plugin=<some java_plugin>` and `--distinct_host_configuration=false` to behave similarly, though.

### What operating system are you running Bazel on?
MacOS 10.13.2

### What's the output of `bazel info release`?
`release 0.16.1`

###  Have you found anything relevant by searching the web?
Discussion of `--distinct_host_configuration` (and whether or not it's the best long-term option for preventing duplicate compilations) at #5572 is relevant, but I don't see anything that touches on this particular problem.

**Comment by cushon** [comment]
Is your use-case for `--distinct_host_configuration=false` the one discussed in #5572, i.e. improving performance by avoiding building the same code twice? I agree that's nice to avoid, but still think there might be more principled ways for Bazel to support that than `--distinct_host_configuration`.

**Comment by jfancher** [comment]
Yes, it's purely the performance issue of otherwise needing to build many libraries twice. If there were a different/better way to achieve the same thing we would gladly switch!

**Comment by lberki** [comment]
Unfortunately, this doesn't lend itself to an easy solution: one of the reasons for the host configuration to exist is exactly to avoid this kind of dependency cycles. Part of the equation is that we'd like to get rid of `--nodistinct_host_configuration` in favor of platforms and platform-based toolchain resolution.

I'll bounce it to the configurability people hoping that they will be able to say something smart: I'm hoping that once the above plan materializes, the special-cased `host` output directory name goes away and thus we'd be able to avoid building things twice... somehow. It's not obvious because after all, a plugin needs to be built without itself to avoid cyclic dependencies, which we can't do without a configuration transition and it's not obvious how to not have a different output directory for, well, an actually different way of building a target...
