### ISSUE TITLE
ctx.action.run_shell: use_default_shell_env=True overwrites env={...} 

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#5980]
A user writing a new experimental rule ran into this issue, that it seemed that enviornment variables were not being correctly set on an action created with `ctx.action.run_shell`, when `use_default_shell_env=True`. We should probably throw some sort of error when a user tries to specify both `env` and `use_default_shell_env=True`, to avoid this confusion in the future.

**Comment by mboes** [comment]
Yes, at the very least an error. Though I would argue that `use_default_shell_env = True` together with `env` is legit. It would have the following semantics: use the default shell environment, and override/augment it it with mappings in `env`.

**Comment by Globegitter** [comment]
I am also just wondering, why is both together not valid? We do have cases where we want some default env bars set in the rule directly but also need some provided by the user. Right now we use the `env` attribute together with `--define` flags, but being able to pass in env variables from the outside as well would be nice. Especially if we also had functionality as discussed in #6111.

**Comment by c-parsons** [comment]
As long as the semantics are explicitly documented that `env` takes precedence (overwrites the default shell environment) that sounds fine to me.

**Comment by fmeum** [comment]
I came across this issue while working on `cc_static_library`. It seems that right now, a rule has to choose between these two options for any action:
1. Inheriting `PATH` from the client env.
2. Specifying additional environment variables.

In the case of `cc_static_library`, I would need to do both, which doesn't seem possible short of emitting a wrapper script that sets the environment variables and running that in the action.

Starlarkified `cc_import` is using `env` and `use_default_shell_env` together and thus loses the fixed environment variables set in the toolchain: https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/builtins_bzl/common/cc/cc_import.bzl;l=91

@comius @brandjon Could you provide guidance on what ways you would find acceptable to proceed? If `use_default_shell_env = True` is the recommended default, `env` should probably override it instead of be silently discarded. If `use_default_shell_env = True` is no longer recommended, that should be clearly documented. I could work on both.

**Comment by DhanalakshmiDurairaj** [comment]
Hi, 
Greetings to all,
I am working on QNX compiler with Bazel. I need to set few environment variables in toolchain using sys feature and few environment variables in .bazelrc file. In ctx.actions.run, while specifying both use_default_shell_env=True and env, compilation command will get only shell environment variables. 
If I specify build --incompatible_merge_fixed_and_default_shell_env in bazelrc 

**I am getting below error:

ERROR: --incompatible_merge_fixed_and_default_shell_env :: Unrecognized option: --incompatible_merge_fixed_and_default_shell_env**

please help to fix this.

Thanks & Regards,
D.Dhanalakshmi
