### ISSUE TITLE
spurious 'unknown enum constant' warnings

### ISSUE THREAD

**Issue by jfancher** [bazelbuild/bazel#5985]
### Description of the problem / feature request:
* `java_library` **A** depends on `java_import` **B**
* `java_import` **B** depends on `java_import` **C**

Building **A** does not seem to put **C** on the classpath during compilation, which can lead to certain warnings from `javac`; specifically if **B** uses annotations from **C** which embed enums, you can get `warning: unknown enum constant [...]`.

This issue is pernicious when trying to introduce `-Werror` to a large code base, because it doesn't seem to be suppressible through compiler flags ([ref](http://hg.openjdk.java.net/jdk/jdk10/file/b09e56145e11/src/jdk.compiler/share/classes/com/sun/tools/javac/jvm/ClassReader.java#l2171)).

A workaround is to make **A** depend on **C** directly, though this isn't great as it's an otherwise unused dep.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Complete reproducer here:
https://github.com/jfancher/bazel-issues/tree/import-transitive-dep-error

### What operating system are you running Bazel on?
MacOS 10.13.3

### What's the output of `bazel info release`?
release 0.16.1

###  Have you found anything relevant by searching the web?
No, although I wasn't quite sure what to search for.

**Comment by davido** [comment]
You want to use `exports` instead of `deps` in that case. That diff fixed your example:

```
diff --git a/BUILD b/BUILD
index 776bde7..5b7267e 100644
--- a/BUILD
+++ b/BUILD
@@ -24,5 +24,5 @@ java_library(
 java_import(
     name = "dep_import",
     jars = [":libdep.jar"],
-    deps = [":annotation"],
+    exports = [":annotation"],
 )
```

**Comment by jfancher** [comment]
Thanks for the responses.

@ittaiz do you have recommended reading on the subject? I'm aware broadly of strict deps from [this](https://blog.bazel.build/2017/06/28/sjd-unused_deps.html) post (and just using bazel day-to-day), but that doesn't say anything about removing transitive deps from the compilation classpath -- in fact it says the exact opposite ("Bazel always passes the entire transitive classpath to javac, not only the direct classpath.").

I should have noted that I realize that changing to `exports` works (in addition to manually adding a dependency), but I don't quite understand why this is the proper change.

The library **A**  does ***not*** reference anything from library **C** directly, it's the textbook example of an `--indirect_dependency` (per the blog post linked above). I can't get `unused_deps` to detect anything at all for recent versions of bazel, but if it did I would expect it to tag **A** -> **C** as one.

Also as noted in my reproducer, this is only a problem with `java_import` -- a similar example using only `java_library` rules compiles cleanly.

At the very least this seems like a documentation bug, as the [docs](https://docs.bazel.build/versions/master/be/java.html#java_import) for `java_import` delegate to `java_library` docs for `deps` and `exports` without noting that there's anything different in the way they handle transitive deps.

Does this also imply that *all* `deps` on `java_import` should be `exports`? If not, what is the use of `deps` for this rule type?

Is there somewhere in the docs where this is specified that I have missed?

Thanks again!

**Comment by jfancher** [comment]
The issue here is broader than `java_import` -- while my previous example only reproduces with an import, I came up with another one using only `java_library` rules. It's... bizarre. Probably easiest to understand by just looking at it:
https://github.com/jfancher/bazel-issues/tree/lib-transitive-dep-error

Here's the outline:
* **D** is an annotation library, again with an embedded enum
* **C** is a library that depends on **D**
* **B** is a library that depends on **C**
* **B** declares two methods, **M(int)** and **M(CType)**. That is, two methods with the same name and argument count, one that depends on **C** and one which does not
* **A** is a library that depends on **B**
* **A** calls **M(int)** on (but ***not*** **M(CType)**)

This fails with the same error as above unless **A** is given a dep to **C**, which I do not expect from my understanding of strict deps.

The 4th and 6th points are important. Unlike the previous example, it's not just any reference that triggers the bug -- it suggests overload resolution is in some way implicated. I'd be suspicious of a `javac` issue at this point but a direct invocation of the compiler with the classpath I expect still works fine. Something about bazel's usage of it is different. 

I don't think my original title is correct any longer, but I'm not sure how to capture the full issue without being vague so I'll leave it as is for now.

**Comment by ittaiz** [comment]
I’m not an expert on the matter but there are cases where javac needs a
bigger (more transitive) classpath then what you expect (for example
something with interface inheritance due to “default method
implementations” since java 8).
Turbine (IINM) tries to be smart and know when the usage of javac of a jar
is a false positive and so not to flag it but maybe it’s not successful
here.
Cc @cushon to make sure I’m not talking rubbish.

**Comment by cushon** [comment]
"Bazel always passes the entire transitive classpath to javac, not only the direct classpath" doesn't tell the full story. It's true that the transitive inputs are available to the compilation action, but it tries to optimize compilation by using a reduced classpath, i.e. the "reduced classpath optimization".

The reduced classpath optimization uses a heuristic to reduce the number of jars from the compile-time classpath. To do this, it uses the data in `.jdeps` files from a target's direct dependencies. The reduced classpath heuristic is to take:

* all jars for targets that are direct dependencies
* all jars that JavaBuilder needed to read when compiling those direct dependencies (as reported by that dependency's `.jdeps` file)

The heuristic is not perfect: sometimes it includes jars that were needed for a dependency, but are not needed by its clients. And sometimes it fails to include a jar that wasn't needed by the direct dependency, but is needed by the current compilation.

Including too few jars may causes a compilation failure. To recover from that, JavaBuilder recognizes certain compilation errors that may have been caused by a too-aggressive reduced classpath, and retries the compilation with the full transitive classpath.

The `unknown enum constant` warnings reported above are not in the set of warnings that cause it to try with the full transitive classpath.

We could change that, but as far as I know the warnings are harmless. Making them go away by explicitly adding deps or changing the reduced classpath behaviour would affect performance and would not change build output. It would be nice if `-Werror` provided a way to promote individual diagnostic categories to errors, instead of the current all-or-nothing approach.

**Comment by jfancher** [comment]
That is enlightening, thank you for the explanation!

I agree the warnings are harmless -- if I could find a way to just make them go away entirely I would. But there doesn't seem to be a flag to suppress them (similar warnings are under `-Xlint:classfile`, not sure why these are different).

It's unfortunate that such a small issue is a blocker for turning on `-Werror`. My second example may seem contrived, but it's a very stripped down version of a common pattern in our code. So it's not a matter of changing one or two things. And the workaround of "export this specific kind of dep under these obscure circumstances" isn't easy enough to communicate to be worth it.

I don't suppose there's any other options I'm missing that could make this work for us?

I guess one alternative is to reimplement the specific lints I care about as errorprone checks. Kind of roundabout, but there are only a few that really matter, so it could work. Unfortunately that would require a resolution to #5972 with our current setup.

**Comment by cushon** [comment]
I wish javac allowed `-Xlint` control of this diagnostic, and that it supported enabling individual diagnostics as errors (e.g. something like `-Werror:unchecked,rawtypes`). Maybe it will some day, but we should find a way to work around this in Bazel in the shorter-term.

I'll think about whether there's a way for Bazel to suppress the `unknown enum constant` warnings.
