### ISSUE TITLE
required_aspect_providers doesn't actually make things required

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#6080]
### Description of the problem / feature request:

https://docs.bazel.build/versions/master/skylark/lib/globals.html#aspect
required_aspect_providers is an argument to `aspect` that controls what providers of other aspects that are being applied to dependencies are made available to this aspect. The name makes it sound like if these cannot be found then it is an error because they are *required* but that is not the case and nothing happens if they cannot be made available. Given that the reason I'm trying to make the providers available is to use them, it would be much easier to debug broken usages if it was actually required. Given the list of list structure of the argument, optionality can be encoded by adding extra lists without the optional providers.

### Feature requests: what underlying problem are you trying to solve with this feature?
Improve debugging of broken aspect code.

**Comment by jin** [comment]
@laurentlb @c-parsons could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by laurentlb** [comment]
@dslomov - do you know a reason why it's not an error?

**Comment by dslomov** [comment]
Sorry for not replying earlier!
It is not an error because it is not an error -by design :)
`aspect_required_providers` is a mechanism to restrict visibility of aspects into other aspects - it is perfectly ok for aspects to be not aware of other aspects. Our documentation in this area can certainly be improved, but here are some design documents that I have just made public (they are from the thankfully bygone era when we didn't default to public for design docs):

* [Aspects-on-aspects](https://docs.google.com/document/d/1TXiG3mqX19akwhJ_1Zjxpqrxov3XFsicj78VuhyO0Ts/)
* [Aspect required providers](https://docs.google.com/document/d/1WZmUsCrI2RkUyIqUVVVgIgDKIpaXsMzKPDGTeJzGfi0/)
