### ISSUE TITLE
Add worker TTL option

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/bazel#6103]
Keeping workers is a balance between their startup, memory usage, number of workers, and frequency of use.

Bazel itself has `--max_idle_secs` (default 3 hours). For some workers, it may make sense to have a different value. For example, if you have up to fours workers, they take 3s to start, each consumes 250MB, and you use workers for several other strategies, you will likely want a lower TTL than 3 hours.

Suggested flag:

```
--worker_max_idle_secs=name=value
```

Alternatively, other options like max total workers or max memory usage per time of inactivity could control worker resource consumption. This worker max TTL is simple though.

**Comment by philwo** [comment]
Sounds like a nice improvement.

**Comment by pauldraper** [comment]
Two workarounds:

1. Add the TTL to the worker process itself. That's clumsy and perhaps has race conditions.
2. Shorten the TTL of Bazel itself (`--max_idle_secs`).

EIther of these solves the problem of workers using a bunch of memory for hours.

**Comment by pauldraper** [comment]
An instance of the "worker uses too much memory" problem: #12466

**Comment by larsrc-google** [comment]
@susinmotion Relevant to your resources work.

**Comment by susinmotion** [comment]
I'm afraid I won't be picking up the worker resources work any time soon. Unassigning to give this task a chance to be picked up by the right folks.

**Comment by larsrc-google** [comment]
The worker pool is a GenericKeyedObjectPool, which has idle-time based eviction: [setMinEvictableIdleTimeMillis](https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#setMinEvictableIdleTimeMillis-long-) and [setMinSoftEvictableIdleTimeMillis](https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/BaseGenericObjectPool.html#setSoftMinEvictableIdleTimeMillis-long-) - the latter allows for keeping some minimum amount of workers idling for longer than that.

A quick fix would be to set those to fractions of `--max_idle_secs`. I doubt that there's much point in doing a separate soft eviction, since typically once a worker gets used, there are likely more actions requiring more workers coming at the same time.

**Comment by larsrc-google** [comment]
If your workers support multiplexing, make sure that is turned on, and your memory consumption should at least be smaller. It's now the default for Javac.

**Comment by pauldraper** [comment]
Yeah, multiplexing is definitely nice for JVM workers (not Node.js workers tho).

**Comment by larsrc-google** [comment]
@wilwell 's work on evicting idle workers at higher memory pressure is probably the better way to handle this.
