### ISSUE TITLE
Release - July 2018 - name: 0.16.2

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6132]
Patch release on top of 0.16.1: https://github.com/bazelbuild/bazel/issues/5792

New cherrypicks:
 - 282b8839ef114aa70e18d98a3e6f5fa8dbed4ef9

Anything else?
@cushon @lberki

**Comment by laurentlb** [comment]
Tests are failing: https://buildkite.com/bazel/release/builds/98#cda3745a-1830-4ac8-a1c5-093817590c2a

This is failing:

ERROR: /var/lib/buildkite-agent/builds/buildkite-worker-ubuntu1404-java8-lqvt-1/bazel/release/src/main/java/com/google/devtools/build/lib/windows/runfiles/BUILD:9:1: Building src/main/java/com/google/devtools/build/lib/windows/runfiles/librunfiles.jar (1 source file) failed (Exit 1)
  | Fatal Error: Unable to find package java.lang in classpath or bootclasspath

**Comment by cushon** [comment]
The fix in 282b8839ef114aa70e18d98a3e6f5fa8dbed4ef9 only works with a JDK 10 `--host_javabase`, not JDK 9. It works ahead at head because of some changes I made in 4566a428c5317d87940aeacfd65f1018340e52b6, which was before we rolled back to a JDK 9 `--host_javabase` in 7eb9ea150fb889a93908d96896db77d5658e5005.

4566a428c5317d87940aeacfd65f1018340e52b6 depends on other changes to `DumpPlatformClassPath` and doesn't apply cleanly to 0.16.2.

My recommendation is to backport the latest version of `DumpPlatformClassPath`. Here's a commit that does that: https://github.com/cushon/bazel/commit/d6a438d29498ea00b38bc3069ec06f5793da4569

**Comment by gertvdijk** [comment]
Would appreciate a cherry-pick of the fix in #6020 as well.

<sup>(not sure why I see several duplicate commits referenced there, so not sure which to request?)</sup>

**Comment by cushon** [comment]
@lberki @laurentlb what are your thoughts on https://github.com/bazelbuild/bazel/issues/6132#issuecomment-420726643?

**Comment by laurentlb** [comment]
So I used your commit (https://github.com/cushon/bazel/commit/d6a438d29498ea00b38bc3069ec06f5793da4569) and it helped a bit. I got other issues on the CI:
https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/442#49a7f000-e511-4d0d-9714-cfc06a9fb8e1

Since 17.2 was ready (and now released) and should fix the issues, I didn't investigate more. So I now plan to abandon the 16.2.

**Comment by katre** [comment]
Closing issue since the 0.16.2 release was abandoned.
