### ISSUE TITLE
Bazel cannot not build itself with Xcode 10

### ISSUE THREAD

**Issue by jgavris** [bazelbuild/bazel#6144]
### Description of the problem / feature request:

Unable to build bazel from source using bazel 0.16.1 and Xcode 10.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```shell
jgavris in ~/code/software/bazel on (HEAD detached at 2da247fc71)
λ bazel clean --expunge
WARNING: Running Bazel server needs to be killed, because the startup options are different.
Starting local Bazel server and connecting to it...
INFO: Starting clean.
jgavris in ~/code/software/bazel on (HEAD detached at 2da247fc71)
λ bazel build //src:bazel-bin
Starting local Bazel server and connecting to it...
INFO: Analysed target //src:bazel-bin (227 packages loaded).
INFO: Found 1 target...
ERROR: /Users/jgavris/code/software/bazel/third_party/ijar/BUILD:67:1: undeclared inclusion(s) in rule '//third_party/ijar:zipper':
this rule is missing dependency declarations for the following files included by 'third_party/ijar/zip_main.cc':
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/errno.h'
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/sys/errno.h'
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/sys/cdefs.h'
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/sys/_symbol_aliasing.h'
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/sys/_posix_availability.h'
```

### What operating system are you running Bazel on?

macOS 10.13.6

### What's the output of `bazel info release`?

release 0.16.1

**Comment by scalbatty** [comment]
We're having a similar error when building a project depending on Protobuf when specifying `xcode_version=10.0` in the build parameters:

```
ERROR: /private/var/tmp/_bazel_pbatty/0281ba5d35574f3891a7ae268665b19a/external/com_google_protobuf/BUILD:64:1: undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf_lite':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/stubs/stringprintf.cc':
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/string.h'
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/_types.h'
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/sys/_types.h'
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/sys/cdefs.h'
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/sys/_symbol_aliasing.h'
  '/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include/sys/_posix_availability.h'
...
```

**Comment by aragos** [comment]
`undeclared inclusion` errors usually happen because there's a dependency on a header that's not part of a target's `deps` attribute. System headers like the ones here should not trigger that error, this is achieved by adding them to the toolchain description (in the CROSSTOOL file) as part of the `cxx_builtin_include_directory` entries.

On macOS we compute the location of these `cxx_builtin_include_directory` entries using [this logic](https://source.bazel.build/bazel/+/master:tools/cpp/osx_cc_configure.bzl;l=31?q=osx_cc_configure.bzl). As you can see we use each Xcode's [computed `developer_dir`](https://source.bazel.build/bazel/+/master:tools/osx/xcode_locator.m;l=165?q=xcode_locator&ss=bazel) as that's where the headers used to be until now.

For Xcode 10 either the location of the headers has changed or something is weird in your setup, I'm still investigating which.

**Comment by aragos** [comment]
So far we haven't been able to replicate the issue with Xcode 10. Can you make sure of the following:

- open Xcode 10 and install anything it asks you to on first start
- run `bazel clean --expunge`

And then try again? Xcode isn't fully initialized without first opening it by hand once...

**Comment by jgavris** [comment]
What I did was download / extract Xcode 10 to `~/Downloads/Xcode.app`, and then ran `sudo xcode-select ~/Downloads/Xcode.app`. I think did `bazel clean --expunge` and `bazel build` as above. Does that help?

**Comment by jgavris** [comment]
And yes @aragos I've built some non-bazel projects in Xcode 10 prior to trying to build bazel.

**Comment by thomasvl** [comment]
After you moved it, did you repeat the `bazel clean --expunge`?  Bazel cache's things.  Also, double check that _Preferences > Locations > Command Line Tools_ agrees with where it is installed (and isn't blank).

**Comment by jgavris** [comment]
@thomasvl yes, definitely `clean --expunge` bazel after I moved. And the command line tools points to `/Applications/Xcode10.app`.

**Comment by jgavris** [comment]
So I installed the [command line tools for Xcode 10 / macOS 10.13.6 DMG](https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_macOS_10.13_for_Xcode_10/Command_Line_Tools_macOS_10.13_for_Xcode_10.dmg) in addition and it's all good now. Perhaps related to changes in packaging in preparation for 10.14. I'll note this _only_ works if the command line tools are installed from this disk image package. If I do `xcode-select --install` then it's still broken as above.

**Comment by kastiglione** [comment]
I ran into this while trying to update rules_swift to use xcode10 on CI. I documented the results here: https://github.com/bazelbuild/rules_swift/pull/63#issuecomment-427121439. I also filed #6307 because that made debugging the issue harder. There have been no comments on that issue.

---
xcode10 investigation summary: What I've been able to learn is the following:

1. The clang frontend is being invoked with an `-isysroot` flag pointing to `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk`, which is not a declared input.
2. The clang driver populates `-isysroot` via the `SDKROOT` environment variable ([clang source](https://github.com/llvm-mirror/clang/blob/76b0fc13b49bfc60789573467260e0d126c3049d/lib/Driver/ToolChains/Darwin.cpp#L1533-L1541))
3. `xcrun` invokes clang with an `SDKROOT` variable, and `xcrun` does have the string `"/Library/Developer/CommandLineTools"` in its binary, so it may be falling back to that value for some reason, the logic around this is not documented as far as I could find.
4. It seems there's some sort of issue passing flags and environment variables to the protobuf build. I tried `--copt="-v"` and that didn't pass through to protobuf compiles, and I also tried setting the `xcrun_log` and `xcrun_verbose` variables, to debug `xcrun` to see where the `CommandLineTools` path is coming from, but this did not work.

I'd like to know more about how external targets are built, that might shed light to the problem (see item 4 above).

**Comment by arguile-** [comment]
We ran into this issue with protobuf as well for multiple version of Bazel on OS X Mojave (10.14) after a system update.

```
ERROR: /private/var/tmp/_bazel_user/c5396df46b8d6253ade7faf6f19ea6a9/external/com_google_protobuf/BUILD:260:1: undeclared inclusion(s) in rule '@com_google_protobuf//:protoc_lib':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/compiler/zip_writer.cc':
   '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/wchar.h'
   '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/_types.h'
   '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/includ
...
```

On Mojave with the Xcode version 10.1 and the latest system update for CLI tools (release date 2018-10-30) this is resolved for us.

**Comment by jdelfino** [comment]
I've made some headway on this. I noticed that my builds were failing when trying to compile protoc for the host. I also noticed that `APPLE_SDK_PLATFORM` and `APPLE_SDK_VERSION_OVERRIDE` were not being set for host build steps (but were being set for target cpu steps).

It appears that either the default TARGET_CPU is set incorrectly on OS X, or Bazel is incorrectly deciding that the default TARGET_CPU on OS X is not an ApplePlatform.

My TARGET_CPU is `darwin`:
```
bazel info --show_make_env | grep TARGET_CPU
INFO: Invocation ID: 7ba7bc7b-157a-42c6-9ab1-c67cc486b5a5
TARGET_CPU: darwin
```

But the code seems to expect `darwin_x86_64`: https://github.com/bazelbuild/bazel/blob/0ccee07ffca4c2da0788efdd01c9a724d3e94cc1/src/main/java/com/google/devtools/build/lib/rules/apple/ApplePlatform.java#L56

For context, `isApplePlatform`, which uses those CPU maps, is called from here before setting `APPLE_SDK_PLATFORM` and `APPLE_SDK_VERSION_OVERRIDE`: https://github.com/bazelbuild/bazel/blob/4348e3ca10f6e2bc1bed925c51524ed78d0059ef/src/main/java/com/google/devtools/build/lib/rules/apple/cpp/AppleCcToolchain.java#L118

I'm guessing I'm seeing this on Travis, but not on my Macbook, because the Travis OS X (XCode 10.1) images are weird in a way that prevents things from building if `APPLE_SDK_PLATFORM` and `APPLE_SDK_VERSION_OVERRIDE` are not set correctly.

Setting `--host_cpu=darwin_x86_64` works around the issue for me.

**Comment by keith** [comment]
I've submitted a PR which would likely solve the `--host_cpu` issue https://github.com/bazelbuild/bazel/pull/7062 it was mentioned in the TODO I edited that this change should be made so hopefully that helps.

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/7151 has landed on master which I think will fix this issue without having to pass `--host_cpu`, if someone could verify that'd be great!

**Comment by davido** [comment]
A similar issue was reported to Gerrit Code Review issue tracker: [1], related to Bazel 0.24 and OS X upgrade to 10.14:

```
ERROR: [path]/gerrit/polygerrit-ui/app/BUILD:10:1 undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf':
this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/struct.pb.cc':
'/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stddef.h'
'/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/__stddef_max_align_t.h'
'/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stdint.h'
'/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/stdarg.h'
'/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include/limits.h'
INFO: Elapsed time: 28.125s, Critical Path: 1.82s
INFO: 269 processes: 268 remote cache hit, 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
```
[1] https://bugs.chromium.org/p/gerrit/issues/detail?id=10674

**Comment by keith** [comment]
I never tested this with a machine that only has the command line tools so there could be a different issue in that case

**Comment by jmmv** [comment]
A lot has changed in the way we find Xcodes and cache their presence since this issue was fixed... so I'll have to assume, given that there are no new reports about this, that the problems are now gone. Please respond otherwise.
