### ISSUE TITLE
installing bazel via brew not getting the latest version

### ISSUE THREAD

**Issue by wayou** [bazelbuild/bazel#6157]
<img width="635" alt="qq20180915-171020 2x" src="https://user-images.githubusercontent.com/3783096/45584658-426c3780-b90a-11e8-9d3d-eed0ba93bc95.png">

**Comment by regisd** [comment]
AFAIK Homebrew is a third-party project.
Updating to the latest version should be as easy as updating the [Homebrew formula](https://formulae.brew.sh/api/formula/bazel) defined in https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazel.rb

**Comment by wayou** [comment]
I'm following the guide from [bazel documentation](https://docs.bazel.build/versions/master/install-os-x.html)

**Comment by davido** [comment]
Since recently Bazel supposed to be installed using [own homebrew-tap](https://github.com/bazelbuild/homebrew-tap). See this [Blog Post](https://blog.bazel.build/2018/08/22/bazel-homebrew.html).

Concerning Bazel 0.17.1 that was released yesterday, the PR to bump to Bazel homebrew-tap [is still pending for review](https://github.com/bazelbuild/homebrew-tap/pull/4).

**Comment by philwo** [comment]
I fixed some stuff in our Homebrew repo and can no longer reproduce this on my own machines.

Does it work now? Homebrew via our own tap should install Bazel 0.18.0 now.

**Comment by wayou** [comment]
Works now!
