### ISSUE TITLE
Allow http_archive to set output

### ISSUE THREAD

**Issue by whilp** [bazelbuild/bazel#6273]
### Description of the problem / feature request:

`ctx.download_and_extract` supports an `output` positional param that allows the caller to specify the target for extraction. `http_archive` does not expose this as an attr. Instead, callers have to manipulate the archive after extraction (with a genrule?).

### Feature requests: what underlying problem are you trying to solve with this feature?

Purpose: simplify the extract workflow. This is particularly useful when the source archive file is named after a specific version (eg `foo-<commit>`) and the caller would like to make it available without that suffix (eg as `foo`).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

n/a

### What operating system are you running Bazel on?

Ubuntu 18.04.

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.17.2
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a

###  Have you found anything relevant by searching the web?

Relevant code:

https://github.com/bazelbuild/bazel/blob/1d704346ae03ec36d8975949888759dcbf8c6cf4/src/main/java/com/google/devtools/build/lib/skylarkbuildapi/repository/SkylarkRepositoryContextApi.java#L305-L316
https://github.com/bazelbuild/bazel/blob/050e0ff8307a249666d5e7f8a27357bc675a1df6/tools/build_defs/repo/http.bzl#L48-L54

### Any other information, logs, or outputs that you want to share?

n/a

Thanks!

**Comment by aehlig** [comment]
> @aehlig wdyt?

To be honest, I don't understand the use case.

For `http_file`, I understand the desire to set the file name, as
some tools attach some semantics to the way file is named (especially
the "ending") and that's why a similar feature was added there
recently. For `http_archive`, however, the archive is unpacked,
so only the content should matter; for the described scenario
(version-numbers embedded into the archive paths), `strip_prefix`
is the established way of handling it.

Scenarious where I can immagine the `output` parameter of
`download_and_extract` being useful are where several archives are
combined to a single tree---but `http_archive` is specificially
designed to fetch only a single archive.

Nevertheless, if a compelling use case is described, I'm happy to
review a pull request.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by meisterT** [comment]
Closing as there was no further response.
