### ISSUE TITLE
Test various compression algorithms for the bazel binary

### ISSUE THREAD

**Issue by meisterT** [bazelbuild/bazel#6318]
They may affect binary size, decompression and extraction speed.

Things to try: brotli, zoepfli, zlib, gz

**Comment by baryluk** [comment]
Not a perfect methodology, but I just took a pre-compiled bazel 0.20 for 64-bit Linux, run it and then done some tests on `~/.cache/bazel/_bazel_user/install/3aadb0885b1cb52846820562c39bed63/_embedded_binaries` directory.

AMD 2950X, DDR4-3200 ECC, all input and output data in memory backed filesystems and caches. Linux 4.18.


Test name                 | Size      | Runtime
------------------------- | --------- | -------
Original binary           | 173026232 | 1.68s
Second run                | -         | 0.74s
`.../_embedded_binaries/` | 310526286 | -
tar                       | 311214080 | 0.13s
tar.gz (gzip -6)          | 170102107 | 1.58s
tar.bz2                   | 157736665 | 9.74s
tar.7z                    | 125130702 | 5.84s
tar.xz                    | 131641348 | 6.98s
tar.zst (zstd / zstd -3)  | 163888338 | 0.42s 
tar.zst (zstd -6)         | 157385878 | 0.43s
tar.zst (zstd -9)         | 155396115 | 0.44s
tar.zst (zstd -19)        | 141284906 | 0.49s
tar.lz4 (lz4 -9)          | 178569048 | 0.40s
tar.lzo (lzop -9)         | 176166773 | 0.68s
tar.br (brotli -Z)        | 124703022 | 1.25s


Runtime is a wall clock time to decompress and untar into (memory backed) file system. 

zoepfli not tested, because it will be similar to gzip, and decompression speed will be similar (~1.6s). 

7z and few other compressor have a native support for multiple files, but these was not tested. Only tar + single file compression.

Compression with brotli (note that -Z aka -q 11 is a default) takes ages! It takes about 11 minutes on my machine! All the other compressors finish in few seconds, and below 1 minute for xz/7z/bz2 or zstd -9.

In my opinion zstd provides excellent benefits, good compression ratio, very fast decompression and practical compression speeds. zstd -19 takes 72 seconds on my machine.

**Comment by meisterT** [comment]
Thanks for testing! Do you happen to have a script handy to do that? If so, please rerun on the a bazel built from HEAD (with minimal JDK, after commit a7f07cb45358f84bc2c1b74c7b21481385845b6d).

**Comment by meisterT** [comment]
Scratch that. We broke the build and the commit was rolled back. I'll update the bug once this is in a testable state again.

**Comment by meisterT** [comment]
We reduced size at HEAD signifcantly (~70MB now) so we might want to rerun those numbers.

**Comment by meisterT** [comment]
We have no plans to replace the compression algo at this point, so I am closing this.
