### ISSUE TITLE
Documentation on cc_library includes is wrong

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#637]
The documentation (http://bazel.io/docs/be/c-cpp.html#cc_library) says that the 'includes attribute adds directories with the '-iquote' where in fact it is with '-isystem'.

Documentation in code:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/cpp/BazelCppRuleClasses.java#L371

**Comment by bsilver8192** [comment]
Technically, as of b1983bec912ada50b68c26cb72e34c7eaaf9250f you can actually configure it in CROSSTOOL. There's also an undocumented `--use_isystem_for_includes` flag which looks like it affects the behavior. I'm not sure how much of that complexity should be mentioned in which parts of the docs; it's a hard decision because CROSSTOOL isn't documented at all (see #59).
