### ISSUE TITLE
incompatible_disable_depset_in_cc_user_flags: Disable depsets in C++ toolchain API in user flags

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/bazel#6383]
Incompatible change.

If true, Bazel will no longer accept depsets in user_compile_flags for create_compile_variables, and in user_link_flags for create_link_variables. Use plain lists instead.

[Migration docs](https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#disable-depsets-in-c-toolchain-api-in-user-flags).

**Comment by dslomov** [comment]
Did the flag flip land?

**Comment by dslomov** [comment]
Seems not at [0.20](https://github.com/bazelbuild/bazel/issues/6117) cut

**Comment by mhlopko** [comment]
Not yet, waiting for intellij plugin to migrate. Since this is not time critical and affects all plugin users I decided to wait a bit.

**Comment by benjaminp** [comment]
Why was this done rather than exposing the `LinkOptions` class to Starlark?

**Comment by hlopko** [comment]
Because:

1) We don't see linkopts used often enough for quadratic behavior be a problem serious enough to block explosing the API
2) We planned to introduce NestedList when 1) becomes a problem
3) But then serialization became a problem and there is now [symbolForEquality](https://source.bazel.build/bazel/+/3d47f74f6688480ad3fb390ba97ed96cc28cc8a0:src/main/java/com/google/devtools/build/lib/rules/cpp/LibraryToLink.java;l=70) in LinkOptions  and it's not clear yet how will it look like in Starlark.

Not sure this is satisfying answer :)

**Comment by benjaminp** [comment]
It's definitely more satisfying than nothing. :) In general, it would be nice to have the justification for a incompatible change in its official issue. I understand the reason here is that the old way was very broken, but how was I supposed to learn that besides guessing or reading 52b208efda6d02c1ea140e6bdcc0b814c6c1788d?

As for why not depset, not expecting too many user link flags is reasonable enough. Serialization is another matter. There's never been any public explication of that project to my knowledge. I don't know at all why a list of strings has to be distinguished across configured targets.

**Comment by hlopko** [comment]
Yup I agree that this incompatible change wasn't well documented, it was one of the pioneering incompatible changes, before we had a set policy. I think we did much better with later changes (I have https://github.com/bazelbuild/bazel/issues/6861 to scare you :)

@dslomov could you comment on the serialization point?

**Comment by dslomov** [comment]
The goal for C++ rules is to be rewritten in Starlark eventually. Which means that after we expose `LinkOptions` we will need to rewrite it in Starlark somehow later anyway, whereas in the current design no special classes are exposed.
