### ISSUE TITLE
Porting Bazel to AIX

### ISSUE THREAD

**Issue by azhar084** [bazelbuild/bazel#6390]
### Description of the problem / feature request:

Could not find java.lang.Object on bootclasspath

### Feature requests: what underlying problem are you trying to solve with this feature?
Adding support for AIX operating system

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

bash compile.sh

### What operating system are you running Bazel on?

AIX

### What's the output of `bazel info release`?

NA

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

NA

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

NA using bazel-dist package

###  Have you found anything relevant by searching the web?

Post on couple of forums but no reply
https://groups.google.com/forum/#!topic/bazel-dev/QtgXiy0P_gk
https://groups.google.com/forum/#!topic/bazel-discuss/54o-x7uMbyQ

### Any other information, logs, or outputs that you want to share?

ERROR: /bazel-0.18.0/tools/jdk/BUILD:207:5: Executing genrule //tools/jdk:platformclasspath8 failed (Exit 1): bash failed: error executing command
  (cd /tmp/bazel_zJxNV1dU/out/execroot/io_bazel && \
  exec env - \
    PATH=/opt/freeware/bin:.:/usr/bin:/usr/local/bin:/etc:/usr/sbin:/usr/ucb:/usr/bin/X11:/sbin:/usr/java8_64/jre/bin:/usr/java8_64/bin:/usr/lpp/htx/etc/scripts:/test/tools:/usr/lpp/htx/test/tools:/nim/build_net/tools \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh;
set -eu
TMPDIR=$(mktemp -d -t tmp.XXXXXXXX)
external/embedded_jdk/bin/javac -source 8 -target 8     -Xlint:-options     -cp external/embedded_jdk/lib/tools.jar     -d $TMPDIR tools/jdk/DumpPlatformClassPath.java
external/embedded_jdk/bin/java -XX:+IgnoreUnrecognizedVMOptions     --add-exports=jdk.compiler/com.sun.tools.javac.platform=ALL-UNNAMED     -cp $TMPDIR DumpPlatformClassPath 8 bazel-out/host/genfiles/tools/jdk/platformclasspath8.jar
rm -rf $TMPDIR
')
Exception in thread "main" java.lang.AssertionError:
Could not find java.lang.Object on bootclasspath; something has gone terribly wrong.
Please file a bug: https://github.com/bazelbuild/bazel/issues
        at DumpPlatformClassPath.main(DumpPlatformClassPath.java:197)
Target //src:bazel_nojdk failed to build
INFO: Elapsed time: 23.992s, Critical Path: 5.39s
INFO: 15 processes: 15 local.
FAILED: Build did NOT complete successfully

**Comment by gongsu832** [comment]
I'm trying to build bazel on IBM s390x Linux and getting the same error when using IBM J9. After a bit digging, the problem is that IBM J9 boot classes are scattered in many different pieces so the ./tools/jdk/DumpPlatformClassPath.java isn't picking up all the jars. With the following hack, I was able to build bazel-0.19.0.

```
*** ./tools/jdk/DumpPlatformClassPath.java.orig	2018-10-30 18:16:36.141739161 -0400
--- ./tools/jdk/DumpPlatformClassPath.java	2018-10-30 23:58:14.974736950 -0400
***************
*** 243,250 ****
          jars.add(extJar);
        }
      }
      for (String jar :
!         Arrays.asList("rt.jar", "resources.jar", "jsse.jar", "jce.jar", "charsets.jar")) {
        Path path = javaHome.resolve("jre/lib").resolve(jar);
        if (Files.exists(path)) {
          jars.add(path);
--- 243,256 ----
          jars.add(extJar);
        }
      }
+     Path j9Dir = javaHome.resolve("jre/lib/s390x/compressedrefs/jclSC180");
+     if (Files.exists(j9Dir)) {
+       for (Path j9Jar : Files.newDirectoryStream(j9Dir, "*.jar")) {
+         jars.add(j9Jar);
+       }
+     }
      for (String jar :
!         Arrays.asList("rt.jar", "resources.jar", "jsse.jar", "jce.jar", "charsets.jar", "math.jar", "xml.jar", "ibmjssefw.jar", "ibmjcefw.jar", "ibmcertpathfw.jar")) {
        Path path = javaHome.resolve("jre/lib").resolve(jar);
        if (Files.exists(path)) {
          jars.add(path);
```

Forgot to mention, you also need a symlink src/main/native/jniport.h to your J9's jniport.h, which is /opt/ibm/java-s390x-80/include/jniport.h in my case.

**Comment by clubremy** [comment]
As pointed out above, the reported compilation issue is not directly an issue with AIX. It is actually an issue with use of the IBM JDK. I had the same compilation problem with bazel 0.20.0 on PPC64 with IBM JDK 1.8.0_181. The patch [above ](https://github.com/bazelbuild/bazel/issues/6390#issuecomment-434720443) fixed my issue, but needed to take into account the system architecture (aka System.getProperty("os.arch")) instead of hardcoding s390x.

**Comment by azhar084** [comment]
@meisterT : I am trying to compile latest bazel-0.23.2 on AIX.  I see that you have made changes to download remote jdk. I was looking at the option to bypass fetching remote jdk and use local jdk

ERROR: error loading package '': Unable to load package for '@bazel_tools//tools/build_defs/repo:http.bzl': BUILD file not found on package path

**Comment by trex58** [comment]
Any news about this?

I've started to port version 3.6.0 of Bazel to AIX 7.1, using OpendJDK 1.8 Hotspot.

I've added changes for AIX inside Bazel code, so that the bootstrap starts but fails with:
```
    Fetching @remote_java_tools_linux; fetching
ERROR: /tmp/bazel_wR3kAcOi/out/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'aix'
```
due to still some not-AIX values (piii) appearing in /tmp files, like:
```
/tmp/bazel_wR3kAcOi/out/external/local_config_cc/BUILD :
  +47  cc_toolchain_suite(
  +48      name = "toolchain",
  +49      toolchains = {
  +50          "piii|compiler": ":cc-compiler-piii",
  +51          "piii": ":cc-compiler-piii",
  +52          "armeabi-v7a|compiler": ":cc-compiler-armeabi-v7a",
  +53          "armeabi-v7a": ":cc-compiler-armeabi-v7a",
  +54      },
  +55  )
```

I need to understand how the template file:
   `./tools/cpp/BUILD.tpl`
is used for creating the file:
   `out/external/local_config_cc/BUILD .`
