### ISSUE TITLE
Bazel doesn't sort Platform properties

### ISSUE THREAD

**Issue by ola-rozenfeld** [bazelbuild/bazel#6421]
API spec http://go/gh/bazelbuild/remote-apis/blob/master/build/bazel/remote/execution/v2/remote_execution.proto#L513-L516 says Platform properties should be sorted. Bazel currently doesn't sort them.

We need to consider whether we really want to fix it at this point, and if so, how to do it in a way that doesn't immediately invalidate all existing cache keys. In particular, remote servers need to consider how many keys do their clients currently use in their platform, are they already sorted, etc.

**Comment by katre** [comment]
This would only need to affect the way the remote_execution_properties is parsed into the PlatformProto in RemoteSpawnRunner, correct?

**Comment by ola-rozenfeld** [comment]
Yes, the fix is very easy, but I'm afraid of the consequences. I want to make sure we don't cause a massive cache key recomputation for all RE users. If we do, I suspect it will be better to either leave this unfixed, or do some server-side work to pre-populate the caches with the new keys first.

**Comment by EricBurnett** [comment]
Personally, I'd start by asking the community if anyone values that constraint, and changing the API to drop it if not. The only place it'd matter is if the sort order is not deterministic (which seems unlikely for any reasonably behaved build tool), or if the sort order is the only thing different between two actions that are otherwise identical. Allowing those to not collide seems reasonable - any callers always _could_ sort if they chose to, so the impact of not sorting seems minimal-to-nonexistant. Conversely, https://github.com/bazelbuild/proposals/blob/master/designs/2018-10-09-platform-inheritance.md proposes a reasonable use-case for _not_ having sorted keys and instead recommending a last-wins semantic.

Beyond that, a key recomputation when bazel users switch bazel versions seems fine - it's at a time of their choosing, incremental (as they roll out the new version), and the keys are potentially getting invalidated then anyways (e.g. if the wrapper scripts bazel uses change). My recollection is that it's not uncommon for an active instance to turn over the action cache on average once per day, which means they're silently paying that cost all the time and it's not proving to be a problem. On the flip side, I'd stay far away from server-side work to pre-populate caches if we can...the times we've done so in the past I think we concluded that it wasn't worth the effort in retrospect, and it's tricky to get right.

**Comment by ittaiz** [comment]
One more data point: George Gensure asked @dslomov in BazelCon if the
action key can be part of the bazel API since he does not want to pay the
cache turnover that much (don’t know why).
FYI

**Comment by buchgr** [comment]
I am with @edbaunton on this one. It doesn't hurt anyone to sort things and potentially avoids hard to find bugs.

Furthermore, I don't think in Bazel we should aim at not changing action cache keys between releases and we also haven't done so for local action in the past. I am fine with announcing known changes to the action cache computation in the release notes.

Also, independent of what we decide for how a future version of the API should handle this the current version supported by Bazel states that they need to be sorted and thus we should fix it, sooner than later.
