### ISSUE TITLE
Allow genrule() srcs to exclude .gitignore files in source tree

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#6429]
Often (as when building the Linux kernel) out-of-tree builds are not supported by the native build system.  `genrule()` wrapping of these build systems is thus difficult, but there is usually one saving grace: the files the `genrule()` should ignore in a` genrule() srcs = glob(exclude = [])` are *already* specified in `.gitignore` files littered throughout the file tree.  If a `genrule()` could automatically exclude these from `srcs`, it would make in-tree build wrapping much easier.

**Comment by regisd** [comment]
I'm not in the bazel team, but I'd like to voice against this feature (if I understand it correctly –– maybe you can point at existing BUILD files to show the change you would impact behaviour). I don't think the build system should address this ; it doesn't sound like an expected build-tool behaviour.

1. AFAIK, no existing build tool automatically exclude files that are not specified by their project descriptor 
2. There is no guarantee that the source is actually not using a different VCS (let's say mercurial because I like it better) and that these .gitignore are lying around for a different reason. Excluding their content from genrule would make the build less consistent.
3. There are alredy extensibility mechanisms in Bazel to address this. For instance, by making a macro.

**Comment by jin** [comment]
I agree with @regisd. Bazel should not know anything about your VCS and make decisions based on that, let alone coupling `genrule` to a Git specific file.

**Comment by kayasoze** [comment]
The use case is in-tree builds, where it is impossible to get incremental builds working correctly without duplicating about a thousand lines of .gitignore in the build definition.  This could be a useful option to a filegroup, or to glob, which already supports recursive wildcard expansion.

**Comment by aiuto** [comment]
We are spending our development time trying to make better interfaces to other build systems, so we don't end up with in-tree builds (e.g. rules_cmake).
To you have specific examples of things you are trying to wrap?

**Comment by lberki** [comment]
I agree with @regisd . I'd be reluctant to add knowledge about Git to Bazel because then the floodgates would open for adding knowledge about other source control systems, too.
