### ISSUE TITLE
Release 0.21 - December 2018

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#6493]
Target RC date: December 3rd

**Comment by laurentlb** [comment]
Candidate created with:
`$ scripts/release/release.sh create --force_rc=2 0.21.0 cb9b2afbba3f8d3a1db8bf68e65d06f1b36902f5 `

However some tests are failing: https://github.com/bazelbuild/bazel/issues/6832

**Comment by davido** [comment]
Gerrit Code Review cannot be built with this RC, because of outdated `protobuf` version in `rules_closure`. Is this expected, to flip the default for any option, until some **core** bazel rules still depend on those options?

This is the [issue](https://bugs.chromium.org/p/gerrit/issues/detail?id=10112) in Gerrit issue tracker.
This is the [PR](https://github.com/bazelbuild/rules_closure/pull/313) for the rules_closure.
This is the [fork](https://github.com/davido/rules_closure/releases/tag/0.20) of rules_closure with this PR included.
This is the [CL](https://github.com/davido/rules_closure/releases/tag/0.20), that switched to the forked rules_clsoure for Gerrit project.

**Comment by jin** [comment]
@davido I think everyone's waiting for 3.6.1.2 to be released https://github.com/protocolbuffers/protobuf/pull/4650#issuecomment-443896241

**Comment by davido** [comment]
@jin Thanks for the pointer, but why Bazel is flipping the bit **before** 3.6.1.2 was released, and **before** the update to consume `protobuf` from HEAD is merged?

**Comment by davido** [comment]
> It feels like a really bad user experience to flip a default when upstream dependencies haven’t even remotely caught up yet.

Right, so can we avoid destroying other people work? I reverted 86013a0a23a232d5549bfe1085ebb0fabcd9b23f here: [1]. Can this CL be merged and cherry-picked here?

* [1] https://bazel-review.googlesource.com/c/bazel/+/83630

**Comment by laurentlb** [comment]
Hi,
We test a number of downstream projects on the CI. Protobuf was updated 6 months ago, other rules were updated more recently. The only exception is rules_closure, but there are pending PRs (it's one-click from being fixed). I think Gerrit just need to update its dependencies too.

I agree that the slow releases of Protobuf are annoying, which is why we want to separate the repository (https://github.com/protocolbuffers/protobuf/issues/5402).

What else shall we update?

**Comment by meteorcloudy** [comment]
We now have [a new pipeline](https://buildkite.com/bazel/bazel-at-release-plus-incompatible-flags) for testing `Bazel@Release + incompatible flags + downstream projects@last_green_commit`
See [this document](https://docs.google.com/document/d/19qd-qxizeFHmS7P0M0u3n0xLjix5oB1ioWSTZdY23uo/edit?usp=sharing) for more details

It will catch those failures earlier and help the downstream projects to migrate.

**Comment by jin** [comment]
This pipeline should help us avoid issues like this in the future. Thanks for working on it!

@davido It’ll not be cherrypicked because there’s a workaround by flipping the  incompatible_* flags, which is the mechanism to deal with unintended breaking changes.

**Comment by davido** [comment]
@laurentlb 

> I agree that the slow releases of Protobuf are annoying, which is why we want to separate the repository (protocolbuffers/protobuf#5402).

Protobuf v3.6.1.2 was released today. I've upgraded my [PR](https://github.com/protocolbuffers/protobuf/releases/tag/v3.6.1.2) to bump protobuf to this version in rules_closure. 

> The only exception is rules_closure, but there are pending PRs (it's one-click from being fixed).

Can someone push merge button then, or what we are missing?

> I think Gerrit just need to update its dependencies too.

How can Gerrit update rules_closure, if there is no commit upstream that updated protobuf dependency, and Gerrit maintainers prefer not to fork third party dependencies.

**Comment by davido** [comment]
So, there is a huge complication with upgrade of `protobuf` version in rules_closure, unfortunately. I filed this [issue](https://github.com/bazelbuild/bazel/issues/6852).

As pointed out by @acozzette:

> We don't have a set date for the 3.7 release, but I'm guessing it should be ready in a month or so.
 
Why can't we re-consider to revert 86013a0, just merge this [CL](https://bazel-review.googlesource.com/c/bazel/+/83630), and re-visit this deprecation after `protobuf` 3.7 s released, and Bazel itself, rules_clsoure and Gerrit itself are upgraded to use this full protobuf release?

**Comment by laurentlb** [comment]
@lberki 
> It solves Android Studio performance issues that arose while migrating to 0.18 (!)

If the same issue is in 0.18, 0.19, and 0.20, it shouldn't be considered as critical for 0.21.

**Comment by meteorcloudy** [comment]
> If the same issue is in 0.18, 0.19, and 0.20, it shouldn't be considered as critical for 0.21.

I don't think I can fully agree. Sounds like as long as a regression exists for a time long enough, it's no longer critical. But there are different reasons for a regression to exist so long:

- There is an easy workaround for the regression so that people can endure it.
- The project that will hit the regression isn't upgrading Bazel frequently (maybe due to incompatible changes).
- The regression is very hard to debug (eg. Android Studio mac performance issues https://github.com/bazelbuild/bazel/issues/6806; TensorFlow malformed output log issue https://github.com/bazelbuild/bazel/issues/6731)

#6806 and #6731 have respectively caused Android Studio and TensorFlow not being able to upgrade Bazel to any version later than 0.18.0. So, I believe they are indeed critical. 

Until we can make sure people are actively testing Bazel release candidate (obviously they don't), we should distinguish such regressions.

**Comment by jin** [comment]
@davido I have written a [postmortem](https://docs.google.com/document/d/1yEvVro14iRshpum-1lnu_ZqoXcL8l7EYbmjdFTsl48Y/edit#heading=h.t36ajsmfpi40) on how we can prevent this from happening again, with a focus on the Android projects that I'm maintaining. I also mentioned the issues surrounding Gerrit and rules_closure, as we both faced similar breakages.

**Comment by davido** [comment]
@Jin Thanks, looks god! I commented on this document.

**Comment by laszlocsomor** [comment]
Potential release-blocker: https://github.com/bazelbuild/bazel/issues/6859

**Comment by dslomov** [comment]
Sorry for not replying earlier, I was on sick leave.

Re protobuf issue: looks like the world (including Bazel itself, rules_closure and other things) need to move to protobuf 3.6.1.2, and that is an acceptable solution to everyone, is that correct?

Re #6806: this fix should be cherry-picked under a provision for critical, high impact issues. What happened there is that it took as a while to reproduce and investigate this issue, that is why we only got the fix at the date we got it - the issue was reported quite a while ago.

**Comment by davido** [comment]
> Re protobuf issue: looks like the world (including Bazel itself, rules_closure and other things) need to move to protobuf 3.6.1.2, and that is an acceptable solution to everyone, is that correct?

Unfortunately, no. Can you see my comments on @jin's postmortem document linked in his previous comment?

1. 3.6.1.2 is broken, as it missed at least one commit compared to 3.5.1 protobuf release. That broke rules_closure integrations tests for protobuf_js. I uploaded a PR to fix that. After the fact, new tag 3.6.1.3 must be created. ETA is unknown.
2. 3.6.1.2 is not a complete protobuf release, but just a tag. Particularly protobuf-java wasn't published on Maven Central
3. Bazel itself still depends on Protobuf 3.6.1
4. Gerrit Code Review depends on both: Rules_closure and on protobuf-java. That why `protoc` and protobuf-java versions must match, otherwise we are hitting this porblem: [1].
5. Can someone please explain my, why all that mess? Why it is that important to flip the bit: `--incompatible_package_name_is_a_function` before all that happened:

a) Protobuf 3.7 official released and all artifacts are published on Maven Central
b) Bazel itself switched to using Protobuf 3.7
c) rules_closure and all other core Bazel rules_xxx projects are adapted and released

**Comment by laurentlb** [comment]
Cherrypicking 12b96466ee0d6ab83f7d4cd24be110bb5021281d, 7fc967c4d6435de2bb4e34aac00ca2e499f55fca, and 798b9a989aa793655d29504edb5fb85f3143db84

**Comment by aehlig** [comment]
rc3 still fails to build offline; can we please cherry-pick dbe05df23ccf4c919379e0294e0701fd3f66739c as requested?

Thanks.

**Comment by laurentlb** [comment]
Done.

`scripts/release/release.sh create --force_rc=4 0.21.0` cb9b2afbba3f8d3a1db8bf68e65d06f1b36902f5 12b96466ee0d6ab83f7d4cd24be110bb5021281d 7fc967c4d6435de2bb4e34aac00ca2e499f55fca 798b9a989aa793655d29504edb5fb85f3143db84 dbe05df23ccf4c919379e0294e0701fd3f66739c

https://releases.bazel.build/0.21.0/rc4/index.html

**Comment by laurentlb** [comment]
@dslomov When can we release it?
I believe it can be released tomorrow, is it okay? (or shall I wait after new year?)

**Comment by dslomov** [comment]
I think tomorrow is fine. Could you include links to [migration-0.21](https://github.com/bazelbuild/bazel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Amigration-0.21) and [breaking-change-0.21](https://github.com/bazelbuild/bazel/issues?q=is%3Aissue+label%3Abreaking-change-0.22) in release announcement?

**Comment by laurentlb** [comment]
Released: https://github.com/bazelbuild/bazel/releases/tag/0.21.0

**Comment by laurentlb** [comment]
cc @vbatts @petemounce

Blog post: https://blog.bazel.build/2018/12/19/bazel-0.21.html

**Comment by vbatts** [comment]
On 19/12/18 11:22 -0500, Laurent Le Brun wrote:
>   cc [1]@vbatts [2]@petemounce
>
>   Blog post: [3]https://blog.bazel.build/2018/12/19/bazel-0.21.html

https://github.com/bazelbuild/bazel/issues/6965

**Comment by jin** [comment]
0.21.0 documentation is up: https://docs.bazel.build/versions/0.21.0/bazel-overview.html

**Comment by vbatts** [comment]
fedora/centos build: https://copr.fedorainfracloud.org/coprs/vbatts/bazel/build/838751/

**Comment by sergiocampama** [comment]
when will this hit homebrew?

**Comment by laurentlb** [comment]
It should be updated (https://github.com/bazelbuild/homebrew-tap/pull/35)

**Comment by petemounce** [comment]
Published to chocolatey.

**Comment by ittaiz** [comment]
Thanks for the correction! Where was this released? If I look on their
github project releases tab I don't see it.

**Comment by davido** [comment]
> Where was this released?

Check this PR that updated rules_closure to protobuf 3.6.1.3: [1]:

```python
http_archive(
        name = "com_google_protobuf",
        strip_prefix = "protobuf-3.6.1.3",
        sha256 = "73fdad358857e120fd0fa19e071a96e15c0f23bb25f85d3f7009abfd4f264a2a",
        urls = [
            "https://mirror.bazel.build/github.com/google/protobuf/archive/v3.6.1.3.tar.gz",
            "https://github.com/protocolbuffers/protobuf/archive/v3.6.1.3.tar.gz",
        ],
    )
```

* [1] https://github.com/bazelbuild/rules_closure/pull/320

**Comment by davido** [comment]
Bazel 0.21 package for Alpine Linux is here: https://github.com/davido/bazel-alpine-package/releases/tag/0.21.0.

**Comment by petemounce** [comment]
Belatedly, pushed to chocolatey.
