### ISSUE TITLE
Potential performance issue in com.google.devtools.build.lib.actions.cache.DigestUtils.getDigestOrFail

### ISSUE THREAD

**Issue by kohlerm** [bazelbuild/bazel#65]
I tried to compile a Java project with about 20000 java source code files. When I ran it for the first time it would take quite some time without using much cpu time, I would also get "slow read" messages. 
I did a thread dump (see at the end) and apparently there is a global lock in com.google.devtools.build.lib.actions.cache.DigestUtils.getDigestOrFail and 199 threads are waiting on that lock/
 do a 
grep 0x00000000c02f6570 /tmp/bazel.log  

I think the number of threads is a bit high, I don't think it would go any faster especially since the lock is really global. 

the thread dump is here:
https://github.com/kohlerm/bazel/blob/issues/global_lock.log

**Comment by lberki** [comment]
We put that exclusive lock in place so that Bazel doesn't start checksumming 200 files in parallel, since that would be a lot of I/O load. This was introduced at the beginning of 2009, so the state of affairs could have changed a lot since then.

At the very least we could raise the file size limit for concurrent threads or run things on more than one (but not --jobs) threads. 

Could you try removing the sychronization from getDigestInExclusiveMode and see how much (if at all) it improves performance?

**Comment by damienmg** [comment]
Closing as obsolete.
