### ISSUE TITLE
Platform/toolchain support for C++ rules

### ISSUE THREAD

**Issue by gregestren** [bazelbuild/bazel#6516]
Tracking issue  on [Bazel Configurability Roadmap](https://bazel.build/roadmaps/configuration.html)

Goal:
* C++ toolchains can be defined with Bazel's generic [toolchain machinery](https://docs.bazel.build/versions/master/toolchains.html)
* C++ rules read these toolchains
* C++ rules resolve properly against [platforms](https://docs.bazel.build/versions/master/platforms.html)

**Comment by mhlopko** [comment]
Before I leave for 3 weeks of vacation, let me say I'm not aware of any work needed now that https://github.com/bazelbuild/bazel/commit/683c302129b66a8999f986be5ae7e642707e978c is submitted. John, do you know about anything?

**Comment by katre** [comment]
Testing, that's all. Enjoy your vacation!

**Comment by mhlopko** [comment]
I'm back! :)

Could you give me a list of behaviors/features that I should test? I don't know where to start :)

**Comment by nlopezgi** [comment]
I'd like to see tests that run with custom values for some of the ENV variables that cc_config uses. Most of the times we have seen issues is because we set custom values for some of these ENV variables in our rules (https://github.com/bazelbuild/bazel-toolchains/blob/master/rules/environments.bzl#L30).

**Comment by nlopezgi** [comment]
This is a bigger ask: I would like to see changes that impact crosstool/c_toolchain compatibility to be guarded behind --incompatible flags. Let me expand that: Currently, when there are changes to the CROSSTOOL / c_toolchain, there is no guarding them behind an --incopatible flag (afaik). For users that have hand built or checked in versions of a CROSSTOOL / c_toolchain, they have no way of preventing Bazel changes in release X+1 from breaking them. 
For example, a recent change to how toolchains are selected using as key only e.g., "k8" instead of e.g., "k8|clang" could have been guarded behind an --incompatible flag for ~1 bazel release. That way, I could have tested that with version X my c_toolchain that did not have the  "k8|clang"  would work, but if I use --incompatible_someting_something it would break.

**Comment by nlopezgi** [comment]
The other problem I had in the past is that adding the 
enabled_toolchain_types=@bazel_tools//tools/cpp:toolchain_type
made it so that the OPT toolchain was always selected and linkopt files were not passed (https://github.com/bazelbuild/bazel/issues/5291) 
(not sure if this is relevant to this thread or if it has been fixed already)

**Comment by mhlopko** [comment]
Hi Nick!

1) tests for cc_configure, absolutely, but since we plan a big rewrite of cc_configure because https://github.com/bazelbuild/bazel/issues/5380, we will only add tests during the rewrite. I think it's independent from this issue.
2) we (C++ rules) already do that, and we did that before it was cool. This is the flag for the change that broke you: https://github.com/bazelbuild/bazel/issues/6382. The problem was that it took us too long to polish the policy, so the upcoming incompatible changes announcement didn't receive due attention.
3) I pinged https://github.com/bazelbuild/bazel/issues/5291, let's see what are the next steps.

Thanks for chiming in!

**Comment by katre** [comment]
Also, this issue is specifically for "cc rules work when --enabled_toolchain_types=@bazel_tools//tools/cpp:toolchain_type is passed". Other cc rules issues should be filed separately.

**Comment by nlopezgi** [comment]
Thanks for the clarifications @mhlopko , sorry for tagging along other stuff here @katre

**Comment by jin** [comment]
@gregestren could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by gregestren** [comment]
See https://github.com/bazelbuild/bazel/issues/7260

**Comment by dslomov** [comment]
Please do not assign issues to more than one team

**Comment by gregestren** [comment]
**April '19 update:**

This is imminently ready with `--incompatible_enable_cc_toolchain_resolution`. @hlopko mentioned some small ongoing cleanup work but the core support is pretty much there, I believe.

Is this still the right issue for ongoing work or are things ready for more fine-grained issues? I guess the ultimate user-facing result is being able to have an instance of `$ bazel build //my:cc_rule --platforms=//some_platform` and see a working result that can be generalized for other projects.

**Comment by hlopko** [comment]
The small cleanup work is https://github.com/bazelbuild/bazel/issues/7793, which I plan to flip as soon as we have 0.25 released. Second prerequisite is having the common platforms repository. Once those 2 bits are done, I can make C++ autoconfiguration (cc_configure) use the common platforms repository and we can try to flip https://github.com/bazelbuild/bazel/issues/7260.

**Comment by gregestren** [comment]
Update: a major reason this hasn't been toggled on yet is it'll break Android or iOS projects with C++ native deps. Configurability devs are doing a concerted focus now on adding platform/toolchain support for Android builds to unblock. We *may* be getting support for doing the same for iOS builds too, although I'm unclear on how much yet.

**Comment by c-mita** [comment]
Changing team to reflect who's been doing the work.

**Comment by katre** [comment]
Downgrading priority to reflect the current level of activity.
