### ISSUE TITLE
Have BEP reflect what was cached remotely

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#6567]
### Description of the problem / feature request:

Given a build which does `bazel test //...` and uses RemoteExecution then following UIs which are based on top of the BEP (and so are target driven) are very confusing since they have no indication whether a target was cached remotely or not. Even the test indication is about local caching.
I'd like for the BEP to return true/false about whether or not the target was cached remotely or not. Given a target that has several actions it should return true iff all actions were remotely cached.

### Feature requests: what underlying problem are you trying to solve with this feature?

The underlying problem is to give users visibility on the impact of their change as well as being able to easily see only the targets relevant to their change (for example see durations).

cc @aehlig @ulfjack @dslomov @helenalt @willsc79

**Comment by benjaminp** [comment]
Since 1bbeadc2e3b9dd09909c0a47f86cd878aede1392, both the UI and BEP should be telling you when a test is remotely cached.

**Comment by ittaiz** [comment]
Thanks!
Why does the commit talk about “standalone”? Is this a different standalone
than the strategy? Will this apply to builds with remote execution (as
opposed to only remote caching)?

Btw,
What do you think in general about this request? Do you have a target based
UI or just console output?

**Comment by benjaminp** [comment]
> Thanks! Why does the commit talk about “standalone”? Is this a different standalone than the strategy? Will this apply to builds with remote execution (as opposed to only remote caching)?

There's a distinction between test strategy and spawn strategy. The only extant Bazel test strategy is called "standalone", which is used regardless of the ultimate spawn strategy used to execute the test-running spawns.

> Btw, What do you think in general about this request? Do you have a target based UI or just console output?

I'm not sure what exactly you're requesting that isn't already present. The builtin Bazel UI shows remotely cached tests as cached. That information is also exposed in BEP as `TestResult.ExecutionInfo.cached_remotely`.

**Comment by ittaiz** [comment]
I'm talking about non test artifacts such as java_library and others. This
is so that if you have a target based UI on top of the BEP you can filter
out all cached targets so the user can see the targets that this run
impacted. This is important when running with "bazel test //..."

**Comment by ulfjack** [comment]
I don't think Bazel can do that. The problem is that such an indicator is inherently unreliable, i.e., you'd be getting false positives and false negatives. If you're making workflow decisions based on whether something was a remote cache hit, e.g., whether to push updated files to production, that's dangerous, and I definitely do not recommend doing that.

In particular, the outputs of a target can include source files, which are usually not uploaded to a remote cache (there's no 'cache hit' in that sense), and it also heavily depends on the state of the remote cache. Maybe a coworker who's using the same cache has tried out a change on his machine, and now it looks like a cache hit on your run.

It also breaks down when you grow larger - in our experience, you'll need to split up runs of //... when the repository has grown to a certain size, and then it's possible for targets to be built in multiple runs, and whether it's a cache hit or not depends on whether you got there first or second.

That said, it is - in principle - possible for Bazel to tell all affected targets from a list of modified (deleted / added) files. In a CI system, this could be done based on the current commit before running bazel test //... so unaffected targets wouldn't even show up in the results.

**Comment by ittaiz** [comment]
Thanks for the detailed reply.
We’re not looking to make decisions based on this info (we use checksums
for deciding on deployment for example) but we are trying to give the user
more/better information.

In your suggestion do you mean to use bazel query? Can you say how reliable
that is? Additionally can you say how performant that is?

**Comment by ulfjack** [comment]
We've internally been using query for this for many years. There are some corner cases where it's not completely reliable, e.g., if you're selecting a different toolchain at runtime such as --crosstool_top=//custom_compiler, then this can't predict that changes to //custom_compiler will affect C++ code. It also has to be conservative if you have a lot of select() in your codebase, so changes to things that are only reachable through select() still show up as affecting the top-level targets.

Performance depends heavily on how large / complex your source tree is. In our case, the time needed to figure out which tests to run is lower than the time needed to get cache hits for those tests so it's a significant net win; I'm assuming CI does clean builds and most changes only affect a small number of tests.

**Comment by ittaiz** [comment]
Thanks.
Don’t you have a full blown service which has the build graph in memory?

Also, I think you can close it as “should not be implemented” as it sounds
like you feel strongly against.
TBH I’m not convinced but:
1. I might not fully understand
2. It’s natural some people won’t agree to design decisions :)
