### ISSUE TITLE
Please add the script that installs only what is required to run bazel

### ISSUE THREAD

**Issue by yurivict** [bazelbuild/bazel#658]
This is a followup of https://github.com/bazelbuild/bazel/issues/613

It currently installs files like these:
```
third_party/java/buck-ios-support/java/com/facebook/buck/apple/xcode/xcodeproj/PBXBuildFile.java
third_party/py/gflags/tests/flags_modules_for_testing/module_baz.py
third_party/py/gflags/NEWS
```
Obviously build tool doesn't need to have Java sources in it, and we don't want to install tests or news either.

I am making the FreeBSD port, and am very reluctant to just copy the whole directory over.

**Comment by ulfjack** [comment]
I think this is obsolete now. You should only need the bazel binary and neither third_party nor tools. We've made it so that there's a bazel_tools workspace which contains all the tools and they're all in the binary.

I'll close this as obsolete, feel free to reopen if I'm wrong. However, if you do, please provide more concrete steps for what you're doing - I'm having a hard time following the description above.
