### ISSUE TITLE
Cross-repository build violation with third_party/googleapis

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazel#6601]
Bazel has a feature to attempt to detect and prevent referring to a package by two different labels.

Currently, from the Bazel source, it is possible to build both `//third_party/googleapis:all` and `@googleapis//:all`.

The repository form is the preferred form (since it is defined in Bazel's WORKSPACE). The third_party form does not build, because several source paths are wrong, but this should be flagged as an error.

**Comment by katre** [comment]
Discovered while testing #6595.

**Comment by katre** [comment]
Issue is that "googleapis" is a new_local_repository, not a local_repository (with an associate WORKSPACE file).

Time to try and figure out if there's a reason why.

**Comment by katre** [comment]
It looks like `@googleapis` was added by @buchgr in https://github.com/bazelbuild/bazel/commit/166f28cd620f9fc9c4694242916a7fe1a9a998da.

@buchgr, why is this a new_local_repository instead of a local_repository?

**Comment by buchgr** [comment]
@katre I don't recall. I believe the most likely explanation is that at this point (May 2017) I wasn't knowledgeable enough to understand the difference between `local_repository` and `new_local_repository`. Do you want me to fix it?

**Comment by katre** [comment]
I have changes in progress (it requires a test fix first). Just wanted to be sure there wasn't a deeper reason I'd missed.

**Comment by Ubehebe** [comment]
I ran into a closely related issue: is it possible to consume the googleapi targets from a downstream repo? As @katre notes above, `bazel build //third_party/googleapis:...` is broken due to incompatible source paths in the .proto files. This means a downstream repo can't consume `@io_bazel//third_party/googleapis:...`. But as far as I know, there is no way for downstream repos to see the local repository `@googleapis` form either.

(Context: I'm trying to consume the Build Event Service protos. Although their canonical home seems to be in the googleapis repo, that repo [doesn't have any build targets at all](https://github.com/googleapis/googleapis/tree/master/google/devtools/build/v1) for those protos. The forked versions in the Bazel repo have exactly the targets I want...I just don't know how to consume them.)

**Comment by katre** [comment]
Unfortunately, there's no good way for Bazel to make this available directly from our source tree. The ideal solution would be for googleapis to provide their own BUILD files.

You should be able to import a Bazel release as an http_archive, and then give a strip_prefix that, basically, takes out everything except "third_party/googleapis". (Or possibly handle that with a patch on top of the Bazel repository). I haven't tested that, but it might work. It's pretty wasteful on downloads, however.
