### ISSUE TITLE
Multiple toolchain rules unable to use same implementation

### ISSUE THREAD

**Issue by smukherj1** [bazelbuild/bazel#6613]
### Description of the problem / feature request:

Look at the toolchain rules added by https://github.com/bazelbuild/rules_docker/pull/559 in //toolchains/docker/BUILD. There are three toolchains of //toolchains/docker:toolchain_type using the same implementation function. Bazel appears to arbitrarily pick one of these toolchains during toolchain resolution

### Feature requests: what underlying problem are you trying to solve with this feature?
Reuse the toolchain implementation with multiple toolchain rules

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
Not entirely sure. I reproduced the issue with blaze. @katre has more context

### What operating system are you running Bazel on?
Linux

**Comment by katre** [comment]
After some debugging, the problem is much simpler: the `--extra_toolchains` flag was not allowing multiple uses, so the last value passed was replacing the previous ones.

I'll send a patch to fix that, until that is released you can use the multiple value format:
```
bazel build --extra_toolchains=//toolchains/docker:default_linux_toolchain,//toolchains/docker:default_windows_toolchain,//toolchains/docker:default_osx_toolchain
```
Or, even use the target pattern version:
```
bazel build --extra_toolchains=//toolchains/docker:all
```
