### ISSUE TITLE
Feature: java_library.resource_add_prefix

### ISSUE THREAD

**Issue by BlackIsTheNewBlack** [bazelbuild/bazel#6683]
### Description of the feature request:

java_library has a resource_strip_prefix property which removes a path prefix. Please add the complementary property "resource_add_prefix" which would place files in a different folder.

### Feature requests: what underlying problem are you trying to solve with this feature?

Many times resources need to be placed in specially named folders in order to work. For example, Java ServiceLoader resources have to be placed under META-INF/services. Ideally, in the source folders the resource file would be placed right near the {Service}.java it describes. Currently that is not possible, it has to be either placed in a META-INF/services subfolder (which increases the complexity of the directory structure) or in a dedicated resources/META-INF/services folder which aggreggates all service resource, which breaks modularity.

Without resource_add_prefix:
Service.java
META-INF/
    services/
        com.test.Service

With proposed resource_add_prefix='META-INF/services':
Service.java
com.test.Service

### What operating system are you running Bazel on?
Windows 10

### What's the output of `bazel info release`?
release 19.1

###  Have you found anything relevant by searching the web?
Nothing

**Comment by cushon** [comment]
> ServiceLoader resources have to be placed under `META-INF/services`

Consider using [AutoService](https://github.com/google/auto/tree/master/service#autoservice) for this. It's an annotation processor that generates the `META-INF/services` files for you.

> Currently that is not possible

It's not possible using attributes on `java_library`, but if it's necessary to have full control over the resource layout you can generate a separate `.jar`, add it to the build using `java_import`, and then add the `java_import` to the `deps` or `runtime_deps` of the original `java_library`.

**Comment by ittaiz** [comment]
Also another option is to use a genrule with the zipper from bazel_tools

**Comment by RaresI** [comment]
@ittaiz 
Thank you for the tip. Please notice that the zipper is not documented and requires two extra rules to manage. The same argument could be made for strip_resource_prefix, why have it when you can just merge an external archive?

@cushon 
Actually I did not need it for ServiceLoader, it was just an example, I need it for a Vaadin web app, which actually requires 3 extra directory levels (META-INF/resources/frontend) and webjars (META-INF/resources/webjars/iron-...) . IMHO the java_library rule should be self contained if possible, strip_resource_prefix is half usable without its complementary resource_add_prefix.

Thank you for your time.

**Comment by cushon** [comment]
> The same argument could be made for strip_resource_prefix, why have it when you can just merge an external archive?

I think it's worth considering deprecating [`resource_strip_prefix`](https://docs.bazel.build/versions/master/be/java.html#java_binary.resource_strip_prefix). @lberki do you remember the motivation for beccb9bfee87fb4869b5c00abd9400ebaf647bf0? I wonder if it was to work around issues like #6353?

> IMHO the java_library rule should be self contained if possible

I don't see this is a goal. I'd rather have slightly more rules that solve specific problems than having `java_library` try to do everything.

**Comment by ittaiz** [comment]
@rarsel,
Did not mean to say your request isn’t valid just to offer a workaround.

@cushon,
Aren’t you concerned about the additional IO? One needs to unzip and zip.
Maybe I’m zooming in too much.

**Comment by RaresI** [comment]
Hello,

> I think it's worth considering deprecating [`resource_strip_prefix`](https://docs.bazel.build/versions/master/be/java.html#java_binary.resource_strip_prefix). 

Please do not deprecate resource_strip_prefix unless you provide a mechanism for controlling the paths layouts in the resulting jar, which should at least be able to... strip the prefix. The layout of resources in the JARs has to be separated from the logical layout of source files and resource file, because they are guided by different requirements.

> > IMHO the java_library rule should be self contained if possible
> I don't see this is a goal. I'd rather have slightly more rules that solve specific problems than having `java_library` try to do everything.

How about this:
Explicitely map the layout of resources with a map of labels and some regex magic using capturing groups:
`$STRIP='//some/embedding/root'
META_ROOT = 'META-INF/resources/frontend'
resources = glob( 
{
        "$STRIP/(**)/(*).properties.in": i18n("$META_ROOT/$1/$LANG/$2.properties"),
} )`

In this example, the resource prefix is stripped, the destination root is changed, same for file extension, and it is also using custom logic for the localization language.

This approach can replace java_library.resources, resource_strip_prefix and classpath_resources properties, which would become obsolete, along with their limitations such as "This heuristic cannot be overridden.". #6353 can also be closed because the system wide configuration can be replaced with a specific map and some function calls.

In order to address the IO concern raised by @ittaiz, please consider adding a rule equivalent with rsync which would operate directly on such a map of source files to destination files, based in a dedicated directory instead of a zip.

**Comment by cushon** [comment]
> Aren’t you concerned about the additional IO? One needs to unzip and zip.

The implementation of `java_library.resources` creates a separate action to add the resources to the output jar, to avoid re-running the compilation action if only the resources change. Creating a completely separate jar for the resources should be marginally less expensive than merging the resources into the library's output jar. And either way, creating the zip is almost free compared to the cost of compilation.

> a mechanism for controlling the paths layouts in the resulting jar

I think the approach described earlier in the bug provides full control over the resource layout? https://github.com/bazelbuild/bazel/issues/6683#issuecomment-439244436
