### ISSUE TITLE
rules_webtesting has started needing `--no-sandbox` to avoid crashing

### ISSUE THREAD

**Issue by jmhodges** [bazelbuild/bazel#6710]
Since upgrading from bazel 0.13 to 0.18 and from macOS High Sierra to Mojave, my tests using Chrome (well, Chromium) in headless mode through rules_webtesting have started to crash.

It appears to be related to sandboxing. Adding `--no-sandbox` to the flags you run Chromium with fixes the problem. (The `--no-sandbox` flag is mentioned in Chrome's [original blog post about headless mode](https://developers.google.com/web/updates/2017/04/headless-chrome) as a hack for missing certain environment variables)

I have a repro at this branch: https://github.com/jmhodges/bazel_bugs/tree/rules_webtesting_no_sandbox

It includes a discussion on how to run the repro in https://github.com/jmhodges/bazel_bugs/blob/rules_webtesting_no_sandbox/README.md

In response to a rules_webtesting bug, I was asked to talk to whoever was handling sandboxing on macOS in bazel proper, and this seemed like the best way to do that.

**Comment by jmhodges** [comment]
Ping! (And for the record, the rules_webtesting ticket was https://github.com/bazelbuild/rules_webtesting/issues/315)

**Comment by jmhodges** [comment]
Oh, and this has continued with bazel 0.20.0.

**Comment by jmhodges** [comment]
The rules_webtesting ticket got closed without any feedback, but I’ll link it here in case it helps https://github.com/bazelbuild/rules_webtesting/issues/315#event-2089489370

**Comment by jmmv** [comment]
FTR, the referenced bug hints at a possible problem here: lack of nested sandboxing. Bazel is sandboxing the action and the action itself runs Chromium with its own sandboxing. Don't know if that's the issue, but if it is... then it's likely a change in Mojave, not Bazel, because I don't recall any recent changes to the darwin sandbox in Bazel that would explain this.

What happens if you run this with `--spawn_strategy=standalone` and `--test_strategy=standalone` with Chromium's sandbox enabled?

**Comment by jmhodges** [comment]
Ugh, I can't repro now. I'm now on macos mojave 10.4.2 and rules_webtesting updated some of its deps, too.

**Comment by jmmv** [comment]
Closing as stale given that this doesn't seem reproducible any longer per the last update.
