### ISSUE TITLE
Remove --genrule_strategy

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/bazel#6760]
I'm planning to deprecate and remove the --genrule_strategy flag in early 2019.

As of e6263c3b0b9a467d315b91eac14162cf7915dcfd, it is no longer necessary to set --genrule_strategy in addition to --spawn_strategy if both are set to the same value. If --genrule_strategy is not set, it now defaults to --spawn_strategy. This makes --genrule_strategy superfluous - it can already be replaced with --strategy=Genrule=&lt;value&gt;, and now the existence of the flag no longer implies a default strategy setting for genrules.

**Comment by ulfjack** [comment]
Note that the first step is to make --genrule_strategy a noop, which will land in January. This only requires action for users who set --spawn_strategy to a different value than --genrule_strategy.

**Comment by perfinion** [comment]
I just spent a fair while on remote exec not working for genrules, turns out the culprit was that the .bazelrc had `--strategy=Genrule=standalone` and I was setting `--genrule_strategy=remote`. It seems genrule_strategy is irrelevant if strategy=Genrule is set and there is no warning to the console that its being ignored. Can bazel print a warning if those two don't match?
