### ISSUE TITLE
Changing --max_idle_secs on a running server doesn't have any effect.

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#6773]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Changing --max_idle_secs on a running server doesn't have any effect.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ cd src/bazel
$ bazel info

# This doesn't restart the server, but probably should:
$ bazel --max_idle_secs=1 info

$ sleep 3
$ ps axu | grep -v grep | grep bazel
# Bazel server is still running, even though max_idle_secs=1 should
# have caused it to shutdown by now.
```

### What operating system are you running Bazel on?

Linux, macOS.

### What's the output of `bazel info release`?

release 0.19.2

**Comment by philwo** [comment]
@lberki @meisterT I'm not sure which team this belongs to - performance maybe? Could you assign it to someone who can have a look? :)

**Comment by meisterT** [comment]
I don't think we currently have a way to communicate new values for volatile startup options. Lukacs introduced the code in 2009, so he's a good person to look at it :-)

**Comment by jmmv** [comment]
The `max_idle_secs` feature is implemented by setting a property of the gRPC server at construction time. As far as I can tell, there is no way to change this value once the server has started. This is implemented via a separate `ServerWatcherRunnable` thread, so it'd be plausible to extend the gRPC API to support this kind of change.

An alternative would be to _not_ use that feature of the gRPC server and instead start our own `ServerWatcherRunnable` instance on the side -- but that's a private class, so we'd need to duplicate the logic or ask for it to become public. Or... recreate the gRPC server instance once we know that the value has changed, but that seems pretty complex as well (because by the time we know, we are serving a client request, which means the request would die; or we'd have to postpone the server restart until we finish that request).

So... I doubt recognizing `--max_idle_secs` updates are worth it. Too much complexity for no(?) gain.

What's surprising is that a change in this startup flag doesn't cause the server to restart, like all other startup flags do. Having things silently "work" when they don't is incorrect, so I'd say we need to fix that problem by making the server restart. At least this would match current expectations.

**Comment by meisterT** [comment]
>What's surprising is that a change in this startup flag doesn't cause the server to restart, like all other startup flags do. Having things silently "work" when they don't is incorrect, so I'd say we need to fix that problem by making the server restart. At least this would match current expectations.

https://cs.opensource.google/bazel/bazel/+/master:src/main/cpp/blaze.cc;l=1051;drc=cffd417a4c4ec4d082f815f57a771ad1010972dd
