### ISSUE TITLE
BEP should contain workspace name

### ISSUE THREAD

**Issue by ittaiz** [bazelbuild/bazel#6797]
### Description of the problem / feature request:

BEP should contain the workspace name of the current workspace

### Feature requests: what underlying problem are you trying to solve with this feature?

I'm trying to use information from the BEP file in a many-repo setting. In such a setting knowing information about a label is worthless if you don't know the workspace name it belongs to. For example building an index of FQCN-> label.
One can always use a different storage system to keep a mapping of invocationId->bazel_workspace_name and correlate that but IMHO this sounds redundant and adding it to the BEP is more coherent.

### What's the output of `bazel info release`?

0.19.2

**Comment by ittaiz** [comment]
@lfpino wdyt?

**Comment by lfpino** [comment]
Hi Ittai, I actually had a look at this last week and forgot to update the bug. Sorry about that.

In principle I'm not opposed to the idea; however, we should be very conservative with what we add to the BEP so the larger question is how much information do we need in the BEP (if any) to support external repos in general which is a question I think worth spending time instead of adding a few fields here and there given that this won't happen right away.

I'm not an expert on external repos so I briefly discussed this with @aehlig and he had some ideas that maybe he can share here.

A question for you is regarding priorities since it seems you have a workaround already for this?

**Comment by ittaiz** [comment]
+1 for taking time to think it through.
I would really like this to move along (even in a slow pace) and not get
stuck.
For now we’re not blocked though it’s a heuristic based so I hope we won’t
encounter a blocker.
In general I agree this might be a broader issue of representing external
repositories (and fully qualifying targets):

**Comment by aehlig** [comment]
@ittaiz argued correctly, that the workspace name is a bazel concept and therefore could have a more prominent position that other status information. For the latter, my idea for a generic interface is to add the output of the workspace-status-command to the BEP, preferably as an uploaded artifact. For external repositories in general, my idea would be to make the resolved file somehow part of the BEP; but that obviously is blocked on the resolved file getting out of experimental status.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by ittaiz** [comment]
We (Wix) are hoping to move to a mono repo so this will effect us much less but when you have problems with external repositories inside the org which broke the story is not great :(
