### ISSUE TITLE
C++ SingleJar on Windows can't deal with empty files

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#6820]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

It seems like C++ SingleJar on Windows crashes when it encounters an empty file as an input:

```
WARNING: C:\users\philwo\_bazel_philwo\i3dsexk6\execroot\io_bazel\src/tools/singlejar/mapped_file_windows.inc:66: Windows MappedFile cannot handle empty file (bazel-out/x64_windows-fastbuild/genfiles/src/main/java/com/google/devtools/build/lib/runtime/commands/LICENSE)
ERROR: src/tools/singlejar/output_jar.cc:922: bazel-out/x64_windows-fastbuild/genfiles/src/main/java/com/google/devtools/build/lib/runtime/commands/LICENSE
Target //src:bazel.exe failed to build
```

You can easily repro this by changing this line:
https://source.bazel.build/bazel/+/cb9b2afbba3f8d3a1db8bf68e65d06f1b36902f5:src/main/java/com/google/devtools/build/lib/BUILD;l=1273

to just

```
cmd = "touch \"$@\"",
```

and then build Bazel as usual:

```
bazel build //src:bazel.exe
```

### What operating system are you running Bazel on?

Windows 10

### What's the output of `bazel info release`?

I can repro this at Bazel HEAD

**Comment by laszlocsomor** [comment]
Thanks for the report!

The error comes from here:
https://github.com/bazelbuild/bazel/blob/7fc967c4d6435de2bb4e34aac00ca2e499f55fca/src/tools/singlejar/mapped_file_windows.inc#L66

The caller is here:
https://github.com/bazelbuild/bazel/blob/7fc967c4d6435de2bb4e34aac00ca2e499f55fca/src/tools/singlejar/output_jar.cc#L909

The comment above the failing line in `mapped_file_windows.inc` explains that empty files are not supported. I think the caller should handle empty files instead of attempting to map them.

I'll try to fix this.
