### ISSUE TITLE
Skylark macros should have access to results of evaluated `config_setting`.

### ISSUE THREAD

**Issue by PiotrSikora** [bazelbuild/bazel#6883]
### Description of the problem / feature request:

Skylark macros should have access to results of evaluated `config_setting` in order to take different actions based on the selected build-time options.

### Feature requests: what underlying problem are you trying to solve with this feature?

(same as #6882)

I'm trying to add an alternative SSL library (different build of BoringSSL, really) to Envoy, which could be selected at the build-time using `--define ssl_library=alternative`. Both: `config_setting()` and `select()` work fine for local rules, but it seems that there is no way to pass those selections to the dependencies.

Most Bazel projects that link against SSL libraries use `//external:ssl`, which works great for linking against the same SSL library in projects with a lot of dependencies,  but because there is no way to programmatically set the target of the `//external:ssl` binding nor take a different action in Skylark based on the `config_setting()`, there is no way to switch between the SSL libraries.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.20.0

###  Have you found anything relevant by searching the web?

No.

### Any other information, logs, or outputs that you want to share?

No.

**Comment by katre** [comment]
Bazel's evalutation happens in three more-or-less distinct phases, which we call "load", "analysis", and "execution".

During the loading phase, BUILD, BUILD.bazel, foo.bzl, and other files are read into memory. This is the point where macros are expanded: they are literally just macros that create new build targets. You can view the expanded BUILD file with the `bazel query -output=build //path/to:target` syntax.

During the analysis phase, each target that needs to be built is checked, dependencies are analyzed, and the configuration is applied. This is the point at which `config_setting` targets are evaluated to see if they can match a `select()` call.

Because of the way macros work when they are expanded, the config_setting is still not evaluated, so the macro cannot consider that data.

Your options are the following:
1.  Write your macro so that the targets that get expanded contain the correct `config_setting` and `select` calls to handle the configurable conditions you need. It's enitlrely possible for macros to create select calls, and these will work as you expect. This is where viewing the macro-expanded build file with `--output=build` is helpful.

2. Write a custom rule to encapsulate your logic. This rule will be analyzed after configurable attributes are resolved, and so a custom rule can see the result of a `select()` call.

Since this isn't something we can fix, I am closing this issue. Feel free to reach out on the mailing lists or StackExchange for help on writing the macros or rules you need.
