### ISSUE TITLE
Can't use the same name for workspace and top-level python package

### ISSUE THREAD

**Issue by barancev** [bazelbuild/bazel#6897]
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Can't use the same name for the workspace and the top-level python package.
Use the attached sample project and run `bazel test python/...` to reproduce the issue.

[bazel-sample.zip](https://github.com/bazelbuild/bazel/files/2671945/bazel-sample.zip)

The test fails with an import error:
```
python\test\test_something.py:1: in <module>
    from some.thing import Something
E   ImportError: No module named thing
```

If I rename the workspace (in WORKSPACE file) to something different from 'some' (that is the name of the top level python package) the issue disappears.

### What operating system are you running Bazel on?

Windows 7

### What's the output of `bazel info release`?

0.19.2

**Comment by brandjon** [comment]
This ambiguity arises because both the runfiles root, and every repo root within that runfiles root, are put on `PYTHONPATH`. This means that when you do `import myrepo.package.package.module`, the myrepo part is optional.

The plan is to deprecate the form of import where the repo is omitted (#7067). At that point, package names won't be involved in import conflicts unless the repo name itself clashes or you're using the `py_library.imports` attribute.
