### ISSUE TITLE
There is no way to specify a root of python's package structure

### ISSUE THREAD

**Issue by barancev** [bazelbuild/bazel#6903]
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

In the selenium project (https://github.com/SeleniumHQ/selenium) we have a top-level directory per language. When we try and run python tests, it seems as if the root of the project is treated as part of python's package structure. In reality, it lacks an `__int__.py` file, and so shouldn't be.

Here is a sample project that mimics this structure:
[bazel-sample.zip](https://github.com/bazelbuild/bazel/files/2672820/bazel-sample.zip)

Run `bazel test python/...` to reproduce the issue.

Test fails with an import error `'No module named other.thing'`, bazel would like it to be `python.other.thing` as if the `python` directory is a part of python's package structure.

### What operating system are you running Bazel on?

Windows 7

### What's the output of `bazel info release`?

0.19.2

**Comment by clintharrison** [comment]
@barancev I am not able to reproduce this.
Using `imports = ["."]` is a reasonable way to fix the issue you described, as it will add the `python` subdirectory to `PYTHONPATH`. In your sample project, the reason it is not importing `other.thing` is because you have not declared `other` as a dependency anywhere.

With the following change to your BUILD file, I was able to get tests to pass:
```diff
+++ b/python/BUILD
@@ -1,11 +1,18 @@
+py_library(
+    name = "other",
+    srcs = glob(["other/**/*.py"]),
+    imports = ["."],
+)
+
 py_library(
     name = "some",
     srcs = glob(["some/**/*.py"]),
-    imports = ["."]
+    imports = ["."],
+    deps = [":other"],
 )
 
 py_test(
-    name = "test",
+    name = "some_test",
     srcs = ["conftest.py", "test/run_pytest.py", "test/test_something.py"],
     main = "test/run_pytest.py",
     deps = [":some"]
```
(`test` is renamed because your `py_test` target creates an executable called `test`, which is put in the runfiles as well: `runfiles symlink python/test/run_pytest.py -> python/test/run_pytest.py obscured by python/test -> bazel-out/darwin-fastbuild/bin/python/test`)

pytest output:
```
INFO: Found 2 targets and 1 test target...
============================= test session starts ==============================
platform darwin -- Python 2.7.12, pytest-4.0.2, py-1.7.0, pluggy-0.8.0
rootdir: /private/var/tmp/_bazel_charrison/72613869e4079d6c5b2a82a09e7b6fa5/sandbox/darwin-sandbox/1/execroot/somex/bazel-out/darwin-fastbuild/bin/python/some_test.runfiles/somex, inifile:
collected 1 item

python/test/test_something.py .                                          [100%]

=========================== 1 passed in 0.07 seconds ===========================
INFO: Elapsed time: 1.245s, Critical Path: 0.93s
```

In a more complex example, you may run into issues with py.test's modification of `sys.path`, as it tries to import tests by looking up in the directory structure for `__init__.py` files. To fix that error, you may need to set the `legacy_create_init` attribute on your `py_test` target to `False`.

**Comment by brandjon** [comment]
Thanks for the excellent response @clintharrison. I can confirm that this is WAI: Python targets can only import their in-workspace dependencies if those deps are in the target's runfiles, which doesn't happen if they're not declared directly or transitively as deps.

You can debug this kind of issue by dumping the actual runfiles manifest or inspecting its directory structure:

```
cd $(bazel info bazel-bin)/python
cat some_test.runfiles_manifest  # or...
cd some_test.runfiles
```
