### ISSUE TITLE
http_archive doesn't replace older new_http_archive in 0.20 release

### ISSUE THREAD

**Issue by mnlnl4** [bazelbuild/bazel#6924]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
In 0.20, http_archive seems to always parse BUILDs file in downloaded repo. But older new_http_archive ingores them which allows customizing BUILD file. E.g. I have a project depends on 
RPC status proto in https://github.com/googleapis/googleapis. I can write a small BUILD file just for that small part. Now with http_archive, bazel always tries to parse BUILD files in the repo, it requires a lot more work in WORKSPACE file to make things to work. 

> Replace this line with your answer.

### Feature requests: what underlying problem are you trying to solve with this feature?

> Replace this line with your answer.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Replace this line with your answer.

### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

> Replace this line with your answer.

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

> Replace this line with your answer.

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by dslomov** [comment]
You can use `@//path/to/BUILD.customized` to access BUILD files from the main reepository

**Comment by rkallal** [comment]
I am having the exact same issue in 19.2 related to pulling in https://github.com/googleapis/googleapis using http_archive. In 19.2, this path would not work "@//path/to/BUILD.customized" to access a local BUILD file but this path would work "@//path/to:BUILD.customized" provided that you have a dummy BUILD file in the the "to" directory. Even with that path specified, bazel appears to attempt to read the BUILD files found in the external directory where the http repository was unzipped.  In my specific case, it appears to die because it can't file the BUILD file.

Here is my WORKSPACE section that pulls in the googleapis:

http_archive(
    name = "googleapis",
    sha256 = "7b6ea252f0b8fb5cd722f45feb83e115b689909bbb6a393a873b6cbad4ceae1d",
    url = "https://github.com/googleapis/googleapis/archive/143084a2624b6591ee1f9d23e7f5241856642f4d.zip",
    strip_prefix = "googleapis-143084a2624b6591ee1f9d23e7f5241856642f4d",
    build_file = "@//bazel/pkg:BUILD.googleapis",
)


Here is what my BUILD.googleapis has in it. It might be related to the cpp_proto_compile from build_stack_rules_proto but I am not yet convinced of that.

package(default_visibility = ["//visibility:public"])
load("@build_stack_rules_proto//cpp:cpp_proto_compile.bzl", "cpp_proto_compile")
load("@build_stack_rules_proto//cpp:cpp_grpc_compile.bzl", "cpp_grpc_compile")

# Tried with "@" vs "@googleapis//" crossed with "v1:" and "v1/" 
proto_library(
  name = "googleapis_proto",
  srcs = [ "@//google/devtools/build/v1:build_status.proto", ],
  visibility = ["//visibility:public"],
)

proto_library(
  name = "googleapis_grpc",
  deps = ["googleapis_proto"],
  srcs = [ "@//google/longrunning:operations.proto", ],
  visibility = ["//visibility:public"],
)

cpp_proto_compile(
    name = "googleapis_proto_cc",
    deps = [ ":googleapis_proto" ],
)

cpp_grpc_compile(
   name = "googleapis_grpc_cc",
   deps = [ ":gooleapis_grpc" ],
)


I get this failure when 19.2 runs:

NFO: Build options have changed, discarding analysis cache.
ERROR: /tmp/bazel/3f2a9cfea13caab96887ef2b4facfd85/external/googleapis/BUILD.bazel:19:1: no such package 'google/devtools/build/v1': BUILD file not found on package path and referenced by '@googleapis//:googleapis_proto'
ERROR: Analysis of target '//src/cpp/worker:worker' failed; build aborted: no such package 'google/devtools/build/v1': BUILD file not found on package path
INFO: Elapsed time: 1.758s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 12267 targets configured)

**Comment by dslomov** [comment]
Sorry I mislead you: the path is indeed `@//path/to:BUILD.customized`.
This error message:
> ERROR: /tmp/bazel/3f2a9cfea13caab96887ef2b4facfd85/external/googleapis/BUILD.bazel:19:1: no such package 'google/devtools/build/v1': BUILD file not found on package path and referenced by '@googleapis//:googleapis_proto'

tells you that `@//google/devtools/build/v1` is not a package in Bazel's sense: see this [overview](https://docs.bazel.build/versions/master/build-ref.html#labels) for details on labels, packages, and targets.

**Comment by rkallal** [comment]
That makes more sense now. Thank you.
