### ISSUE TITLE
Versioned Docs: the navigation sidebar should also be versioned

### ISSUE THREAD

**Issue by jin** [bazelbuild/bazel#6937]
Currently, the doc contents are versioned. However, the navigation sidebar isn't, and will link to 404s when the requested page does not exist for a particular release, or that the links simply don't exist in the sidebar if it's been removed from git-master.

Neither of these are regressions from the previously git-master-only docs, but it would be nice to have the sidebar versioned as well.

**Comment by spomorski** [comment]
Me and axgillies@ recently discovered this problem recently and it's important that we fix this ASAP.

Not having a matching nav tree per versioned docset makes the versioned docsets feature a lot less useful since users will look for docs that have been moved, renamed, or deleted, not find them in the nav tree when viewing an older docset, and assume the docs are gone.

Can we give this a high priority? I think it's a serious usability problem that negatively impacts the Bazel user experience.

**Comment by jin** [comment]
@fweikert I discovered this and assigned it an initial P2. Could you please take a look and re-triage its priority? Thanks!

**Comment by fweikert** [comment]
@jin - who should own this issue? You're the expert for versioned documentation :)

**Comment by aiuto** [comment]
If we can do any quick fix, that would be fine for now.
For Federation releases, I want to do versioned doc sets that include rules too, with links to bazel at the appropriate federation version. We will have to redo the docs pipeline at that time. 
So then the question is if this EngProd, Product, or DevExp at that time.

**Comment by jin** [comment]
bumping this up to p1. I'll take a look at it sometime next week.

**Comment by jin** [comment]
Moving to team-XProduct as part of the recent team merge.

**Comment by jin** [comment]
Closing this: we can now apply version conditionals in the navigation bar.

**Comment by jin** [comment]
Reopening this issue to actually version the sidebar without conditionals
