### ISSUE TITLE
dicts are unhashable

### ISSUE THREAD

**Issue by Profpatsch** [bazelbuild/bazel#6975]
We have a `set` implementation that uses `dict` keys as internal implementation (similar to [skylib’s `new_set`](https://github.com/bazelbuild/bazel-skylib/blob/master/lib/new_sets.bzl)).

When I want to create a `set({ 'foo': sometarget, 'bar': someothertarget})`, it fails:

```
unhashable type: 'dict'
```

It’s baffling to me that targets are hashable and dicts are not. Is there any particular reason why dicts can’t be made hashable, and if not, could I politely request that they would be made hashable?

**Comment by guibou** [comment]
I think it comes from python where `dict` are not hashable. Actually, by default, in python, mutable objects are not hashable, which makes sens because if you later modify a mutable object which is already stored in a dict / set, the dict / set will be in an undefined state: it stores object at hash location with unrelated hash.

**Comment by Profpatsch** [comment]
The solution is to use:

```
set(
  struct(
    foo = sometarget,
    bar = someothertarget,
  )
)
```

`struct`s are immutable and thus hashable.

Thanks to @guibou for the solution!
