### ISSUE TITLE
Need a way to get a path to python interpeter

### ISSUE THREAD

**Issue by solomatov** [bazelbuild/bazel#7002]
### Description of the problem / feature request:
I want to run a python based tool such as pylint

### Feature requests: what underlying problem are you trying to solve with this feature?
I don't want people running our build install pylint manually as well as running from manually installed virtual environment. I want it to be installed via repository rule without any extra actions.

### What operating system are you running Bazel on?
OSX and Linux

### What's the output of `bazel info release`?
release 0.20.0-homebrew

###  Have you found anything relevant by searching the web?
I found that there're tool variables for C/C++ and Java but there's no such a variable for Python

### Any other information, logs, or outputs that you want to share?
No

**Comment by brandjon** [comment]
You're asking for pylint to be distributed via Bazel to users using a repository rule? This seems to be treating Bazel as a package manager rather than a build tool. Or do you mean you want pylint automatically invoked as part of the build process, and to block the build if it detects any warnings/errors?

**Comment by brandjon** [comment]
See also #7805.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
