### ISSUE TITLE
Can toolchains  of  cc_library be used to specify a compilation toolchain for a target?

### ISSUE THREAD

**Issue by ax7476** [bazelbuild/bazel#7020]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:
I want to customize rules, like cc_library, to use the specified toolchain. Usage toolchains parameters of  cc_library  do not work. 
Can toolchains  of  cc_library be used to specify a compilation toolchain for a target?

### Feature requests: what underlying problem are you trying to solve with this feature?

Specify a compilation tool chain for some target

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

cc_library(
    name = "hello-greet",
    srcs = ["hello-greet.cc"],
    hdrs = ["hello-greet.h"],
    toolchains = ["//test:my-cc-compiler"],
)
Setting parameters toolchains,but "//test:my-cc-compiler" compilation tool chain is not used.

### What operating system are you running Bazel on?

Linux moonx 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What's the output of `bazel info release`?

WARNING: Processed legacy workspace file /home/moonx/Downloads/apollo/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
Starting local Bazel server and connecting to it...
release 0.18.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Build label: 0.18.1

### 

bazel-0.18.1-installer-linux-x86_64.sh install

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

**Comment by ax7476** [comment]
> This is not the ideal way to specify toolchains. What do you expect to happen if you hardcode a toolchain which uses a linux gcc binary, but someone tries to build your project on Windows? The main point of the toolchain resolution process is to better support these types of multi-platform scenarios.
> 
> Let's go back to the actual use case: what's the original problem you wanted to solve, that you thought hard-coding a specific toolchain would be the answer?

I want to compile some code with nvcc and some code with GCC in the same project.
Custom my_cc_library for nvcc compilation:
def my_cc_library(
        name,
        srcs = [],
        deps = [],
        copts = [],
        **kwargs):

    cc_library(
        name = name,
        copts =  copts,
        srcs = srcs,
        deps = deps,
        toolchains = ["//test:my-cc-compiler"],
        **kwargs
)

**Comment by katre** [comment]
We don't currently have a way to do this that I am aware of.  @hlopko, is this something your team plans to support?

**Comment by hlopko** [comment]
The only way I know of is to have one toolchain that can handle both. That's what tensorflow does, they have wrapper scripts around compilers and depending on the command line flags they use cuda or clang.

**Comment by jin** [comment]
@gregestren could you add a [priority](https://www.bazel.build/maintainers-guide.html#priority) to this issue, please?

**Comment by dslomov** [comment]
Please do not assign issues to more than one team.

**Comment by Monnoroch** [comment]
@katre why is this closed?

**Comment by katre** [comment]
@Monnoroch Because this is not a feature that we currently plan to add to `cc_library`. Directly coupling a specific toolchain to a specific library is not portable and is not a use case we are prioritizing.

**Comment by ccontavalli-j** [comment]
@katre is there a recommended way to use multiple C++ toolchains in the same project, to support, eg, libraries that require gcc, and libraries that require clang?

**Comment by katre** [comment]
You would need to ask the cc rules maintainers. I suggest asking on the bazel-discuss mailing list.

**Comment by Monnoroch** [comment]
I don't think this is about cc_rules. It's a fundamental build system issue. Most languages have multiple toolchain options and code is very often toolchain-dependent. Doesn't matter, what the language is, be it C or D or Go or even Python, there's always going to be room for building different targets with different compilers.

My research on this topic tells me that currently this is impossible, as in, you'd have to write your own msvc_cc_library and friends if you want to build some targets with msvc and the rest with gcc, for example. I myself had to write cc_* rules for TI toolchain (which I currently can't open source) to build a firmware image and run unit tests under Linux for the same code in one `bazel test //...` invocation. I feel that this is something the build system rather than individual language rules has to solve it at least aid solving.

**Comment by luxe** [comment]
Could this be achieved through [transitions](https://docs.bazel.build/versions/master/skylark/lib/transition.html#transition) now?
I see "Flagless multiplatform builds" on the [roadmap](https://bazel.build/roadmaps/configuration.html), but it is not started yet.

**Comment by katre** [comment]
The overall problem "can a specific cc toolchain be used for a specific cc target?" could be implemented with a combination of transitions and custom cc toolchain declarations.

The more bazel-centric way to handle this may be with [execution constraints](https://docs.bazel.build/versions/master/be/common-definitions.html#common.exec_compatible_with). This would allow you to mark certain targets as only being able to build on a platform with a specific constraint (say, nvcc-available). Then the nvcc toolchain would also have that present, allowing the correct cc toolchain to be selected (but requiring you to double the number of execution platforms).

**Comment by luxe** [comment]
Does "toolchain resolution" only occur **once** at the start of a build?  If so, this may insufficient for us. 
 We are looking for a way to use both clang and nvcc simultaneously from the same build invocation.  But I think I understand what you are saying.  

1. Build two platforms:  
     - a nvcc supported platform
     - a clang supported platform

2. Build two toolchains
     - an nvcc toolchain tied to the nvcc platform
     - an clang toolchain tied to the clang platform

3.  Tie particular targets to these platforms via execution constraints

3. based on the toolchain resolution, which I think is a globally configured thing, the right rules will be executed using the correct cc_toolchains.  And building everything would look like this:  
```
bazel build --platforms=@nvcc_platform ...
bazel build --platforms=@clang_platform ...
```

With the birth of transitions this can be reduced to a single build invocation, but may not be a "bazel best practice". 


Now I may be conflating ideas here, but I think we could elegantly dispatch between clang and nvcc by overwriting the standard cc action configs in our crosstool.  Example:  
```
    nvcc_action = action_config(
        action_name = ACTION_NAMES.cpp_compile,
        enabled = True,
        tools = [
        tool(path = "wrappers/nvcc_clang",with_features = [with_feature_set(features = ["cuda_nvcc"])]),
        tool(path = "wrappers/clang",with_features = [with_feature_set(not_features = ["cuda_nvcc"])])
        ],
    )
```

Then:
 - Set the correct flags for the two different tools by leveraging features.  
 - Tie particular targets to these features (enabling /disabling)

Maybe that's also bad form because the same cc_toolchain is acting sort of like two toolchains, but this may be the easist way to do what we want.  

Worst case scenario, we were going to mimic what tensorflow does:  
Spawn a python file as our cc tool which parses the cli, and chooses gcc or nvcc (see: crosstool_wrapper_driver_is_not_gcc).  
At least the above approach seems cleaner than that.  I do wonder why tensorflow did that instead of what I'm proposing.

**Comment by katre** [comment]
Toolchain resolution is performed for every configured target, and depends on the target itself (specifically, its rule implementation), and the available toolchains and execution platforms. Please read the documentation at https://docs.bazel.build/versions/1.2.0/toolchains.html for details.

Also, please discuss this with the CC rules team, as they may have better ideas on how to express this in Bazel builds.

**Comment by aadwived** [comment]
> The only way I know of is to have one toolchain that can handle both. That's what tensorflow does, they have wrapper scripts around compilers and depending on the command line flags they use cuda or clang.

Is this feature introduced in the latest releases of bazel?
>>release 3.7.2

What I want to do is as follows:

I intend to compile a part of the project with clang, while the rest of the project is compiled with GCC.
A clang toolchain is configured, which is only required for one dependency in the whole project.

Is there a way to specify in cc_library of this dependency what toolchain to use?

**Comment by pauldraper** [comment]
> please discuss this with the CC rules team

I don't see anything here that's inherently specific to C++ rules. It's a fundamental aspect of the toolchain paradigm.

I would like to understand the canonical way for rules to influence toolchain selection. For example, a library that is only compatible with glibc.

Constraints is poor solution, as it prevents the targets from being in the same build, which limits flexibility. For example, a binary that is used as a tool for another target.

Of course, you can just avoid using toolchains altogether, and use explicit rule inputs instead. But Bazel is really trying to push this global toolchain thing.

**Comment by katre** [comment]
This is no longer an issue that can be resolved on GitHub. Please raise this on the bazel-discuss mailing list if you'd like to discuss when and whether toolchains are appropriate.

I'll go ahead and restate myself from earlier: the toolchain system that Bazel has introduced is intended to allow from cross-platform builds. If you wish to tie your code to a specific toolchain, you'll need another mechanism. I'm happy to discuss this in a wider forum where more users can notice and interact with the conversation.
