### ISSUE TITLE
Gracefully handle large stdout from remotely-executed actions.

### ISSUE THREAD

**Issue by bwkimmel** [bazelbuild/bazel#7034]
### Description of the problem / feature request:

Actions may generate very large stdouts (e.g., several hundreds of megabytes), which may or may not be needed by the client (it might not be needed, for example, for a successful test run). If the action was executed remotely, sending this back to the client may incur significant network overhead. Since the remote execution API indicates the digest of stdout/stderr, Bazel could handle large output more gracefully. For example, the first N bytes (say somewhere in the range of a few KB to a MB) could be displayed. If the output goes beyond that, the digest could be displayed instead, allowing the user to find the remainder of the output if needed.

### Feature requests: what underlying problem are you trying to solve with this feature?

Reduce network overhead/latency involved in streaming large output which may not be needed.

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 0.21.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

**Comment by buchgr** [comment]
@bwkimmel would you be able to quantify the headache this causes (e.g. what percantage of actions have stdout/stderr > 100KiB?).

In general it's a tricky one:
* We want remote execution to behave as similar to local execution as possible.
* We currently don't have a general mechanism to provide blobs from the CAS for download i.e. a bytestream URL is not something a user can just click on. So the user experience there would not be great. We might want to add a download command to Bazel that can fetch blobs?
* If we only download the first N bytes of a >>N byte blob then this will likely be a waste of bandwidth, since most likely the first N bytes won't contain the information relevant to the user. So there we might just want to not download anything.

A first step might be to quantify the problem as part of https://github.com/bazelbuild/bazel/issues/6727

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by coeuvre** [comment]
Deduplicate this against https://github.com/bazelbuild/bazel/issues/19782 because the latter is a more concrete request.
