### ISSUE TITLE
Add additional timing information to BEP

### ISSUE THREAD

**Issue by willsc79** [bazelbuild/bazel#7052]
### Description of the problem / feature request:

The feature request is to add a duration field to the BEP events target_completed and test_summary.

### Feature requests: what underlying problem are you trying to solve with this feature?

The duration information reported in BEP should match the duration reported by Bazel in the CLI and log. This will allow clients that are reading BEP to report this information correctly to their users. Currently we have to calculate the target duration based on finish time alone.

**Comment by ittaiz** [comment]
Might be obvious but just to add that the current outcome of calculating
according to finish time is that we see the time between the target being
discovered (not sure the term is correct, maybe configured is better) to
finished. This is valuable to analyze critical path but is insufficient.

**Comment by ulfjack** [comment]
I'm not sure what you're looking for, exactly. The TestResult message has a duration. For the summary on the command line, I think we're just computing min, max, avg, and stddev from the durations of the individual results. Someone recently noted that the time summary isn't all that useful for tests that have multiple shards, because different shards can have very different performance profiles. Personally, I disable the CLI test summary for passing tests (using --test_summary=testcase).

What kind of data would you like to see in target_completed? I don't think we do anything on the CLI for that right now.

**Comment by ittaiz** [comment]
@willsc79 wdyt? Does the BEP contain the timing information?

**Comment by jmmv** [comment]
It is unclear to me why this bug is tagged with `team-Local-Exec`. Is this really tied to local execution, or the same feature request would apply to remotely-executed actions? If so... this should be reclassified, but I have no idea what `team-*` label applies.

**Comment by dslomov** [comment]
This is the issue that affects both local and remote execution.

**Comment by jmmv** [comment]
@dslomov Well then I'm not sure which `team-*` would best handle this. Maybe Performance? Or maybe we do need a separate category for BES/BEP issues? I think I favor the latter at this point.

**Comment by eduardojmc** [comment]
@ulfjack 
This issue seems to be high priority for some customers - we have good timing for individual test actions, but the timing for the entire target/configured target is inconsistent since this data is not reported in BEP. In this case, we don't even know how the data is computed in the CLI so it is understandable that it might differ a lot. Having imprecise/inconsistent data makes an UI driven by BEP an unreliable tool (for that particular data).

From a design stand point my understanding is that BEP should be powerful enough to be the source of data for the Bazel CLI itself and other UIs, so that was the main motivation for this feature request.

>  What kind of data would you like to see in target_completed? I don't think we do anything on the CLI for that right now.

The data that we'd like to show in the UI is the duration of a target/configured target. There can be multiple definitions of a duration for that (build_started -> target_completed? pattern_expanded -> target_completed?). By having this data reported on BEP (on target_completed and test_summary) we get both a well-defined and consistent duration for a target/configured target.

**Comment by ulfjack** [comment]
We have no plans of reporting per-target / per-configured-target durations, and I still have no idea what such a thing would even look like. If there's already data in the BEP, its semantics are not well-defined.

**Comment by ittaiz** [comment]
I’ll add that we are really feeling the absence of this data in order to
make intelligent decisions (for example show compilation times, for one
run, over time, and many more).
I expect Bazel to support a data driven CI but it doesn’t right now

**Comment by ulfjack** [comment]
The absence of _what_ data? I am not aware of any per target or per configured target value that would give you any meaningful insight into build performance.
