### ISSUE TITLE
Starlark transition whitelist is hardcoded

### ISSUE THREAD

**Issue by clintharrison** [bazelbuild/bazel#7056]
### Description of the problem / feature request:
c2200fd8e95b1c93b52ddd10725138f01e1c01a0 introduced a whitelist for which targets are able to use rules with Starlark-defined transitions. This is hardcoded to `//tools/whitelists/function_transition_whitelist`, which presumably doesn't make much sense outside of google3.

It also is easy to get wrong: using it outside the main workspace (e.g. in `rules_docker`) requires the rule to set the attribute's default to `@//tools/whitelists/function_transition_whitelist` -- otherwise, it's impossible to use, since downstream users cannot override it; it starts with `_`.

cc @juliexxia, who asked for this issue after I reported it on Slack 🙂 

### Feature requests: what underlying problem are you trying to solve with this feature?
I would like to use the experimental configuration transitions in a `rules_docker` fork to build all `container_image` dependencies for linux/x64.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
I can upload a repo to repro if needed.

### What operating system are you running Bazel on?
macOS 10.14

### What's the output of `bazel info release`?
bazel 0.21.0

**Comment by gregestren** [comment]
Did we want the whitelist enabled at all for Bazel?

Most important is that you understand the performance/memory/efficiency consequences of adopting these transitions, e.g. themes prioritized on https://bazel.build/roadmaps/configuration.html, and don't get caught off guard.

My hunch is that for a lot of Bazel projects the scale is small enough where it's worth the risk.

**Comment by juliexxia** [comment]
IIRC our plan was to have all of Bazel "whitelisted". I think that's going to require module-izing some of the whitelist logic so I'll work on that!

**Comment by juliexxia** [comment]
While I'm doing that, @clintharrison can tell us a little more about how you're using transitions()? i.e. what kind of transitions you're trying to write? Parts of the transition functionality are still in development but quite a bit of it is already out there. Since you're an early user definitely want to hear which parts you're interested in!

**Comment by clintharrison** [comment]
@juliexxia sure! We use `rules_docker` to build container images for Python apps. All of our third-party dependencies are available as precompiled distributions for both Linux and macOS, and we choose them in `py_image` and `py_binary` targets' `deps` by `select()`ing based on `@bazel_tools//platforms:osx` or `:linux`. (Under the hood, they're `http_archive`s we unpack into a `py_library` with `whl_archive` from `rules_python`.)

All developer machines here are Macs, but we'd still like to be able to build a Docker image there, so a simple transition on `--platform` to linux/x64 is all we need. Right now, we suboptimally force the whole build to a linux platform, which causes some difficulty when we want to mix Mac-target output and Docker-image-output in test runs.

https://github.com/clintharrison/rules_docker/commit/188a6b9a4374f9334d093b5f9a37504ac4a4b7bf is a quick change to rules_docker which seems to accomplish what we need -- though I had to work around the current behavior (focusing on split transitions?) which causes a `Label` to always become a `List<Label>`. Pretty happy with how easy it was to get working 🙂

**Comment by gregestren** [comment]
Neat. This is such a core kind of transition we're angling to support (`--platform`) that we may one day support it universally for all rules. Nice guinea pigging!

Can your binaries target either Mac or Linux? So does a `docker_platform_transition` inherently imply Linux, or can that also imply Mac depending on the binary? 

I think it'd be great to opt your project into this, although we may want to be careful about generic `rules_docker` support for other projects due to scaling consequences that should be understood.

**Comment by clintharrison** [comment]
The py binaries can run under Mac or Linux, but if you're putting the binary in a `container_image`, it doesn't make sense to have Mac dependencies -- there is no concept of a "mac container".

As to the last point, I think I'm a little confused. What "scaling consequences" do we need to be aware of for 1-1 transitions? I thought the primary concern was unexpected consequences of split transitions.

I do understand the hesitation for using it for all `rules_docker` users. Once 0.22 is out (with the two-parameter transition implementation function from 1bcaf62b4cd836a894c67df2f353fa83ad386607), we can use an attr to make it opt in, rather than all-or-nothing. But perhaps that's a conversation best had on [rules_docker](https://github.com/bazelbuild/rules_docker) :)

**Comment by jin** [comment]
@gregestren issues must have [either the `untriaged` or a priority label](https://www.bazel.build/maintainers-guide.html#issues); could you assign one please?

**Comment by gregestren** [comment]
Split transitions exaggerate the problem. But there are also scaling consequences with 1-1 transitions (*maybe*: it really depends on how your builds are structured, so the point isn't to alarm but to promote due diligence).

Transitions on non-platform flags could impact remote execution caching, if that's a setup you're working with. But that's not so much a problem for `--platform` flags.

Transitions also increase the size of the build graph, which implies how much memory Bazel needs to do the build. A worst case story would be `bazel build //foo:for_mac //foo:for_linux` where `//foo:for_mac` and `//foo_for_linux` have the same exact dependencies (like they're the same exact binary, just targeted for different platforms).

That essentially doubles the build graph, since each transitive dependency is configured twice: once for each platform.

If `//foo` has 10 targets for 10 platforms, you could get a 10x increase. etc.

So those are the basic concerns. And they matter more the bigger your builds are and the more variations in which you want to reconfigure your rules. Ultimately you know best how to weigh these issues.

`rules_docker` is more sensitive since neither you nor I know how other projects are going to weigh these issues. So we need to be more careful about what they get opted into and their awareness of the same issues.

**Comment by prestonvanloon** [comment]
Is there any update on this feature? I am still having the same issue with bazel v2.

```
ERROR: Built-In: Use of Starlark transition without whitelist: //tools:binary_targets.bzl NORMAL
```

**Comment by prestonvanloon** [comment]
I unblocked myself by adding the _whitelist_function_transition attribute.

```starlark
go_image_debug = rule(
    implementation = _go_image_debug_impl,
    attrs = {
        "image": attr.label(
            cfg = build_in_debug_mode,
            executable = True,
        ),
        "_whitelist_function_transition": attr.label(default = "@bazel_tools//tools/whitelists/function_transition_whitelist"),
    },
)
```

**Comment by gregestren** [comment]
@prestonvanloon I believe that's the recommended solution. Any rule can use this feature but it needs to define that attribute for two reasons:

1) It's a forcing function to acknowlege that transitions can have performance cost
2) `@bazel_tools//tools/whitelists/function_transition_whitelist` defaults to everything:

https://github.com/bazelbuild/bazel/blob/8536172a6743c3ca05c49dddc63325bf69dc5799/tools/whitelists/function_transition_whitelist/BUILD#L4-L6

but gives project owners the ability to narrow that down if desired.

If that's not documented on https://docs.bazel.build/versions/master/skylark/config.html we should file a documentation bug to ensure that's clear.

**Comment by juliexxia** [comment]
Closing this since it's old and it looks like we've documented best practices
