### ISSUE TITLE
Bazel CI: Mac builds are flaky (Unexpected IO error)

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#7064]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/736#3d6288f7-3bba-4994-a5cc-f8566909a8de

We get `Unexpected IO error` quite often for macos builds.
```
ERROR: /Users/buildkite/builds/buildkite-imacpro-9/bazel-downstream-projects/migration-tooling/third_party/BUILD:22:1: Couldn't build file third_party/_ijar/maven_model/third_party/maven_model/maven-repository-metadata-3.2.3-ijar.jar: Extracting interface //third_party:maven_model failed: Unexpected IO error.: /private/var/tmp/_bazel_buildkite/79d4575926210ee9a56b311da1bc22dc/execroot/__main__/third_party/maven_model/maven-repository-metadata-3.2.3.jar (No such file or directory)
```

/cc @philwo

**Comment by ob** [comment]
I don't have access to the logs in build kite, and "Unexpected I/O error" isn't really helpful but I'll go ahead and mention that in a large macOS cluster I've seen strange I/O problems due to leakage of POSIX semaphores. I'm not saying this is the case here, but a way to check Is by running 
```
zprint | head -2 ; zprint | grep sema
```
and comparing it with `kern.posix.sem.max`...

**Comment by meteorcloudy** [comment]
I think this is a duplicate of https://github.com/bazelbuild/bazel/issues/4751
