### ISSUE TITLE
Platforms should support a "test_runtime"

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#7092]
### Feature requests: what underlying problem are you trying to solve with this feature?

(This bug report is a paraphrased version of a question by @trybka .)

Bazel's "test runtime" is `//tools/test/test-setup.sh`. It  effectively sets up the "runtime" environment (copies runfiles, sets env vars, what have you).

It'd be nice if for example "bazel test --platforms=//android:sdk21 //:foo_cc_test" could have a different "runtime" setup which starts an emulator for sdk21, copies foo_cc_test over, and runs it.

There appears to be ad-hoc one-off precedent for this with Windows.
See: https://github.com/bazelbuild/bazel/pull/5925
which appears to have added a one-off way to slot in a different "test_runtime."

/cc @trybka @katre

**Comment by katre** [comment]
This is a good idea: the next step is to figure out how it ties into the overall platform concept.

**Comment by jyknight** [comment]
I think it'll need to be a bit trickier than just running a different setup script around the invocation of a normal binary -- the "test runtime" also needs to be able to affect how the test binary gets built in the first place.

E.g., on iOS, tests should to be built into a shared object, which gets loaded by the test-runner framework binary, rather than building a standalone executable for the test cases.

**Comment by trybka** [comment]
Sure. Could that be expressed as a separate request of cc_test? (Distinct from the test_runtime).

Which is not to say that a single script can actually encompass the whole notion of arbitrary "Test Runtimes"
