### ISSUE TITLE
[FR] .bazelignore should support wildcard prefix

### ISSUE THREAD

**Issue by or-shachar** [bazelbuild/bazel#7093]
### Description of the feature request:
Currently `.bazelignore` supports only full relative path prefix without any wildcards

I have many `node_modules` subfolders in my repo that I want to ignore.
With `.gitignore` I'd just need to put: `node_modules` and it will be ignored by git.
With `.bazelignore` I need to specify each folder by it's full relative path from workspace root.

I suggest to adjust behavior to the way `.gitignore` and save our users the trouble of collecting all folders.

### What operating system are you running Bazel on?
We tested it on linux with bazel 0.20.0 and 0.21.0

**Comment by ittaiz** [comment]
@iirina @dslomov when can we expect this to be triaged?

**Comment by jupp0r** [comment]
Is somebody working on this issue? If not, I'd like to start working on a patch.

**Comment by gregmagolan** [comment]
+1 for the Angular repo. `.bazelrc` could be a few lines with wildcards instead of ```node_modules
dist
aio/content
aio/node_modules
aio/tools/examples/shared/node_modules
integration/bazel/bazel-bazel
integration/bazel/bazel-bin
integration/bazel/bazel-out
integration/bazel/bazel-testlogs
integration/bazel/node_modules
integration/bazel/.yarn_local_cache
integration/bazel-schematics/node_modules
integration/bazel-schematics/.yarn_local_cache
integration/bazel-schematics/demo
integration/cli-hello-world-ivy-compat/node_modules
integration/cli-hello-world-ivy-compat/node_modules
integration/cli-hello-world-ivy-i18n/node_modules
integration/cli-hello-world-ivy-minimal/node_modules
integration/cli-hello-world-lazy/node_modules
integration/cli-hello-world-lazy-rollup/node_modules
integration/dynamic-compiler/node_modules
integration/hello_world__closure/node_modules
integration/hello_world__systemjs_umd/node_modules
integration/i18n/node_modules
integration/injectable-def/node_modules
integration/ivy-i18n/node_modules
integration/language_service_plugin/node_modules
integration/ng_elements/node_modules
integration/ng_update/node_modules
integration/ng_update_migrations/node_modules
integration/ngcc/node_modules
integration/platform-server/node_modules
integration/service-worker-schema/node_modules
integration/side-effects/node_modules
integration/terser/node_modules
integration/typings_test_ts36/node_modules
integration/cli-hello-world/.yarn_local_cache
integration/cli-hello-world-ivy-compat/.yarn_local_cache
integration/cli-hello-world-ivy-i18n/.yarn_local_cache
integration/cli-hello-world-ivy-minimal/.yarn_local_cache
integration/cli-hello-world-lazy/.yarn_local_cache
integration/cli-hello-world-lazy-rollup/.yarn_local_cache
integration/dynamic-compiler/.yarn_local_cache
integration/hello_world__closure/.yarn_local_cache
integration/hello_world__systemjs_umd/.yarn_local_cache
integration/i18n/.yarn_local_cache
integration/injectable-def/.yarn_local_cache
integration/ivy-i18n/.yarn_local_cache
integration/language_service_plugin/.yarn_local_cache
integration/ng_elements/.yarn_local_cache
integration/ng_update/.yarn_local_cache
integration/ng_update_migrations/.yarn_local_cache
integration/ngcc/.yarn_local_cache
integration/platform-server/.yarn_local_cache
integration/service-worker-schema/.yarn_local_cache
integration/side-effects/.yarn_local_cache
integration/terser/.yarn_local_cache
integration/typings_test_ts36/.yarn_local_cache
packages/bazel/node_modules
```

**Comment by cgruber** [comment]
+1 for all the rules_* repos, which typically have a variety of sub-repos to handle testing the rules.

**Comment by David-Lam** [comment]
Hi everyone! I have create a PR https://github.com/bazelbuild/bazel/pull/13756 that add wildcard to .bazelignore. Feel free to review it. Thanks!

**Comment by nkoroste** [comment]
also related https://github.com/bazelbuild/bazel/pull/13807

**Comment by guw** [comment]
Is this a dup of [#8106](https://github.com/bazelbuild/bazel/issues/8106)?

**Comment by Toxaris** [comment]
Experience report:

Like others, we have a monorepo where developers run `bazel build //...` but we also install NodeJS packages into `node_module` folders in the source tree (to make the IDE happy). We would prefer to put `**/node_modules` into the `.bazelignore`, but since that is not supported, we have a script that generates the `.bazelignore` from the repo structure, and a check in our CI that the `.bazelignore` has been generated by the script.

Even with these precautions, we run into issues after the repo structure has changed upstream and a developer does `git checkout` or `git pull` on their machine. Developers will get the new `.bazelignore` but still have the old `node_modules` folders in their source tree. Since the `node_module` folders contain symlinks to internal dependencies, `bazel` will expand the dependency graph into a tree and find an exponential number of copies of our internal packages. It will either crash because of memory issues, or try to make sense of these weird packages and run into visibility issues.

I acknowledge that the root cause here is really that we put non-source files into the source tree, but we are not aware of a practical way to avoid. Wildcards in the `.bazelignore` file would give us a much nicer development experience in practice.

**Comment by chadxzs** [comment]
My team would really appreciate this feature. We're having issues right now because we're running into "infinite symlink expansion detected" when Bazel traverses into `.terraform` directories due to the way we are structuring our terraform code. It would be nice to be able to add a global `.terraform` ignore to prevent Bazel from encountering this.

Additionally, we're running into the same sort of issue with the `node_modules` being problematic and having to add an ignore line for each instance of this in our monorepo.

If we do a broad `.bazelignore` for a whole subtree that may contain these files, the IntelliJ Plugin for Bazel ignores these paths in the project view, which causes these paths to be excluded from things like code search which we value.

**Comment by dgoldstein0** [comment]
+1 to this.

Ran into this in the node_modules context, similar to @Toxaris, but probably a little simpler of a failure mode - rxjs is one dep of ours that uses some third party bazel rules, which crash any bazel queries that use `...` over the folder after it's installed as we don't have the repositories it uses configured in our workspace.

I would love if .bazelignore worked more like .gitignore - e.g. support .gitignore syntax and/or support distributed .bazelignore files.  (With the latter, we could make a yarn plugin that adds node_modules/.bazelignore whenever we yarn install - but the plugin approach obviously doesn't generalize to other folks' problems)

**Comment by dgoldstein0** [comment]
any chance of getting this prioritized? seems like this would be an easy thing to fix and a good experience win for users of .bazelignore.

**Comment by armandomontanez** [comment]
When working in a project that has parallel CMake support via `ExternalProject_Add` , it'd be really nice if I could just .bazelignore `cmake-*` to prevent Bazel from trying to pick up the build directories produced by CMake.

**Comment by zbowling** [comment]
Any updates?

**Comment by David-Lam** [comment]
Hi folks! Sorry I no longer have time to complete this. Please feel free to take a stab if interested. Thanks!

**Comment by meteorcloudy** [comment]
We do have a REPO.bazel for repo-level configuration, I think that would be a good place to merge ".bazelignore"

**Comment by lberki** [comment]
Good call. I forgot about the existence of `REPO.bazel`, which is just the perfect place for this functionality. Let me see if I can crank out the code today...

**Comment by lberki** [comment]
Ok, I give up (for today). This ended up being _way_ more involved than I had expected. I'll regroup and maybe try again tomorrow.

**Comment by lberki** [comment]
I have a change out that *almost* works. The "almost" part is because apparently requring the evaluation of `REPO.bazel` to determine the ignored package prefixes when the `WORKSPACE` file is enabled sometimes results in a Skyframe dependency cycle (for example in `testNoModuleDotBazelAndFallbackToWorkspace`).

The dependency cycle is as follows:

1. The repo mapping for the main repository depends on the `//external` package (this makes sense)
2. The `//external` package depends on `ExternalPackageFunction` (this also makes sense)
3. That one in turn depends on the `WORKSPACE` file, i.e. on `WorkspaceFileValue` (this makes sense, too)
4. `WorkspaceFileValue` depends on a Starlark file (i.e. a `BzlLoadValue`) in a repository defined in the `WORKSPACE` file itself if it loads a symbol from it (this makes sense; loading makes the dependency edge necessary)
5. Loading the Starlark file depends on a `PackageLookupValue` in that repository.
6. The `PackageLookupValue` depends on `IgnoredPackagePrefixesValue` (this makes sense; it needs to so that it knows which packages exist)
7. The `IgnoredPackagePrefixesValue` depends on the `REPO.bzl` of that repository (makes sense, this is the new edge I am adding)
8. The `REPO.bzl`  file depends on the repository mapping for the main repository (apparently, to support `Label.debugPrint()`?)

Thus, dependency cycle.

More simply: The main repository mapping depends on the `WORKSPACE` file, which in turn can depend on a Starlark file in an external repository, which then can depend on its `REPO.bzl` file, which then depends on the main repository mapping.

@meteorcloudy do you have any ideas how to fix this?

**Comment by fmeum** [comment]
You can cut the last edge without any loss in functionality. `REPO.bazel` can't `load` and you can't use `Label` in it, so it doesn't need access to the main repo mapping.

**Comment by lberki** [comment]
@fmeum  You are technically correct, but `REPO.bazel` does deal in Labels as parameters of `repo()` (e.g. `default_compatible_with=` and the like). So yes, that dependency edge could in theory be cut today, but it's probably not wise.

**Comment by fmeum** [comment]
@lberki But doesn't that only require the repo mapping of the repo containing the `REPO.bazel` file? The fixed dependency on the main repo mapping could then be cut. In the cycle you mention, it's not the main repo's `REPO.bazel` file that causes the cycle.

**Comment by lberki** [comment]
I don't know. I assumed that the reason why the main repo mapping is passed in is so that the labels reported on the debug output are consistent, no matter which repository they are in. @meteorcloudy is that correct?

It looks like we do pass in `null` in some cases (notably, when `MODULE.bazel` is evaluated). However, that doesn't solve the whole problem because there is still [this](https://github.com/bazelbuild/bazel/blob/c3677ba0fbbdb689b65c5c09980463ba7d920052/src/main/java/com/google/devtools/build/lib/skyframe/RepoFileFunction.java#L151) line of code which also requires the main repo mapping. It's also about user-friendly output and it looks like there is some code that handles `null` there, too, but I wouldn't replace that with null without understanding why the main repo mapping is needed there, which I currently don't.

Let me create a pull request so that we can better discuss the change...

**Comment by lberki** [comment]
https://github.com/bazelbuild/bazel/pull/24022 it is.

**Comment by lberki** [comment]
(paging @Wyverald )

**Comment by lberki** [comment]
Looks promising! I didn't have time to make a proper pull request, but this change implementing the "split `RepoFileFunction` into two parts, one not requiring a repository mapping" approach:

https://bazel-review.googlesource.com/c/bazel/+/261670

seems to be looking good, although the tests didn't finish by the end of my workday:

https://buildkite.com/bazel/google-bazel-presubmit/builds/85367

**Comment by lberki** [comment]
https://github.com/bazelbuild/bazel/pull/24032 implements this feature, makes all test cases pass and is principled enough to be submittable. Let the review begin!

**Comment by lberki** [comment]
This is now fixed at HEAD: you can use the `ignore_directories()` directive in `REPO.bazel` to achieve the same effect as `.bazelignore`, except supporting glob-style wildcards.

@meteorcloudy do you think I should backport this feature to Bazel 8.0?

**Comment by lberki** [comment]
Ack. @Wyverald opined that you'd think otherwise, but I assume it was not that he had concerns, it's just that he thought you had. How urgent is the backporting?

**Comment by meteorcloudy** [comment]
> How urgent is the backporting?

We still have about 2 weeks before the final release, but the sooner the better ;)

**Comment by lberki** [comment]
Already done, it was *much* easier than I expected.

**Comment by navignaw** [comment]
Is there any documentation for this change? I was able to piece together the syntax from the unit tests in the PR, but would be great to surface this in docs somewhere for other users!

**Comment by Wyverald** [comment]
Thanks for the nudge -- I'll be looking at adding docs tomorrow!

**Comment by Wyverald** [comment]
docs are live: https://bazel.build/rules/lib/globals/repo#ignore_directories

**Comment by dgoldstein0** [comment]
thanks for implementing this, very much looking forward to using it once my team upgrades to bazel 8!
