### ISSUE TITLE
bazel coverage support for Scala

### ISSUE THREAD

**Issue by basavaraj29** [bazelbuild/bazel#7109]
### Description of the problem / feature request:

Code Coverage support for Scala.

### Feature requests: what underlying problem are you trying to solve with this feature?

We need to track code coverage statistics for scala. We've seen that `bazel coverage` works for Java, but we are not able to find any pointers for tracking scala code coverage using bazel.

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 0.18.0

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/rules_scala/issues/184

**Comment by gergelyfabian** [comment]
I think this feature is already supported by bazel.

Let me summarize the state (as I see it) for December 2019 (Bazel 1.2.0 and rules_scala 26cf9b74fc46f1e9a970c97837447549ed7257b6).

Code coverage is supported by Jacoco for JVM languages in Bazel. Jacoco uses the lcov format for code coverage output.

To run code coverage with Jacoco for Scala code you can run (you need the extra toolchain as the scala support wasn't enabled by default - please see the comments in https://github.com/bazelbuild/rules_scala/pull/692):

bazel coverage //... --extra_toolchains="@io_bazel_rules_scala//test/coverage:enable_code_coverage_aspect" //...

It will produce several .dat files for your modules.
You should install lcov package to have access to genhtml (e.g. on Ubuntu: sudo apt install lcov), that can be used to convert the .dat files to html for a more readable report.

Then you've got two issues to solve:

1. bazel does not summarize the coverage statistics for you (for Scala)
2. when you try running genhtml for the .dat files it won't have access to the source files

Both can be solved by using an approach taken e.g. by Gerrit project.
See https://github.com/bazelbuild/bazel/issues/2528 for more information, this also seems to be an issue for Java source code. A possible solution is running a script that moves all source files to a new folder and runs genhtml from that place so that genhtml can have access to them. You can check https://gerrit-review.googlesource.com/c/gerrit/+/106471/6/tools/coverage.sh for inspiration. Current version of this script is also in Gerrit source code: https://gerrit.googlesource.com/gerrit/+/master/tools/coverage.sh.

Using a modified version of this script solved also the html report problem for me (e.g. add copying also Scala source files, not just Java).

For sure some documentation on Scala code coverage would be nice to have, but with some digging it seems to be working.

**Comment by basavaraj29** [comment]
Yes, support for coverage was first introduced in `0.23.0` I suppose. We've got it to work with 0.29.0. Closing this issue, thank you.
