### ISSUE TITLE
Lack of --[no]allow_undefined_configs option cuts into usability of --config options

### ISSUE THREAD

**Issue by andyscott** [bazelbuild/bazel#7116]
### Description of the problem / feature request:

Bazel 0.16.0 onwards has removed the ability to use "undefined" config options. This is extremely problematic for flagging config options for certain bazel commands (such as build/test) and not others (such as query), as I've been applying config options broadly for all bazel commands depending on the host environment.

First, consider the following correctly formed `.bazelrc`:

```
# .bazelrc
common:ci --announce_rc
test:ci --test_output=all
```

Bazel commands will behave as follows:

`bazel build --config=ci ...` ✓ expands to `--announce_rc`
`bazel test --config=ci ...` ✓ expands to `--announce_rc --test_output=all`
`bazel query --config=ci ...` ✓ expands to `--announce_rc`

However, consider what happens if we remove the `common` options:
```
# .bazelrc
test:ci --test_output=all
```

`bazel build --config=ci ...` ✗ fails due to unused config `ci`
`bazel test --config=ci ...` ✓ expands to `--test_output=all`
`bazel query --config=ci ...`✗ fails due to unused config `ci`

For the time being, I've been using a workaround of routing all config options to a noop setting:

```
# route potentially unrouted configs to a terminating noop config
# it's a noop because we use the default value
common:ci --config=noop
common:other_config --config=noop

# pick something trivial as a "noop"
common:noop --logging=3
```

This works fine, for the time being, with the caveat that Bazel emits warnings for all duplicate expansions of `noop`.

In terms of impact, this affects some open source work as well as Bazel upgrades at Stripe.

### Feature requests: what underlying problem are you trying to solve with this feature?

Reenable unused config options with three modes: on, warn, and error.

```
--allow_undefined_configs=<on, warn, error; default to error>
```

### What operating system are you running Bazel on?

OSX, Linux (in CI)

### What's the output of `bazel info release`?

Various versions after 0.16.0.

**Comment by andyscott** [comment]
Minor update:

I believe, instead of:
```
common:noop --logging=3
```
you can just leave the right hand side empty:
```
common:noop
```

But it's still a hack/trick/workaround 😄.

**Comment by gregestren** [comment]
Point taken. Can you describe the impact more and why the noop approach you're applying now is insufficient?  Why is it important to be able to set flags to commands that don't support them?

**Comment by katre** [comment]
@juliexxia is this something you can investigate?

**Comment by andyscott** [comment]
The empty noop approach works as an okay solution, but it seems like more of an accidental combination of seemingly orthogonal features/behaviors.

I'd be great to formalize a solution, either through a new flag or documentation the interaction for empty noop options.

**Comment by juliexxia** [comment]
Hi @andyscott is this still bothering you? I'm also curious, why are you needing to set the same configs across all bazel commands?

Closing since this is on the older side, we realistically don't have time to prioritize and there's a viable workaround. @andyscott if workaround is no longer working for you feel free to re open for more discussion.

**Comment by bcsgh** [comment]
I'm running into this same issue. In my case, what's happening is that my CI needs to set some extra flags in some environments but not others. What I'm looking for is is a way to populate the `.bazelrc` file in my workspace so that `bazel test --config=ci ...` is (by default) a no-op, but so that it picks up things like `build:config --disk_cache=/some/local/path` lines, if they exist, in my `~/.bazelrc`

- The simplest way to make this would would be to explicitly (re?)allow a `.bazelrc` lines with no flags. (That is [andyscott's suggestion from above](https://github.com/bazelbuild/bazel/issues/7116#issuecomment-454118050).) This has the downside of looking odd.
- The second simplest solution would be to add  a `--noop` flags that exists only to be used where a flag is required but not needed. This still looks odd, but it's at least self explanatory and gives you something to look up for more details.
- A third option would be an `--allowed_undefined_configs=ci,noop,etc` flag. The is likely the best option from a don't-surprise-the-user perspective, but is likely the most complicated to implement.

**Comment by bcsgh** [comment]
FWIW: while `common:noop` doesn't seem to work any more (getting `ERROR: Config value 'noop' is not defined in any .rc file`), it seems you can use `common:noop --` ... It still seems like a hack unless it gets explicit support, but it seem to [work on my machine](https://blog.codinghorror.com/the-works-on-my-machine-certification-program/).
