### ISSUE TITLE
[aquery] fails with external repository

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#7229]
Check out rules_nodejs at head and run with Bazel 0.21.0

```
$ bazel aquery //internal/...

Internal error thrown during build. Printing stack trace: java.lang.IllegalStateException: java.lang.IllegalStateException: Root /home/alexeagle/Projects/rules_nodejs in repository @ could not be found in the graph.
        at com.google.devtools.build.lib.cmdline.TargetPattern.evalAdaptedForAsync(TargetPattern.java:187)
        at com.google.devtools.build.lib.query2.ActionGraphQueryEnvironment.getTargetsMatchingPattern(ActionGraphQueryEnvironment.java:269)
        at com.google.devtools.build.lib.query2.engine.TargetLiteral.eval(TargetLiteral.java:71)
        at com.google.devtools.build.lib.query2.engine.AbstractQueryEnvironment.eval(AbstractQueryEnvironment.java:129)
        at com.google.devtools.build.lib.query2.AbstractBlazeQueryEnvironment.evalTopLevelInternal(AbstractBlazeQueryEnvironment.java:105)
```

**Comment by dslomov** [comment]
Passing to performance team since they are responsible for aquery.

**Comment by meisterT** [comment]
Some insights:
It also fails with Bazel 0.22.
Both `bazel query` and `bazel build --nobuild` work, but `bazel aquery` and `bazel cquery` do not.

cc @juliexxia 

@joeleba can you please have a look?

**Comment by atavakoli** [comment]
Has anyone found a workaround to this?

**Comment by janakdr** [comment]
@juliexxia and I had a good debugging session just now. The bug is connected to the .bazelignore file in this repository. The code in question is [RecursivePkgValueRootPackageExtractor](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/RecursivePkgValueRootPackageExtractor.java;l=51), and the problem is `blacklistedSubdirectories`. This comes from [ConfiguredTargetQueryEnvironment](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/query2/ConfiguredTargetQueryEnvironment.java;l=232), which is ignoring (ha) the lines in the .bazelignore file. That needs to be changed.

Julie and I discussed a number of options, but I think we just need to pass in the right set of directories there. Note that we should also be filtering that blacklist inside RecursivePkgValueRootPackageExtractor, the same way as is done in [EnvironmentBackedRecursivePackageProvider](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/skyframe/EnvironmentBackedRecursivePackageProvider.java;bpt=0;l=165). Maybe there or in 
GraphBackedRecursivePackageProvider.
