### ISSUE TITLE
Bazel query fails somewhere in protobuf, but error indicates my code is at fault

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#7238]
Tried to update rules_nodejs to stardoc. Trying to find out why my target has a transitive dep on compiling protoc (which is failing for me).

Error is 
```
/Projects/rules_nodejs$ yarn bazel query 'somepath("//docs", "@com_google_protobuf//:protoc_lib")'
yarn run v1.13.0
$ /home/alexeagle/Projects/rules_nodejs/node_modules/.bin/bazel query 'somepath("//docs", "@com_google_protobuf//:protoc_lib")'
INFO: Invocation ID: 0e8d9205-e532-4a22-9aed-c16f8c8819b5
ERROR: /home/alexeagle/.cache/bazel/_bazel_alexeagle/78c7479a1baf683797e1e6cd7cfefe83/external/com_google_protobuf/BUILD:668:1: no such target '//external:python_headers': target 'python_headers' not declared in package 'external' defined by /home/alexeagle/Projects/rules_nodejs/WORKSPACE and referenced by '@com_google_protobuf//:python/google/protobuf/pyext/_message.so'
ERROR: Evaluation of query "somepath(//docs, @com_google_protobuf//:protoc_lib)" failed: errors were encountered while computing transitive closure
```

The error uses a syntax "package external" which doesn't make sense.

**Comment by aehlig** [comment]
> Error is
> 
> ```
> /Projects/rules_nodejs$ yarn bazel query 'somepath("//docs", "@com_google_protobuf//:protoc_lib")'
> yarn run v1.13.0
> $ /home/alexeagle/Projects/rules_nodejs/node_modules/.bin/bazel query 'somepath("//docs", "@com_google_protobuf//:protoc_lib")'
> INFO: Invocation ID: 0e8d9205-e532-4a22-9aed-c16f8c8819b5
> ERROR: /home/alexeagle/.cache/bazel/_bazel_alexeagle/78c7479a1baf683797e1e6cd7cfefe83/external/com_google_protobuf/BUILD:668:1: no such target '//external:python_headers': target 'python_headers' not declared in package 'external' defined by /home/alexeagle/Projects/rules_nodejs/WORKSPACE and referenced by '@com_google_protobuf//:python/google/protobuf/pyext/_message.so'
> ERROR: Evaluation of query "somepath(//docs, @com_google_protobuf//:protoc_lib)" failed: errors were encountered while computing transitive closure
> ```

If I read this error as it is written, it states that in line 668 of the `BUILD` file of the protobuf repository, there is a declaration of a target `@com_google_protobuf//:python/google/protobuf/pyext/_message.so` which has a dependency on `//external:python_headers` which does not exist. Now, if I look at [the specified line in the `BUILD` file](https://github.com/protocolbuffers/protobuf/blob/4dd45935d7a2b91da912113a4c03a569654b5cb7/BUILD#L668) I find the definition of that target, and in that definition... literally the string `"//external:python_headers"`. So I wonder, which error message you would prefer, if you don't like literally showing the undefined label together with the location where it occurs.

There is the entirely different problem, on how `select` statements should be interpreted in query; but this is not related to the wording of the error message.

> The error uses a syntax "package external" which doesn't make sense.

Well, it is the package of the label `//external:python_headers` that was mentioned in the target where the dependencies could not be met. Admittedly, the "external" package is a somewhat strange concept, that [our documentation](https://docs.bazel.build/versions/master/be/workspace.html#bind) describes as follows.

> The `//external` package is not a "normal" package: there is no external/ directory, so it can be thought of as a "virtual package" that contains all bound targets.

Maybe we could add an additional link to that part of the documentation, whenever we report an error in the package `//external`. Would that help?

Since your command was a `query` it is interesting to note that the documentation has a whole section on [the external packge in `query`](https://docs.bazel.build/versions/master/query.html#external-repos).

**Comment by dslomov** [comment]
I agree there is not much we can do here. Few things to note:
1. To properly process selects, use [bazel cquery](https://docs.bazel.build/versions/master/cquery.html)
2. The whole `//external` package saga is really an abomination; I think we should get protobuf to update that code
