### ISSUE TITLE
struct(...).to_proto() throws an error on finding a None

### ISSUE THREAD

**Issue by cgruber** [bazelbuild/bazel#7263]
### Description of the problem / feature request:

calling to_proto() on a struct containing a None value results in an error. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Omit the field with None from the printing, or find a proto-text appropriate way to represent the None

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

struct(name = None).to_proto()

### What operating system are you running Bazel on?

Mac OS X

### What's the output of `bazel info release`?

INFO: Invocation ID: 4718aec6-af43-4ab9-983c-30879e75300f
release 0.21.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

Bazel documentation does not list NoneType as a valid member of the list of types under "it should work if".  The failure of representing NoneType seems intentional.  However, protos can represent none (even if only by omission in the wire format).  NoneType should be a valid thing to create a string representation of.

**Comment by wintermelons** [comment]
Currently, `to_proto` will omit the value of a field if it is an empty list:
```
print(struct(my_field = []).to_proto())  # will print nothing!
```

This is because repeated fields in protobufs will only list each element and not the parent, like:
```
print(struct(my_field = [1, 2, 3]))
# prints to
my_field: 1
my_field: 2
my_field: 3
```

Currently we have a lot of code that specify `[]` as the default value since it would omit the field in a proto (a optional message field), but setting them to NoneType would be much more readable and intuitive. Would this be something the Starlark team can support?

**Comment by brandjon** [comment]
I'm not sure that just because a field is None it should be omitted from the output, as opposed to failing fast with an error.

For the existing supported conversions, there's a straightforward correspondence between the Starlark type and the proto type. There is no such conversion for None, so omitting it is akin to silently skipping over malformed data. In contrast, json has a `null` value, and the json encoder convers None to null.

If the "schema" of a struct field can be thought of as a list, then it makes sense that its empty value must be `[]`, not `None`.

That said, if we supported recursion in .bzl files (as we do optionally in some Starlark implementations / with certain flags), it'd be possible to write your own conversion function to do what you're looking for.
