### ISSUE TITLE
Misleading error for target collisions

### ISSUE THREAD

**Issue by shmish111** [bazelbuild/bazel#7346]
### Description of the problem / feature request:

Overlapping targets in the same external repository cause a very confusing cyclic dependency error rather than a naming conflict error.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
purs_bindist_buildfile = '''
package(default_visibility = ["//visibility:public"])
filegroup(
   name = "purs",
   srcs = glob(["*"]),
)'''

http_archive(
      name = "purs_bindist_darwin",
      urls = "https://github.com/purescript/purescript/releases/download/v0.11.7/macos.tar.gz",
      sha256 = d8caa11148f8a9a2ac89b0b0c232ed8038913576e46bfc7463540c09b3fe88ce,
      strip_prefix = "purescript",
      build_file_content = purs_bindist_buildfile,
)
```

This will cause the error:
```
ERROR: ... in filegroup rule @purs_bindist_darwin//:purs: cycle in dependency graph:
    //test:purs_darwin_bindist
.-> @purs_bindist_darwin//:purs [self-edge]
`--
This cycle occurred because of a configuration option
```

Notice that the source of the ascii arrow is empty

```
.-> dest
`-- source
```

and that `@purs_bindist_darwin//:purs` is a slf-edge.

The issue here is that the archive we are downloading contains a file called `purs` in the root. Bazel creates a target for this called `purs` as its a filegroup but we called the filegroup `purs` so they conflict. This is an easy mistake to make because you may not know all the files that are in that archive.

If this was reported as a naming conflict in `@purs_bindist_darwin//:purs` then we would have a better clue as to what has happened but instead it comes up as a dependency cycle. It may be a (zero depth) cycle due to the way the bazel logic works but this is not really the issue. Perhaps bazel could detect a zero depth cycle and report it in another way? Alternatively you could explicitly check for naming conflicts and report them.

### What operating system are you running Bazel on?

OSX and Linux (NixOS)

### What's the output of `bazel info release`?

```
INFO: Invocation ID: 4c07675d-6e3e-4ce5-99f5-0ee558275e91
release 0.21.0- (@non-git)
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

`nix-env -iA unstable.bazel`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> N/A

###  Have you found anything relevant by searching the web?

Some issues guided us to the issue but it was a hard slog and there was nothing explicit.

**Comment by dslomov** [comment]
@aehlig wdyt - how feasible is it?

**Comment by aehlig** [comment]
First of all, this has nothing to do with external repositories. The underlying problem is the expansion of `glob`s. Here is a minimal reproduction example (not using external repositories at all).

```
$ cat BUILD 
package(default_visibility = ["//visibility:public"])
filegroup(
   name = "purs",
   srcs = glob(["*"]),
)
$ ls -al *
-rw-r--r-- 1 aehlig primarygroup 108 Apr 24 15:15 BUILD
-rw-r--r-- 1 aehlig primarygroup   0 Apr 24 15:15 data.txt
-rw-r--r-- 1 aehlig primarygroup   0 Apr 24 15:15 WORKSPACE
$ bazel build :purs
(15:17:40) INFO: Invocation ID: 2422a6c2-cce9-4e2f-96b7-3d7ae8510ca6
(15:17:40) INFO: Current date is 2019-04-24
(15:17:40) INFO: Analysed target //:purs (1 packages loaded, 4 targets configured).
(15:17:40) INFO: Found 1 target...
Target //:purs up-to-date (nothing to build)
(15:17:40) INFO: Elapsed time: 0.115s, Critical Path: 0.00s
(15:17:40) INFO: 0 processes.
(15:17:40) INFO: Build completed successfully, 1 total action
$ touch purs
$ bazel build :purs
(15:17:49) INFO: Invocation ID: 7ff9a83f-b847-482f-aa6a-42a7180f3dba
(15:17:49) INFO: Current date is 2019-04-24
(15:17:49) ERROR: /tmp/work23-a/min/BUILD:2:1: in filegroup rule //:purs: cycle in dependency graph:
.-> //:purs [self-edge]
`--
This cycle occurred because of a configuration option
(15:17:49) ERROR: Analysis of target '//:purs' failed; build aborted
(15:17:49) INFO: Elapsed time: 0.102s
(15:17:49) INFO: 0 processes.
(15:17:49) FAILED: Build did NOT complete successfully (1 packages loaded, 3 targets configured)
$
```

The problem is that, when the target `//:purs` expands to the file `//:purs` these labels are no longer distinguishable, hence the loop. No external dependency needed.

**Comment by aehlig** [comment]
It should be noted, that this behavior is in line with `bazel` silently giving targets in `BUILD` files precedence over files. A more fun example is the one below (where no errors occur at all); note the different file names in the last `SUBCOMMAND`. It should be noted that not checking for files if a target is already defined in the `BUILD` file saves a lot of `stat(2)`/`readdir(3)` in the typical case; so changing that is probably infeasible for performance reasons. Maybe an additional check is feasible after `glob` expansion, but I'm not sure if it even is desirable that a `glob` expansion triggers additional checks that wouldn't be there if instead of the `glob` its expansion would be written in the `BUILD` file. So I leave it to the core team to decide if this is working as intended.

```
$ ls -al
total 300
drwxr-xr-x  2 aehlig primarygroup   4096 Apr 24 15:57 .
drwxrwxrwt 40 root   root         294912 Apr 24 15:57 ..
-rw-r--r--  1 aehlig primarygroup    238 Apr 24 15:54 BUILD
-rw-r--r--  1 aehlig primarygroup      0 Apr 24 15:57 data0.txt
-rw-r--r--  1 aehlig primarygroup      0 Apr 24 15:39 WORKSPACE
$ cat BUILD

[ genrule(
    name = "data%d" % (i,),
    outs = ["data%d.txt" % (i,)],
    cmd = "echo %d > $@" % (i,),
  ) for i in range(20) ]

genrule(
  name = "it",
  srcs = glob(["data*.txt"]),
  outs = ["it.txt"],
  cmd = "cat $(SRCS) > $@",
)
$ bazel build //:it
(15:57:40) INFO: Invocation ID: 80b8529f-083b-4fe6-acd7-36c849ff9529
(15:57:40) INFO: Current date is 2019-04-24
(15:57:40) INFO: Analysed target //:it (1 packages loaded, 3 targets configured).
(15:57:40) INFO: Found 1 target...
Target //:it up-to-date:
  /usr/local/google/home/aehlig/.cache/bazel/_bazel_aehlig/f78fd10d61278efa55b1ce5eb9a0410c/execroot/__main__/bazel-out/k8-fastbuild/genfiles/it.txt
(15:57:40) INFO: Elapsed time: 0.144s, Critical Path: 0.01s
(15:57:40) INFO: 1 process: 1 remote cache hit.
(15:57:40) INFO: Build completed successfully, 2 total actions
$ cat /usr/local/google/home/aehlig/.cache/bazel/_bazel_aehlig/f78fd10d61278efa55b1ce5eb9a0410c/execroot/__main__/bazel-out/k8-fastbuild/genfiles/it.txt
0
$ touch data5.txt data7.txt data9.txt
$ !bazel
bazel build //:it
(15:58:08) INFO: Invocation ID: 4d2438d5-fec5-453f-bc39-9a5746f77268
(15:58:08) INFO: Current date is 2019-04-24
(15:58:08) INFO: Analysed target //:it (1 packages loaded, 9 targets configured).
(15:58:08) INFO: Found 1 target...
Target //:it up-to-date:
  /usr/local/google/home/aehlig/.cache/bazel/_bazel_aehlig/f78fd10d61278efa55b1ce5eb9a0410c/execroot/__main__/bazel-out/k8-fastbuild/genfiles/it.txt
(15:58:09) INFO: Elapsed time: 0.334s, Critical Path: 0.19s
(15:58:09) INFO: 2 processes: 2 linux-sandbox.
(15:58:09) INFO: Build completed successfully, 3 total actions
$ !cat
cat /usr/local/google/home/aehlig/.cache/bazel/_bazel_aehlig/f78fd10d61278efa55b1ce5eb9a0410c/execroot/__main__/bazel-out/k8-fastbuild/genfiles/it.txt
0
5
7
9
$ echo manual > data-manual.txt
$ !bazel -s
bazel build //:it -s
(15:58:30) INFO: Invocation ID: 7bb34c82-b44e-49d5-9549-a37676e02034
(15:58:31) INFO: Current date is 2019-04-24
(15:58:31) INFO: Analysed target //:it (1 packages loaded, 10 targets configured).
(15:58:31) INFO: Found 1 target...
(15:58:31) SUBCOMMAND: # //:it [action 'Executing genrule //:it']
(cd /usr/local/google/home/aehlig/.cache/bazel/_bazel_aehlig/f78fd10d61278efa55b1ce5eb9a0410c/execroot/__main__ && \
  exec env - \
    PATH=/usr/local/google/home/aehlig/bin:/usr/local/google/home/aehlig/software/install/bin:/usr/local/google/home/aehlig/Bazel/bin:/usr/local/google/home/aehlig/bin:/usr/local/google/home/aehlig/software/install/bin:/usr/local/google/home/aehlig/Bazel/bin:/usr/lib/google-golang/bin:/usr/local/buildtools/java/jdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; cat data-manual.txt bazel-out/k8-fastbuild/genfiles/data0.txt bazel-out/k8-fastbuild/genfiles/data5.txt bazel-out/k8-fastbuild/genfiles/data7.txt bazel-out/k8-fastbuild/genfiles/data9.txt > bazel-out/k8-fastbuild/genfiles/it.txt')
Target //:it up-to-date:
  /usr/local/google/home/aehlig/.cache/bazel/_bazel_aehlig/f78fd10d61278efa55b1ce5eb9a0410c/execroot/__main__/bazel-out/k8-fastbuild/genfiles/it.txt
(15:58:31) INFO: Elapsed time: 0.237s, Critical Path: 0.09s
(15:58:31) INFO: 1 process: 1 linux-sandbox.
(15:58:31) INFO: Build completed successfully, 2 total actions
$ !cat
cat /usr/local/google/home/aehlig/.cache/bazel/_bazel_aehlig/f78fd10d61278efa55b1ce5eb9a0410c/execroot/__main__/bazel-out/k8-fastbuild/genfiles/it.txt
manual
0
5
7
9
$
```

**Comment by janakdr** [comment]
I think that @aehlig 's investigation is very illuminating. My personal opinion is that we should probably disambiguate glob expressions from typical strings. It seems undesirable that the state of the source tree could affect whether a generated file is consumed in this way. However, I don't see a trivial way to thread this data through in our code, it would probably break somebody to change this behavior, and it could make things even more bizarre: you could end up with a rule that had a glob expression *and* an explicit target dep, where the glob referred to the source file and the target to the generated file. Presumably what we'd want to do is fail the build if the glob matched a source file with the same name as a target. Also weird, but maybe better? 

We do apparently [mung the raw strings](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/packages/StarlarkNativeModule.java#L122-L126) to avoid misinterpreting them as external repositories. That seems pretty hackish: I can imagine there are other ways to trip up whatever parses them, so using a custom object seems reasonable. We would then need to, presumably based on the value of an "incompatible" flag, track when a target came from such a custom object and validate that no generated targets have the same names. Don't think this should be higher than P3.

cc @alandonovan @haxorz

**Comment by alandonovan** [comment]
I agree with Klaus's analysis, but there is no way we can change glob. It is defined to return a list of strings, and it would be a profoundly surprising and incompatible change for it to return anything else. Also, glob is crucial to performance (and still needs further optimization), so we couldn't afford to change its result type so something that (say) wraps a string. In short, glob returns strings, and attr.label_list accepts strings, and there can be no out-of-band communication between them. I think fundamentally this is working as intended.

That said, we could improve the error. For example, we could observe that the cyclic path occurred in a package that uses globs, and use some heuristic to decide that the strings returned by glob are similar to the names of targets in the package, and suggest to the user that the glob was ultimately used as a set of labels (as is usual), but the heuristics may be fragile. That seems ok if they're only triggered in a fairly uncommon error situation. The implementation could be tricky.

(As Janak points out, a glob may return a directory entry such as `@foo`, which, if used as a label, would be misinterpreted as repository, so glob contains a hack to replace them with `./@foo`. In hindsight, we should have used the syntax //@repo/dir/name for labels to avoid this problem, and keep only `/` and `:` as the only two reserved characters. Colons are exceptionally rare in file names because they have had special meaning on Windows, classic Mac, and POSIX for decades.)

**Comment by janakdr** [comment]
My concern is less the error and more the situation where there is no
error: the user expects to consume a source file, and consumes a generated
file instead with the same package-relative name. That seems not WAI, and
hard to catch after the fact.

**Comment by alandonovan** [comment]
Glob can be used in two ways. Originally it could only be used as a shorthand for a known list of files that could in principle be typed out, even though it may be tedious and redundant to do so. More recently it has evolved another use, to match an open-ended set of files that is not statically knowable. This occurs in Bazel when a glob is applied to the files fetched by a repo rule, but it also occurs in Blaze (which has no concept of repo) when a macro in a .bzl file executes a glob on behalf of an unknown client package.

This demands good hygiene: the macro should make clear which portions of the file/target namespace it will inspect or 0define. A similar problem exists, without glob, when a macro makes decisions based on the set of rules that already exist.
And a reverse variant exists when two macros use the same names for their auxiliary rules due to insufficient disambiguation. I don't think glob is the root of the problem. Such problems are at least diagnosable using blaze query.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
