### ISSUE TITLE
#include "external/..." have inconsistent compile behavior as current repo VS external dependency

### ISSUE THREAD

**Issue by c-nuro** [bazelbuild/bazel#7360]
### Description of the problem / feature request:
`#include "external/..."` have inconsistent compile behavior when this lib is compiled as current top-workspace VS external dependency

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
mkdir foo
touch foo/WORKSPACE
cat <<EOF > foo/BUILD
package(default_visibility=["//visibility:public"])

cc_library(
    name = "header",
    hdrs = ["header.h"],
    includes = ["."],
)
EOF

touch foo/header.h

mkdir bar
cat <<EOF > bar/WORKSPACE
local_repository(
    name="foo",
    path="../foo"
)
EOF

cat <<EOF > bar/BUILD
package(default_visibility=["//visibility:public"])

cc_library(
    name = "lib",
    deps = ["@foo//:header"],
    srcs = ["bar.cc"],
)
EOF

cat <<EOF > bar/bar.cc
#include "external/foo/header.h"
EOF

mkdir test
cat <<EOF > test/WORKSPACE

local_repository(
    name = "foo",
    path = "../foo",
)

local_repository(
    name = "bar",
    path = "../bar",
)
EOF

cat <<EOF > test/BUILD

package(default_visibility=["//visibility:public"])

cc_library(
    name = "test",
    deps = ["@bar//:lib"],
)

EOF

# This can compile
(cd bar && bazel build :lib)

# This won't compile
(cd test && bazel build @bar//:lib)
(cd test && bazel build :test)

```

### What operating system are you running Bazel on?

ubunut 16.04

### What's the output of `bazel info release`?

release 0.19.2

###  Have you found anything relevant by searching the web?
No

**Comment by dslomov** [comment]
I believe you should never use `external` in include paths.

**Comment by c-nuro** [comment]
I agree we should never use `external` in include path, but there are some third-party library use that, and it's hard for us to enforce it, if bazel can compile within their codebase.

**Comment by hlopko** [comment]
So i'm looking into this, and the example is quite exotic. Let me see if I get it right:

1) If you replace "external/foo/header.h" with "header.h" in bar.cc, everything builds fine. This is not what you want, because you don't want to change bar.cc.
2) Therefore I assume that external/foo/header.h just happens to be the the path that "has to work" for bar.cc to compile. It has nothing to do with Bazel, it just has to be like that.
3) Then you actually want to declare that the cc_library exporting header.h wants to make that header available under "external/foo/header.h" and you can do that using [include_prefix](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.include_prefix).

But I'm skeptical that this is really your problem. Can you maybe try to explain it again, from the higher level?
