### ISSUE TITLE
Add common env attribute for *_binary and *_test

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#7364]
### Description of the problem / feature request:

In the same way as we can define in code that bazel passes on cli args on `bazel run` and `bazel test` it would be great to be able to define env vars in the same way. 

### Feature requests: what underlying problem are you trying to solve with this feature?

Some applications/libraries/tests/test frameworks prefer environment variables over cli args and being able to define that on a per target level in code would save the need to use external tools or `test_env` in a lot of cases. We also have cases where we just need env variables in ci for certain tests (that use docker) and this could also accommodate for that. Also with make var substitution or stamping we could even pass in non static env vars this way. 

This could also help solving part of the issue described in #6111

Also I noticed on our team, developers where quite surprised when they saw one can set `args` in code but not `env`. So it seems some developers even have some expectations around this behaviour. 

One could of course work around this by wrapping the binary into a `sh_binary` or similar and that is probably a reasonable solution, but the same would be true for `args` so parity on this would be ideal. 

###  Have you found anything relevant by searching the web?

Not really, maybe #955 is somewhat related.

**Comment by Globegitter** [comment]
Also one interesting case we ran into where we did not just need a hardcoded env var, but one with an absolut path to the location of some generated files, so now we are wrapping that target and setting `$(pwd)/some/path`, so one interesting question for such feature would be if the env vars would get quoted, i.e. take the value literal or of this would just pass it through as is and therefore apply standard shell mechanisms and `pwd` would expand to a path.

**Comment by lberki** [comment]
I don't have any fundamental counter-arguments, except that it's Yet Another Feature... I would expect that since you control both the test rule and the code it runs, it's just as easy to just do `export ENV=value` at the very beginning of our test (with `value` potentially coming from the command line)

@aehlig , mind giving a second opinion?

**Comment by lberki** [comment]
(pull request is https://github.com/bazelbuild/bazel/issues/7364)

/cc @lberki

**Comment by blico** [comment]
A little more context for why this feature would be valuable for us: 
There is a common environment variable that tests and binaries within our repo depend on during execution time. The environment variable's value needs to be a relative path to another directory within the repo. When auto-generating BUILD files we can determine the location of this directory, so if the `envs` attribute existed we could also set the proper env value in the generated rules. This way developers would never have to worry about adding an `export ENV=value` into their tests/binaries.

**Comment by lberki** [comment]
Erm, sorry about the delay.

If we added this feature, we would have to worry about maintaining it forever... I think if there were more people who wanted it, I would be more amenable to it, but as it is, I don't want to add a single-use feature to Bazel.

I'll take a look at the code review, but I'm not very enthusiastic and would much prefer not to merge it.

**Comment by blico** [comment]
@lberki is there anything that would make you more enthusiastic about this change?
This functionality would be very valuable for our repository. 
I originally tried to add the feature into `rules_go` https://github.com/bazelbuild/rules_go/pull/1973, but it was recommend that the feature belongs here.

**Comment by lberki** [comment]
More use cases and more people to whom this would be useful.

**Comment by wesleyw72** [comment]
I have a use case need for this. I have a `cc_binary` which dynamic links against a shared object `Liba.so`. I’d like to test runtime polymorphism of two different implementations of the same shared library , so in a test I would like to specify a different `Liba.so` on the `LD_LIBRARY_PATH`. Having the `env` attribute would help a lot.

**Comment by wesleyw72** [comment]
@lberki is this still something you'd be opposed to merging?

**Comment by ulfjack** [comment]
I would like to have this feature for Google to remove some internal hacks in test execution, and I have a patch to implement it.

**Comment by ulfjack** [comment]
https://bazel.googlesource.com/bazel/+/02d28a26c58d96b0f130d9669774f76a83375086

**Comment by Globegitter** [comment]
@ulfjack I can not find the commit here on github. Is the plan to get this patch merged into open source also?

**Comment by ulfjack** [comment]
It wasn't merged yet - Google doesn't have a separate code base for Bazel. :-)

There are some open questions that I haven't addressed yet. I was considering changing the name of the attribute to ```test_env```. The other main question was whether to signal inheritance inline like I did by using a special value or to use separate attributes. Technically, it would be sufficient to only support inheriting env variables, but not setting them (if you set an env variable to a fixed value, you can also do that *inside* the test, rather than outside, e.g., by wrapping it in a shell script).

**Comment by blico** [comment]
> Technically, it would be sufficient to only support inheriting env variables, but not setting them (if you set an env variable to a fixed value, you can also do that inside the test, rather than outside, e.g., by wrapping it in a shell script).

We find value in being able to set env variables via attribute rather than inside tests. 

For example, one use case we have is the ability to conditionally set env variables for a subset of our repo. Meaning we have a `config_setting` defined with narrow visibility and based off of that we use a `select` statement on the `test_env` attr for certain test rules. 
AFAIK the only other way we could achieve this same functionality would be via a `select` on the `args` attr, and then conditionally setting the env variable in code based off of the passed in args. In my opinion, the first approach is much more elegant and straight-forward.

**Comment by TheKaur** [comment]
@ulfjack Any update on when this will be merged?

**Comment by ulfjack** [comment]
I left Google at the end of January, and I've been exceptionally busy with my new company (www.engflow.com). Not sure when I will have time to look into this again.

**Comment by mcwilson07** [comment]
This would be extremely useful for setting the ASAN environment variables when executing tests.

**Comment by linzhp** [comment]
Running into another case where this is needed. The Go package github.com/mattn/go-oci8 requires `LD_LIBRARY_PATH` to point to Oracle instant client location at its `init` function. Setting it in the Go tests or `TestMain` is too late because `init` is called and failed before that. We can't `export LD_LIBRARY_PATH` before running the test because some other tests may depend on other C libraries and need a different `LD_LIBRARY_PATH`.

@lberki Are the use cases and enthusiasm so far enough? According to @ulfjack, it seems Google would also benefit from this too by reducing some internal hacks.

**Comment by flaub** [comment]
We would also very much like this feature. Many tools use environment variables for configuration rather than just command line args.

**Comment by virusdave** [comment]
Adding support for this request.  We have several use cases where we want to specify that a particular portion of the execution environment (a set of environment variables, specifically) is depended upon explicitly by a small subset of our build graph, but not the rest.  Adding these variables to the build or test environment for the whole graph means caching is busted and targets rebuilt/retested whenever they change, when really it should only be the affected subset.

If you squint at this, it's very analogous to a file dependency.  I don't want my entire repo rebuilt or the cache invalidated when a file FOO (depended upon by a single target BAR) changes, i only want BAR rebuilt.  The same is true for some environment variables.

For real world examples, i can provide a couple.  Most immediate one i ran into is:

Small set of tests which are non-cacheable and have legitimate per-machine dependencies.  You don't want all tests to become uncacheable because a small set of them require cache-key-busting transitive dependencies on environment variables, but you _do_ want them executed when their dependencies change.

However, i've run into more cases as well.  Part of bazel's power comes from allowing the modeling of build steps as cacheable functions from `(environment, sources, tools) => (outputs)`.  It provides great mechanisms for maximizing cache hits by restricting the domain in the case of both `sources` and `tools`, but not really for `environment`, which currently is effectively "the union of the environments required by all tools, toolchains, binaries, and targets", and that's the opposite of what you want for maximizing cache hits.  We need to be able to apply a projection of the outer, union environment into minimal smaller environments as needed for individual tools, tests, or runs.

**Comment by aiuto** [comment]
@gregestren Is this really a configurability issue?

**Comment by wesleyw72** [comment]
It seems there may be community support for implementing and getting the change through review from the discussion on this thread. I think one unknown is still whether Google would accept this patch. Could @lberki or another Google Bazel team provide some guidance on this?

**Comment by linzhp** [comment]
@ulfjack already have a [patch](https://bazel-review.googlesource.com/c/bazel/+/127330) up for review. We just need to raise the awareness of the patch among reviewers.

**Comment by aiuto** [comment]
cc/ @sdtwigg

**Comment by dfreese** [comment]
I've run into a similar situation where this would be extremely helpful.  When testing allocation failures, asan will complain.  This requires setting ASAN_OPTIONS.  Being able to set ASAN_OPTIONS="allocator_may_return_null=1" for a specific test, would be extremely helpful.

The alternative, currently, is to tag the test, filter it from our primary asan config, and create a secondary "asan_alloc_null_allow" config.

**Comment by dws-uber** [comment]
This would make it convenient for our bazel macros to set environment variables such as `OMP_NUM_THREADS` and `MKL_NUM_THREADS` on a per-test basis to reflect the per-test value of the `cpu:N` tag in the `tags` attribute of tests.

**Comment by jbms** [comment]
I'd like to add my support for this feature as well.  I have run into a need for it numerous times.  Of course there are workarounds, like modifying the test code to accept the relevant parameter as a command-line argument, or creating a wrapper with genrule, but environment variables are an extremely common interface for specifying program and test behavior.  It isn't like environment variable are going to go away, and you could likewise eliminate the need for `args` by using a genrule wrapper as well.  Additionally, environment variables are often a lot *more* convenient than command-line arguments, because they automatically pass through any number of layers of test framework without interference.

**Comment by aiuto** [comment]
I would be interested in knowing how far having parameterized tests as per https://github.com/bazelbuild/bazel/issues/11772 would work for people.  I very much want to add that feature as part of an effort to improve our integration tests.

**Comment by konste** [comment]
In many cases devs working on the build are separate from the devs working on the product code and tests and build devs don't have much say in how the tests are organized. Or there are just a ton of legacy tests nobody have time to rewrite. For those reasons it is important for the build system (with the help of build devs) to accommodate for existing test requirements which VERY often include setting the environment variables in a specific way. That's why we need this feature as is and test parameters would not help with it.

**Comment by jbms** [comment]
I'm not clear on how the exactly the parameterized tests proposed in #11772 would work, but regardless I agree with @konste that such a facility would surely be largely orthogonal to the ability to set environment variables.

**Comment by konste** [comment]
Woohoo! Thank you!

**Comment by dws-uber** [comment]
Yay!

**Comment by sulume** [comment]
I'm having trouble and landed here today, and surprised that it's nicely resolved just a week ago. Thank you!
Is this coming in the next minor release, while 4.0 is happening?

**Comment by sitaktif** [comment]
@brandjon @meisterT Is my understanding correct that https://github.com/bazelbuild/bazel/commit/021576d17aebfc63db1854331ee682cd444a8d1c effectively disabled the feature for all starlark rules, and if so, can we re-open this issue?

**Comment by konste** [comment]
Initially, we were very upset that this feature we wanted so much is limited to built-in rules only, but then we discovered [testing.TestEnvironment](https://docs.bazel.build/versions/master/skylark/lib/testing.html#TestEnvironment) and returning this provider from our custom test rules actually works and sets the environment the way we need it. I am not sure if something similar exists for binary rules.

**Comment by jbms** [comment]
@sitaktif Yes, it had to be disabled for starlark rules.  The original change did not properly add `env` and `env_inherit` as attributes for starlark rules, so it wasn't available except if those rules happened to themselves define an `env` or `env_inherit` attribute of the correct type (and not attempt to use it for a different purpose).  However, at least one docker rule was already using the env attribute for a different purpose, which made this problematic.  In any case, injecting this behavior into starlark rules is kind of weird --- it already happens for `args`, but at least that has been around forever so starlark rules aren't using that attribute for a different purpose.  As far as I'm aware there isn't a similar mechanism to TestEnvironment available for binary rules, but adding something like that would indeed seem like the best solution to this.

**Comment by sitaktif** [comment]
@jbms Are we saying that we're thinking of not implementing the feature? I understand it's a little awkward to inject that into starlark but there are strong use cases rationalizing this feature. I think [this comment](https://github.com/bazelbuild/bazel/issues/7364#issuecomment-631645464) particularly nails it. Are we aware of any reasonable way to achieve "only pass these specific (currently-set) env vars to these test targets" without this feature?

@konste I can see how you can work around the absence of `env` attribute with this provider, but do you manage to replicate the behavior of `env_inherit`?

**Comment by jbms** [comment]
@sitaktif I implemented https://github.com/bazelbuild/bazel/commit/eb5cdcb972326321a649d9b4df495ae22aea3f12 based on an initial version by @ulfjack but I am not on the bazel team and cannot speak for them.  I don't think there is any specific opposition to making it work for starlark rules, it is just a matter of someone with the necessary expertise taking the time to implement it.

From my own limited knowledge of bazel internals, I think the cleanest solution would be to support something like TestEnvironment for binary rules.   It would probably also make sense to extend TestEnvironment to support the equivalent of `env_inherit` (that isn't necessary for binary rules since they inherit everything by default anyway).

I think one hacky workaround would be to define a local repo rule that depends on the environment variables you care about, and use that to route the environment variables to your test target via TestEnvironment.  However, that is awfully hacky....

**Comment by konste** [comment]
@sitaktif We strive to not depend on the local environment at all and for that reason we do not use env_inherit. I don't think TestEnvironment can get you that.

**Comment by sitaktif** [comment]
@jbms thanks for the details 🙂

Maybe we can keep the discussion open about what the best approach is (e.g. provider vs. common attribute).

I feel this issue is the best place to do this. Could we consider re-opening it?

**Comment by brandjon** [comment]
(The P3 -> P4 reflects more a change in how we interpreter priority labels rather than a change in our view of this particular issue's priority. IIUC, P3 or higher priority now means we either have it on the roadmap or are soliciting PRs for the issue.)

**Comment by hlopko** [comment]
I'd like to add more data, hopefully increasing the visibility of this issue.

To start, lack of this feature blocks migration of native test rules to Starlark (fyi @comius @oquenchil).

Rules Rust require this behavior and currently achieve it by generating a test launcher for each test. In the launcher we append the environment variables we need, and exec the test. This has following issues:

* `--run_under` debugging workflow doesn't work anymore, debugger will be attached to the launcher, not to the test. If the user invokes the debugger manually on the correct binary, they loose the environment setup.
* runfiles directories are created for the launcher, not for the test. All language specific runfiles libraries (for languages having rules in Starlark that want to be able to set environment for tests) need to be made aware of the existence of the launcher and look for the runfiles directory not only in the `<binary name>.runfiles`, but also `<binary name>.launcher.runfiles` (or any other convention used for the launcher name)
* user confusion - user opens the build output directory and is confused by the presence of the launcher and the test. They can manually run both, the only observable difference is the environment setup.
* build bloat - since by the Bazel convention all tests have to be invokable without command line parameters, the only way to modify the environment for the test is to build a separate launcher binary for each test.

**Comment by hlopko** [comment]
CC @c-mita

**Comment by lberki** [comment]
/cc @comius 

My $.02: since this feature request has been open since a while that there are legitimate use cases, why not? With our move to Starlark-based rules from Java-based ones, we'll need the pertinent  functionality in Starlark anyway.

I'm a little surprised, though, about @hlopko 's assertion that this is a blocker: from a cursory reading of the code:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/RunfilesSupport.java#L495

it looks like that if a test rule has the `env` attribute defined, it will be used as a source for environment variables, it's just that Starlark test rules, contrary to native ones, don't define this attribute by default. If you define a `STRING_DICT` attribute like that, it will magically work (and this magic is arguably an argument for that attribue being defined by default...)

**Comment by c-mita** [comment]
A few lines above that, you'll see that this feature is explicitly disabled for non-native rules.
https://github.com/bazelbuild/bazel/blob/4261b2a/src/main/java/com/google/devtools/build/lib/analysis/RunfilesSupport.java#L488

Removing that check is a breaking change for rules that already define and use an "env" attribute (which is why it was added in the first place; https://github.com/bazelbuild/bazel/issues/12758.

Since there is a desire for this functionality, should we just accept the need for an incompatible change and make this an attribute all Starlark binary/test rules have by default?

**Comment by lberki** [comment]
Oh, indeed. That's what experienced engineers call "tunnel vision".

I think what you propose is a reasonable path forward. Since then, we became somewhat more lax about incompatible changes so I don't think we need an actual flag. Maybe let's try without a flag and then if it breaks something on CI add the flag?

**Comment by hlopko** [comment]
That sounds wonderful to me!

**Comment by jbms** [comment]
The reason the feature was explicitly disabled for non-native rules is that otherwise it breaks rules_docker, which already was using `env` with a different meaning.

There already is the `TestEnvironment` provider, which solves this problem for test rules in what I would consider a more elegant way than adding magic pass-through attributes:
https://docs.bazel.build/versions/main/skylark/lib/testing.html#TestEnvironment

There are just two things missing:

- a corresponding `RunEnvironment` provider for non-test binary rules
- support for `env_inherit`, if needed.

**Comment by hlopko** [comment]
I didn't know about docs.bazel.build/versions/main/skylark/lib/testing.html#TestEnvironment. That is indeed much nicer solution that allows us for example to define our own expansion variables. I've implemented a change to use `TestEnvironment` in `rules_rust` in https://github.com/bazelbuild/rules_rust/pull/960, and I'm generally happy, thank you!

I plus-one the need for an equivalent provider to handle `bazel run` use case, therefore this issue should stay open.

**Comment by sitaktif** [comment]
`env_inherit` has been great for our java integration tests and is the UX is very discreet (just an attribute). We're currently using an ugly workaround for non-native starlark rules so I am in favour of keeping `env_inherit` for non-native rules in scope for this issue.

**Comment by fmeum** [comment]
Couldn't the `TestEnvironment` provider be extended with an (optional) field `inherited_environment` that would allow Starlark rules to easily implement their own `env_inherit` attribute? This would allow for the feature to be implemented with full backwards compatibility (and no magic attributes on custom rules).

If there is consensus on how to proceed, I could submit a PR. However, this would probably require raising the priority to at least P3.

**Comment by fmeum** [comment]
@lberki Friendly ping. I am generally willing to work on this feature request, but wouldn't want contributions to get stuck in review due to this being labeled P4.

**Comment by linzhp** [comment]
@fmeum I think the turnaround time for reviewing pull requests is much better than responding to issues. I had two pull requests getting merged in reasonable time.

**Comment by meteorcloudy** [comment]
@oquenchil As we're making progress on starlarkify cc rules, we probably should bump the priority of this issue? 
@fmeum A PR on this would be welcome!

**Comment by fmeum** [comment]
> @fmeum I think the turnaround time for reviewing pull requests is much better than responding to issues. I had two pull requests getting merged in reasonable time.

I have fared well with this strategy so far, so why not try it again. This PR adds `inherited_environment` to `testing.TestEnvironment`: #14849.

**Comment by comius** [comment]
Is adding `inherited_environment` to `testing.TestEnvironment` a sufficient solution or is there something following this?

I don't see a problem, giving rule writers an option to use `inherited_environment` and this being used on some special mostly testing rules that need it.

The title of the bug says "Add common env attribute for *_binary and *_test". I oppose adding any new attributes like this to standard rules that Bazel implements, because they would hurt hermeticity. 

Adding it to TestEnvironment and providing extendable standard rules in Starlark, does allow anybody to create custom rules like *_test with it, even if this is a bad idea.

**Comment by rickeylev** [comment]
A missing part is making run + binary work. `TestEnvironment` is only respected if the rule is a test. A binary returning TestEnvironment will have the TestEnvironment provider ignored.

I'm running into this as part of Starlarkifying the Python rules, where some targets set env for a binary. Given that env is already public, without this feature, an incompatible change is inevitable. It sounds like this problem isn't limited to just the Python rules, either.

I dug through the Bazel code yesterday trying to figure out if there's _any_ way a Starlark rule, or special builtin Starlark rule with a Java helper, could make this work without any modifications to (core) Bazel. I don't think there is; there just isn't any point where Starlark code could try to inject or set something somewhere to cause the necessary, lower-level, logic to run.

The three basic options appear to be:

1. Check for some provider binary rules can return (probably in RunCommand.java; it already has special code for test+TestEnvironment) (this is what jbms said a few comments back).
2. Make env/env_inherit present for all binary rules. Prior comments indicate this is incompatible and breaks the docker rules. So either accept the incompatible change, or rules/targets need some indicator that they're opting in to this behavior.
3. Let rules define their own env/env_inherit attributes, and have a third indicator somewhere that indicates they are to be specially handled. I guess the "flags" setting of an attribute?

(From what I can tell, (2) and (3) would probably require changes within RuleConfiguredTargetBuilder.java#build and/or RunfilesSupport.java#computeActionEnvironmentModify; those seem to be the common code paths that a Starlark rule will go through where the envvars are computed. The logic to do so is already there, it's just only run for test rules)

IMHO, (1) seems most preferable. A provider allows a rule to control, filter, and transform the env/env_inherits values before passing them along. There may be a bit of extra boilerplate to e.g. expand makevars, but I don't think that's a big deal. It's easy to imagine that a rule might want to reject or warn about certain envvars, or silently ignore them, or silently tweak them. If Bazel team is still hesitant about this, we can restrict creation of it to builtin rules and revisit making it more generally available later.

Always present attributes that are "magical" and implemented directly by Bazel have the advantage of guaranteed consistent behavior. But that's also their major drawback: no control. Having to modify core Bazel (and hence wait for a bazel release) just to pass along some envvar also seems annoying (but to be fair, I wouldn't expect this logic to change much).

**Comment by fmeum** [comment]
> Is adding inherited_environment to testing.TestEnvironment a sufficient solution or is there something following this?

What I had in mind aligns with @rickeylev's option (1) and also what @jbms proposed: Introduce the equivalent of `testing.TestEnvironment` for non-test executable Starlark rules, which would then allow these rules to implement their own `env` and `env_inherit` attributes.

**Comment by comius** [comment]
> > Is adding inherited_environment to testing.TestEnvironment a sufficient solution or is there something following this?
> 
> What I had in mind aligns with @rickeylev's option (1) and also what @jbms proposed: Introduce the equivalent of `testing.TestEnvironment` for non-test executable Starlark rules, which would then allow these rules to implement their own `env` and `env_inherit` attributes.

This sounds reasonable.

Are there use cases where a rule would return both TestEnvironment and RunEnvironment, or we should just call it Environment (aliasing and deprecating TestEnvironment) thus covering both use cases?

Is there a use case for a library? Should there be an error if this is used in a lib?

**Comment by fmeum** [comment]
> Are there use cases where a rule would return both TestEnvironment and RunEnvironment, or we should just call it Environment (aliasing and deprecating TestEnvironment) thus covering both use cases?

I don't see a reason for a rule to return both (in fact, this duplication could become very confusing and error-prone). It would make sense to just make a renamed `testing.TestEnvironment` the generic solution for both binary and test targets and simply preserve it as a Starlark method for backwards compatibility.

Do you have a preference for the Starlark name of the new provider? Does it require namespacing or could it just be called e.g. `EnvironmentInfo`? 

Also, would you be fine if the new provider's key was visible to Starlark? This would allow wrapper rules around binaries and tests to forward the provider (which would be very useful for transition wrappers like the one in https://github.com/bazelbuild/bazel/issues/14673).

> Is there a use case for a library? Should there be an error if this is used in a lib?

Transitively collecting general-purpose environment variables doesn't seem like a good use case to me and would probably be prone to conflicts, so I would say this should be an error.

**Comment by fmeum** [comment]
@comius I just tried to refactor `TestEnvironmentInfo` into a general `RunEnvironmentInfo` provider that can be used for both executable and test rules, but ran into an issue: The `ActionEnvironment` for a target run with `bazel run` is constructed in `RunfilesSupport`, which only receives a `RuleContext` but not a `RuleConfiguredTarget` and thus doesn't seem to have access to the providers returned by the target. Do you see a way to work around this limitation?
