### ISSUE TITLE
vc_installation_error.bat failed: error executing command

### ISSUE THREAD

**Issue by whyAtGh** [bazelbuild/bazel#7393]
### Description of the problem / feature request:

> D:\Work\GitRepos\examples\cpp-tutorial\stage1>bazel build --verbose_failures //main:hello-world
INFO: Invocation ID: f02ec9de-9f7d-4e2b-ac90-8c736c2f7cfe
INFO: Analysed target //main:hello-world (8 packages loaded, 66 targets configured).
INFO: Found 1 target...
ERROR: D:/work/gitrepos/examples/cpp-tutorial/stage1/main/BUILD:1:1: C++ compilation of rule '//main:hello-world' failed (Exit 1): vc_installation_error.bat failed: error executing command
  cd C:/users/wanghongyun/_bazel_wanghongyun/szpbmvpy/execroot/__main__
  SET INCLUDE=
    SET PATH=
    SET PWD=/proc/self/cwd
    SET TEMP=
    SET TMP=
  external/local_config_cc/vc_installation_error.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-fastbuild/genfiles /Ibazel-out/x64_windows-fastbuild/bin /Iexternal/bazel_tools /Ibazel-out/x64_windows-fastbuild/genfiles/external/bazel_tools /Ibazel-out/x64_windows-fastbuild/bin/external/bazel_tools /showIncludes /MD /Od /Z7 /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Fobazel-out/x64_windows-fastbuild/bin/main/_objs/hello-world/hello-world.obj /c main/hello-world.cc
Execution platform: @bazel_tools//platforms:host_platform

> The target you are compiling requires Visual C++ build tools.
Bazel couldn't find a valid Visual C++ build tools installation on your machine.
Please check your installation following https://docs.bazel.build/versions/master/windows.html#using

> Target //main:hello-world failed to build
INFO: Elapsed time: 0.753s, Critical Path: 0.19s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

### Feature requests: what underlying problem are you trying to solve with this feature?

> I'm learning bazel these days and I installed bazel through the steps given by [this link](https://docs.bazel.build/versions/master/install-windows.html). Then the problem above came up and I searched the answers but no decision has been reached.

> Is it necessary to install visual studio when I just wanna use bazel?

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> The source code is your example demo in [this link](https://github.com/bazelbuild/examples/).

### What operating system are you running Bazel on?

> Win10.

### What's the output of `bazel info release`?

> INFO: Invocation ID: 4d630fa4-7653-4289-8cc0-303c88c8f530
release 0.22.0.

###  Have you found anything relevant by searching the web?

> [#85](https://github.com/bazelbuild/migration-tooling/issues/85)
[#4818](https://github.com/bazelbuild/bazel/pull/4818)
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

**Comment by rongjiecomputer** [comment]
You are trying to build `examples\cpp-tutorial\stage1` which is a C++ project, so yes, you need C++ compilers and linkers to build the project.

On Windows, you have two option: either use Visual Studio or Mingw/Msys GCC. If you have never heard of the later before, just install Visual Studio. So far, Visual Studio is better support in Bazel than Mingw/Msys GCC.

**Comment by whyAtGh** [comment]
I installed the msys2 as requested in the tutorial and I'm afraid Visual Studio is more heavier than msys so IMO msys would be preferred. 
If I use msys2, what needs to be done to fix it？
Thx.

**Comment by rongjiecomputer** [comment]
Since you already have Msys2 installed, make sure it includes GCC compilers (you can install it with pacman if it is not already there).

Then run `bazel build --compiler=msys-gcc --verbose_failures //main:hello-world`.

**Comment by whyAtGh** [comment]
It worked! Thanks a million！
I installed gcc using pacman with ` pacman -S gcc`, then I build the project by running `bazel build --compiler=msys-gcc --verbose_failures //main:hello-world`. Below is the outpurs,
```
D:\Work\GitRepos\examples\cpp-tutorial\stage1>bazel build --compiler=msys-gcc --verbose_failures //main:hello-world
INFO: Invocation ID: 870d0b44-cf1b-47eb-b4b9-5c612837ddb9
INFO: Analysed target //main:hello-world (8 packages loaded, 65 targets configured).
INFO: Found 1 target...
Target //main:hello-world up-to-date:
  C:/users/fred/_bazel_fred/szpbmvpy/execroot/__main__/bazel-out/x64_windows-fastbuild/bin/main/hello-world.exe
INFO: Elapsed time: 11.969s, Critical Path: 11.37s
INFO: 2 processes: 2 local.
INFO: Build completed successfully, 6 total actions
```

**Comment by Parth-Mawai** [comment]
ERROR: C:/users/parth/_bazel_parth/rqrcdjur/external/com_google_protobuf/BUILD:106:1: C++ compilation of rule '@com_google_protobuf//:protobuf_lite' failed (Exit 1): vc_installation_error.bat failed: error executing command
  cd C:/users/parth/_bazel_parth/rqrcdjur/execroot/org_tensorflow
  SET INCLUDE=msvc_not_found
    SET PATH=msvc_not_found
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Python27/python.exe
    SET PYTHON_LIB_PATH=C:/Python27/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=msvc_not_found
    SET TF2_BEHAVIOR=1
    SET TF_CONFIGURE_IOS=0
    SET TMP=msvc_not_found
  external/local_config_cc/vc_installation_error.bat /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/com_google_protobuf /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf /Iexternal/com_google_protobuf/src /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf/src /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw -w -w -DWIN32_LEAN_AND_MEAN -DNOGDI /DHAVE_PTHREAD /wd4018 /wd4065 /wd4146 /wd4244 /wd4251 /wd4267 /wd4305 /wd4307 /wd4309 /wd4334 /wd4355 /wd4506 /wd4514 /wd4800 /wd4996 /Fobazel-out/x64_windows-opt/bin/external/com_google_protobuf/_objs/protobuf_lite/arena.obj /c external/com_google_protobuf/src/google/protobuf/arena.cc
Execution platform: @bazel_tools//platforms:host_platform
                                                                                                                                                                                                                                                                     
The target you are compiling requires Visual C++ build tools.                                                                                                                                                                                                        
Bazel couldn't find a valid Visual C++ build tools installation on your machine.                                                                                                                                                                                     
Please check your installation following https://docs.bazel.build/versions/master/windows.html#using                                                                                                                                                                 
                                                                                                                                                                                                                                                                     
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 18.992s, Critical Path: 0.57s
INFO: 0 processes.                                                                                                                                                                                                                                                   
FAILED: Build did NOT complete successfully




I'm trying to install TensorFlow through bazel but while building it gives this error, i found this issue which is similar to what i'm facing but I used visual studio instead of msys2. I'm on win11.

**Comment by sudhakarmsr** [comment]
Even after the above steps, I'm still getting the following error. Any help here? ( I just used a simple hello world cpp file)
`$ bazel build --compiler=msys-gcc --verbose_failures /...
INFO: Analyzed 4 targets (5 packages loaded, 113 targets configured).
INFO: Found 4 targets...
ERROR: C:/dev/code/msr_work/projects/cpp_project/BUILD.bazel:13:10: Compiling cpp_project/hello_msr.cpp failed: (Exit -1): gcc failed: error executing command (from target //cpp_project:hello_msr) 
  cd /d C:/users/jeni/_bazel_jeni/7zorydrn/execroot/__main__
  SET PATH=c:/program files/git/usr/bin
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
  c:\program files\git\usr\bin\gcc -std=gnu++0x -MD -MF bazel-out/x64_windows-fastbuild/bin/cpp_project/_objs/hello_msr/hello_msr.pic.d -frandom-seed=bazel-out/x64_windows-fastbuild/bin/cpp_project/_objs/hello_msr/hello_msr.pic.o -fPIC -DBAZEL_CURRENT_REPOSITORY="" -iquote . -iquote bazel-out/x64_windows-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/x64_windows-fastbuild/bin/external/bazel_tools -c cpp_project/hello_msr.cpp -o bazel-out/x64_windows-fastbuild/bin/cpp_project/_objs/hello_msr/hello_msr.pic.o
# Configuration: 6a35e75860397fd63fefd3dfc7acd42ea4e381c287d73f07e6f4aa778b1deae1
# Execution platform: @local_config_platform//:host
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("c:\program files\git\usr\bin\gcc" -std=gnu++0x -MD -MF bazel-out/x64_windows-fastbuild/bin/cpp_project/_objs/hello_msr/hello_msr.pic.d -frandom-seed=bazel-out/x64_windows-fastbuild/bin/cpp_project/_objs/hello_msr/hello_msr.pic.o -fPIC "-DBAZEL_CURRENT_REPOSITORY=\"\"" -iquote . -iquote bazel-out/x64_windows-fastbuild/bin -iquote external/bazel_tools -iquote bazel-out/x64_windows-fastbuild/bin/external/bazel_tools -c cpp_project/hello_msr.cpp -o bazel-out/x64_windows-fastbuild/bin/cpp_proje(...)): The system cannot find the file specified.
 (error: 2)
INFO: Elapsed time: 0.200s, Critical Path: 0.03s
INFO: 6 processes: 6 internal.
FAILED: Build did NOT complete successfully`
