### ISSUE TITLE
Specify j2objc location?

### ISSUE THREAD

**Issue by spierce7** [bazelbuild/bazel#740]
Is there any way to specify the j2objc location? [The documentation](http://bazel.io/docs/be/objective-c.html#j2objc_library) doesn't really say anything. One thing about reproducing builds that would be nice is if the exact j2objc version could be ensured. An easy way to do that would be to check j2objc into version control, and then tell the j2objc rule where it should be looking for j2objc. Maybe there is a way to do this already that I'm not realizing?

**Comment by kchodorow** [comment]
It looks like j2objc is specified here: https://github.com/bazelbuild/bazel/blob/1a90e50a90055fa75ab6ab2c41fd344934be5a96/src/main/java/com/google/devtools/build/lib/bazel/rules/objc/j2objc.WORKSPACE.  You could override that in your own WORKSPACE file with the identical rule:

```
new_http_archive(
    name = "bazel-j2objc",
    url = "https://github.com/google/j2objc/releases/download/0.9.8.1/j2objc-0.9.8.1.zip",
    sha256 = "3edff65fbfaa0a99fdb36dad97059070ba09b77ace7753573771204395dd862b",
    build_file = __embedded_dir__ + "/embedded_tools/third_party/java/j2objc/BUILD.remote"
)
```

Which should guarantee that's the version used for anyone you checks out your repo (instead of it being dependent on the Bazel code they're using).  (You could also define bazel-j2objc to anything else you wanted in your WS file.)

**Comment by spierce7** [comment]
Awesome! I didn't realize it was downloading and installing it locally.
