### ISSUE TITLE
sandboxfs not working with --output_base or --output_user_root

### ISSUE THREAD

**Issue by ahippler** [bazelbuild/bazel#7435]
### Description of the problem / feature request:

Sanboxfs is producing errors (Operation not permitted while opening output file) when defining --output_base or --output_user_root not in /private/var/tmp

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel build --experimental_use_sandboxfs //absl/...` and 
`bazel --output_base=$HOME/abseil/ build //absl/...` passes without erros
but 
`bazel --output_base=$HOME/abseil/ build --experimental_use_sandboxfs //absl/...` produces 
`error: unable to open output file 'bazel-out/darwin-fastbuild/bin/absl/strings/_objs/ascii_benchmark/ascii_benchmark.o': 'Operation not permitted'`

### What operating system are you running Bazel on?

MacOS 10.12.6

### What's the output of `bazel info release`?

release 0.22.0-homebrew

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/abseil/abseil-cpp.git
426eaa4aa44e4580418bee46c1bd13911151bfb1

### Sandboxfs Version

sandboxfs-0.1.0-20190205
FUSE for macOS 3.8.3

**Comment by ahippler** [comment]
any news?

**Comment by freme** [comment]
@jmmv - this error is still present with bazel 3.1.0 and sandboxfs 0.2.0

Changing the default output directory layout as described in https://docs.bazel.build/versions/master/output_directories.html using either --output_base or --output_user_root breaks the sandbox build

**Comment by jmmv** [comment]
Sorry for the delay...

So the problem comes from here:

```
(version 1)
(debug deny)
(allow default)
(deny file-write*)
(allow file-write*
    (subpath "/dev")
    (subpath "/private/var/folders/6c/16j7hmxs65x4mtf6xq6m8qhm002m9r/T")
    (subpath "/Users/jmmv/Library/Logs")
    (subpath "/private/var/tmp")
    (subpath "/Users/jmmv/Library/Developer")
    (subpath "/private/var/folders/6c/16j7hmxs65x4mtf6xq6m8qhm002m9r/C")
    (subpath "/Users/jmmv/abseil/sandbox/darwin-sandbox/10/execroot/com_google_absl")
    (subpath "/private/tmp")
)
```

This is the configuration we write for `sandbox-exec`. When we use the default output base, we get blanket access to write into `.../tmp/` and because the sandboxfs instance is there, things work. When we move the output tree elsewhere, the sandbox only allows access to the `.../sandbox/darwin-sandbox/...` paths. This is fine for the symlinked sandbox because the symlinks are there, but when sandboxfs is active, we are issuing the writes to a path that is not covered by the sandbox.

Should be easy to fix. Let me see if I can do something quickly.

**Comment by jmmv** [comment]
This uncovers something else though: because the default output base is under `/private/var/tmp`, and because the sandbox configuration allows blanket write access to `tmp` directories... the sandbox isn't really protecting against writes across different per-action directories! Yikes. I'll add a note to #11100 about this, which I think is where we should tackle this separate issue.
