### ISSUE TITLE
Symbol resolving when indirect referencing.

### ISSUE THREAD

**Issue by chin33z** [bazelbuild/bazel#751]
I have a() in libA.c , b() in libB.c.
main() calls a() & a() calls b().
Thus, main() has indirect dependency to b().
The following is my BUILD file.

```
cc_binary(
    name = "hello",
    srcs = ["main.c", "libA.so"],
)

cc_binary(
    linkshared = 1,
    name = "libA.so",
    srcs = ["libA.c", "libB.so"],
)

cc_binary(
    linkshared = 1,
    name = "libB.so",
    srcs = ["libB.c"],
)
```

After executing **bazel build //:hello**
Bazel complains it cannot find the symbol b() when linking hello:

```
/usr/bin/ld: warning: libB.so, needed by bazel-out/local_linux-fastbuild/bin/_solib_local/_U_S_S_Chello___U/libA.so, not found (try using -rpath or -rpath-link)
bazel-out/local_linux-fastbuild/bin/_solib_local/_U_S_S_Chello___U/libA.so: undefined reference to `b'
collect2: error: ld returned 1 exit status
ERROR: /root/test/BUILD:1:1: Linking of rule '//:hello' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local_linux-fastbuild/bin/hello '-Wl,-rpath,$ORIGIN/_solib_local/_U_S_S_Chello___U' -Lbazel-out/local_linux-fastbuild/bin/_solib_local/_U_S_S_Chello___U -B/usr/bin/ ... (remaining 7 argument(s) skipped).
Target //:hello failed to build
```

Can't Bazel automatically resolves the indirect symbols? Thanks.

**Comment by bsilver8192** [comment]
Actually, it's failing to find libB.so when linking, so then it can't find any of the symbols in it. That's because libB.so is in libA.so's runfiles, but those aren't used at compile time. I think the issue is that shared objects generated with `cc_binary` (like libA.so and libB.so) are intended for linking into external code or opening with dlopen, not linking into other Bazel-compiled code. Is there some reason `cc_library` won't work for what you're doing?

**Comment by chin33z** [comment]
I want to control the soname (libxxxxx.so) when linking, so I have to use cc_binary().
Bazel will do its own mangling on soname when linking with cc_library() & deps.

Here is the thread discussed before but I didn't find the answer:
https://groups.google.com/forum/#!topic/bazel-discuss/PxZ6Znjor1g

In summary, we cannot have the benefits of 
```
   1) auto-resolves libraries dependency when linking (cc_library()'s deps)
   2) full control of the soname
```
at the same time. Am I correct on this? Thanks.

**Comment by philwo** [comment]
@chin33z, I think you're right. Leaving this open in case someone has an idea for a workaround, but I guess this is unfortunately a use case that it just not supported by Bazel (yet).

**Comment by ulfjack** [comment]
Putting the .so into the srcs attribute tells Bazel to only consider the file, not anything attached to the rule generating it, so Bazel will not look at the dependencies of libA.so. I think putting the cc_binary into deps instead might work, except Bazel currently doesn't allow this (the whitelist for deps in BazelCppRuleClasses.java only allows cc_library).

You could try to change that Java file and see if that does what you want. However, I'm not sure we want to allow cc_binary in the deps of cc_binary. If we're going this route, it might make more sense to add a new cc_dynamic_library rule that explicitly generates a dynamic library, rather than ab-using cc_binary to do that.

**Comment by chin33z** [comment]
I just whitelist the cc_binary in BazelCppRuleClasses.java and modify my BUILD to:
```
cc_binary(
    name = "hello",
    srcs = ["main.c"],
    deps = ["libA.so"],
)

cc_binary(
    linkshared = 1,
    name = "libA.so",
    srcs = ["libA.c"],
    deps = ["libB.so"],
)

cc_binary(
    linkshared = 1,
    name = "libB.so",
    srcs = ["libB.c"],
)
```

Then I get the error:
```
main.c:(.text+0xa): undefined reference to `a'
collect2: error: ld returned 1 exit status
```

I guess it is not simple as just whitelist the cc_binary in deps.
Ex. cc_binary() does not have the hdrs attributes. How will Bazel handle the library symbol in this case?

Still, thanks for this idea. I will try this route.

**Comment by davidstanke** [comment]
@mhlopko what do you recommend?

**Comment by mhlopko** [comment]
I'm glad you're not using cc_library to produce shared libraries that are supposed to be consumed outside of the bazel build. That said, I'm aware of limitations of cc_binary when producing shared library. This all will be solved by [transitive-libraries](https://docs.google.com/document/d/1d4SPgVX-OTCiEK_l24DNWiFlT14XS5ZxD7XhttFbvrI/edit), currently scheduled to be finished by EO2018.

Until then, I'm afraid you'll have to enumerate all transitive shared libraries as deps of cc_binary. Unless @dslomov says it's possible to write a an [aspect](https://docs.bazel.build/versions/master/skylark/aspects.html) that will collect all transitive shared library cc_binary outputs and put them just into the right place for cc_binary to load.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
