### ISSUE TITLE
CI: //src/test/shell/bazel:bazel_rules_test fails on Windows

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7515]
e.g. https://buildkite.com/bazel/google-bazel-presubmit/builds/15753#252c0188-d29d-4bb1-8752-0546144f8026
https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/252c0188-d29d-4bb1-8752-0546144f8026/src%5Ctest%5Cshell%5Cbazel%5Cbazel_rules_test%5Cattempt_1.log

Since it started failing approximately the same time as @fwe said "I'm deploying new CI worker images", I'm assigning the bug to you. It might be unrelated, but I don't see any commit that could be related.

**Comment by philwo** [comment]
I have a fix for this, will send it for review.

**Comment by philwo** [comment]
Fix is in review, basically what happened here was setting PATH on Windows to a ';' delimited PATH even though the test runs in MSYS (thus PATH is ':' delimited), which caused the first entry in the PATH to become invalid, which means that the "Bazel wrapper" used inside the integration tests to redirect "bazel" to the Bazel binary of the runfiles of the test could no longer be found, which in turn caused "bazel" to run the Bazel installed on the system.

**Comment by gregestren** [comment]
FYI I'm still experiencing this, and I think others are too (https://buildkite.com/bazel/google-bazel-presubmit/builds/15871#5ea58499-72d4-4987-8676-4250895cbd55).

@fweikert pointed me to https://github.com/bazelbuild/bazel/commit/33c982e01ec7ce50db0a3de4d79b2adfe9e244af and suggested that might not have been enough.

FYI @c-parsons

**Comment by gregestren** [comment]
But we also have some passes:

https://buildkite.com/bazel/google-bazel-presubmit/builds/15873#eb4df38e-5708-41c4-b68f-a8e484a3667c
https://buildkite.com/bazel/google-bazel-presubmit/builds/15874#7a4b17e7-5978-4785-93c6-b14c5c4da425

So maybe flaky?

**Comment by gregestren** [comment]
Yeah, its the same issue:

From https://buildkite.com/bazel/google-bazel-presubmit/builds/15876#5fbc3188-e9eb-41c4-8e2f-dbe49894c11e:

```
PATH=(C:\python3\Scripts\;C:\python3\;C:\Windows\system32;
C:\Windows;C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;
C:\ProgramData\GooGet;C:\Program Files\Google\Compute Engine\metadata_scripts;
C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;
C:\Program Files\Google\Compute Engine\sysprep;C:\ProgramData\chocolatey\bin;
C:\Program Files\Git\cmd;C:\tools\msys64\usr\bin;c:\openjdk\bin;
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;
C:\Program Files\CMake\bin;c:\ninja;c:\bazel;c:\buildkite)
```

**Comment by gregestren** [comment]
Since then both @c-parsons and I have had our changes pass & successfully commit.

I think I've figured out (sort of) what's going on. The environment lines above are a false trail: as I understand @philwo 's test fix didn't try to change that path, rather just work around it.

The problem was just client sync latency on the CI machines. For reasons I don't fully understand, my [failing presubmit run](https://buildkite.com/bazel/google-bazel-presubmit/builds/15871#5ea58499-72d4-4987-8676-4250895cbd55) was synced (under `Setup` -> `Preparing working directory` -> `git checkout -f ...`) to [e424e9b4ddc79b588b1e3f8f5836dd784866567a](https://bazel.googlesource.com/bazel/+/e424e9b4ddc79b588b1e3f8f5836dd784866567a). This has a `Copybara-Service` committer timestamp of `Fri Feb 22 16:12:08 2019 -0800`, which predates https://github.com/bazelbuild/bazel/commit/33c982e01ec7ce50db0a3de4d79b2adfe9e244af.

I was first led to this after looking at this [log entry](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/5ea58499-72d4-4987-8676-4250895cbd55/src%5Ctest%5Cshell%5Cbazel%5Cbazel_rules_test%5Cattempt_1.log): 

```
FAILED: Failed to build //pkg:test .
D:\\b\\wxhy3tvl\\execroot\\io_bazel\\bazel-out\\x64_windows-
fastbuild\\bin\\src\\test\\shell\\bazel\\bazel_rules_test:322: in call to
test_genrule_default_env
```
That's weird because https://github.com/bazelbuild/bazel/commit/33c982e01ec7ce50db0a3de4d79b2adfe9e244af#diff-802dc58833c9f7ec118f31124ac63e63 removes that check on line 322 -> the post-diff version of line 322 is just a comment.

I swear up and down my local client was fully synced, so I don't know what determines exactly which baseline made it to the presubmit.

So after [another equivalent try](https://buildkite.com/bazel/google-bazel-presubmit/builds/15875#3e687af8-1ff2-4f74-9533-3dee1663d43f) of the presubmit, it now syncs to [94d1a57cbfb5afb70bb186bb07ec2abec0ce1163](https://bazel.googlesource.com/bazel/+/94d1a57cbfb5afb70bb186bb07ec2abec0ce1163), which is sufficiently current.

So... there!
