### ISSUE TITLE
Shared library with `dynamic_library` default output group and automatic naming - `cc_library::linkshared`

### ISSUE THREAD

**Issue by excitoon** [bazelbuild/bazel#7538]
How would I create shared library target which would resolve into shared library and have automatic naming (`libXXX.so` for POSIX and `XXX.dll` for Windows)?

I would like to not specify exact name because, you know, one does not simply make a `select` for target name:
```
cc_binary(name = select({':windows' : 'XXX.dll', '//conditions:default' : 'libXXX.so'}), ...)
```

I could use `cc_library` but unfortunately its' default output group is `static_library` and staticness of library is being tuned in consuming target.

What would you advice me?

**Comment by hlopko** [comment]
So the summary of the issue, if I understand it correctly, is:

* you have a multiplatform project, at least linux and windows.
* you need to create a dynamic library and link against it from a binary, so expressing this using cc_library doesn't work (pls confirm this, as using cc_library and not insisting on using shared library would be more Bazel-idiomatic and would in general produce better code).

In this case cc_binary forcing you to specify the exact filename is the problem. I believe this will be solved by [transitive libraries](https://github.com/bazelbuild/bazel/issues/5200).

To propose a temporary workaround, you could create a macro, that would always declare both .so and .dll targets, and a filegroup that will select on the current platform and pick one of them. Only the used library will be built.

Does that solve your problem?

**Comment by meteorcloudy** [comment]
@excitoon I just implemented the exact thing for TensorFlow a while ago:
https://github.com/tensorflow/tensorflow/blob/f2d02715b39b369b17cbe78874e6338d5687dab9/tensorflow/tensorflow.bzl#L407

**Comment by excitoon** [comment]
@hlopko Agree on first point and partly on second one.

dynamic libraries created as `cc_library` work perfectly well, I even tried to upload an example of it in #7629. But in general libraries are double-natured, static and dynamic. We can disable shared library (strictly speaking `dynamic_library` output group) by using `linkstatic=1`, but we can not disable `archive` same easy.
One can use `filegroup` with `dynamic_library` output group for this but after `filegroup` library become plain file, and can not be used in `deps` of other rules anymore.

I guess we need a way to mask output groups of a target in order to use them in different cases, for example:
```
cc_library(name='b')

cc_library(name='a', deps=[ static(':b') ])
pkg_tar(name='c', files=[ dynamic(':b') ])
```

Or specify staticness in the library (which is more CMake-like, but cleaner):
```
cc_library(name='b_static', linkstatic=1)
cc_library(name='b_dynamic', linkshared=1) # This is an imaginary attribute, not implemented.

cc_library(name='a', deps=[ ':b_static' ])
pkg_tar(name='c', files=[ ':b_dynamic' ])
```

Main underlying problem (well, under several layers) here is that in `pkg_tar` we can not distinguish what it shall be, `archive` or `dynamic_library`. `cc_binary` is a wrong way to solve this problem, masking output groups is better option, but requires to create additional wrappers and call functions unfortunately. What is need to be done I guess is a corresponding option to `linkstatic` in `cc_library` - `linkshared`.

Declaring multiple targets is a big overhead for us (we shall have 3x more targets, including `.dylib` on OS X).

**Comment by excitoon** [comment]
@hlopko @meteorcloudy ping 😥

**Comment by chandlerc** [comment]
It is unclear whether this feature request is really the thing that the transitive libraries would ever address.

There seem to be two different issues here:

1. Building a library that will be part of the `deps` of some other artifact of the Bazel build, but *needs* to be a dynamic library of some form. This seems close to the transitive library space?

2. Building a dynamically loaded plugin library.

The second use case is, IMO, much more common. This is building a `.so`, `.dll`, or `.dylib` that is an actual output artifact of a Bazel build. This seems to be the use case described above for TF and implemented here:
https://github.com/tensorflow/tensorflow/blob/f2d02715b39b369b17cbe78874e6338d5687dab9/tensorflow/tensorflow.bzl#L407

This second use case is *almost* supported by Bazel, as you can see in the TF build: you can build `cc_binary` targets that are linked as loadable shared objects. It even works on ~most platforms. But because Bazel keys off of the *name* of the target and provides no way to configure that name, TF is forced to resort to pretty egregious steps to implement this functionality.

It turns out that using LLVM and Clang with Bazel would *also* benefit from exactly this kind of functionality. Both of these systems at times build dynamically loadable plugins (such as `libclang.so`), and we currently have no way of expressing that. Rather than duplicate the TF workaround into another project, is there any hope of getting a principled approach for this into Bazel? Should we file a separate issue to track specifically the ability to build plugins like this?

**Comment by excitoon** [comment]
This shall be closed as resolved. Your bot does not work very well. Please
do not spam with useless comments.

**Comment by oquenchil** [comment]
This is not a bot, but an actual person and please call out mistakes respectfully in the future.

**Comment by sventiffe** [comment]
@excitoon even if you disagree with our decisions, mind your language please.  We are indeed closing out old issues -- if you think this one is still relevant, please follow up with @oquenchil in particular if cc_shared_library might address your problem.

**Comment by excitoon** [comment]
If he is a person, it's even worse, because he does not even read issues
where he leaves comments, in this case @chandlerc proposed a working
solution, which resolved the issue. I apologize, however, for saying he is
a bot.

I do not disagree with decisions of Bazel team, but I disagree to ignorance.

**Comment by excitoon** [comment]
@oquenchil Actually, it is like 10th email in my inbox, and I patiently
endures first mistakes of these.

**Comment by sventiffe** [comment]
@excitoon If you want to engage with anyone, tone down. I ask you to gracefully accept our criticism and to stop your derogatory comments about sgowroji. Your tone is not acceptable. 

The issue stalled since the least meaningful update 2 years ago and is considered closed. You might notice more issues that are closed down due to age and inactivity. Consider them not being closed by mistake. 

My comment from 1 hour ago still applies for this and other issues of your interest.

**Comment by excitoon** [comment]
I wonder do you understand that this issue is resolved 2 years ago, not
stalled? It's fine to close it, but saying it is stalled or the team does
not have time for it is simply a lie (disinformation). Why you blame me for
criticizing disinformation?

**Comment by sventiffe** [comment]
I blame you for statements like "If he is a person, it's even worse". 

I am happy to hear from you that issue got resolved two years ago.

If the main thing that keeps you busy is someone used the wrong word or might not have carefully read the history of the issue, then I am happy to tell you that you made your point. Please stop spamming us. For all other issues that may or may not be resolved, my past comments apply.

**Comment by excitoon** [comment]
You blame people for saying truth, then. I got your point too. :(

**Comment by sventiffe** [comment]
I am just a language model, I can't help you with that.
