### ISSUE TITLE
FR: provide Build Event Protocol messages over an HTTP port

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#7565]
Discussed in-person with @dslomov at Bazel rule author summit.

Bazel's command-line UI is not the most intuitive way for users to understand builds. In Google, we rely on a web-based UI (sponge, of which I was TL for a couple years) to understand most build results, and Google Cloud has a similar Test Result UI for this purpose.

However, for local development where the user cannot upload results to a cloud service, it would be convenient for the tooling to display a web-based build result UI running locally, either in a browser or in the editor directly. We have thoughts of building a VS Code extension that displays the currently running build (likely belongs in the official Bazel Team extension if successful)

The best way for such tooling to get the Build Events is to connect directly to a port on the Bazel Server, get a dump of past events, then recieve new events using some push mechanism like the WebSocket API.

This also presents a fix for the `ibazel` case I reported in https://github.com/bazelbuild/bazel/issues/6856 - if several bazel commands are run, the HTTP client can receive events for all of them without having to negotiate some re-connection for each command.

Proposal:
- bazel accepts startup option like `--bep_expose_http=[port]`
- bazel server buffers build events for some period, or some fixed memory size
- when a client connects, send them all buffered build events
- additional build events are also sent to the client
- use the existing JSON format of build events available on the command line today

/cc @lfpino

**Comment by dslomov** [comment]
@lfpino @ulfjack how hard would it be to implement this?

**Comment by ulfjack** [comment]
I don't have an overarching writeup, but let me add some notes here of what we should keep in mind:

- exposing an HTTP port
  - exposing an HTTP port is a potential security+privacy concern, and not something to do lightly
  - we already ship at least one HTTP server in Bazel, although locked-down to prevent usage from anyone except the same local machine login; it also doesn't report BEP events
  - we already have a push model for the BEP, why would we also need a pull model? VS Code could just as well open a port and have Bazel push data to it, rather than the other way round
  - a pull model also introduces issues with additional buffering which are hand-waved in the original post
- we want to cover _other_ IDE use cases as well
  - sponge was primarily designed as a historic view rather than an real-time UI (although it does some of that), and this is reflected in the BEP
  - we already have requests to provide richer information than the BEP currently provides in order to have more real-time reporting
- however, putting more stuff into BEP will bloat the protocol and make historic storage and retrieval more costly
  - I'm wondering if we should use the BES protocol (which wraps BEP) to publish multiple streams, some of which are ephemeral
  - that would solve the protocol bloat and allow servers to make decisions around garbage collecting partial data over time
  - Buffering stdout/stderr may not be useful in any case, and splitting the information into multiple streams could help reduce memory consumption if we need an additional buffer
- Bazel is _already_ caching all BEP events (to support incremental builds) _other than_ stdout/stderr, although replaying the events on demand while another build is ongoing is technically difficult


Adding another HTTP server is ~easy, but I have to ask why? Also, we may want to change Bazel to use the BES protocol wrapping BEP even for local reporting rather than vanilla BEP.

**Comment by alexeagle** [comment]
/cc @andresdominguez who is looking into writing the UI

- Agreed on binding only to loopback network interface (unless users specifies otherwise so their coworker can observe a build, or can use an editor UI remote from their workstation)
- The reason that we want Bazel to be the server is that we only want a client footprint. That makes it easier to re-use the UI component across a dedicated VSCode extension, embedded in other extensions that Angular users already interact with (e.g. https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console), embedded in web IDEs (e.g. https://stackblitz.com/) and simply open an .html file in the browser. If the UI is required to start a server process as well, then we have to have a separate process and it makes it much harder to port it to run in these environments.

**Comment by ulfjack** [comment]
It would seem preferable to point the browser at the local http port rather than open an .html file, although that'd require that we ship the html code with Bazel, which in turn means that someone would have to maintain it.

I still don't like the buffering requirement. We can't buffer unconditionally, and we can't buffer indefinitely. How's that supposed to work?

**Comment by alexeagle** [comment]
I don't want the application to be served from the bazel binary, that would make the release process for it intractable, and harder to embed different views in different context (in an editor there would be just a panel, in the browser it would need more context about what project you're in, etc). Just having Bazel serve data is sufficient I think.

I'm sure I can't produce a better proposal for buffering events than you can :)

Thinking a bit more about the common workflow, I think we could deal with no buffering at all. The constraint would be that the client should be connected before the build command starts, so the boot process should be:
1. client (editor plugin or CLI tool) starts the web application, which tries to connect to bazel. Commonly the bazel server is already running, but if this is the first command, it just has to retry until the bazel server is listening
2. client (after maybe a hardcoded wait time?) executes the first bazel command
3. if the client doesn't get a `BuildStarted` event first, it can just report to the user that they might want to re-try this initial build
4. the client and bazel server stay running, so subsequent commands don't have a handshake issue

If the client connects after `BuildStarted`, it's just missing some build context, but could probably still degrade to a useful state of streaming the test results.

How do you feel about iterating on the developer experience of the feature with no buffering?

**Comment by cgruber** [comment]
Any motion on this?

**Comment by ulfjack** [comment]
It seems like the better option would be to start the build through the http API, rather than starting a build with a subprocess execution and then trying to listen to events on a separate channel.

**Comment by alexeagle** [comment]
That's a very interesting proposal. Of course it expands the scope of this FR (what would a build request look like? similar to the protocol buffer we use to send requests to Build Rabbit in g3?) but also opens up a lot of other use cases where you could skip calling through the C++ client wrapper and spawning a subprocess to interact with Bazel. For example in a nodejs environment you could have a JS client that interacts with the Bazel server which would be more idiomatic. Another example, the editor plugin could perform a build or a query without spawning a process.

All that said, it feels like a larger scope here is even less likely to happen. WDYT?

I suppose we could experiment with this by writing a bazel wrapper that lives at `tools/bazel` in users repo and hosts the HTTP endpoint.

**Comment by ulfjack** [comment]
I don't think it's significantly more complex, and it resolves a concern that could otherwise cause a lot of maintenance and debugging. For my own selfish reasons, I'd like to build a prototype, but it's unlikely to happen this year.

**Comment by alexeagle** [comment]
/cc @pcj 
discussing this at BazelCon - Ulf tells me Bazel server already exposes gRPC over HTTP.

**Comment by janakdr** [comment]
cc @michaeledgar

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
