### ISSUE TITLE
Error importing python module in action that requires a py_binary tool

### ISSUE THREAD

**Issue by sergiocampama** [bazelbuild/bazel#7569]
### Description of the problem / feature request:

When running a python tool that's added as an action from a py_binary target, this tool is having issues finding imports that are also coming from the workspace.

```
ERROR: /Users/kaipi/Development/Github/rules_apple/examples/multi_platform/Buttons/BUILD:72:1: StoryboardCompile examples/multi_platform/Buttons/Buttons-intermediates/Base.lproj_storyboardc/Main.storyboardc failed (Exit 1)
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_kaipi/064c9eeacb1ec8864a00b136cc08e89e/execroot/build_bazel_rules_apple/bazel-out/host/bin/tools/xctoolrunner/xctoolrunner.runfiles/build_bazel_rules_apple/tools/xctoolrunner/xctoolrunner.py", line 45, in <module>
    from build_bazel_rules_apple.tools.wrapper_common import execute
ImportError: No module named build_bazel_rules_apple.tools.wrapper_common
Target //examples/multi_platform/Buttons:Buttons failed to build
```

https://buildkite.com/bazel/rules-apple-darwin/builds/397#bb927f9a-e4ab-4f6e-9bef-6022b6450356

This is a problem in the latest green version of bazel. 0.23.0 works as expected, as can be seen in the logs.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Checkout `bazelbuild/rules_apple`
```
bazel build examples/multi_platform/Buttons # with bazel 0.23 works
```

```
bbazel build examples/multi_platform/Buttons # with bbazel being built from head using 0.23, it fails
```

### What operating system are you running Bazel on?

macOS 10.13

### What's the output of `bazel info release`?

It's the head version

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

```
bazel build src:bazel
```

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

ceffff91dfa910146389235abef3537ad789c301

**Comment by brandjon** [comment]
The fact that it works in 0.23 but regressed at head surprises and concerns me. I believe the only thing I touched that was imports related was fixing #7054. Possible mechanism would be if that causes something to be put on PYTHONPATH that was previously (incorrectly) ignored, and it shadows your library. Though since you're using a fully qualified import (with the repo name) that shouldn't matter.

Will have to investigate.

**Comment by meteorcloudy** [comment]
This is the same root cause as https://github.com/bazelbuild/bazel/issues/7577

See the bisecting at https://buildkite.com/bazel/culprit-finder/builds/130#4c0a054a-5029-48fa-b408-5291b0f8a8c5

**Comment by meteorcloudy** [comment]
Should be fixed after https://github.com/bazelbuild/bazel/commit/70981cd18d16501779ec59434270f7eb313aa551

**Comment by sergiocampama** [comment]
fixed for our purposes

**Comment by brandjon** [comment]
Ok, after some lengthy debugging @dkelmer and I have this one figured out.

The Python rules automatically generate empty `__init__.py` files in the package of a Python executable target and its parent packages, excluding the repo's top-level package. The top-level package needs its own explicitly defined `__init__.py`, which rules_apple does via `//:py_init_shim`. You depend on this target in some places but not others.

Contrary to the [comment](https://github.com/bazelbuild/rules_apple/blob/54c468410e088f5ad31f01e29194a14cea49fc00/__init__.py#L17-L18) in the init file, you actually do need to depend on the top-level init from both `py_binary` targets and `py_test` targets, not just `py_test`. Because you were missing this dependency from `//tools/xctoolrunner:xctoolrunner`, the top-level init file was not in the runfiles tree and the tool was therefore unable to load any Python modules from any of its dependencies within the repo.

The funny thing is that this should've never worked in the first place, with or without the new `--incompatible_remap_main_repo` flag. From inspecting the generated files, it appears that there's a bug in the Python rules causing extra `__init__.py` files to be generated in the runfiles tree, both at the repo root dir and (bizarrely) in the runfiles root itself. My guess is that this is happening because the "external" prefix has special logic that is confusing the init file auto-generation logic. This prefix is created when you refer to the target as `@your_main_repo_name//some:target` but not when you refer to it as `@//some:target`. The new incompatible flag has the effect of causing the former to be rewritten as the latter.

The fix for your side of things is to just add a dep on `//:py_init_shim` to `//tools/xctoolrunner:xctoolrunner`, and any other Python targets for which you get this error. (You can factor the dependency into an earlier `py_library` target, of course.)
