### ISSUE TITLE
Bazel does not copy xml test output from sandbox.

### ISSUE THREAD

**Issue by chpatton013** [bazelbuild/bazel#757]
Bazel has support to capture xml test output via the `XML_OUTPUT_FILE` environment variable. The gtest driver can look for this environment variable and use it to define the `gtest_output` option to `"xml:$XML_OUTPUT_FILE"`.

However, Bazel fails to copy this xml file out of the sandbox, so the results are lost.

See this chat log for a history of how this information was discovered: https://gist.github.com/chpatton013/52ae6a1311980df9c884

Also, there is seemingly no documentation on the `XML_OUTPUT_FILE` feature. I think that should also be fixed, since I wasted multiple hours searching the documentation for this feature.

**Comment by philwo** [comment]
This is because the XML output file is not a declared output artifact, but instead some weird "well, concatenate some strings and what you get from that may or may not exist" special case in the test strategy. I would love to fix this! We also need this fixed for the new JUnit test runner that @damienmg is integrating now.

@ulfjack I remember that we talked about this a month ago or so. We could either make this a real output artifact of tests and require it to be present, or we could somehow introduce the idea of "optional output artifacts", or we could add a way to signal the sandbox strategy that certain files should be copied in case they exist. The latter is probably the easiest. WDYT?

**Comment by ulfjack** [comment]
SGTM. We probably want to make sure that we cover the other optional test
outputs as well.

On Thu, Jan 7, 2016 at 3:49 PM, Philipp Wollermann <notifications@github.com
