### ISSUE TITLE
Make Xcode setup more resilient

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#7592]
https://github.com/bazelbuild/bazel/pull/7519 is getting reverted because of issues Google hit internally. This ticket is tracking what the issues were so that we can fix them and resubmit to fix the original issue.

Related:

- https://github.com/bazelbuild/bazel/issues/7575
- https://github.com/bazelbuild/bazel/pull/7576
- https://github.com/bazelbuild/bazel/issues/6056

**Comment by sergiocampama** [comment]
One of the issues we saw internally is that some developers, and CI machines, may have unfinished Xcode installations. These will fail when invoking `xcodebuild` on them, but they may have other Xcode installations that are suitable for building, so we should not `fail` when one of the Xcode installations failed and others didn't

**Comment by keith** [comment]
It sounds like in that case we shouldn't error from xcode_locator itself and just not add that broken install to the output

**Comment by mariusgrigoriu** [comment]
I encounter the `external/local_config_cc/BUILD:55:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-watchos_i386: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, try: "bazel clean --expunge" to re-run Xcode configuration` issue frequently, especially if I get errors during the analysis phase on a prior bazel invocation. The resolution has been to `bazel shutdown` which is far less invasive than `bazel clean --expunge`. Is it fair to get update the recommendation to try a shutdown first as a short-term fix while we hammer out the root cause of these issues?

**Comment by steeve** [comment]
I agree with @mariusgrigoriu, that solution is far less invasive that suggesting a full clean until the proper fix is done.

**Comment by jmmv** [comment]
If the Xcode installation is incomplete/wrong, there is not much we can do. And since 2488347ecfd07931ea2c6676e11fba16dec3273b, which was submitted after this report, we no longer tell users to run clean but instead say that shutdown is sufficient. So I think we can say that this is resolved.
