### ISSUE TITLE
[BEP] Multiple events reporting the same ActionCompletedId child, making BEP a DAG instead of a tree

### ISSUE THREAD

**Issue by EdSchouten** [bazelbuild/bazel#7608]
### Description of the problem / feature request:

For [Buildbarn Browser](https://github.com/buildbarn/bb-browser) I am currently working on adding support for parsing/displaying BEP/BES data. So far stuff is going pretty well: I can display targets, whether they succeeded/failed, build error output, test output, etc.

During my tests, I managed to stumble upon a single log in which two separate nodes, both a Progress and TargetCompleted node, announce the same child ActionCompletedId. In other words, it means the stream of events thus corresponds to a DAG; not a tree.

As I've previously observed that the generated output always (?) corresponds to a tree and not a DAG, my question is: is BEP supposed to be a DAG or a tree? I've noticed that for other events, the protocol already performs tricks to avoid creating a DAG at the event level. For example, TargetComplete nodes don't have NamedSetOfFiles nodes as direct children. Their IDs are contained in OutputGroup, but they are only true children of Progress.

What I've observed about the current structure is that due to this DAG-like approach, the topological sorting between events as normally generated by Bazel is violated. We first send the Progress, followed by the ActionCompleted, followed by the TargetComplete, referring back to the ActionCompleted. In Buildbarn Browser I have to 'hack' around this by delaying processing of ActionCompleted until the very end to permit top-down construction.

My question is, is all of this intended?

**Edit:** I've rephrased the text above, as I got a better understanding of the problem.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Extract this file: [foo.zip](https://github.com/bazelbuild/bazel/files/2922506/foo.zip)
And run `bazel build -k [fill in your BEP/BES flags] //...`.

This will yield a build event file that should look similar to this one: [build-event-stream.gz](https://github.com/bazelbuild/bazel/files/2922507/build-event-stream.gz)

### What operating system are you running Bazel on?

```
Linux p 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### What's the output of `bazel info release`?

```
$ bazel info release
release 0.23.0
```

###  Have you found anything relevant by searching the web?

No. :-/

**Comment by EdSchouten** [comment]
Interesting observation is also that for logs like these, Progress nodes may even contain ActionCompletedId's that were already received. In other words, we're sometimes emitting backward references, whereas we only generate forward references for all other messages.

**Comment by EdSchouten** [comment]
Interestingly enough, the model behind ActionCompleted suffers from quadratic explosion as well:

```
$ for i in `seq 0 999`; do
echo hoi '#error fail' > $i.c
done
$ cat BUILD.bazel 
cc_library(
    name = "l",
    srcs = ["%d.c" % i for i in range(1000)],
)

[filegroup(
    name = "a%d" % i,
    srcs = [":l"],
) for i in range(1000)]
$ bazel build --build_event_binary_file=/home/ed/bep7 -k //...
$ ls -lh ~/bep7
-rw-r--r-- 1 ed ed 91M mrt  4 19:18 /home/ed/bep7
```
I guess that altering the build event protocol to emit completed actions in a fashion similar to what we do for OutputGroup/NamedSetOfFiles (through recursively defined sets) would solve this issue and what I reported above in one go.

Is this something that is by any chance already being worked on?

**Comment by aehlig** [comment]
> is BEP supposed to be a DAG or a tree?

It is supposed to be a DAG. For failed actions, we want to report each failed action only once and do so, as soon as possible (i.e., immediately upon the action failing). But we also want to report for each failed target, the independent set of root causes, even though they can overlap.

Concerning the order of the events, the BEP makes the following guarantees.
- Every event, except the first one, has been announced as a child of some previous event before it occurs in the stream.
- The stream ends precisely once the first event is received and all events that where announced also occurred in the stream.
- Whenever an event is mentioned as the root cause of some failed target, the event that is a root cause occurs earlier in the stream.

The reason for the last constraint is to simplify the on-the-fly construction of a dash board. The idea is that events are processed one by one and immediately used to update some storage/database for the build. Events that are not in the successful expansion tree (BuildStarted -> ... -> TargetCompleted (-> Test{Result,Summary})) but only serve to be root causes of failures (in particular ActionExecuted) can immediately be written away as they are, with their Id as unique identifier within this build. Then, when a failed TargetComplete event comes, the web page/database entry/... can be generated immediately, without having dangling references to its root causes. That is the idea behind the order, and also the way, the google-internal dash board processes the events.

**Comment by ulfjack** [comment]
I'm not aware of anyone working on the quadratic # of events problem for actions. By default, Bazel only reports actions if they are root causes, i.e., if they failed, so we did not consider this a serious issue so far. However, that doesn't affect the DAG-ness of the graph, as far as I can tell.

**Comment by ulfjack** [comment]
Let's keep this one.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
