### ISSUE TITLE
@// should be visible from // (and visa versa)

### ISSUE THREAD

**Issue by kchodorow** [bazelbuild/bazel#761]
For example:

```
$ bazel build @//:hello
ERROR: /usr/local/google/home/kchodorow/test/a/BUILD:1:1: Target '//:main.c' is not visible from target '@//:hello'. Check the visibility declaration of the former target if you think the dependency is legitimate.
ERROR: Analysis of target '@//:hello' failed; build aborted.
INFO: Elapsed time: 0.262s
```

BUILD file:

```
cc_binary(
    name = "hello",
    srcs = ["main.c"],
)
```

**Comment by bsilver8192** [comment]
I get a different error with current master, which is fixed by https://bazel-review.googlesource.com/#/c/2590/ (error message in that commit message). After applying that patch, I get the same error you mentioned. https://bazel-review.googlesource.com/#/c/2591 (on top of the other change) makes it work.

**Comment by kchodorow** [comment]
As mentioned, this was fixed by Brian's changes.
