### ISSUE TITLE
Cache collision across linux distributions

### ISSUE THREAD

**Issue by robfig** [bazelbuild/bazel#7702]
### Description of the problem / feature request:

We just started using rules_go widely at my company, and I'm hearing that developers on Linux workstations are getting build errors. The build errors are not reproducible with the remote cache disabled, and the error suggests that a cgo-generated file produced by and specific to our CI system is attempted to be built on a developer workstation. 

Our CI system runs CentOS 7 and is the only thing that populates the build cache.  This particular developer runs Ubuntu 16.04.4 LTS. My guess is that both qualify as linux_amd64 which could be a source of the apparent collision.

Here's the example error message:

```
(19:06:26) ERROR: /home/jsharps/.cache/bazel/_bazel_jsharps/8c279106a568f928c3ee245a89be553d/external/org_golang_x_sys/unix/BUILD.bazel:3:1: undeclared inclusion(s) in rule '@org_golang_x_sys//unix:go_default_library%linux_amd64%cgo_c_lib':
this rule is missing dependency declarations for the following files included by 'external/org_golang_x_sys/unix/linux_amd64_stripped/go_default_library%linux_amd64%cgo_codegen%/_cgo_export.c':
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
Target //gocode/src/corp/lmp/apigateway:go_default_library failed to build
```

This error resolves when disabling the cache, and it also resolves when passing --features=pure to disable cgo. 

Do you have any advice on how to manage a cache that services multiple linux distributions? The only short-term fix I can think of is to disable cache population for Linux Go artifacts. 

This issue was originally opened against rules_go in https://github.com/bazelbuild/rules_go/issues/1988, and the maintainer said it was part of the C++ toolchain and redirected me here.

Thank you!
Rob

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I believe any similar situation to the one described above would reproduce (Ubuntu and CentOS7 machines trying to share Go artifacts built from golang.org/x/sys/unix with the remote cache). Creating a reproducer using Vagrant is a decent amount of work, so I'd like confirmation that it's necessary before doing it.

### What's the output of `bazel info release`?

release 0.23.1

**Comment by buchgr** [comment]
Hi @robfig,

thanks for reporting this! The C++ rules are not well specified enough to safely share a remote cache between different linux distros,  gcc  and libc versions etc. For example, the gcc version does not go into the cache key computation.

In general, our recommended approach to avoid such problems is for a user to provide a unique key for each platform that Bazel can inject into the remote cache key computation. This will allow you to avoid the kind of cache poisoning you are seeing.

The recommended way is to use platforms and to specify the unique key in the `remote_execution_properties` attribute.
```
platform(
    ...
    remote_execution_properties = """
        properties: {
          name: "platform"
          value: "ubuntu1604-gcc704"
        }
        """,
)
```

Note that the `name` and `value` can be arbitrary strings and it's also perfectly valid to have multiple properties instead of just one.

If your project is not using platforms yet, then you can also specify this via a flag `--remote_default_platform_properties`. The flag equivalent to above platform definition would be 
```
--remote_default_platform_properties='properties:{name:"platform" value:"ubuntu1604-gcc704"}'
```

For me, there are two action items for this bug report:
1) Document this on our website
2) Think about a special flag for this purpose so that a user does not have to specify a text protobuf on the command line e.g. `--remote_cache_identifier=ubuntu1604-gcc704` to be equivalent to the above flag.

fyi @agoulti

**Comment by robfig** [comment]
Thank you for the explanation! This is extremely helpful.

**Comment by buchgr** [comment]
I ll take this issue as a motivation to write docs about how to use platforms for remote execution. https://github.com/bazelbuild/bazel/issues/8221
