### ISSUE TITLE
Sandbox interferes with git operation in genrule

### ISSUE THREAD

**Issue by kerrick-lyft** [bazelbuild/bazel#7742]
### Description of the problem:
I am using a Git repository on the local filesystem as a `new_local_repository`. I want to be able to do git operations in a genrule in this repository (e.g. `git rev-parse HEAD`, which gets the current SHA).

When I run git commands, they don't detect the `.git` directory because the sandbox somehow interferes. I know it's related to the sandbox because passing `--spawn_strategy=standalone` fixes the issue.

### Bugs: what's the simplest, easiest way to reproduce this bug?

Run the below commands in a Bash shell on Linux with Bazel installed. To see how it behaves without the sandbox, change the last line to `bazel build :git_sha --spawn_strategy=standalone`.
```
##################################
# Set up external git repository #
##################################
cd $(mktemp -d)
mkdir git_repo
cd git_repo
git init
touch .gitignore
git add .gitignore
git commit -m 'Add .gitignore'

###########################
# Set up Bazel repository #
###########################
cd ..
mkdir bazel_repo
cd bazel_repo

#########################
# Create WORKSPACE file #
#########################
cat > WORKSPACE <<EOF
new_local_repository(
    name = "git_repo",
    path = "$PWD/../git_repo",
    build_file = "git_repo.BUILD",
)
EOF

##############################
# Create git_repo.BUILD file #
##############################
cat > git_repo.BUILD <<"EOF"
filegroup(
    name = "all",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)
EOF

#####################
# Create BUILD file #
#####################
cat > BUILD <<"EOF"
genrule(
    name = "git_sha",
    outs = ["git_sha_file"],
    srcs = ["@git_repo//:all"],
    cmd = """
        ( cd external/git_repo && git rev-parse HEAD ) > $(location git_sha_file)
    """,
)
EOF

###################
# Run bazel build #
###################
bazel build :git_sha
```

### What operating system are you running Bazel on?
Ubuntu 16.04.5

### What's the output of `bazel info release`?
```
INFO: Invocation ID: d168d5da-9898-458e-912e-d9bab81d72b3
release 0.20.0.lyft1
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

My understanding is that we use mostly stock Bazel, with some new features cherry-picked. I'm fairly certain our changes to Bazel do not affect this bug.

###  Have you found anything relevant by searching the web?

Nope.

**Comment by jmmv** [comment]
Thanks for the detailed reproduction steps. Was trivial to copy/paste them.

If you run the build with `--sandbox_debug`, you'll be able to navigate into the `external/git_repo` directory that is created. There you will see that `.git` exists... but all of its contents are symlinks to the original files. I think these symlinks are confusing Git though I haven't investigated further.

Running this same build with `--experimental_use_sandboxfs` works because we expose real files instead of symlinks under that location.

A possible improvement that could resolve this (and that we have been thinking about for a while but for which I cannot find an existing issue) is to make the sandbox code use copy-on-write files if possible instead of symlinks. Unfortunately, that would be subject to the features of the underlying file system, so I'm hesitant about doing this.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
