### ISSUE TITLE
Bad error message in WORKSPACE with incompatible_disallow_load_labels_to_cross_package_boundaries

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7826]
```
$ cat WORKSPACE
load("@foo//:bar.bzl", "x")  # @foo doesn't exist

$ bazel build :all
ERROR: Failed to load Starlark extension '@foo//:bar.bzl'.
It usually happens when the repository is not defined prior to being used.
Maybe repository 'foo' was defined later in your WORKSPACE file?
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.100s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

$ bazel build :all --incompatible_disallow_load_labels_to_cross_package_boundaries
ERROR: cycle detected loading external package '[/tmp/bzl]/[WORKSPACE]'
ERROR: cycles detected during target parsing
INFO: Elapsed time: 0.079s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

cc @haxorz

**Comment by laurentlb** [comment]
My plan is to enable `incompatible_disallow_load_labels_to_cross_package_boundaries` this week, so that would be a regression in terms of error messages for the users.

**Comment by haxorz** [comment]
to be clear, i wouldn't blame this on `--incompatible_disallow_load_labels_to_cross_package_boundaries`.

within your example, a change in that flag's value changes the sort of cycle bazel thinks it in encounters. in the `--incompatible_disallow_load_labels_to_cross_package_boundaries=true` case, it triggers the code initially added by https://github.com/bazelbuild/bazel/commit/36532fced0440d231c43dba3d16be775c9c1fd19#diff-47907aacbced38aa2b57f66e8c14564c. i think the issue is simply that the error message constructed by the code isn't as helpful as it could be. for example, the comment on line 87 of SkylarkModuleCycleReporter.java in that commit is in a sense more useful that the actual error message -- it'd certainly satisfy you here, right?

**Comment by laurentlb** [comment]
Yes. I don't see any test for the `"cycle detected loading"` error message.
I can just remove it and use the previous branch.

**Comment by haxorz** [comment]
i think the error messages constructed in both branches could use improvement. if you're planning to ditch the IS_PACKAGE_LOOKUP branch, then i suggest improving the other one.

my complaint is: it's not obvious that the error is coming from WORKSPACE.

maybe something like s/Failed to load Starlark extension <label of .bzl file>./When evaluating the WORKSPACE file <path to workspace file>, failed to load Starlark extension <label of .bzl file>./
