### ISSUE TITLE
select() doesn't work in remote repositories

### ISSUE THREAD

**Issue by lberki** [bazelbuild/bazel#783]
This is an unfortunate side effect of the weird way we map local labels to actual ones: it's done in `AbstractAttributeMapper#visitLabel()`, which is apparently bypassed by the mechanism `select()` uses.

I tried plugging all the holes, but it looks kinda sisyphean. Maybe we should just bite the bullet and do it in a more principled way (e.g. by doing the conversion where the string is converted to a label, although that would raise questions about how we keep query returning the label that was in the BUILD file originally)

**Comment by lberki** [comment]
@damienmg @ulfjack: this is the next thing to be fixed if we want TensorFlow to work as a remote repository. Kinda embarrassing bug, that.

**Comment by ulfjack** [comment]
That proposed refactoring seems like a rather big change - plug holes first, refactor later?

**Comment by lberki** [comment]
Actually, it's just a few trivial lines of code, plugging the holes is more work.

The issue is that if you do the conversion when parsing the build file, `bazel query` will always return labels with a specified repository (i.e. `@//a/b:c/d`), which would wreak a lot of havoc internally. and it also won't be able to tell the difference between a label that got resolved to a particular repository because it was included in the original label or because the label didn't specify one and but was in that repository.

Maybe a better idea is to tweak `bazel query` to return labels in the default repository if they refer to the repository they are in?

**Comment by ulfjack** [comment]
There are two kinds of labels, absolute labels and relative labels. At this point in time, only @repository//foo:bar is an absolute label, everything else are relative labels (e.g., //foo:bar, :bar). Query should never output relative labels, except making that change would break a lot of preexisting software.

I'd suggest to add a flag to query that makes it output the new absolute labels, and enabling that by default in Bazel. Internally, we'd disable that flag for now, check that all labels are in the main repository, and then only output //foo:bar.

Alternatively, we could make query output relative labels for the main repository, but absolute ones for any other repository. Since we only have one repository internally, that would continue to work, while external users would get a mixture of absolute and relative labels as output. If we go with this approach, I'd still add a flag to query to make it always output absolute labels.

The only question I have is, what's the right absolute label for the main repository? Does the main repository have a name, or does it always use the empty string? @main//foo:bar or @//foo:bar?

**Comment by lberki** [comment]
Well.  I tried... it almost worked. What tripped me up was:
  * I couldn't get the Skylark function `Label` work properly (it uses `Label#parseAbsolute` and doesn't have easy access to the package it is in)
  * We wanted to load packages in the main repository (as opposed to the default repository) which required more tweaks

So I'll just send out the hackish solution for now. Meh. I don't really like your plan because it makes internal and external `query` diverge. I'd much rather make query output repository-relative labels, which is close to what it does now.
