### ISSUE TITLE
Add indentation to struct.to_json()

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#7879]
A user at Google suggests to add a `pretty_print` argument to `to_json` for producing more readable output.

Before:
```
{"expect_response":0,"fuses":{"DEV_ID0":45,"DEV_ID1":74},"info":{},"keyid":1477893011,"timestamp":1551398606}
```

After:
```
{
  "err_response":0,
  "expect_response":0,
  "fuses":{
    "DEV_ID0":45,
    "DEV_ID1":74
  },
  "info":{},
  "keyid":1477893011,
  "timestamp":1551398606
}
```

I'm filing the bug to get more feedback on this feature request.

cc @alandonovan

**Comment by alandonovan** [comment]
Let's not add to the existing to_json method.

Ideally any JSON functionality in Starlark should be completely decoupled from struct, so that you can apply it to any Starlark value of type T where  T = string, int, bool, iterable of T (e.g, tuple, list),  mapping of string to T (e.g. dict), or has-fields of type T (e.g. struct, provider). In that world, the struct.to_json behavior would be provided by a standalone 'encode' function imported from a 'json' module.

Adding spaces and newlines to the output of struct.to_json can be done (asymptotically efficiently) after the fact; indeed, this is how it's implemented in the Go standard library: https://golang.org/src/encoding/json/encode.go?s=6923:6995#L165. So this argues for a json.indent function in the json module that adds indentation to a JSON string already produced by json.encode(x) or the (legacy) struct.to_json method.

**Comment by alandonovan** [comment]
Please take a look at https://github.com/google/starlark-go/pull/179 for a simple implementation of the idea just described.

**Comment by brandjon** [comment]
The `json` module is implemented and has an `indent` function. We can use a separate issue to track deprecation of `struct.to_json()`.
