### ISSUE TITLE
pkg_deb should support a way of embedding version into control fields

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#7886]
### Description of the problem / feature request:

Cannot add `pkg_deb`'s version from `version_file` into Debian control field (i.e. `Depends:`)

### Feature requests: what underlying problem are you trying to solve with this feature?

I have several dependent packages (say, `A` and `B` depending on `A`) which I'm building at once. I want to specify dependency from `B` (of version `$version`) to `A` (of same `$version`). However, as I'm using `version_file` to specify version, I'm not able to specify `depends` = [`A (=<$version — how would I get it?>)`]

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_deb")

pkg_deb(package = "A", version_file = "//:VERSION")
pkg_deb(package = "B", version_file = "//:VERSION", depends=["A (=version)"]) # <-- how can I make `A` the same version as in `//:VERSION` here?
```

### What operating system are you running Bazel on?

macOS Mojave 10.14.4

### What's the output of `bazel info release`?

`release 0.23.0`

###  Have you found anything relevant by searching the web?

#7474 is probably relevant

**Comment by aiuto** [comment]
Is this really EngProd or RulesServer?  That's a trick question, all package building should be a separate project and not part of Bazel itself.

That aside. I think the least cost way to get there is to add a depends_file attribute. Implement just like version/version_file.

- the user still needs a genrule to get the depends file from VERSION, so maybe ugly.
- we can mitigate that by creating a rule set that does easy template expansion. Imagine 
 ```
expand_template(
        name="x",
        srcs = ["//:VERSION"],
        template = "A ($(content //:VERSION))" 
     )
```
$(content label) is like the $(location label) syntax in a genrule, but expands the content.
someone could spend months making this. It would be a huge boon for cross platform tooling,
because we would not have to assume a whole bunch of unix tools on windows.

I would be happy to review a PR for adding @depends_file. I'm not going to have a lot of time to do it myself 

I would also be happy to review a proposal to move packaging rules to a new repo. They need a lot of work for performance and portability. We could innovate better if this was shared by the community rather than part of core bazel.
