### ISSUE TITLE
Toggle "exclusive" tag from command line / force parallel test execution

### ISSUE THREAD

**Issue by RNabel** [bazelbuild/bazel#7911]
### Description of the problem / feature request:

It is ( / seems to be) impossible to force parallel execution of tests marked as "exclusive", i.e. it is impossible to either a) override the `"exclusive"` tag from the command line, or b) to use a `select()` construct on the `tags` parameters (see https://github.com/bazelbuild/bazel/issues/2971) . 

### Feature requests: what underlying problem are you trying to solve with this feature?

The lack of configurability of the exclusive test execution policy.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

N/A

### What operating system are you running Bazel on?

Linux, Windows, macOS. 

### What's the output of `bazel info release`?

0.23.1

### Any other information, logs, or outputs that you want to share?

Problem context:
 - Tests are executed on different platforms,
 - On Linux the tests are containerized and can therefore be executed in parallel

A possible workaround: use a combination of `--jobs` and `--test_tag_filter` in multiple bazel invocations.

**Comment by gregestren** [comment]
This looks more doable than the generic `tags` request from https://github.com/bazelbuild/bazel/issues/2971, since all calls on `exclusive` happen at a point where we can properly resolve the `select()`.

The big challenge with this is the syntax though. `exclusive` is just a value in `tags` so we'd have to either break that out into its own attribute or only allow `select` on `tags` that only set `exclusive`. I guess the latter is manageable but would have to be designed carefully. And one could argue it's confusing to have "partially configurable attributes: where when a `select` is or isn't allowed isn't immediately obvious.

**Comment by ittaiz** [comment]
+1 to partially configurable attributes being confusing.
Would Bazel fail with a clear message if one uses select on tags which have other values?

**Comment by gregestren** [comment]
I'd imagine a clear message explaining pretty much reality: "select() isn't allowed on attribute `tags` if it contains any value that's not `exclusive`", or something like that.

... okay, out of curiosity I tried to make `tags` fully configurable. It looks like it's fine to mix `select()` with `exclusive`, `local`, and `external`. But not `manual` and other values described at https://docs.bazel.build/versions/master/be/common-definitions.html#common.tags.

But this looks like the biggest problem: https://github.com/bazelbuild/bazel/blob/1f684e1b87cd8881a0a4b33e86ba66743e32d674/src/main/java/com/google/devtools/build/lib/packages/TestTargetUtils.java#L113-L116

This doesn't look like code that can handle `select()` and it uses the *entire* value of `tags` to do sorting which gets fed up into other code that doesn't look `select`-friendly. This is a big blocker for both this and https://github.com/bazelbuild/bazel/issues/2971 unless someone can figure out how to untangle this code. `#testMatchesFilters` above looks similarly delicate.

**Comment by GMNGeoffrey** [comment]
I'd similarly like to see the "local" attribute be configurable. This already exists as a separate non-configurable attribute. I assume because it gets mapped to being a tag

**Comment by glukasiknuro** [comment]
Below commit allows parallel execution of exclusive tests, given that instead of using `exclusive`, users are using `exclusive:X` tag, where X specifies some resource, like GPU:
  https://github.com/glukasiknuro/bazel/commit/cfc5be1e6e4d4e6da0e605748e14c2a1b137ef8c

I may try to merge it into main repo, although it's a little hacky way of achieving that instead of being able to specify that remote execution is able to support some form of exclusivity.

**Comment by GMNGeoffrey** [comment]
At least my request to make "local" configurable is still a thing. Not sure if that should be moved to a different issue. Making attributes that historically have been mapped to tags configurable seems generally useful.

**Comment by GMNGeoffrey** [comment]
Also, your teams are secret to the organization and not taggable, so it's not really helpful to tell people to reach out to them
