### ISSUE TITLE
Java error during installation

### ISSUE THREAD

**Issue by Milerius** [bazelbuild/bazel#7934]
As usual when I install a java application, Exception.

Following this tutorial: https://docs.bazel.build/versions/master/install.html

(chmod +x bazel-<version>-installer-linux-x86_64.sh
./bazel-<version>-installer-linux-x86_64.sh --user)

(ubuntu guide)

Cherrypicks:
+ c56c489119e6587975964c44ceb9e429ad950736: Wrap StatusRuntimeExceptions from GrpcRemoteCache

## Build information
   - [Commit](https://github.com/bazelbuild/bazel/commit/e2e243e)
Uncompressing......Extracting Bazel installation...
Error: LinkageError occurred while loading main class com.google.devtools.build.lib.bazel.Bazel
	java.lang.ExceptionInInitializerError: null

**Comment by iirina** [comment]
Please re-open with more error details.

**Comment by ddavout** [comment]
I am willing to give more details, please tell me how to get them : I am new to Java

## Build information
   - [Commit](https://github.com/bazelbuild/bazel/commit/9c257df)
Uncompressing......Extracting Bazel installation...
Error: LinkageError occurred while loading main class com.google.devtools.build.lib.bazel.Bazel
	java.lang.ExceptionInInitializerError: null

Thanks

**Comment by philwo** [comment]
Never saw it. I think the binary that was built is broken somehow. :|

Can you please give information about:
- your operating system (include the output of `uname -a`),
- the JDK on your system (what does `echo $JAVA_HOME` print and what does `java -version` and `javac -version` print?),
- the Bazel version that you used to build your custom Bazel (output of `bazel version`)
- and the steps (command lines) that you used to build your custom Bazel binary (ideally starting from `git clone https://github.com/bazelbuild/bazel.git` so that I can follow along)?
