### ISSUE TITLE
repository_rule with quiet=false breaks output of bazel query

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#8077]
Users expect that bazel query output can be piped to other commands, e.g. for Angular releases we do something like

`bazel query --output=label 'kind(".*_package", //packages/...)' | xargs bazel build`

However if this runs a repository rule that has some logging output (doesn't use quiet=True to hide the stdout from actions it runs) then this output appears in the bazel query output in a way that can't be separated from the query result.

Originally filed at https://github.com/bazelbuild/rules_nodejs/issues/583 where you can see an end-user affected by it.

**Comment by aiuto** [comment]
In the general case, I don't think we can solve the "rule is not quiet" case.  Some tools which are otherwise useful and reasonable are going to spew to stdout.

Rather than fighting that uphill battle, what if bazel query had a '-o' (--output_file) parameter to write output to a designated file. 
 
(bazel query -o /tmp/q.out --output=label 'kind(".*_package", //packages/...)'  >/dev/null 2>&1; cat /tmp/q.out) | xargs bazel build

But if you want to use xargs, then we really need to support the -print0 output that find does, so that we are not back at this in few months with a bug for not supporting space in paths.

I should split this into a few bugs. For now, if it is specifically a repository rule, we can let the external deps team take a look first.
