### ISSUE TITLE
incompatible_depset_for_libraries_to_link_getter: use depsets in linking_context in C++ Starlark API

### ISSUE THREAD

**Issue by oquenchil** [bazelbuild/bazel#8118]
Flag: --incompatible_depset_for_libraries_to_link_getter
Available since: 0.26 (June 2019 release)
Will be flipped in: 0.27 (September 2019 release)
Tracking issue: #8118

linking_context.libraries_to_link will return a depset instead of a list. To make code compatible with the list and the depset, simply check whether the value returned from linking_context.libraries_to_link has the attribute "to_list".

```
libraries_to_link = linking_context.libraries_to_link
if hasattr(libraries_to_link, "to_list"):
   # It's a depset
else:
  # It's a list
```

**Comment by mboes** [comment]
How will I be able to use the resulting depset? Will I be able to pass it directly as an input to `ctx.actions.run()`? If not, then I will have to traverse the depset in order to extract e.g. all the dynamic libraries and feed that as the inputs. Traversing the depset will be a performance pessimization.

I often need the dynamic libraries for purposes other than feeding them to a linker, e.g. to provide them to an interpreter for code that depends on native libraries.

**Comment by benjaminp** [comment]
See #7626. It's already a depset internal, and the current API is flattening the depset every time its referenced.

**Comment by mboes** [comment]
Sure, but my question is what about the future? Will there be a way to use the depset without flattening it to eagerly? Internally, `LibrariesToLink` is something like `depset(LibraryToLink)` AFAIU. But the `inputs` argument to `ctx.actions.run()` is expected to be of type `depset(File)`. So how will this work? Will I be expected to convert `depset(LibraryToLink)` to `depset(File)`?
