### ISSUE TITLE
Better link options for cc_library and cc_binary

### ISSUE THREAD

**Issue by mlh0101** [bazelbuild/bazel#8176]
### Description of the feature request:
need cc_library() to support "linkshared" option.
need cc_binary() to support "hdrs" option

### Feature requests: what underlying problem are you trying to solve with this feature?

>Now, it is hard for cc_library to build sharde libraries only. And headers now are together with “.c”, which is hard to understand.

**Comment by adam-azarchs** [comment]
`hrds` in `cc_library` are to tell bazel about files which other `cc_*` targets which link against the library will need to access at build time.  Since you shouldn't be linking against a binary, there's no point in having a `hdrs` attribute.  Most of the time, what you should probably be doing is to have one or more `cc_library` targets with the `hdrs` and have the `cc_binary` depend on those libraries - you'll get better build incrementalism that way, too.

As for having a `linkshared` argument for cc_library, I'm not quite clear on what the point is?  Right now, if you specify `linkstatic=False` for a `cc_binary`, it'll link against shared library output, but if you specify `linkstatic=True` it'll link against the static output.  Is the concern here the the time it takes to make the `.a` file?  That's very fast (especially compared to the time it takes to link a `.so`), and I'm not even sure bazel will do it at all if no explicitly requested build target requires it.

**Comment by mlh0101** [comment]
As for the first request, when i use cc_library(), and add a arm-toolchain on it,  only ".a" is linked, there is no ".so".
As for the second request, when i want to build ".obj" target, only cc_binary() can be used, but there is no hdrs option.

**Comment by aiuto** [comment]
I would love to see someone do a good requirements document for linkage options in cc_library
Beyond this basic request there are a few considerations I know of. Other can certainly find more.

- linkshared must be configurable (that is, you can use a select() to set it). This is important because the nature of your top-level target can determine how a deep dependent should be linked. For example, if you have an LGPL library in an end user application you would need to link it shared, but if it is a server that you run on your own hardware and do not publish, then you can link static. IANAL, so don't quote me on that interpretation.
- cc_library should also have the ability to become a Framework. This, of course, only works if the target platform is {mac,i,tv}os and you already want shared linkage. Again, the top level application wants to set something in configuration which tweaks how the dependency is built.
- cc_binary for producing a shared library is something of a hack.  We could consider it a cc_library, but with a feature that says - actually link all my dependencies together into one object, and then become a shared_library.
- there is some need for a cc_interface_library. This would have `hdrs`, to define the interface and a default implementation, but a cc_binary that (transitively) depends the cc_interface_library should be able to provide their own implementation. The easiest example would be. swapping out malloc, but the need arises when applications need to provide app-specific behaviors in third party libraries, when those libraries were not built with any sort of capability injection framework.

**Comment by aiuto** [comment]
See #4135

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
