### ISSUE TITLE
Feature: pipe bazel compiled artifact paths to other shell commands

### ISSUE THREAD

**Issue by perezd** [bazelbuild/bazel#8177]
### Description of the problem / feature request:

I'd love a way to pipe output paths from bazel build commands to other shell commands as input.

### Feature requests: what underlying problem are you trying to solve with this feature?

So imagine I have a target ":foo" that outputs a file to bazel-bin, normally bazel prints thet bazel-bin path of the compiled artifact, but often I want to do something with it in bash like cat the output or grep.

It'd be really cool if I could somehow do this:

```
bazel build :foo | cat 
```
or any other bash command. I imagine in order to do that a special flag would need to be set to signal the correct kind of output should be sent to STDOUT, specifically the paths of artifacts that were built, etc.

**Comment by adam-azarchs** [comment]
Build output artifacts are currently output to standard error.  The problem is that a bunch of other stuff is, too, and none of it is formatted in a helpfully machine-readable format.

A great example use-case for this would be if you have for example a tarball package build target you want a CI system to archive, e.g.
```
bazel build --stamp -c opt :tarball | xargs upload_archive
```
I could imagine other ways of providing this functionality, such as adding a `--output_manifest` flag or something like that.

**Comment by perezd** [comment]
Yes! This is exactly the kind of use cases I'm contemplating.

**Comment by pcj** [comment]
I've thought about implementing this in https://github.com/bzl-io/bzl.  Once you have the names of the output files (from the build events), it's pretty straightforward to read the file(s) and pipe the content to stdout.  Maybe something like `bazel pipe :tarball | xargs upload_archive`

**Comment by perezd** [comment]
:/

**Comment by laurentlb** [comment]
You can create a new target and then do `bazel run :foo` or `bazel run :foo | cat`

Related: https://docs.bazel.build/versions/3.1.0/skylark/tutorial-custom-verbs.html
