### ISSUE TITLE
Store remote metadata in the on disk action cache

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8248]
This is part of #6862.

The persistent action cache stores the state of Bazel's output base. It does not know about remotely stored files. We need to extend it to do so.

```
$ bazel build :foo --experimental_remote_download_outputs=minimal
$ bazel shutdown
# This will be clean build, because the metadata from the previous build are
# not yet properly persisted to disk
$ bazel build :foo --experimental_remote_download_outputs=minimal
```

**Comment by moroten** [comment]
This problem makes up to several minutes for me. Any updates on priority?

**Comment by buchgr** [comment]
No updates.

**Comment by moroten** [comment]
I saw the related #10233 which talks about refactoring `findMissingBlobs`. Is there more difficulties relating to `--experimental_inmemory_jdeps_files` and `--experimental_inmemory_dotd_files` that needs to be considered? Would the right way to solve this issue be to implement `--disk_cache` support in combination with remote execution or should there be another flag involved?

I do see this phenomenon also when the analysis cache is discarded due to changing configuration flags, even if the server is still alive.

**Comment by sohaibiftikhar** [comment]
@buchgr I'd like to work on this. Any pointers to get started?

**Comment by coeuvre** [comment]
This can be enabled by setting `--experimental_action_cache_store_output_metadata`.
