### ISSUE TITLE
query labels includes empty

### ISSUE THREAD

**Issue by bricerebsamen** [bazelbuild/bazel#825]
`bazel query 'labels(srcs,...)'` returns all the files listed in the srcs attribute of all the targets. But `bazel query 'labels(includes,...)'` returns nothing.

I'm trying to get the list of include directories for my cc rules.

```
bazel query 'labels(srcs, kind("cc_.* rule", ...)) union labels(hdrs, kind("cc_.* rule", ...))'
```
gives me all the headers and sources :smile:

**Comment by bricerebsamen** [comment]
`labels(copts,...)` also returns nothing.

**Comment by lberki** [comment]
This is WAI, at least as far as the query results are concerned: the value of the `includes` attribute is a list of strings and not labels.

What do you want to use the list of `-I` directories for?

**Comment by bricerebsamen** [comment]
`labels(srcs` returns the list of strings that make all the sources, so I thought `labels(includes` should do the same.

I want it to build my project config for my IDE (QtCreator).

**Comment by lberki** [comment]
`bazel query` is not the best tool for these things, because it doesn't really have access to all the data IDEs need. A better mechanism is to use Aspects, using which you can traverse the dependency graph and peek at analysis-time information. I don't think we have documentation at the moment, but here is an aspect we use to generate IntelliJ projects:

https://github.com/bazelbuild/bazel/blob/master/src/test/java/com/google/devtools/build/lib/ideinfo/intellij_info.bzl

You'll need to invoke Bazel with the undocumented (and prone to change) option `--aspects` as `--aspects=path/to/bzl/file%name_of_aspect` and probably with `--output_groups=<the output group your aspect produces>`. 

@dslomov

**Comment by bricerebsamen** [comment]
for QtCreator, I need the list of files, the list of includes (`-I` options), and the list of defines (`-D` options). These are all in the BUILD files. I used bazel query to get the list of c++ source files (minus the generated files from protobuf, etc.). `bazel query` does not have that info?

I'll look into Aspects but from the example you gave me that looks bad.

**Comment by lberki** [comment]
What's bad about the example?

BUILD files contain only some of this data. The CROSSTOOL file can also contain compiler options (including include directories and defines), which would not be reflected in the output of `blaze query`. 

If you for some reason don't like aspects, here are a few alternatives:
* Use `extra_action` (http://bazel.io/docs/be/extra-actions.html) to find out the command lines Bazel executed
* Use `bazel build -s` to make Bazel print the compiler command lines on stderr
* Use `bazel query --output=xml` (or `--output=proto`) to get the dependencies in a machine-readable format, including the `includes` attribute

**Comment by bricerebsamen** [comment]
By "bad" I mean that my prospects at getting this to work look bad since the aspects example is quite involved.

**Comment by lberki** [comment]
Yeah, it's much more complex than `bazel query 'deps(...)' | whatever`. Sorry about that... 

In the meantime, I'll close this bug since Bazel actually works as specified and there are at least four ways to get closer to your goal.
