### ISSUE TITLE
Remote Builds without the Bytes should support remote output eviction

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8250]
This is part of #6862

A remote caching or execution system must not evict outputs during a build. That is an output of action 1 must still be available to action 1000. Before this feature Bazel would simply reupload an output that's been evicted from the remote system, but this is no longer possible.

**Comment by phb** [comment]
I'm trying to debug a situation where I keep getting the
"java.io.IOException: Failed to fetch file with hash '0fe19df8b8f8eb5f545f50e11f958bf37d27ab7da5c260a9bd2bc0ff6fb760a4' because it does not exist remotely. --experimental_remote_outputs=minimal does not work if your remote cache evicts files during builds."
message. 

I had my cache misconfigured when I started experimenting with this feature and I lost (evicted) a few keys. The message above seems to indicate that restarting a build should be enough to get the missing keys to be uploaded, but I can't get that to work, ie, restarting the build (from scratch or not) always fails the same way.

**Comment by buchgr** [comment]
@phb it depends on your cache. If the remote cache in general ensures that an action is only served as a cache hit if all outputs exist then restarting the build should do the trick. However, if you use GCS or nginx as a cache that does not understand the relationship between actions and outputs then restarting won't help.

**Comment by phb** [comment]
@buchgr That's great to know. I'm assuming my cache falls in the dumb-category (I'm using the https://github.com/Asana/bazels3cache, waiting patiently for native support https://github.com/bazelbuild/bazel/pull/4889 if that will ever happen)
What cache implementations are aware of the output relationships?

**Comment by keith** [comment]
Related conversation: https://github.com/bazelbuild/bazel/issues/8508#issuecomment-509755175

**Comment by thii** [comment]
If I’m understanding correctly, does this mean that Remote Builds without the Byes still works with a read-only cache? (The cache is populated elsewhere, and we don’t delete anything)

**Comment by axeluhlig** [comment]
Hi @coeuvre any update on this issue? It's blocking us from using builds without the Bytes.

**Comment by coeuvre** [comment]
Still working on #12665. Maybe I can find time to work on this in Q2.

**Comment by axeluhlig** [comment]
Cool, thanks for the update!

**Comment by illicitonion** [comment]
I had a go at implementing some support for this, specifically by allowing rewinding in more places, but ran into an issue I'd love to get some feedback on.

The issue I was trying to address was runfiles needing to be uploaded after eviction, having not been downloaded. A simple repro is to make a `go_binary` rule, build it remotely with `--remote_download_minimal`, flush the remote storage, edit the file being built as the `go_binary`, and build remotely again. This should result in a failure because Bazel tries to read one of the compiler helpers from the runfiles of the action, and throws a `FileNotFoundException` because it was never downloaded.

The shape of the fixed I tried to put together was:
1. [When building the Merkel tree](https://github.com/bazelbuild/bazel/blob/6b33bdb1e22514304c0e35ce8e067f2175685245/src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java#L254-L255) if an input was a `DerivedArtifact`, store that `DerivedArtifact` in the `MerkelTree`.
2. If [the bulk upload](https://github.com/bazelbuild/bazel/blob/6b33bdb1e22514304c0e35ce8e067f2175685245/src/main/java/com/google/devtools/build/lib/remote/RemoteSpawnRunner.java#L359) fails with only `FileNotFoundException`s for artifacts with a known `DerivedArtifact`, throw a `LostInputsExecException` instead of a `BulkTransferException`.
3. Allow the [`RemoteRetrier` to propagate `ExecExceptions`](https://github.com/bazelbuild/bazel/blob/6b33bdb1e22514304c0e35ce8e067f2175685245/src/main/java/com/google/devtools/build/lib/remote/RemoteRetrier.java#L126-L131).

This appeared to be working fine - the `ActionRewindingStrategy` kicked in and put together a `RewindPlan`, but this leads to a bazel crash because of graph inconsistency:
```
java.lang.IllegalStateException: Unexpected inconsistency: ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//:bin, config=BuildConfigurationValue.Key[9b3dc679644997acb2eb31acfb64ec07bfc5831a68166d756e3e8abdbcd3a8e4]}, actionIndex=0}, [ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=@go_sdk_linux//:builder, config=BuildConfigurationValue.Key[2646f9c701b7ccc168560c0ef59608649f3ee184a5d3b8d438d5cede85e70cc4]}, actionIndex=1}], PARENT_FORCE_REBUILD_OF_CHILD
	at com.google.devtools.build.skyframe.GraphInconsistencyReceiver.lambda$static$0(GraphInconsistencyReceiver.java:41)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator.maybeHandleRestart(AbstractParallelEvaluator.java:872)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator.access$400(AbstractParallelEvaluator.java:71)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:570)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
ERRO exit status 37                               
```

I couldn't see any `GraphInconsistencyReciever`s that would allow for this rewinding to happen - any pointers for how to tell SkyFrame that rewinding is ok, or how to handle this, would be much appreciated...

/cc @coeuvre @janakdr

**Comment by illicitonion** [comment]
Thanks - as far as I can tell there's not much documentation for this corner, would it simply have to do nothing in `noteInconsistencyAndMaybeThrow` (and return `true` for `restartPermitted`), or would it need to do something more effect-ful?

**Comment by janakdr** [comment]
That's correct. Ideally you'd check the Inconsistency reason: "missing
children" inconsistencies are not expected solely from rewinding, but it's
fine to ignore everything if you're experimenting.

**Comment by coeuvre** [comment]
I have drafted a [design doc](https://docs.google.com/document/d/1wM61xufcMS5W0LQ0ar5JBREiN9zKfgu6AnHVD7BSkR4/edit) and work can be tracked at https://github.com/bazelbuild/bazel/pull/16660.

**Comment by coeuvre** [comment]
Remote output eviction is supported by Bazel@HEAD and will be supported by future releases (Bazel 7+):
1. Bazel can clear staled state that prevents you from doing an increment build if remote output eviction happened during this build.
2. `--experimental_remote_cache_eviction_retries` can be used to ask Bazel automatically retry the build upon remote cache eviction.
3. `--experimental_remote_cache_ttl` can be used to tell Bazel the lifetime of a cache entry in the remote cache so that Bazel knows when to invalidate local reference. The default value is `3h`.
4. `--experimental_remote_cache_lease_extension` can be used to ask Bazel periodically refresh the TTL of cache entries that are still required by Bazel if your remote cache evict entries based on LRU strategy.
