### ISSUE TITLE
Rework bazel using golang

### ISSUE THREAD

**Issue by HuKeping** [bazelbuild/bazel#8257]
Is there any plan that rework the whole bazel project with golang?

**Comment by indrgun** [comment]
@HuKeping What is the advantage of rewriting bazel in golang?

**Comment by HuKeping** [comment]
Java is dead, long live go

**Comment by laurentlb** [comment]
Short answer is: No.

Do you have specific issues with our implementation? In the past, some users complained about having to install a JVM, and we fixed that. There were also issues about the binary size, but it improved a lot. If you have other problems, please let us know!

**Comment by w4-hanggi** [comment]
@laurentlb It looks nice, but can it run without JDK?

**Comment by laurentlb** [comment]
You don't need to install a JDK to run Bazel (it's embedded in the binary, so it's just an implementation detail).

**Comment by zozo123** [comment]
Since this was closed in 2019, one thing that has changed is the maturity of LLM-assisted large-scale refactoring and translation. I understand that a language-preference rewrite is not actionable by itself, and the core maintenance / compatibility risks do not disappear just because translation is easier.

Would maintainers be open to reopening this, or preferably starting a fresh design discussion, if it were framed around concrete goals and evidence rather than “rewrite Bazel in Go”? For example:

- a small prototype that ports one isolated Bazel subsystem to Go;
- benchmark data for startup time, memory, binary/distribution size, and build throughput;
- a compatibility plan for Starlark semantics, remote execution, repository rules, and existing Java/C++ integration points;
- a long-term maintainership plan.

If the answer is still “no” for product-direction or maintenance reasons, that is useful signal too; then the better path is probably to file narrow issues for specific pain points instead of reopening this broad proposal.

**Comment by meisterT** [comment]
I think the best course of action here is to open a new discussion (https://github.com/bazelbuild/bazel/discussions) and my recommendation is focus less on the choice of language, but mostly on the changes people would like to see to Bazel to make a port feasible.
