### ISSUE TITLE
Produced source JARs don't correspond to files in class JAR

### ISSUE THREAD

**Issue by vmax** [bazelbuild/bazel#8277]
### Description of the problem / feature request:

Source JARs produced currently replicate the structure of source files used to build the class JAR. Example:
```
ghost:c vmax$ bazel build //:libanotherlib-src.jar
…
Target //:libanotherlib-src.jar up-to-date:
  bazel-bin/libanotherlib-src.jar
```

```
ghost:c vmax$ jar tf bazel-bin/libanotherlib-src.jar
META-INF/
META-INF/MANIFEST.MF
Anotherlib.java
```

Given this example, I would expect source JAR to contain structure similar to the following:
```
META-INF/
META-INF/MANIFEST.MF
com/
com/smth/
com/smth/Anotherlib.java
```

### Feature requests: what underlying problem are you trying to solve with this feature?

We need produced source JARs to have the same structure as class files inside class JAR so that:
- produced source JARs could be deployed to Maven Central
- "Go to source" functionality works with IntelliJ IDEA + Bazel plugin

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
ghost:c vmax$ cat BUILD 
java_library(
    name = "anotherlib",
    srcs = ["Anotherlib.java"],
    visibility = ["//visibility:public"]
)
```

```
ghost:c vmax$ cat AnotherLib.java 
package com.smth;

public class Anotherlib {
    public Anotherlib() {
        System.err.println("ctor");
    }
}
```

### What operating system are you running Bazel on?

macOS Mojave 10.14.4

### What's the output of `bazel info release`?

release 0.25.0

###  Have you found anything relevant by searching the web?

—

**Comment by davido** [comment]
Have you tried to create `java/com/smth` directory, put there your `Anotherlib.java` and say this in BUILD file:

```
java_library(
    name = "anotherlib",
    srcs = ["java/com/smth/Anotherlib.java"],
    visibility = ["//visibility:public"]
)
```

Check Gerrit Code Review: [1]. We do it like I described and we put JARs and source jar created by Bazel to Maven Central:

```
  $ bazel build java/com/google/gerrit/common:server
```

And check the structure of the resulted JAR an source-JAR.

[1] https://github.com/GerritCodeReview/gerrit/blob/master/java/com/google/gerrit/common/BUILD

**Comment by vmax** [comment]
@davido thank you for your suggestion! however, my intention is to preserve the directory structure we currently have where directories represent logical separation of modules and not necessarily java packaging

**Comment by vmax** [comment]
We were able to resolve it by wrapping `singlejar` in a Java wrapper ([src](https://github.com/graknlabs/build-tools/blob/3fd3f7c48104f5d72ada6efe38ddc6ea7fc14d20/bazel/SingleJar.java)) and using custom `java_toolchain` ([src](https://github.com/graknlabs/build-tools/blob/3fd3f7c48104f5d72ada6efe38ddc6ea7fc14d20/bazel/BUILD#L38-L60))

**Comment by vmax** [comment]
We've addressed it by using a workaround on plugin level: bazelbuild/intellij#1206, bazelbuild/intellij#1207

**Comment by davido** [comment]
@vmax Can you re-open this issue? Alternatively, I can open a new issue for source path normalization in created "-src.jar" in `java_library` rule.

I am facing a similar problem, when trying to migrate existing project to Bazel an I think, that this should be fixed in Bazel.

Consider this directory structure (that I cannot change):

<workspace_root>/foo/org/example/app/Test.java

The build file is put in `foo` directory. The `java_library` rule is:

```python
java_library(
  name = "foo",
  srcs = glob(["org/**/*.java"]),
)
```

When building `foo` the java library is correct, but that libfoo-src.jar is wrong: it has this entry:

"foo/org/example/app/Test.java"
instead
"foo/org/example/app/Test.java"

Note, that if I rename the foo directory to one of these directories:

- java
- src
- src/main/java

then the "foo" directory is stripped. One approach to fix that would be to provide `source_strip_prefix` in `java_library` rule or apply `resource_strip_prefix` on path normalization in "-src.jar" file.

One workaround, that can be done now, is to create `srcjar` manually and provide it as source to the `java_library` rule. Using `java_binary`, the sources can be provided as `resources` and the path can be normalized using `resource_strip_prefix=foo`, so something like:

```python
# TODO(davido): Remove that hack to create source package without the wrong path prefix.
java_binary(
    name = "foo-src-binary",
    main_class = "Dummy.java",
    resources = glob(["org/**/*.java"]),
    resource_strip_prefix = "foo",
)

# TODO(davido): Remove that hack to rename the java_binary source with ".jar" suffit
# to zip with ".srcjar" suffix so that java_library can accept it.
genrule2(
    name = "foo-src",
    cmd = "mv $< $@",
    srcs = [":foo-src-binary_deploy.jar"],
    outs = ["foo.srcjar"],
)

java_library(
    name = "foo",
    srcs = [":foo-src"],
)
```

**Comment by vmax** [comment]
@davido I think you should open another one: you might have another reasons for wanting to have a correct source JAR and will then be able to convince Bazel team to look at them 🙂
