### ISSUE TITLE
Bazel CI: Flipping --incompatible_list_based_execution_strategy_selection broke RBE build

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#8372]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/977#_
The RBE related jobs are failing due to 37033338332c0bd3069ff7ac93d69432787a4aed

Remote execution: https://buildkite.com/bazel/culprit-finder/builds/154
Rules_nodejs (RBE): https://buildkite.com/bazel/culprit-finder/builds/156

/cc @ishikhman @buchgr Please help fixing the downstream projects.

**Comment by ishikhman** [comment]
thanks @meteorcloudy, I'll have a closer look on Monday. 

**Notes for a fix**:
So far it seems that those builds were explicitly requesting `--spawn_strategy=remote` which was by default falling back to a local execution. With a flag flip in order to get the same behaviour we either do not need to specify `--spawn_strategy` at all or make it `--spawn_strategy=remote,local`

**Comment by meteorcloudy** [comment]
@ishikhman Thanks for the notes!
Maybe to be compatible with Bazel 0.25.2, we should use `--spawn_strategy=remote,local` instead of removing the flag?
FYI @philwo 
https://github.com/bazelbuild/continuous-integration/blob/d00107eaef8712316a1521f810c90eeeaba382e6/buildkite/bazelci.py#L1168

**Comment by hlopko** [comment]
Friendly ping :) Our downstream pipeline is red because of this (https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/987). If you could file issues against those projects with more context that would be great. I can then disable these projects on downstream to get a happy green build while waiting for fixes.

Thank you so much!

**Comment by meteorcloudy** [comment]
Looks like we should fix the flag in [bazelci.py](https://github.com/bazelbuild/continuous-integration/blob/d00107eaef8712316a1521f810c90eeeaba382e6/buildkite/bazelci.py#L1168) instead of from downstream projects. I'll send a fix.

**Comment by meteorcloudy** [comment]
@ishikhman @buchgr Can you help fixing the Remote Execution job ?
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/989#c020a9d7-2121-46d7-82c6-d073f341e24b

**Comment by ishikhman** [comment]
@meteorcloudy sure, I'm on it
