### ISSUE TITLE
Enable sandboxfs on a per-target basis

### ISSUE THREAD

**Issue by Globegitter** [bazelbuild/bazel#8394]
### Description of the feature request:

It would be great to be able to configure the use of sandboxfs on a per-target basis rather than an all-in or nothing approach. I could see this being implemented either via tags/execution_requirements or by using a regex flag like `--runs_per_test` where one can specifiy which targets to build using sandboxf. But maybe there are further options.

### Feature requests: what underlying problem are you trying to solve with this feature?

While sandboxfs is great and has a lot more potential it seems to not quite work with all builds yet, or rather uncover non-hermetic behaviour in them and for some it seems to makes things slower than the normal sandbox. And for some builds (especially in the NodeJS world) it has the potential to make things much better as a lot of tools there struggle to preserve symlinks. So it would be great to be able to benefit from sandboxfs already today for the targets that work with it / see improvements through it and one can incrementally adopt it until (hopefully) all remaining issues are ironed out. 

Maybe it could also help figuring out for which types of build it has better performance than the normal sandbox by being able to turn it on only for some targets.

### What operating system are you running Bazel on?

Elementary OS 5 (Ubuntu 18.04)

### What's the output of `bazel info release`?

release 0.26.0rc4

###  Have you found anything relevant by searching the web?

No

cc @jmmv

**Comment by jmmv** [comment]
This is an interesting proposal. Actually, something similar crossed my mind a while ago: using sandboxfs for some actions only, but basing such decision on the number of inputs of the action.

The reason I didn't pursue that yet is because sandboxfs changes the semantics of sandboxing (from symlinks to real files) so switching back and forth could cause hard-to-diagnose build failures. This would become a smaller problem if we made Bazel use cow files instead of symlinks for regular sandboxing, as then sandboxfs would become just a performance trick. But we haven't done that yet, and whether that's doable depends on the actual file systems in use.

**Comment by Globegitter** [comment]
An automatic selection as well as cow files do indeed sound very interesting improvements for sandboxing. Manual selection of some sort seems like a good stepping stone towards that, especially if a cow file sandbox is still a bit away.

**Comment by jmmv** [comment]
Will make this a dup of #6194, as that bug tracks per-target configuration of sandbox settings.
