### ISSUE TITLE
Bazel's macOS sandbox allows write access to entire output root.

### ISSUE THREAD

**Issue by philwo** [bazelbuild/bazel#8407]
### Description of the problem / feature request:

Bazel's macOS sandbox allows write access to `/private/var/tmp`.
Bazel's default output user root is `/private/var/tmp/_bazel_$username`.

This means that every action has full write access to Bazel's install base, output base, ...

On Linux, this is not an issue, because the default output user root is `$HOME/.cache/bazel/_bazel_$username`.

We could probably fix this by adding an explicit `(deny file-write* (subpath "$output_root"))` at the end of the config. Or by moving the default output root on macOS to a more sensible path - e.g. `$HOME/Library/Caches/bazel`? But I remember that there were some issues with macOS having a rather short maximum path length for UNIX sockets.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I noticed this when running a test with --sandbox_debug and checking out the generated sandbox config:

```
cat /private/var/tmp/_bazel_philwo/7a01905b4627ca044e5e3f5ad5b14d26/sandbox/darwin-sandbox/1/sandbox.sb 
(version 1)
(debug deny)
(allow default)
(deny file-write*)
(allow file-write*
    (subpath "/dev")
    (subpath "/private/var/tmp/_bazel_philwo/7a01905b4627ca044e5e3f5ad5b14d26/sandbox/darwin-sandbox/1/execroot/io_bazel")
    (subpath "/private/var/tmp")
    (subpath "/private/var/tmp/_bazel_philwo/7a01905b4627ca044e5e3f5ad5b14d26/sandbox/darwin-sandbox/1/execroot/io_bazel/_tmp/e67ade99c380ac4e1bb96288a830bc98")
    (subpath "/Users/philwo/Library/Developer")
    (subpath "/private/tmp")
    (subpath "/private/var/folders/_g/1lhp9yyn5js9k3_c1fp_m0b4005v1x/T")
    (subpath "/Users/philwo/Library/Logs")
    (subpath "/private/var/folders/_g/1lhp9yyn5js9k3_c1fp_m0b4005v1x/C")
)
```

### What operating system are you running Bazel on?

macOS 10.12.5

### What's the output of `bazel info release`?

release 0.25.2

**Comment by jmmv** [comment]
Yes, you are right. Unix sockets are a problem... but the good thing is that, since the conversion of the Blaze client to gRPC, we don't use one any more! We actually use a localhost-bound port! (Actually, that's not a good thing, but at least it wouldn't prevent us from moving the output base today.)

It'd be nice to move the output base and possibly even split it into multiple pieces (most of the stuff in it could be generated on a server instance basis and wiped on deletion, thus belonging in `/tmp`), but I don't see us stopping the use of `/tmp`. Partially because of what you mention, and partially because it just makes sense to use `/tmp` for some of our files.

So adding a `deny` entry to the sandbox configuration is the easiest "solution" for now.

But another thought: do we need to expose the real `/tmp` to the sandbox at all? It'd be nice if each action saw an empty `$TMPDIR` (though that might be harder because of macOS's getconf settings...). I think this was tried in the past but didn't work well?

**Comment by jmmv** [comment]
Duping against the more-general #11100 .
