### ISSUE TITLE
Toolchain inheritance

### ISSUE THREAD

**Issue by s-kanev** [bazelbuild/bazel#841]
One use case for defining a custom toolchain is to just add an additional tool, like [nvcc in TensorFlow](https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/CROSSTOOL#L45). Right now that requires defining a toolchain from scratch, which seems to scare people away, leading to quite bizarre wrappers like [the one for swig, again in TensorFlow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/swig/swig.sh).

It would be nice to be able to define a new toolchain by inheriting all settings from an existing one (including the bazel default), and then just adding that one little tweak that a particular project needs, whether it's a new tool, a new flag, etc.

**Comment by davidzchen** [comment]
Is the main issue that it is cumbersome to add a new toolchain to the CROSSTOOL file?

**Comment by s-kanev** [comment]
Yes, exactly. And in the use case I described you can end up with toolchains that are 99% the same, which sounds like unnecessary duplication.

**Comment by davidzchen** [comment]
Got it. I agree that this is pretty cumbersome at the moment since the CROSSTOOL file is text protobuf (think plain JSON).

One idea that I have is to generate the CROSSTOOL config using a configuration generation language. Internally, we have a configuration language that generates proto, but there are no plans to externalize that language. However, we do have a very similar open source configuration language, [Jsonnet](http://jsonnet.org/), for which we also have [Skylark build rules for](http://bazel.io/docs/be/jsonnet.html).

Jsonnet is a configuration generation language that compiles to JSON. Its syntax is very similar to JSON but has a rich set of language features, most importantly, tuple inheritance that allows you to compose and inherit from JSON tuples to generate new data. If we write the CROSSTOOL in Jsonnet, adding a new toolchain that is based on an existing toolchain would be as simple inheriting from an existing one. For example:

```
// Define a template for all default_toolchain configs with toolchain_identifier
// "local_linux":
local linux_default_toolchain = {
  cpu: "",
  toolchain_identifier: "local_linux"
}

// Then, the default_toolchains for k8, piii, etc., can simply inherit from
// linux_default_toolchain:
local k8_default_toolchain = linux_default_toolchain {
  cpu: "k8"
}

local piii_default_toolchain = linux_default_toolchain {
  cpu: "piii"
}

// We can do the same for the toolchain entries as well.

// The below will generate the JSON representation of the CROSSTOOL
// file, though we can also easily write an adapter to have it generate
// text proto instead:
{
  major_version: "local",
  minor_version: "",
  default_target_cpu: "same_as_host",
  default_toolchain: [
    k8_default_toolchain,
    darwin_default_toolchain,
    ...
  ],
  toolchain: [
    k8_toolchain,
    darwin_toolchain,
    ...
  ]
}
```

Given that Protocol Buffers 3 has an official [JSON mapping](https://developers.google.com/protocol-buffers/docs/proto3#json), we can use `jsonnet_to_json` to generate the JSON and read it using `JsonFormat` or write a simple adapter to generate text proto instead.

What does the team think?

Also, adding @sparkprime if he has any thoughts about this.

**Comment by ulfjack** [comment]
We already have a configuration language called Skylark. We've also been
considering removing the CROSSTOOL file entirely and instead putting the
information into the cc_toolchain rules (or cc_toolchain_suite), at which
point you could apply Skylark (it can't currently be applied to CROSSTOOL
files). However, we're not currently working on this or even planning to
work on it in the near future.

I'm also reluctant to add yet another dependency to Bazel. Note that the
CROSSTOOL files are currently read before we create a configuration, i.e.,
very early in the build, and we can't run any actions at that point (yet).

That said, several teams at Google generate CROSSTOOL files from some other
description. You have to be a bit careful to make sure to manually rerun
the generator on changes, but this otherwise seems like a reasonable
workaround for the time being.

**Comment by bsilver8192** [comment]
+1 for something easier to work with than CROSSTOOL. I would prefer having it in Skylark to adding another configuration system.

@s-kanev: I don't see how that swig wrapper script is related. I don't think it makes much sense to run swig the same way a C++ compiler gets run because you get a very different set of outputs from it. Are you thinking something different?

**Comment by sparkprime** [comment]
Is there a plan to externalize skylark as a separate tool / library?

**Comment by rdadolf** [comment]
@bsilver8192 The original reason this issue came up was because I was complaining to @s-kanev about the way swig was integrated into tensorflow. Specifically, if swig is installed in a non-standard location, [this](https://github.com/tensorflow/tensorflow/issues/681) and [this](https://github.com/tensorflow/tensorflow/issues/706) seem to be the official solutions for getting it working. Suffice to say, dealing with that across different platforms is irritating. By comparison, python and nvcc install paths are specified using a handwritten [configure script](https://github.com/tensorflow/tensorflow/blob/master/configure). He seemed to think that both of these were unclean, hacky solutions, and that a `tool_path` statement in a toolchain file was the more appropriate approach. That led to the realization that in order to implement this, we'd have to copy an entire crosstool file instead of just, say, inheriting some defaults an overriding a single statement.

I'm only a recent bazel user because of tensorflow, so if I'm doing everything wrong, I'd be happy to learn the right way instead.

**Comment by trainman419** [comment]
+1. I have a similar use-case and would like some variety of toolchain inheritance or automated generation of the CROSSTOOL file too.

**Comment by damienmg** [comment]
fwiw we are now generating the CROSSTOOL file in Bazel using skylark, see https://github.com/bazelbuild/bazel/blob/master/tools/cpp/cc_configure.bzl and https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL.tpl

**Comment by hlopko** [comment]
Closing this issue in favor of https://github.com/bazelbuild/bazel/issues/5380. With crosstool in starlark the toolchain inheritance is a question of code design.

**Comment by jheaff1** [comment]
Now that Bazel is migrating away from the legacy `crosstool`API and moving towards the `platforms` API, can this issue be revisited? Is it now possible to inherit from the default local cc tool chain and override the `gcc` tool path to `musl-gcc`, for example?
