### ISSUE TITLE
implement action output inlining for remote execution

### ISSUE THREAD

**Issue by buchgr** [bazelbuild/bazel#8421]
See https://github.com/bazelbuild/remote-apis/commit/948b9c7e3311ffef8f01b4ccb65a06875d65af20

**Comment by katre** [comment]
Marking untriaged so that the team can decide if this is still needed.

**Comment by ulfjack** [comment]
It doesn't seem high priority at this time as there are a number of other possible performance improvements that'll have a bigger impact.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Comment by tjgq** [comment]
From offline discussion: https://github.com/bazelbuild/bazel/pull/23428 will mark in-memory outputs (currently: `.d`, `.jdeps` and `unused_inputs_list` files) as inlinable. Beyond that, we should consider marking any output that will be immediately downloaded (per the `--remote_download_outputs` and `--remote_download_regex` flags) as inlinable. I'm not convinced that we need to provide a general facility for rule authors to mark outputs as inlinable, since covering these two cases should provide most of the performance benefit.

**Comment by fmeum** [comment]
@tjgq Is it clear that inlining arbitrary outputs that are downloaded with BwoB is a win? For `.d` and `.jdeps` files this is definitely true since they are read synchronously in and thus block the action that ran the spawn. But wouldn't `--remote_download_regex` downloads happen off the critical path? Inlining is also constrained to 4 MiB files.

**Comment by tjgq** [comment]
That's a good point - forcing the download to occur synchronously might very well undo the gains of avoiding the extra round trip. I suppose we could try it out and see what happens, but it's definitely not a clear win.

**Comment by tjgq** [comment]
(Also note: while we *could* download outputs in the background, they currently block completion of the spawn that produces them: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/remote/RemoteExecutionService.java;l=1239;drc=d91e05e4a82e61720d41e64b81d4b36924b1c398).

**Comment by fmeum** [comment]
I wasn't aware of that. It may very well be better to lift that restriction first before we extend the scope of inlining.

**Comment by tjgq** [comment]
Yeah, I'm now of the opinion that we should make downloads async (other than the in-memory case) and not bother with inlining them at all.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc1`. Thanks!
