### ISSUE TITLE
Building multiple targets for iOS results in duplicate builds

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#8449]
Currently if you have a BUILD file with multiple targets like this:

```python
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_unit_test")
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Foo",
    srcs = ["Foo.swift"],
)

swift_library(
    name = "FooTestsLibrary",
    srcs = ["FooTests.swift"],
    deps = ["Foo"],
)

ios_unit_test(
    name = "FooTests",
    minimum_os_version = "10.0",
    deps = ["FooTestsLibrary"],
)
```

And you build them all at once with `bazel build --apple_platform_type=ios //:all` (you have to pass `apple_platform_type` here because otherwise `Foo` is built once for macOS, which is likely indicative of the core issue).

You end up with multiple different libraries in `bazel-out`:

```
bazel-out/ios-x86_64-min10.0-applebin_ios-ios_x86_64-fastbuild/bin/libFoo.a
bazel-out/darwin-fastbuild/bin/libFoo.a
```

AFAICT there's no way to force this second target to be built the same way as the first target. Passing some of the internal flags like `--apple_split_cpu=x86_64` results in a different second build directory, but still doesn't eliminate the duplicate build.

Here's a sample project showing this. On macOS run `./repro.sh` to see the case [doublebuild.zip](https://github.com/bazelbuild/bazel/files/3214127/doublebuild.zip)

It seems like ideally there would be a way to make sure the build of all the targets ends up being the same, in our case the library here is only compatible with iOS in the first place, and we want to only build it with the specific settings we care about.

**Comment by katre** [comment]
This issue looks like it is caused because the ios_unit_test and swift_library rules are in different configurations. I don't know enough about those rule implementations to specifically pinpoint the cause of that, but the different output directories point at that.

Which of the following is the problem:
1.  You are seeing incorrect build results (compilation failures, or binaries that don't execute on the expected platforms).
2.  You are seeing correct build results, as well as extra builds that are consuming extra resources.

If the first is the problem, this is a much higher priority for fixing. If the second is the problem, I will suggest that this will be improved by upcoming changes in Bazel's output directory handling, as well as moving the Apple and Swift rules to use [toolchain resolution](https://docs.bazel.build/versions/master/toolchains.html).

**Comment by keith** [comment]
We're only seeing the second problem you mentioned. Which stops us from ever being able to use any form of ... to do builds.

Cc @thomasvl @sergiocampama @allevato to comment on the toolchain issue

**Comment by thomasvl** [comment]
I believe there has been talk in the past about not having *_library rules in `:all` and `/...`because builds without the transitions are of questionable value; but I think for legacy reasons this hasn't be done.  You can somewhat avoid the issue by doing `bazel test --build_tests_only ...`

**Comment by jmmv** [comment]
Is this still an issue worth addressing? Or can it be worked around like @thomasvl proposed?

Asking because I'm not sure what we should be doing here. Do we have to fix the rules? Do we have to tackle that issue of not including libraries into globs? Something else?

**Comment by allevato** [comment]
There's nothing particularly iOS- or Apple-specific about this issue. Fundamentally this can/will happen any time that you have a library target A and some other target B that depends on A if B applies a configuration transition to its `deps` and you build them both in the same invocation.

That invocation must build A in both the default configuration and the transitioned-to configuration, because there's no way for the invocation to know that you don't care about the library output independently—after all, Blaze is just doing what you're asking it to when you tell it to build `:all` or `/...`.

@thomasvl refers to talk in the past about not having `*_library` rules build at all when you do a wildcard build like that, which may make sense, especially in a world where you have libraries that support building on multiple platforms/configurations.

In the meantime, adding `tags = ["manual"]` to your library targets is an option, and Bazel won't include them in `:all` or `/...` builds.

**Comment by jmmv** [comment]
Alright. So this actually sounds like a configurability issue, and I'll leave it up to that team to decide if we should do anything extra here.

**Comment by katre** [comment]
There are long-standing issues with using `:all` and `/...`. We don't have plans to address this specifically, although it will definitely be impacted by the work on multiplatform builds.
