### ISSUE TITLE
Binary differences with Host JDK 8 and 11

### ISSUE THREAD

**Issue by Xjs** [bazelbuild/bazel#8499]
### Description of the problem / feature request:

An internal project depending on https://developers.google.com/protocol-buffers/ produced different `main_deploy.jar` files depending on whether it was built on a machine with JDK 8 or JDK 11 installed on the host system.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I have created and documented a working minimal test case on https://github.com/Xjs/bazel-java-test/blob/master/case2.md – there the differences are described and the source files form google/protobuf are included and will produce artefacts that show the issue.

### What operating system are you running Bazel on?

These test cases were produced on Windows 10 and Ubuntu 18.04 with different JDKs.

### What's the output of `bazel info release`?

Tested with `release 0.25.2`

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

```
git@github.com:Xjs/bazel-java-test.git
70202cc99f788de3fd89c48be169bb09946a86e8
70202cc99f788de3fd89c48be169bb09946a86e8
```

**Comment by comius** [comment]
This is expected. Bazels Java compilations are not hermetic without additional configuration.

In the default (of the shelf) configuration, Bazel compiles the code against system libraries of the locally installed JDK (found via JAVA_HOME). Rationale for this is that there are users who don't configure what JDK Bazel should use, however the users still expect everything works after Bazel upgrade. If we pinned system libraries of any JDK version, unconfigured repositories would break on Bazel upgrade when the pinned libraries were changed.

In order to configure system libraries without looking at the locally installed JDK. You can use for example `--java_runtime_version=remote_jdk11` in Bazel@HEAD. (Old configuration `--java_base=@remote_jdk11//:jdk` should work in older Bazel version). This will use JDK from a remote repository. It will be used to gather info about system libraries as well to execute the code or tests.

Additional information is available on: https://docs.bazel.build/versions/master/bazel-and-java.html
