### ISSUE TITLE
incompatible_use_specific_tool_files: Use appropriate artifacts from cc_toolchain as inputs to C++ actions. 

### ISSUE THREAD

**Issue by scentini** [bazelbuild/bazel#8531]
`cc_toolchain` has attributes corresponding to various toolchain components like `ar_files`, `compiler_files`, and `as_files`. Previously, Bazel used broad file groups like `all_files` as inputs for several classes of actions and ignored the more specific toolchain attributes. `--incompatible_use_specific_tool_files` brings these attributes into use.

Namely, under this flag:

- C and C++ compilation actions use `compiler_files` rather than `all_files`.
- Static library-generating actions use `ar_files` rather than `linker_files`.
- Non-processed assembler actions use `as_files` rather than `all_files`. Preprocessed assembly actions use `compiler_files` because preprocessing is usually done by the C compiler.

Relevant issues: #6927, #6928.

### Migration
For every `cc_toolchain` rule, ensure
- `compiler_files` contains the compiler binary and standard library header files if necessary
- `as_files` includes the assembler (e.g., `gas`)
- `ar_files` includes the static archive tool (e.g., `ar`)

### Expected timeline
Disabled by default in 0.27.
Enabled in the September 2019 release.

**Comment by scentini** [comment]
@benjaminp Can you please update this issue with migration details?

**Comment by benjaminp** [comment]
(I lack permissions to edit the actual issue, but here we go.)

`cc_toolchain` has  attributes corresponding to various toolchain components like `ar_files`, `compiler_files`, and `as_files`. Previously, Bazel used broad file groups like `all_files` as inputs for several classes of actions and ignored the more specific toolchain attributes. `--incompatible_use_specific_tool_files` brings these attributes into use.

Namely, under this flag:
- C and C++ compilation actions use `compiler_files` rather than `all_files`.
- Static library-generating actions use `ar_files` rather than `linker_files`.
- Non-processed assembler actions use `as_files` rather than `all_files`. Preprocessed assembly actions use `compiler_files` because preprocessing is usually done by the C compiler.

### Migration

For every `cc_toolchain` rule, ensure
- `compiler_files` contains the compiler binary and standard library header files if necessary
- `as_files` includes the assembler (e.g., `gas`)
- `ar_files` includes the static archive tool (e.g., `ar`)

### Expected timeline
Disabled by default in 0.27.
Enabled in the September 2019 release.

**Comment by kkiningh** [comment]
With this flag enabled I get the following error on OSX 10.14.2 when I try to compile a cc_library.

```
src/main/tools/process-wrapper-legacy.cc:58: "execvp(external/local_config_cc/wrapped_ar, ...)": No such file or directory
```

Simple example [here](https://github.com/kkiningh/bazel_issue_tool_files).

**Comment by luxe** [comment]
I'm confused why this is enabled now, but the master docs still say ar_files is unused (#6928).
https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
