### ISSUE TITLE
0.27 new bash runfiles init doesn't set RUNFILES_MANIFEST_ONLY

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel#8668]
I tried updating rules_nodejs to the new bash runfiles init boilerplate that was announced in 0.27
https://github.com/bazelbuild/rules_nodejs/pull/873/files
but it fails with
https://circleci.com/gh/bazelbuild/rules_nodejs/21792

```
ERROR: /home/circleci/rules_nodejs/internal/npm_package/test/BUILD.bazel:20:1: Assembling npm package internal/npm_package/test/dependent_pkg failed (Exit 1)
bazel-out/host/bin/internal/npm_package/packager: line 60: RUNFILES_MANIFEST_ONLY: unbound variable
```

**Comment by laszlocsomor** [comment]
Thanks for reporting!

The old init code also didn't set the envvar. The culprit is the `set -u` in the new init code [1] that you copied over. The old init code also sets this [2] but `./internal/node/node_launcher.sh` and the other files omitted that line from the boilerplate.

You can fix the problem in `./internal/node/node_launcher.sh` -- change `$RUNFILES_MANIFEST_ONLY` to `${RUNFILES_MANIFEST_ONLY:-}`.

[1] https://github.com/bazelbuild/bazel/blob/934045fb0d80f3b9d89238b19dbec06863c47b33/tools/bash/runfiles/runfiles.bash#L56

[2] https://github.com/bazelbuild/bazel/blob/616481a6b4ffa1818c04bedefe138880b45fe7fa/tools/bash/runfiles/runfiles.bash#L40
