### ISSUE TITLE
run multiple binaries at once based on tags

### ISSUE THREAD

**Issue by JoshSullivan11** [bazelbuild/bazel#8686]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

> Similar to ```bazel test --test_tag_filter=<tag_name> //path/...```, we would like to see the ability to run binaries the same way with something like ```bazel run --run_tag_filter=<tag_name> //path/...```

### Feature requests: what underlying problem are you trying to solve with this feature?

> Be able to run multiple binaries in a single session based on their tag values.

### What operating system are you running Bazel on?

> linux Ubuntu 16.04

### What's the output of `bazel info release`?

> 0.19.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> fatal: No such remote 'origin'
073ae3230e73ccb77a7805382fea73540f190cb1
a62544247d0d49ebd7614090f68b524234bb9599

###  Have you found anything relevant by searching the web?
> no

**Comment by dslomov** [comment]
It should be easy to extract neccessary targets using [`bazel query`](https://docs.bazel.build/versions/master/query-how-to.html) but it is a reasonable feature request.

**Comment by jmmv** [comment]
The semantics of doing this seem complicated (do the processes run sequentially or in parallel? what happens with input/output?), and the interface to this would be hard to fit because of how `blaze run` is today (the first argument is the target and the rest are arguments to that target). So I think this is actually unfeasible and much better achieved by wrapping query and doing execution as necessary.
