### ISSUE TITLE
Windows: enable symlink support by default

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/bazel#8704]
Windows 10 version 1703 (Creators Update) brought unprivileged symlink support to Windows. (After enabling Developer Mode.)

It might be time to enable symlink support in Bazel on Windows by default.
Bazel could possibly also detect if symlinks are supported (i.e. try to create one) and fall back to no support if that failed.

Version: 0.26.0

**Comment by jimevans** [comment]
One other possible way to do this would be to check the registry. In pseudo-code:

    if (registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock` exists):
      if (DWORD registry value `AllowDevelopmentWithoutDevLicense` exists in the key and the value is not 0):
        return true

    return false

**Comment by laszlocsomor** [comment]
Duplicate issue: https://github.com/bazelbuild/bazel/issues/7954

**Comment by rickeylev** [comment]
It's been several years since this was filed. Are there plans to enable, or known blockers to enabling, symlinks on windows? Some light searching seems to indicate Windows has had this support for many years; perhaps long enough has passed that whatever versions had a problem aren't really supported anymore?

In particular, i found https://github.com/bazelbuild/bazel/issues/5807 which seems to indicate several language rules enable symlinks on windows. And the [bazel docs](https://bazel.build/configure/windows#symlink) seem to recommend enabling it (while simultaneously warning not to because they're "expensive").

In any case, it's looking like rules_python will join the set of rules that requires them to be enabled.

cc @meteorcloudy (seems he was active on 5807, and it doesn't look like there are any current bazel members on this issue)

**Comment by meteorcloudy** [comment]
Note that, here symlink actually means "file symlink", we use junction for directory symlink on Windows, it has always been working.

But for creating file symlinks, the user still requires admin right (to run bazel or to enable developer mode). We don't want to add this hard requirement for Bazel users.
