### ISSUE TITLE
incompatible_enable_cc_toolchain_resolution breaks ios_unit_test targets

### ISSUE THREAD

**Issue by keith** [bazelbuild/bazel#8716]
### Description of the problem / feature request:

When using `--incompatible_enable_cc_toolchain_resolution` to build a `ios_unit_test` target, the build fails with an error like:

```
clang: error: invalid version number in '-mmacosx-version-min=13.0'
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
```

Because it appears to be being passed the wrong flags.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Clone [rules_apple](https://github.com/bazelbuild/rules_apple/) and run:

```
bazel build examples/ios/PrenotCalculator:PrenotCalculatorTests --incompatible_enable_cc_toolchain_resolution
```

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

development version (this also repros with 0.27.0)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

bazel build src:bazel

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel
562eaf30092d81f04706c8a7fcda560dc243a659
562eaf30092d81f04706c8a7fcda560dc243a659

###  Have you found anything relevant by searching the web?

This looks very similar to this issue https://github.com/bazelbuild/bazel/issues/8330 of which the patch exists in master and in 0.27.0, so this seems to be a distinct issue

**Comment by hlopko** [comment]
Yup this is a known hiccup blocking flipping this flag. Android and Apple rules use configuration transitions that currently transition on the values of `apple|android_crosstool_top` and `cpu`, and we need them to transition on `platforms`. Work is ongoing.

If you need to be unblocked for this, there is a way by using the `PLATOFORM_MAPPING` file (being documented). If waiting is fine, then be sure we'll fix this before flipping the flag.

Thanks!

**Comment by gregestren** [comment]
FYI I was able to get this specific build working with platform mappings.

I just tried it experimentally but got:

```
$ mkdir platforms
$ cat >platforms/BUILD <<EOF
platform(
  name = "ios",
  constraint_values = [
   "@platforms//os:ios",
   "@platforms//cpu:x86_64"
   ])
EOF

$ cat > platform_mappings <<EOF
platforms:
  //platforms:ios
    --cpu=ios_x86_64
    --apple_platform_type=ios

flags:
  --cpu=ios_x86_64
  --apple_platform_type=ios
    //platforms:ios

  --cpu=darwin
  --apple_platform_type=macos
    //platforms:ios
EOF

$ bazel build //examples/ios/PrenotCalculator:PrenotCalculatorTests
  --incompatible_enable_cc_toolchain_resolution
INFO: Build completed successfully, 1 total action
```

I'm a little unclear why I had to define the top `platform` section in the mapping, and some of the specific iOS vs. MacOS settings. But I'd need to chat with the Apple rules experts to clarify those details.

**Comment by katre** [comment]
I suspect that the apple rules also read the value of cpu, and thus the platform->flag mapping is ensuring that the value of `--cpu` matches the platform that was set.

**Comment by cpsauer** [comment]
If other folks are landing here looking for good ways to get platform_mappings working with iOS or apple platforms, lmk.  

We just got platforms working Android/iOS/macos via platform_mappings--at least from the flags side, enabling select()s--and I'd be happy to share if there's demand!

**Comment by keith** [comment]
I think there is interest from the bazel folks to finish up platforms wrt iOS, so it might be helpful! (I'm still not entirely sure what needs to be done here)

**Comment by gregestren** [comment]
A number of us are working a bit behind the scenes to try to land proper iOS support for platforms and finally resolve this issue. There's a bunch of context but it's an ongoing discussion between folks inside and outside of Google.

@keith you've been part of these conversations. :) Since I'm doing my best to get all stakeholders on the same page re: timeline expectations and specific responsibilities, would you like more guidance beyond what we've already discussed on Slack?  I'm trying to identify specific tasks as much as I can while recognizing we still have to wait for the Apple rule logic changes to land from the Bazel devs.

**Comment by gregestren** [comment]
<extremely tempted to revisit the P4 tag on this issue...>

**Comment by cpsauer** [comment]
Ah sorry guys. Didn't mean to inflame anything here. 
We were just eager to adopt platforms and ran across this issue because it's linked as one of the few examples of the platform_mappings stopgap on https://docs.bazel.build/versions/main/platforms-intro.html. It took us a little figuring from here to get everything working, so I thought I'd offer to help if others were running into the same.
[If useful: Having platforms solves some pain points for us around having platform-specific backends for a library that's packaged up for multiple platforms. This is especially true now that C++ libraries, like boost, have adopted platforms, and we'd really like them to work as intended.]

**Comment by gregestren** [comment]
Nothing inflamed!

This is healthy conversation. We're probably not signaling the state of this development clearly enough. It's a bit hard since it crosses work across different groups, so there's extra coordination confusion. 

Maybe I can add some updates to https://docs.bazel.build/versions/main/platforms-intro.html to try to be more clear.

**Comment by keith** [comment]
Yea I guess we're just in a "wait for google" phase, which is why I'm not sure about what's going on. AFAIK we (the rules_apple maintainers) can't do anything (without duplicating work being done at google) right now, is that correct?
