### ISSUE TITLE
Error when build Android project with '--incompatible_disable_native_android_rules'

### ISSUE THREAD

**Issue by Vaigard** [bazelbuild/bazel#8757]
### Description of the problem / feature request:

When I try to build my project with `--incompatible_disable_native_android_rules`, I got next error:
<pre>ERROR: /home/user/.cache/bazel/_bazel_user/aee0be3e153556afb3ddc0b7aea89213
/external/androidsdk/BUILD.bazel:8:1: in tags attribute of android_sdk 
rule @androidsdk//:sdk-28: The native Android rules are deprecated. 
Please use the Starlark Android rules by adding the following load statement 
to the BUILD file: load("@build_bazel_rules_android//android:rules.bzl",
"android_sdk"). See http://github.com/bazelbuild/rules_android.. 
Since this rule was created by the macro 'create_android_sdk_rules', 
the error might have been caused by the macro implementation in
/home/user/.cache/bazel/_bazel_user/aee0be3e153556afb3ddc0b7aea89213/
external/androidsdk/BUILD.bazel:8:1</pre>

After Bazel 0.27 installing I use

<pre>load("@rules_android//android:rules.bzl", android_sdk_repository_rule = "android_sdk_repository")
...
def my_sdk_rule(name = None, api_level = None, build_tools_version = None):    
    android_sdk_repository_rule(
        name = name,
        api_level = api_level,
        build_tools_version = build_tools_version,
    )</pre>
### What operating system are you running Bazel on?

Ubuntu 18.04.

### What's the output of `bazel info release`?

release 0.27.0

**Comment by ahumesky** [comment]
This is because the `android_sdk_repository` workspace rule generates native `android_sdk` rules:
https://github.com/bazelbuild/bazel/blob/ebfd3bcb0baec0774db584fd3ff5445a1ec7925b/tools/android/android_sdk_repository_template.bzl#L107

As a workaround we can manually add `__ANDROID_RULES_MIGRATION__` to the tags for that android_sdk rule, since it's trickier to actually migrate the rule, and it's autogenerated anyway.

Unfortunately there's no easy way to apply this workaround locally without recompiling bazel because the repository template file is embedded inside bazel.
