### ISSUE TITLE
incompatible_enable_cc_toolchain_resolution has correctness issues

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel#8787]
Setting/unsetting the flag `incompatible_enable_cc_toolchain_resolution` doesn't invalid the build. This leads to correctness issues.

See https://github.com/bazelbuild/bazelisk/issues/73 for the exact report.

cc @katre, @lberki, @hlopko, @keith

**Comment by hlopko** [comment]
This is hard to believe, were you able to reproduce with plain Bazel? Are you confident it's only this flag and not others?

**Comment by ulfjack** [comment]
The upstream bug report is pretty clear. However, it might be a pre-existing condition and not related to the flag.

**Comment by keith** [comment]
Here is a repro project for the issue I reported on bazelisk. We specifically are hitting this issue the first time https://github.com/bazelbuild/bazel/issues/8716 and then once we do a valid build without this flag, re-adding this flag still passes the build.

[toolchain_repo.zip](https://github.com/bazelbuild/bazel/files/3356252/toolchain_repo.zip)

Using bazelisk + 0.27.1 running `./repro.sh` in this example should reproduce the issue for you. Let me know if it doesn't!

**Comment by hlopko** [comment]
I can repro at HEAD, with 0.27.1, with 0.26.0, and I cannot with 0.25.0. \o/ Going to bisect.

**Comment by hlopko** [comment]
And the winner is ... drumroll ... https://github.com/bazelbuild/bazel/commit/7dc78cdd04eedf2f4373b170053ba5fc2a990929. I will leave the interpretation of the potential cause till tomorrow.

**Comment by hlopko** [comment]
And of course that commit is not the cause, it just uncovered the issue. The problem seems to be that with the `--incompatible_enable_cc_toolchain_resolution` flipped and unflipped we get an action with identical command line, but not so identical env variables (`APPLE_SDK_PLATFORM` and `APPLE_SDK_VERSION_OVERRIDE` specifically). And it seems Bazel incorrectly decides that identical command line is enough to take the cached output. Investigation continues.

**Comment by laurentlb** [comment]
I haven't looked at it (the repro script didn't work for me on Linux), but isn't about changing the effectTags?
https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CppOptions.java;l=848?q=incompatible_enable_cc_toolchain_resolution

Have you tried using EXECUTION here?

**Comment by hlopko** [comment]
Aren't those tags used for documentation only? I'd be very surprised if that was causing the correctness issue. At this very second I blame broken env variables handling in C++ actions. Still investigating.

**Comment by lberki** [comment]
Ouchie. Not taking environment variables into account sounds like a serious correctness issue.

**Comment by hlopko** [comment]
I have a fix in flight. The problem is that we were not putting environment variables set by the C++ toolchain into the action key of C++ linking actions, therefore Bazel would happily claim cache hit on actions that only differed in the environment variables. Compilation actions are not affected by this bug.
