### ISSUE TITLE
py_binary executables can be very slow on Windows

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#8981]
### Description of the problem:

Executing a `py_binary` on Windows takes much longer than executing the same `py_binary` target on Linux or macOS.

On Windows `py_binary` targets are compiled into a zip archive. Upon execution the archive is unpacked into a temporary directory, the python interpreter is called on the main python module, after termination the temporary directory is cleaned up. The unpacking and clean-up can incur a large overhead. If the `py_binary` is used as a build tool and called often during build steps this overhead quickly adds up to impractically long times.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

We noticed this issue when writing a wrapper around the C compiler for rules_haskell. See https://github.com/tweag/rules_haskell/pull/1002. To reproduce checkout https://github.com/tweag/rules_haskell/pull/1002/commits/aebfbe12be1af963f50ac3c0c02cfba16bdade07 and execute `bazel build @haskell_vector//:lib` on Windows. Compare the required time to the same Bazel build on Linux or macOS. A summarized procmon trace is shown [here](https://github.com/tweag/rules_haskell/pull/1002#issuecomment-514980293). In this particular case the overhead for a single `cc_wrapper` invocation amounts to about 9s on a local Windows laptop. (Windows defender was disabled) The execution time of the actual python code lies below 1s, i.e. below the resolution of the procmon trace. The total overhead causes the Windows build to timeout at 1h on CI. The relevant step would usually complete in 15min.

### What operating system are you running Bazel on?

Windows 10 Home

### What's the output of `bazel info release`?

release 0.27.0

**Comment by brandjon** [comment]
Assuming that the cost is all related to extracting and then cleaning up the zip files:

You could try running with `--build_python_zip=false` and `--enable_runfiles=true`, provided your windows machine has symlinks enabled. This isn't a general solution for all windows machines, but the problem is without symlink support, our options are more limited. We (currently) need to create a directory tree of runfiles for the Python interpreter to be able to import dependencies, whose `.py` sources are stored in the runfiles tree.

Importing without extracting is a possibility, see google/subpar. But we don't support that for the main Bazel Python rules because it can be brittle.

We are interested in modifying the rules to hook into Python's import mechanism, to get finer control over how imports are resolved (to make them more hermetic, control whether user libraries override system-installed ones, etc.). Perhaps the same mechanism could also allow us avoid unpacking the runfiles tree.

**Comment by nicolov** [comment]
> Perhaps the same mechanism could also allow us avoid unpacking the runfiles tree.

Did you have anything in mind to achieve this? As far as I can tell (say, for remote execution), .py files somehow need to be added to runfiles to be available at runtime.

Asking this because `py_binary` becomes slow even on Windows when importing many large Python projects and their transitive dependencies.

**Comment by aherrmann** [comment]
@brandjon I can confirm that `--build_python_zip=false` and `--enable_runfiles=true` avoids the issue. The build time for a test target after `bazel clean` drops from 1501s to 36s. Unfortunately, as you point out, this requires admin privileges. We would like to avoid forcing this restriction on users of rules_haskell on Windows.

I'm unfamiliar with the internals of `py_binary`. Why can't the generated `.exe` not set `PYTHONPATH` to point to the relevant runfiles instead of zipping and unzipping, or symlinking them into place?

**Comment by brandjon** [comment]
> Did you have anything in mind to achieve this? As far as I can tell (say, for remote execution), .py files somehow need to be added to runfiles to be available at runtime.

To access runfiles in general, we provide a [runfiles library](https://github.com/bazelbuild/bazel/blob/137f969b40318b5941e594e5136290b65b89c197/tools/python/runfiles/runfiles.py) that translates from workspace-relative paths to real paths. On systems with symlinks enabled (the directory-based implementation), we just look under the runfiles symlink tree at the given lookup path. On systems without symlinks (the manifest-based implementation), we instead consult a manifest file that allows us to indirect back into the source or output tree (where the symlink would've pointed to).

This manifest approach doesn't play nice with Python's default way of handling imports, because Python expects the module import path to correspond to a directory structure in `PYTHONPATH`. For user code that needs to load some `data.txt` file we can just say to lookup the path with the runfiles library, but that doesn't work when it's the Python interpreter trying to resolve `import mypkg.foo`. If this could be circumvented, say by using a custom module loader, then perhaps we won't need to build a zip at all.

Not sure how remote execution plays into this, but I imagine that all the runfiles would always be shipped to the remote platform regardless of whether symlinks are enabled. Anyway, the Python rules currently don't quite work with Windows and remote execution (#8410).

**Comment by nicolov** [comment]
> On systems with symlinks enabled (the directory-based implementation), we just look under the runfiles symlink tree at the given lookup path.

Sorry, what I tried to say is that, even on Linux with symlinks, the runfile trees of many Python programs are prohibitively large. Importing large pip dependencies like numpy or matplolib as `py_library` easily creates tens of MBs of _symlinks_. If you extend this to many hundreds of Python tests or binaries in a workspace, you have GBs of symlinks in the build tree. I was wondering if you had any magic plans for working around this.

**Comment by brandjon** [comment]
Hm, checking this out on my machine, if I create a hello world target that depends on matplotlib and numpy, I get a runfiles tree where `find | wc -l` reports `2399` and `du -sh` reports `9.9M`, which is about right at 4KB / symlink or directory. So a mitigation might be to use a filesystem with smaller block size?

If we did implement the alternative module loader, so that we didn't need the physical directory structure to import things, then you could presumably build with `--enable_runfiles=false`. Today you can do that build but the resulting artifact won't execute; the runfiles tree drops down to half a meg for the manifest file only.

**Comment by nicolov** [comment]
> So a mitigation might be to use a filesystem with smaller block size?

Yes, but on many configurations, it's easier to run out of inodes because of the many files than to run out of space.

> you could presumably build with --enable_runfiles=false

Is this supposed to work with `bazel test` on Linux? Bazel seems to create the runfiles anyway.

**Comment by brandjon** [comment]
You apparently need to run `bazel clean` to wipe out the runfiles tree. This sounds like an incremental correctness bug -- filed #9150.

**Comment by nicolov** [comment]
> You apparently need to run bazel clean to wipe out the runfiles tree.

Yes, I did it. I think `--enable_runfiles=false` is broken for `test`, but works with `run`. When using `test`, runfiles are still created.

**Comment by brandjon** [comment]
You're correct again. Not sure what's up with that, filed #9164.

**Comment by nicolov** [comment]
Thanks a lot for creating the issue! I’d been putting that off for a day..

**Comment by laszlocsomor** [comment]
@aherrmann :

> Unfortunately, as you point out, this requires admin privileges.

Only on older Windows versions. Since Windows 10 v1703 you can enable Developer Mode to create symlinks in non-elevated processes. (Not sure if that applies to Windows Home.) Does that help?

**Comment by aherrmann** [comment]
@laszlocsomor Thanks for pointing that out. Yes, that is true, though AFAIK enabling developer mode itself also requires admin privileges. For now, we were able to work around this limitation in this particular case by using a `sh_binary` instead of a `py_binary`.

**Comment by laszlocsomor** [comment]
> AFAIK enabling developer mode itself also requires admin privileges

Good point -- I don't know for sure, but sounds likely.

I'm curious, what is the workaround? Add a `sh_binary` that `data`-depends on the `py_binary` so the runfiles are rolled up to the sh_binary and no zip is built?

**Comment by aherrmann** [comment]
@laszlocsomor No, the workaround was to replace the `py_binary` by a `sh_binary`. It's a fairly simple script for Windows, so it's feasible to implement in bash instead of Python.

**Comment by laszlocsomor** [comment]
Thanks!

Is there anything left to do for this issue? `py_binary` on Windows is slow because zipping is slow, the workaround is `--build_python_zip=false` and `--enable_runfiles=true`.

**Comment by moroten** [comment]
> No, the workaround was to replace the `py_binary` by a `sh_binary`. It's a fairly simple script for Windows, so it's feasible to implement in bash instead of Python.

@aherrmann Can you share this "fairly simple script"?

**Comment by aherrmann** [comment]
@moroten The bash script is here https://github.com/tweag/rules_haskell/pull/1039/files#diff-5a327d69f8f6d0dc769c7c2bd7866f31, the python script is part of the same PR.

@laszlocsomor Ideally, `py_binary` would not be slow on Windows without the need to workaround it with `--enable_runfiles=true`, which requires admin rights/developer mode. Also, as I understand the discussion between @nicolov and @brandjon the symlinks solution has issues as well, after all the workaround for @nicolov's issue is the exact opposite, i.e. `--enable_runfiles=false`. @brandjon's proposed hooking into the import mechanism might be a better solution:

> We are interested in modifying the rules to hook into Python's import mechanism, to get finer control over how imports are resolved (to make them more hermetic, control whether user libraries override system-installed ones, etc.). Perhaps the same mechanism could also allow us avoid unpacking the runfiles tree.

@brandjon I couldn't find an issue for that approach, does one exist already?

**Comment by brandjon** [comment]
> I couldn't find an issue for that approach, does one exist already?

#7959

**Comment by aherrmann** [comment]
@brandjon Thanks! Closing this then.
