### ISSUE TITLE
cc_library cannot set CompilationContext.includes or quote_includes

### ISSUE THREAD

**Issue by aherrmann** [bazelbuild/bazel#8984]
### Description of the problem:

The include search paths defined in the `includes` attribute of the `cc_library` rule populate the `system_includes` field of the `CompilationContext` in the generated `CcInfo` provider. The `cc_library` rule does not have an attribute that allows to forward header search paths to be set with `-iquote` or `-I`, only `-isystem`. This can cause issues because of the following behavior of gcc when it encounters `-isystem`, `gcc(1)`:

> If a standard system include directory, or a directory specified with -isystem, is also specified with -I, the -I option is ignored. The directory is still searched but as a system directory at its normal position in the system include chain.

There should be a way to populate the `quote_includes` and `includes` fields of `CompilationContext` using `cc_library`.

### Feature requests: what underlying problem are you trying to solve with this feature?

If an include path is set using both `-isystem` and `-I`, then the `-I` flag will be ignored, see man-page quote above. This can cause unexpected headers to be included if the same header file name appears in multiple include paths and can cause build failures or wrong runtime behavior. In particular, this can be an issue in generated targets. See https://github.com/tweag/rules_haskell/issues/1010.

### What operating system are you running Bazel on?

opensuse:tumbleweed:20190529

### What's the output of `bazel info release`?

release 0.28.0- (@non-git)

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

Using the Nix shell of the rules_haskell rule set.

**Comment by scentini** [comment]
There is work in progress regarding this, see [this proposal](https://docs.google.com/document/d/1D-WLmwgy6K1hsByLRxJjjZdAJUbPeLIWEYzKmGQoVdI/edit#heading=h.5vdf0kvel8gb) and [this proposal](https://docs.google.com/document/d/1PKTDhE9rHzd0WQJY2czjg_vPT28fufGcl2Gain6mUaI/edit#heading=h.9grrl7f2c55j).
Either of them will solve this problem, the first one adding the necessary attributes to cc_library, the second one removing the need for include-like attributes altogether.

Currently, you can add `-I` and `-iquotes` in a nontransitive manner through copts, and, if the public headers in your cc_library are in the same directory, you can use the [`include_prefix`](https://docs.bazel.build/versions/0.28.0/be/c-cpp.html#cc_library.include_prefix) and [`strip_include_prefix`](https://docs.bazel.build/versions/0.28.0/be/c-cpp.html#cc_library.strip_include_prefix) attributes in order to have the headers directory included with `-I`.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
