### ISSUE TITLE
Can't bazel sync at HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazel#9007]
if I clone bazel at HEAD and try to "bazel sync" I get a failure, looks like:

```
ERROR: An error occurred during the fetch of repository 'rbe_ubuntu1604_java8':
   Traceback (most recent call last):
File "[redacted]/rbe_repo.bzl", line 449
    validate_host(ctx)
File "[redacted]/external/bazel_toolchains/rules/rbe_repo/util.bzl", line 152, in validate_host
    fail("Cannot run rbe_autoconfig as 'd...")
Cannot run rbe_autoconfig as 'docker' was not found on the path and environment variable DOCKER_PATH was not set. rbe_autoconfig attempts to pull a docker container if a toolchain config was not found for the version of Bazel (selected via attr or implicitly identified). If you do not want rbe_autoconfig to ever attempt to pull a docker container, please use attr 'use_checked_in_confs = "Force"'.
```

I believe this is a recent regression, though it doesn't look like we updated the bazel->bazel_toolchains dependency *that* recently. Any ideas what's going on here?

**Comment by jin** [comment]
This looks like a CI drift, where `docker` isn't available on the path. cc @philwo

**Comment by c-parsons** [comment]
..how is this CI, given that I'm trying to sync locally, and not touching a CI instance at all?

**Comment by jin** [comment]
I totally misread, oops. Do you have `docker` on your path? When was the last time this worked for you?

**Comment by c-parsons** [comment]
I do not have docker on my path (and I'm not sure I ever did).

I thought it worked last week, but I still have this breakage when I reset back to the beginning of last week.

I arbitrarily reset to 5d72d4ea54fdcb6e963cacb7181fda847e01bc50 (commit from late June) and retried, and ran into no issues.

Do we require that users download docker to contribute to bazel?

**Comment by jin** [comment]
AFAICT `bazel sync` tries to resolve *all* repository rules unconditionally, whether you have targets that depend on them or not. `rbe_autoconfig` is a repository rule that should only trigger on CI, not the local workstation. Maybe what you want is `bazel fetch //...`?

**Comment by agoulti** [comment]
So rbe_autoconfig looks for the right toolchain config, as determined by the combination of the Docker container and Bazel that is doing the build.
It looks:
- in bazel-toolchains repo
- in the repo that is being built
- if it doesn't find it, it attempts to build it.

In order to build it, it needs 'docker' installed on the machine that's running it.
It looks like it's not finding the toolchains for the right combination of tools.

Your options are:
1. use a combination that is released in bazel-toolchains
2. install "docker" on the machine where you want to build this
3. run it once on a machine that has Docker, generate the toolchains and check them in. (see https://github.com/bazelbuild/bazel-toolchains/blob/b28d792809c459bdb629cda8e520a090b23a9db3/rules/rbe_repo.bzl#L53)

I'm guessing what's changed is this:
https://github.com/bazelbuild/bazel/commit/60df905100d0f1ea74ea22ae31cd3c205e101521

**Comment by c-parsons** [comment]
ack. Maybe I should be using `bazel fetch //...` instead (which also seems to be broken, but for a different reason)

**Comment by nlopezgi** [comment]
you shouldn't need to fetch the rbe_autoconfig repo unless you are doing a remote build. If you are doing a remote build, and using Bazel head, you do need to have docker installed or override the bazel_version to use with rbe_autoconfig. Doing bazel sync is probably not what you want here though.

**Comment by jin** [comment]
So this is WAI, right?

**Comment by c-parsons** [comment]
Sounds like it, from now on I'll note "bazel sync isn't expected to work locally"

**Comment by philwo** [comment]
> "bazel sync isn't expected to work locally"

Sounds like it won't work in most environments and it's easy to get a project into a state where it will not work on any environment (e.g. if certain repositories can only be synced on certain platforms), right? Why do we even have the feature then?

**Comment by jin** [comment]
`sync` is for unconditionally resolving all external repositories so we can encode and pin them in a `resolved.bzl` file. cc @aehlig

**Comment by c-parsons** [comment]
I believe Jin is correct -- which makes it unfortunate that this feature is unusable for end users.

Is there no way to make the toolchains repo a bit more resilient to unhandled platforms and environments?
