### ISSUE TITLE
Failing to follow dependencies for libcurl

### ISSUE THREAD

**Issue by nicmcd** [bazelbuild/bazel#9120]
### Description of the problem / feature request:
Bazel fails during tracking dependencies for curl. The failing output is:
```
ERROR: /home/nic/dev/tmp/bazel_curl/BUILD:8:1: Linking of rule '//:get' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-fastbuild/bin/get-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/bin/external/curl/_objs/curl/vtls.pic.o:vtls.c:Curl_ssl: error: undefined reference to 'Curl_ssl_openssl'
bazel-out/k8-fastbuild/bin/external/curl/_objs/curl/vtls.pic.o:vtls.c:available_backends: error: undefined reference to 'Curl_ssl_openssl'
collect2: error: ld returned 1 exit status
```
### Feature requests: what underlying problem are you trying to solve with this feature?
Trying to build and use libcurl. 

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.
clone and build this repo: https://github.com/nicmcd/bazel_curl_testing

### What operating system are you running Bazel on?
Ubuntu 18.04.2 LTS

### What's the output of `bazel info release`?
release 0.28.1

###  Have you found anything relevant by searching the web?
I haven't found a solid example of using bazel to build and integrate libcurl. The only one seems to be tensorflow, but theirs is highly custom.

### Any other information, logs, or outputs that you want to share?
The curl.BUILD was taken from the tensorflow project. It differs only in that I removed the various OSes supported in that curl.BUILD.

**Comment by aiuto** [comment]
Your curl.BUILD looks wonky.  You are including vtls/polarssl.c instead of vtls/openssl.c

I'm closing this because it is not a bazel bug. It is actually a deeper question of how to adopt libraries that use configure and have a lot of options to work with Bazel. In this case, we should take the discussion to tensorflow or curl.haxx.se.

It is actually a problem I am interested in, as I am the principal maintainer of Google's copy of curl. We build for many platforms with various options from a single BUILD file, without shelling out to configure each time.  I would love to make that work available, but I don't have the time to turn it into a general solution that anyone could use.  If you want to discuss ideas in either of those projects feel free to include me (aiuto@google.com) in the discussion.
