### ISSUE TITLE
ProtoInfo.direct_sources contains duplicate entries when using import_prefix

### ISSUE THREAD

**Issue by aaliddell** [bazelbuild/bazel#9127]
### Description of the problem:

When using the `import_prefix` attribute on `proto_library`, the generated ProtoInfo provider contains duplicate entries for each proto file in the `direct_sources` attribute. When trying to use this provider to populate a call to protoc, this leads to passing the same proto file twice unless manual deduplication is done.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See repo at https://github.com/aaliddell/demo_import_prefix. Run `bazel build //...` and it will print the ProtoInfo provider. For me this gives:

```
struct(
    check_deps_sources = depset([<generated file _virtual_imports/proto_lib/a/b/demo.proto>, <generated file _virtual_imports/proto_lib/a/b/other.proto>]),
    direct_descriptor_set = <generated file proto_lib-descriptor-set.proto.bin>,
    direct_sources = [<generated file _virtual_imports/proto_lib/a/b/demo.proto>, <generated file _virtual_imports/proto_lib/a/b/demo.proto>, <generated file _virtual_imports/proto_lib/a/b/other.proto>, <generated file _virtual_imports/proto_lib/a/b/other.proto>],
    proto_source_root = "bazel-out/k8-fastbuild/bin/_virtual_imports/proto_lib",
    transitive_descriptor_sets = depset([<generated file proto_lib-descriptor-set.proto.bin>]),
    transitive_imports = depset([<generated file _virtual_imports/proto_lib/a/b/demo.proto>, <generated file _virtual_imports/proto_lib/a/b/other.proto>], order = "preorder"),
    transitive_proto_path = depset(["bazel-out/k8-fastbuild/bin/_virtual_imports/proto_lib"]),
    transitive_sources = depset([<generated file _virtual_imports/proto_lib/a/b/demo.proto>, <generated file _virtual_imports/proto_lib/a/b/other.proto>], order = "preorder")
)
```

As you can see, the `direct_sources` attribute contains four items for the two input proto files.

### What operating system are you running Bazel on?

Linux (Ubuntu 18.04)

### What's the output of `bazel info release`?

`release 0.28.1`

###  Have you found anything relevant by searching the web?

No. I am aware that the `proto_library` rule will be moving into an external repo for Bazel 1.0, but presently these just forward to this native implementation.

**Comment by lberki** [comment]
Good catch! This is caused by this case here: https://github.com/bazelbuild/bazel/blob/2fad01673a2c6cf6088016f5999474310065ba31/src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCommon.java#L360

I would totally go after it and debug it and fix it, except that this is only an issue if the `--incompatible_do_not_emit_buggy_external_repo_import` command line flag is unflipped, which I'm flipping literally today (see https://github.com/bazelbuild/bazel/issues/8711)

In the meantime, if de-duplicating or flipping the flag or just living with the duplicates isn't a viable option, please contact me and I'll figure something out.
