### ISSUE TITLE
//src/test/shell/bazel:namespace_runner_test fails on ci.bazel.io

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/bazel#913]
Git bisect culprit: bbe748063fa139949656fd7a8dec86ebdecddb6f
found by: `git bisect run ./output/bazel test //src/test/shell/bazel:namespace_runner_test`

**Comment by damienmg** [comment]
See http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/358/console for an example

**Comment by damienmg** [comment]
Assigning to Philip for following.

/cc @bsilver8192

**Comment by damienmg** [comment]
Also test reports: http://ci.bazel.io/job/Bazel/358/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/testReport/

**Comment by philwo** [comment]
Found the issue - the creation of the empty base file needs the directory "tmp" to exist, but we don't create it when we run the namespace-sandbox binary from the tests.

This only broke the tests, not the build, because "createImportantDirs" in LinuxSandboxedStrategy specifies the -d flag that triggers creation of the tmp directory.

Unfortunately our test suite didn't catch this before I submitted it, because it ran on a machine that didn't support sandboxing (in which case the test does nothing but still passes...).

I'll send a fix. :)
