### ISSUE TITLE
Poor error message when using local_repository with ~ in path

### ISSUE THREAD

**Issue by davidcrosby** [bazelbuild/bazel#9139]
I added this rule to my WORKSPACE file

`
local_reposity(
    name = "build_bazel_rules_nodejs",
    path = "~/rule_nodejs"
)
load("@build_bazel_rules_nodejs//:defs.bzl", "npm_install")
`
And saw this error message:
`
ERROR: error loading package '': Encountered error while reading extension file 'defs.bzl': no such package '@build_bazel_rules_nodejs//': /home/dcrosby/.cache/bazel/_bazel_dcrosby/961e3bd3eff49d294c0953b14ae9acc7/external/build_bazel_rules_nodejs must be an existing directory
`
Turns out the problem was  that `~` was not being expanded correctly.
I believe this error message can be improved, feedback is welcome.

**Comment by AustinSchuh** [comment]
A better error would have been something like:

```ERROR: local_repository "@build_bazel_rules_nodejs", directory ~/rule_nodejs does not exist``` 

It took David and I a bit of time to figure out that the ```~``` wasn't being expanded correctly.  Bazel can do better!

**Comment by laszlocsomor** [comment]
Thanks for reporting!

I managed to repro: the culprit is that Bazel does not understand `~/` as `$HOME` and treats `~/foo` as a relative path under the workspace.

The right behavior isn't obvious though:
- `~/` is a shorthand that only works in Bash, `fopen("~/foo", "wt")` fails even on Linux
- `~` is a valid directory name on every platform, and maybe the user really means `<workspace>/~/foo` (unlikely)
- using `~/` to mean the home directory is foreign to Windows, so it's unclear what's the right resolution (maybe `%USERPROFILE%`)

Because of these, I think Bazel actually did the right thing ignoring `~`.

I agree the error message is misleading. Let me try to fix that.

**Comment by laszlocsomor** [comment]
On second thought, there are also pro-arguments:
- `~/` to mean `$HOME` is probably what we _mean_, so why shouldn't bazel support it
- to mean `<workspace>/~/foo`, we can write `./~/foo`

**Comment by jin** [comment]
It would be absolutely amazing to have `repository_ctx.user_home` and `repository_ctx.path('~')` to return `System.getProperty("user.home")`.

**Comment by AustinSchuh** [comment]
I'm neutral on ```~``` working or not.  I think the bigger usability issue here is that the error message wasn't helpful enough that @davidcrosby could figure it out on his own.  Let's not lose sight of that.

**Comment by laszlocsomor** [comment]
@AustinSchuh : Agreed, I'll focus on improving the error message for now.
