### ISSUE TITLE
Cquery's Transitions output format breaks following builds

### ISSUE THREAD

**Issue by moroten** [bazelbuild/bazel#9192]
### Description of the problem / feature request:

`bazel cquery --transitions=full` affects the next bazel command. The error message in my example is `transition inputs [//:type] do not correspond to valid settings`.

The commands I run are
```
bazel shutdown  # Reset the bazel state
bazel cquery "deps(//:my_drink)" --transitions=full --noimplicit_deps  # Success
bazel cquery "deps(//:my_drink)" --transitions=full --noimplicit_deps  # Fail

bazel shutdown  # Reset the bazel state
bazel build //:my_drink  # Success
bazel build //:my_drink  # Success
bazel cquery "deps(//:my_drink)" --transitions=full --noimplicit_deps  # Success
bazel build //:my_drink  # Fail
```

(My major concern is if there are more bugs where the state, what I've been running before, affects the output.)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The example below is a modified version of https://github.com/bazelbuild/bazel/blob/master/src/test/shell/integration/starlark_configurations_test.sh

```
touch WORKSPACE


cat > BUILD.bazel <<EOF
load(":rules.bzl", "drink", "drink_attribute")
drink_attribute(name = "type", build_setting_default = "unknown")
drink(name = "my_drink", deps = [":second_drink"])
drink(name = "second_drink")
EOF


cat > rules.bzl <<EOF
BuildSettingInfo = provider(fields = ['name', 'value'])

def _build_setting_impl(ctx):
    return [BuildSettingInfo(name = ctx.attr.name, value = ctx.build_setting_value)]

drink_attribute = rule(
    implementation = _build_setting_impl,
    build_setting = config.string(flag = True),
)

def _my_transition_impl(settings, attr):
    return {
        '//:type': settings['//:type'],
    }

my_transition = transition(
    implementation = _my_transition_impl,
    inputs = ["//:type"],
    outputs = ["//:type"],
)

def _drink_impl(ctx):
    return [DefaultInfo(files = depset([]))]

drink = rule(
    implementation = _drink_impl,
    cfg = my_transition,
    attrs = {
        "deps":attr.label_list(allow_files = True),
        "_type":attr.label(default = Label("//:type")),
        "_whitelist_function_transition": attr.label(default = "@bazel_tools//tools/whitelists/function_transition_whitelist"),
    },
)
EOF
```

### What operating system are you running Bazel on?

Ubuntu Linux x86_64

### What's the output of `bazel info release`?

`release 0.28.1`

###  Have you found anything relevant by searching the web?

I've search for `transition` and `transitions` in open and closed GitHub issues and did not find anything relevant.

**Comment by katre** [comment]
This also fails if `--transitions=lite` is passed, so the error appears to lie within [`TransitionsOutputFormatterCallback`](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/query2/cquery/TransitionsOutputFormatterCallback.java;l=91).

This is pretty odd, the error seems to indicate that the output callback is actually changing the transition state somehow. Still investigating.

**Comment by katre** [comment]
Okay, debugged this a bit, there are two actual errors here:

1. In [`TransitionsOutputFormatterCallback.processOutput`](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/query2/cquery/TransitionsOutputFormatterCallback.java;l=147), the `fromOptions` object doesn't have any starlark build options set, so when the transition is executed and control passes into [`FunctionTransitionUtil.buildSettings`](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/skylark/FunctionTransitionUtil.java;l=193), the setting isn't handled, `remainingInputs` never has `//:type` removed, and the error condition is applied (throwing an `EvalException`.
2. When that exception is caught in [`StarlarkRuleTransitionProvider.FunctionPatchTransition.apply`](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/skylark/StarlarkRuleTransitionProvider.java;l=124), it is copied into the event handler for the transition, but nothing further is done. The transition then returns a copy of the input build options, and the cquery continues as if there was no error.
3. The next time a build happens (the next command), the error is discovered in the event handler, reported, and the build fails. (This happens from [`StarlarkTransition.replayEvents`](https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/skylark/StarlarkTransition.java;l=513)).

**Comment by katre** [comment]
Bumping the priority down to P2 since this only affects starlark transitions and there is a workaround (shut down bazel between calls).

Assigning to Greg to investigate when he returns.

**Comment by gregestren** [comment]
I acknowledge the importance of the outcome (non-deterministic output). Thanks for the investigation above, @katre. I'll try to take a look at options next week.

**Comment by gregestren** [comment]
I'm fairly certain this was fixed by https://github.com/bazelbuild/bazel/commit/f0a40accfbcca85262bbf2eaec8aa36d594540be, which removed the stored event handler described  in https://github.com/bazelbuild/bazel/issues/9192#issuecomment-524363684 precisely because of these non-functional effects. See the commit message for more details.

Testing the above example in my own client also shows this working now. 

You're absolutely right about the concern of stateful effects. Thank you for originally filing this and highlighting that concern.

There remains a logic bug in that `--transitions=lite` or `--transitions=full` produces an error (albeit consistently now) on a transition that reads `//:type` if you haven't explicitly included `--//:type=foo` at the command line.  The bug and fix are well understood and comment-documented here: https://github.com/bazelbuild/bazel/blob/74ae9b4160100665fbf7522d3bd63ea0c5514e7b/src/main/java/com/google/devtools/build/lib/query2/cquery/TransitionsOutputFormatterCallback.java#L149-L151

I'm going to close this issue since the crash and stateful effect concerns have been resolved. Since `--transitions` isn't the most heavily used flag, I won't open a separate bug for the logic issue until someone really needs it fixed in practice. This is to help concentrate our engineering focus and prevent a proliferation of open issues we don't have the time to fairly address. Anyone who would like to open an issue for that bug, please reference this comment.
