### ISSUE TITLE
ctx.action documentation doesn't have types for some of its arguments

### ISSUE THREAD

**Issue by endobson** [bazelbuild/bazel#921]
Most of the arguments to ctx.action have types in the docs. But executable and command do not. Command I'm fairly sure is supposed to be a string, but executable could reasonably support File or String and I cannot tell which is right before trying it out.

http://bazel.io/docs/skylark/lib/ctx.html#action

**Comment by davidzchen** [comment]
I'll take a look at this.

**Comment by davidzchen** [comment]
This is because these fields have `type = Object.class` in their `SkylarkSignature`. See [SkylarkRuleImplementationFunctions](https://github.com/bazelbuild/bazel/blob/cbbbf2e461396d3817a00c4bd4d26b9b43b68ce3/src/main/java/com/google/devtools/build/lib/rules/SkylarkRuleImplementationFunctions.java#L119), for example:

```java
      @Param(
        name = "executable",
        type = Object.class, // File or PathFragment or None
        defaultValue = "None",
        doc = "the executable file to be called by the action"
      ),
```

I can have the docgen display "Object" for now, but ideally, we should display the exact types that are allowed as described in the code comments. Should we add something like an `allowedTypes` field to the `Param` annotation?
