### ISSUE TITLE
Tensorflow build fails on 0.1.5

### ISSUE THREAD

**Issue by panmari** [bazelbuild/bazel#922]
When trying to build tensorflow with bazel 0.1.5, I get these kind of exceptions:

```
ERROR: /home/panmari/tensorflow/WORKSPACE:66:1: no such package '@six_archive//': 
Error downloading from https://pypi.python.org/packages/source/s/six/six1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55 to 
/home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/external/six_archiv
e: Error downloading https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55 to /home/panmari/.cache/bazel/_bazel_panmari/f5b407cdd255b7813aa5a26beb5d6822/external/six_archive/six-1.10.0.tar.gz: 
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced by '//external:six'.
```

Going back to bazel 0.1.4 solved the issue. I also tried `sudo update-ca-certificates -f` as recommended on stackoverflow. I'm on Ubuntu 15.10.

**Comment by damienmg** [comment]
Did you tried with bazel @HEAD?

**Comment by damienmg** [comment]
(I am suprised that 0.1.4 still compiles tensorflow btw)

**Comment by panmari** [comment]
Works on head (@cbbbf2e). Sorry for the inconvenience.

**Comment by damienmg** [comment]
No problem we fixed an issue that have that exact symptom recently. We are
going to push a new release soon.

**Comment by silinge** [comment]
Hi there, thanks for your great work. I m from China and I've tried a few times " $ bazel build -c opt tensorflow/tools/pip_package:build_pip_package " but it still got the same erorr < bzl:55:3: no such package '@six_archive//': Error downloading from https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55 to /home/william/.cache/bazel/_bazel_william/370bb719cacd674d46b6afbee5ff9055/external/six_archive: Error downloading https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55 to /home/william/.cache/bazel/_bazel_william/370bb719cacd674d46b6afbee5ff9055/external/six_archive/six-1.10.0.tar.gz: Remote host closed connection during handshake and referenced by '//external:six'.
ERROR: Loading failed; build aborted.
>.
when I use this link to download six-1.10.0.tar.gz in a chrome browser, it works well.  Since I M a new one, please forgive me for knowing nothing. Any advice would be helpful, thanks again.@damienmg

**Comment by damienmg** [comment]
The error seems a bit different here, it is correctly reported. Do you have a proxy?

**Comment by silinge** [comment]
Thanks! @damienmg I just test in both way by the using hosts(which helps us get google in China) or not, it returns to the same error. every file could be downloaded except them above the comment.  I wonder if there is a method we can download the two file and use them as local source to finsh this build task.

**Comment by damienmg** [comment]
I think bazel HEAD does contains support for proxy, pulling in @kchodorow who knows :)

**Comment by kchodorow** [comment]
It does contain proxy support (and should have better error messages).  You will have to set the environment variable HTTP_PROXY (or HTTPS_PROXY).

**Comment by silinge** [comment]
thanks @kchodorow  HTTP_PROXY maybe the hard part. :)
