### ISSUE TITLE
Build Failed - ubuntu

### ISSUE THREAD

**Issue by GhostDZ9** [bazelbuild/bazel#9268]
### Description of the problem / feature request:
When executing the following command:
`bazel build :all`

I have confirmed that all the files are in the location specified.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I receive the following error:
`Starting local Bazel server and connecting to it...
INFO: Analyzed 50 targets (43 packages loaded, 1220 targets configured).
INFO: Found 50 targets...
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/sandbox
ERROR: missing input file '@external_libs//:mysql/byte_order_generic_x86_64.h'
ERROR: missing input file '@external_libs//:mysql/little_endian.h'
ERROR: missing input file '@external_libs//:mysql/m_ctype.h'
ERROR: missing input file '@external_libs//:mysql/m_string.h'
ERROR: missing input file '@external_libs//:mysql/my_alloc.h'
ERROR: missing input file '@external_libs//:mysql/my_attribute.h'
ERROR: missing input file '@external_libs//:mysql/my_byteorder.h'
ERROR: missing input file '@external_libs//:mysql/my_compiler.h'
ERROR: missing input file '@external_libs//:mysql/my_config.h'
ERROR: missing input file '@external_libs//:mysql/my_dbug.h'
ERROR: missing input file '@external_libs//:mysql/my_dir.h'
ERROR: missing input file '@external_libs//:mysql/my_global.h'
ERROR: missing input file '@external_libs//:mysql/my_list.h'
ERROR: missing input file '@external_libs//:mysql/my_net.h'
ERROR: missing input file '@external_libs//:mysql/my_pthread.h'
ERROR: missing input file '@external_libs//:mysql/my_sys.h'
ERROR: missing input file '@external_libs//:mysql/my_valgrind.h'
ERROR: missing input file '@external_libs//:mysql/mysql.h'
ERROR: missing input file '@external_libs//:mysql/mysql_com.h'
ERROR: missing input file '@external_libs//:mysql/mysql_time.h'
ERROR: missing input file '@external_libs//:mysql/mysql_version.h'
ERROR: missing input file '@external_libs//:mysql/mysqld_error.h'
ERROR: missing input file '@external_libs//:mysql/private/violite.h'
ERROR: missing input file '@external_libs//:mysql/typelib.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/byte_order_generic_x86_64.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/little_endian.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/m_ctype.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/m_string.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_alloc.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_attribute.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_byteorder.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_compiler.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_config.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_dbug.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_dir.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_global.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_list.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_net.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_pthread.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_sys.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_valgrind.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/mysql.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/mysql_com.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/mysql_time.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/mysql_version.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/mysqld_error.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/private/violite.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/typelib.h'
ERROR: /root/.cache/bazel/_bazel_root/7a911ea801381bb402d0269290fdddd1/external/external_libs/BUILD.bazel:15:1 24 input file(s) do not exist
INFO: Elapsed time: 12.813s, Critical Path: 0.04s
INFO: 0 processes.
FAILED: Build did NOT complete successfully`

### What operating system are you running Bazel on?

ubuntu-minimal-1804-bionic-v20190814 - on a Google Cloud VM Instances - Connection via SSH

### What's the output of `bazel info release`?

release 0.28.1

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

`https://github.com/google/mysql-ripple.git
71b35f3e807b935bc1a4ac09641dd54902331034
71b35f3e807b935bc1a4ac09641dd54902331034`

**Comment by philwo** [comment]
Are you sure that these files exist on your system? Could you please run the following command and paste the full output:

```
ls -l \
    /usr/include/mysql/byte_order_generic_x86_64.h \
    /usr/include/mysql/little_endian.h \
    /usr/include/mysql/m_ctype.h \
    /usr/include/mysql/m_string.h \
    /usr/include/mysql/my_alloc.h \
    /usr/include/mysql/my_attribute.h \
    /usr/include/mysql/my_byteorder.h \
    /usr/include/mysql/my_compiler.h \
    /usr/include/mysql/my_config.h \
    /usr/include/mysql/my_dbug.h \
    /usr/include/mysql/my_dir.h \
    /usr/include/mysql/my_global.h \
    /usr/include/mysql/my_list.h \
    /usr/include/mysql/my_net.h \
    /usr/include/mysql/my_pthread.h \
    /usr/include/mysql/my_sys.h \
    /usr/include/mysql/my_valgrind.h \
    /usr/include/mysql/mysql_com.h \
    /usr/include/mysql/mysql_time.h \
    /usr/include/mysql/mysql_version.h \
    /usr/include/mysql/mysql.h \
    /usr/include/mysql/mysqld_error.h \
    /usr/include/mysql/private/violite.h \
    /usr/include/mysql/typelib.h
```

**Comment by mykolaz** [comment]
So, with Ghost, we managed to find the fix to the mysql section and it was as follows (to help others faced with this issue):
1) We are using mariadb, and we managed to find the files in 
> ~/usr/include/mariadb/server (`cd ~/usr/include/mariadb/server`)
2) went to 
> ~/mysql-ripple (`cd ~/mysql-ripple`)
 and ran 
> `grep -rl "{missing_file}" ~/mysql-ripple`  $missing_file = byte_order_generic_x86_64.h
to retrieve one file that contained this text: 
~/mysql-ripple/external_libs.BUILD.bazel

3) In the file, **'hdrs'** list, updated each **"mysql/{missing_file}"** to **"home/{user}/usr/include/mariadb/server/mysql/{missing_file}"**

After running bazel build :all - four openssl files were missing

4) Found to have ~/usr/include/openssl (aes.h, err.h, evp.h, rand.h)
After running grep -rl, found to have three files:
```
/home/{user}/mysql-ripple/my_crypt.cc
/home/{user}/mysql-ripple/external_libs.BUILD.bazel
/home/{user}/mysql-ripple/external_libs.BUILD.bazel.save
```

In the same external_libs.BUILD.bazel in the **'cc_library'** object's **'hdrs'** list performed the same action as in step 3: 
"openssl/aes.h" >> "home/{user}/usr/include/openssl/aes.h"

Updated the file with the following due to missing list and a missing comma.
List 'linkopts': `linkopts = ["lcrypto"],` >> `linkopts = ["-lcrypto",]`
includes list: `includes = ["openssl",],`

Still did not work.

`bazel version`:
**Build label: 1.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/
bazel/BazelServer_deploy.jar
Build time: Thu Oct 10 10:16:08 2019 (1570702568)
Build timestamp: 1570702568
Build timestamp as int: 1570702568**

`ls /usr/include/openssl`:
**aes.h**        cmserr.h     ec.h         modes.h       rc2.h        symhacks.h
asn1.h       comp.h       ecdh.h       obj_mac.h     rc4.h        tls1.h
asn1_mac.h   comperr.h    ecdsa.h      objects.h     rc5.h        ts.h
asn1err.h    conf.h       ecerr.h      objectserr.h  ripemd.h     tserr.h
asn1t.h      conf_api.h   engine.h     ocsp.h        rsa.h        txt_db.h
async.h      conferr.h    engineerr.h  ocsperr.h     rsaerr.h     ui.h
asyncerr.h   crypto.h     **err.h**        opensslv.h    safestack.h  uierr.h
bio.h        cryptoerr.h  **evp.h**        ossl_typ.h    seed.h       whrlpool.h
bioerr.h     ct.h         evperr.h     pem.h         sha.h        x509.h
blowfish.h   cterr.h      hmac.h       pem2.h        srp.h        x509_vfy.h
bn.h         des.h        idea.h       pemerr.h      srtp.h       x509err.h
bnerr.h      dh.h         kdf.h        pkcs12.h      ssl.h        x509v3.h
buffer.h     dherr.h      kdferr.h     pkcs12err.h   ssl2.h       x509v3err.h
buffererr.h  dsa.h        lhash.h      pkcs7.h       ssl3.h
camellia.h   dsaerr.h     md2.h        pkcs7err.h    sslerr.h
cast.h       dtls1.h      md4.h        **rand.h**        stack.h
cmac.h       e_os2.h      md5.h        rand_drbg.h   store.h
cms.h        ebcdic.h     mdc2.h       randerr.h     storeerr.h

Error output:
```
ERROR: missing input file '@external_libs//:home/{user}/usr/include/openssl/aes
.h'
ERROR: missing input file '@external_libs//:home/{user}/usr/include/openssl/err
.h'
ERROR: missing input file '@external_libs//:home/{user}/usr/include/openssl/evp
.h'
ERROR: missing input file '@external_libs//:home/{user}/usr/include/openssl/ran
d.h'
```

Any help would be appreciated

**Comment by philwo** [comment]
Sorry, we cannot help with this here. If it's still an issue, consider asking on StackOverflow or on the bazel-discuss mailing list.
