### ISSUE TITLE
Bazel on mac 10.15 fails with "“bazel-real” can’t be opened because its integrity cannot be verified."

### ISSUE THREAD

**Issue by paladox** [bazelbuild/bazel#9304]
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

When i upgraded to Mac 10.15, bazel stopped working. bazel build release fails with (“bazel-real” can’t be opened because its integrity cannot be verified.)

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

* bazel build release (in the gerrit project)

### What operating system are you running Bazel on?

Mac OSX 10.15

### What's the output of `bazel info release`?

Does not work due to "“bazel-real” can’t be opened because its integrity cannot be verified."

(I'm using the packages from https://github.com/bazelbuild/bazel/releases)

I tried upgrading to bazel 0.29, but the installer fails with the same error.

**Comment by paladox** [comment]
Work around is to do:

sudo spctl --master-disable

Which brings backs the option of "Anywhere" to Security & Privacy.

**Comment by philwo** [comment]
@paladox I can reproduce this on a test machine with macOS 10.15.

It is because of the new notarization requirement. We will have to find a way how to correctly notarize our release binaries for macOS.

As a workaround, you can download the Bazel installer or binary not using a web-browser, but using "wget" or "curl", which doesn't mark the file as "having been downloaded from the internet", so macOS will not complain:

```
curl -LO https://github.com/bazelbuild/bazel/releases/download/0.29.0/bazel-0.29.0-installer-darwin-x86_64.sh && bash bazel-0.29.0-installer-darwin-x86_64.sh
```

You could also install Bazel or Bazelisk using Homebrew, which apparently also works fine.

**Comment by paladox** [comment]
Ah thanks! I just went for the "sudo spctl --master-disable" option :)

**Comment by philwo** [comment]
I think Apple relaxed the requirements here, because I can no longer reproduce this in the final version of macOS 10.15.

Reducing priority due to this, however, we'll of course still work on notarizing our official release binaries. :)

**Comment by cmooreml** [comment]
Good article on how to enable/disable: https://www.imore.com/how-open-apps-unidentified-developers-mac

**Comment by Splaktar** [comment]
I ran into this today on macOS 10.15.2. So it doesn't look like the requirements were relaxed in a way that this isn't a problem anymore. I hit it with my installed version and then tried to install 2.0.0, hoping that would solve the problem, but it ran into the same issue and blocked the install. Using curl did workaround the issue.

It would be great if https://docs.bazel.build/versions/master/install-os-x.html#install-with-installer-mac-os-x could be updated with instructions that recommend using curl or wget to download the release so that people don't continue to run into this.

It would also be nice to support MacPorts and keep that version of Bazel up to date so that MacPorts users could have a simple way to install Bazel.

**Comment by markkolich** [comment]
`sudo spctl --master-disable` seems like an unnecessarily heavy hammer.

Clearing the Apple quarantine bit from the extracted binary worked just fine for me:

`sudo xattr -c /path/to/bazel`
`sudo xattr -c /path/to/bazelisk`

**Comment by badges7** [comment]
None
