### ISSUE TITLE
legacy_external_runfiles => incompatible_disable_legacy_external_runfiles

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel#9306]
We should rename `--legacy_external_runfiles` to `--incompatible_disable_legacy_runfiles` and roll it out as an incompatible change.

**Comment by philwo** [comment]
@meteorcloudy Is this still an issue?

**Comment by meteorcloudy** [comment]
Hmm, yeah, this never happened. --legacy_external_runfiles still exists and default to `True`.
https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java;l=425?q=legacy_external_runfiles&ss=bazel

**Comment by asuffield** [comment]
I stumbled over this and noticed that the fix @alexeagle made to rules_jvm_external would need replicating into rules_go, because https://github.com/bazelbuild/rules_go/blob/master/go/tools/bzltestutil/init.go has the same problem and all go tests break with `--nolegacy_external_runfiles`.

It's been 3 years. Are we even going to do this?

**Comment by alexeagle** [comment]
My understanding is there's a performance benefit to avoiding the extra I/O from creating the legacy layout so this is still a good idea, if unowned.

**Comment by fmeum** [comment]
This has been flipped in Bazel 8 without a rename.
