### ISSUE TITLE
Feature request: bazel to setup dependencies without actually build/link 

### ISSUE THREAD

**Issue by lizan** [bazelbuild/bazel#9578]
### Description of the problem / feature request:

Allow bazel setup symlinks, bazel-out directories, generate protobuf pb.h/cc files without do actual build / link targets.

### Feature requests: what underlying problem are you trying to solve with this feature?

We use bazel to generate compilation database and run clang-tidy, and probably more clang tools in the future in Envoy CI. I also use it for local development. To get compilation database fully working, we have to do a full build to let Bazel setup stuff like protobuf code generation, setting up virtual_includes directories, while we don't use the compiled objects / binaries in those scenario. While RBE shorten the time for full build this is still waste of time and/or disk.

**Comment by jin** [comment]
Does the compilation database need the full set of outputs from the build? Or is it a subset? If it's a subset, it sounds like aspects + custom output groups may be the principled solution here.

**Comment by aiuto** [comment]
I don't know what this request means.
- it could be: a mode to just run protoc and generate .c/.h files
- a mode to do the full build, but just stop at cc_library targets and not do those.
- a mode to never call compilers, but to do everything else.

But all of these are not simple at all, because you might have to build a code generator like protoc by compiling things.  Basically, any time the build graph gets more complex than "spec file -> .c" it falls down. Can you come up with a more generalized proposal for what you would expect?

**Comment by lizan** [comment]
@aiuto Close to "a mode to never call compilers, but to do everything else", except host configuration. 

@jin For tools against compilation database work, it basically needs all input to the compiler, no need any input to the linker however. This includes:
1. generated pb.h
2. all includes directory (including external dep, _virtual_includes that cc_library generates)

With bazel query, get 1 is not that hard (not trivial though), 2 without running full build is hard.

**Comment by aiuto** [comment]
I don't see how this is possible. It still sounds like 
- do everything you need to generate all sources needed for your build
- but don't actually run any compilation steps

This is, in general, not possible, because you often need to build tools just to generate output. We could have something that says "don't run the linker step of cc_binary" targets, but then how would we build protoc? So now it would have to be 'don't link cc_binary targets that are in the target configuarion".  This would be a never ending chain of special cases.

**Comment by lizan** [comment]
> This is, in general, not possible, because you often need to build tools just to generate output. We could have something that says "don't run the linker step of cc_binary" targets, but then how would we build protoc? So now it would have to be 'don't link cc_binary targets that are in the target configuarion". This would be a never ending chain of special cases.

This is not a never ending chain of special cases, I do need tools under host configuration built, that's not the argument here. I am asking a mode that do everything before CppCompile in specified targets, and this is because bazel sets up virtual_includes and other path manipulations. Alternatively, adding native support on clang tools (based on compilation db) is also fine.

A possible workaround is adding an unknown compiler option to fail compilation fast enough, and pass `-k` to let bazel do as much as possible.

**Comment by htuch** [comment]
I think this is generally useful to anyone developing Clang libtooling based tools. I'm working on right now, and it needs to be able to reach at various headers that were gathered during compilation database creation and live in the Bazel cache.

**Comment by jpeach** [comment]
> Alternatively, adding native support on clang tools (based on compilation db) is also fine.

This would be amazing. As a novice Bazel user, getting a working compilation DB in envoy was a pretty frustrating experience and it's really needed nowadays for productive code navigation.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
