### ISSUE TITLE
windows_cc_toolchain_config: don't force a c++ standard in gcc toolchain by default (rely on compiler defaults instead)

### ISSUE THREAD

**Issue by oakad** [bazelbuild/bazel#9870]
When compiling with gcc on windows (mingw) bazel default toolchain configuration forces an `-std=gnu++0x` flag on compiler invocation.

However, no language standard version is forced on "msvc-cl", which defaults to a certain post c++11 standard by default (depending on the `cl.exe` version pulled into path). 

This is a weird and baffling mismatch, easy to work around with `.bazelrc`, but still annoying.

I believe that the `-std=gnu++0x` flag should be removed from the `windows_cc_toolchain_config.bzl` for consistency with other toolchains and platforms, allowing gcc to perform in accordance with its spec file by default.

**Comment by laszlocsomor** [comment]
Thanks for reporting that! I see the same behavior on Windows: `--compiler=mingw-gcc` passes `-std=g++0x` but `--compiler=msvc-cl` does not.

But it's more inconsistent: on Linux, Bazel uses `-std=c++0x` but on macOS it's `-std=c++11`.

I don't know why that is, or if it's intentional. Looping in the C++ team to comment: @hlopko, @scentini , @oquenchil

**Comment by scentini** [comment]
I don't think it's intentional, however fixing this is an incompatible change. We are planning to move the autoconfiguration mechanism to [@rules_cc](https://github.com/bazelbuild/rules_cc), and we will fix this once it's there.

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
