### ISSUE TITLE
Add number of processors as a make variable

### ISSUE THREAD

**Issue by kayasoze** [bazelbuild/bazel#988]
It would be nice if Bazel could compute the number of cores it is configured to use and make that available as a make variable.  I have a number of Makefile based genrules which make use of make's `-j`, but the optimal value of `-j` varies from host to host.  In particular, a high value of `-j` can massively slow build times by unnecessarily paging to swap.  Querying the number of processors in a cross platform way is rather involved, and/or requires Python as a dependency.

**Comment by kchodorow** [comment]
To clarify, you have BUILD files with genrules that call `make -j whatever`?

**Comment by kayasoze** [comment]
> To clarify, you have BUILD files with genrules that call make -j whatever?

Exactly.

**Comment by kchodorow** [comment]
On the one hand, we're trying to help people convert their builds to Bazel (which adding # cores would do). On the other hand, we probably don't want people to use number of cores in Bazel-executed build rules (that's something Bazel should figure out for the user), so I'm reluctant to add a feature for it (because it encourages bad rule construction for things that aren't shelling out to other build systems).

That said, we have a couple of proposals circulating about exposing environment variables to Bazel and adding ./configure-like functionality, so one or both of those things might help with this in the next couple of months.

**Comment by kayasoze** [comment]
If it makes any difference, it would be just as useful (if not more useful) if Bazel could pass along its own notion of the number of processors available.  It needn't correspond to the actual number of physical processors, such as when `--local_resources` has been specified.

**Comment by kchodorow** [comment]
That is probably more do-able.

**Comment by helenalt** [comment]
@gregestren Is this something that you would consider implementing or close this issue?

**Comment by jmmv** [comment]
Just stumbled upon this bug by chance.

How does passing `-j N` to `make` from within a rule behave though? Bazel itself may already be using N jobs so telling `make` to use N as well will result in machine overload -- and I don't think there is a way you can control that unless your make-based build is in the critical path of every single target.

Worse: if your target happens to be built remotely, the number of local processors has no relation to the processors available remotely, so passing this information to the rule would be wrong.

If you are constructing a command line to run make, you can query the number of processors yourself and make whatever decisions you need there. Mind you, this would work fine in the remote execution case because the whole command line would run remotely and would discover the right number of remote processors.

So: I don't think Bazel should expose this as a built-in variable because it seems to address a corner case, and it seems to do so incorrectly.

The real answer here, I think, is: if we add first-class support for external build systems behind predefined rules, this would be handled transparently and you wouldn't have to worry about it.

**Comment by dslomov** [comment]
сс @irengrig

**Comment by sgowroji** [comment]
Hi there! We're doing a clean up of old issues and will be closing this one. Please reopen if you’d like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.
