### ISSUE TITLE
Bazel test messing up system time

### ISSUE THREAD

**Issue by nicmcd** [bazelbuild/bazel#9970]
### Description of the problem / feature request:
When using python (tested with 3.6.8 and 2.7.15+), running a test versus a binary yield different system times when run using bazel (bazel run <target>).

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here is the BUILD file:
```
py_test(
    name = "date_test",
    srcs = [
        "date_test.py",
    ],
    python_version = 'PY3',
)
py_binary(
    name = "date_print",
    srcs = [
        "date_print.py",
    ],
    python_version = 'PY3',
)
```
Here is the test code:
```
import datetime
import unittest
class DateTest(unittest.TestCase):
  def test_date(self):
    now = datetime.datetime.now()
    print(now)
if __name__ == '__main__':
  unittest.main()
```
Here is the binary code:
```
import datetime
now = datetime.datetime.now()
print(now)
```

If I run the code directly without bazel:
```
nic@quasar:~/dev/bazel_test_date$ python3 date_print.py && python3 date_test.py
2019-10-07 23:49:03.940868
2019-10-07 23:49:04.217462
```
Everything is good.

If I manually run the bazel generated files:
```
nic@quasar:~/dev/bazel_test_date$ bazel-bin/date_print && bazel-bin/date_test
2019-10-07 23:49:18.177063
2019-10-07 23:49:18.715331
```
Everything is good.

However, if I run it under using bazel, the problem is shown:
```
nic@quasar:~/dev/bazel_test_date$ bazel run :date_print && bazel run :date_test
2019-10-07 23:50:01.700563
2019-10-08 06:50:03.489103
```
The dates are WAY off. The date_print is right, the date_test is 1/4 day in the future.

### What operating system are you running Bazel on?
Ubuntu 18.04.3 LTS
Python 3.6.8 and Python 2.7.15+

### What's the output of `bazel info release`?
release 0.29.0

**Comment by nicmcd** [comment]
https://github.com/nicmcd/bazel_python_date_problem

**Comment by benjaminp** [comment]
`bazel test` [sets `TZ=UTC`](https://docs.bazel.build/versions/master/test-encyclopedia.html#initial-conditions), which probably accounts for the difference.

**Comment by alex-xnor** [comment]
Right, I think this behavior is intentional. Bazel tries to make test execution hermetic, and so it intentionally ignores your system's usual timezone and forces it to UTC while running tests.

**Comment by nicmcd** [comment]
While I get the idea of being hermetic, this removes any ability for bazel to be able to test system time APIs. For example, assume I make a binary that prints out the current systime. If I create a bazel test application in Python to drive the binary an inspect its output, I won't be able to check its validity. 

Any thoughts? Any test using system time is not hermetic regardless of the timezone, right?

**Comment by alex-xnor** [comment]
You can check it in two ways:

1. Change your test code that runs inside of Bazel to explicitly set a non-UTC time zone before beginning the test. Then it can match your unmodified outside-of-Bazel code.
2. Modify your outside-of-Bazel code to set the time zone to UTC. Then it can match Bazel's test environment.

I think you are right that using the system time at all is not hermetic, but complete hermeticity is difficult to achieve. That does not mean it is not worth striving for, so even if it is not perfect, Bazel tries to control what it can. The time zone is easy to control for, so Bazel does so.

**Comment by hlopko** [comment]
I guess this is 'won't fix' for the mentioned reasons. Please complain loudly if you disagree :)

**Comment by nicmcd** [comment]
In this case it seems like the TZ should not be set. I would like to know of reasons why it should be set to give better judgement. In the spirit of hermeticity (did I just make that word up?), it seems to me that a bazel user would understand that calling a library that relies on the TZ variable would return something timezone aware. Thus the user should pre-set the TZ variable or check what the system currently believes is the timezone. On the other hand, a user that doesn't know a library uses the TZ variable will come to github complaining (like I did). 

In the end, I don't see a reason the TZ variable should be set. It doesn't add hermetic value but only removes the tests users can write. Thoughts?

**Comment by alex-xnor** [comment]
Here are two reasons you might want Bazel to fix TZ:

* One of the reasons you might want hermeticity is to ensure you don't have cases of "works on my machine" -- ideally, if a test fails for one person, it also fails for everyone else, and if it succeeds for one person, it succeeds for everyone else -- ideally there would not be any skew there. If TZ is allowed to vary between systems, if someone encodes an assumption of one particular TZ in their test, then someone in a different time zone running their test (or maybe the same person later on, if daylight savings time goes into effect!) might see a different result.

* If you are using a [remote cache](https://docs.bazel.build/versions/1.0.0/remote-caching.html), then any (ideally) any environmental differences that could affect the test's execution should be encoded in the cache key. If TZ varies with the client's environment rather than being fixed to a particular value, less people will be able to share the same cached result, so you may end up needing to do more work, and the cache will need to store more data, even for tests where TZ does not affect the result, because Bazel cannot know whether the test depends on TZ or not.

**Comment by nicmcd** [comment]
By the same logic couldn't you say that the clock should be frozen?

**Comment by alex-xnor** [comment]
I personally think it would make a lot of sense to freeze the clock, if it could reasonably be done. I'm not sure there's a good way for Bazel to do that, though. I'm not aware of a way to do it in Linux other than ptracing the child (performance penalty and possibly changes behavior if the children themselves use ptrace) or using something like libfaketime (doesn't work with statically-linked targets), and I'm not sure what the landscape looks like on other platforms. So again it seems like Bazel will try to control what it reasonably can, but there are limits to what it can control; in those cases, it just does its best. But just because it is not perfect does not mean we should not try to control those things that we easily can.

**Comment by nicmcd** [comment]
I'm not saying give up. I'm trying to say that there are things we can reasonably set up for hermetic tests, and there are things that we can't and shouldn't. For example, having a frozen clock might be great for some tests, but it would completely remove the ability to test code that has timeouts. Why should users have to fight this?

My opinion is that users should not have to guess about what Bazel and the libraries being tested are doing underneath the hood. The reason I don't like the TZ=UTC setting is that I just don't know when that gets paid attention to. I don't want to have to fight to undo Bazel's poor attempt at hermeticity. I'd rather fight to guarantee hermeticity. For example, if I have a hard coded test result that is based on UTC, then I'd better guarantee that my test environment believes it is UTC. If not, then I'd make my expected result according to whatever timezone my machine thinks it is.
